#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXkXlXkXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXkXlXkXlXkXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXkXlXkXlXlX",
"lXlXkXlXkXlXNXCXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXCXMXkXkXlXjXzXNXCXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXVXnXkXkXlXlXlX",
"lXlXlXkXzXzXv.N j k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k h D K.bXlXjXcXdXr.v j k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k h Y `.mXjXkXlXlX",
"lXlXkXjXnX3.  X                                                                         .   v.mXjXzX)   X                                                                           + Q.mXjXlXlX",
"lXlXjXbX9X;   X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X   i hXVX X  . X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X o   G CXhXlXlX",
"lXlXjXnX4X                . X X                                           . X .             > fXAX).  o               . X X .                                   . X X .           X   k ZXhXlXlX",
"lXlXjXnX4X                                                              .                   , fXZX).  o           . .                                                             X   k ZXhXlXlX",
"lXlXjXnX4X              O 8 h x ,                                         t c y             > fXAX).  o             . q g u -                                 . 1 d c 0           X   k ZXhXlXlX",
"lXlXjXnX4X          X   &.UXKXUX%.  .                               .   r xXUX&X            > fXAX).  o           = m.DXPXUXJ.                            .   c bXLXUXL.          X   k ZXhXlXlX",
"lXlXjXnX4X          .   ' j.`.UXo.  .                               .   Y.UXUXXX            > fXAX).  o       X   z.UXJ.t K o.O                           .   x c.m.UXF.          X   k ZXhXlXlX",
"lXlXjXnX4X                  m.UXo.  .                             X   / HXt.UXOX            > fXAX).  o     X   e nXjXA W h                                   X   ' UXG.          X   k ZXhXlXlX",
"lXlXjXnX4X              .   C.UXo.  .                               = nXm.k UXoX            > fXAX).  o     X   M UXZXMXUXPXs.                                X   | UXG.          X   k ZXhXlXlX",
"lXlXjXnX4X              .   C.UX+.  X                           X   N.aX$ v UX.X            > fXAX).  o     X   B UXKXX.p mXUXd   .                           X   | UXH.  .       X   k ZXhXlXlX",
"lXlXjXnX4X                  m.UX}   .                         .   & 5XVX~.1XUXZXA.:   .     > fXAX).  o     X   f LXlX1   OXUXF   .                           X   ' UXA.          X   k ZXhXlXlX",
"lXlXjXnX4X              7 B Q.UXi.b ;                         .   $ Y.gXfXzXKXPXoX<   .     > fXAX).  o         . ].UX*.B FXnX4                               - x r.UX(.V 0   .   X   k ZXhXlXlX",
"lXlXjXnX4X          o   8.UXJXUXKXUXZ   X                             .   x UX#X            > fXAX).  o       .   g =XUXUXgX~   .                         .   N UXPXIXHXUXp.  O   X   k ZXhXlXlX",
"lXlXjXnX4X              5 M b m b m *                               X o   ; V s .           > fXAX).  o             - k c 3                                   & n b m b N 7       X   k ZXhXlXlX",
"lXlXjXnX4X                                                                                  , fXZX).  o           X         .                                                     X   k ZXhXlXlX",
"lXlXjXnX4X              . X X X X X                                         X .             > fXAX).  o             . X X .                                     X X X X X .       X   k ZXhXlXlX",
"lXlXjXbX9X-   X . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . X X   u hXVX X  . X . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . X o   F CXhXlXlX",
"lXlXkXjXnX1.  X                                                                         .   z.mXjXlX/   X                                                                           O E.mXjXlXlX",
"lXlXlXkXxXkXz.b a s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s p C F.vXlXjXcXaXq.k a s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s p L /.mXkXkXlXlX",
"lXlXkXlXkXzXMXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXMXkXkXlXjXxXNXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXNXmXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXkXkXlXlXlX",
"lXlXlXkXlXkXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXkXlXkXlXkXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXgXjXCXSXSXSXSXSXSXSXSXSXSXSXSXSXSXCXjXjXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnXfXI.m.M.M.M.M.M.M.M.M.M.M.M.M.m.U.hXbXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX8XS X                             o H qXcXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXNXO.  o O O O O O O O O O O O O O O o   &.BXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   X                             X   k CXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXkXjXgXgXhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXgXgXgXhXkXlXkXlXlXlXlXlXhXBXs   .             X o o X         X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXkXNXDXFXVXzXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXlXCXSXVXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXBXFXGXSXBXzXkXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXzXxXm.N k 9.pXcXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlX{ s @.xXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXhXf.m d C r.iXxXjXlXlXlXlXlXhXBXs   .       .   > e.1X8XD.7   .   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXjXMXy.  9 h   / lXlXkXlXlXlXlXlXlXlXlXlXlXlXkXkXgXCXl.    m xXlXkXlXlXlXlXlXlXlXlXlXlXlXjXxXyXU d C =   =.nXjXkXlXlXlXlXhXBXs   .         * *XUX-X{.>XN   X   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXvXeX2   ;XcXi   {.BXhXkXlXlXlXlXlXlXlXlXlXlXkXjXnX1X9 D   S xXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXgX7XCXUXp.  J hXzXkXlXlXlXlXhXBXs   .     X   >.UXj.    o #       X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXmXoX  r fXVX~   z.MXjXkXlXlXlXlXlXlXlXlXlXkXkXjXNXE c ~.  Z zXkXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXnX|.Y.F = Y.mXjXkXlXlXlXlXhXBXs   .     X   oXUX`.kXkX>.        X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXmX^.  d iXnX`   y.mXjXkXlXlXlXlXlXlXlXlXlXlXhXVXF.@ OX=X  F BXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXhXbXi     r .XbXjXkXlXlXlXlXhXBXs   .     X   3XUXlXt.wXUX#.  o   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXnX@X  q gXZXW   b.NXjXkXlXlXlXlXlXlXlXlXlXkXlXlXx j  Xu.  g ].dXzXkXlXlXlXlXlXlXlXlXlXlXlXkXcXBX8X<X5.  b sXzXkXlXlXlXlXhXBXs   .     X   @XUX8.  ;.UXH.  .   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXcXyXq    XiX8   oXNXhXkXlXlXlXlXlXlXlXlXlXjXxXyXj   X   @   y 4XbXjXlXlXlXlXlXlXlXlXlXlXkXvX0X[.vXJXG.  8 tXcXkXlXlXlXlXhXBXs   .     X   y.UXx.  8.UXc.  o   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXhXMXn.  & >   %.vXkXkXlXlXlXlXlXlXlXlXlXlXkXlXjXOX/.XXj.  i OXfXlXkXlXlXlXlXlXlXlXlXlXlXhXVX{.. 9 9 +   6.bXjXkXlXlXlXlXhXBXs   .     .   5 rXUX6XFXcXc   X   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXbXE.' Q n.kXzXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXBXCXGX3XK e.CXlXkXlXlXlXlXlXlXlXlXlXlXlXkXcXrXt.( U X.I.zXzXkXlXlXlXlXlXhXBXs   .       .   8 f.].c.s   .     X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXjXMXJXKXCXkXkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXkXhXhXgXxXLXAXhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXxXSXJXLXHXNXkXkXlXkXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXlXhXfXfXhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXdXgXlXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXfXfXhXkXlXkXlXlXlXlXlXhXBXs   .           . O + O .         X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXlXjXgXgXhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXgXgXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXgXgXgXhXkXlXkXlXlXlXlXlXhXBXs   .         . O O O O o         X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXjXvXSXDXmXjXlXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXzXVXSXDXZXzXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXmXAXDXSXnXjXlXlXkXlXlXlXlXhXBXs   .                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXjXMX8XP.G.=XmXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXpX{.J.F.~.aXvXkXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkX:XY.F.L.>XnXkXkXlXlXlXlXlXhXBXs   .         9 ] _ _ ] U o       X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXhXmX Xy     : V.MXhXkXlXlXlXlXlXlXlXlXlXlXlXjXMXE.@       D wXxXkXlXlXlXlXlXlXlXlXlXlXlXjXzXpXS   o   > J.mXjXkXlXlXlXlXhXBXs   .     .   [ UXPXLXUXtX*   .   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXzXgXC   z.(.@ < 1XnXjXlXlXlXlXlXlXlXlXlXlXlXjXbX@XB.>X~.9   B.VXhXlXlXlXlXlXlXlXlXlXlXlXkXxXpXZ.`.2X]   K hXzXkXlXlXlXlXhXBXs   .     .   ! UX%., a f X       X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXnX;X  4 gXFXL   F.BXhXkXlXlXlXlXlXlXlXlXlXlXlXkXcXVXPXrXs @ |.nXjXlXlXlXlXlXlXlXlXlXlXlXlXkXlXMXFXJX8.  -.bXkXkXlXlXlXlXhXBXs   .     .   ( UX/.f.;.<         X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXmX(.  s aXnX`   u.MXjXkXlXlXlXlXlXlXlXlXlXlXkXhXBX[.& %   0.BXjXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXnXD @   x 0XbXjXlXlXlXlXlXhXBXs   .     .   ` AXvXKXUX3X5   .   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXmX].  i aXmX)   s.MXjXkXlXlXlXlXlXlXlXlXlXlXlXjXmX:X| Q = & /.MXjXlXlXlXlXlXlXlXlXlXlXlXlXkXkXbXr.' g   +.xXkXkXlXlXlXlXhXBXs   .         8 k   5 >XUX-.  O   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXjXbX4XX = uXDXm   R.BXhXkXlXlXlXlXlXlXlXlXlXlXkXlXhXNXUXIX{   =.FXfXlXlXlXlXlXlXlXlXlXlXlXkXlXjXzXKXUX'.  3 rXcXkXlXlXlXlXhXBXs   .         O   o   J.UX0.  +   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXkXcX]   ' 2.  k tXcXjXlXlXlXlXlXlXlXlXlXlXlXgXSX<.` l.6.3   B.VXhXlXlXlXlXlXlXlXlXlXlXlXhXBXXXD y.j.D   K hXlXkXlXlXlXlXhXBXs   .     X   E.)...v.KXDXD   o   X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXjXvXqX_ +   V @XmXhXlXlXlXlXlXlXlXlXlXlXlXlXgXZXt.#     w u.jXkXkXlXlXlXlXlXlXlXlXlXlXlXjXmX:Xu .   * Q ;XbXjXkXlXlXlXlXhXBXs   .     .   $.gXUXPXqX{   .     X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXjXvXxXrXeXjXnXjXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXkXpXrXeXpXMXzXkXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXfXtXeXtXxXnXkXlXlXlXlXlXlXhXBXs   .           + - > $           X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXjXkXvXvXlXjXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcXvXvXxXjXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXvXvXvXkXjXlXkXkXlXlXlXlXhXBXs   .                   X         X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXlXkXlXlXlXlXlXhXBXs   X                             X   k ZXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXP   o o o o o o o o o o o o o o o o   R VXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXjXnX{.>                                 < .XbXjXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbXMXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXlXkXzXMXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXMXxXkXjXmX*X@.U T Y Y Y Y Y Y Y Y Y Y T U $.-XmXjXkXlXlX",
"lXkXlXhXdXfXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXgXkXlXjXvX%X/.`._._._._._._._._._._._._._._.`.).[.jXcXtX/.`._._._._._._._._._._._._._._._.`.^.8XvXkXjXbXDXHXHXHXHXHXHXHXHXHXHXHXHXHXHXDXvXjXlXlXlXlX",
"lXlXjXBXPXJXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXZXkXkXjXbX XJ.Y.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.I.W.jXvXwXK.Y.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.T.H.3XbXjXlXjXgXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXjXlXkXkXlXlX",
"lXhXVXQ.+.1.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.C.lXxXkXkXvXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXbXlXkXzXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                                   W gXlXkXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXJX8.  % O O O O O O O O O O O O O O O + X   v.SXgXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                                 +   >.KXdXlXlXlXlXlXlXlXlXlXlXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                 .               O   >.KXdXlXlXlXlXlXlXlXkXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXkXlXkXjXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                                 O   >.KXdXlXlXlXlXlXlXkXlXkXzXcXzXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXnXmXnXcXmXxXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXxXMXvXzXlXkXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O             X   T bXvX`   o     O   >.KXdXlXlXlXlXlXlXlXkXzXsXZ $ W xXkXkXlXlXlXlXlXlXlXlXlXlXlXkXxXyX:.e & u 3.uXcXjXlXlXlXlXlXlXlXlXlXlXlXlXkXvX;XG 5 $ %.xXkXkXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O               ; 0XUXUX+.  O     O   >.KXdXlXlXlXlXlXkXkXgXCX7.    B xXkXkXlXlXlXlXlXlXlXlXlXlXlXhXNX$X6 R $.2   *.nXjXkXlXlXlXlXlXlXlXlXlXlXlXjXmX_.l N   ' xXkXkXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O           o   M.eXoXUX|   O     O   >.KXdXlXlXlXlXkXlXhXMX+X; (   A xXkXkXlXlXlXlXlXlXlXlXlXlXlXkXxXuX>XvXKXv.  v sXxXkXlXlXlXlXlXlXlXlXlXlXlXkXlXaXxXD.  [ cXkXkXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O         o   C LX! B.UX|   o     O   >.KXdXlXlXlXlXlXkXlXvXn K '.  Z lXkXkXkXlXlXlXlXlXlXlXlXlXlXlXkXzXbXfXZX0.  #.bXkXkXlXlXlXlXlXlXlXlXlXlXlXlXkXkXCXN.  [ cXkXkXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O           O <X(.  K.UX]   O     O   >.KXdXlXlXlXlXkXhXCXf.= 6X*X  G VXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXjXhXVXN.  i 5XbXjXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXMXB.  [ xXkXkXkXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O       .   K UXv...2XUXT.j       O   >.KXdXlXlXlXlXkXlXgXk i V.#.  e C.pXzXkXlXlXlXlXlXlXlXlXlXlXlXkXzXmXy.  N 8XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXVXV.  [ vXlXkXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O       .   Q UXIXUXKXFXUXs.  .   O   >.KXdXlXlXlXlXjXzXiXl   X   #   u 5XvXjXlXlXlXlXlXlXlXlXlXlXkXlXjX3.  b %X8X4XkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXhXbXB.  } jXhXlXkXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O           # 7 6 % !.UX4.  o     O   >.KXdXlXlXlXlXkXlXkX0X3XuXP.  j eXjXlXkXlXlXlXlXlXlXlXlXlXlXhXNX#X$   o X   t uXcXkXlXlXlXlXlXlXlXlXlXlXlXjXmX{.  .   O   3.GXfXkXlXlXlXlXlXlXlX",
"lXfXKX5.  O               X   W j.g   .     O   >.KXdXlXlXlXlXlXkXlXvXbXBX7X>.V.nXlXkXlXlXlXlXlXlXlXlXlXlXlXkXvXqXy.7.4.2.1.d.fXzXkXlXlXlXlXlXlXlXlXlXlXlXkXcX3X,.4.8.8.&.!.NXhXkXlXlXlXlXlXlXlX",
"lXfXKX5.  O             . .                 O   >.KXdXlXlXlXlXkXlXkXkXkXjXcXLXSXjXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXcXHXKXKXKXLXGXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXLXKXJXJXPXVXjXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                   o + .         O   >.KXdXlXlXlXlXlXlXlXlXkXlXjXdXgXlXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXkXfXdXfXfXdXfXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXjXdXfXfXfXdXhXlXkXlXlXlXlXlXlXlXlX",
"lXfXKX5.  +                                 +   3.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXJX6.  +                               .   = {.MXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXfXKX5.  O                                 g J.mXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXxXyX1X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4XiXBXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXkXcXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXxXhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXkXkXlXjXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXkXlXkXkXlXhXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXhXkXlXkXlXlX",
"lXlXlXlXlXjXnXHXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXZXlXkXlXkXjXNXHXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXVXjXkXlXkXlX",
"lXlXlXkXkXMXOX3.-.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.=.m.jXcXjXlXmX!.>.-.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.I.bXlXkXlXlX",
"lXlXkXjXMXP.%                                                                   .   Q hXjXmXu.  .                                                                 .   1.nXjXkXlX",
"lXlXkXkXvXc   + O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O + X   I.GX7X<   O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O   $ :XmXjXlX",
"lXlXkXkXxX8   .         X O + X                                     X + o         O   N.PX<X                o O O X                               X O + o           X   +XBXhXlX",
"lXlXkXkXxX9   .                                                                   O   N.PX<X              .                                                         .   @XNXhXlX",
"lXlXkXkXxX8   .       . V *.6.V                                 .   n 9.`         O   N.PX<X              . D 5.,.x                               g @.6.!           X   +XBXhXlX",
"lXlXkXkXxX8   .       1 yXLXUXx.  .                           .   > 5XUX6Xo       O   N.PX<X              N.UXNXSXT.                              ].UXUXXXo         X   +XBXhXlX",
"lXlXkXkXxX8   .       & k [ UXf.  .                           X   c.yXVX>X.       O   N.PX<X        X   ^ UXg.  O 6 X                           X j S MX X          X   +XBXhXlX",
"lXlXkXkXxX8   .       X   T UXh.  .                         X   S mX~ zX7XX       O   N.PX<X        o   I.UXQ.iXXXj   .                         X   t SXOX          X   +XBXhXlX",
"lXlXkXkXxX8   .       X   W UXh.  X                           o <Xx.  SX2X        O   N.PX<X        O   ].UX4Xq.GXgX:                           X   p SXOX.         X   +XBXhXlX",
"lXlXkXkXxX8   .       X   Y UXd.  X                       X   U UXs.q.HXcXo.+     O   N.PX<X        o   P.UX'   Q.UXn   .                       X   r SXXX          X   +XBXhXlX",
"lXlXkXkXxX8   .       o , o.UXN.5 $                       X   Y BXGXLXHXUX1X-   . O   N.PX<X        X   ` UXb.: qXFX6   .                         : S ZX$Xr =       X   +XBXhXlX",
"lXlXkXkXxX8   .       - kXUXPXKXUXZ   X                         X   ; ZX0X.       O   N.PX<X            X m.PXUXNX+.  .                       .   .XUXKXJXUX4.  O   X   +XBXhXlX",
"lXlXkXkXxX8   .       X c B m m C =                                 X b h         O   N.PX<X              o a B 8   .                             s C m m Z 6       .   +XBXhXlX",
"lXlXkXkXxX8   .                                                                   O   N.PX<X              .       .                                                 .   @XBXhXlX",
"lXlXkXkXxX9   .         X X X X X                                     X X         +   N.PX<X  .             X X .                                 X X X X o .       o   +XBXhXlX",
"lXlXkXjXnXL   O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O   o ).AXeXi   O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O   5 5XbXjXlX",
"lXlXkXjXnX@Xf                                                                     $ 7.bXgXMXU.6                                                                     < V.MXhXkXlX",
"lXlXlXlXjXMXtXY.H.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.H.oXMXlXkXjXBX3XL.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.H.G.G.G.G.G.G.G.G.G.G.H.G.H.;XBXjXlXlXlX",
"lXlXlXkXlXhXxXAXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXNXhXkXlXlXhXbXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXAXAXLXIXPXPXPXPXPXPXPXPXPXPXPXPXNXfXlXkXkXlX",
"lXlXlXlXkXlXjXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXhXkXlXkXkXlXjXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXfXkXcX,X&X&X&X&X&X&X&X&X&X&X&X&X&XuXNXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX*.*                           j `.MXhXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXCXa.  . . . . . . . . . . . . . X   a eXcXjXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXlXkXlXlXlXlXfXFXU   O                           o   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXhXxXvXzXhXlXkXkXlXlXlXlXlXlXlXlXlXlXlXkXlXkXlXvXcXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXlXxXcXcXlXjXlXkXkXlXlXlXfXFXU   o         . .               X   @XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXkXkXMXdXyXjXmXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXjXwXyXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXfXiXyXkXnXkXlXlXlXlXlXfXFXU   o             $ * o         .   @XBXhXlX",
"lXlXlXlXlXlXlXlXkXlXjXmXM.7   g `.mXjXkXlXlXlXlXlXlXlXlXlXlXkXkXjXMX[   B jXlXkXlXlXlXlXlXlXlXlXlXlXjXmXW.2   O M XXnXjXkXlXlXlXfXGXU   o         , D.GXUXwXu   .   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXhXNX].  n B.1 7 0XbXjXlXlXlXlXlXlXlXlXlXkXlXgXZXH..   z jXlXkXlXlXlXlXlXlXlXlXlXlXjXmX^.5.Y.}   R xXkXkXlXlXlXfXGXU   o         R.UX;.h -.p   .   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXgXFX>.  D.UX#.  L.VXhXkXlXlXlXlXlXlXlXlXlXjXcXuX6 $.3 f jXlXkXkXlXlXlXlXlXlXlXlXlXlXkXxXAXUXP.  +.nXjXkXlXlXlXfXGXU   o   X   k UX X/ @.7         X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXjXMX`   I.PX6.  s.BXhXkXlXlXlXlXlXlXlXlXkXhXZX..h aX* h xXzXkXlXlXlXlXlXlXlXlXlXlXkXgXZXn.X   e <XmXhXlXlXlXlXfXGXU   o   o   Y UXZXdXJXxXx   X   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXhXVX .  U.UX3.  z.BXhXkXlXlXlXlXlXlXlXlXjXmXoX# L.5X@ s qXkXkXkXlXlXlXlXlXlXlXlXlXlXhXZX#X0.`   ^ xXkXkXlXlXlXfXGXU   o   o   L UX5X  } UXg.  X   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXgXFXa.  y.UXY   ].BXhXlXlXlXlXlXlXlXlXlXhXNXD.  X   @   g tXcXjXlXlXlXlXlXlXlXlXlXkXxX1XzXUX3X# 3 pXxXkXlXlXlXfXGXU   o   X   p JX-X  ! UXh.  X   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXxX0Xs . f   Q lXlXkXlXlXlXlXlXlXlXlXlXkXcX4XV.V.l.# , P.gXlXkXlXlXlXlXlXlXlXlXlXgXSX( 5 m 3   *.bXjXkXlXlXlXfXGXU   o     .   b.UX@XfXSXb   X   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXjXnX5X,.T p.sXcXjXlXlXlXlXlXlXlXlXlXlXlXkXbXDXHXMX| 6.ZXzXkXlXlXlXlXlXlXlXlXlXlXjXnX~. .T ] Z.jXzXkXlXlXlXlXfXGXU   o         X @.(.C.k   .     X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXlXjXcXFXLXAXzXkXlXkXlXlXlXlXlXlXlXlXlXkXlXjXgXfXhXGXAXgXkXlXkXlXlXlXlXlXlXlXlXlXlXkXMXJXLXJXVXlXkXlXkXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXkXgXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXjXgXfXfXhXkXlXkXlXlXlXlXfXGXU   o           o O O .         X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXkXgXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXkXkXlXhXfXfXfXjXlXkXkXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXfXhXkXlXkXlXlXlXlXfXGXU   o         o + O + O         X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXlXjXcXFXLXAXlXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXBXKXLXGXmXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXvXGXLXJXCXzXkXlXkXlXlXlXfXGXU   o                           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXjXnX5X,.T p.sXcXjXlXlXlXlXlXlXlXlXlXlXkXkXzXK._ R #.'.bXjXlXlXlXlXlXlXlXlXlXlXlXkXcX:X=.R ) x.dXxXkXlXlXlXlXfXGXU   o       + y.^./.{.B.+       X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXxX0Xs . f   Q lXlXkXlXlXlXlXlXlXlXlXlXkXlXhX) t k   & }.mXjXlXlXlXlXlXlXlXlXlXlXhXNXA.q b 1   :.mXjXkXlXlXlXfXGXU   o   .   % 6XHX-XwX[.#       X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXgXFXs.  y.UXT   ].BXhXlXlXlXlXlXlXlXlXlXkXlXjXqXGXUX_   Z.VXhXlXlXlXlXlXlXlXlXlXlXkXzXeXjXUX^.  L zXlXkXlXlXlXfXGXU   o   .   O qX`.O :           X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXhXVX .  U.UX4.  z.BXhXkXlXlXlXlXlXlXlXlXlXkXkXmXn.-.3 Y gXlXkXlXlXlXlXlXlXlXlXlXlXlXhXVXOX4.A < ].mXhXkXlXlXlXfXGXU   o   .   % 2XUXPXSXi.        X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXjXMX`   I.PX6.  s.BXhXkXlXlXlXlXlXlXlXlXkXlXjXvXJ #   c <XcXjXlXlXlXlXlXlXlXlXlXlXkXgXZXM.# # $ m.bXjXkXlXlXlXfXGXU   o       # $.E R wXUXT   o   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXgXFX>.  S.UX@.  L.VXhXkXlXlXlXlXlXlXlXlXlXkXlXNXKXUX6.  3.DXgXlXlXlXlXlXlXlXlXlXlXlXkXbXDXUX*X+ 0 aXxXkXlXlXlXfXGXU   o           O   7.UX-.  O   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXhXNX].  n B.< 7 0XbXjXlXlXlXlXlXlXlXlXlXjXbX5X{ N.F.N   z.CXhXlXlXlXlXlXlXlXlXlXlXhXBX0.6.Y.;.  V jXlXkXlXlXlXfXGXU   o   X   m {.} +.hXUXD   o   X   +XBXhXlX",
"lXlXlXlXlXlXlXlXkXlXjXmXm.7   g `.mXjXkXlXlXlXlXlXlXlXlXlXjXvXqXz o   3 3.fXlXkXlXlXlXlXlXlXlXlXlXlXhXCX3.@   @ H #XbXjXkXlXlXlXfXGXU   o   .   0 .XFXUXaX@.  .     X   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXkXkXMXdXyXjXmXjXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXpXuXsXMXxXkXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXuXiXxXnXkXlXlXlXlXlXfXFXU   o           $ = +           .   @XBXhXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXhXxXvXzXhXlXkXkXlXlXlXlXlXlXlXlXlXlXlXkXzXcXcXxXjXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXxXcXcXkXjXlXkXkXlXlXlXfXFXU   o                 X         X   @XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXlXkXlXlXlXlXfXFXU   O                           o   +XBXhXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXCXs.  . . . . . . . . . . . . . X   s eXcXjXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXzXkXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXcXkXlXhX-.=                           k '.MXhXlXlX",
"lXkXlXkXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXjXlXkXzXpX8X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X8XsXzXhX9X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X9XrXzXkXxXmX3X-X;X;X;X;X;X;X;X;X;X;X;X;XaXNXjXlXkXlX",
"lXlXkXxXDXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXcXhXjXnX@Xv.Z.V.V.V.V.V.V.V.V.V.V.V.V.V.Z.v.,XMXiXV.V.V.V.V.V.V.V.V.V.V.V.V.V.V.C.m.E.vXkXkXjXnXMXMXMXMXMXMXMXMXMXMXMXMXMXxXhXlXkXkXlX",
"lXkXcXtXF.K.J.J.J.J.J.J.J.J.J.J.J.J.J.J.I.0XNXjXlXhXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXjXlXkXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXlXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlXlXlX",
"lXhXBX+X  X                               y {.mXhXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXkXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXhXNX@X  @ O O O O O O O O O O O O O O O   B zXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X                 X X .       .   , fXzXkXlXlXlXlXlXlXkXlXjXhXjXkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXkXjXhXhXjXlXkXkXlXlXlXlXlXlXlXlXlXlXkXkXlXjXhXhXjXkXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X               .                 , gXzXkXlXlXlXlXlXkXlXjXvXZXNXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXzXmXVXBXcXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXcXNXCXMXlXkXlXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X               . h C 5           > fXzXkXlXlXlXlXlXlXjXvX0X_.$XkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXhX<X XXXtXmXjXlXlXlXlXlXlXlXlXlXlXlXkXkXlXtX#X`.*XkXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X           X   V HXUX6.  O       > fXzXkXlXlXlXlXkXkXkXxXD   k hXzXkXlXlXlXlXlXlXlXlXlXlXhXVXu.o .   y `.mXhXkXlXlXlXlXlXlXlXlXlXkXkXcXQ     D hXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X             # #XmXUX>.  o       > fXzXkXlXlXlXkXlXgXAXf.* O c jXlXkXlXlXlXlXlXlXlXlXlXlXhXBXj.p.4X2.  P lXlXkXlXlXlXlXlXlXlXlXlXkXlXjXD.z.* D kXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X         X   t.wX4.UX>.  o       > fXzXkXlXlXlXlXjXmX<X: i.4 d hXlXkXkXlXlXlXlXlXlXlXlXlXlXkXnXMXGX#X  H zXlXkXlXlXlXlXlXlXlXlXlXlXkXhXFX6X$ A lXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X       .   f AXC W UX=.  o       > fXzXkXlXlXlXkXkXMXL U bX% k nXzXkXlXlXlXlXlXlXlXlXlXlXkXlXfXxXhXD   R.NXhXkXlXlXlXlXlXlXlXlXlXkXkXjXvX-X$ A kXlXkXkXlXlXlXlXlXlXlX",
"lXhXBX+X  X       X   I.yXa j.UXn.:         > fXzXkXlXlXlXjXMX).  M.^.@ e .XhXlXkXlXlXlXlXlXlXlXlXlXlXjXMXwXC X D.CXjXkXlXlXlXlXlXlXlXlXlXlXlXlXjXnX:X$ A kXlXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X           /.UXKXPXFXUXr.  X     > fXzXkXlXlXlXhXNXG.  .   @   d eXcXjXlXlXlXlXlXlXlXlXlXjXcX>Xk X J.kXtXkXlXkXlXlXlXlXlXlXlXlXlXlXlXhXNX1X= G vXxXkXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X           8 l 9 e.UXc.o .       > fXzXkXlXlXlXkXzXuX#X*X{.$ 8 ;XkXlXkXlXlXlXlXlXlXlXlXlXgXAXo.  + -   g sXzXkXlXlXlXlXlXlXlXlXlXkXjXnXT   X O   f.DXgXkXlXlXlXlXlXlX",
"lXhXBX+X  X             .   i w.j   .       > fXzXkXlXlXlXlXkXxXNXBXcXh.A.mXlXkXlXlXlXlXlXlXlXlXlXlXjXbX(.i.p.e.q.v.hXlXkXlXlXlXlXlXlXlXlXlXkXkXcXZ.7.d.a.3.{.MXjXkXlXlXlXlXlXlX",
"lXhXBX+X  X           . X X     . .         , gXzXkXlXlXlXkXlXkXjXhXkXGXAXjXkXlXkXlXlXlXlXlXlXlXlXlXlXjXVXHXHXJXKXFXlXkXlXlXlXlXlXlXlXlXlXlXlXlXkXSXKXGXHXLXNXjXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X                 . + X           > fXzXkXlXlXlXlXlXlXkXlXkXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXkXlXhXfXfXfXfXgXkXlXkXlXlXlXlXlXlXlXlXlXkXkXlXgXfXfXfXfXjXlXkXlXlXlXlXlXlXlX",
"lXhXNX@X  @ O O O O O O O O O O O O O O +   s kXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXhXBX+X  X                               @ A.MXhXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXjXbX6X$.:.;.;.;.;.;.;.;.;.;.;.;.;.;.-.1.|.MXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXkXcXKXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXHXmXjXlXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXjXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlX",
"lXlXkXlXjXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXjXkXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXlXkXkXlX",
"lXlXlXjXnXnXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXmXbXzXNXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXcXNXkXlXlXlX",
"lXlXjXnX#Xv t i s a u u u u u u u u u s p t n =XxX{ q i i s p u u u u u u u p s i i r b.MXjXkXlX",
"lXlXgXFX;.  o                             o   e.:X  .                             .   a xXkXkXlX",
"lXlXgXFX=.  o & [ V   X . . . . X . O ^ 8     q.-X  O   : | C   X . . . o   z  .>     p zXlXkXlX",
"lXlXfXFX*.  . % ^.^.  X         o   ( UXT     0.;X  X   !./.K   .       .   I jXZ     i zXlXkXlX",
"lXlXfXFX*.  @   E U.  X       .   i b.~.'     0.;X    5 gXn.c.            .   ^.A     u zXlXkXlX",
"lXlXfXFX*.  o   s.1X5   .     X   I |.hXI.    0.;X    # &Xt.:Xo         .   y qX1.    i zXlXkXlX",
"lXlXgXFX=.    < e.k.H   o       . .   { l     q.;X  o   l g.l   X       X   R l.9.=   p zXlXkXlX",
"lXlXfXFX*.  o                             o   0.;X  .                             .   u zXlXkXlX",
"lXlXhXNX(.1 $ * - ; * % % % % % % & % - = $ 2 [.jXB O * * ; * % % % % # @ @ % * * $ . 4.NXhXkXlX",
"lXlXlXjXmXpX7X9X8X8X8X8X8X8X8X8X8X8X8X8X9X7XpXnXcXlX7X9X8X8X8X8X8X8X8XpXfXdXdXdXdXsXjXAXkXkXlXlX",
"lXlXkXlXjXxXbXvXcXcXvXvXvXvXvXvXvXvXvXcXvXbXxXjXkXlXbXvXcXxXvXbXvXcXVXD.I W E Q Q E R !.mXjXkXlX",
"lXlXkXkXlXkXkXhXbXmXhXkXjXjXjXjXjXjXhXmXzXjXkXlXlXkXjXjXmXBXkXjXhXxXwX,   .       X   k cXkXkXlX",
"lXlXlXlXlXlXjXmX,X$XmXkXlXlXlXkXlXjXvX*XtXxXkXlXlXkXkXzX@X'.hXzXjXvX8X*   o   v c o   p zXlXkXlX",
"lXlXlXlXlXjXMX.XC N H.CXhXlXlXlXgXZX(.  Y.ZXhXkXlXkXlXfXx.D o.ZXgXvX9X&     1..Xo.X   i zXlXkXlX",
"lXlXlXlXlXgXHX1.q.U.Q FXgXkXlXkXcX9X1.J L.SXhXlXlXlXhXmXwXS 3.AXgXvX8X&     5XW.y.$   i zXlXkXlX",
"lXlXlXlXlXgXDXj.! =.$.FXgXkXlXhXZXK.M e ' NXjXkXlXkXlXdX{.| S BXhXvX8X&     $X5.2Xp   p zXlXkXlX",
"lXlXlXlXlXkXzXgX1.X.wXvXjXlXlXkXlXsX9X3.Y.MXjXkXlXkXxXpX4...W.nXhXvX8X%     x J.O.    u zXlXkXlX",
"lXlXlXlXlXlXkXzXZXAXcXkXlXlXlXlXkXzXnXZXMXkXlXlXlXlXkXzXVXCXNXkXkXvX8X%           .   u zXlXkXlX",
"lXlXlXlXlXkXlXkXhXgXkXlXkXlXlXkXlXkXjXhXjXlXkXlXlXkXlXkXhXhXhXlXjXvX8X%     . o X .   u zXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXvX8X%           .   u zXlXkXlX",
"lXlXlXlXlXlXkXlXkXkXlXlXlXlXlXkXlXkXkXkXkXlXkXlXlXlXkXlXkXkXkXlXjXvX8X%       .   .   u zXlXkXlX",
"lXlXlXlXlXkXlXjXzXcXjXlXkXlXlXlXkXkXvXcXjXlXkXlXlXlXlXkXcXvXjXkXjXvX8X%           .   u zXlXkXlX",
"lXlXlXlXlXlXjXnXsXyXmXjXlXlXlXkXkXlX6XqXmXkXlXlXlXkXkXzXqX6XmXlXjXvX8X%     # 0 5     u zXlXkXlX",
"lXlXlXlXlXjXbX<XL C [.NXhXlXlXkXcXwX6.B n.CXhXlXlXkXlXgXp.F 4.VXgXvX8X%     V.#X#.    u zXlXkXlX",
"lXlXlXlXlXgXHX5.>.N./ GXgXkXlXlXjXbX$Xk c.AXhXlXlXlXjXvX7XH -.AXfXvX8X%     n.OXo.    u zXlXkXlX",
"lXlXlXlXlXgXGXe.o.i.] GXgXkXlXkXlXgXoXA &.DXgXlXlXkXkXkX-X' L BXgXvX8X%   X t J fX<   i zXlXkXlX",
"lXlXlXlXlXkXcXeX` I -XnXjXlXlXjXnX,XO.~ I.NXhXlXlXkXxXyX;.^ k.MXhXvX9X*     1.(.0.    p zXlXkXlX",
"lXlXlXlXlXlXkXvXnXvXnXjXlXlXkXjXjXzXfXkXMXhXkXkXkXjXjXlXhXgXBXjXhXvX8X&   O X @   +   u zXlXkXlX",
"lXkXlXkXgXgXgXfXfXfXfXgXhXkXxXnXbXbXnXbXcXnXnXxXlXnXbXbXnXnXcXbXbXbXsXp   .       X   K mXjXkXlX",
"lXlXkXcXSXSXSXSXSXSXSXDXNXzXuX:X,X,X,X,X,X<X:XrXgX>X,X,X,X,X,X,X:X6XmX,Xc.b.b.b.b.v.M.qXvXjXlXlX",
"lXkXcXwXN.V.V.V.V.V.C.m.[.mXtX-X>X:X:X:X:X>X-XeXfX;X>X:X:X:X:X>X;X7XlXbXDXSXSXSXSXDXSXcXkXlXkXlX",
"lXhXBX X  .               `.CXvXbXnXbXvXbXbXnXxXlXnXnXbXbXbXcXnXnXvXkXjXgXgXfXfXgXgXgXjXlXkXlXlX",
"lXhXBX.X  O o O X   X #   V.SXfXkXhXxXMXlXjXjXkXkXjXjXlXxXxXNXjXjXkXlXkXlXkXcXbXzXkXlXlXlXlXlXlX",
"lXhXBX X  . X   S 3X9     C.SXgXjXmX4Xj `.BXhXkXlXkXzXdX;.K A.MXjXkXlXkXhXNXC.z %XMXjXlXlXlXlXlX",
"lXhXBX X  .   $ k.eXf     V.SXgXjXbXi.t R.SXgXlXlXkXzXiXhXu.H AXhXkXlXkXkXlXyXM !.VXhXkXlXlXlXlX",
"lXhXBX X  O   <.~.7X..    V.SXdXCXY.K M ,.VXjXkXlXlXjXMXOXP >XnXjXlXlXlXkXhXGXL '.ZXhXlXlXlXlXlX",
"lXhXBX X  X   k =.rX{     C.SXfXvX,Xm.l 4.NXjXkXlXkXzXhXd g h.xXkXkXlXkXhXMXD.5 ) dXzXkXlXlXlXlX",
"lXhXBX.X  O O .   ; o #   V.SXgXkXvXHXgXxXxXkXlXlXkXlXhXrX3X3XzXkXkXlXkXkXxX0X5X3XgXlXkXlXlXlXlX",
"lXhXBX X  .           .   Y.CXhXlXkXfXzXkXkXlXkXlXlXkXlXvXnXbXkXlXlXlXlXlXkXvXbXnXlXkXlXlXlXlXlX",
"lXjXbX2X#.=.*.*.*.=.=.@.c.lXlXkXlXkXlXkXkXlXkXlXlXkXlXkXkXjXkXlXkXlXlXlXkXlXkXjXkXkXlXkXlXlXlXlX",
"lXlXkXcXFXFXFXFXFXFXFXFXZXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXfXgXfXfXfXfXgXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlX",
"lXlXkXlXkXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXgXjXkXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXkXlXkXlX",
"lXlXlXkXvXAXCXCXCXCXCXCXCXCXCXCXCXCXCXCXAXmXkXZXCXCXCXCXCXCXCXCXCXCXCXCXCXCXZXVXkXkXlXlX",
"lXlXjXcX8X' D L I K J J J J J J J L I J J `.MX6.A K L I J J J J J J J P P K A l.bXjXkXlX",
"lXlXgXDXj.  o                         o   ~ 6X                            .   < tXcXkXlX",
"lXlXgXDXd.    t 8.e   O o o X O   v o.X   W 2X  O   S $.<   o o o X X +.^     > eXcXkXlX",
"lXlXgXDXs.    < =X^   X           L.=X    E 2X    j eXi.;             0.).    : eXcXkXlX",
"lXlXgXDXs.  #   M.(   X     o   =./.@X5   W 2X    ] OXJ.]   o     X   N T.    ; eXcXkXlX",
"lXlXgXDXd.    p 6XK.X       .   M d.4Xr   Q 3X    6 F.Q.N   X         z.yXM   < eXcXkXlX",
"lXlXgXDXs.  O ; 0 0 @ . X X X X   X * O   E 2X  o   > 4   o X X X X O 9 0 1   : eXcXkXlX",
"lXlXhXCXL.  .                         X   =.sX,   .                       .   f gXzXkXlX",
"lXlXkXkXcX{.L.Y.Y.Y.U.U.U.U.U.U.U.U.Y.I.W.aXmX:XL.Y.Y.Y.U.U.U.I.(.{.[.{.}.{.'.uXvXkXlXlX",
"lXlXlXlXkXBXAXZXBXCXZXZXZXZXZXZXZXCXVXZXCXzXjXnXAXZXBXVXZXZXCXHX`.;.2.3.5.3.:.Q.bXjXkXlX",
"lXlXkXlXkXhXgXgXVXcXfXhXgXgXgXhXfXzXMXgXhXkXlXjXgXjXCXmXgXgXkXrX4   .     .   5 uXxXkXlX",
"lXlXlXlXlXkXlXlXK.:XnXjXlXlXlXjXbX6X/.xXkXkXlXkXxXpXH.'.lXkXcXeX> .   0 ) 7   , eXcXkXlX",
"lXlXlXlXkXgXSXy.Y Y eXcXkXlXkXjXCX{ v MXjXkXlXkXcXqXi.s -XnXxXeX>   - @XZ.8   > eXcXkXlX",
"lXlXlXlXkXgXDX! ].)  XNXjXkXhXAXN.~ L yXxXkXlXlXhXCX(.k -XnXxXeX>   m 3Xm.&.  , eXcXkXlX",
"lXlXlXlXkXhXZXb.S / aXzXkXkXhXMXI.[ 9 ;XnXjXlXjXmX&X6.b .XMXzXeX:   > L.(.$.  , eXcXkXlX",
"lXlXlXlXlXkXkXbXoXeXbXjXlXlXlXjXVXmX5XvXkXlXlXkXzXpX).2XbXhXcXeX;     5 x     ; eXcXkXlX",
"lXlXlXlXlXlXlXjXNXcXjXlXkXlXkXlXhXjXbXkXlXkXlXlXkXxXCXbXjXkXcXeX;   .     .   ; eXcXkXlX",
"lXlXlXlXlXkXlXkXjXkXlXkXlXlXlXkXlXkXjXlXlXkXlXkXlXkXjXjXlXkXcXeX;     . . .   ; eXcXkXlX",
"lXlXlXlXlXkXlXkXjXkXlXkXlXlXkXlXkXjXjXlXkXlXlXkXlXkXjXjXlXkXcXeX;   . . X .   ; eXcXkXlX",
"lXlXlXlXlXlXlXjXNXcXjXlXkXlXlXkXxXCXvXkXlXkXlXlXkXzXVXnXkXkXcXeX;             ; eXcXkXlX",
"lXlXlXlXlXkXkXbXoXeXbXjXlXlXkXxXiX_.7XcXkXlXlXkXzXfX].,XcXjXcXeX;   . i C ;   : eXcXkXlX",
"lXlXlXlXkXhXZXb.S ( aXzXkXlXjXnX;X*.N uXxXkXlXkXvX8X9.z :XbXxXeX:   , 4XA.<   : eXcXkXlX",
"lXlXlXlXkXgXDX! ]._  XNXjXlXlXhXAXN.M iXxXkXlXlXhXZX/.k ,XbXxXeX:   * >.Y.P   , eXcXkXlX",
"lXlXlXlXkXgXSXt.Y Y eXcXkXlXjXmXoX6.h 3XbXjXlXjXbX:Xi.f [.NXzXeX:   3 ! +X&.  < eXcXkXlX",
"lXlXlXlXlXkXlXlXK.:XnXjXlXkXjXcX2XB.%XcXjXkXkXjXxXwXZ.|.xXhXcXeX>   % ( U o   > eXcXkXlX",
"lXkXlXkXhXhXgXgXVXcXfXhXkXzXvXcXNXKXCXcXvXxXlXvXcXmXJXAXcXcXnXiX5   .     .   5 iXxXkXlX",
"lXlXkXlXCXZXZXZXBXCXAXVXzXdX8X0X8X6X7X9X8XtXhX9X9X9X6X7X9X8XqXnXT...#.%.%.#...T.nXjXkXlX",
"lXkXzXfXE.I.U.U.Y.Y.P./.zXpX&X=X=X=X*X=X&X5XgX*X=X=X*X*X=X*X<XkXBXFXDXDXDXDXFXBXkXlXlXlX",
"lXkXcXeX;           X   p.DXxXbXbXbXMXbXnXcXlXbXbXbXVXmXvXnXvXlXhXfXgXlXkXfXgXhXlXkXkXlX",
"lXkXcXeX,   o X & ; +   @.DXdXjXkXlXrXkXjXkXkXjXkXjX<XpXvXhXkXlXkXkXlX0XyXzXkXkXlXlXlXlX",
"lXkXcXeX;   X   W.I.    #.DXgXgXGX1.N mXkXkXlXjXmX*X%.F :XnXjXlXkXlXxX} / BXjXkXlXlXlXlX",
"lXkXcXeX;     R !.A.    @.FXdXNX[.` R lXkXkXlXlXjXnXjXJ ,XnXjXlXlXhXCXOX) DXhXlXlXlXlXlX",
"lXkXcXeX;     i.@XeX3   #.FXsXZXf.G 7 $XmXjXlXjXcXqXu =.hXlXkXlXkXjXMXl.x 0XxXjXlXlXlXlX",
"lXkXcXeX,   O   a ! X   #.DXgXkXvX8XF.jXlXkXlXjXbX1Xr.f.2XbXjXlXkXlXjXm.9.XXmXjXlXlXlXlX",
"lXkXcXeX;           o   *.DXgXlXkXcXCXlXkXlXlXlXjXvXGXDXvXkXlXlXlXkXlXAXGXmXjXlXlXlXlXlX",
"lXkXxXuXW F K J K P G E =XbXjXlXkXkXhXkXlXkXlXkXlXkXgXgXkXlXkXlXkXlXkXgXfXjXlXkXlXlXlXlX",
"lXlXkXlXVXCXCXCXCXCXCXAXnXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXhXhXhXhXhXhXhXgXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXkXkXkXkXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"kXlXjXhXjXjXjXjXjXjXjXjXjXjXhXhXjXhXjXjXjXjXjXjXjXjXjXjXjXhXkXlX",
"lXkXmXBXmXNXMXMXMXMXMXMXMXMXNXMXvXVXmXMXNXMXMXMXMXMXNXMXMXBXzXkX",
"hXNX~.c n z n n n n n m b b h c.9XA b b z n n n n n z n k %.zXkX",
"fXDX%.  @ &             O +   L P.  X O %           & o   ; eXvX",
"fXDX*.  < ^.d   O X O   j.i.  T I.  : T.#.  o X O   d.>.  2 eXvX",
"fXDX&.    j.B   . X   v -XV.  I U.  l +XZ.=     X   Q q.  , eXvX",
"fXDX*.  4 D.|   + O   < o.3.  I P.  % ,.,.o o O O   3.c.X ; eXvX",
"fXDX>.  o                 X   R Q.  X                 .   1 yXcX",
"jXvX6Xp.u.a.i.u.u.u.u.i.a.s.e.@XjXz.t.a.a.i.u.a.v.c.b.m.k.[.vXjX",
"lXkXvXFXSXGXDXDXDXDXDXDXDXFXFXmXlXSXFXHXDXSXHXnX5.} o. .] h.xXkX",
"kXlXkXfXzXpXlXgXgXgXgXgXkXdXgXjXkXgXfXwXhXdXmX/.  .   .   ; eXvX",
"lXlXjXmX%X_ m.MXhXlXhXFXw.u.DXgXkXzXhX9.2.bXNX_.  . h.4.  , eXvX",
"lXlXgXFXl.6.-.zXkXhXMX@Xm &.BXhXkXjXMXZ.U xXBX`.  7 oXF.1 $ rXvX",
"lXlXjXnX<X .H.MXjXjXvX7Xu.7.nXjXkXcXtX9.r.lXBX_.  . ,.g.# * eXvX",
"lXlXlXjXvXbXnXkXlXlXjXbXZXMXlXkXlXkXlXgXMXjXVX_.  . X o   ; eXvX",
"lXlXkXlXjXjXjXlXkXkXlXjXgXjXkXlXkXlXkXlXjXhXVX_.  X X X   - eXvX",
"lXlXkXlXjXjXjXlXkXlXkXlXlXjXlXkXkXlXkXlXjXhXVX_.  . .     ; eXvX",
"lXlXlXjXvXvXnXkXlXlXlXkXjXmXkXlXlXkXlXhXnXhXVX_.  .   +   - eXvX",
"lXlXjXnX<X .H.MXjXkXxXuX1.x.NXhXkXzXgXw.t.vXBX_.  X K.$.  : eXvX",
"lXlXgXFXl.6.-.zXkXkXjXNXa.] CXhXkXjXNXZ.Y cXBX_.  + 9.J.+ * eXvX",
"lXlXjXmX%X_ m.MXjXjXcX8X=.e.mXhXkXxXyX5.,.lXBX`.  % O.D.$ ; eXvX",
"lXkXgXfXzXpXlXgXjXzXvXzXiXMXvXxXzXvXxXiXmXxXAX`.  . o X   ; eXvX",
"kXzXSXFXSXGXSXFXmXaXqXeXtXqXqXyXfXqXwXtXqX0XyXiX#.T R ! I r.cXkX",
"zXsXg.y.i.a.p.t.>XdX,X3X<X1X1X0XaX1X2X<X<X2X5XxXAXAXCXZXAXZXlXkX",
"vXeX;   .   o   ) DXxXxXAXCXcXcXzXvXnXBXSXvXvXkXgXgXvXcXfXhXkXlX",
"vXeX, X   2./   ^ ZXaXSXV.m.CXgXkXzXuXt.k.cXjXkXkXnXt.J.VXhXkXlX",
"vXeX>   h =X3.  / CXxX2XD ,.ZXhXkXkXnX!.@.mXjXkXhXAXG.d.GXgXlXlX",
"vXeX<   m W.l.  / CXcX*X} X.nXjXkXxXpXZ h.nXjXkXjXBXe.' cXkXkXlX",
"vXeX;     . O   W AXfXnXnXfXzXkXkXlXgX6X5XkXlXkXlXkX7X4XgXlXkXlX",
"cXyXF c N m n l D.BXhXjXjXzXkXlXlXkXlXbXbXlXkXlXkXlXbXbXlXkXlXlX",
"kXlXmXMXMXMXMXNXMXkXlXlXkXkXlXkXkXlXkXjXkXlXlXkXkXlXkXkXkXlXkXlX",
"lXkXjXjXjXjXjXhXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXxXdXhXjXjXfXzXcXgXgXjXhXdXzXzX",
"NX .t d i i q ` 2.8 g u s s Z pX",
"VXj G g   2 7.b A [ ~   + ' 4 0X",
"BXN 1 7   % w m R , e   & B i wX",
"cX;X(.`._.).~.&X3XQ.`.~.-.Y e.kX",
"jXVX$X0XFXnX#XbXVX5XwXqX% V 6 0X",
"jXnXi.W.CX3X,.sXBXP.T.1X: s.t 7X",
"kXlXzXzXkXzXcXkXlXfXMX-XX   1 qX",
"kXlXzXzXlXjXjXlXkXgXMX=XO   1 qX",
"jXbXi.W.CXuXu.sXCXR.E.4X- 9.r 8X",
"kXAX$X0XNXpX/.hXmX@X>X2Xo f 9 9X",
"gX{.`.`.eXrXhXtXrXpXdXeXI.n.T.kX",
"wX; 5 # A.VXXXhXcX<X<XnXNXwXZXlX",
"eX@ =.n n.hX%.dXCXK.Y.CXsXa.iXzX",
"rXn p t /.BXaXjXzXtXsXzXkXeXhXlX",
"kXjXgXhXxXkXxXlXkXcXxXkXlXvXlXkX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
