#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 177 2 ",
"   c #080803",
".  c #140201",
"X  c #1A0B00",
"o  c #011801",
"O  c #080716",
"+  c #1D0615",
"@  c #130E12",
"#  c #1D1315",
"$  c #1D1F15",
"%  c #1E1519",
"&  c #131300",
"*  c #2E0A00",
"=  c #350102",
"-  c #320C02",
";  c #2F1700",
":  c #351C01",
">  c #361C03",
",  c #201417",
"<  c #012301",
"1  c #022901",
"2  c #013501",
"3  c #033A03",
"4  c #1D2015",
"5  c #353502",
"6  c #3A3A03",
"7  c #362000",
"8  c #0C1235",
"9  c #0B133A",
"0  c #080B2B",
"q  c #220038",
"w  c #460000",
"e  c #490000",
"r  c #520000",
"t  c #481F00",
"y  c #720000",
"u  c #4E2500",
"i  c #4D2A00",
"p  c #512600",
"a  c #562800",
"s  c #5D2C02",
"d  c #783900",
"f  c #773700",
"g  c #006800",
"h  c #007600",
"j  c #007C00",
"k  c #515000",
"l  c #504F00",
"z  c #49473A",
"x  c #48473B",
"c  c #0B184B",
"v  c #04144A",
"b  c #110D59",
"n  c #051853",
"m  c #04145A",
"M  c #0B1854",
"N  c #0B1253",
"B  c #33004F",
"V  c #051B7C",
"C  c #18117C",
"Z  c #3B006F",
"A  c #0F256E",
"S  c #112577",
"D  c #4B005A",
"F  c #51015F",
"G  c #4D3A4D",
"H  c #410179",
"J  c #5F0079",
"K  c #5E0077",
"L  c #530061",
"P  c #67017F",
"I  c #3A434D",
"U  c #4B4949",
"Y  c #757576",
"T  c #9E0000",
"R  c #8B0000",
"E  c #A80000",
"W  c #BE0000",
"Q  c #853600",
"!  c #C20000",
"~  c #D90001",
"^  c #E00000",
"/  c #EA0000",
"(  c #F40000",
")  c #FE0000",
"_  c #974500",
"`  c #9A4900",
"'  c #A54B01",
"]  c #BB5A00",
"[  c #B05F00",
"{  c #B46200",
"}  c #C15F00",
"|  c #DE6300",
" . c #C76603",
".. c #E06400",
"X. c #E06B02",
"o. c #EE7A00",
"O. c #EA7700",
"+. c #F27B00",
"@. c #FC7E00",
"#. c #008301",
"$. c #009700",
"%. c #009900",
"&. c #00BA00",
"*. c #00C400",
"=. c #00CC00",
"-. c #00DB00",
";. c #00D600",
":. c #00E703",
">. c #00FE00",
",. c #00F500",
"<. c #FF8100",
"1. c #FF8A03",
"2. c #F08502",
"3. c #FF9406",
"4. c #FEFE00",
"5. c #F7F700",
"6. c #141482",
"7. c #1F1A9E",
"8. c #231E9E",
"9. c #0B259E",
"0. c #142497",
"q. c #152A9D",
"w. c #192787",
"e. c #1430BF",
"r. c #1F35BC",
"t. c #162AAC",
"y. c #2036BF",
"u. c #52008A",
"i. c #590097",
"p. c #6A0082",
"a. c #7C00AE",
"s. c #7E00B0",
"d. c #162AC4",
"f. c #1632C5",
"g. c #163AC5",
"h. c #1A3EC5",
"j. c #2439C4",
"k. c #2237C3",
"l. c #2A38DE",
"z. c #1F36E0",
"x. c #2036E0",
"c. c #2C36E0",
"v. c #2E38E8",
"b. c #333DF3",
"n. c #2041DC",
"m. c #2142E0",
"M. c #2B43E7",
"N. c #2A45F6",
"B. c #2B49F6",
"V. c #2C49FC",
"C. c #3149F5",
"Z. c #334CFE",
"A. c #394FFF",
"S. c #3652FF",
"D. c #3953FF",
"F. c #3A59FF",
"G. c #415DFF",
"H. c #8000B3",
"J. c #8701BF",
"K. c #8B01BD",
"L. c #8A01C4",
"P. c #8701C1",
"I. c #9302CC",
"U. c #9801D2",
"Y. c #CACAC9",
"T. c #D4D4D4",
"R. c #DCDAD2",
"E. c #D2D2DE",
"W. c #DED2DE",
"Q. c #D2DBDE",
"!. c #DDDDDE",
"~. c #E0DFDE",
"^. c #DEE0DE",
"/. c #E0E0DE",
"(. c #DEDFE0",
"). c #E0D8E0",
"_. c #F5F6F5",
/* pixels */
"T.T.T.T.T.T.Q.T.T.T.T.T.Q.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.Q.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.T.R.Y.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.",
"T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.",
"T.T.T.R.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.",
"T.E.R.Y.Y.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.E.T.T.T.T.T.T.T.T.T.T.E.T.E.T.T.T.T.T.T.T.T.T.E.T.E.T.T.T.E.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.T.R.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.Y.T.R.T.T.",
"T.T.T.Y.Y x z x z z z z x x x x z z z z z z z z x x z z z z z z z z z z z x z z z z z z z z z z x x z z z z z z z z z z x U U I I I I I I I I I G I I I U U G G G G G G U G G G G G U Y.!.T.T.T.",
"T.T.T.T.U m q.0.0.0.0.0.7.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.q.m t ` _ ` _ _ _ _ _ _ _ _ ` Q o %.$.$.$.$.$.$.$.$.$.$.$.$.o ).!.T.T.T.",
"T.T.T.T.z q.F.D.D.D.D.D.D.D.S.D.D.D.D.D.D.D.D.D.S.D.D.D.D.D.D.D.D.D.D.D.D.D.S.D.D.D.D.D.D.D.D.D.S.D.D.D.F.D.D.D.D.D.D.D.F.q.d 3.2.1.1.1.1.1.1.1.1.1.3.| 3 >.>.>.>.>.>.>.>.>.>.>.>.>.3 W.^.T.T.R.",
"R.T.T.E.z 6.D.C.Z.C.Z.C.Z.C.Z.C.Z.Z.C.Z.C.Z.Z.Z.Z.C.Z.C.Z.C.Z.C.Z.C.Z.C.Z.C.Z.C.Z.Z.C.Z.Z.C.C.Z.C.Z.C.Z.Z.C.Z.C.C.C.Z.C.D.9.f 1.+.@.<.@.<.<.@.@.@.+.<.| 2 >.>.>.>.>.>.,.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.@.<.<.<.<.<.<.@.@.1...2 >.,.>.>.>.>.>.>.>.>.>.>.>.2 ~.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.<.<.@.<.@.<.@.@.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.<.<.<.<.<.<.@.@.<...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W./.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.S.Z.C.D.9.d 1.@.<.@.@.@.<.@.<.<.<.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W./.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.@.<.<.<.<.<.@.<.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 ~.!.T.T.T.",
"Q.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.C.D.9.d 1.@.<.<.<.@.<.@.<.<.@.<...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.@.<.<.<.<.@.@.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.<.<.<.<.@.<.@.@.@.1...2 >.>.>.>.>.>.>.>.>.>.>.,.>.2 W.!.T.T.T.",
"E.T.T.T.x 0.S.C.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.C.Z.C.Z.C.Z.C.Z.C.Z.C.Z.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.+.@.@.@.@.@.@.@.@.@.@.| 2 >.>.>.>.>.,.>.>.>.>.>.,.>.2 W.(.T.R.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.D.D.D.D.D.S.D.D.D.D.D.D.D.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 3.<.1.1.1.<.1.1.1.1.1.3.| 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.j.e.e.d.e.e.e.d.e.e.e.f.e.d.r.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.C.D.q.a  .] ] ] } ] ] ] ] ] ] } ' 1 &.&.&.&.&.&.&.&.&.&.&.&.*.< Q.(.T.T.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.O p a a a a a a a a a a p s X k.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.j.N m m m m m m m m m m m m m M b b b b b b b b b b b b b O !.!.T.T.T.",
"T.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.V.% <.1.1.1.1.1.1.1.1.1.1.<.3.i f.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.D.D.D.D.D.D.D.D.D.A.D.D.D.D.S.S.S.S.S.S.S.D.S.S.S.D.D.8 R.(.T.T.T.",
"T.T.T.E.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.@.@.@.@.@.@.@.@.@.@.1.u f.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.C.C.Z.C.Z.C.Z.Z.C.Z.C.Z.C.Z.C.Z.Z.Z.C.Z.C.C.Z.C.Z.8 R.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.@.<.<.<.<.<.@.<.@.@.1.p f.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.<.@.<.@.<.@.@.<.<.@.@.1.p f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.R.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.@.@.<.<.@.@.<.<.<.<.@.1.p f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R./.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.N.# +.<.@.<.<.<.<.<.@.<.@.@.1.p f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 ~.R.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.N.# @.<.@.<.<.@.@.<.<.<.<.@.1.p f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.!.T.T.T.",
"T.T.T.E.z 0.D.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.<.@.<.<.<.<.@.<.<.@.1.p f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.@.<.<.<.<.@.<.@.@.@.1.p f.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.8 R.(.T.T.R.",
"T.T.T.T.x 0.S.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.% @.<.@.<.<.@.<.<.<.<.@.@.1.p f.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.9 R.(.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.@.@.@.@.<.<.@.@.@.@.@.1.p f.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.A.Z.D.V.# @.<.<.<.<.<.<.<.<.<.<.@.1.p f.D.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.!.T.T.T.",
"T.T.T.E.z 0.D.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.V.N.N.N.N.N.N.N.V.N.N.N.N.v.# O.2.o.+.+.o.+.+.o.+.o.o.1.u f.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.C.B.B.B.B.B.B.B.B.B.B.B.B.V.9 R.(.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.S.j.  , # # # # # # # % # # # @   * * * * * * * * * * * * - . k.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.M.O + + + + + + + + + + + + +   ^.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.+.@.+.@.+.@.+.+.@.@.@.O.* / ( ( ( ( ( ( ( ( ( ( / ) e g.A.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.n.= ) ( ( ( ) ( ) ( ) ( ( ( ) = Q.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.d.a 1.@.<.<.@.@.<.<.<.@.<.<.o.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.n.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.@.@.@.@.@.@.<.<.@.@.<.o.* ( ) ) ) ) ) ) ) ) ) ) ( ) r g.A.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = ^.~.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.@.@.@.<.<.@.<.@.<.<.<.+.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.~.R.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.C.D.e.a 1.@.@.<.@.<.<.<.@.<.@.<.+.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.~.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.A.e.a 1.@.<.<.<.<.@.<.<.<.<.<.o.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.A.n.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.!.T.T.T.",
"T.T.T.E.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.@.@.@.<.<.<.<.<.@.@.<.+.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = ^.~.T.T.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.A.e.a 1.@.<.@.@.<.@.<.<.<.<.<.o.* ( ) ) ) ) ) ) ) ) ) ) ) ) e g.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.~.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.@.@.<.@.<.@.<.@.<.@.<.+.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.~.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.D.e.a 1.@.<.<.<.<.<.<.<.<.@.<.+.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) - Q.~.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.e.a 1.@.@.@.@.@.@.<.<.@.@.@.o.* ( ) ) ) ) ) ) ) ) ) ) ) ) r g.A.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.m.= ) ) ) ) ) ) ) ) ) ) ) ) ) = Q.(.T.T.T.",
"T.T.T.T.z 0.D.C.Z.S.Z.Z.Z.Z.Z.Z.Z.D.e.a 1.+.@.@.@.@.@.@.@.@.@.@.o.* ( ) ( ) ) ) ) ) ) ) ) ( ) e g.A.C.Z.Z.C.C.Z.Z.C.Z.C.Z.C.C.Z.Z.C.Z.C.Z.Z.C.C.C.C.Z.n.= ) ) ( ) ) ) ) ) ) ) ) ( ) * Q.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.e.s 3.<.1.1.1.1.1.1.1.1.1.1.2.* ( ) ) ) ) ) ) ) ) ) ) ) ) r h.D.D.A.S.S.D.Z.D.D.D.Z.A.D.D.D.D.D.Z.D.D.A.D.S.D.S.D.M.= ) ) ) ) ) ) ) ) ) ) ) ) ) = ^.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.C.S.f.X a u p p p p p p p p p a u   w e w e e e w w e e w w e . 9 c c c c c c c c c c c c c M n n n n n n n n n n n n v . r r r r r r r r r r r r r . ^.!.T.T.T.",
"Q.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.f.f.f.f.f.f.f.f.f.f.f.f.f.e.@ [ { { { { { { { { { [ [  .7 B p.J J J J J J J J J K p.B r ~ W W W ! ! ! ! ! ! W ! E < =.*.*.*.*.*.*.*.*.*.*.*.=.1 W.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.D.D.D.D.A.A.D.A.D.D.D.D.D.C.# @.1.1.<.1.1.1.<.1.1.1.<.3.i i.I.J.P.J.J.J.J.J.J.J.J.I.H y ) ) ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.E.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.C.Z.C.Z.Z.C.Z.Z.C.Z.N.# +.@.@.@.@.@.@.@.@.@.@.@.1.u u.J.s.s.a.H.H.a.H.H.a.a.L.Z y ) ( ) ) ) ) ) ) ) ) ) ) ^ 2 >.,.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.R.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.N.# @.@.@.@.<.<.@.@.@.<.<.@.1.i u.K.s.s.H.H.H.H.H.H.H.s.L.Z y ) ) ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.E.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.<.@.<.<.@.@.<.@.<.<.@.1.i u.J.H.H.H.H.H.H.H.H.H.s.K.Z y ) ( ) ) ) ) ) ) ) ) ) ) ^ 3 >.>.>.>.>.>.>.>.>.>.>.>.>.2 ~.!.T.T.T.",
"T.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.@.<.<.<.<.<.@.<.<.@.1.u u.K.a.H.H.H.H.H.H.H.H.a.K.Z y ) ) ) ) ) ) ) ) ) ) ) ) ^ 3 >.>.>.>.>.>.>.>.>.>.>.>.>.1 W.!.T.T.T.",
"T.T.T.T.z 0.S.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.@.@.<.@.<.<.<.<.<.@.@.1.i u.K.a.H.H.H.H.H.H.H.H.H.L.Z y ) ) ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 ~.~.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.N.# @.<.@.<.<.<.@.<.@.<.@.@.1.u u.K.H.H.H.H.H.H.H.H.H.H.L.Z y ) ) ) ) ) ) ) ) ) ) ) ) ~ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.1 W.~.T.Q.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.@.@.<.<.@.<.@.<.<.<.@.1.u u.K.s.H.H.H.H.H.H.H.H.s.K.Z y ) ( ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.(.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.<.@.<.<.<.<.<.<.@.<.@.1.i u.K.s.H.H.H.H.H.H.H.H.s.K.Z y ) ) ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# @.<.@.@.<.@.<.@.<.<.@.@.1.i u.K.s.H.H.H.H.H.H.H.H.a.L.Z y ) ) ) ) ) ) ) ) ) ) ) ) ^ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.(.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.# +.@.@.@.@.@.@.@.@.<.@.+.1.u u.J.a.s.s.s.s.a.s.s.s.a.L.Z y ) ( ( ) ) ) ) ) ( ) ) ) ~ 2 >.,.>.,.>.,.>.>.,.>.,.,.>.2 W.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.N.% 1.1.1.1.1.1.1.1.1.1.1.1.3.i i.I.K.L.L.L.L.L.L.L.L.K.U.H y ) ) ) ) ) ) ) ) ) ) ) ) ~ 2 >.>.>.>.>.>.>.>.>.>.>.>.>.3 W.!.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.B.@ _ ` ` ` ` ` ` ` ` ` ` ` ' ; B D D D D D D D D D D D L q e E E E T T T T E E T T E R < $.$.$.%.%.%.$.$.$.%.%.$.%.< (.~.T.T.T.",
"T.T.T.E.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.w.V V V V 6.V V V V V 6.V V S A A A A A A A A A A A A S c 3 #.j j j j #.#.j j j j #.h O 6.C C 6.6.C C C C 6.6.C C O R.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.D.F.D.D.S.F.D.D.D.S.F.S.D.D.D.D.D.D.D.D.D.D.D.D.D.D.F.8.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 F.F.D.D.D.D.F.D.D.D.D.S.F.9 R.!.T.T.T.",
"T.T.T.T.x 0.S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.C.Z.C.Z.C.C.Z.C.Z.C.Z.C.Z.C.Z.Z.C.C.Z.C.Z.Z.C.Z.C.S.8.h >.,.>.>.>.,.>.>.,.>.,.>.-.8 Z.B.C.Z.C.Z.C.C.Z.C.C.Z.Z.8 R.~.T.T.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.S.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"Q.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.F.7.h >.,.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.~.T.T.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.C.F.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.V.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.T.x 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.T.x 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.F.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.(.T.T.T.",
"T.T.T.E.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.S.7.h >.,.>.>.>.>.>.>.>.>.>.>.-.8 Z.V.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.!.T.T.T.",
"T.T.T.T.z 0.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.V.F.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.~.T.T.T.",
"T.T.T.T.z 0.F.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.F.7.h >.>.>.>.>.>.>.>.>.>.>.>.-.8 Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.8 R.~.T.T.T.",
"T.T.T.T.z 0.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.Z.Z.Z.Z.V.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.S.Z.Z.S.7.h >.,.>.>.>.>.>.>.>.>.>.>.-.8 Z.C.Z.Z.V.Z.Z.C.Z.Z.Z.Z.Z.8 R.!.T.T.T.",
"T.T.T.T.z 0.F.Z.Z.S.S.Z.Z.S.S.Z.Z.S.S.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.S.S.Z.S.Z.S.Z.S.Z.D.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.S.7.h >.,.>.>.>.>.>.>.>.>.>.>.-.8 D.Z.Z.Z.S.Z.S.S.S.Z.Z.S.D.8 R.!.T.T.T.",
"T.T.T.T.x 6.b.c.c.c.c.l.c.c.c.l.c.l.c.M.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.M.l.x.z.z.l.z.z.l.z.z.z.l.x.M.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.8.g ,.;.-.-.-.;.-.-.-.-.;.:.&.0 v.l.l.c.c.c.c.c.c.c.l.l.c.0 ~.~.T.T.T.",
"T.T.T.T.U o 3 2 2 2 2 2 2 2 2 2 2 3 o M S.C.S.Z.Z.Z.Z.Z.Z.Z.Z.S.N.O 5 5 5 5 5 5 5 5 5 5 5 5 6   j.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.q.. > : : : : : : : : > : : ;   3 2 2 2 2 2 2 2 2 2 2 2 2   W.!.T.T.T.",
"T.T.T.T.G $.>.,.>.>.>.>.>.>.>.>.>.>.&.b S.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.4.4.4.4.4.4.4.4.4.5.4.l d.D.Z.Z.Z.Z.Z.Z.Z.Z.A.C.D.9.d 1.@.1.<.1.1.<.<.1.1.<.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.5.4.4.4.4.4.4.4.4.4.4.l d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.G.9.d 1.@.@.@.@.@.@.@.<.@.@.1.| 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 ~.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.4 5.4.4.4.4.4.4.4.4.4.4.4.4.k d.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.@.@.@.@.@.@.@.@.<...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.S.Z.Z.Z.Z.Z.Z.Z.Z.S.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.l d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.<.<.<.@.<.@.<.<.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.,.>.&.b S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.l d.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.<.@.<.<.<.<.@.@.<...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.,.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.k d.D.Z.Z.Z.Z.Z.Z.Z.Z.A.C.D.9.d 1.@.@.<.<.<.@.@.<.<.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.W.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.V.4 5.4.4.4.4.4.4.4.4.4.4.4.4.k d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.<.@.<.<.<.<.<.<.<.<.| 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.k d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.@.<.<.<.@.<.@.@.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.4.4.4.4.4.4.4.4.4.5.4.k d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.@.<.@.<.@.<.<.<.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.,.>.&.b S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.k d.D.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.d 1.@.<.<.<.<.<.<.<.@.@.<...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.~.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.N.4 5.4.4.4.4.4.4.4.4.4.4.5.4.k d.D.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.@.@.@.<.@.@.@.@.@.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.U $.>.>.>.>.>.>.>.>.>.>.>.>.&.b D.C.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.N.$ 5.4.4.4.4.4.4.4.4.5.4.5.4.l d.D.C.Z.Z.Z.Z.Z.Z.Z.Z.C.D.9.d 1.@.@.@.@.@.<.@.<.@.@.1.| 2 >.>.>.>.>.>.>.>.>.>.>.>.>.2 W.^.T.T.T.",
"T.T.T.T.G $.>.>.>.>.>.>.>.>.>.>.>.>.&.b S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.N.$ 5.4.4.4.4.4.4.4.4.4.4.4.4.l d.D.Z.C.Z.Z.Z.Z.Z.Z.Z.C.G.9.f 3.<.<.1.<.<.<.1.<.<.<.1...2 >.>.>.>.>.>.>.>.>.>.>.>.>.3 W.^.T.T.T.",
"R.T.T.Y.U o 3 2 2 2 2 2 2 2 2 2 2 2 1 O 9 8 8 8 8 8 8 8 8 8 8 8 8   5 5 5 6 5 5 5 5 5 5 5 5 6 & 0 9 8 8 8 8 8 8 8 8 8 8 9 O X > : : : : : : : : > : > ;   3 2 2 2 2 2 2 2 2 2 2 2 2   !.~.T.T.T.",
"T.T.R.Y.Y.).W.W.W.W.W.W.W.W.W.W.W.W.W.!.R.R.R.R.R.R.R.R.R.R.R.R.R.!.E.E.E.E.E.E.E.E.E.E.E.(.E.R.R.R.R.~.R.R.R.~.R.R.R.R.R.~.(.E.Q.E.Q.Q.Q.E.Q.E.Q.Q.E.Q.!.W.W.W.W.W.W.W.W.W.W.W.W.W.(._.R.T.T.T.",
"T.Q.T.T.).!.^.^.^.^.^.!.^.!././.(.!.!.(.~.~.~.!.(.(././.(.!.(.(.!.!./.!.~./././.~.~.~.~.~.~.~.~.(.!.~.!.~.!.!.!.~.).(.!.~.~.~.~.~.~./././.!.~.~.!.!./.!.!.!.^.^.!.!.!.^.~.!.!.!.!.!.).R.T.T.T.T.",
"T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.",
"T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.T.T.T.T.T.T.T.Q.T.T.T.T.T.T.T.R.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.T.T.R.T.T.T.T.T.R.Q.T.T.T.T.T.T.T.T.T.Q.",
"R.T.R.T.T.T.T.T.T.T.R.T.T.T.T.T.T.T.T.T.Q.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.Q.T.R.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.Q.T.R.T.T.T."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 181 2 ",
"   c #001A00",
".  c #060419",
"X  c #1D0E00",
"o  c #220500",
"O  c #3C0000",
"+  c #231200",
"@  c #3D1B00",
"#  c #002500",
"$  c #003C00",
"%  c #3C3B00",
"&  c #010824",
"*  c #06093B",
"=  c #1D002D",
"-  c #2D003A",
";  c #31003D",
":  c #490000",
">  c #540000",
",  c #5B0000",
"<  c #451C00",
"1  c #620000",
"2  c #690000",
"3  c #790000",
"4  c #492500",
"5  c #552600",
"6  c #562A01",
"7  c #5B2C00",
"8  c #5E3300",
"9  c #5E3800",
"0  c #612F00",
"q  c #633202",
"w  c #6B3400",
"e  c #653901",
"r  c #733702",
"t  c #004E00",
"y  c #004300",
"u  c #005200",
"i  c #005B00",
"p  c #006B00",
"a  c #006100",
"s  c #017100",
"d  c #4F4E00",
"f  c #515100",
"g  c #605F00",
"h  c #616000",
"j  c #49483E",
"k  c #44433B",
"l  c #0E164E",
"z  c #081448",
"x  c #0E1652",
"c  c #0D1A55",
"v  c #0C1A5D",
"b  c #09155A",
"n  c #111457",
"m  c #101854",
"M  c #12145C",
"N  c #14195E",
"B  c #0D0C44",
"V  c #270041",
"C  c #2B0147",
"Z  c #0A1C64",
"A  c #091469",
"S  c #091A6B",
"D  c #111E67",
"F  c #081971",
"G  c #3F0060",
"H  c #0A216E",
"J  c #4C3E4C",
"K  c #5F0078",
"L  c #61007A",
"P  c #3E454C",
"I  c #4A4749",
"U  c #747475",
"Y  c #9A0000",
"T  c #AF0000",
"R  c #B10000",
"E  c #BE0000",
"W  c #8B3E00",
"Q  c #C30000",
"!  c #CE0000",
"~  c #D30000",
"^  c #F70000",
"/  c #FE0000",
"(  c #FF0208",
")  c #A94B00",
"_  c #AC5000",
"`  c #BB5A00",
"'  c #B75701",
"]  c #B56500",
"[  c #BD6100",
"{  c #8B4900",
"}  c #C05C00",
"|  c #CF5700",
" . c #D35800",
".. c #D75A02",
"X. c #E15F00",
"o. c #CA6200",
"O. c #C66800",
"+. c #D06300",
"@. c #F77C00",
"#. c #FB7E00",
"$. c #008900",
"%. c #00AC00",
"&. c #00A400",
"*. c #01B600",
"=. c #00C600",
"-. c #00CB00",
";. c #00D300",
":. c #01DC02",
">. c #00F700",
",. c #00FE00",
"<. c #08FF00",
"1. c #BEBC00",
"2. c #9C9800",
"3. c #FF8101",
"4. c #FF8901",
"5. c #FF9203",
"6. c #FF9008",
"7. c #C0BE00",
"8. c #CECD00",
"9. c #DDDC03",
"0. c #FEFE01",
"q. c #FBFB04",
"w. c #1F2E9C",
"e. c #182AAC",
"r. c #1729AA",
"t. c #122FBE",
"y. c #1A2DB9",
"u. c #1E36BC",
"i. c #1D30AD",
"p. c #2625BE",
"a. c #2729BE",
"s. c #2233AA",
"d. c #2216AA",
"f. c #52008D",
"g. c #590098",
"h. c #690182",
"j. c #7C00AE",
"k. c #7E00B0",
"l. c #1529C9",
"z. c #172CC8",
"x. c #1633CB",
"c. c #173AC8",
"v. c #1937D8",
"b. c #292BCE",
"n. c #2827CB",
"m. c #203DC1",
"M. c #2239CC",
"N. c #2A2DD4",
"B. c #2B35D4",
"V. c #2841D5",
"C. c #2D43E1",
"Z. c #3149F7",
"A. c #334CFE",
"S. c #394FFF",
"D. c #3652FF",
"F. c #3953FF",
"G. c #3B59FF",
"H. c #375AFF",
"J. c #1940C9",
"K. c #405AFF",
"L. c #8000B3",
"P. c #8601BE",
"I. c #8902BB",
"U. c #8A00C1",
"Y. c #9302CC",
"T. c #CACBCA",
"R. c #D0CFC3",
"E. c #D2D1CA",
"W. c #C4C7D3",
"Q. c #D3C3D3",
"!. c #D4CCD4",
"~. c #C5D3D3",
"^. c #D4D4D4",
"/. c #D7D8D7",
"(. c #E3DFDF",
"). c #DFE3DF",
"_. c #E3E2DF",
"`. c #DFDFE1",
"'. c #DFE0E2",
"]. c #E0E0E3",
"[. c #F1F2F1",
/* pixels */
"^.^.^.^.^.^.^.^.^./.^.^.^.^./.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.",
"^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^././.^.",
"^.^.^././.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.",
"^.^./.E.T./.^.^.^.^.^.^./.^.^.^.^.^.^./.^.^.^./.^.^./.^././.^./.^./.^.^.^./.^.^.^.^.^./.^.^././.^./.^.^.^./.^.^.^./.^.^././.^./.^././././.^.^.^.^.^.^.^.^.^.^./.^.^.^.T.^.^.^.^.",
"/.^./.T.U I j j j j j j I j j j j j j j j j j j I j j j j j j j j j j j I j j k j j j j j j j j I k j j j j j j I P P P I P P P P P P P P I J J I J J J J J J J J J I T./.^.^.^.",
"^.^.^.^.I A u.r.e.e.r.r.r.e.e.e.e.e.e.e.e.e.e.r.r.r.r.r.e.e.e.e.e.e.e.e.r.e.e.e.e.e.e.e.e.e.e.e.e.r.e.e.e.e.r.y.z W ' ) _ _ _ _ _ _ _ _ ' @ $.*.%.%.%.%.%.%.%.%.&.*.$ Q.'.^.^.^.",
"^.^.^.^.k i.G.F.F.F.F.F.F.F.S.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.G.Z O.6.4.4.4.4.4.4.4.4.4.5.6 -.<.<.,.<.,.,.<.,.,.,.<.u Q.).^.^.^.",
"^.^.^.^.k e.F.Z.A.Z.Z.A.Z.A.A.A.A.Z.A.Z.A.A.A.A.A.A.A.Z.Z.A.A.Z.Z.A.Z.Z.Z.A.A.A.A.Z.A.Z.A.A.Z.A.Z.A.Z.A.Z.A.Z.F.b o.4.#.#.#.#.#.#.#.@.@.4.5 =.<.>.,.,.,.,.>.,.,.>.,.t Q.).^./.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.D.A.A.S.A.A.A.A.A.A.A.A.A.A.D.v o.4.#.#.3.#.3.3.3.#.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.t Q.).T.^.^.",
"^.^.^.^.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.S.v o.3.#.#.3.#.3.#.3.3.#.4.5 -.<.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.F.v o.4.#.3.3.3.#.#.3.3.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^./.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.b o.4.#.#.#.3.3.3.3.#.#.4.5 -.<.,.,.,.,.,.,.,.,.,.,.t Q.'.^.^.^.",
"/.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.Z o.4.#.3.3.#.3.3.#.3.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.S.Z | 4.#.3.#.#.3.#.3.3.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.u Q.).^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.b o.4.#.#.#.3.3.#.#.#.#.4.5 -.<.,.,.,.,.,.,.,.,.>.,.t Q.).^.^.^.",
"^.^.^./.j e.F.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.Z.A.Z.A.A.Z.A.A.A.Z.A.A.A.A.A.A.A.A.A.A.A.A.S.Z o.3.#.#.#.#.#.#.#.#.@.4.5 =.,.>.>.,.,.>.,.,.,.>.,.t Q.).E.^.^.",
"^.^.^.^.I r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.S.F.F.F.F.F.F.F.F.F.F.F.F.A.A.A.A.A.A.A.A.A.A.A.F.v O.5.4.4.4.4.4.4.4.4.4.5.6 -.<.,.,.,.,.,.,.,.,.,.,.u Q._.!.^.^.",
"^.^.^./.k r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.s.Z F S F F F S F F S F S S C.A.A.A.A.A.D.A.A.A.A.F.v 5 r w w w w w w r w w r + u p p p p p p p p p p s # !.).^.^.^.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.S W } ` ` ` ` ` ` ` ` ` o.< x.F.A.A.A.A.A.A.A.A.A.A.V.y.z.t.t.t.x.t.t.t.t.t.t.u.a.p.p.p.n.p.p.p.p.p.p.n.* E.].^.^./.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.S.A.A.Z.F.S O.6.4.4.4.4.4.4.4.4.4.5.q x.F.A.A.A.A.A.A.A.A.A.A.A.F.F.F.F.F.F.F.F.F.F.F.F.D.D.H.D.D.D.H.D.H.D.D.H.F.x R.`.E.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.S ` 4.@.#.#.#.#.#.#.@.@.4.0 c.D.A.A.A.A.A.A.S.A.A.A.A.A.Z.A.Z.Z.A.Z.A.A.A.Z.Z.A.Z.A.A.A.A.A.A.Z.A.Z.Z.D.l R.`.^.^.^.",
"^.^.^.^.j e.F.Z.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.F.A } 4.#.#.#.#.3.3.3.3.@.4.0 z.F.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.l R.`.^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.S } 4.#.3.3.#.3.3.#.3.#.4.0 z.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.l R.`.^.^.^.",
"^.^.^./.j e.F.Z.A.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.Z.F.S } 6.#.3.#.3.#.3.3.3.@.4.0 x.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.x R.`.^.^.^.",
"/.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.F.Z } 3.#.#.3.#.#.3.3.3.#.4.q x.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.D.l R.].^.^.^.",
"^.^.^./.j e.F.Z.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.F.A } 4.#.3.3.3.3.3.#.#.#.4.0 x.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.D.m R.].^.^.^.",
"^.^.^.^.j r.F.Z.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.F.S } 6.#.#.#.#.3.3.#.3.#.4.0 x.F.A.A.A.A.D.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.l R./.^.^.^.",
"^.^.^./.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.F.S } #.#.#.3.3.3.#.3.#.#.4.0 x.A.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.D.l R.].^.^.^.",
"^.^.^.^.I e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.A.Z.A.A.A.Z.Z.F.S ` 4.@.#.#.@.#.#.#.#.@.4.7 x.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.Z.A.A.Z.A.Z.A.Z.A.Z.A.l R.].^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.A.D.F.F.F.F.F.F.F.F.F.F.F.K.S [ 5.4.4.4.4.4.4.4.4.4.5.8 x.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.D.F.F.F.F.F.S.F.F.F.S.F.G.x R.].^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.s.v S Z A S A Z S A S Z F & 4 q 8 8 8 8 8 8 8 8 8 e + m.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.w.Z H S H Z Z H H Z H Z H & E./.^.^./.",
"^.^.^.^.j e.F.A.A.A.A.A.A.D.A.A.F.S W o.} } } } ` } } } ` +.4 3 E T R R R R R R R T E : c.S.A.D.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.c Y Q E Q E Q E Q E Q E ! O ^.].^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.F.F ` 6.3.4.4.4.4.4.4.4.4.5.9 R / / / / / / / / / / / 1 c.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.S.c ! ( / ( / / / / / ( ^ ( : ~.(.^.^.^.",
"^.^.^.^.j r.F.A.A.A.A.A.A.A.A.Z.F.F ' 6.@.#.#.#.#.#.#.#.@.4.8 T / ^ / / / / / / / ^ / 1 c.F.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.D.c ! ( ^ / ^ / / / / / ^ / : ~.(.^.^.^.",
"/.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.F.F ` 4.@.3.#.3.#.#.3.#.@.4.8 R / / / / / / / / / ^ / 1 c.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.c ! / / / / / / / / / / / > ~.(.^.^.^.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.Z.F.S ` 4.#.3.3.3.3.#.3.#.#.4.8 R / / / / / / / / / ^ / 1 c.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.c ~ / / / / / / / / / ^ / > ~.(.^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.F.F ` 4.#.3.#.#.3.3.#.3.#.4.8 R / / / / / / / / / ^ / 1 c.F.A.D.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.Z.F.v ! / ^ / / / / / / / ^ / : ~.(.E.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.D.A.F.S ` 4.#.3.3.3.#.3.#.3.#.4.8 R / / / / / / / / / ^ / 1 c.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.H.c ! ( / / / / / / / / / / > ~.(.^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.Z.F.F ` 4.#.3.3.#.3.3.3.#.#.4.8 R / / / / / / / / / / / 1 c.D.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.c ! / / / / / / / / / / / > ~.(.!.^./.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.F.F ` 4.#.#.3.3.#.#.3.3.#.4.8 R / / / / / / / / / ^ / , c.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.D.c ! ( ^ / / / / / / / ^ / : ~.(.^.^.^.",
"^.^.^.^.I r.F.A.A.A.A.A.A.A.A.Z.F.F ` 4.@.3.3.3.3.3.#.3.#.4.8 T / / / / / / / / / / / 1 c.D.Z.A.Z.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.c ! / / / / / / / / / / / > ~.].^.^./.",
"^.^.^./.k r.F.Z.A.A.A.A.A.A.A.Z.F.S ' 4.@.#.#.@.#.#.#.#.@.4.8 T / ^ / ^ ^ ^ ^ / ^ ^ / , c.F.Z.A.A.A.A.Z.A.Z.A.A.A.A.Z.Z.Z.A.A.Z.A.A.Z.Z.A.c ! ( ^ ^ / ^ ^ ^ / ^ ^ / : ~./.^.^.^.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.F.F [ 6.4.4.4.4.4.4.4.4.4.5.8 R / / / / / / / / / ^ / 1 J.G.F.H.D.D.F.F.D.D.F.F.F.F.F.F.D.F.F.F.F.F.F.D.G.v ! / / / / / / / / / ^ / > ~.(.^.^./.",
"^.^.^.^.j e.F.A.A.D.A.A.A.A.A.Z.F.D < q 7 0 0 0 0 0 0 0 7 w + O 1 > , , , , , , , , 1 o z N v v v v v v N c v v N Z Z Z Z Z Z Z Z Z Z Z D & > 2 , 2 1 1 1 2 1 1 2 2 o ~.`.^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.D.C.z.x.x.x.x.x.x.x.x.x.x.v.b { O.] ] ] ] ] ] ] ] ] O.4 G h.K L L L L L L L L h.= Y ! Q Q Q Q Q Q Q Q Q ~ : &.;.-.-.-.-.-.=.-.-.=.;.$ Q.).^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.Z.F.S.F.F.F.S.F.F.F.S.S.F.Z } 5.5.4.4.3.4.3.4.4.3.5.8 g.U.P.P.P.P.P.I.P.P.P.Y.C Q ( / / / ( / / / ( / / > ;.<.>.<.,.<.,.<.<.,.<.,.t Q.).^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.A.A.A.Z.A.A.A.A.Z.A.A.A.Z.F.Z ` 4.@.3.#.#.#.#.#.#.@.4.7 f.I.k.k.k.L.k.k.k.k.k.P.C Q / ^ / / / / / / / ^ / > -.<.>.,.,.,.,.,.,.,.>.,.t Q.).^.^.^.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.A.A.Z.F.S } 4.@.3.#.#.3.3.3.#.#.4.8 f.I.k.L.L.L.L.L.L.L.k.U.V Q / ^ / / / / / / / ^ / , ;.,.,.,.,.,.,.,.,.,.,.,.u Q.).E.^.^.",
"/.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.F.A } 4.#.3.#.#.3.3.#.#.#.4.8 f.I.j.L.L.L.L.L.L.L.k.I.V Q / / / / / / / / / ^ / , ;.,.,.,.,.,.,.,.,.,.,.,.u Q.).^.^.^.",
"^.^.^.^.j e.F.Z.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.F.Z ` 4.#.3.3.3.#.3.3.#.#.4.8 f.I.L.L.L.L.L.L.L.L.k.P.C Q / / / / / / / / / / / > ;.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^./.j r.F.Z.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.A.Z.F.S } 4.#.3.#.3.#.#.3.3.#.4.8 f.I.L.L.L.L.L.L.L.L.k.U.V Q / / / / / / / / / ^ / > ;.<.,.,.,.,.,.,.,.,.,.,.t Q.).E.^.^.",
"^.^.^./.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.S } 4.#.3.#.3.3.3.3.#.#.4.q f.I.j.L.L.L.L.L.L.L.k.U.V Q / / / / / / / / / / / , ;.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.I r.F.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.S } 3.#.#.#.#.3.3.#.3.#.4.7 f.I.L.L.L.L.L.L.L.L.k.U.C Q / / / / / / / / / ^ / , ;.,.,.,.,.,.,.,.,.,.>.,.t Q.).^.^.^.",
"^.^.^./.j r.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.F.A } 4.#.3.3.3.3.#.3.3.#.4.8 f.I.L.L.L.L.k.k.L.L.k.U.V Q / / / / / / / / / / / > ;.<.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.Z.F.Z ` 3.@.#.#.#.#.@.#.#.@.4.7 f.I.L.L.k.k.k.k.k.k.k.U.V Q / ^ / ^ ^ / ^ / ^ ^ / > -.,.>.,.>.,.,.,.,.,.,.,.t Q.).^./.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.F.A O.6.4.4.4.4.4.4.4.4.4.5.8 g.Y.I.I.U.U.U.U.U.U.P.Y.C Q / / / / / / / / / / / , ;.<.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.D < q 6 7 7 7 7 7 7 7 7 q + = ; - - - - - - - - - - . : 1 , 1 , , , , , , , 2 o t i i i i i i i i i u a   !.).^.^.^.",
"^.^.^.^.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.C.c.v.v.x.x.x.x.x.x.x.x.x.M.m.m.J.u.m.m.m.m.m.m.u.V.B &.;.-.-.;.-.-.-.-.-.-.:.y d.N.b.b.n.n.b.b.n.n.b.N.B R.'.^.^.^.",
"^.^.^.^.j e.F.Z.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.A.F.F.F.F.S.F.F.F.S.F.F.S.A.F.A.F.A.F.A.F.D.A.G.N =.<.,.,.<.<.<.<.,.<.>.,.i B.H.D.D.D.D.H.D.D.H.D.H.l R./.^.^.^.",
"^.^.^./.j e.G.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.Z.Z.D.M =.,.,.,.,.,.,.,.,.,.>.,.u N.D.Z.Z.A.A.A.A.A.A.A.D.l R.].^.^.^.",
"/.^.^.^.j e.F.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.F.D =.,.,.,.,.,.,.,.,.,.,.,.i N.D.A.A.A.A.A.A.A.A.Z.D.x R.].^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.M =.,.,.,.,.,.,.,.,.,.,.,.u N.D.A.A.D.A.A.A.A.A.A.D.l R.].^.^.^.",
"^.^.^./.j e.F.A.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.D.M =.,.,.,.,.,.,.,.,.,.,.,.u N.D.A.A.A.A.A.A.A.A.A.D.l R.].^.^.^.",
"^.^.^.^.j e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.M =.,.,.,.,.,.,.,.,.,.,.,.i N.D.A.A.A.A.A.A.A.A.A.D.x R.].^.^.^.",
"^.^.^.^.I e.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.M =.<.,.,.,.,.,.,.,.,.,.,.u N.H.Z.A.A.A.A.A.A.A.A.D.l R.`.^.^.^.",
"^.^.^./.j r.F.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.N =.,.,.,.,.,.,.,.,.,.>.,.u N.D.A.A.A.A.A.A.A.A.A.D.l R.`.^.^.^.",
"^.^.^.^.k r.F.A.A.A.A.A.A.A.A.A.A.A.A.D.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.D.M =.,.,.,.,.,.,.,.,.,.,.,.u N.D.A.A.A.A.A.D.A.A.Z.D.l R.'.^.^.^.",
"^.^.^.^.j r.F.Z.Z.A.A.A.A.Z.A.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.Z.A.A.A.A.A.A.A.Z.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.D.A =.,.>.,.,.,.,.,.,.,.>.,.u b.D.Z.A.Z.A.A.Z.A.A.Z.A.l R.'.^.^./.",
"^.^.^.^.j i.G.D.D.D.D.D.D.D.D.D.D.D.A.A.A.A.A.A.A.A.A.A.A.A.D.D.D.D.D.A.F.F.F.F.F.F.F.F.A.A.A.A.A.A.A.A.A.A.A.D.M -.,.,.,.,.,.,.,.,.,.,.,.u B.H.D.D.D.D.D.D.D.H.H.F.l R.'.^.^.^.",
"^.^.^.^.I & N n M M n n n n n n n l V.Z.A.A.A.A.A.A.A.A.A.D.w.z M v b x x b b b b b b x C.A.A.A.A.A.A.A.A.A.Z.D.M $ i u u u u u u u u u i   B N n M n n n n n n n M . ^./.^.^.^.",
"^.^.^.^.J $.:.-.-.;.;.-.-.;.-.-.:.i a.D.Z.A.A.A.A.A.A.A.A.F.A 2.9.8.8.8.8.8.8.8.8.8.9.d z.F.A.A.A.A.A.A.A.A.A.D.v ) .. . . . . . . . .| X.< &.;.-.-.;.-.-.-.-.-.-.:.y Q.'.^.^.^.",
"^.^.^./.J %.<.,.,.,.,.,.,.,.,.>.,.p n.D.A.A.A.A.A.A.A.A.A.F.A 7.q.q.0.0.0.0.0.0.0.q.0.h z.F.A.A.A.A.A.A.A.A.Z.F.v O.5.4.4.4.4.4.4.4.4.4.5.6 =.<.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"/.^.^.^.J %.,.>.,.,.,.,.,.,.,.>.,.p p.D.A.A.A.A.A.A.A.A.A.F.A 1.q.q.0.0.0.q.0.0.q.q.0.g l.F.A.A.A.A.A.A.A.A.A.F.b o.3.#.#.#.#.#.3.#.#.#.4.5 =.,.,.,.>.,.,.,.,.,.,.,.t Q.).!.^.^.",
"^.^.^.^.J %.,.,.,.,.,.,.,.,.,.,.,.p p.D.Z.A.A.A.A.A.A.A.A.G.A 7.0.0.0.0.0.0.0.0.0.q.0.h l.D.A.A.A.A.A.A.A.A.Z.F.v o.4.#.3.3.3.#.3.3.3.#.4.5 -.<.,.,.,.,.,.,.,.,.,.,.u Q.).^./.^.",
"^.^.^.^.J %.,.,.,.,.,.,.,.,.,.>.,.p p.H.A.A.A.A.A.A.A.A.A.F.A 7.0.0.0.0.0.0.0.0.0.q.0.h l.F.A.A.A.A.A.A.A.A.Z.D.Z o.4.#.3.#.#.3.3.#.#.#.4.5 -.,.,.,.,.,.,.,.,.,.>.,.t Q.).^.^./.",
"^.^.^.^.J %.<.>.,.,.,.,.,.,.,.,.,.p p.H.Z.A.A.A.A.A.A.A.A.F.A 7.0.0.0.0.0.0.0.0.0.q.0.g l.F.A.A.A.A.A.A.A.A.A.F.v o.3.#.3.#.3.3.3.3.3.#.4.5 -.<.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.I %.<.,.,.,.,.,.,.,.,.,.,.p n.H.Z.A.A.A.A.A.A.A.Z.F.A 7.q.0.0.0.0.0.0.0.0.q.0.h l.D.A.A.A.A.A.A.A.A.A.F.Z | 3.#.3.#.3.#.#.3.#.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.u Q.).E.^.^.",
"^.^.^./.I %.,.>.,.,.,.,.,.,.,.>.,.p p.D.A.A.A.A.A.A.A.A.Z.F.A 7.0.0.0.0.0.0.0.0.0.q.0.h z.F.A.A.A.A.A.A.A.A.Z.F.v o.4.#.3.3.3.#.3.#.3.#.4.5 -.<.,.,.,.,.,.,.,.,.>.,.t Q.).^.^.^.",
"^.^.^.^.J %.,.,.,.,.,.,.,.,.,.,.,.p p.D.A.A.A.A.A.A.A.A.A.F.A 7.0.0.0.0.0.0.0.0.0.q.0.h z.F.Z.A.A.A.A.S.A.A.A.F.v o.4.#.#.#.3.3.3.3.#.#.4.5 -.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.J %.<.,.,.,.,.,.,.,.,.,.,.p p.D.A.A.A.A.A.A.A.A.A.F.A 7.0.0.0.0.0.0.0.0.0.q.0.h z.F.A.A.A.A.A.A.A.A.A.F.b o.4.@.3.3.#.3.#.3.3.#.4.5 -.<.,.,.,.,.,.,.,.,.,.,.u Q.).^.^.^.",
"^.^.^.^.J %.,.>.,.,.,.,.>.,.,.>.,.p n.D.Z.A.A.Z.Z.A.Z.A.Z.F.A 1.0.q.q.q.q.q.q.q.q.q.q.g z.F.Z.Z.A.A.A.Z.Z.A.Z.F.b o.4.@.#.#.@.3.3.@.3.@.4.5 =.<.>.,.,.,.>.,.,.,.>.,.t Q.).!.^.^.",
"^.^.^.^.J %.<.,.,.,.,.,.,.,.,.,.,.p a.H.D.D.A.D.D.F.D.D.D.G.A 7.0.q.q.0.0.0.q.q.0.q.0.g x.G.A.F.D.D.D.D.D.F.A.H.v O.5.4.4.4.4.4.4.4.4.4.5.6 -.,.,.,.,.,.,.,.,.,.,.,.t Q.).^.^.^.",
"^.^.^.^.I # u u t t t t t u u t u # * m l x l x l x l x l n & % d d d d f d d d d d f + B x l x l l x l l l l n . @ 6 4 4 5 6 6 4 4 4 6 6 X y u t t t u t u t u u u   !._.^.^.^.",
"^.^./.T.T.!.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.!.R.R.R.R.R.R.R.R.R.R.R.R.E.W.W.W.W.W.W.W.W.W.W.W.W.^.R.R.R.R.R.R.R.R.R.R.R.R.^.~.W.~.W.W.W.W.W.W.W.W.W.!.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.!.[./.^./.^.",
"^./.^.^./.].).).).).).)./.].).)._.)./.].].].`.`.`.`.].].].].(._._._._._._.]._._._._.)./.].].`.`.]./.].].].].].].`./.].]._._._.]._.)._._.(./.].).).).).).).).).).].).`.^.^.^./.^.",
"^.^.^.^.^.^.^.^.^.!.E.^.^.^.^.^.^.^.^.^.^.^.^.^.^.E.^.^.^.^.^.^.^.^.E.^.^.E.^.^.^.^.^.^.^.^.^.^.^.^.^.^.!.^.^.E.^.^.E.^.^.^.^.T.^.^.^.E.^.^.^.^.!.^.E.^.E.^.^.^.E.^.^.^.^.^.^.^.",
"^./.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^././.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^./.^.",
"^.^.^.^./.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^./.^.^.^.^.^.^.^.^./.^.^.^.^.^./.^.^.^./.^.^.^.^./.^.^.^.^.^.^.^.^.^.^."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 192 2 ",
"   c #1D321B",
".  c #6C1401",
"X  c #76010E",
"o  c #5D072B",
"O  c #6D113A",
"+  c #70153D",
"@  c #583733",
"#  c #693830",
"$  c #53190D",
"%  c #214803",
"&  c #127412",
"*  c #316900",
"=  c #347000",
"-  c #0A7831",
";  c #2A792C",
":  c #0D5631",
">  c #794200",
",  c #54433D",
"<  c #6C4239",
"1  c #65423A",
"2  c #744431",
"3  c #734638",
"4  c #654B2C",
"5  c #6C723B",
"6  c #616638",
"7  c #033F59",
"8  c #1E2274",
"9  c #37306A",
"0  c #510079",
"q  c #473869",
"w  c #0F415E",
"e  c #16526C",
"r  c #384065",
"t  c #53566B",
"y  c #9A1D00",
"u  c #8F020A",
"i  c #A50500",
"p  c #AB0501",
"a  c #B20101",
"s  c #BE0100",
"d  c #A31E00",
"f  c #830024",
"g  c #DC0000",
"h  c #D70001",
"j  c #E20000",
"k  c #ED0000",
"l  c #FD0101",
"z  c #924901",
"x  c #9C5000",
"c  c #A75B00",
"v  c #AC5B02",
"b  c #B25A02",
"n  c #B65A02",
"m  c #A76000",
"M  c #85592B",
"N  c #C96800",
"B  c #D16600",
"V  c #D86C00",
"C  c #DA7400",
"Z  c #E16101",
"A  c #EC6E01",
"S  c #F26600",
"D  c #FB7E01",
"F  c #FE7400",
"G  c #996F6F",
"H  c #8C776F",
"J  c #827779",
"K  c #997070",
"L  c #009F00",
"P  c #02A505",
"I  c #02AA03",
"U  c #08A902",
"Y  c #01BA01",
"T  c #06B500",
"R  c #2D842D",
"E  c #00CD00",
"W  c #00C300",
"Q  c #00DC01",
"!  c #01E301",
"~  c #00ED00",
"^  c #02F501",
"/  c #02FE01",
"(  c #04FF08",
")  c #6F8E6F",
"_  c #6F946F",
"`  c #6F996F",
"'  c #669066",
"]  c #709A6F",
"[  c #6F9970",
"{  c #719A71",
"}  c #9C9B02",
"|  c #B1B104",
" . c #A5A602",
".. c #F38301",
"X. c #FE8401",
"o. c #FF8B01",
"O. c #F68A00",
"+. c #DDDC01",
"@. c #E0DE00",
"#. c #ECEC00",
"$. c #FDFD02",
"%. c #9B856F",
"&. c #9B9B6E",
"*. c #878875",
"=. c #999970",
"-. c #998470",
";. c #2C1F8B",
":. c #2B1890",
">. c #162A97",
",. c #2F218D",
"<. c #2E338C",
"1. c #2932A7",
"2. c #2139A7",
"3. c #2939A6",
"4. c #2638AA",
"5. c #2434B2",
"6. c #2336B9",
"7. c #2838BB",
"8. c #1A33A8",
"9. c #5F008F",
"0. c #5F0099",
"q. c #6C008C",
"w. c #60009C",
"e. c #710190",
"r. c #6A00A4",
"t. c #7E00A3",
"y. c #7E00B2",
"u. c #7200BA",
"i. c #6F00B5",
"p. c #3E4683",
"a. c #787C99",
"s. c #757996",
"d. c #747B86",
"f. c #1E39D5",
"g. c #1D3ADC",
"h. c #1D34DC",
"j. c #1724C8",
"k. c #2B34D5",
"l. c #253ADB",
"z. c #273BC9",
"x. c #1039E9",
"c. c #153BFB",
"v. c #122CF6",
"b. c #223BED",
"n. c #2A34E6",
"m. c #243DFF",
"M. c #243FF7",
"N. c #343BFF",
"B. c #3032E3",
"V. c #1D42DC",
"C. c #2340DC",
"Z. c #2345FF",
"A. c #2C47FF",
"S. c #244DFF",
"D. c #2C4AFF",
"F. c #3149F5",
"G. c #3443FE",
"H. c #334CFE",
"J. c #394DFE",
"K. c #3047F0",
"L. c #3551FF",
"P. c #3A53FE",
"I. c #2549F7",
"U. c #8401A6",
"Y. c #8301B4",
"T. c #8501BA",
"R. c #8800BB",
"E. c #8C02C1",
"W. c #818F81",
"Q. c #ABB2AB",
"!. c #D2D0C5",
"~. c #D2D2CD",
"^. c #C5CDD5",
"/. c #CACFD5",
"(. c #D5C5D5",
"). c #D2CFD2",
"_. c #D4D4D4",
"`. c #D8D6D4",
"'. c #D4D8D4",
"]. c #D5D6D8",
"[. c #CFD2D1",
"{. c #E7E6DF",
"}. c #E8E6DF",
"|. c #DFDFE9",
" X c #E9DFE9",
".X c #E0DFE0",
"XX c #DFE4E9",
"oX c #DFE9E9",
"OX c #E5E5E4",
"+X c #E8E7E3",
"@X c #E9E1E9",
"#X c #E3E6E9",
/* pixels */
"_._._.]._._.`._._.'.`._.]._._._.].`._._._._.'._._._.]._.`._._.]._._.`.]._._._.`._.]._._._._._._.",
"_._.`._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.`._._._._._._._._._._.`._.].`.",
"_._._._.].].].].].]._.'.].].].].].].].].].].]._.].].].].].].`.`.`.`.`.].`._.'.'.'._.'._._._._._.",
"_._.]._.~.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.[.^.^.^.^.^./.(.(.(.(.(.(._._.'._.`.",
"_._._.~.t p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p., M M M M M 4 ; R R R R ; ) @X_._._.",
"_._.].!.p.Z.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.H.c.2 X.D D D X.c Q / / / ( ~ `  X)._.'.",
"]._.].!.p.A.H.H.H.H.H.J.J.H.H.H.J.H.H.H.H.H.H.H.H.H.J.H.J.Z.2 X...D D X.c Q / / / ( ~ {  X).'._.",
"`._.`.!.p.A.H.H.H.H.D.H.A.H.H.H.H.H.H.H.H.H.H.H.H.H.D.H.J.Z.2 X.D D D X.c Q / / / / ~ `  X)._._.",
"_._.].!.p.A.H.H.H.H.H.H.H.H.H.H.H.H.H.H.F.H.D.L.H.H.A.H.J.Z.2 X.D D D X.c Q / / / ( ~ `  X_._.].",
"_._.].!.p.A.L.H.H.H.H.H.H.H.H.H.H.L.H.L.L.L.L.L.J.D.H.H.J.Z.2 O.X.X...o.c Q / / / / ~ `  X_._._.",
"]._.].!.p.A.H.H.H.H.H.H.H.H.H.H.H.z.6.6.6.6.6.7.F.H.H.H.J.Z.@ N n n n N > P Y Y Y Y P ) @X[._.`.",
"_._.].!.p.A.H.H.H.H.H.H.H.H.H.L.A.@ V B B B Z z g.L.H.H.A.H.l.f.f.f.f.f.l.k.k.k.k.k.j.s.{.[._._.",
"`._.].!.p.A.J.D.H.H.H.H.H.H.H.H.Z.< o.X.X.X.o.b g.L.H.H.H.H.J.L.J.J.L.L.J.L.L.H.L.P.I.s.}.)._._.",
"_._.].!.p.A.H.H.H.H.H.H.H.H.H.H.Z.< X.D D D X.v g.J.H.H.H.H.D.H.H.H.D.H.D.H.H.H.H.J.b.s.OX[._._.",
"]._.].!.p.A.J.H.H.H.H.H.H.A.H.H.Z.< X.D D D X.b g.L.H.H.H.H.J.H.H.H.H.H.H.H.H.H.H.J.b.a.{.[._._.",
"_._.].!.p.A.J.D.H.H.H.H.H.J.J.J.Z.< X.D X.D X.v g.J.D.H.H.H.H.H.H.H.H.H.H.H.H.H.J.J.b.a.+X_.`.].",
"_._.].!.p.A.H.D.H.H.L.Z.Z.Z.Z.A.c.1 o.......O.v g.L.H.H.H.H.H.H.H.H.H.H.H.S.S.S.S.S.x.a.{.[._.'.",
"`._.].!.p.A.H.H.H.L.z.@ < < < # 1 $ y y y y d . C.J.H.H.H.H.H.H.H.H.A.L.7.o + + O O O t OX)._._.",
"_._.].!.p.A.H.H.H.L.6.B o.X.X.X.O.y l l l l l a V.J.D.H.H.H.H.H.H.H.H.L.1.j l l l l l K oX)._._.",
"_._.'.!.p.A.J.D.H.L.6.B X.D D D ..y l l l l l a V.J.H.H.H.H.H.H.H.H.H.L.1.g l l l l k K #X_._.].",
"_._.].!.p.A.L.H.H.L.6.B X.D X.D ..y l l l l l a V.J.H.H.H.H.H.H.H.H.H.L.1.j l l l l k K oX]._._.",
"]._.].!.p.D.H.H.F.L.6.B X.D D D ..y l l l l l a g.H.H.D.A.H.H.H.H.F.F.H.1.g l l l l k K oX'._._.",
"_._.].!.p.D.H.D.H.L.6.B o.X.X.o.O.y l l l l l a V.P.L.L.L.J.H.L.H.L.L.L.1.j l l l l k K oX_.'.'.",
"`._.].!.q D.H.H.H.L.6.z n v b b v . a a a a s X >.7.5.5.5.5.5.4.5.5.5.6.8 i a a p p i H #X_._._.",
"_._.].!.p.A.J.H.A.J.F.g.g.g.g.l.x.@ C N N N C z 0 e.q.q.q.w.X j h h h j u W ! Q Q Q E _ @X[._.`.",
"_._.].!.p.A.H.H.H.H.H.L.L.L.J.J.Z.< o.X.o.X.o.b r.R.Y.T.T.u.f l l l l l i ! / / / ( ~ ` @X_._.].",
"'._.].!.p.A.H.H.H.H.H.H.H.H.H.H.Z.< X.D X.D X.b 0.Y.Y.y.Y.i.f l l l l l i ! / / / / ~ ` @X)._._.",
"]._.].!.p.A.H.H.H.H.H.H.H.H.H.H.Z.< X.D D D X.b 0.T.y.y.Y.u.f l l l l l i ~ / / / ( ~ ` @X~._._.",
"_._.].!.p.A.J.D.H.H.H.H.H.H.H.H.Z.< o.D X.D X.b w.E.y.y.Y.u.f l l l l l i ! / / / ( ~ {  X)._._.",
"_._.].!.p.A.H.H.H.H.H.H.H.H.H.J.Z.# X.D X...X.b 9.t.t.t.U.r.f l l l l l i ! / / / / ~ `  X[._._.",
"_._.'.!.p.A.H.H.D.H.H.H.H.H.H.H.D.<.q q q q q 9 ,.,.,.,.,.:.  = * * * = % w e e e e w t OX_.`._.",
"]._._.!.p.A.H.H.H.H.H.H.H.H.H.H.H.L.A.A.D.D.D.D.L.S.L.L.L.G.- / / / / / I B.J.G.J.P.N.W.+X).]._.",
"`._.].!.p.A.L.H.H.H.H.H.H.H.H.H.H.H.H.H.F.H.H.F.H.H.H.H.L.N.- / / / ^ / I n.L.F.H.P.x.a.+X).`._.",
"_._.].!.p.A.J.H.H.H.H.H.H.H.H.H.H.H.H.H.J.H.H.J.H.H.H.H.H.N.- / / / / / I n.L.H.D.L.b.a.}._.`._.",
"_._.].!.r A.H.J.D.H.H.D.H.H.H.H.D.H.H.H.H.H.F.D.H.H.H.H.H.N.- / ^ / ^ / I n.L.H.F.P.b.a.+X)._._.",
"_._.].!.p.H.H.L.L.J.J.H.H.H.H.H.H.H.J.H.H.J.L.H.H.H.H.A.H.N.- / / / / / I B.P.L.L.P.b.a.{.).`._.",
"]._.].~.r 8.2.2.2.2.2.K.H.H.H.H.H.7.3.4.3.3.3.3.K.H.H.H.H.G.: T U U U T & >.2.2.2.4.>.d.+X[._._.",
"_._.'.(.; ! Q Q Q ~ L k.L.D.H.J.m.6 #.+.@.+.#.} h.L.A.H.H.Z.# S V Z Z S z Y ! Q ! Q E _ @X[._._.",
"`._.].(.R / / / ^ / Y k.L.H.D.L.m.5 $.$.$.$.$.| h.P.H.H.J.Z.2 o.D X.X.o.m Q ( / / ( ~ {  X_._._.",
"_._.'.(.R / / / / / Y k.L.H.H.H.m.5 $.$.$.$.$.| h.L.H.H.H.Z.2 X.D D D X.c Q / / / ( ~ `  X_._.`.",
"'.'.'.(.R / / / / / Y k.L.H.H.H.m.5 $.$.$.$.$.| h.L.H.J.J.Z.2 X.D D D o.v Q / / / / ~ { @X)._._.",
"_.'.'.(.R / ( ( ^ / Y k.P.P.H.P.m.5 $.$.$.$.$.| l.P.J.P.L.A.2 o.X.X...o.v Q / / ( ( ~ {  X_._._.",
"_._.].(.; ^ ~ ~ ~ / I j.I.b.b.b.v.6 $.#.#.#.$. .j.M.x.b.b.v.# D A A A F x E / ~ ~ ^ Q {  X_._._.",
"_._.].[.*.` ` ` { ] _ s.s.a.a.a.s.*.=.=.=.=.=.*.s.a.a.a.a.a.J %.-.-.%.%.H _ ` ` ` { ' Q.]._._.'.",
"]._._._.OX X X X X@X@X+X}.{.{.{.{.OXXX|.|.|..X#XOX+X+X{.+X{.OXXXXXXXXXXX#X@X@X@X X X@X.X]._.'.`.",
"_._._.]._._.[.[.).[.)._.).).[.).)._._.).)._.)._.[.[.[.[.)._.).).)._._.).)._.).~.[.)._._.].`._._.",
"`.]._._._._._._._._.]._.`._._._._._._._._._._._._.].'._._._._.]._._._._._.]._.'._._.]._.`.]._.`.",
"_._._._._.`.'._._.'.'._._._._._.].`._.]._._.]._._._._._.]._.`._.]._._.]._._.`._._._.'._._._._._."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 179 2 ",
"   c #7C0B01",
".  c #532802",
"X  c #733200",
"o  c #6A3D27",
"O  c #663C32",
"+  c #2B7E00",
"@  c #126423",
"#  c #746D01",
"$  c #736600",
"%  c #7C4933",
"&  c #381B5C",
"*  c #342F78",
"=  c #470255",
"-  c #563840",
";  c #47026D",
":  c #630074",
">  c #4A2373",
",  c #4A3B74",
"<  c #44376A",
"1  c #124D74",
"2  c #175574",
"3  c #195775",
"4  c #0C4C6A",
"5  c #3C4877",
"6  c #615F41",
"7  c #7A785A",
"8  c #4C5568",
"9  c #4A5673",
"0  c #60717A",
"q  c #70727F",
"w  c #8D0600",
"e  c #990500",
"r  c #9F1200",
"t  c #A90500",
"y  c #B20800",
"u  c #BA0500",
"i  c #A31001",
"p  c #A60613",
"a  c #C50000",
"s  c #CC0001",
"d  c #D30001",
"f  c #E40000",
"g  c #FD0101",
"h  c #F70200",
"j  c #82460E",
"k  c #8E500F",
"l  c #9D5200",
"z  c #AF5A09",
"x  c #B05E00",
"c  c #A45511",
"v  c #A55A10",
"b  c #AC5911",
"n  c #844C31",
"m  c #82613C",
"M  c #C56500",
"N  c #C96400",
"B  c #CB6B00",
"V  c #D46900",
"C  c #DB7601",
"Z  c #DD7D00",
"A  c #EA6C00",
"S  c #EA6300",
"D  c #FE6E00",
"F  c #EA7400",
"G  c #E97E00",
"H  c #FD7401",
"J  c #F77D03",
"K  c #FC7D01",
"L  c #F67600",
"P  c #995A5A",
"I  c #885B5E",
"U  c #A05A5A",
"Y  c #896541",
"T  c #9D7B58",
"R  c #A37D5A",
"E  c #009F01",
"W  c #328C01",
"Q  c #359202",
"!  c #04A811",
"~  c #0B8232",
"^  c #368136",
"/  c #02CB01",
"(  c #00D400",
")  c #00EA00",
"_  c #00E600",
"`  c #00F601",
"'  c #01FD02",
"]  c #01FF08",
"[  c #3C8741",
"{  c #428842",
"}  c #418641",
"|  c #579C59",
" . c #559157",
".. c #5AA05A",
"X. c #59A054",
"o. c #7C907C",
"O. c #A4A611",
"+. c #A6A814",
"@. c #FD8302",
"#. c #FF8B00",
"$. c #CBCB00",
"%. c #C8C700",
"&. c #FDFD01",
"*. c #F7F701",
"=. c #999959",
"-. c #88885E",
";. c #A3A359",
":. c #183C8F",
">. c #28309F",
",. c #1630AF",
"<. c #2736A2",
"1. c #3239A2",
"2. c #3137A2",
"3. c #233FB3",
"4. c #580487",
"5. c #65008B",
"6. c #670095",
"7. c #7D00AF",
"8. c #2141A2",
"9. c #4F5688",
"0. c #4F5787",
"q. c #515789",
"w. c #484F84",
"e. c #656D9E",
"r. c #666C99",
"t. c #676987",
"y. c #686EA1",
"u. c #676FA5",
"i. c #6970A2",
"p. c #1330D3",
"a. c #243BCB",
"s. c #2539CB",
"d. c #283ED4",
"f. c #1E3EED",
"g. c #1E36EE",
"h. c #1535F1",
"j. c #2B38ED",
"k. c #253EFA",
"l. c #293BFB",
"z. c #3439FF",
"x. c #2C2DEE",
"c. c #1C41DB",
"v. c #2646DE",
"b. c #1E46ED",
"n. c #2341EE",
"m. c #2746E5",
"M. c #2440F5",
"N. c #2A45F2",
"B. c #2344FF",
"V. c #2943FF",
"C. c #2C4BFF",
"Z. c #2D49F5",
"A. c #3645FF",
"S. c #334CFE",
"D. c #394AFF",
"F. c #2C52FF",
"G. c #3551FE",
"H. c #3A52FF",
"J. c #8400BA",
"K. c #8600B7",
"L. c #8D00C4",
"P. c #8A00C8",
"I. c #92A692",
"U. c #DAD9CF",
"Y. c #DDCFDD",
"T. c #CFD6DD",
"R. c #D4D4D4",
"E. c #DAD9D5",
"W. c #D6D6DB",
"Q. c #E5E4DA",
"!. c #DADAE8",
"~. c #DFDFE7",
"^. c #E2DEE2",
"/. c #E8DAE8",
"(. c #E8DFE7",
"). c #DAE1E8",
"_. c #DBE8E8",
"`. c #DFE8E7",
"'. c #E6E3E3",
/* pixels */
"R.R.W.R.E.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.U.R.R.R.R.R.R.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.E.R.R.",
"R.R.R.R.R.R.R.W.R.W.R.R.R.R.R.W.R.R.R.R.R.R.R.R.W.R.R.R.R.R.U.R.R.R.R.R.R.R.R.R.R.R.E.R.",
"E.R.R.R.E.U.U.U.U.U.U.U.U.U.E.U.E.U.U.E.U.U.E.U.U.U.E.E.T.T.T.T.T.W.Y.Y.Y.Y.Y.E.R.R.R.W.",
"R.R.R.E.q w.9.9.9.9.9.9.9.9.9.9.0.0.9.9.9.9.9.9.0.0.q.9 m Y Y Y Y 6 { { { { [ -.^.R.R.R.",
"R.R.R.U.9.k.V.k.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.<.A K H K H # ' ' ] ] ] ..^.R.R.R.",
"R.R.R.E.q.V.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.D.S.G.1.F @.@.@.K # ' ' ' ' ' | /.R.R.R.",
"R.R.R.U.q.V.S.S.C.S.S.S.S.S.A.S.S.S.S.S.S.A.S.S.S.S.S.1.F @.K J K # ' ' ] ' ' | /.R.R.R.",
"E.R.R.E.9.V.S.S.S.S.S.S.S.C.S.S.S.S.S.S.D.S.S.S.S.Z.S.1.F @.@.@.@.# ' ' ] ' ' | /.R.R.R.",
"R.R.R.U.9.V.S.S.S.S.S.S.S.S.S.S.B.B.B.B.B.B.S.S.S.S.S.2.F K K J @.# ' ' ] ' ' | /.R.E.R.",
"R.R.R.U.9.V.S.S.S.C.S.S.S.S.S.N.- n % % n O d.S.S.S.S.s.< , , , , * 2 2 2 3 4 0 ^.R.R.R.",
"R.R.R.U.9.V.S.S.S.S.S.S.S.S.H.f.v #.@.@.#.B a.H.S.S.S.S.C.C.C.C.C.Z.A.A.A.D.l.e.E.R.U.R.",
"R.R.R.U.0.V.S.S.S.S.S.S.S.S.S.f.v @.J @.@.N a.S.C.S.S.A.S.S.S.Z.S.S.Z.S.S.G.M.y.Q.R.R.R.",
"R.R.R.U.9.V.S.S.S.S.S.S.S.C.S.f.v @.J J @.N a.G.S.S.S.S.S.S.S.S.S.S.S.S.S.S.M.y.Q.R.R.R.",
"R.R.W.U.9.V.S.S.S.A.S.G.S.S.H.b.v @.@.@.@.N a.S.S.S.S.S.S.S.S.S.S.S.G.S.S.H.M.e.Q.R.R.R.",
"R.R.R.E.9.V.S.S.S.S.M.f.j.b.k.p.k G C C G x a.S.S.S.S.S.S.S.S.S.S.Z.b.b.b.m.h.r.Q.R.R.R.",
"R.R.W.U.9.V.S.S.S.C.- z c c b k   u y y u w a.G.S.S.S.S.S.S.S.A.F.* t p p p t I _.R.R.R.",
"R.R.R.U.9.V.S.S.S.B.% #.@.@.#.Z y g g g g s a.H.S.S.S.S.S.S.S.Z.F.> g g g g h U _.R.R.R.",
"R.R.R.U.9.V.S.S.S.B.% @.J J K C y g g g g a a.G.S.S.S.S.S.S.S.S.F.> g g g g h U !.R.W.R.",
"R.R.R.U.9.V.S.S.S.B.% @.J @.@.C y g h g g a a.G.S.S.Z.S.A.S.S.Z.F.> g g g g h U _.R.R.R.",
"R.R.R.U.9.V.S.S.D.B.n #.@.@.#.Z y g g g g s a.G.S.H.H.D.S.G.S.G.F.> g g g g g U _.R.R.R.",
"R.R.W.U.9.V.S.S.S.B.% V N N N x w d a u d e >.d.a.a.a.s.a.a.a.s.a.> s s s s s P ).R.R.R.",
"R.R.R.U.0.V.S.S.S.S.d.p.a.a.d.,.X C M M B l ; 6.5.: 6.= u d a a d . ( / / / /  .^.R.R.R.",
"R.R.R.U.0.V.S.C.S.S.S.G.S.G.G.n.b #.@.@.#.B 6.P.J.J.P.: f g g g g X ' ' ' ] ` ../.R.R.R.",
"R.R.R.U.9.V.S.S.S.S.S.C.S.A.S.f.c @.J J @.M 4.K.7.K.7.: d g g h g X ' ' ' ' ` ..^.R.R.R.",
"R.R.W.U.9.V.S.S.S.S.S.S.S.S.S.b.c @.J @.@.M 5.J.7.7.P.: f g g h g X ' ' ' ' ` ../.R.R.U.",
"R.R.R.U.9.V.S.S.C.S.S.S.S.S.S.j.v #.@.@.#.B 6.L.K.K.P.: f g g h g X ' ' ' ' ' | /.R.R.R.",
"R.R.R.E.9.V.S.A.S.S.S.S.C.S.S.n.% z c v b j ; 4.; 4.4.= r i i i i . ! ! ! ! E  .^.R.R.R.",
"R.R.R.U.9.V.S.S.S.S.S.S.S.S.S.S.f.f.j.b.b.j.m.v.m.v.N.:.( ` ) ) ' @ x.j.j.j.x.r.Q.R.R.R.",
"R.R.R.U.9.V.S.C.S.S.S.S.S.S.S.S.Z.G.G.S.D.S.G.S.S.S.H.8.` ] ' ' ' ~ S.G.H.G.M.y.Q.R.R.R.",
"R.R.R.E.9.V.S.S.S.S.S.S.S.S.S.S.S.Z.C.S.S.S.S.S.S.Z.S.8._ ] ' ' ' ~ z.G.S.S.l.y.E.R.R.R.",
"R.R.R.U.0.N.S.S.Z.S.S.S.S.C.S.S.S.S.S.S.D.Z.S.S.S.S.D.8._ ' ' ` ' ~ l.G.S.G.M.e.Q.R.R.R.",
"R.R.W.U.0.V.D.A.A.A.S.S.S.S.A.S.C.V.V.V.V.S.S.S.S.S.S.<.) ] ' ' ' @ z.S.A.D.l.y.Q.R.R.R.",
"R.R.R.E.8 4 2 2 2 2 3.S.S.S.S.N.5 9 9 9 9 5 m.S.S.S.G.<.+ Q W W Q @ 1 3 3 3 4 0 ^.R.R.R.",
"R.R.R.Y.{ ' ' ' ' ' 2 A.S.S.G.g.+.&.*.&.&.$.s.S.Z.S.F.1.S H D L D $ ' ' ' ' ' ../.R.R.R.",
"R.R.R.Y.{ ' ] ] ] ' 2 S.S.S.G.g.+.&.&.&.&.$.s.G.S.S.G.1.F @.@.@.@.# ' ' ' ' ' ../.R.R.R.",
"E.R.R.Y.{ ' ' ' ' ' 3 A.Z.S.G.j.O.&.&.&.&.$.s.G.S.S.S.2.F @.J @.K # ' ' ' ' ` | /.R.U.R.",
"R.R.R.Y.{ ' ' ' ] ' 3 A.G.S.H.g.+.&.*.&.&.$.s.H.S.S.H.1.F @.@.@.@.# ' ' ' ] ' ../.R.R.R.",
"R.R.R.Y.{ ' ' ' ] ' 1 l.M.k.B.h.O.&.*.*.&.$.p.V.k.M.B.<.A H H L H $ ` ' ' ' ` ../.R.R.R.",
"R.R.R.W.o.| ....X.| 0 u.e.e.e.r.-.;.;.=.;.=.t.y.r.r.i.t.T R T R R 7 | ......X.I.E.R.R.R.",
"R.R.R.R.W./././././.Q.Q.Q.Q.E.Q.^.!.!.!.!.!.E.Q.Q.Q.Q.Q.).!.).).!.!./.^./././.^.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.",
"E.R.R.R.R.R.E.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.E.R.R.R.R.R.R.R.E.R.R.R.R.",
"R.R.R.E.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.U.R.R.R.R.R.R.R.W.R.R.R.R.R.R.W.R.R.R.R.E."
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 172 2 ",
"   c #3A253B",
".  c #6D291B",
"X  c #6F0039",
"o  c #564600",
"O  c #645501",
"+  c #5F1A57",
"@  c #6F0D4C",
"#  c #761A54",
"$  c #5F3E46",
"%  c #57007B",
"&  c #563F66",
"*  c #0F6341",
"=  c #0C7A50",
"-  c #146B63",
";  c #127263",
":  c #5F515D",
">  c #6A4855",
",  c #744B54",
"<  c #70474C",
"1  c #5F6757",
"2  c #737B55",
"3  c #554063",
"4  c #674963",
"5  c #664663",
"6  c #764D68",
"7  c #497A68",
"8  c #71626F",
"9  c #767A68",
"0  c #AB0102",
"q  c #BA0000",
"w  c #982300",
"e  c #B62B01",
"r  c #BD2A00",
"t  c #C70206",
"y  c #D30101",
"u  c #DB0000",
"i  c #E00000",
"p  c #FE0100",
"a  c #F60405",
"s  c #AF5800",
"d  c #B95B00",
"f  c #B05405",
"g  c #966030",
"h  c #A46B31",
"j  c #B27431",
"k  c #CE6A03",
"l  c #C56706",
"z  c #D36B00",
"x  c #DB6C01",
"c  c #D16600",
"v  c #D27000",
"b  c #DE7200",
"n  c #E06C00",
"m  c #E06500",
"M  c #E97200",
"N  c #F67D06",
"B  c #FA7C03",
"V  c #860046",
"C  c #A24242",
"Z  c #B44242",
"A  c #B67D43",
"S  c #A77242",
"D  c #029F0B",
"F  c #05A203",
"G  c #328C32",
"H  c #2FA930",
"J  c #31A331",
"K  c #33AF33",
"L  c #04C401",
"P  c #02CA01",
"I  c #04C708",
"U  c #08C803",
"Y  c #01D203",
"T  c #00DC01",
"R  c #00E301",
"E  c #05F705",
"W  c #01FE01",
"Q  c #108157",
"!  c #439D44",
"~  c #42A242",
"^  c #43B543",
"/  c #42BB42",
"(  c #619661",
")  c #72A672",
"_  c #A7A704",
"`  c #BCBB3B",
"'  c #FD8202",
"]  c #FF8900",
"[  c #F78504",
"{  c #D2D201",
"}  c #C4C509",
"|  c #FEFE01",
" . c #F6F607",
".. c #A2A241",
"X. c #B6B643",
"o. c #39188E",
"O. c #1E37BB",
"+. c #2333AF",
"@. c #2134B0",
"#. c #431999",
"$. c #6C0091",
"%. c #6E009A",
"&. c #660099",
"*. c #423D8C",
"=. c #4015A4",
"-. c #7E01AE",
";. c #7A01BD",
":. c #444B96",
">. c #5F6488",
",. c #414DA4",
"<. c #4752A4",
"1. c #4954A3",
"2. c #4151AC",
"3. c #565DA6",
"4. c #565EB9",
"5. c #5A65B4",
"6. c #5665B9",
"7. c #2D3EC7",
"8. c #2C3CC8",
"9. c #293ED4",
"0. c #2F3DDF",
"q. c #233ADB",
"w. c #1B39F0",
"e. c #2333E3",
"r. c #253DE0",
"t. c #2C3CE0",
"y. c #2E3CEA",
"u. c #283AFF",
"i. c #7D00C6",
"p. c #2844C5",
"a. c #2C42DA",
"s. c #2842D9",
"d. c #1D42FF",
"f. c #1745FF",
"g. c #2A44E6",
"h. c #2446FF",
"j. c #2C47FF",
"k. c #2648FF",
"l. c #2B49FE",
"z. c #334BF6",
"x. c #3542FE",
"c. c #334CFD",
"v. c #384DF9",
"b. c #3840FF",
"n. c #2551FE",
"m. c #2C51FE",
"M. c #3651FE",
"N. c #3650F7",
"B. c #8600B6",
"V. c #8600AA",
"C. c #8900C0",
"Z. c #D6D4C7",
"A. c #D6D5CD",
"S. c #D7CFD7",
"D. c #DAC7D9",
"F. c #D9CAD9",
"G. c #C7D0DA",
"H. c #C9D2D9",
"J. c #D3D4D3",
"K. c #D8D6D4",
"L. c #D4D8D4",
"P. c #D4D5D8",
"I. c #DFD7DF",
"U. c #DCDDDD",
"Y. c #E0DED2",
"T. c #E2DBDD",
"R. c #DBE2DD",
"E. c #D2D2E4",
"W. c #D2DBE3",
"Q. c #E3D2E3",
"!. c #E0D8E0",
"~. c #D2E3E3",
/* pixels */
"J.J.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.J.K.K.K.K.J.K.L.L.P.P.J.",
"J.J.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.H.G.H.H.F.D.D.D.K.J.K.",
"P.K.>.,.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.2.: h h h g G H J H ( T.S.",
"P.Z.<.h.c.j.j.j.j.j.j.j.j.j.j.j.j.j.z.d.5 ' N ' m P W W W K Q.J.",
"P.Z.<.j.v.c.c.c.c.c.c.c.c.c.c.v.c.c.v.k.4 ' N ' x U W E W ^ Q.J.",
"P.Z.<.j.c.c.c.c.c.c.c.c.c.c.c.c.c.c.v.h.4 ' [ ] n P W W W ^ Q.J.",
"P.Z.<.j.c.c.c.c.c.c.c.a.7.7.7.7.z.c.c.k.3 c l k f D Y I P ! !.J.",
"P.Z.<.j.c.c.c.c.c.c.k.> M x M d 9.c.c.c.g.g.r.r.r.0.0.0.e.3.K.J.",
"P.Z.<.j.c.c.c.c.c.c.h., ] [ ] z 9.c.c.c.c.M.c.M.c.c.c.M.j.5.K.J.",
"P.Z.<.j.c.c.j.c.v.v.j., ' N ' z 9.c.c.j.c.c.c.j.c.v.v.v.j.5.Y.J.",
"P.Z.<.j.c.c.c.h.h.l.f.> ] [ ] v 9.c.c.c.c.c.c.c.c.l.n.n.f.6.Y.P.",
"P.Z.<.j.v.c.a.> , , > . r e r w 9.c.c.c.c.c.c.c.g.+ # # @ 6 R.J.",
"P.Z.<.j.v.c.7.b ] ' ] e p p p y s.c.c.c.c.c.j.c.g.t p a p Z ~.J.",
"P.Z.1.j.c.M.p.x ' B [ e p p p y 9.c.z.c.c.c.c.v.s.t p a p Z W.A.",
"P.Z.<.j.c.c.7.b ] ' ] e p p p y s.M.c.c.c.c.c.M.g.t p p p Z ~.J.",
"P.Z.<.j.c.c.7.d x c v w y y y 0 +.a.9.s.9.s.9.s.O.0 u y u C ~.J.",
"P.Z.<.j.c.c.z.9.9.s.q.$ x k b s % %.$.&.X u y u q F T Y Y ~ Q.A.",
"P.Z.<.j.c.c.j.c.c.M.h., ' [ ] z %.B.B.i.V p p p u P W W W ^ Q.J.",
"P.Z.<.j.c.c.c.c.c.z.k., ' N ' k &.B.-.i.V p a p u L W E W ^ !.J.",
"P.Z.<.j.c.c.c.c.c.v.k., ' [ ] c $.B.V.;.V p p p i U W W W ^ Q.J.",
"P.Z.<.j.c.c.c.c.c.v.l.*.< , , > o.#.#.=.  O O O o * Q = = 7 T.J.",
"P.Z.1.j.M.c.c.c.c.j.c.l.h.h.k.k.m.m.m.x.; W W W T 8.b.x.u.4.A.J.",
"P.Z.<.j.c.j.c.c.c.c.c.c.v.v.v.v.c.c.v.b.; W E W T p.M.z.j.5.Y.J.",
"P.Z.1.l.M.c.c.c.c.c.c.c.M.c.c.c.c.c.z.u.; W W W T p.M.c.j.5.Y.P.",
"P.Z.:.e.t.t.t.c.c.c.c.g.r.r.r.r.l.c.M.x.- R T R L +.y.0.e.3.Y.J.",
"L.F.G P I Y F t.M.z.h.1 { } { _ 9.M.z.l.3 z l k s D Y I U ! Q.J.",
"L.F.J W W W I t.M.c.u.2 |  .| { 9.c.z.k.4 ' ' ' n P W W W ^ Q.J.",
"L.F.J W E W I t.M.M.u.2 |  .| { 9.M.M.l.4 ' [ ' x U W E W ^ E.J.",
"J.D.J W W W I e.j.j.w.2 | | | { q.j.j.w.4 B B ' m P W W W ^ Q.L.",
"J.P.( K ^ ^ ! 3.6.5.4.9 ` X.X...3.5.5.6.8 j A A S ! / ^ K ) T.J.",
"P.J.U.Q.Q.Q.!.Y.Y.Y.Y.U.E.E.E.E.Y.K.U.Y.U.W.W.W.W.Q.Q.Q.Q.!.J.K.",
"J.K.J.J.J.J.J.P.J.J.J.J.J.J.K.K.J.J.J.J.J.A.J.J.A.J.J.J.J.J.K.J."
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 214 2 ",
"   c #D4D4D5",
".  c #D0CFC8",
"X  c #CFCDC4",
"o  c #CFCEC5",
"O  c #CFCEC4",
"+  c #D0CEC4",
"@  c #C8CCCF",
"#  c #C3CBD2",
"$  c #CCC9D1",
"%  c #D2C3D1",
"&  c #D2C9D2",
"*  c #D4D5D4",
"=  c #5663BC",
"-  c #4053DA",
";  c #4657D4",
":  c #4557D5",
">  c #4858D1",
",  c #4857D1",
"<  c #4757D4",
"1  c #3B53DA",
"2  c #9B694A",
"3  c #E9781D",
"4  c #729028",
"5  c #0DDB1D",
"6  c #47C046",
"7  c #D7CED7",
"8  c #4154D5",
"9  c #2945FF",
"0  c #2F49FD",
"q  c #2E48FF",
"w  c #2B48FF",
"e  c #1E44FF",
"r  c #2145FE",
"t  c #314AFD",
"y  c #1F42FF",
"u  c #AE6735",
"i  c #FF8000",
"p  c #749F04",
"a  c green",
"s  c #2DDB29",
"d  c #D8CBD8",
"f  c #2E49FF",
"g  c #364DF7",
"h  c #324DFF",
"j  c #4249C7",
"k  c #8D5759",
"l  c #7D536A",
"z  c #3449EB",
"x  c #2E4BFF",
"c  c #5E4E92",
"v  c #875471",
"b  c #476176",
"n  c #0B8770",
"m  c #3D877A",
"M  c #D7D1D2",
"N  c #324DF9",
"B  c #2149FF",
"V  c #504EA9",
"C  c #FF8E00",
"Z  c #E27E0A",
"A  c #3347E1",
"S  c #334DFF",
"D  c #2A4AFD",
"F  c #2348FF",
"G  c #2D4AFD",
"H  c #283FFF",
"J  c #4959DD",
"K  c #D6D5CB",
"L  c #544DAE",
"P  c #654473",
"I  c #DF5300",
"U  c #C24D0D",
"Y  c #3345E1",
"T  c #324CFF",
"R  c #364BF7",
"E  c #344DFF",
"W  c #4040CB",
"Q  c #522D9E",
"!  c #644F9E",
"~  c #D4D5D0",
"^  c #1F44FF",
"/  c #895864",
"(  c #FF8D00",
")  c #D85404",
"_  c #F80000",
"`  c #E10307",
"'  c #3445E1",
"]  c #3250FF",
"[  c #364CF9",
"{  c #2453FF",
"}  c #7B2577",
"|  c red",
" . c #DA2A2D",
".. c #CBD8D8",
"X. c #4857D2",
"o. c #2145FF",
"O. c #F37E00",
"+. c #C34D0B",
"@. c #E90000",
"#. c #D30806",
"$. c #313BCC",
"%. c #2F45ED",
"&. c #3541DD",
"*. c #2847F1",
"=. c #70246B",
"-. c #F10000",
";. c #C62F2F",
":. c #CCD8D8",
">. c #3549E8",
",. c #2C45EE",
"<. c #524697",
"1. c #F07300",
"2. c #D0650A",
"3. c #6E0694",
"4. c #6902B0",
"5. c #AA0827",
"6. c #FB0000",
"7. c #6A5B08",
"8. c #00F500",
"9. c #32C52B",
"0. c #D8CCD8",
"q. c #354DF9",
"w. c #294CFF",
"e. c #554DA9",
"r. c #FF8400",
"t. c #E47308",
"y. c #7D0396",
"u. c #7800B3",
"i. c #C00422",
"p. c #746403",
"a. c #2DD929",
"s. c #CFCDC5",
"d. c #4459D2",
"f. c #2D4BFF",
"g. c #334DF8",
"h. c #3848DF",
"j. c #5B4F9E",
"k. c #534BA6",
"l. c #3A35C8",
"z. c #3A29D4",
"x. c #31772E",
"c. c #3AB300",
"v. c #287543",
"b. c #1860B0",
"n. c #41749B",
"m. c #D6D3D0",
"M. c #474ED5",
"N. c #323AFF",
"B. c #3548FD",
"V. c #2F4AFF",
"C. c #1B3EFF",
"Z. c #1F41FE",
"A. c #3053FD",
"S. c #3143FF",
"D. c #0BB639",
"F. c #188A66",
"G. c #3724FF",
"H. c #5154D9",
"J. c #D5D5CB",
"K. c #D0CBCB",
"L. c #338078",
"P. c #108B6C",
"I. c #275EB3",
"U. c #3347FF",
"Y. c #3F54CD",
"T. c #81896A",
"R. c #727D79",
"E. c #354BEB",
"W. c #2F44FF",
"Q. c #4E7C37",
"!. c #70AE00",
"~. c #3A8132",
"^. c #0A8478",
"/. c #3C8A79",
"(. c #D1C4D1",
"). c #21D225",
"_. c #188673",
"`. c #2633FF",
"'. c #5066A5",
"]. c yellow",
"[. c #E2E30A",
"{. c #3147E0",
"}. c #1D41FF",
"|. c #AE5E34",
" X c #FF6F00",
".X c #749804",
"XX c #44BF49",
"oX c #21E71A",
"OX c #3C897D",
"+X c #4A51F5",
"@X c #64739F",
"#X c #E1E021",
"$X c #C7C834",
"%X c #505EC8",
"&X c #425AE6",
"*X c #A3734E",
"=X c #F08320",
"-X c #7A992E",
";X c #15E326",
":X c #4EC74D",
">X c #D8CFD8",
",X c #D8CAD9",
"<X c #D6D5C9",
"1X c #D4D3D0",
"2X c #CACAD9",
"3X c #CCCCD8",
"4X c #D5D4CC",
"5X c #D6D4CA",
"6X c #CFD3D5",
"7X c #C9D2D9",
"8X c #D2D0D8",
"9X c #D9CAD8",
"0X c #D5D5D5",
"qX c white",
/* pixels */
"  . X o O O O O O + @ # $ % & * ",
". = - ; : ; > , < 1 2 3 4 5 6 7 ",
"O 8 9 0 q w e r t y u i p a s d ",
"o ; f g h j k l z x c v b n m M ",
"O : q N B V C Z A S D F G H J K ",
"O ; w j L P I U Y T R E W Q ! ~ ",
"O > ^ / ( ) _ ` ' ] [ { } |  ...",
"O X.o.l O.+.@.#.$.%.&.*.=.-.;.:.",
"O : f >.,.<.1.2.3.4.5.6.7.8.9.0.",
"O : q q.w.e.r.t.y.u.i.| p.a a.d ",
"s.d.f.g.T h.j.k.l.z.x.c.v.b.n.m.",
"O M.N.B.S V.C.Z.A.S.D.a F.G.H.J.",
"K.L.P.I.U.Y.T.R.E.W.Q.!.~.^./.M ",
"(.).a _.`.'.].[.{.}.|. X.Xa s d ",
"& XXoXOX+X@X#X$X%X&X*X=X-X;X:X>X",
"* 7 ,XM <X1X2X3X4X5X6X7X8X9X>X0X"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
