#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 201 2 ",
"   c #010101",
".  c #0B0B0B",
"X  c #1A1A1A",
"o  c #2A2A2A",
"O  c #393939",
"+  c #771717",
"@  c #7B0D0D",
"#  c #6D2727",
"$  c #782828",
"%  c #6B3939",
"&  c #773938",
"*  c #347134",
"=  c #197C19",
"-  c #784616",
";  c #7A7A14",
":  c #725131",
">  c #76762A",
",  c #757537",
"<  c #6C6C2F",
"1  c #2E3776",
"2  c #45105B",
"3  c #4E305C",
"4  c #4B0369",
"5  c #540279",
"6  c #4F1467",
"7  c #563563",
"8  c #3D4475",
"9  c #494949",
"0  c #595959",
"q  c #56415E",
"w  c #754848",
"e  c #6E5555",
"r  c #775959",
"t  c #6F4B44",
"y  c #577657",
"u  c #4C704C",
"i  c #75754B",
"p  c #767658",
"a  c #736A55",
"s  c #565A76",
"d  c #4D4C6E",
"f  c #64546B",
"g  c #65516D",
"h  c #6A696A",
"j  c #7A6B6B",
"k  c #766664",
"l  c #676979",
"z  c #767575",
"x  c #7C7C7B",
"c  c #7A7576",
"v  c #71756A",
"b  c #5F616E",
"n  c #890808",
"m  c #9C0101",
"M  c #930606",
"N  c #841515",
"B  c #921010",
"V  c #A40000",
"C  c #AB0000",
"Z  c #B40000",
"A  c #BC0000",
"S  c #812424",
"D  c #C40000",
"F  c #CC0000",
"G  c #D40000",
"H  c #DC0000",
"J  c #E40000",
"K  c #EC0000",
"L  c #F40000",
"P  c #FE0000",
"I  c #8C4C0D",
"U  c #A85301",
"Y  c #B95800",
"T  c #A54D00",
"R  c #815529",
"E  c #C95D00",
"W  c #D86600",
"Q  c #CF6200",
"!  c #FD7E00",
"~  c #F47600",
"^  c #EA7000",
"/  c #827C7C",
"(  c #816E6B",
")  c #049804",
"_  c #158815",
"`  c #01A601",
"'  c #00B600",
"]  c #00C700",
"[  c #00D600",
"{  c #00E700",
"}  c #00FE00",
"|  c #00F200",
" . c #798179",
".. c #898907",
"X. c #959505",
"o. c #868619",
"O. c #A8A801",
"+. c #B8B800",
"@. c #828226",
"#. c #FF8101",
"$. c #FF8902",
"%. c #C8C800",
"&. c #D8D800",
"*. c #E5E500",
"=. c #ECEC00",
"-. c #FEFE00",
";. c #F4F400",
":. c #84847A",
">. c #81816F",
",. c #1C2B93",
"<. c #253393",
"1. c #1B2EB1",
"2. c #2233AB",
"3. c #5B0085",
"4. c #690099",
"5. c #62008D",
"6. c #6F00A1",
"7. c #7700AA",
"8. c #7F00B2",
"9. c #797983",
"0. c #1C32CD",
"q. c #2137D1",
"w. c #233CE8",
"e. c #263FF2",
"r. c #2B45FC",
"t. c #334CFE",
"y. c #3651FF",
"u. c #3953FF",
"i. c #8000B3",
"p. c #8501BB",
"a. c #8801BE",
"s. c #807E81",
"d. c #8A03C1",
"f. c #858484",
"g. c #8B8B8B",
"h. c #888888",
"j. c #91938E",
"k. c #8E8D94",
"l. c #8D9394",
"z. c #939393",
"x. c #949C9C",
"c. c #9B9B9B",
"v. c #989996",
"b. c #918F91",
"n. c #A3A59D",
"m. c #9B9BA5",
"M. c #9BA6A6",
"N. c #A3A3A3",
"B. c #ACACAC",
"V. c #A4A7AA",
"C. c #ABABB8",
"Z. c #AAB6B7",
"A. c #B4B3B3",
"S. c #BBBBBB",
"D. c #B3BABB",
"F. c #B3B0AE",
"G. c #A69AA4",
"H. c #C1B1BB",
"J. c #B5C2BB",
"K. c #C6C5BB",
"L. c #B6B8C4",
"P. c #AFAFC4",
"I. c #C8BAC7",
"U. c #B4C3C3",
"Y. c #BCC8C9",
"T. c #AFC2C2",
"R. c #C3C3C3",
"E. c #CCCCCC",
"W. c #C5CACA",
"Q. c #CDD2CC",
"!. c #D2D3CD",
"~. c #C9C9D5",
"^. c #D3CAD3",
"/. c #CBD4D6",
"(. c #C9D7D7",
"). c #D4D4D4",
"_. c #D9D6D6",
"`. c #D6D9D6",
"'. c #D9D9D6",
"]. c #D4D5DB",
"[. c #D3DBDB",
"{. c #DCDCDB",
"}. c #DBD5DB",
"|. c #D0CEC4",
" X c #E1DEDE",
".X c #DDE1DC",
"XX c #E1E1DE",
"oX c #E9E9DC",
"OX c #DEDEE1",
"+X c #DADAE7",
"@X c #E1DEE1",
"#X c #DDE1E1",
"$X c #DAE3E6",
"%X c #E2E2E2",
"&X c #EAEBEA",
"*X c #E7E7E8",
"=X c #E9F2EF",
"-X c #EBF4F4",
";X c #FEFEFE",
":X c #F2F3F2",
">X c #F0EDF1",
/* pixels */
").).).).`.).).).).`.).).).).).).).).).).).).`.).)._.).).).).).).).).).)._.).).).).)._.).].).).).).).).).).).).`.).).).)._.).).).).).).).).).).).)._.).).).).].).)._.).).)._.).`.).`.).).].).).].",
").).).).).].).).).).).).).).).).).).).).).).).).).).`.).).).).).).).).).)._.).).`.).).).).).).).).).).).).).).).].).).).).).).).).).).).).).).).).).).).).).).).`.).).).].).).).).).).).`.).`.).",
").)._.).).).).).).).).)._._.}.'.).).).).).)._.].).).).).).).{.{.{.).).).).).).).).).).).).).).{.XX{._.!.).).).).).).`.).).).).).].{.{.{.).!.).).).).).).).).).).).).).).).).).).).).).).).).).).",
").].).`.).).).).).).{.#X/.U.T.W.[.%X).).).).).).).).)._.%X(.U.T.Y.(.%X).).).).).).).).)._.%X].L.P.P.~.#X'.).).).).).).).).).{.OXW.L.P.L.+X X).)._.).).).).).).).).).).).).).).).).).).).).).)._.",
").).).`.).).).).).OXZ.k S n M N r M.[._.).).).).).).#XY.c & n M B & f./. X).).).).).^.{./.k.i o.X...@.z D.@X).).).).).).`.{.V.p @.X.X.o.p m.{.`.).).).).).).{.%X#X`.).).)..X%XOX{.).).).).).).).",
")._.).).).).).).[.j n J P P P P K V e W._.).).).).OXx.+ G P P P P L A # Z.{.!.).).!.{.L.< +.;.-.-.-.-.&.R f.{.).).).).`.].v X.*.-.-.-.-.=.X.a W._.).).).)._.N.z x A.{.)._.c.c c A._.).).`._.).).",
").).)._.).).).{.k Z P P P P P P P P G % /.).).). Xx.n P P P P P P P P L @ Z.{.).).{.L.< *.-.-.-.-.-.-.-.-.O.x .X).).`.`.k +.-.-.-.;.-.-.-.-.%.a /._.).).@Xz.f.&X{.z B.%Xg.g.&X{.z A._.).).).).).",
"`.).].).).).%Xh.V P L P P P P P P L P D k #X)._.D.+ P P P P P P P P P P K # W._.).].i &.-.-.-.-.-.-.-.;.-.-...m.XXE.%Xh.O.-.;.-.-.-.-.-.-.;.-.%.v @X).).).z :X;X;XOXx ).z ;X;X;X).x %X).].).)._.",
").].)._.)._.W.$ P P P P P P P P P P P P n Z._.#Xk G P P P P P P P P P P P A f.%X{.x.O.-.;.-.-.-.-.-.-.-.-.-.=.i ]._.W.> -.;.-.-.-.-.-.-.-.-.;.-.o.C.'.).Q.z ;X;X;X>Xx E.9.;X;X;X*Xz %X).).).).].",
").).).).).%Xx.C P P P P P P P P P P P P F x %XY.N P P P P P P P P P P P P L & /.{.p *.-.-.-.-.-.-.-.-.-.-.-.-...C.*Xz.O.-.-.-.-.-.-.-.-.-.-.-.-.%.f.#XQ.{.s.A.;X;Xv.z.*Xc S.;X;Xj.v.{.).).).).`.",
"_.).).).).#Xj H P P P P P P P P P P P P L & =XM.V P P P P P P P P P P P P P B U.(.R -.-.-.-.-.-.-.-.-.-.-.-.-.%.h.>Xp *.-.-.-.-.-.-.-.-.-.-.-.-.;.i ].)._.^.x x c h.).`.E.z x c g.].).).).`.).).",
").).).).!.$Xr J P P P P P P P P P P P P P $ $XM.Z P P P P P P P P P P P L P m J./.o.-.;.-.-.-.-.-.-.-.-.-.-.-.&. .>Xi =.-.-.-.-.-.-.-.-.-.-.-.-.-., +X).).`.OXE./.{.).).`.#XE.E.%X).).)._.).).].",
")._.).`.).#Xk J P P P P P P P P P P P P P & $XM.C P P P P P P P P P P P P P M J.~.o.-.-.-.-.-.-.-.-.-.-.-.-.-.%.:.>Xp =.-.-.-.-.-.-.-.-.-.-.-.-.;., {.).`.`.R.B.F.R.].)._.S.B.A.W._.).).).]._.).",
").).).).).{.b.A P P P P P P P P P P P P G k *XL.N P P P P P P P P P P P P P $ /.}.i =.-.-.-.-.-.-.-.-.-.-.-.-.X.m.&Xh.+.-.-.-.-.-.-.-.-.-.-.-.-.&.x {.).'.H.g.h.h.b.W._.S.g.h.f.z.E.).).`.).).).",
")._.).].)._.U.N P P P P P P P P P P P P m M. X[.w J P P P P P P P P P P P G j #XXXh.+.-.-.-.-.-.-.-.-.-.-.-.;.> ~.XXP...-.-.-.-.-.-.-.-.-.-.-.-.X.V.{.)._.M.h.j.z.h.B.{.v.h.z.z.f.A._.).).).).).",
").).).).).).%Xz D P P P P P P P P P P J t {.).#XM.M P P P P P P P P P P P + D.{.`.~.< ;.-.-.-.-.-.-.-.-.-.-.O.g.@X!.%Xv %.-.;.-.-.-.-.-.-.-.-.&.a ].).)._.c.g.b.g.h.B._.v.g.g.z.h.B._.).).).).`.",
"`.).).)._.)._./.: G P P P P P P P P L + U._.).).OXz C P P P P P P P P P m l.OX).).{.N.; -.-.-.-.-.-.;.-.-.%.a ].).).`.~.< *.-.-.;.-.-.-.-.-.;.> L._.).)._.D.h.h.h.g.R.{.A.h.g.f.k.R._.).).).].).",
").).).).).).)._.Y.% Z P P P P P P F # Z.{.).).).).{.z m K P P P P P K @ h..X^.).).). Xm.; &.-.-.-.-.-.;.O.a /.[.).).)._.L.< +.-.-.-.-.-.-.%.< C.{.!.).).).`.S.c.N.S.).)._.A.c.M.R.`.).).).`.).).",
")._.).).).).).).'.`.f.$ B A A V $ j W.{.).).).).).).{.M.w B Z A C N w Z.#X).).).).).).{.L.p o.O.+.+.X., l.}.`.).).).).).}./.f., O.+.+.O.> c ~.'.).).).).).)._.).)._.).).)._.)._.).).).`._.).)._.",
").].).`.).).).).).).XX/.C.l.l.M.~.$X{./.).).).).).).).{.[.Z.x.l.x.U.{.{./.).).).).).].)._.+XL.c.k.k.C.].{.).).).).).).).).).OX~.V.k.k.m.~.OX_.).).).).).).).).).).).).).).).).).).).).).).).).).",
"_.).).).).).).).).).). X*X&XoX&X%X_./.].).).).).).).).).{.%X>X>X&X*X'.!.).).).).).).).).)._.%X=X=X=X&X%X).).).).).).).).).!.^.%X=X=X$X=X%X).).).).).).).).).).).).).).).).).).).).).).).).).).).",
").).).).).).`.).!. X!.v.l d d s j.K. X).).).).).).).'.{.B.v u * u  .A.@X}.).).).).).).).#XU.h.w % & j M.[._.).].).).).).). X/.x.r & & r l.W. X/.).).).).).).`.#X{.).).).).]..X{.).).).)._.).`.).",
").].).).).).).).'.n.8 2.w.r.r.w.1.1 k..X).).).)./.'.I.y ) ] | } | ] _ h ^.}.).).).).).`./ N A K P P G V % D.#X).).).)./..XM.$ C J P P J Z $ l.#X).).).).).{.^.N.N.).`.)._.E.N.B._.).).).].)._.).",
").).).).).).).#Xj.,.r.y.t.t.t.t.u.t.,.z {.).).)..XH.* [ } } } } } } } ] * E.{.).).).[.e Z P P P P P P P K + M.%X).).).#Xg.n P P P P P P P P m x {.).).).`.S.o     9 E.{.A.o     9 ).).).).).).).",
"`.)._.).).).OXB.1 r.y.t.t.t.t.t.t.t.y.,.b. X^.`.^.* { } } } } } } } } } [ u @X).)..Xz A P P P P P P P P P P + U.'.).@XM.n P P P P P P P P P P m l.OX!.!._.0         z *XO          .%X!.).).).).",
").).).).).).).d w.t.r.t.t.y.t.t.t.t.t.r.1 R.).%X .' } } } } } } } } } } } ) v.{.'.Z.n P P P P P P P P P P P G k {.).(.& L P P P P P P P P P P P $ W.}./.{.o         9 *XX .   .   0 *X).).).).).",
")._.).).).{.B.,.y.t.t.t.t.t.t.t.t.t.t.u.1.g.@X^.* } } } } } } } } } } } } | u }..Xj G P P P P P P P P P P P P N U.%XM.V P P P P P P P P P P P P Z k.#X).#X0         z &X9         /  X).).].].).",
").].).`.!.XX9.0.y.t.t.t.t.t.t.t.t.t.t.t.e.s *XG.` } } } } } } } } } } } } } _ I.[.& P P P P P P P P P P P P P Z z.&X( G P P P P P P P P P P P P K r #X)._.S.O     9 E._.A.o     0 ).).).).).)._.",
").)._.).).XXl w.y.t.t.t.t.t.t.t.t.t.t.t.r.8 oXm.' } } } } } } } } } } } | } ) H.(.+ P P P P P P P P P P P P P F :.-Xe K P P P P P P P P P P P P P & $X/.)._.).B.A.`.).)._.!.B.A._.).).).).).)._.",
").).).]./.oXl w.y.t.t.t.t.t.t.t.t.t.t.t.r.8 oXG.' } } } } } } } } } } } } } ) I.(.N P P P P P P P P P P P P P F / -Xw K P P P P P P P P P P P P P & $X!.).).).R.E.).).).)./.W.E.).).).).).).].).",
"_.`.).).).@X9.0.y.t.t.t.t.t.t.t.t.t.t.t.w.s *XF._ } } } } } } } } } } } } } = I.[.& P P P P P P P P P P P P P C v.=Xc G P P P P P P P P P P P P J r {.).).E.v.h.h.m.!._.W.z.f.g.V.).).)._.).`.).",
").).).).!.{.F.<.y.t.t.r.t.t.t.t.t.t.t.u.1.j.%X^.* } } } } } } } } } } } } { y }.#Xc F P P P P P P P P P P P P N Y.@XV.m P P P P P P P P P P P P C x.OXQ._.V.h.g.j.h.F.{.G.f.b.b.f.D._.).`.).).).",
"`.).).).).).`.s w.y.t.y.t.t.t.t.t.t.t.r.1 |.).#Xh.` } } } } } } } } } } } ) G.'._.D.N P P P P P P P P P P P D j $X).`.t J P P P P P P P P P P L $ /.).)._.c.g.j.k.h.N.{.v.g.j.b.h.B.{.).).).).).",
").).).).).).{.F.1 r.y.r.r.t.t.t.t.y.t.,.v.OX).).].u [ } | } } } } } } } ] h {.).).@Xx C P P P P P P P P P K # W._.).{.Z.@ P P P P P P P P P P n M.{.).).).B.h.g.j.h.D.{.N.h.g.g.h.S._.).).).).).",
")._.).).).).).OXc.1 e.y.y.y.t.t.y.r.,.:.XX!.).).'.W.* ] } } } } } } } ' u ).`.).).).{.h m P P P P P P P H # D._.).).).{.x.@ K P P P P P P L n g.{.).).).).).N.g.g.B.).).E.N.g.b.B.`.).).).).).`.",
").).).).).).).).{.F.d <.q.w.e.q.2.8 n.{.).).).).^.{.^.h _ ] { | { ' =  .}.`.).).).).).{.k.$ C J L K D n e Y.{.).).).).).{.Z.w m G K K H V % M.@X).).).).).].).E.E.).).).).).E.E.].).).`.].)._.).",
").]._.).`.).).)./.'._.B.x s s z v.|.@X).).).).).).).`.@XI.f.y u y b.I.@X).).).).).).).).%XW.x.k w r / Z.#X_.).).).).).).).{.].M.( e w ( M./. X).).).).).).).).`.`.).).).).).)._.).).).).).`.).).",
").).).).).).).).).).).oX&X:X>X&XoX).!.).).).).).).).).!.{.&X>X>X>X*X_./.).).).).).).).).!._.%X=X-X-X&X X).).).).).).).).).).).%X&X-X-X-X%X!.).).).).).).).).).).).).).).).).).).).).).).).).].).",
"_.).`.).).).).).)._.{.Y.x.9.x k.L.+X{.!.).).).).).).). X/.M.f.s.h.C.].OX).).).).).).).).{.+XD.g.x f.M.W.{.).).).).).).).).{.XXY.x./ s.z.Y.{.{./.).).).).).).).).).).).).).).).).).).).).)._.)._.",
").).).).).).).!.{.~.c - Y E Q Y I a L.@X).).).).).).{.k.: U E E E I : m.OX).).).).).).{.Z.t B A F D C $ f.)._.).).).).).{.Y.j N Z F F Z N r U.{.).).).).).).{.).).{.).).]._.).)._.).).).).).).).",
").`.).).).).).{.D.: E #.$.$.$.$.$.W - m. X).).).`.).a T ! $.$.$.$.$.~ I c {.).).).).{.l.n K P P P P P P Z t W._.).).).{.D.# F P P P P P P H + Z. X!.).).`.).h X o c _.`.).B.v.v.S.].).).).).).`.",
").).).`.).)._.W.: ^ #.~ ! ! ! ! ! $.! - C.{.).)..Xh Y $.#.! ! ! #.#.! $.T x #X).).{.x.n P P L P P P P P P G t ).).)._.Y.# K P P P P P P P P L + Z.{.).).@Xh         k.%XB.h.g.g.g.R._.)._.).).).",
").)._.).)./.OXk Q $.! ! ! ! ! ! ! ! $.^ : /.!..Xx.T $.! ! ! ! #.! ! ! ! $.I Z.'._.Y.$ P P P P P P P P P L P Z f.#X!.{.r G P P P P P P P P P P J w ).).).{.o     .   9 *Xz.g.z.g.h.B._.).).].).).",
"].).).).!.{.L.I $.! ! ! #.! #.#.! ! ! $.T m.XX].t ~ #.! ! #.#.! #.! #.! $.W k {. Xf.A P P P P P P P P P P P P $ /.{.Z.n P P P P P P P P P P P P m M.{.).%XO         0 *Xv.g.g.z.h.A.{.).).`.)._.",
"`.).).).).OXg.Y $.! ! ! ! #.! #.#.! ! #.W j *XZ.I $.! ! ! #.! #.#.! ! ! #.! R W.{.w K P P P P P P P P P P P P V c.&X/ D P P P P P P P P P P P P G ( #X!.{.N..     X A.{.S.j.f.h.v.E._.).).).).).",
").].).).!.#Xk ^ $.! ! ! #.! #.#.#.! #.#.! : $Xc.U $.! ! ! ! #.#.! #.#.#.! $.I P.(.N P P P P P P P P P P P P P D / -Xr K P P P P P P P P P P P P L & +X).)._.B.h h D.{.)._.R.A.D.E.].).).).).).).",
").).).).).%Xa ^ #.! ! #.! #.#.! ! #.! #.! : *Xm.Y $.! #.#.! #.! #.! #.! ! $.T Z.(.N P P P P P P P P P P P P P G / -Xe L P P P P P P P P P P P P P & $X!.).)..X%X%X{.).).]._._._._.).).).)._.).`.",
").).).).).%X( W $.! ! ! #.! ! #.! ! #.#.~ r $XM.T $.! ! ! #.! #.! #.! ! ! #.I L.[.$ P P P P P P P P P P P P P D g.-Xj H P P P P P P P P P P P P K w [.).).).B.k.j.A.).).).N.z.z.D.).).).).].).).",
").).).].).{.m.T $.! #.! ! #.! #.#.! ! $.E x %XW.: #.! ! ! ! #.! #.! ! ! #.~ : )..Xk J P P P P P P P P P P P P n D.*Xx.C P P P P P P P P P P P P A g.#X)._.A.h.g.g.h.S.{.B.f.g.h.h.R.].).).).).).",
"`.).).).).)./.: ! #.! ! ! #.! ! #.! ! $.I Z.'.OXj Q $.! ! ! ! #.! ! ! ! $.Y g. X{.M.m P P P P P P P P P P P J w [.).W.$ P P P P P P P P P P P P N U._.).].c.h.z.b.h.V.{.z.g.j.k.h.B._.).)._.).].",
").)._.).).).%Xz.T $.~ ! ! ! ! ! ! ! $.Y z OX)._.L.- ! #.! ! ! ! ! #.! $.^ : /.).).[.e G P P P P P P P P P P n Z.{.).{.k.m P P P P P P P P P P C x #X).)._.N.h.z.b.f.B.{.c.g.z.j.h.A.{.).`.).).).",
").).`.).).).)..Xz T $.$.#.#.! #.$.$.E e ].).)./.%XM.- ~ $.#.! ! #.#.$.W : L.{.).).}.Y.% G P P P P P P P P n g.@X).).).{.v V P P P P P P P P A e `.).).).`.R.z.h.h.v.|.}.U.z.h.h.c./._.).).).`.).",
").).).`.).).).).[.f.I Q ~ $.$.! W I k )._.).).).).{.V.: Y ^ ! ! ! ^ U : L. X!.).).).{.W.e m J P P P L D + x.{.).).).).).{.x N G P P P P H n j [.).).).).)._.E.A.S./._.).).E.A.S.!._.).).).).).).",
")._.).).).).).).).#XL.c : I I R v C.XX`.).).).).).).{./.h.a R I R a z.].'./.).).).).)._.{.M.r S N N w s.Y.%X).).).).).).).%XD.z & + N S j Z..X).).).).).).).).`._._.).).)._._._.).).).).).`.)._.",
").].)._.)._.).).).)._.#X].~.~.(.OX_.).).).).).).).).).). X}./././.OXOX).).).).).).).).).).{.{./.(./.[.#X_.!.).).).).).).).)._.%X[.(.(.[.OX_.).).].).).).).).).).).).).).).).!.).).).).).).).].).",
"`.).).).).].).).).).{..XK.S.S.R.`.OX).).).).).).).).)._. XE.P.C.L.~.@X_.).).).).).).).).).OX[.U.T.T.W.#X{.).).).).).).).).).OX'.K.J.J.K.'.{.).!.).).).).).).).).!.).).).)./.^.).).).).).)._.).).",
"].`.).).).).).).).{.n.b <.<.,.<.d z..X.X).).).).).).XXL.>.> X.X.X., x I.OX).).).).).)._.(.g.w B m M S k Z..X).).).).).).).{.N.f 6 4 4 6 f v.[.).).).).).).).{.%X%X{.).).).OX*X*X_.).).).).).).).",
").).).).).).).].`.l ,.w.y.u.y.y.e.2.d K.{.).).).).OXz.; &.-.-.-.-.-.%.> M.OX).].).).{.J.% Z P P P P P H n f.'.).).).)._.).h 4 6.i.p.a.p.6.4 f |.).).).).).{.N.0 0 A.{.)._.c.0 0 S.{.).).).).`.).",
")._.)._.).).)._.h 1.t.y.t.t.t.t.t.y.0.d |.`.).).{.k...-.-.-.-.;.-.-.-.;.; N.{.).)._.U.# K P P P P L P P P V z {.).).).`.f 3.d.i.i.i.7.8.p.a.5.q Q.).).).{.z.      . B.%Xf.      X A._.).).].).).",
").).).).).!.@Xf.1.y.t.r.t.t.t.t.t.t.y.0.b .X).'.A.; -.-.-.-.-.-.-.-.-.-.;.< W._.).{.% J P P P P P P P P P P M M.{.!.@Xs.5 d.8.8.i.i.i.8.i.i.a.5.h %X).).OXO     .   0 *Xo     .   h %XE.`.).).).",
").`.).).).].|.1 t.t.t.t.t.t.t.t.t.t.r.y.,.F.{.+Xp *.-.-.-.-.-.-.-.-.-.-.-.%.x OX{.x.V P P P P P P P P P P P K & (.[.K.6 8.8.8.8.i.8.i.8.8.i.i.a.4 A.'.).{.o     .   9 *XX     .   0 *X).).).).].",
").)._.).).OXv.2.y.t.t.t.t.t.t.t.t.t.t.y.0.x %XL.R -.-.-.-.-.-.-.-.-.-.-.-.;., ~..Xr J P P P P P P P P P P P P B Z.*Xj.3.d.8.8.8.i.i.i.i.i.i.8.p.5.f.#XQ.{.z   .     z.&Xh       . N.{.).)._.).).",
").`.).).!.%X9.q.y.t.t.t.t.t.t.t.t.t.t.y.r.d %Xm.O.-.-.-.-.-.-.-.-.-.-.-.-.-.X.L.(.S P P P P P P P P P P P P P D h.=Xf 4.p.8.8.8.i.8.i.i.i.i.i.i.6.g .X).).).z o o h._.`.).h o o z.{.).).`.).`.).",
").).).]./.#Xs w.y.t.t.t.t.t.t.t.t.t.t.t.r.8 oXx.+.-.;.-.-.-.-.-.-.-.-.-.-.-.X.C.(.N P P P P P P P P P P P P P G / :Xf 6.p.8.i.8.i.i.8.i.8.i.i.i.7.7 [.).).).*X%X%X*X).).).*X{.{.%X).).).).).).).",
"_.).).).).%Xl w.y.t.t.t.t.t.t.t.t.t.t.t.r.d *Xm.O.-.-.-.-.-.-.-.-.-.-.-.-.-.X.L.(.N P P P P P P P P P P P P P D s.:Xf 4.p.i.i.i.i.8.i.i.i.i.8.i.7.q .X).).).z.z z c._.).).S.V.V.R.}.).).).).].).",
").).).).).{.z.2.y.t.t.t.t.t.t.t.t.t.t.y.q.l *XD.o.-.-.-.-.-.-.-.-.-.-.-.-.;.> E..Xw K P P P P P P P P P P P P m V.&Xg.3.p.i.8.i.i.i.8.i.8.8.i.p.5.z #X).OXg.z.:X>Xf.N.%XA.g.h.h.b.E.).).).)._.).",
").`.).).).+XK.1 t.t.y.r.t.t.t.t.t.t.t.y.,.n.{.].i *.-.-.-.-.-.-.-.-.-.-.-.%.c {..Xg.Z P P P P P P P P P P P P & /.{.J.6 p.i.i.8.i.i.i.i.i.i.7.a.4 B.OX).).z ;X;X;X*Xz .Xv.g.j.j.f.F._.).`.).).).",
").).]._.)./.OXz 1.y.t.t.t.t.t.t.t.r.y.w.s '.)..XV...-.;.-.-.-.-.-.-.-.-.-.; L.XX)./.% L P P P P P P P P P P V g. X|.XXl 3.a.8.i.8.8.8.i.i.7.a.4.f .X^.).E.z ;X;X;X&Xz {.v.g.g.z.g.B.{.).).).).).",
").).)._.).).).!.d 0.y.y.t.t.t.t.t.u.r.1 F.'.).).{.x O.-.-.-.-.;.-.-.-.-.X.k.{.).).{.V.+ P P P P P P P P P A r [.).).`.Q.3 4.d.8.8.8.8.8.i.d.6.3 K.[.).).{.h.n.;X;Xh.c.%XA.h.g.f.z.R._.).).).].).",
").).).].).).)._.|.d 1.r.t.y.y.y.r.0.8 A.XX!.).).).}.x ..=.-.-.-.-.-.*.; k.{.).).).). XM.+ G P P P P P L m k [.).).).).`.W.q 5 8.p.a.p.p.i.5 3 S.{.).).).].).h.z z z._.).).D.M.N.R.`.).)._.).).).",
")._.).).).).).).`.`.g.d <.1.2.<.8 x Q.{.!.).).).).).{.V.i o.O.+.O.o.p C.OX).).).).).).{.Y.j $ V Z C B w x.{.).).).).`.!.'.`.h.7 6 5 5 5 3 x Q.{.).).).).).).{.).).#X).).)._._._.).).]._.).)._.).",
").).).).).).).).).`..X!.F.v.n.n.K.XX_.).`.!._.).).).).{.].D.m.x.m.L.+X_.).).).).).).).)._.#XY.N.x.c.Z.[.#X).).).).).).).).)..X!.B.v.v.B.!.XX).).).).).).).).).).).).).).).).).).).).).).).).`.).",
").)._.).).).).).).).).%X%X$X+XXX%X}.!.).).).).).).)./.!..X*X&X@X*X%X{.!.).).).).).).).).)._.%X*X$X*X%X.X).).).).).).).).).).).%X*X*X*XoX%X`./.).).).).).).).).).).).).).).).).).).).).).].).).).",
").].).).).).}.).).{.~.k.p , , ( g.L.OX).).).).).).).{._.G.v * * u x F.@X`.^.).).).).).).#XD.f.w & & r M.(.{.!.).).).).).)..XW.j.g 7 3 f g.W.XX).).).).).).).].%XOX).).).).). X{.).).).).).).).`.",
"_.).`.).).).).).XXm.> +.*.-.-.=.+.; h.{.).).).).).{.I.u ) [ } } | [ ) y ^.+X).).).)._.[.z n D K P P H C % Z.OX).).).).).OXx.3 5 4.8.8.6.3.2 g..X).).).).).{.E.c.N.)._.).{.E.v.V.)._.).).).].).).",
").).).).).).!.+Xg...;.;.-.-.-.-.-.-.O.v {.).).).'.S.* [ } } } } } } } ] * I._.).)._.(.e A P P P P P P P L + M.{.).).). Xh.4 8.d.p.8.8.p.d.8.4 z {.).).)._.A.o     O E.{.B.X     9 E.`.).).).)._.",
").].).).).).OXV...-.-.-.;.-.-.-.-.-.-.O.g.@X)._.^.* { } } } } } } } } } [ u _.).).{.j A P P P P P P P P P P + U._.)..Xn.4 p.i.8.8.8.8.8.8.i.d.4 g.XX^.).#X9         h &XO   .     x OX).`._.).).",
"`.).).`.).).~., =.-.-.-.-.-.-.-.-.-.-.-.> L.). Xx ] } } } } } } } } } } } ` z.#X_.Z.n P P P P P P P P P P P H r +X!.!.3 7.8.8.i.8.8.i.8.i.8.8.p.3 W.}.!.#Xo     .   9 *XX         0 *X!.).).).).",
")._.).).). XV.O.-.-.-.-.-.-.-.-.-.-.-.-.%.h.*XI.* } } } } } } } } } } } } | u `.#Xj H P P P P P P P P P P P P N U.%Xn.5 d.8.i.8.8.i.i.i.8.i.8.p.5 z.@X!.%X0         z &X9         f.%X).)._.).).",
").).).).).OX>.%.-.-.-.-.-.-.-.-.-.-.-.-.=.i @XB.` } } } } } } } } } } } } } _ I..X$ P P P P P P P P P P P P P Z g.&Xz 4.i.8.8.i.i.8.i.8.i.8.8.p.4.g .X).`.R.O     9 ).{.S.o     0 ).).).).].).`.",
"_.).`.).).$Xp *.-.-.-.-.-.-.-.-.-.-.-.-.-.> +XG.` } } } } } } } } } } } } } ) H.~.N P P P P P P P P P P P P P G  .:Xf 6.p.8.i.i.i.8.i.8.i.i.8.i.7.7 .X^.`.{.{.H.R.{.].)._._.R.R.{.).).).).).).).",
").).).].).%Xp *.-.-.-.-.-.-.-.-.-.-.-.-.-., $XG.' } } } } } } } } } } } } } ) I.(.+ P P P P P P P P P P P P P F / -Xf 6.i.8.8.i.i.i.i.i.i.i.8.i.7.7 .X)./.'.R.z.v.E._.).{.R.z.c.)._.).).).).).).",
").).).).^.#X:.%.-.-.-.-.-.-.-.-.-.-.-.-.*.p %XF.) } } } } } } } } } } } } } _ I.{.& L P P P P P P P P P P P P C x.&Xc 5.p.8.8.8.i.8.i.i.i.8.i.p.4.l .X!._.A.X     o R.{.V..     O E.).).].).).).",
"`.).).).).{.C.X.-.;.-.-.-.-.-.-.-.-.-.-.+.k.%X^.* } } } } } } } } } } } } { y @X.X/ D P P P P P P P P P P P P N Y. XF.4 a.8.i.8.i.i.i.8.8.i.8.d.5 v.OX)..X9   . .   h &XO     .   z %X).).`.).).",
").]._.).).).].a *.-.-.-.-.-.-.-.-.-.-.;.> ~.).{.k.` } } } } } } } } } } } ) V.'._.U.+ P P P P P P P P P P P D j %X).`.q 4.p.8.8.8.i.i.8.i.8.i.7.3 !.`.).{.o         9 *XX         0 *XQ.).)._.).",
").).).).).).{.D.; ;.-.-.-.-.-.-.-.-.-...m.{.).).}.u [ } } } } } } } } } ' h  X).).{.f.V P P P P P P P P P J % W._.)..XA.2 8.p.8.8.8.8.8.i.i.p.2 N.XX!.).%X0         x &X9         h.@X).).).).`.",
")._.).).).).)..Xm.; *.-.-.-.-.-.-.;...g.{.).).).}.^.* ' } } } } } } } ' y }.).).).).{.z m P P P P P P P G # D.{.).).)..Xn.2 6.p.p.p.p.p.a.7.2 j.{.).).)._.E.9   . 0 `.{.R.O . . h `.).)._.).).).",
").).).`.).).).).#XP.a X.%.*.*.&.X., V.+X).).).).!._.).z _ ' { { [ ` = f._.).).`.).).).{.x.# C H K J D n k W.{.!.).).).).XXJ.q 4 5.4.4.5.4 7 V.#X).).).).)._.{.U.S._.`.).{.].S.R.{.).).).).).].).",
").)._.).).).).).^.{.[.C.:.p p >.m./.XX).).).).).).).).@XI.j.y y v v.I.#X).).).).).).).).%XW.M.j r r f.L..X`.!._.).).).).).{.'.F.s.f f x B.`.{.).).).).).).).)._._.).).).).).{._.).).).).).).).).",
"].).).).`.).).).).).). X%X*X*X%X%X).).).).).).).).).).)._.%X*X>X*X%X'.).).).).).).).).).)._. X*X=X=X%X{.)./.).).].).).).).).^.OX*X&X*X*X.X).!.).).).].).).).).).).).).).).).).).).).).).`.).)._.",
"_.`.).).).).).).).).).!.L.A.A.S.E._._.).).).]._.).).)._.).I.A.A.A.R.)._.).).).].).).).).).).E.A.C.A.S.)._.).).).`.).).).).).].!.S.A.F.S.E._.).).).`.).).).).).).).).`.].).).).).).).].).).).).).",
").).).).).).].).).!.A.x.j.h.g.g.z.B.E.).).).).).).).).L.c.b.g.g.g.j.N.R.).).).).).).).).E.V.z.g.h.g.j.v.S.).).).).).).).).!.A.z.g.g.g.g.z.B.E.).).).)._.)._.).).).).).).).).`.).).)._.)._.).`.].",
"`.)._.)._.`.).).).).E.E.^.!.!./.^.E.).).).).).`.).).).E.E.Q.!.^.).E.E./.).).)._.).).).).!.E.E.).E.).!.E.E.).).).).).).).).).E.E.E.).E.)./.E.).).).).`.).)._.).].`.).].).).].).).).`.).).).).).`.",
").).).).).).).).).).`.).)._.).).`.).).).).).).).).).).`.`.).`.).).`.).).).).).].).).).).]._.).).).].)._.).).).).`.).)._.).`._.).)._.).)._.).).).).).).).).).).`.).).)._.).)._.).].).).).).).).).",
").].).).)._.).).].).).).).).).).).).).).)._.`.).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).].).).).).).).).).).).).).).).).).).).).).).).).).).).`.).).)._.).`.).).).)._.",
").).).`.).].).).).).).).).).).).).).).).).).).].).).].).).).).)._.).).).).).`.).).)._.).).`.).).).).).].).).).).).).).).).).)._.).).).).).).).).].)._.).`.).)._.).).`.).).)._.).).).)._.).].).)."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 209 2 ",
"   c #020202",
".  c #0C0C0C",
"X  c #181818",
"o  c #363636",
"O  c #262626",
"+  c #7E1A1A",
"@  c #792727",
"#  c #783737",
"$  c #337833",
"%  c #197E19",
"&  c #775636",
"*  c #7A7A27",
"=  c #7B7B37",
"-  c #7B6A1D",
";  c #313B7E",
":  c #550378",
">  c #500D6B",
",  c #5A3768",
"<  c #542666",
"1  c #4C215F",
"2  c #484848",
"3  c #585858",
"4  c #784747",
"5  c #7A5858",
"6  c #7D5E40",
"7  c #527B51",
"8  c #797849",
"9  c #79665A",
"0  c #7A7A56",
"q  c #7D644B",
"w  c #515275",
"e  c #67516F",
"r  c #686868",
"t  c #7C6969",
"y  c #67687A",
"u  c #7C7C7C",
"i  c #747678",
"p  c #75726F",
"a  c #5F617D",
"s  c #3D4473",
"d  c #970808",
"f  c #891717",
"g  c #931414",
"h  c #8A0D0D",
"j  c #AC0101",
"k  c #A40404",
"l  c #B40000",
"z  c #BC0000",
"x  c #842727",
"c  c #823838",
"v  c #C30000",
"b  c #CC0000",
"n  c #D40000",
"m  c #DC0000",
"M  c #E30000",
"N  c #EB0000",
"B  c #F40000",
"V  c #FE0101",
"C  c #8E4F12",
"Z  c #A75503",
"A  c #B45600",
"S  c #A74F00",
"D  c #84582C",
"F  c #CB5E00",
"G  c #D56400",
"H  c #CE6400",
"J  c #FD7E00",
"K  c #F57500",
"L  c #E86F00",
"P  c #815252",
"I  c #816857",
"U  c #826868",
"Y  c #847374",
"T  c #867C7B",
"R  c #817366",
"E  c #0F910F",
"W  c #00B800",
"Q  c #04A404",
"!  c #2B832B",
"~  c #00CA00",
"^  c #00D600",
"/  c #00E800",
"(  c #01FE01",
")  c #00F400",
"_  c #528252",
"`  c #758375",
"'  c #979708",
"]  c #898918",
"[  c #909011",
"{  c #ABAB01",
"}  c #A3A304",
"|  c #B6B600",
" . c #848425",
".. c #828238",
"X. c #FF8101",
"o. c #FF8902",
"O. c #CBCB00",
"+. c #C3C300",
"@. c #D7D700",
"#. c #E9E900",
"$. c #F4F400",
"%. c #FEFE01",
"&. c #828251",
"*. c #86847B",
"=. c #84836A",
"-. c #1E2D95",
";. c #2A378F",
":. c #1A2DB3",
">. c #2233A8",
",. c #2335B7",
"<. c #5A0083",
"1. c #6B009D",
"2. c #61008D",
"3. c #7800AB",
"4. c #7E00B2",
"5. c #6F00A1",
"6. c #394387",
"7. c #474E83",
"8. c #787882",
"9. c #6E7081",
"0. c #1E35D7",
"q. c #1C32C3",
"w. c #2138D9",
"e. c #243DEA",
"r. c #243EF2",
"t. c #2E48FF",
"y. c #2B45FB",
"u. c #334CFE",
"i. c #3650FE",
"p. c #3953FF",
"a. c #8001B3",
"s. c #8501BB",
"d. c #8902BE",
"f. c #827F83",
"g. c #8A02C0",
"h. c #858585",
"j. c #8B8B8B",
"k. c #898685",
"l. c #918B8B",
"z. c #92928D",
"x. c #8E9192",
"c. c #929293",
"v. c #9B9B9C",
"b. c #97989A",
"n. c #8E8D90",
"m. c #9EA29C",
"M. c #A4A49D",
"N. c #9B9CA3",
"B. c #A29CA6",
"V. c #9BA4A5",
"C. c #A4A4A4",
"Z. c #A3ACAD",
"A. c #ABABAB",
"S. c #A7A5A8",
"D. c #B4B5AB",
"F. c #A8ABB6",
"G. c #ADBABA",
"H. c #A9B3B4",
"J. c #B4B4B4",
"K. c #BBBBBB",
"L. c #B4B5BB",
"P. c #B2ADAF",
"I. c #A09D9D",
"U. c #BCC3BA",
"Y. c #C4C4BB",
"T. c #D1CDBE",
"R. c #B6B8C4",
"E. c #C5B7C5",
"W. c #C1BFD2",
"Q. c #BCCACA",
"!. c #B7C4C5",
"~. c #C4C4C4",
"^. c #C1CECE",
"/. c #CCCCCC",
"(. c #C9CAC5",
"). c #D1CFCC",
"_. c #CDD3C9",
"`. c #D2D2CE",
"'. c #D8D6C9",
"]. c #C8C9D5",
"[. c #D4C8D4",
"{. c #C4D2D2",
"}. c #CAD5D6",
"|. c #CDD8D9",
" X c #D4D4D4",
".X c #D9D6D6",
"XX c #DADAD6",
"oX c #D4D4DB",
"OX c #D4DCDC",
"+X c #DCDCDC",
"@X c #D7D8D6",
"#X c #E1DEDE",
"$X c #DEE1DD",
"%X c #E2E1DD",
"&X c #E3E1D5",
"*X c #DCDDE1",
"=X c #D6D8E7",
"-X c #DDDDF0",
";X c #E1DEE1",
":X c #E4D5E4",
">X c #DDE1E1",
",X c #DAE7EA",
"<X c #DDF0F0",
"1X c #E2E2E2",
"2X c #E8E9E9",
"3X c #E7EBF4",
"4X c #FFFFFF",
"5X c #F6F6F6",
"6X c #E7F1E8",
/* pixels */
" X X X X X X X X X X X X X X X X X X X X X X X X X X X@X X X X X X X X X.X X@X X X X X X X X X X X X X@X X@X X X X X X X X X X X X X X X X X X@X X X X@X.X X X X X.X X X@X@X X X",
" X X@X X X X X X X X X X X X X X X X X X@X X X X@X X X X`. X X X.X X X X X X X X X X X X`. X X X X X X X X X X X@X X X X X}. X X X X X X X X X X X@X X X X X X X X X@X X X X X@X",
" X@X X X X X X X X X.X+X1X1X+X.X X X X X X X X X X}..X>X1X1X+X X X X X X X X X X X X+X1X1X1X+X.X X X X X X X X X X.X+X1X1X;XXX X X X X X.X X X X X X X@X X X X X X X X X X@X X@X",
" X X X@X X X X X+X>XQ.b.k.k.V.{.>X X X X X X X XXX$XR.c.k.k.H.|.+X X X X X X X X+XoXF.z.k.z.F.oX+X X X X X X X X$X].S.j.k.c.R.+XXX X X X X X X@X+XoX X X`.}.+X+X X X X X X X X X",
"@X X X X X X X+X{.t f l m n j x j.>X X X X X X%X!.5 g v n b k # V.*X X X X X X*XS.8 ' O.@.O.' 8 F.1X X X X X X+Xb.= { O.@.+.[ 0 R.#X X X X XXX+XJ.K.+X X X+XK.J. X@X X XoX X X X",
"@X X X X X X+X!.# m V V V V V V l 5 |.@X X X+XZ.+ N V V V V V V d *.$X`. X X*Xn.' $.%.%.%.%.%.$.] b.*X`. X X+Xp { %.%.%.%.%.%.#.* F.+X X X X/.i b.j.h. X+Xj.j.v.u ~..X X X X X X",
" X@X X X X X}.# N V V V V V V V V v t +X X.X!.+ V V V V V V V V V k z.%X|.$XN.' %.%.%.%.%.$.%.%.%.[ F.+X`.+Xk.| %.%.%.%.%.%.$.%.$.= R.XX X+Xh.~.4X4Xv.A.J.c.4X4X`.8.+X X X X X@X",
" X X XoX X1Xk.v V V V V V V V V V V d H.#XOX5 M V V V V V V V V V V x Q.$X|.D $.%.%.%.%.%.%.%.%.%.#.8  X+XR.] %.%.%.%.%.%.%.%.%.%.@.=.*X X+Xu 5X4X4X`.b.C.E.4X5X4Xh.@X X@X@X X X",
" X X X X X|.c V V V V V V V V V V V m U 1X!.g V V V V V V V V V V V v x.2XN.{ %.%.%.%.%.%.%.%.%.%.%.} J.2X*.O.%.$.%.%.%.%.%.%.%.$.%. .R.+X*Xj.K.4X4Xc.A.K.j.4X4XE.k.*X X X X@X@X",
" X X X X+XG.k V V V V V V V V V V V V c >Xb.z V V V V V V V V V V V N P 3X=.@.%.%.%.%.%.%.%.%.%.%.%.O.*.2X&.$.%.%.%.%.%.%.%.%.%.%.%.| S.%X X/.h.j.h.c.+X+Xc.h.j.` /. X X@X X X X",
"@X X X X#XH.j V B V V V V V V V V V V x ,Xj.b V V V V V V V V V V V B 4 <X0 #.%.%.%.%.%.%.%.%.%.%.%.@.*.-X= %.%.%.%.%.%.%.%.%.%.%.%.| N.1X`. X*X~./.*X X X+X/.~.+X@X X X X X X X",
" X X X X+XH.k V V V V V V V V V V V V x ,Xz.v V V V V V V V V V V V B P 3X=.#.%.%.%.%.%.%.%.%.%.%.%.@.*.-X..%.%.%.%.%.%.%.%.%.%.%.%.| S.1X X XK.C.A.~.@X X(.A.C.K.@X X X X X XoX",
" X X X X.X{.x V V V V V V V V V V V M 5 1XG.d V V V V V V V V V V V v k.2Xb.| %.%.%.%.%.%.%.%.%.$.%.{ N.2X=.@.%.%.%.%.%.%.%.%.%.%.%.] R.XX X~.j.j.h.c./. Xc.j.j.j.K.+X X X X X X",
" X@X X X X>XY n V V V V V V V V V V j V.%XOX4 B V V V V V V V V V V f !.#XW. .%.%.%.%.%.%.%.%.%.%.%.= ].#XF.' %.$.%.%.%.%.%.%.%.$.#.0 *X X+XC.j.j.c.k.~.~.h.x.n.j.C..X X X X@X X",
" X@X@X X X.XQ.@ V V V V V V V V V m 5 OX X+XZ.h V V V V V V V V V z T *X).#Xj.{ %.$.%.%.%.%.%.%.%.' N.1X`.+Xp O.%.%.%.%.%.%.%.%.$.] L.+X X@XJ.h.j.n.h.~./.j.j.j.k.A.OX X X X X X",
" X X X X X X+XZ.+ B V V V V V V n # ^..X X X>Xj.d V V V V V V V z 9 OX X X X+Xp | %.%.%.%.%.%.%.} *.*X X X.X}.8 O.%.%.%.%.%.%.$.[ N.+X X X X`.N.j.j.A.@X XJ.j.j.v./. X X X@X@X X",
"@X X X X X X X+XG.4 j m B N n d t /..X X X X X+XV.@ z M B N b f T @X.X X X X.XoXj. .+.#.$.#.| * c.+X X X X XXX}.Y [ O.$.$.@.| = S.*X X X X X X X~.(.@X X X X~.~. X.X X X X X X@X",
"@X X XoX X X X X+X@XV.Y 5 5 T G.*X.X X X X X X X+X}.V.t 5 5 j.!.>X X X X X X X X1XR.c.&.8 =.c.].%X X X X X X X X*XL.*.` 0 =.N.[.+X X X X X X X X+X X X X X X+X X X X@X X XoX X X",
" X X X X X X X X X X2X6X2X6X2X2X}. X X X X X X X X X1X2X3X5X2X#X}. X.X X X X X X}.#X2X3X3X3X2XXX`. X X X X X X X`.%X2X3X3X3X2X.X X X X X X X X X`. X X X X X X X X X X X X X@X X",
" X@X@X X X X X X+X.XM.8.a a h.D.#X.X X X X X X X+X[.v.` 7 7 l.E.%X X X X X X X X%XQ.c.P 5 U b.^.1X X X X X X X X>X!.k.P 5 U V.|.+X X X X X X X X*X+X X X X X+X+X X X X X X X X X",
" X X X X X X X+XD.w >.w.r.e.0.;.y (.+X X X X X+XB.$ W / ) / ~ E ` :X.XoX X X X+Xj.f v M B M z x c.>X X X X X.X|.t g v N B m l # Z.+X X X X X+X/.C.A. X X X+XA.C./.+X X@X X X@X@X",
" X X X X X X+XA.;.r.i.u.i.u.i.u.0.s T.+X X X#Xn.E ( ( ( ( ( ) ( W 7 .X X X X+Xp l V V V V V V V k T +X X X.X}.4 b V V V V V V V h V.+X X X X~.o     3  X Xr     O R.XX X@X X X X",
" X@X X X X+XY.; y.i.u.u.u.u.u.u.p.w.w XX}.+XA.E ( ( ( ( ( ( ( ( ( W ` ;X X*Xj.j V V V V V V V V V d b.#X`.+Xt b V V V V V V V V V f G.+X/.1Xr         C.J.    .   3 1X`..X X X X",
" X X X X X1Xi 0.i.t.u.u.u.u.u.u.u.i.>.M.+X X7 / ( ( ( ( ( ( ( ( ( ( E E.$XQ.x V V V V V V V V V V V # }.#XH.d V V V V V V V V V V M 5 >X X1X3     .   c.S.        2 1X X X X X X",
"@X@X X X X).6.y.u.u.u.u.u.u.u.u.u.i.e.y %XE.E ( ( ( ( ( ( ( ( ( ( ( ~ j.2Xb.z V V V V V V V V V V V j Z.2XY n V V V V V V V V V V V f Q..X+Xb.      X R./.O       j.+X X X X X X",
" X X X X+XD.>.i.u.u.u.u.u.u.u.i.u.u.y.6.&Xc.~ ( ( ( ( ( ( ( ( ( ( ( ) 7 3XU M V V V V V V V V V V V n T <Xc V V V V V V V V V V V V l V.#X X+Xc.o 2 A.+X@XK.2 o h.+X X X X X X X",
" X X X X>XD.>.i.u.u.u.u.u.u.u.u.t.u.t.;.#Xl.~ ( ( ( ( ( ( ( ( ( ( ( ) 7 3X9 N V V V V V V V V V V V M Y <X# V V V V V V V V V V V V l V.1X X X1X1X1X+X X X+X1X1X1X X X X@X X@X X",
" X X X X+XD.>.u.u.u.u.u.u.u.u.u.u.t.y.w #XB.~ ( ( ( ( ( ( ( ( ( ( ( / _ 3XY m V V V V V V V V V V V n T 1XP B V V V V V V V V V V V l Z.+X X XA.c.b.K.@XXXK.b.c.A. X X X X X@X X",
"oX X X X@X`.7.y.u.u.u.u.u.u.u.u.u.i.w.9.1XE.E ( ( ( ( ( ( ( ( ( ( ( W c.2XN.l V V V V V V V V V V V d H.2XT n V V V V V V V V V V V x {..XXXK.k.l.j.j././.c.h.j.h.J.+X X X X@X X",
" X X@X X X1X8.:.p.u.u.u.u.u.u.u.u.i.-.D.+X+X7 ^ ( ( ( ( ( ( ( ( ( ( ! W.#X X# V V V V V V V V V V N 4 OX.X!.f V B V V V V V V V V n U >X`.XXZ.j.z.c.h.K.~.j.c.j.j.C.@X X@X XoX X",
" X X.X X X X`.w e.p.u.u.u.u.u.u.p.q.y $X X@XR.% ( ( ( ( ( ( ( ) ( Q c.;X`.+XV.d V V V V V V V V V f H.#X`.;Xh.l V V V V V V V V B @ Q..X X.XL.k.j.j.j././.j.j.j.h.J.+X X X X X X",
" X X X X X X+XY.s 0.u.u.p.i.u.y.:.y XX X X X#XA.% / ( ( ( ( ( ( Q ` +X X X X+Xj.d B V V V V V N h v.+X X X XOXp j V V V V V V M @ G.+X X X X XA.c.c.J. X+XK.c.n.C. X X X X X X X",
"@X X X X X X X+X).y ;.,.0.0.,.6.k.+X@X X X X X+XE.7 E ~ ^ ~ Q $ B.#X X X X X X+XZ.& k b n b d 4 G.+X X X X X X*Xc.@ j b n v g 5 Q.+X X X X X X@X`.`..X@X XXX X/. X@X X X X X@X X",
" X X@X X X X X XXX&XY.b.h.k.M.(.*X X X X X X X X.X:XL.z.*.j.P.oX%X[. X X X X X X+X|.F.l.f.l.G.@X+X X X X X X X X>X|.Z.k.k.c.!.+X.X X X X X X X XoX X X X X X X X X X X X@X X@X X",
" X@X X X X X X X`..X2X,X>X,X2X>X X X X X X X X X`..X2X,X,X-X2X+X X X X X X X X X X+X1X,X<X,X2X#X`. X X X X X X X X+X2X<X,X>X2X.X`. X X X X X X X`.`. XoX X X X X X X X X XoX X X",
" X X X X X X X X;XQ.*.P D D I b.}.+X X X X X X X*XR.*.D & D R V.OX.X X X X X X.X>XH.U c x c Y H.*X.X X X X X X@XOXV.5 x x P T !.#X X X X X X X.X1X1X X X X X X+X@X X X X X X X@X",
"@X@X X X X X X+Xb.& F K J J L A & P.+X`. X X X+X*.C G J J J L Z 9 Q.XX X X X.X}.t d M V V V m d t OX X X X X+XQ.4 l M V V B n f j.+X X X X X+XK.i h./.@XoX XK.J./.@X X X X X X X",
" X X X X X X+Xx.S J X.J X.X.X.o.K & L.+X X X+Xp A X.X.J X.J X.X.G & ^.@X X X|.4 n V V V V V V V v 5 OX X X+XQ.@ M V V V V V V V k h.>X X X+XJ..     o `. XB.j.k.n.~.@X X X X X@X",
" X X@X X XXXH.C X.X.J J J J J J X.K & }. X+Xb.S o.J X.J J X.J J o.G t OX`.>XY v V V V V V V V V V l j.1X`.OX4 M V V V V V V V V V d V.*X`.1Xr         c.`.h.n.n.k.S.@X X X@X X X",
" X XoX X}.$Xt L X.J X.J X.J J X.J o.A c.1X}.& J X.J X.J J X.J J J o.Z F.#X!.f V B V V V V V V V V V x Q.#XV.j V V V V V V V V V V B 4 *X`.1X3   .     c.}.k.n.z.j.S.+X X X X X@X",
" X X X X.XQ.D J J X.J J X.J J J J X.L I 1XZ.Z X.J J X.X.J X.X.J J X.H *.2Xj.v V V V V V V V V V V V l v.2XU m V V V V V V V V V V V g K.+X@XA..     O (. XM.h.h.n.~.@X X@X X X X",
" X X X X+XF.Z X.J J X.X.J X.X.X.X.X.J D >Xz.F o.J X.X.J X.J X.J X.X.K I 3XU M V V V V V V V V V V V m T <Xc V V V V V V V V V V V V l V.#X}.+XJ.r i ~.+X X`.L.J.~.@X X@X X XoX X",
"@X@X X X+XH.A o.J J X.J X.X.J J J J X.D =Xz.F o.J J J X.J J X.X.J J K 6 3X9 N V V V V V V V V V V V m Y <X# V V V V V V V V V V V V l V.#X X X+X*X+XOX X X@X X X XoX X X X@X X@X",
" X X X X+XK.C X.J J X.X.J X.X.J J X.K D ,XV.A X.J J X.J X.X.J J J J L R 3XT n V V V V V V V V V V V b l.1XP N V V V V V V V V V V V k H.#X X`.C.j.j.P.@X@XJ.j.j.C.`.@X X X@X X X",
" X X X X XoX6 K X.J X.J J X.J J J o.H *.1XQ.C X.X.X.J X.J X.X.X.J o.A b.2XZ.k V V V V V V V V V V V g G.2Xj.v V V V V V V V V V V V x |. XXXJ.h.n.n.k.~./.j.j.x.h.A.+X X X X@X X",
" X XoX X X$Xc.A o.J J X.J J X.J J X.C R.XX+Xu F o.K J X.J J X.X.X.K & }. XOX4 M V V V V V V V V V m 5 >X.X^.@ V V V V V V V V V V l k.>X`.+XS.j.z.z.j.R.~.k.c.n.j.C. X X X X X X",
" X X X X X XOX9 F X.o.X.J J J J o.S j.$X`.@X].& L o.J J J J X.X.X.C V.+X X+XG.f V V V V V V V V B @ Q.+X`.+Xb.d V V V V V V V V m 4 oX X X XK.j.j.j.z./.`.c.j.j.h.L.+X X X X X@X",
" X X@X X X X.X{.9 A J X.o.X.J K C h.+X X X X+XR.& F J o.o.o.X.L C N.*X X X X+XZ.+ m V V V V V n @ G.+X X X X+Xx.h N V V V V V z 4 ^.XX X X X.XL.v.v.~..X+X~.v.b.J.@X X X X X X X",
" X X@X X X X X XoXc.& Z A Z C q Z.+X X X X X X.X].*.D Z A A C t R.+X X X X X X+X!.t x j l j x Y ^.+X X X X X}.%XH.5 g j l k # k.@X.X X X X X X.X X.X@X X X X X X@X X X X X@X@X X",
"@X X@X X X X X X X*X|.L.F.F.!.=X+X X X X X X X XXX*X].H.Z.F.Q.=XXX X X X X X X/.+X+X(.H.Z.G.{.>X.X X X X X X X`.+X$XQ.H.Z.R.|.$X X X X X X X X X X X X X X X X X X X X X X X X.X",
" X@X X X X X X X X+X&X`.T.)..X&X@X X X X X X X X X+X*X].].W.oX+X@X X X X X X X X X#X X{.{.{.>X$X X X X X X X X`. X%XXX_._.`.$X+X X X X X X X X}.`. X X X X X X X X X@X X@X X X X",
" X X X@X X X X X+XA.y 6.;.;.6.8.Y.+X X X X X X.XoXN.&.] ' [ ..h.].+X X X X X X+X|.j.P g d g 4 c.oX.X X X X X X$X(.8., > > < e C.+X X X X X X X+X1X1X+X X X+X1X1X*X X X X@X X X X",
"@X X X X.X X X+X8.-.e.t.u.u.t.0.; v.#X X X X+X].0 { $.%.%.%.%.O.* F.&X X X X.X!.# v V V V V B l 4 Q..X X X X$XA.1 2.3.s.s.a.5.: y XX.X X X X+Xv.2 3 L.+X+XK.3 2 c.+X X XoX X X X",
"oX X X X X X*X8.:.i.i.u.t.u.u.i.y.-.M.+X`. XoX0 @.%.%.%.$.%.%.%.$.* L.+X X+X^.@ N V V V V V V V m # }.XX X+XA.> a.d.a.4.4.4.a.d.<.r +X X X+Xv.      X ~./.O       c.*X`. X X X X",
" X X X X X>XM.-.i.u.u.u.u.u.u.u.u.u.; (. X>Xh.| %.$.%.%.%.%.%.%.%.#.8 oX`.+X5 m V V V V V V V V V b p >X X'., 3.s.4.a.4.4.4.a.4.g.: c.*X`.1X3     .   c.S.    .   2 1X`. X@X X@X",
" X X X X XXXa e.i.u.u.u.u.u.u.u.u.i.q.h.1X]. .%.%.%.%.%.%.%.%.%.%.%.} N.2XG.g V B V V V V V V V V V f Q.;Xb.: s.4.a.4.a.a.a.4.4.4.4., @X X1Xr         C.J.        3 1X`. X@X X X",
" X X X X+XY.;.u.u.u.u.i.u.u.u.u.u.u.y.w %XC.{ %.%.%.%.%.%.%.%.%.%.%.#.=.2Xf.n V V V V V V V V V V V z c.6Xe 5.a.a.4.a.4.a.a.4.a.4.s.> J.+X X~.O     2  X@X3     X L.+X X X X X X",
" X X X X*XD.>.i.u.u.u.u.u.u.u.u.u.u.y.6.&Xx.O.%.%.%.%.%.%.%.%.%.%.%.%._ 3XI N V V V V V V V V V V V m T 6X, 4.a.4.a.a.a.a.a.a.4.4.s.<.V.%X X.X`.C.A.@X X X@XC.b.(.+X X X X X X X",
" X X X X+XD.>.i.u.y.u.u.u.u.u.u.u.u.t.6.&Xn.O.%.%.%.%.%.%.%.%.%.%.%.$.I 3XU N V V V V V V V V V V V m Y 6X, 4.a.4.a.a.4.a.4.a.4.4.g.<.m.*X`.+X~.b.C./.@X X X[./. X X X X X@X X X",
"@X X X X.XY.;.u.u.u.u.u.u.u.u.u.y.u.y.w %XS.{ %.$.%.%.%.%.%.%.%.%.%.@.=.2Xk.b V V V V V V V V V V V v b.6Xe 5.a.a.4.a.a.a.a.a.a.4.s.> D.+X+XJ.i (.J.i /.@XA.h.h.c./. X X X X X@X",
" X X X X XXXa e.i.u.u.u.u.u.u.u.u.p.,.j.6XQ.D %.%.%.%.%.%.%.%.%.%.%.} N.;XG.d V V V V V V V V V V V f Q.1Xb.: d.a.a.4.a.a.a.a.4.a.3., XX X+Xh.+X4X4XL.b.}.k.j.z.h.S. X X@X@X X X",
" XoX X X X*XM.-.i.u.u.u.u.u.u.u.u.y.; (. X$Xz.| %.$.%.%.%.%.%.%.%.#.8 oX X*X9 n V V V V V V V V V b i >X X`., 3.a.3.4.4.4.4.a.3.g.: b.%X X+Xu 2X4X4X/.z.`.k.z.z.j.C.+X X X X XoX",
".X X X X X X$Xu :.i.u.u.u.u.u.i.t.-.M.+X`.@XoX0 O.%.%.%.%.$.%.$.$.* R.+X[..X^.# M V V V V V V V m # }..X X+XA.1 4.d.a.a.a.a.a.d.<.y +X X X+XI.c.5X2Xu K.+Xb.k.k.j.K.+X X X.X X X",
" X X X X X X XXXu -.e.t.u.u.y.0.; M.%X}. X X.X}.0 } $.%.%.%.%.+.* L.+X X X X+X!.4 z B V V V B l 4 {..X X X X+XD.1 2.3.s.s.a.1.: p @X X X X X+XN.*.u P.+X X/.P.S.!.+X X X X X X X",
"@X X XoX X X X X+XD.y 6.;.;.7.u Y.*X`.oX X X X X=XN.0 ] ' [ _ l.[.XX X X X X}.XX@Xx.4 g g g 4 b.OX+X X X X X X+X_.f., > > < e A.$X@X X X X X X$X+X+X+X X X X X+X.X X X X X X X X",
"@X X X@X X X X X X+X%X'.'.`.XX%X@X X X X X X X X`.+X*X].].].#X&X X X X X X X X X X+X$X}.{.}.>X%X X X X X X X X X X$X+X_._.@X*X+X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X*X].L.N.S.R.=X+X X X X X X X X@X#X[.P.S.P.E.:X#X[. X X X X X X+X+XQ.H.Z.A.{.>X X X X X X X X X+X$XU.A.A.D._.*X X X X X X X X X X X X X X X}. X X X X XoX X X X",
" X@X@X X X X X.XoXn.= } | | [ 8 B.*X X X X X`.+X[.` ! Q W W ! 7 L.+X X.X X X X+X!.t f j l j x t Q.+X X X X X X+XD.e > : : : , h.`.+X X X X X X+X X+X+X X X+X+X.X+X X X X X X@X@X",
" X X X X X X@X].0 | %.%.%.%.%.$.' *.+X X X X+XE.$ ~ ( ( ( ( ( / E b.:X X X X1XV.f m V V V V V n @ G.+X}. X X$Xj.> 5.a.s.d.s.4.<., ~.+X X X X+Xi O O v.+X+XC.o O p  X X X X X X X",
" X X X X X XoX0 @.%.%.$.%.$.%.%.%.{ k.1X X@X[.$ ) ( ( ( ) ( ( ( ( E B.#X`.+XG.f V V V V V V V V B + !.+X/.;Xc.> s.s.a.4.4.4.a.d.1.3  X X X+Xj.      . K.~..       u +X X X X@X X",
" X X X X X+Xc.{ %.$.%.%.%.%.%.%.%.%.] L.@X;X` ~ ( ) ( ( ( ( ( ( ( ) $ [. XOX4 N V V V V V V V V V m 5 *X@X(.< 4.a.4.a.4.4.4.a.4.g.<.h.>X/.1X3         c.S.        2 +X/.@X@X X X",
" X X X X X=X..$.%.%.%.%.%.%.%.%.%.%.O.*.>XE.E ( ( ( ( ( ( ( ( ( ( ( W b.2XZ.k V V V V V V V V V V V d G.2Xj.<.g.4.a.4.a.a.a.4.a.a.4.< `. X%Xi         A.K.        r 1X X X X X@X",
"@X@X X X+XR.' %.%.%.%.%.%.%.%.%.%.%.%...=XI.W ( ( ( ( ( ( ( ( ( ( ( / _ 3XY n V V V V V V V V V V V v l.2Xe 3.a.a.4.a.a.a.a.4.a.4.s.: A.+X X`.2     r +X+Xi .   o (.@X X@X X X X",
" X X X X+XF.{ %.$.%.%.%.%.%.%.%.%.%.%.] =Xc.~ ( ( ( ( ( ( ( ( ( ( ( ) 7 3XI N V V V V V V V V V V V m Y 6X, 4.4.4.a.a.a.a.4.a.4.4.d.<.m.*X`.@X*X/.`.;XoX X1X X(.1X@X X X X X@X X",
" X X X X%XF.} %.%.%.%.%.%.%.%.%.%.%.%. .=Xz.~ ( ( ( ( ( ( ( ( ( ( ( ) 7 3XU N V V V V V V V V V V V m T 6X, 3.4.4.a.a.4.a.a.a.4.4.d.: C.;X X+XA.r p ~..X.X~.i r A.*X X X X@X X X",
" X X X X+X~. .%.%.%.%.%.%.%.%.%.%.%.#.R :XP.Q ( ) ( ( ( ( ( ( ( ( ( ~ ` 5Xl.v V V V V V V V V V V V l N.2Xy 1.s.4.4.a.a.a.a.4.a.4.s.> U. X+XA..     O /.`.o       N.+X X X X X X",
"@X X X X X*X0 #.%.%.%.%.%.%.%.%.$.%.| b.$XoX$ ) ( ( ( ( ( ( ( ( ( ( E L.>X!.f V V V V V V V V V V V x ^.;XC.: g.3.a.a.a.a.4.a.a.a.3.e @X/.1X3     .   b.A.    .   2 1X X@X X X X",
"@X X X X X+XF.] %.%.%.%.%.%.%.$.%.#.= ]. X$XI.Q ( ( ( ( ( ( ( ( ( ~ p >X`.>XT z V V V V V V V V V j j.+X`.$X3 1.d.a.a.a.4.a.a.a.s.> S.*X X1Xr         v.A.        2 1X X X XoX X",
" X X X X X X+Xc.' %.%.$.%.%.%.%.#.* R.+X X`.$Xi Q ( ( ( ( ( ( ( ^ $ [.@X X X@X4 b V V V V V V V v t @X X X+X~.< 1.s.a.a.a.a.s.s.> h.*X X X+XJ.X     o /. X2     . A.+X X X@X X@X",
" X@XoX X X X X+Xb.* O.$.%.%.#.| = R.+X`. X X X:Xh.E ^ ) ( ) / Q 7 /.@X X X X.X|.t d m B V V n d i +X X X X`.+XY.e : 1.3.4.3.<.1 n.+X X X X X+XK.8.j.`.@X+X Xj.i K.+X X X X@X X.X",
" X X X@X X X X X#XQ.j.&...D &.b.}.+X`.oX X X X X1XE.` _ ! ! ` S.+X X X X X X X X>XH.Y c x 4 Y G.>X X X X X X X@XXXM.y , < e h.~.1X X X X X X X.X1X1X@X X XoX1X1X+X X X X XoX X X",
"@X@X X X X X X X XXX%X=X,X=X-X#X X X X X X X X X}.@X1X:X:X:X1X$X X X X X X X X X X+X>X,X,X>X1X#X X X X X X X X X X;X%X$X$X$X1X.X X X X X X XoX X X`. X X X X X`. X X X X X@X X X",
" X X@X X X X X X X X_.K.D.U.~. X X X X X X@X X X.X X/.J.J.J.~. X X X X X@X X X X.X X~.J.J.J.(. X X X X XoX X X X.X X~.J.J.K./.oX X X X X X X@X XoX X X@X X X X@X X X X X X X@X X",
" X@X X X@X X X.X XJ.v.z.x.j.c.v.E..X X X X X X X`.A.b.c.z.c.c.C./..X X X X X X@X/.S.b.z.n.z.b.A./. X X X X X X@X~.C.c.x.x.c.b.P. X X X X X X X X X X X X X X X@X X X X X@X X X X",
" X X X X X X X X X`.`.oX X X X X`. X X X X@X X X X`. X X X X X}. X X X X@X X X X`./. X X X X X/. X X X X X X X@X`. X X X X X X`. X X X X X X@X@X X X@X X@X X X X X X@X X X@X X@X",
"oX X X X X X X X X@X X X X X X X X X X X X X@X X X X X X X X X.X X X X X X X@X X X.XoX X X X X X X X X X X@X X X X X X X X X X@X X X X X@X X X X X X@X X X X@X X X X X X X X X X",
"@X X X X X X@X X X X X X X X X X X X@X@XoX X X X X X X X X X X X X X X X XoX X X X X X X X X X X X@X X X X X X X X X X X X X X X X X X X@X X X X X X X X X@X X X X X@X@XoX X X.X",
" X X@X XoX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X@X X X@X X X X X X X X X X.X X X X X X X X X X@X X X X X X X X X X.X X X XoX X X.X X@X X X X X X X X"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 207 2 ",
"   c black",
".  c #0B0B0B",
"X  c #1E1E1E",
"o  c #202020",
"O  c #343434",
"+  c #3C3C3C",
"@  c #5F5F5F",
"#  c #535353",
"$  c gray29",
"%  c #616161",
"&  c gray43",
"*  c #7C7B7B",
"=  c gray45",
"-  c #BC1B1A",
";  c #BB211F",
":  c #B82928",
">  c #B23433",
",  c #C90A0A",
"<  c #D30101",
"1  c #DC0000",
"2  c #D10A0A",
"3  c #C31716",
"4  c #C5120F",
"5  c #E40000",
"6  c #EC0000",
"7  c #F30000",
"8  c #FE0101",
"9  c #C92828",
"0  c #CB3033",
"q  c #B76E26",
"w  c #B17337",
"e  c #BC6917",
"r  c #D36E09",
"t  c #E66C00",
"y  c #F47201",
"u  c #FD7E01",
"i  c #FB7601",
"p  c #EC7000",
"a  c #CB7925",
"s  c #AD4444",
"d  c #BC494A",
"f  c #BF544E",
"g  c #AC5757",
"h  c #BB5353",
"j  c #B65A59",
"k  c #B2764D",
"l  c #AB6969",
"z  c #B66868",
"x  c #AB7A79",
"c  c #B37B7B",
"v  c #BA7168",
"b  c #C04A48",
"n  c #28B728",
"m  c #3CAD3A",
"M  c #40B13D",
"N  c #05CC04",
"B  c #04DB04",
"V  c #00E800",
"C  c #01FE01",
"Z  c #00F300",
"A  c #35C83A",
"S  c #52B057",
"D  c #5BBB61",
"F  c #6CB16D",
"G  c #3FC242",
"H  c #42C44D",
"J  c #BCBC19",
"K  c #AFAE3D",
"L  c #B3B337",
"P  c #B8B825",
"I  c #FF8302",
"U  c #C2813B",
"Y  c #CCCB0B",
"T  c #DCDB03",
"R  c #D4D401",
"E  c #C6C616",
"W  c #E3E400",
"Q  c #EBEA00",
"!  c #F3F300",
"~  c #FEFE01",
"^  c #F7FB02",
"/  c #EFF200",
"(  c #C4C93A",
")  c #CCCB25",
"_  c #AE8155",
"`  c #ADAD46",
"'  c #B1B252",
"]  c #B1B155",
"[  c #B6987B",
"{  c #B28968",
"}  c #B0AE75",
"|  c #B6B877",
" . c #AFAF68",
".. c #C19F69",
"X. c #C2C349",
"o. c #670A8E",
"O. c #6A009B",
"+. c #680293",
"@. c #6A168B",
"#. c #7300A4",
"$. c #7901AF",
"%. c #7501AA",
"&. c #7E00B2",
"*. c #3546BF",
"=. c #4855B3",
"-. c #5A66B1",
";. c #5F67AA",
":. c #6D74AB",
">. c #737EBB",
",. c #2B3DD7",
"<. c #1E39F2",
"1. c #243CEB",
"2. c #233EFB",
"3. c #3346CC",
"4. c #2A45FE",
"5. c #334CFE",
"6. c #3851FF",
"7. c #3650FF",
"8. c #4455CB",
"9. c #767DC0",
"0. c #5A6CCA",
"q. c #8203B4",
"w. c #8501BC",
"e. c #845996",
"r. c #8A6699",
"t. c #92739E",
"y. c #8D7BAC",
"u. c #7A83B1",
"i. c #7383C1",
"p. c #878787",
"a. c #9B9B9B",
"s. c #949494",
"d. c #938896",
"f. c #AB8787",
"g. c #B28888",
"h. c #AB9292",
"j. c #AD9C9B",
"k. c #B39996",
"l. c #B3938E",
"z. c #8DB18F",
"x. c #ACAB87",
"c. c #A7A99B",
"v. c #B4B095",
"b. c #9A88A6",
"n. c #9A99A8",
"m. c #989BB8",
"M. c #A597A8",
"N. c #B295A6",
"B. c #97A2B5",
"V. c #A4A4A4",
"C. c #ACABAC",
"Z. c #A9A6AA",
"A. c #B3A3A3",
"S. c #B4AAA8",
"D. c #B5B6AD",
"F. c #B8B5A6",
"G. c #AAACB5",
"H. c #B7A8B4",
"J. c #AABCB6",
"K. c #B4B4B3",
"L. c #BBBBBB",
"P. c #B6B7B7",
"I. c #A2B1A2",
"U. c #C1B8BA",
"Y. c #BFC1BE",
"T. c #C3C2BD",
"R. c #BDBEC4",
"E. c #BEBEC8",
"W. c #ADBEC2",
"Q. c #C2BDC1",
"!. c #BCC3C3",
"~. c #BAC7C8",
"^. c #B6C9CD",
"/. c #C4C5C5",
"(. c #C3C4CC",
"). c #C3CDCC",
"_. c #CCCCCB",
"`. c #C9C5C5",
"'. c #D4CDCB",
"]. c #D6D5CC",
"[. c #C6C5D2",
"{. c #CDCDDB",
"}. c #C7C9D3",
"|. c #D8CBD7",
" X c #CAD4D5",
".X c #CCD9DA",
"XX c #C8D3D8",
"oX c #D5D4D4",
"OX c #D9D7D7",
"+X c #D9DBD6",
"@X c #D4D4DB",
"#X c #D4DCDC",
"$X c #DADBDB",
"%X c #D8D8D7",
"&X c #C8D3CD",
"*X c #DDE2DC",
"=X c #E2E5DB",
"-X c #CAD9E3",
";X c #D3DAE3",
":X c #D8D8E3",
">X c #D7C8E4",
",X c #E5DBE4",
"<X c #D5E2E2",
"1X c #DBE2E2",
"2X c #DCEBEB",
"3X c #E4E6E4",
"4X c white",
/* pixels */
"oXoX%XoXoXoX%XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX%XoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX%XoX%XoXoX",
"oXoXoXoXoXoXoX%X$X$XoXoXoXoXoX$X$XOXoXoXoXoXoX$X$XOXoXoXoXoXoX$X$XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoX<X!.S.!.<XoXoX%X;XL.S.).#XoXoX$X{.P.D.(.$XoXoX$X{.P.K.[.$XoXoX$X$XoXoX$X$XoXoXoXoXoX",
"oXoXoXoXoX.Xl 2 5 , x #XOX).g 2 5 4 f.#XOXE.` T T E v.:X%XR.K T T J F.$X+XL.V.`.`.V.L.$XoXoXoXOX",
"oXoXoXoX<Xl 7 8 8 8 5 x 2Xg 8 8 8 8 1 h.;XK ~ ~ ~ ~ R D.{.P ~ ~ ~ ~ E L.oXK.4XC.C.4XP._.oXoXoXoX",
"oXoXoXoX).3 8 8 8 7 8 9 !., 8 8 8 8 8 d J.T ~ ~ ~ ~ ~ ] S.W ~ ~ ~ ~ ^  .;XC._.P.P._.K. XoXoXoXoX",
"%XoXoX%X!.2 8 8 8 8 8 9 V.1 8 8 8 8 8 0 I.Q ~ ~ ~ ~ ~ ' x./ ~ ~ ~ ~ ~ ] :X_.V.oXoXV._.%XoXoXoXoX",
"oX%XoXoX X> 8 8 8 8 8 d ^.3 8 8 8 8 8 j ~.Y ~ ~ ~ ~ ! } L.R ~ ^ ~ ~ Q x.:Xc.p.G.C.p.V.oXoXoXoXoX",
"oXoXoXoX:Xj.< 8 8 8 , A.2Xf.1 8 8 8 - L.:X} W ~ ~ ~ P (.:X] Q ~ ~ ^ L [.$XZ.p.P.L.p.C.+XoXoXoXoX",
"oXoXoXoXoX$XC.d 0 h K.#X'.#Xj.d 0 j P.$XoX{.v.X.(  .Q.:XOX{.x.( (  .(.oXoXoX`.oXoX`.oXoXoXoXoXoX",
"oXoXoXoXoXOX=XW.B.!.=XoXoXoX,XJ.z.~.,XoXoX+X<XM.h.^.1XoXoX$X-XM.M.}.1XoXoX$X3X$X$X3X$XoXoXoXoXoX",
"oXoXoXoX%X_.;.,.1.,.:.&X*X(.m B Z N F >X+XL.> 5 6 2 x #X$XK.- 6 6 4 h.#X$XV.# L.L.# V.$XoXoXoXoX",
"oXoXoX{.=X:.1.6.5.5.<.d.$XS C C C C V z.:X> 8 8 8 8 < A. X; 8 8 8 8 < K.3XO   % @   O $X XoXoXoX",
"oXoXoX%XT.3.5.5.5.5.4.8.F.B C C C C C G H.5 8 8 8 8 8 j A.5 8 8 8 8 8 l 2X* X a.a.X * $XoXoX%XoX",
"%XoXoX$XT.3.5.5.5.5.5.3.c.B C C C C C A N.5 8 8 8 8 8 d h.7 8 8 8 8 8 j <X'.L.oX$XL.oX$XoXoXoXoX",
"oXoXoXoX].=.4.6.5.7.4.-.'.n C C C C C F [.4 8 8 8 8 7 c ~.< 8 8 8 8 6 h.1Xa.r.I.D.F b.|.oXoXoXoX",
"oXoXoXoX=XC.,.2.4.2.*.P.3Xz.N C C Z n U.1Xf.1 8 8 7 > ).1Xl 1 8 8 6 s .X$XC.p.L.Y.p.H.OXoXoXoXoX",
"oXoXoXoX].+XL.>.0.u.T.$XoX$XK.D H F `.%X'.;XS.j h c  XOXoX#Xj.j h g. X%XoXoX'.oXoX'.oXoXoXoXoX%X",
"oXoXoXoXoXOX#XF.[ F.;XoX|.%X@XS.l.U.;XoXoX$X.Xj.h.L.<XoXoX$XXXk.h.~.1XoXoX$X3X$X%X+XOXoXoXoXoXoX",
"oXoXoXoX;X~.w t y t k ).*XY.q p i t _ XX$XD.- 6 7 < l #X$Xj.4 7 7 < x #X$Xs.+ C._.V.Y.oXoXoXoXoX",
"oXoXoXoX-Xk i I I I p { -Xw i I I I p l.-X: 8 8 8 8 1 k.XX- 8 8 8 8 < A.3XO   # K.= a.%XoXoXoXoX",
"oXoXoX$X!.r I u I u I a G.r I u u u u U Z.5 8 8 8 8 8 h j.6 8 8 8 8 8 l 2Xp.O Z._.M.Y.oXoXoXoX%X",
"oXoXoX$X!.r I u u u I a Z.r I u I u u U M.5 8 8 8 8 8 h h.6 8 8 8 8 8 j <X'.L.oX XK.`.%X XoXoXoX",
"oXoXoXoX.Xw u I u I i _ -Xq u I I I y { ^.3 8 8 8 8 6 g.~., 8 8 8 8 5 j.1Xa.= C.C.* a.%XoXoXoXoX",
"oXoXoXoX$XL.e y i i q R.,XS.r y i y w (.3Xh.< 8 8 6 s  X1Xf.< 8 8 6 g .XOXK.s./.Y.s.P.$XoXoXoXoX",
"oXoXoXoXoX$X(.[ { } ).%XoX$X/.[ { k. X$XoX<XL.c z k..X%XoX#XK.v z A..XoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoX$X].m.i.m.].%X&X%X(.v.| F.{.oXoX$X).g.c S.#X%XoX$XR.b.y.P.+XoXoX$X$X$X$X$X$XoXoXoXoXoX",
"oXoXoXoX%XL.=.<.4.1.=./.:XD.J ! ~ Q ` (.1XA., 7 8 5 g .X$Xb.o.#.%.+.r.%X$Xp.o V.V.X p.$XoXoXoXoX",
"oXoXoX@XOX-.4.5.7.7.<.:.oXL ~ ~ ~ ~ / } XX; 8 8 8 8 5 l.).o.w.q.q.w.+.Z.3XO   @ @   O $XoXoXoXoX",
"oXoXoX%XT.3.5.5.5.5.6.3.S.T ~ ~ ~ ~ ~ ( M.5 8 8 8 8 8 b n.#.q.q.&.q.&.e.*XV.$ P.L.$ V.$X XoX%XoX",
"oXoXoX$XT.3.5.5.5.7.7.8.S.T ~ ~ ~ ~ ~ ( M.5 8 8 8 8 8 b m.#.q.q.&.q.$.e.*XL.L.`._.K._.oXoXoXoXoX",
"oXoXoX@X+X;.2.5.5.6.2.:.OXL ~ ~ ~ ~ / } {.: 8 8 8 8 5 h.).@.w.q.q.w.O.Z.oXD.4XC.V.* a.oXoXoXoXoX",
"oXoXoXoX$XT.=.1.4.1.=.`.$XL.J ! ^ W ` [.$XA.4 7 8 1 g @X+XM.o.#.%.+.r.$XoXP.G.L./.a.L.%XoXoXoXoX",
"oXoXoXoXoXoX].m.>.m.+X%XoX$X[.v.| U.{.%XoX$X).h.c K.<XoXoX$X/.b.b.L.*XoXoXoX_.oXoX%X%XoXoXoXoXoX",
"oXoXoXoXoX$XE.| X.| [.%XoX$XQ.F S z.|.,XoX%XP.v z h. X%XoX$XC.t.r.M.oXoXoX$XoX$X$X].@XoXoX%XoXoX",
"oXoXoXoX%XP.J ~ ~ ! P L.,XI.N Z C Z n Q.1Xh.< 8 8 7 s  X*Xt.+.$.$.O.e.'.:X= . s.s.. = :XoXoXoXoX",
"oXoXoX%X{.L ~ ~ ~ ~ ~ ' {.n C C C C Z F }.- 8 8 8 8 6 g./.o.w.q.&.w.O.h.3XO   @ %   O $XoXoXoXoX",
"oXoXoX$XR.Y ~ ~ ~ ~ ~ ) Z.B C C C C C A N.6 8 8 8 8 8 b n.#.q.&.&.q.&.:.=XK.& `._.& K.%XoXoXoXoX",
"oX%XoX%XE.E ~ ~ ~ ~ ~ ) G.B C C C C C G N.5 8 8 8 8 8 h m.#.q.&.&.q.$.r.3Xs.+ C.C.+ s.$XoXoXoXoX",
"oXoXoXoX>X] ~ ~ ~ ~ !  .>Xm C C C C V z.@X: 8 8 8 8 1 k.&X@.w.q.q.w.+.C.3XO   @ @   O $XoXoXoXoX",
"oXoXoXoX%X~.K W ! T ` [.:X/.n V Z B S |.$XP.- 6 7 < x #X$XZ.@.#.#.+.b.%X%Xa.+ K.P.+ a.$X'.oX%XoX",
"oXoXoXoXoX%X{.F.x.D.{.%XoX$X|.I.z.D.$XoXoX$X Xk.g.L.#XoXoX$X).M.b.T.$XoXoX$X3X$X$X3X$XoXoXoXoXoX",
"oXoXoXoXoXoX_.L.K.R.].oXoXoX_.L.H.Q. XoXoXoX_.J.G./.oXoXoXoX`.P.K./.oXoXoXoX XoXoX&XoXOXoXoX@XoX",
"oXoXoX%XoXoXoX_._._.oXoXoXoX_._._._.oXoXoXoX_._._._.oXoXoXoX&X_._._.oXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoX%XoX%XoXoXoXoX%X%X%XoXoXoXoXoX%XOX%XoXoXoX%XoXoXoXoX@XoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoX%XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX%XoX%XoXoX%X",
"oX#XoXoXoXoXoXoXoXoXoXoX@XoXoXoXoXoXoXoXoXoXoXoXoXoXoX%XoXoXoXoXoXoXoXoXoXoX%XoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 205 2 ",
"   c #010101",
".  c #0B0B0B",
"X  c #171617",
"o  c #222222",
"O  c #2C2C2C",
"+  c #3D3D3D",
"@  c #313131",
"#  c #464646",
"$  c #555454",
"%  c #767676",
"&  c #BE1F1F",
"*  c #BC2D2C",
"=  c #BF2323",
"-  c #B73B3B",
";  c #B9322E",
":  c #CE0D0D",
">  c #D50304",
",  c #DB0202",
"<  c #D60808",
"1  c #C71414",
"2  c #D61B1A",
"3  c #D81919",
"4  c #E20202",
"5  c #EB0000",
"6  c #E10D0F",
"7  c #F30000",
"8  c #FE0101",
"9  c #E00E10",
"0  c #D41E24",
"q  c #C92828",
"w  c #D22427",
"e  c #C83738",
"r  c #C1312E",
"t  c #BE7228",
"y  c #B5783E",
"u  c #D97108",
"i  c #C36C19",
"p  c #D67A1B",
"a  c #C96D0D",
"s  c #E87302",
"d  c #F37300",
"f  c #FD7E01",
"g  c #FA7200",
"h  c #F16E00",
"j  c #D07725",
"k  c #B74747",
"l  c #B75353",
"z  c #B86E4F",
"x  c #B66868",
"c  c #B47B7B",
"v  c #B27573",
"b  c #AF7777",
"n  c #C34848",
"m  c #30B92D",
"M  c #04DA02",
"N  c #15D915",
"B  c #13C911",
"V  c #00E500",
"C  c #00EB00",
"Z  c #01FE01",
"A  c #00F300",
"S  c #0FE011",
"D  c #2CC82B",
"F  c #5CAF5A",
"G  c #4EB44E",
"H  c #70B870",
"J  c #3AC446",
"K  c #43C24D",
"L  c #BDBD3B",
"P  c #FF8202",
"I  c #C1BE25",
"U  c #D9D805",
"Y  c #C7C718",
"T  c #D7D812",
"R  c #CECF09",
"E  c #E0DC02",
"W  c #EBEB01",
"Q  c #E4E402",
"!  c #F4F400",
"~  c #FEFE01",
"^  c #F6FA00",
"/  c #C8C823",
"(  c #CACA3C",
")  c #CFD32C",
"_  c #B38455",
"`  c #B2B052",
"'  c #B28B66",
"]  c #AF936F",
"[  c #B5B46A",
"{  c #B3B379",
"}  c #AEAE6D",
"|  c #6B009B",
" . c #680394",
".. c #6F1E8F",
"X. c #722C8F",
"o. c #76388F",
"O. c #7500AB",
"+. c #7301A7",
"@. c #7E01B2",
"#. c #6F00A2",
"$. c #7C34A6",
"%. c #4A58BA",
"&. c #5C68B3",
"*. c #6B72B1",
"=. c #1D37F2",
"-. c #203BFC",
";. c #3144C9",
":. c #2D43DB",
">. c #354AD9",
",. c #3148E2",
"<. c #2C47FF",
"1. c #2641FA",
"2. c #344DFE",
"3. c #3750FD",
"4. c #2D43E9",
"5. c #4151C2",
"6. c #4D60D3",
"7. c #8103B4",
"8. c #8603BA",
"9. c #83489F",
"0. c #895B9C",
"q. c #8E699D",
"w. c #8144A0",
"e. c #9678A3",
"r. c #9066A1",
"t. c #838383",
"y. c #8B8B8B",
"u. c #939393",
"i. c #9E9E9E",
"p. c #96819F",
"a. c #AE8982",
"s. c #B38C8B",
"d. c #B58686",
"f. c #A69494",
"g. c #A99A9A",
"h. c #B39595",
"j. c #8CB190",
"k. c #B4B487",
"l. c #A5A79B",
"z. c #B3B397",
"x. c #B7A891",
"c. c #858AB9",
"v. c #9A9BA6",
"b. c #A79AA9",
"n. c #9AAAAE",
"m. c #A4A4A4",
"M. c #ACACAC",
"N. c #AAA6A7",
"B. c #B7A9A5",
"V. c #AAB6AB",
"C. c #B8B4AA",
"Z. c #A9AAB4",
"A. c #B5AAB7",
"S. c #ABB8B7",
"D. c #B4B4B3",
"F. c #B9B5B4",
"G. c #BAB9B4",
"H. c #B4B3BC",
"J. c #BBBBBB",
"K. c #B4BCB1",
"L. c #C0BEBD",
"P. c #C0AD91",
"I. c #BEC1BB",
"U. c #C1C6BE",
"Y. c #BCB6C1",
"T. c #C3BCC3",
"R. c #C6B7D0",
"E. c #BCC4C5",
"W. c #BCCCD8",
"Q. c #BDD4D5",
"!. c #C3C4C4",
"~. c #C5C5CB",
"^. c #CCCCCB",
"/. c #C6CBC9",
"(. c #CED1CE",
"). c #D4D4CC",
"_. c #D6D5CB",
"`. c #C9C7D2",
"'. c #C8CAD7",
"]. c #D3CAD8",
"[. c #CAD2D3",
"{. c #CCDBDB",
"}. c #C8D1DA",
"|. c #D5D5D4",
" X c #D9D7D6",
".X c #D4DAD3",
"XX c #DADAD6",
"oX c #D4D4DD",
"OX c #DBD5DA",
"+X c #D4DCDD",
"@X c #DADBDB",
"#X c #E3D3D6",
"$X c #D7E2DA",
"%X c #E2E8DF",
"&X c #DCDDE2",
"*X c #D6D8E7",
"=X c #C7D4E1",
"-X c #E2DCE7",
";X c #CBE4E4",
":X c #CFE1E8",
">X c #DCE2E3",
",X c #D5E5E6",
"<X c #E2E2E2",
"1X c #E8EAE7",
"2X c #F1F1F1",
/* pixels */
"|.|.|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|..X X|.|.|.|.|.|.",
"|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|.",
"|.|.|.|.|.|.|.@X@X|.|.|.|.|.@X@X|.|.|.|.|.@X@X_.|.|.|.|.@X@X|.).|.|.|.|.|.|.|.|.|.|.|.|.",
"|.|.|.|.|.@X{.F.F.{.XX|.|.+XJ.F.[.@X|.@XoXJ.G.~.@X|.|.oXY.K.`.@X|.|.|.@X X X X|.|.oX|.|.",
"|.|.|.|. X!.- , 4 - E.@X/.k , , * J.@X`.` U Q L C.OX'.[ U Q Y C.@X|.D.D./.D.J. X|.|.|.|.",
"|.|.|.|.{.k 8 8 8 8 - ;Xl 8 8 8 8 * }.[ ! ~ ~ ~ Y '.{ W ~ ~ ~ R ~.J.@X@Xu.2X~.!. X|.|.|.",
"|.|.|.@XJ., 8 8 8 8 < N.2 8 8 8 8 5 b.) ~ ~ ~ ~ W l.( ~ ^ ~ ~ ! { oXG.J.!.J.J.[.|.|.|.|.",
"|.|.|.@XJ., 8 8 8 8 4 m.3 8 8 8 8 5 g.) ~ ~ ~ ~ ! l.( ~ ^ ~ ~ ! k.*XN.D.|.N.G. X|.|.|.|.",
"|.|.|.|.{.- 8 8 8 8 - ;Xl 7 8 8 8 * }.[ ! ~ ~ ~ Y '.{ W ~ ~ ~ Y T.(.t.y.J.t.u..X|.|.|.|.",
"|.|.|.|.@X!.- 6 4 - E.&X/.k 6 4 ; J.$X`.` U Q L C.&X'.[ U W / z.oX|.D.J.|.D.Y. X|.|.|. X",
"|.|.|.|.|.@X$XN.l.$X@X|. X*XM.b.*X@X(.XX*XS.l.}.&X|.|.*XS.l.W.<X|.|.1X1X|.1X<X|.|.|.|.|.",
"|.|.|.|.@X!.*.>.>.*.!.@X].F N N G T.@X}.x 3 6 - F.&X{.v 2 6 r A.+X|.u.u. Xt.m.@X|.|.|.|.",
"|.|.|.|..X&.-.2.2.-.&.#XF Z Z Z Z m *Xv 5 8 8 8 = {.d.5 8 8 8 1 /.J.  X y.  o |.|.[. X|.",
"|.|.|.@XJ.:.2.2.2.2.:.M.N Z Z Z Z V n.w 8 8 8 8 5 m.e 8 8 8 8 5 d.&X$ $ Y.+ % @X|.|.|.|.",
"|.|.|.@XF.:.3.2.2.2.,.b.N Z Z Z Z C j.w 8 8 8 8 7 g.e 8 8 8 8 7 c ,XL.L.@XG.~.|.|.|. X|.",
"|.|.|. X_.%.1.3.2.1.%.#XG Z Z Z Z m oXx 7 8 8 8 1 [.v 7 8 8 8 : S.W.b e.A.H u.|.|.|.|.|.",
"|.|.|.|.@XL.%.=.4.%.J.@XT.m C C B D.&X/.k 4 5 1 N.@X[.l , 5 : s.+X|.D.C.|.M.J.|.|.|.|.|.",
"|.|.|.|.|.@XXXn.n..X@X(.#X*Xn.n.].-X[.OX,XZ.g.Q.>X).XX,XS.f.Q.>X|.|.-X<X|.@X@X|.|.|.|.|.",
"|.|.|.|.|.[.' p j ' '.@X|.] j p _ /.XX.Xc w 2 l !.|.+Xs.q w k J.@X.Xm.N.@XY./.OX|.|.|..X",
"|.|.|.|.oX_ h P f g _ :X' h P P g z :Xc 5 8 8 8 * ;Xs.4 8 8 8 1 [.J.  . M.y.u..X|.|. X|.",
"|. X|.@XJ.u P f f P u Z.p f f f P s V.q 8 8 8 8 5 l.n 8 8 8 8 5 s..X+ # /.m.M..X|.|.|.|.",
"|.|.|.@XG.u P P f f s m.p f f f P s m.w 8 8 8 8 7 f.e 8 8 8 8 7 v >XT.!.@XF.~.|.|.|. X|.",
"|.|.|.|.}.t f P f f j W._ f P P P i Q.l 8 8 8 8 : E.x 7 8 8 8 < L.].H y.J.q.u.|.|.|.|.|.",
"|.|.|.|.@XD.i h d i D.,XJ.t d d a z.&X!.; 5 7 : h.>X[.- 5 7 > d.OX].b.V.(.l.D.OX|.|.|.|.",
"|.|.|.|.|.&X[.x.k.^.@X).OX}.b.f.'.&X).@X;XM.f.Q.>X).|.,Xz.a.!.>X|.|.@X<X|.<X@X|. X|.|.oX",
"|.|.|.|.|.).c.5.6.c._.XX].k.( ) [ `.|..Xs.e q x ~.OX$XN.w.$.0.U.@X@XD.D.$XN.L.@X|.|.|.|.",
"|.|.|.|.XX*.-.2.<.=.*.&X{ W ~ ~ ! ` *Xs.4 8 8 8 - $Xb. .@.@.O.X.(.Y.  X u.  O |.|.|.|.|.",
"|.|.|.@XU.;.2.2.2.3.>.A./ ~ ~ ^ ~ U S.e 8 8 8 8 4 B.$.@.7.7.8.+.b.(.O + D.X # @X|.|.|. X",
"|.|.|.@XG.:.2.<.2.2.,.v.T ~ ~ ~ ~ W l.w 8 8 8 8 7 a.$.7.@.@.7.+.e.%XD.D.&XF./.@X|.|.|.|.",
"|.|.|.|._.%.<.2.3.<.5.~.( ~ ^ ~ ~ R E.l 8 8 8 8 : U.q.O.8.7.8.| H.J.@X@XN.y.u.|.|.|.|.|.",
"|.|.|.|.@XZ.;.1.-.;.Z.<XD.Y ! ~ R z.&XY.& 7 8 , ] *XU.X.#.O.| q.@X/.G.J.!.i.M.@X|.|.|.|.",
"|.|.|.|.|.XX~.c.c.~.XX(.|.`.P.P.T.+X|.@X}.h.a.E.>X].XX.Xb.p.L.$X|.|.|.|.@X@X+X|.|.|.|.|.",
"|.|.|.|.|.}.k.( ( z.]..X*Xj.K J j.]..X+XB.n n c [.|.XXA.0.9.e./.|.OX!.!.@XJ./.OX|.|.|.|.",
"XX|.|.|.*X{ W ~ ~ W } *Xj.M Z Z A F -Xh., 8 8 7 k ,XM. .@.@.+.o..X!.. X m.  @ |.|.|.|.|.",
"|.|.|.@X!.R ~ ~ ~ ~ T Y.D Z Z Z Z M S.e 8 8 8 8 4 C.w.@.7.@.8.+.b.(.X @ m.. + OX|.|.|.|.",
"|.|.|.@XG.U ~ ~ ~ ~ Q g.N Z Z Z Z C j.0 8 8 8 8 7 a.$.7.@.7.7.O.e.1Xi.m.1Xu.D.@X|.|.|.|.",
"|.|.|.XX~./ ~ ~ ~ ~ Y R.D Z Z A Z B W.k 8 8 8 8 > U.0.O.8.7.8.| A.!.  X y.  o |.|.|.|.|.",
"|.|.|.|.oXz.R ~ ~ U z.-XV.M Z Z M } &XD.1 8 8 4 v $XL...O.O.| 0.XX/.@ + D.o $ @X|.|.|.|.",
"|.|.|.|.|.OXJ.[ [ G.OX|.#XL.H H V.-X|.@X~.c x B.+X|.XX/.p.r.b..X|.@X@X|.@X.X@X|.|.|.|.|.",
"|.|.|.|.|.|.^.Y.Y.[.|.|.].`.T.T./.|.|.|.[.E.S.^.|.|.|.(.U.K.^. X|.|.|.|.|.|.|.|.|.|.|.|.",
"|.|.|.|.|.|.).^./.^.|.|.|.[././.^. X|.|.[.^.^.^.|.|.|.|.`.^.`.|.|.|.|.|.|.|.|.|.|.|..X|.",
"|.|.|.|.|.|.|.|. X|.|.|.|.|.|.OX|.|.|.|.|.|. X|.|.|.|.|.|..X X|.|.|.|.|.|.|.|.|. X|.|.|.",
"|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|..X|.|.oX|.|.|.|.|. X|.",
" X|.|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|. X|.|.|.|.|."
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 208 2 ",
"   c black",
".  c #1B1A1A",
"X  c #242424",
"o  c #393738",
"O  c #585858",
"+  c #686868",
"@  c #797979",
"#  c #DB0708",
"$  c #D61817",
"%  c #E40202",
"&  c #EA0000",
"*  c #E20A09",
"=  c #F30000",
"-  c #FE0202",
";  c #E71212",
":  c #E40C14",
">  c #CA1F20",
",  c #C72C2A",
"<  c #CB3C3C",
"1  c #C83131",
"2  c #D4312C",
"3  c #E02A3E",
"4  c #E46D02",
"5  c #F56F00",
"6  c #FE7D01",
"7  c #F97604",
"8  c #E97D0D",
"9  c #D77C24",
"0  c #D07B38",
"q  c #D57113",
"w  c #BF4C4C",
"e  c #BD5654",
"r  c #BB4A5D",
"t  c #BA5063",
"y  c #B76666",
"u  c #BA7777",
"i  c #B77E7E",
"p  c #B1717A",
"a  c #C84747",
"s  c #C45857",
"d  c #D34C41",
"f  c #C16458",
"g  c #CF5663",
"h  c #C37A7B",
"j  c #C36E69",
"k  c #00E500",
"l  c #00F600",
"z  c #02FE02",
"x  c #0BEA14",
"c  c #17E21C",
"v  c #25D627",
"b  c #38CC38",
"n  c #12D30F",
"m  c #40D732",
"M  c #54BF52",
"N  c #73B371",
"B  c #2FC940",
"V  c #48CB4A",
"C  c #59C363",
"Z  c #6DC175",
"A  c #FE8203",
"S  c #E48114",
"D  c #CA823B",
"F  c #D88B33",
"G  c #D9DA0A",
"H  c #D6D515",
"J  c #DEE41B",
"K  c #E4E403",
"L  c #E8E903",
"P  c #EFF300",
"I  c #F4F400",
"U  c #FEFE02",
"Y  c #E3E615",
"T  c #C9C934",
"R  c #D7D62F",
"E  c #CCE03E",
"W  c #BF8B59",
"Q  c #81B87D",
"!  c #BBBC61",
"~  c #B5B479",
"^  c #B58C66",
"/  c #C7884E",
"(  c #C0BE56",
")  c #C09A77",
"_  c #C49160",
"`  c #C5B566",
"'  c #B8C061",
"]  c #C3C348",
"[  c #CCD747",
"{  c #C3CA62",
"}  c #720E9C",
"|  c #700E99",
" . c #782C98",
".. c #7202A3",
"X. c #7800AC",
"o. c #7D01B2",
"O. c #770AA6",
"+. c #7F26A2",
"@. c #7E48AF",
"#. c #6972BC",
"$. c #1F3EF8",
"%. c #253EEC",
"&. c #253EF7",
"*. c #2E42D3",
"=. c #2942FC",
"-. c #2842F5",
";. c #354FFF",
":. c #3850FE",
">. c #3750FF",
",. c #4958C5",
"<. c #7979C9",
"1. c #6B79C9",
"2. c #8204B5",
"3. c #8301B9",
"4. c #854D9B",
"5. c #927A9C",
"6. c #B97687",
"7. c #8745A1",
"8. c #8455AE",
"9. c #8A67AD",
"0. c #9773A9",
"q. c #7ACA8A",
"w. c #778CCA",
"e. c #6784CC",
"r. c #878787",
"t. c #959595",
"y. c #9F9E9D",
"u. c #A88584",
"i. c #BD8080",
"p. c #BB8B8A",
"a. c #AD9A9B",
"s. c #BA9899",
"d. c #BB9C80",
"f. c #BCBC85",
"g. c #BBA895",
"h. c #BCBC95",
"j. c #A7A482",
"k. c #989CB3",
"l. c #908EAF",
"z. c #AD9DB6",
"x. c #BD9DA9",
"c. c #9DA1BD",
"v. c #A4A4A4",
"b. c #ACACAC",
"n. c #A8A5A5",
"m. c #BEABAB",
"M. c #B7A8A8",
"N. c #BAB9AA",
"B. c #AAABBB",
"V. c #B8ABB5",
"C. c #AABAB7",
"Z. c #BCBBBC",
"A. c #B7B5B5",
"S. c #A8BCA3",
"D. c #C39B96",
"F. c #C28D82",
"G. c #C5B191",
"H. c #C1AFAF",
"J. c #C5BAA9",
"K. c #C2B5B5",
"L. c #C2BABA",
"P. c #8FC18C",
"I. c #BCC292",
"U. c #BFC682",
"Y. c #99CAA6",
"T. c #B8C1B7",
"R. c #BDC3AC",
"E. c #C1C190",
"W. c #C1C1B5",
"Q. c #C2C2BD",
"!. c #C0C1AC",
"~. c #8A81C9",
"^. c #BABCC7",
"/. c #B0AFC2",
"(. c #C7BCC9",
"). c #BBC6CB",
"_. c #C4C3C3",
"`. c #CCCCCC",
"'. c #C7C8C6",
"]. c #D2CECF",
"[. c #CDD1CD",
"{. c #D4D4CE",
"}. c #D4D8CF",
"|. c #CECEDB",
" X c #CDCDD3",
".X c #D5CCD6",
"XX c #D1CFDB",
"oX c #CDD5D5",
"OX c #CED9D9",
"+X c #C7D6DB",
"@X c #D5D4D4",
"#X c #D8D7D7",
"$X c #D6DAD5",
"%X c #DADAD5",
"&X c #D4D4DD",
"*X c #D4DBDC",
"=X c #DADBDA",
"-X c #DBD4DB",
";X c #DDE3DB",
":X c #DADBE2",
">X c #D8D9E7",
",X c #CFDBE7",
"<X c #E0D9E7",
"1X c #D2E5E7",
"2X c #DBE2E4",
"3X c #D8E8E9",
"4X c #E3E4E3",
"5X c #E2E9E0",
/* pixels */
"@X@X@X].%X=X@X@X@X@X=X#X@X@X@X@X-X@X@X@X$X=X@X@X@X@X@X@X@X@X@X@X",
"@X@X@X1X_.L.*X@X=XoXA.`.*X@X:X'.Q.|.@X=X XZ.'.:X@X.X@X#X@X@X@X@X",
"@X@X*Xu # % w OX'.1 & $ s.>X~ G K (  X'.T L H h.&XT._._.).`.@X@X",
"@X=Xm.% - - = p.s - - - 2 N.K U U I f.{ U U U H ^.`.`.A.@X_.#X@X",
"].1Xp.= - - - y a - - - : j.I U U U ! ] U U U K Q.^.A.'.n.@X@X@X",
"@X=X'.$ - - % A.i = - - < ).H U U L N.f.I U U T &Xy.t.b.r.`.#X@X",
"@X@X=XH.d < D.*XoXh 3 g '.>XL.[ [ I.&X XU.E { '.#X`.`.].'.@X@X@X",
"@X@X%X{.w.e.^.%X&XY.C q..X=X Xp r K.*X;Xx.r 6.oX%X`.`.@X'.#X@X@X",
"@X@X`.,.&.&.*.^.P.k z l V XX, - - # K.s.% - - w 3Xo X +   Z.=X@X",
"@X%Xc.%.:.:.=.<.m l z z x u.= - - - y a - - - # _.r.@ n.O oX#X@X",
"@X%X/.%.:.:.&.~.V l z z c a.& - - - u s - - - * '.A.b.L.v.`.@X@X",
"@X@X@X#.-.-.,.].T.n z k P.>Xe = - , '.K.$ - & u 2Xn.v.Z.t.@X@X@X",
"@X@X@X=Xc.l.oX@X:X'.N B.<X#X3Xa.u.+X@X*X).^ B.3X}.;X4X%X2X@X@X@X",
"@X@X,X) 8 S W oX'.D 7 9 M.2Xi.$ ; s @X'.< ; > x.;X#.@ _.b.@X@X@X",
"@X%XA.4 A A 5 g._ 7 A 6 F B.# - - = p.j - - - $ }.o . A.r.`.#X@X",
"@X*Xg.7 A A 6 ^ / 6 6 A 8 ^ = - - - y a - - - = W.W.A.`.Z.@X@X@X",
"@X#X_.q 7 6 4 m.) 5 6 7 0 ).$ - - & M.i.= - - 1 $Xa.t.b.r.'.%X@X",
"@X@X:XJ.F F G.,XoX) 0 _ _.2XH.a < p.*X@Xh 2 s Q.*X'.'.@X'.@X@X@X",
"@X@X=X`.w.1.).%X&XR.' I.|.#XoXi y L.=X%X/.9.k.$X#X@X[.=X'.-X@X#X",
"@X@X].,.&.&.*.^.G.K U I ( +X1 - - # L.z...o...4.2Xo X +   Z.*X@X",
"oX=XB.&.;.;.=.1.R U U U Y u.= - - - f 8.o.2.3...'.@ + v.O `.@X@X",
".X=XB.%.:.;.-.<.[ U U U Y a.& - - - j 8.o.2.3.} Z.oX@XZ.n.@X@X@X",
"@X@X{.#.&.-.,.`.N.H U K ~ ,Xs = - > '.A.} X...0.#XZ._.b.t.`.@X@X",
"@X@X@X@Xk.l. X%X-X(.~ N.:X@X1Xa.u.+X*X;X'.5.b.;X@X=X=X4X4X=X@X@X",
"@X@X#Xf.G Y { XX'.V x v S.2Xp.$ ; e *X`.7.O.7.B.4Xr.r.v.+ `.@X@X",
"@X*XZ.K U U I G.C z l z v V.* - - = F.9.X.2.o.} %Xo X +   Z.%X@X",
"@X:Xh.I U U U ` B z l z x u.= - - - f @.2.o.2..._.v.t.Z.@ #X#X@X",
"@X#XZ.H U U L J.N z z z b (.$ - - * D.0...2.o. .=Xo . +   A.*X@X",
"@X@X=XN.T R f.&X.XN c V Q.:XM.< 2 i.:X{.0.+.7.Z.4Xn.v.^.t.@X@X@X",
"@X@X@X&X^.B.&X@X=X.XV.(.%X@X%X).C.*X@X@X}.C.Q.%X@X=X=X#X4X@X@X@X",
"@X@X@X@X{.`.{.@X@X[.`.[.@X@X@X`.'.@X@X@X`.].`.@X@X@X@X@X@X@X@X@X",
"@X@X@X@X@X@X@X@X@X@X#X#X@X@X@X@X#X@X@X@X=X@X@X@X@X@X@X@X@X@X@X@X"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 240 2 ",
"   c #D5D4D4",
".  c #D2DBDB",
"X  c #C9C4C4",
"o  c #D1D7D7",
"O  c #CAC5C4",
"+  c #D4DDE1",
"@  c #CDCCCF",
"#  c #CCCCC9",
"$  c #D5D5E3",
"%  c #CBCBC7",
"&  c #CECED2",
"*  c #D5D5D8",
"=  c #D2D2D2",
"-  c LightGray",
";  c #D5D5D5",
":  c #D3E1E1",
">  c #D18181",
",  c #F00000",
"<  c #D06F70",
"1  c #D55E5C",
"2  c #EF0201",
"3  c #C88E8A",
"4  c #E2EC33",
"5  c #E9E51B",
"6  c #C6C692",
"7  c #ECEA12",
"8  c #E0DF37",
"9  c #C7C7CA",
"0  c gray77",
"q  c #CACACA",
"w  c #D1E4E4",
"e  c #D65C5D",
"r  c red",
"t  c #D44546",
"y  c #DD3735",
"u  c #C86A5A",
"i  c #F0FF14",
"p  c #FBF700",
"a  c #C5C45F",
"s  c yellow",
"d  c #F0EF14",
"f  c #BBBBB7",
"g  c #B0B0B1",
"h  c #BEBEBD",
"j  c #D8D8D8",
"k  c #D7D9D9",
"l  c #CCC8C7",
"z  c #9C5A7B",
"x  c #CBC1C8",
"c  c #C1BAAD",
"v  c #957E50",
"b  c #D1D4E0",
"n  c #C7AE84",
"m  c #C5A16B",
"M  c #CDDCE8",
"N  c #C49B5F",
"B  c #C9B492",
"V  c #C7CDD4",
"C  c #B5B3B2",
"Z  c gray76",
"A  c #D7D7D7",
"S  c #E0DED1",
"D  c #7A87D5",
"F  c #1541FF",
"G  c #6A6FDF",
"H  c #3BE72D",
"J  c green",
"K  c #72BC65",
"L  c #FD0819",
"P  c #F50603",
"I  c #C56B6B",
"U  c #FA0000",
"Y  c #F42122",
"T  c #989595",
"R  c #5B5C5C",
"E  c #8D8C8C",
"W  c #DFDFDF",
"Q  c #DFDDD1",
"!  c #8792D6",
"~  c #1E41FF",
"^  c #7A7CE1",
"/  c #4CE445",
"(  c #00FD03",
")  c #82C37D",
"_  c #F3232E",
"`  c #EB1D18",
"'  c #C78484",
"]  c #F11310",
"[  c #E53331",
"{  c #B9B9B9",
"}  c #C0BFBF",
"|  c #D6D8DA",
" . c #D1C8BC",
".. c #B78359",
"X. c #D1C4B8",
"o. c #CCBAA8",
"O. c #B5904A",
"+. c #D4D5D9",
"@. c #C87E7E",
"#. c #C86565",
"$. c #CDE1E1",
"%. c #C75959",
"&. c #CD8E8E",
"*. c #B8C5C5",
"=. c #AAA8A8",
"-. c #CECECE",
";. c #D0DBE4",
":. c #D49258",
">. c #FF7100",
",. c #D3853F",
"<. c #DC8330",
"1. c #FF7600",
"2. c #C78151",
"3. c #F00912",
"4. c #FC0100",
"5. c #C45657",
"6. c #FE0000",
"7. c #F71818",
"8. c #958E8E",
"9. c #7D7F7F",
"0. c #BEBDBD",
"q. c #D3D9DF",
"w. c #D6B793",
"e. c #EE820C",
"r. c #D7B185",
"t. c #D1A17D",
"y. c #DF7A22",
"u. c #CBB8A8",
"i. c #D85053",
"p. c #DC3C3C",
"a. c #CBAFAD",
"s. c #E63327",
"d. c #DE5A50",
"f. c #CED4D4",
"g. c #C9C8C8",
"h. c gray84",
"j. c #DCDAD4",
"k. c #ABB4D7",
"l. c #4960DE",
"z. c #9BA6E1",
"x. c #D6DA85",
"c. c #D3D935",
"v. c #CBD6BD",
"b. c #D26066",
"n. c #D54E4B",
"m. c #C5C4CC",
"M. c #8542B0",
"N. c #A275C2",
"B. c #AEB3AE",
"V. c #7A797A",
"C. c #A2A2A2",
"Z. c gainsboro",
"A. c #E1DFD0",
"S. c #6875D3",
"D. c #0E2DFF",
"F. c #4A5BDB",
"G. c #E9E71F",
"H. c #C6B44F",
"J. c #EF0013",
"K. c #FF0300",
"L. c #A1547F",
"P. c #7100B7",
"I. c #7E13AB",
"U. c #A6A3A8",
"Y. c #858684",
"T. c #9D9C9D",
"R. c #DDDDDD",
"E. c #DBDAD5",
"W. c #B5B8D5",
"Q. c #5A69CB",
"!. c #A9ACDE",
"~. c #DAD296",
"^. c #CCCB41",
"/. c #D4D6CC",
"(. c #CC7073",
"). c #CE5B5A",
"_. c #CDD4D3",
"`. c #9050A8",
"'. c #A47CB3",
"]. c #DBE0D9",
"[. c #D2D1D2",
"{. c #CDCDCD",
"}. c #D2D2E1",
"|. c #D6D685",
" X c #F9F900",
".X c #E2D673",
"XX c #53D46B",
"oX c #02EC14",
"OX c #92C894",
"+X c #E93A44",
"@X c #E52F28",
"#X c #BA9BAE",
"$X c #8223AE",
"%X c #9C50B8",
"&X c #A3A4A2",
"*X c #6A6A6A",
"=X c #979697",
"-X c #D1D1E4",
";X c #D4D55B",
":X c #DDD443",
">X c #26DB34",
",X c #68B758",
"<X c #FF0315",
"1X c #FE0400",
"2X c #A55D86",
"3X c #6F00B3",
"4X c #851CB2",
"5X c #8F8C8F",
"6X c #4D4E4D",
"7X c #838283",
"8X c gray88",
"9X c #D6D6D8",
"0X c #CFCFC8",
"qX c #C2C375",
"wX c #D4CEC4",
"eX c #B3CCB7",
"rX c #7AC278",
"tX c #D0D8D7",
"yX c #C99A9B",
"uX c #C68A8A",
"iX c #D4DCD9",
"pX c #A482B0",
"aX c #B8A5C0",
"sX c #CACEC9",
"dX c #B2B1B2",
"fX c #C1C1C1",
"gX c gray83",
"hX c #D5D5D7",
"jX c #CECEDF",
"kX c #D3D5D8",
"lX c #DAD4D9",
"zX c #DECEDF",
"xX c #D7D5D6",
"cX c #D1DCDB",
"vX c #D0DDDD",
"bX c #D6DED3",
"nX c #D6DAD4",
"mX c #D8D8D9",
"MX c #DADADA",
"NX c white",
/* pixels */
"  . X . o O + @ # $ % & * = - ; ",
": > , < 1 2 3 4 5 6 7 8 9 0 q ; ",
"w e r t y r u i p a s d f g h j ",
"k l z x c v b n m M N B V C Z A ",
"S D F G H J K L P I U Y T R E W ",
"Q ! ~ ^ / ( ) _ ` ' ] [ 0 { } j ",
"|  ...X.o.O.+.@.#.$.%.&.*.=.-.; ",
";.:.>.,.<.1.2.3.4.5.6.7.8.9.0.A ",
"q.w.e.r.t.y.u.i.p.a.s.d.f.g.g.h.",
"j.k.l.z.x.c.v.b.n.m.M.N.B.V.C.Z.",
"A.S.D.F.G.s H.J.K.L.P.I.U.Y.T.R.",
"E.W.Q.!.~.^./.(.)._.`.'.].[.{.h.",
"}.|. X.XXXoXOX+X@X#X$X%X&X*X=XR.",
"-X;Xs :X>XJ ,X<X1X2X3X4X5X6X7X8X",
"9X0XqXwXeXrXtXyXuXiXpXaXsXdXfXA ",
"gXhXjXkXlXzXxXcXvXxXbXnXmXR.MXgX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
