#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 72 1 ",
"  c #000000",
". c #0B0B0B",
"X c #151515",
"o c #1C1C1C",
"O c #232323",
"+ c #2E2E2E",
"@ c #333333",
"# c #3C3C3C",
"$ c #007F00",
"% c #434343",
"& c #4C4C4C",
"* c #525252",
"= c #5D5D5D",
"- c #646464",
"; c #6C6C6C",
": c #737373",
"> c #7C7C7C",
", c #008600",
"< c #028A02",
"1 c #0B8E0B",
"2 c #149214",
"3 c #1C941C",
"4 c #229722",
"5 c #249824",
"6 c #299A29",
"7 c #349E34",
"8 c #37A037",
"9 c #3BA13B",
"0 c #43A443",
"q c #4EA94E",
"w c #54AB54",
"e c #5CAE5C",
"r c #64B264",
"t c #6BB46B",
"y c #71B771",
"u c #75B975",
"i c #7CBB7C",
"p c #828282",
"a c #8D8D8D",
"s c #949494",
"d c #9C9C9C",
"f c #82BE82",
"g c #A3A3A3",
"h c #AAAAAA",
"j c #B2B2B2",
"k c #BDBDBD",
"l c #87C087",
"z c #8BC18B",
"x c #93C593",
"c c #9BC79B",
"v c #9CC89C",
"b c #A4CBA4",
"n c #AFD0AF",
"m c #B3D1B3",
"M c #BCD5BC",
"N c #C5C5C5",
"B c #CCCCCC",
"V c #C1D7C1",
"C c #C5D8C5",
"Z c #CCDBCC",
"A c #D4D4D4",
"S c #D2DED2",
"D c #DFDFDF",
"F c #D7E0D7",
"G c #DCE2DC",
"H c #E6E6E6",
"J c #E9E7E9",
"K c #ECEBEC",
"L c #F5EBF5",
"P c #FAEEFA",
"I c #F3F3F3",
"U c #FCFCFC",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"   .@++++++++++++++++++++++++++++++++++++++++@   ++++++++++++++++++++++++++++++++++++++++++@.   ",
"   @UIUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUX .UIUUUUUUUUUUUIIUUUUUUUUUUUUUUUUUUUUUUUUUUIU@   ",
"   +IDAjdshAHDDDDDDDDDDDDDDHDDDDDDDHDDDDDDDDDKX .KHAkdsgBHDGHDKIDDDDDDGGDDDHDDDDDDDHDDDDDDDI+   ",
"   +UIs   .*AKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKX .KKk    #NKHHKhgHHHHHHHHHHHHHHHHHHHHHHHHHHDU+   ",
"   +IKd&gsO dKDHDHHDHHHHHHHHHHHHHHHHHHHHHHHHHIX .KKk%dd# >KHDKX DHHHHHHJHHHHHHHHHHHHHHHHHHDU+   ",
"   +UHGKIU* dKKKKKKKLKHHHHKHHHHHHHHHHJHHHHHJGIX .KHDKIUp :KKKIdaIIKHHHHHHHHHHHHHHHHHHJHHHHGU+   ",
"   +UDHGKhXoNKBMkmkkkBJHHHHHHHHKHHHHHHHHHHHHHIX .KHHGKNO.hUa%#&*##:IHHHHHHJHJHHJHHHHHHHHHHGU+   ",
"   +UDHKgXohJJ:XXXXX -UGHHHHHHHHHHHHHHHJHHHHHKX .KHHKkO.sHKs*&==&&pKGHHHHJHJHHHHHHHHHHHJHHDU+   ",
"   +UDJs #NUKJNggggggkKHHHHHHHHHHHHHHHHHJHHHHIX .KHKhXOjUKHHHK:=HHHHJJHHHHHHJHHHHHHHHHHHHHDU+   ",
"   +UKd .&:=hJLIIUIIIIHHHHHHHHHHHHHJHHHHHHHHGIX .KKk. #:=sHHHIo JJJHHHHHHHHHJHHHHHHJHHHHHHDU+   ",
"   +ILp     :DHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHHIX .KKh     &DKGHBNGHHHHHHHHHJHHHHHHHHHJHHHHHDU+   ",
"   +UDDAABBBDHHHHHHHHHHHHHHKHHHKHHJHHJHJHHHHHIX .KJGABBABDHHHHKKHHHHHHHHHHHHHHHHHHJHHJHJHHHU+   ",
"   +UDHKKKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHGIX .KHKKKKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDU+   ",
"   +UHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHHHHHJJKKKKJHHHHHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHKHHHHHHHHKHHHHHHHHHJHHHHHHDIX .KHHHHHHHHHHHHJHHHJHGAZSAFHJHHHHJHJHHJHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHJHJHHHHHHHHHHKX .KHHHJHHHHHHHHHHHHbt82<,<4rMJJHHHHHJHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .JHHHHJHHHHHHHHHLC$,<,,<<<,1cJHHHHHHJHHHHHDU+   ",
"   +UDHHHHHHHHHJHHHHKHHHHKHHHKHHHHHHHHHHHHJHGIX .KHHHHHJJHHHHHHHKC,,1563<,<<1CKHHHHHHHHHHHHU+   ",
"   +IHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHHIX .KGHHHHHHHHHHHHHKC,qzMZmw<,1,zHHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHKHHHHHHHHHHHHHHHHHHHHHHJHHKX .KHHHHHHHHHHHHHHHSxKLKGLG8,<,rHHHHJHHHHHHHDU+   ",
"   +UDHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHJHJHJHHHIX .KHHHHHHHHHHHHHHHJLHGHHDLw,<,tHHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGIX .KHHHHHHHJHHHHHHHHHHDHHHD7,1<bJHHHJHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHKHHHKHHHHHHHHHHKHHHHHJHHJHIX .KHHHHHHHHHHHHHHHHHHHHHLy,<,9FJHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHJHHHHHHHHHHHHKHHHHHHHHHHHHHHHGKX .KHHHHHHHHHJHHJHHHHHHHHi1<,5MKHHHHHHHHJHHHDU+   ",
"   +UHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHLX .KHHHHHHHHHHHHHHHHHHHHr,<,6mKHHHHHHHHHHHHHDU+   ",
"   +UDHHHHHJHHHHHHHHHHHHHKHHHHHHHHHHKHHHHHHHHIX .KHHHHHHHHHHHHHHHHHJGw<<,7MKHHHHHHHHHHHHHHHU+   ",
"   +UDHHHHHHJHHHHHHHHHHHHHHHKHHHHHHHHHHHHHHHGIX .KHHHHHKHHHHHJHHHHJS7,<,0ZJHHHHHHHHHHJHHHHDU+   ",
"   +UDHHHHJHHJHJHHKHHHHKHHHHHHHHHHHKHHHHHHHHHIX .KHHHHHHHHHHHHHHHKV5<<,wDKHJHKHHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHJZ2<<,3iffifibHHHHHHHHHHHHDU+   ",
"   +UGHHHHHHHHHKHKHHHHHHHHHHJHHHHHHHHHHHHHHHHIX .KHHHHJHJHHHHJHHJM,<<<<<<<<<,0GJHHHHHHHJHHDU+   ",
"   +UDHHHKHHHHHHHHHHHHKHHHHJHHHHHHHHHHHHHHHHHIX .KHHHJHHHHHHHHHHKM$,,,,,,,,,,9GKHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKHHHHHDIX .KHHHHHHJHHHHHHGJV25444444443eGHHHHJHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHJHHHHHJKHHHHHHHKHHHHKX .KHHHHHHHHJHHHJJHKPLLPLLLLPLLLHHHHHHJHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KGHHHHJHHHHHHJHJHGGHGHHHGHHGHHHHHHHHHHHHHHU+   ",
"   +UGHHHHHHHHHHHHHHHHHHHHJHJHHHHHHHHHHHHHHHDIX .KHHHHHHJHHHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHDU+   ",
"   +UHHHHHHHHHKHHHHHHHHHHHHHHHHJHKHHHHHHHHHHHKX .KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKHHDU+   ",
"   +UGHHHHKHHHHHHKHHHHHHHHHHJHHHHHHHHHKHHHHHHIX .KHHHHHHHHJHHHHHJHHHHHHHJHHHHHHHJHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHKHHHHHHJHHHHHHHHHHHHHHHHHGIX .KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHJHHU+   ",
"   +UDHHHHHKHHHHHHHHHHHHHHHHHHJHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHDU+   ",
"   +UHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKX .KHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHHHHHHHHHHDU+   ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHHHHHHHKHIX .KHHHHHHJHHHHHHHHHHHKHHHHHHHHHHHJHJHHHHHHHHI+   ",
"   +IDHHHHHHHHHHHHHHHHHHHHHHHHHHKHHHHHHHHHHHGIX .KHGHDHHGHHHHHGHHDHHDHHHHGHDHGHHGHHGHHHDHDDU+   ",
"   +UDHHHHHGHHHGHHHHHHHHHHHGHHHHHHGHHHHHHHHHGIX .IIIIIKIIIKIIIIIIIKIIIKIIIIIIIIIIKIIIKIIKIKU@   ",
"   +UHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKIo  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
"    ..........................................                                                  ",
"   +IDDHDDHDDHDDGHGGHDGHDDHDGHDDDHDDDHGGDHDDDKX  ..........................................     ",
"   +UDJHHHHHHHHHHHJJHHJHHHHHJJHHHHHHHJHJHHHHHIX .IKKKKIIIKKKKIIIKKKKKKKKKKKKKKKKKKKKKKKKKHU%    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKX .KHHHHAkBHHKDNNBJHHHHGJHHHHHHGHHHGHHHHHHHDU#    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KGHKA% +jKA=  osKHKHKGKHHHHHHHHHHHHHHHHHHU%    ",
"   +UGHHHHJHHHHHHHHKHHHHHHHHHJHHHHHHHHHHHHHHDIX .KHHK; X+kU- %>..NKj:HKKaaJHHHHHHHHHHHHHHDU#    ",
"   +UDHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHJHJHHHHHHIX .KHId.;+okH@ NU* :Ka ;Ks -HJHHHHHHHHHHHHHDU#    ",
"   +UDHJHHHHHHHHHHHHKHHHHHHHHHHJHHHHHHHJHHHHHKX .KKNO:AooAAo NK: *IKpX*O*HKHHHHHHHHHHHHHHDU#    ",
"   +UDHHJHHHHJHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHHIX .KH:.dsXXsjO BI: &KJK- #DKGJHHHHHHJHHHHHHHU#    ",
"   +UGHHHHHJHHHHHHHHHHHHHHHHHKHHJHHJHJHHHHHHHKX .KD&      d# BU= :KKh+OOpJHHHJHHHHHHJHJHHDU#    ",
"   +UDHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHJHHIX .KDhpa:Xo:H= =sX kKg.%A; yHHHHHHHHHJHHHHHDU#    ",
"   +UDHHHJHHHHHJHKHHHHHHHKHHHHHHHJHJHHHJHHHHGIX .KHIUUBooNUN&  .>KJg&DIJ->HJHHHHJHJHJHHHHDU#    ",
"   +UDHHHHHHHHHHHHHHHHHKHHHHHHHHHHHHHHHHJHHHHIX .KDHHHAhjDHKAjgkHHJHALDKDDJHHHHHHHHHHHHHHHU#    ",
"   +UDHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHIX .KHHHHKIIHHHKIIKHDJHJHHHJJHHHHHHHHHHHHHHHDU#    ",
"   +UGHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHHHDIX .KHHHHHHHHHHHHHHHHHHDDHJJJHHHHHHHHHHHHHHHDU#    ",
"   +UHHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHKX .KHHHHHHHHHHHHHHJHJKJLJJLJJJKJHHJHJHHHJHHDU#    ",
"   +UGHHHHHHHHHHHHKHHHHKHHHHHHHHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHKDt,111111115ZKHHHHHHHHHHHU#    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGIX .KHHHHHHHHHHHHHHKGr,<<,,<,<,3ZKDJHHHHHHHHHU#    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHKHHHHHHHHHHHKHIX .KHHHHHHHKHHHHHHHHr<<<<<<<1<5ZKHJJJHJHHHHDU#    ",
"   +UHHJHHHHHHHHHHHHHHHKKHHHHHHHHHHKKHHHHHHHHKX .KHHHHHHHHHHHHHHKGr<,6vvvcczcGJHHHHHHHHHHDU#    ",
"   +UDHHHHHHHHKHHHKHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHJHHHHHHHHHHHHHr<,8ZMMZGLKHHHHHHHHHHHHDU#    ",
"   +IDHHHHHHHHHJHHKHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHHJHHHHHHHHHHKGr,<11,,20cDHHHHHHHHHHJHDU#    ",
"   +UHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGIX .KGHHHHHHHHHHHHHHHt,<,,,<<,,yHJHHHHHHHHHHHU#    ",
"   +UDHHHHHHHHHHHHHHHHHHKHHHHHHKHHHHHHHHHHHHHKX .KHHHHHJHHHHHHHHHHe,37061,<<,bKJHHHJHHHHHDU#    ",
"   +UDHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHJHHKHHIX .KHHHHHHHKHHHHHHHGzumZDZz3,<,0GJHHHHJHHHHDU%    ",
"   +UDHHHHHHHJHHHHHHHKHHHHKHHHHHHHJHHHHHHHHHHIX .KHJHHHHHHHHHHHHHHHPKJHJPu,<<1SKHJHJJHHHHHU#    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDIX .KHHHJHHHHHHHHHHHHHGGHHGLb2,<,ZKHHHHHHHHHDU#    ",
"   +UDHHHHHHHHHJKHHHHHHHHHHHHHHHHHJHHHHHHHHHHKX .KHHHHHHHHHHHHHHHJKHHHHGKv2,<,SJHHHHHHHHHDU#    ",
"   +UHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHHHHIX .HHHHHHHHHHHHHHHJCfKLJHJPr,<<3SKHHJHHHHHHDU#    ",
"   +UDHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKDIX .KHHHHJHHHHHHHHHJn,7fmCme1,<,rHHHHHHHHHHHDU#    ",
"   +UDHHHHHHJHHHHHHHHHHHHHHKKHHHHJHHHJHHHHHHHIX .KHHHHHHHHHHHHHHJn,,<222<,<<2VJHHHHHHHHHHHU#    ",
"   +UDHHHHJHHJHJHHHHHKHHHHHHHHHHHHHHJHHHHHHHHKX .KHHHHHHHHHHHHHHJm,,,,,,,<<4nJHHHHHHHHHHHDU#    ",
"   +UDHHHHHHHHHHKHHHHHHHHHHHHHHHHJHJHHHHHHHHHIX .KHHHHHHHHHKHHHHJJCf041<28fSKHHHHHHHHHHHHHU#    ",
"   +UDHHJHJHHHHHHHHHHHHHHHHHHHHHJHHHJHHHHHJHGIX .KHHJHHHHJHHHJHHHHJHHHHHHHHJHHHHHHHHHHHHHGU#    ",
"   +UGJHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KGHHHHHHHHJHHHHHHHHHHHHHHHHHJHHHJJHHHHHHHU#    ",
"   +UDHHHHJHHHHHHHHHHKHHHHHHHHHHJHJHHHHHJHHHHKX .KHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGU#    ",
"   +UDHHHHHHHJHHHHHHHHHHHHHKHKHHHHHHHHHJHHHHHIX .KHHHHHJHHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGU#    ",
"   +UDHHJHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJHHHHJHHDU#    ",
"   +UDHHHHHHHHHHHKHHHHHHHHHHHHHHHHHJHHHHHHHHGIX .KHHHHHHHJHHHHHHHHHJHHHJHHHHHHHHHHHHHHHHHHU#    ",
"   +UGHHHHHHHHHHHHHHKHHHHHHHHHHHHJHHHHHHHHHHHIX .KHHJHHHHHHHHHHHHJHHHHHHHHHHHHHHHHHJJHHHHDU#    ",
"   +UGHHHHHJHHHHHHHHHHHHHHHHKHHHHHHHHHHHHHHHHKX .KHHHHHHHJHHHHHHHHHHHHHHHKHHHHHHHHHHHHHHHDU%    ",
"   +UDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIX .KHHHHHHHHHHHHHHHJHHHHHHHHHHHHHHHHHHHHHHHHU#    ",
"   +IDDDDHDHDDDHDHDDHDDHHGHGDDDDDHDHDDDHDDDHDKX .KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDU#    ",
"   @UIUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUIUo .JGHDDGDDDDDHDDDGDDDDDHDDDDDHDDDDDDDHDDDDAI#    ",
"   .%##################%#####################%  .UIUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUIU%    ",
"                                                 +++++++++++++++++++++++++++++++++++++++++@.    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 75 1 ",
"  c #010101",
". c #0B0B0B",
"X c #151515",
"o c #1C1C1C",
"O c #242424",
"+ c gray17",
"@ c #343434",
"# c #3B3B3B",
"$ c #007E00",
"% c #434343",
"& c #4A4A4A",
"* c #535353",
"= c #5B5B5B",
"- c #656565",
"; c #6B6B6B",
": c #747474",
"> c #7C7C7C",
", c #008400",
"< c #028A02",
"1 c #0A8E0A",
"2 c #0E900E",
"3 c #139213",
"4 c #1B941B",
"5 c #209720",
"6 c #259825",
"7 c #2B9B2B",
"8 c #349E34",
"9 c #39A139",
"0 c #43A543",
"q c #4AA64A",
"w c #4DA84D",
"e c #55AB55",
"r c #5BAE5B",
"t c #5FB05F",
"y c #63B163",
"u c #6CB56C",
"i c #70B670",
"p c #75B875",
"a c #7BBB7B",
"s c #858585",
"d c #888888",
"f c #949494",
"g c #9C9C9C",
"h c #82BE82",
"j c #A4A4A4",
"k c #ACACAC",
"l c gray70",
"z c #BABABA",
"x c #86C086",
"c c #8DC28D",
"v c #93C593",
"b c #99C799",
"n c #9DC89D",
"m c #A2CAA2",
"M c #ABCEAB",
"N c #AFD0AF",
"B c #B5D2B5",
"V c #BBD5BB",
"C c #C5C5C5",
"Z c #CACACA",
"A c #C1D7C1",
"S c #C5D9C5",
"D c #CCDBCC",
"F c #D4D4D4",
"G c #D2DDD2",
"H c #DEDEDE",
"J c #DEE2DE",
"K c #E6E6E6",
"L c #E9E7E9",
"P c #EDECED",
"I c #F3EBF3",
"U c #FBEEFB",
"Y c #F4F4F4",
"T c #FFF0FF",
"R c #FBFBFB",
/* pixels */
"                                                                                        ",
"      . .   . . .  .. .  .. .  .. .  .. .        .. .  .. .  ..   . . .  .. .  .        ",
"                                                                                        ",
"   &fdddddddddddddddddddddddddddddddddddd:  *fdddsddddddddddddddddddddddddddddddddf-    ",
"   fRYRRRRRYRRYRYRRRRRYRRRRRRYYRRRRYRRYRRH  fRYRRRRRRRRRRRRYRRYRRRRRRYRRRRRRRYYRRYRz    ",
" . sRF=Oo@jKKHHKKJHKHJKKKHHKHKKKHHKKHKKHLC  sYF=Oo@jKKHKKHJKHKHKJKJKKKJJKHHKHKKKKHYk    ",
" . dRFX&&..CLKKKKKKKKKKLKKKKKKKKKKKKKKKKPZ  dRFo&&. CLHR; FLKKKKKKKKKKKKKKKKKKKKKKYk    ",
"   dRHZYR* lLLLLPLLLKKKKKKKKKKKKKKKKKKKKPZ  dRFFPR* kPPRg&KRLKKKKKKKKKLKKKKKKKKKKKYk    ",
" . dRKKPZOoFKFZZZZZFLKKKKKKKKKKKKKKLKKKKPZ  dYKKLZOXFJ;=-;==gPKKKKLKKKLKPKKKKKKKKHYk .  ",
"   dRJLZOXkPF&ooooX;YKKKKKKKKKKKKKKKKKLKPZ  dYHLZ+XkPF=%**&%fYKKKKKKLKKKKKKKKKKLKKYk    ",
"   dYKlX+CYKKzkkkkjVLKKKKKKKKKKKKKKKKKKJPZ  dRKzX+CYLKKYf%HPKKKKKKKKKKLLKKKKKKKKKKYk    ",
" . dRF. O%#kKPYYYYRYKKKKKPKPKKPKKLKKKKKKPZ  dRF  O&@kLKR; FPKKKKKKKKKKKKKKKKKKKKKKYk    ",
" . dRFOOOOogLKKKKKJKKKKKKKKKKKKKKKKKLKKKPZ  dRFOOOOogLKKKKKKKKKKKKKKPKKKKKKKKKKKKKYk    ",
"   dRKYYYYYKKKKKKKKKKKKKKKKKKKKKLKKKKKKKPZ  sRKYYYYYLKLKKKKKKKKKKKKKKKKKKKKKKKLKKHYk    ",
"   dRHKJKKKKKKKKKKKKKPKKKPKKKKKKKKKKKKKKPZ  sRHKKKKJKKKKKKKKKKKJKKKKKKKKKKKPLKKKKKYk .  ",
"   dRHKKKKKKKKKKKKKKKKKKKKKKKKPKKKLKKLLKPZ  sRHKKKKKKKKKKKKKKIIIIYYPKKKKKKKKKKKLKKYk    ",
" . dRKKKKKKKPKPKKKKKKKKKKKKKKKKKKLKKKKKKPZ  dRHKKKKKLKKKKKKKDcy089ecJLKKKKKKKLKKKKYk    ",
"   dRHKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKPZ  sYKKKKKKKKKKKKLB<1<,,,<<6VPKKKKKKLKKKKYk    ",
" . dRHKKKKKPKKKKKKKKKKKKPKKKPKKKKKKKKKKKPZ  sRKKKKKKKLKLKJPB$<144<<<,6JLKLKKKKLKKKYk    ",
"   dRKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKPZ  dYHKKKKKKLKKKKIB<tnSSa1,<,nLKKKKLKKKKKYk .  ",
" . dRHKKKKKKLKKKKKKKKKKKKKKKKPKKLKKKKKKKPZ  sRHKKKKKLKLKKKLDNIPLLIu,<,aLKKKKLKKKKHYk .  ",
"   dYKKKKKKKKKKLKPKKKKKKKKKKKKKKKKLKKKKKPZ  sRKKLKKKKKKKKKKLIKKKKPh,1,cLKKKKKKLKKKYk    ",
"   dRJKKKKKKKKKKKKKKKKKKKPKKKKKKLKKKKKKKPZ  sRHKKKKKKLKKKKKKJKKKLKw<<<DLKKKKKKKKKKYk    ",
" . dRKLKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKPZ  dYKKKKKLKKKKKKKKKKKKLa<<,aLKKKKKKLKKKKYk    ",
" . dRKKKKKKKKKKKKKKKKKKKPKKKPKKKKKLKKKKKPZ  dYKKKKLKKKKKKLKKKKLKp<<,tKKKKLKKKKKKKHYk    ",
"   dYKKKKKKKKKLKKKPKKKKKKKKKKKKKKKKKLKKKPZ  dRHKKKKKKLKKKKKKJLHr,<,uKKKKKKKKLKKLKKYk    ",
" . dRHLKKKKKLKLKKKKKKKPKKKKKKKKKKKLLLKKKPZ  sRHKLKKKKKKKKKKKPG9,,<aLKKKKKKLKKKKKKKYk    ",
"   dRKKKLKKKKKKKKKKKKKKKPKKKKKKKLKKKKKKJPZ  sRKKKKKKLKKKKKKPS7<<1bILLPLKKKKKKKKKKKYk    ",
"   dRHKKKKKKKKKLKKKKKKKKKKKKKKKKKKKLKKKKPZ  dYJKKLKKKKKKKKLA4,<,ebvcvcBLKKLKKKKKKKYk .  ",
" . dRKKKKKLKKKKLKKKKKKKKKKPKKKKPKKKKLKKKPZ  dRKKKKKKKKKKKKIM,1<<1<<11<yLKKLKKKLKKKYk    ",
" . dYHKKKKKKLKKKKKKKPKKKKKKKKKKKLKKKKKKKPZ  sYKKKKKLKKKKKKIM$,,,$,,,,,eLKLKKKKKKKKYk    ",
"   dRKKKKLKKKKLKPKKKKKKKKKKKKKKKKKKKKKKKPZ  dRJKLLKKKKKKKKLAqrereeeeeecLKKKLKKKKKKYk    ",
" . dRJKKKKLKKKKKKKKKLKKKKKLKKKKKKKKKLKKKPZ  dYKKKKKKKKKLKKKLTTTTUTUUUTIKKKKKKKLLKKYk .  ",
"   dRKKKKKKKKLKKKKKKKKKKKKKKKLKKLKKKKKKKPZ  dRHKKKKKKLKKKKKKKJJJJKJKJJKKKKKKKKKKKKYk    ",
"   dRJKKLKKKKKKKKKKKKKKLLKKKKKKKKKKKLKKKPZ  sRHKKKKKKKKKKKLKKKKKKKKKKKKLKKKKKLKKKJYk    ",
" . dRHKKKKKKLKKKKKKKKKKKKKKKLKKKKKKLKKLJPZ  sRKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKYk    ",
" . dRKKKKLKKKKKKPKKKKKKKKLKKKKKKKKKLKKKKPZ  sRKKKLKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKYk .  ",
"   dYKKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKPZ  sRHKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKYk    ",
" . dRJKLLKKLKKKKKKKKLKKLLKKLKKKKKKKKKKKKPZ  sRJKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKYk    ",
"   dRJKKKLKKKKKKPKKKKKKKKLKKKKKKKKKKKKKKPZ  sRKKKKKKKKKKKKKKJKKKKKKKKKKKKKKKKKKKKKYk    ",
"   dYKKHKKKKKHKKKKJKKKJKKKKKKHKKKJKKKKKKLZ  dRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLRl    ",
"   fRYYRYRYRRYRRYRRRRYRYYRYRRYRRRRYRYRYYRH  :FCZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZCFf    ",
"   =jffffgfffffffffffffffgffffffffffffgffs                                              ",
"   +&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%                                              ",
"   fRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRK  &fssdsssddsssdsdddsssssssssdddssssssds:     ",
"   sYHHKHKKHKHKJKHKJKJHKHKKHKJKJJKHKHKHHKC  fRYYRRRRRRRRRRRRYRRRRRRRRRRYYRRRRRRRRRH     ",
" . dYKKKKKKKKKKLKKKLKKKKKKKKKKKKKKKKKLKKPZ  sYHKH- =FPz#X@lKKKKHHKKKHJHKKHHKJJKJKLZ     ",
"   dRKKKKKLKKKKKKKKKKLKKKLKKKKKKKKKKKKKKPZ  sYHYd  %KFO.*..FPjlPPCfKKKKKKKKKKKLKKLZ     ",
" . dRKKKKKKLKKKKKKKKKKKKKKPKKKKKKLKKKKKKPZ  dRLzo=O#Kj ;R; >Y=XzF+#FLKKKKKKKKKKKKPZ     ",
"   dYKKKKKKKKKKLKKKKKKKKKKKKKKKPKKKKKKKKPZ  sRH#;Z.&Ps >Rd =YH&+#+ZYKKKKKLKKKLKKKPZ     ",
" . dRHLKKKKKKLKKKPKKKKKKKKKKKKKKKKKKKKKKPZ  sRf.::.+gs >Rd =PYZo kYKKKKKKKKLKKLKKPZ     ",
"   dRKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKPZ  dR:     @j -R; sYF&+%+ZPKKKKLKKKKKKKKPZ     ",
"   dRHKKKKLKKKLKKKKKPKKKKKKKKPKPLKKKKKKKPZ  sRFZFj.#FF+.&.XFL-XCH+#FLKKKKKKKKKKKKPZ     ",
" . dRKKKKKKKKKKKKPKKKKKKKPKKKKKKKKLKKKKKPZ  dYKLYC@=KLC%o%zLPjzPYZgLKKKKKLLKKKKKKPZ     ",
" . dYHKKKLLKKKKLKKKKKKKKKKKKKKKKLKKKKKKKPZ  sRHKKLYPKKLYYYKKKLLKKKPKKKKKKLKKLKKLKPZ     ",
"   dRKKKKKKKLLKKKKKKKKKKKKKKKKKKKKKKKKKKPZ  dRHKKKKKKKKKJKKKKJKJJKHJJKKKKKKLKKKKKPZ     ",
" . dYKKKKKKKKKKKKKKKKKKKKKKPKKKKKKLKKKKKPZ  dYKKKLKKLKKKKKKKITYIUUIUUIKKKKKKKKKLKPZ     ",
"   dRKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKLKKKPZ  dRHKKKLKKKKKKKKJi78888888eJLKKLLKKKKKPZ     ",
"   dRKLKLKKKKKKKKKKKKKKPKKKKKKKKKKLLLKKKPZ  sRHKLKKKKKKLKKLJq$<,,,,,$4JLKKKKLKKKKPZ     ",
" . dRJKKKKKLKKKKKKKKKKKKKKKKKKKLLKKKKKKJPZ  sRKKLKKLKKKKKKLJw,<1111118JLKKLKLKKKKPZ     ",
" . dRJKKKKKKKKKKKKKPKKKKKPKKLKKKKKKLKKKKPZ  sYJLKLKKKKLKKKKJq,<aAVBMmNKKKKKKKKKKKPZ     ",
"   dRJKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKLKKKPZ  sRKKKKKKKKKKKKLJw,,uchvVYPJKKKKLKKKLKPZ     ",
" . dRJKKKKKKKKKKKKKKKKPKKKKKKKKKLKKKKKKKPZ  sRJLKKKKKKKKKKLJq,<<,,,2wDLKKLKKKLKKKPZ     ",
"   dRKKKKPKPKKKKKKKPKKKKKKKKKKLKKKKKKKKKPZ  sRJLKKKLLKKKKKLJq,<<<<<<,9JLKKKKKKKKKPZ     ",
"   dRKKKKKKKPKPKKKKKKKKKKKKKKKKPKKLKKKKKPZ  sRHKKKKKKKKKKKLHe7amnr<<<<hPKKKKKKKKKPS     ",
" . dRHKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKLKLKPS  sRKKKKKKKLKKKKLKGKLKLIh,<<8LKKKKKKKKKYZ     ",
" . dRHKKKKKPKKKKKPKKKKKKKPKKKKKKKKKLKKKJPZ  sRHKKKKKKKKLKKKLKKKKKLS5,<4LKKKKKKPKKPZ     ",
"   dRKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKLKPZ  dYKKKKKKKKKKLKKLPKKKKLS6<,4LKKKKKKKKKPZ     ",
" . dRHKKKKKKLKKKKKKKKKKKKKKKKKPKKLKKKKKJPZ  dYKKKKLKLKKKKKKVnIPKLIb,<<8LKKKKKKKPKPZ     ",
"   dYKKKKKKKKKKLKKKKKKKKKKKKKKKKKLKLKKKKPZ  dRHKLLKKKKKLKKLm,0cBBa3<<,hLKKKKKKKKKPZ     ",
"   dYKKKKKKKKKKKKKKPKKKKKKPKKKKKKKLKKKKKPZ  sRHKKKKLKLKKKKPm$,<21<<,,9JKKKKKKKKKKPZ     ",
" . dRKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKPZ  sRKKKKKKKKKKKKPB53<,,,<2qGLKKPKKKKKKKPZ     ",
" . dRKKKKKKKKKKKKKPKKKKKPKKPKKKKKKKKKKKKPZ  dRKKLKKKKKKKKKKPKmateraMLLKKKLKKKKKKKPZ     ",
"   dYKKKKKKKKKLKKKKKKKPKKKKKKKKKKKKLKKKKPZ  sRHKKKKLPKKKKKLKLPYTUUUPKKKKKKKKKKKKKPZ     ",
" . dRHLKKKKKLKLKKKKKKKKKKKKKKPKKKLKKLLKKPZ  sYHKKLKKKKKKKKKKKKJJJJKKKKKKKLKLKKKKKPZ     ",
"   dRKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKPZ  dRKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKLKPZ     ",
"   dRHKKKKKKKKKLKKPKKKKKPKKKKKKKKKKKKKKKPZ  sYKKKKKKKKKKKKKKPKKPKKKKKLLKLKKKKKKKKPZ     ",
" . dRKKKKKLKKKKLKKKKPKKKKKKKKKKKLKKKKKKKPZ  sRHKKKKKKKKKKKKKKKKKKKKKKKKKLKKLLKKKKPZ     ",
" . dYHKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKPZ  sRKKLKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKKKPZ     ",
"   dRKKKKLKKKKLKKKKKKKKKKKKKKPKKKKKKKKKKPZ  sRHKKKKKKKKPKKKKKKKKKKKLKKKKKLKKKKLKKPZ     ",
" . dYKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPZ  sRHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLZ     ",
"   dRLPPPPPPPPPPYPPPPPPPPPPPPPPPPPPPPPPLYF  dRHKKKKHKKKKKKKHKKKKKKKHKKKKKKKHKKKKKLZ     ",
"   :JZZZZZZZZZZZZZSZZZZZZZZZZZZZZZZZZZZZFl  dRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRG     ",
"                                            -zkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklg     ",
"                                                                                        ",
"                                                  .    .  .    .  .    .  .    .        ",
"                                                                                        ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 74 1 ",
"  c #000000",
". c gray6",
"X c #121212",
"o c #1B1B1B",
"O c #242424",
"+ c #2C2C2C",
"@ c #333333",
"# c #3E3E3E",
"$ c #007E00",
"% c #444444",
"& c #4C4C4C",
"* c #535353",
"= c #5D5D5D",
"- c #626262",
"; c gray42",
": c #717271",
"> c #7B7B7B",
", c #008400",
"< c #028A02",
"1 c #0A8D0A",
"2 c #159215",
"3 c #1D941D",
"4 c #239423",
"5 c #259825",
"6 c #359F35",
"7 c #36A036",
"8 c #39A139",
"9 c #42A342",
"0 c #49A749",
"q c #4DA94D",
"w c #54AB54",
"e c #5CAE5C",
"r c #7F807F",
"t c #67B367",
"y c #6AB46A",
"u c #70B670",
"i c #74B974",
"p c #7CBB7C",
"a c #838383",
"s c #8A8A8A",
"d c #929292",
"f c #9C9C9C",
"g c #82BE82",
"h c #A4A4A4",
"j c gray67",
"k c #B4B4B4",
"l c gray73",
"z c #8EC38E",
"x c #94C594",
"c c #9AC79A",
"v c #9EC99E",
"b c #A4CCA4",
"n c #ABCEAB",
"m c #AED0AE",
"M c #B4D2B4",
"N c #BFD7BF",
"B c #C6C6C6",
"V c #CCCCCC",
"C c #C1D6C1",
"Z c #C5D9C5",
"A c #CFDDCF",
"S c #D4D5D4",
"D c #D6DFD6",
"F c #DCDCDC",
"G c #D7E0D7",
"H c #DCE2DC",
"J c #E5E5E5",
"K c #E9E7E9",
"L c #EBEBEB",
"P c #F3EBF3",
"I c #FCEFFC",
"U c #F3F3F3",
"Y c #FDF2FD",
"T c #FAFAFA",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"    O@@OOOOOOOOOOOOOOOO X+@@OOOOOOOOOOOOOOOO    ",
"   OLkfFLJJKLLJLKKLKLKUXrPfkLKKLJLLJKLKKKKJLO   ",
"   OK>&#UUUUJJJJJJJJJJLXaB;OdTskUJJJJJJJJJJLO   ",
"   OKTa;FssdHJJJJJJJJJLX>TL%ld--jLJJJJJJJJJKO   ",
"   OU-olSffhJJJLJJJJJJLX>JX=DF;dJJJJJJJJJJJLO   ",
"   OJ;->JUUUJJJJKJJKJJLXaV*-jTVFKJJJHJJJJJJLO   ",
"   OLUTUJJJJJJJJJJJJJJUX>TUULJLKPPPPLJKJJJJLO   ",
"   OKJJJJJJJJJJJJJJJJJLX>TFJJJJKcq6wnLJJJJJJO   ",
"   OJJJJJJJJLJJJJLJJJJLX>TJJJJJJ446$,mLJJJJLO   ",
"   OKJJJJJJJJJJLJJJLJJLX>TJJJJKJNJIi$pPJJJJLO   ",
"   OKJJJJJJJJLJJJJJJJJLX>THJJJJJLJPw,mLJJJJLO   ",
"   OKJJJLJJLJJLJJJJJJJLX>TJJJJJJJLe$iLJJJJJJO   ",
"   OLJJJJJJJJJJJJJLJJJL.>TJKJJJJJq<xILJJJJJLO   ",
"   OJJJJLJJJKJKJJJJJJJLX>TJJJJJK8,7gynKJJJJKO   ",
"   OKJJJJJJJJJJJJLJJJJLX>TJKJJJJ511<,tPJJJJKO   ",
"   OLJJJJJJLJJJJJJJLJJLX>TJJJJJJHHHHGJJJJJJLO   ",
"   OKJJJJJJJKJKJLJJJJJLX>THJJJJJKKJJKKJJJJJJO   ",
"   OJJJJLJJKJJJJJJJJJJUX>TJJJJJJJJJJJJJJJJJJO   ",
"   OJJJJJHJJJHJHJJHJJJLX>THJJJJJJJJJJJJJJJJLO   ",
"   OTUUUUUULUUUUULUUUUTX>TKLLLLLLULLLLLLLLLUO   ",
"   odsddddddddddddddsddX.XXXXX.XXXXXXXXXXXXo    ",
"   oVBBBVBBVBBVBBVBVBBVX#a>s>asa>>>>>>>>>>a*    ",
"   OULLLLLLLLLLLLLLLLLTXaTB*Kk*kTPTLTTTUTTTk    ",
"   OJJJJJJJJJJJJJJJJJJLX>L=+k@s@l:s>KJJJJFLh    ",
"   OLJJKJJJJLJJJJJJJJJL.sd@+;#S+Fa VLJJJJJUj    ",
"   OKJJJJJJLJJJJJJJJJJLX>FdOf-+-S:f>LJJJJHUh    ",
"   OLJJJJLJJLJJLJKJKJJUX>TUVKJkJKKTJLJJJJJUh    ",
"   OLJJJJJLJJJJJLJJJJJLX>UFKJJUJDNCZZHJJJFUh    ",
"   OKJJJJJJJJJJJJJJKJJLX>TJJJJHPw,,,$MPJJJUh    ",
"   OLJJJJJJJJJJJJJJJJJLXrTHJJJJPw1zzvDJJJJUh    ",
"   OJJJJJJJJLJJJJLJLJJLXrTJJJJJPw,23iJJJJJUh    ",
"   OLJJJLJJJLJLJJJJLJJLX>TJJJJJLpyg4$pPJJJPh    ",
"   OLJJJJJJLJJJJJJJJJJLX>UJJJKJJPPYm$9PJJJPh    ",
"   OKJJJJLJJJJJLLJJJJJUX>TFJJJJHbGPg$wPJJJUh    ",
"   OKJJJJJJJJJJJJJJJJJLX>TJJJJJJ313,1MLJJJUh    ",
"   OKJJJJJLJJJJJJJJJJJLX>TJJJJJKMueiZPJJJHUh    ",
"   OLJJJLJJJJJLJJLJJJJLX>UJJJJJJPPIPLJJJJJUj    ",
"   OKJJJJJJJJJJJJJJJJJLX>TJJJJJJJJHJJJJJJJUh    ",
"   OJJFJJJJJJHJJJJJFJJJX>UJJJJJJJJJJJJJJJJUh    ",
"   OUUUUULUUUUUUUUUUPLTX>THJJJJJJJJJJJJJJJPh    ",
"   ojhhhhhhhhhhhhhhjhhj.>TJLLKKKLJLJLKKKJJUh    ",
"                        X+OOOOOOOOOOOOOOOOOo    ",
"       .                                        ",
"                                                ",
"                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 245 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray2",
"O  c #252525",
"+  c #343434",
"@  c gray20",
"#  c gray14",
"$  c gray15",
"%  c #060606",
"&  c #131313",
"*  c gray18",
"=  c gray21",
"-  c #2C2C2C",
";  c #232323",
":  c #E9E9E9",
">  c #989898",
",  c #9A9A9A",
"<  c #E4E4E4",
"1  c #E7E7E7",
"2  c gray91",
"3  c #E6E6E6",
"4  c gray97",
"5  c #898989",
"6  c #DADADA",
"7  c gray51",
"8  c gray76",
"9  c #EFEFEF",
"0  c #E1E1E1",
"q  c #ECECEC",
"w  c gray92",
"e  c #272727",
"r  c gray86",
"t  c gray61",
"y  c #3A3A3A",
"u  c gray52",
"i  c #FBFBFB",
"p  c gray90",
"a  c gray89",
"s  c #F3F3F3",
"d  c #222222",
"f  c #888888",
"g  c gray79",
"h  c #777777",
"j  c #2D2D2D",
"k  c #B1B1B1",
"l  c #848484",
"z  c gray84",
"x  c #5D5D5D",
"c  c gray80",
"v  c #9B9B9B",
"b  c #6F6F6F",
"n  c gray46",
"m  c gray82",
"M  c #EAEAEA",
"N  c gray50",
"B  c white",
"V  c #8B8B8B",
"C  c #838383",
"Z  c #CECECE",
"A  c #656565",
"S  c #5A5A5A",
"D  c #9D9D9D",
"F  c gray13",
"G  c #353535",
"H  c #B9B9B9",
"J  c #DDDDDD",
"K  c gray81",
"L  c #E2E2E2",
"P  c #909090",
"I  c #A0A0A0",
"U  c gray58",
"Y  c #F1F2F1",
"T  c #E0E2E0",
"R  c #E2E4E2",
"E  c #E3E4E3",
"W  c #C6C6C6",
"Q  c #BBBBBB",
"!  c gray",
"~  c gray74",
"^  c #E8E6E8",
"/  c #F3EBF3",
"(  c #F7ECF7",
")  c #F2EAF2",
"_  c gray93",
"`  c #818181",
"'  c #FDFDFD",
"]  c #E6E5E6",
"[  c #D9E0D9",
"{  c #A6CCA6",
"}  c #8FC38F",
"|  c #AACEAA",
" . c #E9E7E9",
".. c #F8F8F8",
"X. c gray88",
"o. c #48A648",
"O. c #008800",
"+. c #108F10",
"@. c #008200",
"#. c #4AA84A",
"$. c #E7E6E7",
"%. c #F9F9F9",
"&. c #A5CCA5",
"*. c #C6D9C6",
"=. c #40A440",
"-. c #008300",
";. c #C2D6C2",
":. c #EDE9ED",
">. c #E4E5E4",
",. c #EEE9EE",
"<. c #F4EBF4",
"1. c #359D35",
"2. c #138F13",
"3. c #DBE2DB",
"4. c #E8E7E8",
"5. c #EAE7EA",
"6. c #47A547",
"7. c #028702",
"8. c #ADD0AD",
"9. c #F0E9F0",
"0. c #E3E5E3",
"q. c #3AA03A",
"w. c #119011",
"e. c #C4D9C4",
"r. c #FDEFFD",
"t. c #F2EBF2",
"y. c #4CA54C",
"u. c #007800",
"i. c #219621",
"p. c #3AA13A",
"a. c #2A9A2A",
"s. c #BCD5BC",
"d. c #ECE8EC",
"f. c #83BE83",
"g. c #56AC56",
"h. c #57AC57",
"j. c #4DA94D",
"k. c #4EA94E",
"l. c #C3D8C3",
"z. c #F8EDF8",
"x. c #FAEEFA",
"c. c #E1E4E1",
"v. c gray94",
"b. c #808080",
"n. c #F6F6F6",
"m. c gray96",
"M. c gray95",
"N. c #181818",
"B. c #A2A2A2",
"V. c #0E0E0E",
"C. c #282828",
"Z. c gray16",
"A. c #090909",
"S. c gray12",
"D. c gray78",
"F. c #C5C5C5",
"G. c #D2D2D2",
"H. c gray27",
"J. c gray55",
"K. c gray53",
"L. c #868686",
"P. c gray38",
"I. c gray99",
"U. c #797979",
"Y. c #585858",
"T. c gray87",
"R. c #F4F4F4",
"E. c #B7B7B7",
"W. c #3C3C3C",
"Q. c #646464",
"!. c DimGray",
"~. c #5B5B5B",
"^. c gray31",
"/. c #A9A9A9",
"(. c #DFDFDF",
"). c #EEEEEE",
"_. c #2F2F2F",
"`. c gray35",
"'. c gray43",
"]. c #4C4C4C",
"[. c gray70",
"{. c #C0C0C0",
"}. c #ACACAC",
"|. c gray73",
" X c gainsboro",
".X c gray39",
"XX c #AFB0AF",
"oX c #D4D5D4",
"OX c #EBECEB",
"+X c #E5E6E5",
"@X c #EAE9EA",
"#X c #F5F1F5",
"$X c #F2EDF2",
"%X c #F7F2F7",
"&X c #E0E1E0",
"*X c #EEE7EE",
"=X c #90C390",
"-X c #1C941C",
";X c #209620",
":X c #139013",
">X c #F5ECF5",
",X c #78B978",
"<X c #008600",
"1X c #69B469",
"2X c #68B468",
"3X c #84BF84",
"4X c #F4ECF4",
"5X c #79B879",
"6X c #289A28",
"7X c #37A037",
"8X c #EFE9EF",
"9X c #9AC79A",
"0X c #6DB56D",
"qX c #83BF83",
"wX c #189018",
"eX c #008500",
"rX c #BED6BE",
"tX c #F3ECF3",
"yX c #FCF0FC",
"uX c #FFF6FF",
"iX c #92C492",
"pX c #007E00",
"aX c #98C598",
"sX c #79BA79",
"dX c #97C697",
"fX c #C0D7C0",
"gX c #399F39",
"hX c #008100",
"jX c #B4D2B4",
"kX c #F0EAF0",
"lX c #5DAF5D",
"zX c #008900",
"xX c #038A03",
"cX c #078B07",
"vX c #76B976",
"bX c #EBE8EB",
"nX c #D2DED2",
"mX c #D6DFD6",
"MX c #F1F1F1",
"NX c #1B1B1B",
"BX c #AEAEAE",
"VX c gray67",
"CX c gray72",
"ZX c gray9",
"AX c #161616",
/* pixels */
"                                                                                        ",
"        . . . . . . . . . . . . . . . . .   . X . . . . . . . . . . . . . . . .         ",
"                                                                                        ",
"      o O + @ O # # # # # # # # # # # # $ % & * = - ; O $ ; # # # # # # # # # O o       ",
"  .   O : > , < : 1 1 2 2 2 2 2 2 2 2 3 4 ; 5 6 7 8 9 3 0 q 2 2 2 2 2 2 2 2 2 w O   .   ",
"  .   e r t y u i : q 3 p p p p p p p a s d f g h j a k l 1 < p p p p p p p p 2 #   .   ",
"  .   d 9 z x c v b n m M < p p p p p a s # N B V C Z A S D q < p p p p p p p 2 #   .   ",
"  .   $ < F G H J K m L 3 p 3 3 3 3 p a s F P I   h 2 8 U Y T R E p 3 p 3 p p 2 #   .   ",
"  .   O < W Q K q M w 3 p 3 3 3 3 3 p a s # l 3 ! ~ 0 : M ^ / ( ) 3 p 3 p p p 2 #   .   ",
"  .   # : _ 9 w < p p p 3 p 3 3 3 3 p a s # ` ' w 9 3 < ] [ { } | p  .p 3 p p 2 #   .   ",
"  .   # 2 < a p 3 p 3 3 3 3 3 3 3 3 p a s # ` ..X.< p R / o.O.+.@.#.$.p p p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 p p  .&.*.$.=.-.;.:.>.p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 3 p :.,.<.1.2.3.4.p p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 3 >.5.3 6.7.8.9.0.3 p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 >.4.[ q.w.e.r.p p 3 p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 p E t.y.u.i.p.a.s.,.>.p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 p >.d.f.g.h.j.k.l.d.>.p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 3 p t.z.z.x.x.5.p 3 p p 2 #   .   ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L p p p 3 E c.R R c.p 3 p p p 2 #   .   ",
"  .   # 3 L L a a a a a a a a a a a a 0 v.# b.n.X.a a a a a a a a a a a a a a 3 #   .   ",
"  .   $ m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.v.B $ 5 B 9 s s s s s s s s s s s s s s m.$   .   ",
"  .   N.D v v v v v v v v v v v v v v , B.F V.C.d # ; # ; ; ; # ; # # # # # ; Z.A.      ",
"  .   S.g D.D.D.D.D.D.D.D.D.D.D.D.D.D.F.G.# H.J.K.C K.u K.L.L.` f ` 7 ` ` b.f P.  .     ",
"  .   O v._ _ _ _ _ _ _ _ _ _ _ _ _ _ w I.# V B U.h a Y.h _ T.R.6 I...%.%.n.B Q   X     ",
"  .   # 1 < < p p p p p p p p p p p < L M.d 5 E.W.Q.!.7 ~.v 7 ^./.M X.L L (.)./.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s d V L._.* `.'.].[.l - {.q < p 3 a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # b.B |.L. X.Xu  XXXoXXXOX< p +Xa M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # 7 ..1 v.2 m.M.@X#X$X%Xd.3 p 3 a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.0 a p &X*X=X-X;X:Xp.E 3 p a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 R >X,X<X1X2X3X0.3 p a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 R 4X5X@.6X7X{ ,.>.3 a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 0.8X9X0XqXwXeXrX,.>.a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 3 >.tXyXuXiXpXaX>XR a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 p p 5.sXdXfXgXhXjXkX0.a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 p 0.kXlXzXxXcXvXbX>.p a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 3 p 3 d.nXl.mXkX3 p 3 a M.}.  X     ",
"  .   # 2 p p 3 3 3 3 3 3 3 3 3 3 3 p a s # ` %.L 3 +X3 p p bX,.5.0.p 3 p a M.}.  X     ",
"  .   # 3 L L a a a a a a a a a a a a 0 MX# ` ..0 p p p p p >.E >.p p p p L M.}.  X     ",
"  .   $ m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.v.B e ` ..0 p p p p p p p p p p p p L M.}.  X     ",
"  .   NXBX}.}.}.}.}.}.}.}.}.}.}.}.}.}.VXCXZXL.i p 2 2 2 2 2 2 2 2 2 2 2 2 3 m.BX  X     ",
"                                            AXe # # # # # # # # # # # # # # $ NX        ",
"        X X X X X X X X X X X X X X X X X                                               ",
"                                            . . . . . . . . . . . . . . . . . .         ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 233 2 ",
"   c black",
".  c #090909",
"X  c gray21",
"o  c #3C3C3C",
"O  c #393939",
"+  c gray18",
"@  c #2F2F2F",
"#  c #313131",
"$  c gray19",
"%  c gray20",
"&  c #0B0B0B",
"*  c gray15",
"=  c #353535",
"-  c #323232",
";  c #2A2A2A",
":  c #D8D8D8",
">  c gray46",
",  c gray72",
"<  c white",
"1  c gray98",
"2  c #F4F4F4",
"3  c gray93",
"4  c #EEEEEE",
"5  c #ECECEC",
"6  c #F9F9F9",
"7  c gray23",
"8  c gray71",
"9  c #989898",
"0  c #8E8E8E",
"q  c #F8F8F8",
"w  c gray83",
"e  c gray94",
"r  c #EFEFEF",
"t  c gray96",
"y  c gray82",
"u  c #020202",
"i  c #F1F1F1",
"p  c #7B7B7B",
"a  c gray51",
"s  c gray77",
"d  c #9B9B9B",
"f  c #C8C8C8",
"g  c #E9E9E9",
"h  c gray89",
"j  c #E4E4E4",
"k  c #E2E2E2",
"l  c #373737",
"z  c gray75",
"x  c gray35",
"c  c #C0C0C0",
"v  c #5F5F5F",
"b  c #A0A0A0",
"n  c gray91",
"m  c gray92",
"M  c gray76",
"N  c gray16",
"B  c gray69",
"V  c #C6C6C6",
"C  c gray67",
"Z  c gray81",
"A  c gray90",
"S  c gray22",
"D  c gray70",
"F  c #505050",
"G  c #717171",
"H  c gray87",
"J  c #8B8B8B",
"K  c #C3C4C3",
"L  c #E6E7E6",
"P  c #E2E4E2",
"I  c gray79",
"U  c #E1E1E1",
"Y  c gray",
"T  c #CECECE",
"R  c #EAEAEA",
"E  c #E6E6E6",
"W  c #AFAFAF",
"Q  c #D0D0D0",
"!  c #E7E7E7",
"~  c #EAEBEA",
"^  c #F4EEF4",
"/  c #F7ECF7",
"(  c #F4EBF4",
")  c #F3EBF3",
"_  c #E3E5E3",
"`  c #EEE8EE",
"'  c #AACDAA",
"]  c #3FA33F",
"[  c #359F35",
"{  c #87C087",
"}  c #E9E7E9",
"|  c #B2B2B2",
" . c #E3E4E3",
".. c #F1EAF1",
"X. c #95C595",
"o. c #7EBC7E",
"O. c #78B978",
"+. c #008200",
"@. c #B1D1B1",
"#. c #F0EAF0",
"$. c #E2E3E2",
"%. c #E4E5E4",
"&. c #EAE7EA",
"*. c #FFF6FF",
"=. c #ACCEAC",
"-. c #018701",
";. c #C4D8C4",
":. c #EDE8ED",
">. c #A5CCA5",
",. c #179317",
"<. c #AECFAE",
"1. c #F8EDF8",
"2. c #F2EAF2",
"3. c #9BC89B",
"4. c #007E00",
"5. c #4AA64A",
"6. c #8CC28C",
"7. c #C3D8C3",
"8. c #ECE8EC",
"9. c #92C492",
"0. c #41A441",
"q. c #4EA94E",
"w. c #B2D1B2",
"e. c #EFE9EF",
"r. c #EEE9EE",
"t. c #F6ECF6",
"y. c #F5EBF5",
"u. c #EBE8EB",
"i. c #E0E2E0",
"p. c gray97",
"a. c #3A3A3A",
"s. c #BBBBBB",
"d. c gray99",
"f. c LightGray",
"g. c #232323",
"h. c #ACACAC",
"j. c #A4A4A4",
"k. c #A5A5A5",
"l. c gray68",
"z. c gray14",
"x. c #3F3F3F",
"c. c gray25",
"v. c #444444",
"b. c #2D2D2D",
"n. c #DFDFDF",
"m. c gray84",
"M. c #D7D7D7",
"N. c #D5D5D5",
"B. c #343434",
"V. c #8D8D8D",
"C. c #AEAEAE",
"Z. c gray53",
"A. c gray66",
"S. c #767676",
"D. c #B9B9B9",
"F. c #6D6D6D",
"G. c gray1",
"H. c gray95",
"J. c #C1C1C1",
"K. c #898989",
"L. c #5D5D5D",
"P. c #9D9D9D",
"I. c #B1B1B1",
"U. c gray58",
"Y. c #040404",
"T. c gray24",
"R. c gray32",
"E. c gray38",
"W. c #8C8D8C",
"Q. c #707370",
"!. c #525452",
"~. c #E4E6E4",
"^. c gray88",
"/. c #AAAAAA",
"(. c #888888",
"). c #D8D5D8",
"_. c #E0D6E0",
"`. c #DFD5DF",
"'. c #EDE2ED",
"]. c #EAE9EA",
"[. c #F6F6F6",
"{. c gray55",
"}. c #FAF7FA",
"|. c #D0DFD0",
" X c #90C690",
".X c #89C489",
"XX c #88C188",
"oX c #DAE1DA",
"OX c #E8E7E8",
"+X c #E1E2E1",
"@X c #E1E3E1",
"#X c #F0E8F0",
"$X c #98C598",
"%X c #048604",
"&X c #41A341",
"*X c #4FA94F",
"=X c #D6DFD6",
"-X c #97C597",
";X c #088C08",
":X c #319E31",
">X c #6BB56B",
",X c #D2DED2",
"<X c #BDD6BD",
"1X c #A1CAA1",
"2X c #008300",
"3X c #93C493",
"4X c #F5ECF5",
"5X c #DFE0DF",
"6X c #BAD4BA",
"7X c #D1DDD1",
"8X c #C9DAC9",
"9X c #008500",
"0X c #8CC18C",
"qX c #DEE0DE",
"wX c #199419",
"eX c #159215",
"rX c #46A646",
"tX c #DDE2DD",
"yX c #E7E6E7",
"uX c #D9E1D9",
"iX c #EDE9ED",
"pX c #E7E5E7",
"aX c #E9E6E9",
"sX c #B7B7B7",
"dX c #EBECEB",
"fX c #FDFDFD",
"gX c #909090",
"hX c #1D1D1D",
"jX c gray57",
"kX c #939393",
"lX c gray13",
"zX c #9F9F9F",
"xX c #010101",
/* pixels */
"                                                                ",
"  . X o O + + @ # $ $ $ $ $ % & * o o @ = $ $ $ $ $ $ $ - ;     ",
"  O : > , < 1 2 3 4 4 4 4 5 6 7 8 9 0 q w e r 4 4 4 4 3 t y u   ",
"  $ i p a s d f g h j j j k r l 8 z x c v b n h j j j k m f u   ",
"  O M N B V C Z g j A A A h e S D F G H J K L P P A A j 5 I u   ",
"  % U Y T e i R A E E E A j e O W Q M ! ~ ^ / ( ) E A j 3 I u   ",
"  $ i 3 m h h A E A E E A j i S D 6 m _ ` ' ] [ { } A j 3 I u   ",
"  $ 4 k j E A E E E E E A j i S | e k  ...X.o.O.+.@.#.$.3 I u   ",
"  $ 4 j A E E E E E E E A j i S | i h E %.&.*.=.-.;.:.$.3 I u   ",
"  $ 4 j A E E E E E E E A j i S | i h E _ ( >.,.<.1.P j 3 I u   ",
"  $ 4 j A E E E E E E E A j i S | i h  .2.3.4.5.6.7.8.h 3 I u   ",
"  $ 4 j A E E E E E E E A j i S | i h  .2.9.0.q.[ w.e.$.3 I u   ",
"  $ 4 j A E E E E E E E A j i S | i h E %.r.t.y.1.u.%.j 5 I u   ",
"  $ 5 k h j j j j j j j j k r l B r k  .j $.i.i.i.h j k R f u   ",
"  - p.5 3 4 4 4 4 4 4 4 4 5 6 a.s.d.3 e 4 e i i i i i r q f.u   ",
"  g.h.j.k.k.k.k.k.k.k.k.k.j.l.; z.x.c.a.v.S X X S S S l O -     ",
"  b.n.m.M.M.M.M.M.M.M.M.M.N.k B.V.C.Z.A.S.W D.D.B | | W z F.  G.",
"  # H.n g g g g g g g g g ! 2 S J.K.v V.L.P.I.P.n 2 i 3 < U.  Y.",
"  $ 4 j A A A A A A A A A h r T.9 R.o L.E.W.Q.!.~.h h ^.2 J   G.",
"  $ 4 j A E E E E E E E A j i l 8 j /.I (.)._.`.'.].A k [.{.  G.",
"  $ 4 j A E E E E E E E A j i S | 2 3 ~ }.|. X.XXXoXOX+X[.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i U @X#X$X%X&X*X=X} U [.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i h P ( -X;X:X>XA E +X[.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i h A } ,X<X1X2X3X4X5X[.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i h A &.6X7X8X9X0Xt.qX[.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i h P ) { wXeXrXtXyX+X[.{.  G.",
"  $ 4 j A E E E E E E E A j i S | i h E A 8.uX,XiX} A k [.{.  G.",
"  $ R ^.k k k k k k k k k ^.3 l I.e k j j  .pXaX$. .j ^.2 J   G.",
"  B.< 2 [.[.[.[.[.[.[.[.[.2 < o sX6 R 3 3 5 5 dX5 3 3 g fXgX  Y.",
"  hXjXJ {.{.{.{.{.{.{.{.{.J kXlXzXf.f I I I I I I I I V : p   G.",
"                                u u u u u u u u u u u u u xX    ",
"    Y.G.G.G.G.G.G.G.G.G.G.G.Y.xX                                "
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 153 2 ",
"   c #040404",
".  c #202020",
"X  c gray15",
"o  c gray13",
"O  c #232323",
"+  c #151515",
"@  c gray10",
"#  c #272727",
"$  c gray16",
"%  c #222222",
"&  c #1D1D1D",
"*  c #010101",
"=  c #979797",
"-  c #A9A9A9",
";  c #D0D0D0",
":  c #DFDFDF",
">  c gainsboro",
",  c gray92",
"<  c #9A9A9A",
"1  c #868686",
"2  c #9D9D9D",
"3  c gray70",
"4  c #E1E0E1",
"5  c #DCDDDC",
"6  c gray90",
"7  c #C6C6C6",
"8  c #090909",
"9  c #282828",
"0  c gray65",
"q  c gray75",
"w  c #D8D8D8",
"e  c gray91",
"r  c #E4E4E4",
"t  c #F4F4F4",
"y  c gray62",
"u  c #8E8E8E",
"i  c gray73",
"p  c #CACBCA",
"a  c #DEE4DE",
"s  c #EEE9EE",
"d  c #EEEEEE",
"f  c #CECECE",
"g  c gray93",
"h  c #E2E2E2",
"j  c #F3F3F3",
"k  c gray58",
"l  c #BEBFBE",
"z  c #FBF8FB",
"x  c #D2E0D2",
"c  c #64B264",
"v  c #82BD82",
"b  c #F8F0F8",
"n  c #C9CAC9",
"m  c gray87",
"M  c #E6E6E6",
"N  c gray89",
"B  c #959595",
"V  c #EDEEED",
"C  c #EAE6EA",
"Z  c #83BE83",
"A  c #88BF88",
"S  c #F9F1F9",
"D  c #C9CBC9",
"F  c gray95",
"G  c #B7B8B7",
"H  c #F5F0F5",
"J  c #BBD2BB",
"K  c #309B30",
"L  c #A1C8A1",
"P  c #F0ECF0",
"I  c #C8C8C8",
"U  c #EAEAEA",
"Y  c #F9F9F9",
"T  c gray60",
"R  c gray99",
"E  c #EFF0EF",
"W  c #F1F1F1",
"Q  c #EAEFEA",
"!  c #FBFBFB",
"~  c gray4",
"^  c gray77",
"/  c gray80",
"(  c #CACACA",
")  c #D7D7D7",
"_  c #818181",
"`  c gray49",
"'  c gray66",
"]  c #9D9C9D",
"[  c #979697",
"{  c #848484",
"}  c #060606",
"|  c gray12",
" . c gray82",
".. c #DADADA",
"X. c #D5D5D5",
"o. c #939393",
"O. c gray43",
"+. c #656565",
"@. c #747574",
"#. c #909190",
"$. c gray57",
"%. c black",
"&. c #E9E9E9",
"*. c gray96",
"=. c #9F9F9F",
"-. c #909090",
";. c #898989",
":. c #A09EA0",
">. c #B8B0B8",
",. c #FDFDFD",
"<. c #E7E7E7",
"1. c #C0C1C0",
"2. c #FFFCFF",
"3. c #C9DCC9",
"4. c #4EAD4E",
"5. c #AFCEAF",
"6. c #F8F3F8",
"7. c #AFB0AF",
"8. c #B9B9B9",
"9. c #F3F0F3",
"0. c #CAD9CA",
"q. c #54AB54",
"w. c #6FB56F",
"e. c #FCF6FC",
"r. c #AFB1AF",
"t. c #DDDDDD",
"y. c gray88",
"u. c #B9BAB9",
"i. c #CEDACE",
"p. c #71B671",
"a. c #6DB36D",
"s. c #FBF4FB",
"d. c white",
"f. c #C0C0C0",
"g. c #F8F7F8",
"h. c #E5E8E5",
"j. c #CDE0CD",
"k. c #ECEBEC",
"l. c #F9F8F9",
"z. c #B7B7B7",
"x. c gray68",
"c. c #B1B1B1",
"v. c #B2B2B2",
"b. c gray69",
"n. c #BCBCBC",
"m. c #747474",
"M. c gray83",
"N. c #CBCBCB",
"B. c #D3CED3",
"V. c gray84",
"C. c gray3",
"Z. c #080908",
"A. c #070707",
/* pixels */
"  . X X o o O + @ # $ o o % & * ",
"$ = - ; : > , < 1 2 3 4 5 6 7 8 ",
"9 0 q w e r t y u i p a s d f 8 ",
". r g e 6 h j k l z x c v b n 8 ",
"o m M r M N j B i V C Z A S D 8 ",
"o m M r r h F k G H J K L P I 8 ",
"% r g U , e Y T 7 R E W Q ! w ~ ",
"& ^ / ( ( I ) _ ` ' ] y [ T { } ",
"|  ...) w X.N o.O.+.@.#.3 7 $.%.",
"% h , e &.M *.=.-.;.:.>.6 ,.i %.",
"o : <.r 6 h j k 1.2.3.4.5.6.7.%.",
"o : e 6 M N j B 8.9.0.q.w.e.r.%.",
"o t.6 N N y.W k u.9.i.p.a.s.7.%.",
"O U j W W d d.2 f.g.h.j.k.l.z.%.",
"@ x.3 c.v.b.n.m.' M.N.B.n V.y %.",
"%.%.%.%.%.%.%.%.C.~ 8 Z.8 ~ A.%."
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
