#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 141 2 ",
"   c #000000",
".  c #00000A",
"X  c #0B0B0B",
"o  c #060611",
"O  c #0A0A15",
"+  c #111111",
"@  c #1D1D1D",
"#  c #2F2F00",
"$  c #353502",
"%  c #3C3C03",
"&  c #2D2D14",
"*  c #21211E",
"=  c #3C3C14",
"-  c #38381D",
";  c #222222",
":  c #2F2F2F",
">  c #323226",
",  c #393923",
"<  c #343434",
"1  c #3C3C37",
"2  c #3B3B3B",
"3  c #454503",
"4  c #4C4C00",
"5  c #545402",
"6  c #595900",
"7  c #585813",
"8  c #636300",
"9  c #6C6C00",
"0  c #737301",
"q  c #797900",
"w  c #4F4F22",
"e  c #44442A",
"r  c #59592A",
"t  c #404032",
"y  c #565633",
"u  c #5D5D36",
"i  c #3F3F4F",
"p  c #3E3E50",
"a  c #454545",
"s  c #47474D",
"d  c #4A4A4A",
"f  c #52524E",
"g  c #4C4C54",
"h  c #515151",
"j  c #5B5B5B",
"k  c #656554",
"l  c #65656C",
"z  c #69696A",
"x  c #676776",
"c  c #6C6C7A",
"v  c #767676",
"b  c #7A7A74",
"n  c #7C7C79",
"m  c #848400",
"M  c #919100",
"N  c #9A9A00",
"B  c #A3A301",
"V  c #ABAB00",
"C  c #B5B501",
"Z  c #BDBD01",
"A  c #C4C401",
"S  c #CACA02",
"D  c #D2D200",
"F  c #DBDB03",
"G  c #E6E601",
"H  c #EFEF02",
"J  c #F5F503",
"K  c #FFFF00",
"L  c #F6F60C",
"P  c #F8F809",
"I  c #F2F212",
"U  c #FEFE11",
"Y  c #BBBB51",
"T  c #8A8A7A",
"R  c #ABAB6E",
"E  c #AFAF76",
"W  c #B1B174",
"Q  c #BABA71",
"!  c #CFCF4C",
"~  c #D4D445",
"^  c #D1D14B",
"/  c #CCCC50",
"(  c #C0C05C",
")  c #686880",
"_  c #7B7B85",
"`  c #7E7E88",
"'  c gray53",
"]  c #8C8C85",
"[  c #83838C",
"{  c #8E8E8E",
"}  c #94948B",
"|  c #9F9F8C",
" . c #868692",
".. c #8A8A92",
"X. c #87879F",
"o. c #8F8F98",
"O. c #959595",
"+. c #9C9C94",
"@. c #95959D",
"#. c #9C9C9C",
"$. c #A7A783",
"%. c #ABAB83",
"&. c #A3A38B",
"*. c #ADAD88",
"=. c #A4A494",
"-. c #ACAC90",
";. c #8686A0",
":. c #8F8FA7",
">. c #8E8EA8",
",. c #9595A0",
"<. c #9B9BA1",
"1. c #9696A8",
"2. c #9A9AA8",
"3. c #9B9BB0",
"4. c #A3A3A3",
"5. c #A3A3AC",
"6. c #AAAAAA",
"7. c #B2B2B2",
"8. c #B2B2BB",
"9. c #B9B9B9",
"0. c #B9B9C1",
"q. c #C6C6C6",
"w. c #CBCBC4",
"e. c #C3C3CC",
"r. c #CECEC9",
"t. c #D0D0C9",
"y. c #C5C5D2",
"u. c #C9C9D3",
"i. c #C3C3DB",
"p. c #D2D2D3",
"a. c #D5D5DA",
"s. c #DBDBDB",
"d. c #DEDEE2",
"f. c #E5E5E5",
"g. c #E8E8E7",
"h. c #E7E7ED",
"j. c #ECECEB",
"k. c #F1F1F1",
"l. c #F9F9F6",
"z. c #F6F6F8",
"x. c #FDFDFD",
/* pixels */
"f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.g.g.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.g.g.f.f.f.f.f.f.f.f.f.f.f.f.",
"f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.",
"g.g.f.g.j.j.j.j.g.j.j.j.j.j.j.j.j.j.j.j.g.j.j.j.j.j.j.j.j.j.j.j.g.j.j.j.j.j.g.j.j.j.j.j.g.j.j.j.j.j.j.j.j.j.j.j.g.j.j.j.j.j.g.j.j.j.j.j.g.j.j.j.j.j.j.j.j.j.j.j.g.j.j.j.j.j.h.g.j.j.j.j.g.f.g.f.",
"f.f.g.s.r.t.r.r.r.r.r.r.r.r.r.r.t.r.r.r.t.r.t.r.r.r.r.r.r.r.t.r.r.u.t.t.t.r.t.t.t.r.r.r.t.r.t.r.r.r.r.r.r.t.r.r.t.r.t.t.r.r.u.r.r.r.t.r.t.t.t.r.r.r.r.r.t.r.r.r.t.r.t.t.t.t.r.r.r.t.u.r.s.g.f.f.",
"g.f.j.r.' ;.;.;.;.;.X.;.;.;.;.;.X.;.;.;.;.;.;.;.;.;.X.;.;.;.;.;.} } ;.;.;.;.;.;.X.;.;.;.;.;.;.;.;.;.X.;.;.;.X.;.;.;.;.;.;.o.} X.;.;.;.X.;.;.;.;.;.;.X.X.;.;.X.;.;.;.;.;.;.;.;.;.;.;.o.] r.j.f.f.",
"f.f.j.u.E ~ / ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ^ ! ! ! ^ ! ! ^ ^ #.&.^ ! ! ! ! ! ! ! ! ! ! ! ! ^ ! ! ! ^ ! ! ! ^ ! ! ! ! ~ %.@.! ^ ! ! ! ! ! ! ^ ! ! ! ! ! ! ! ^ ! ! ! ! ! ! ! ! ! ~ Q o.u.g.f.f.",
"f.f.g.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ^ ;.t.j.f.f.",
"f.f.j.i.Y K P K P K K P K K P K K P K K P K P K K P K P K P K P ,.$.K P K K P K K P K K P K P K K P K P K P K P K P K P K W :.L K P K K P K P K K P K P K P K P P K K P K K P K P K / ;.t.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K K K K K K K K K K K K K K K K K K K K K K K K K ^ ;.r.j.f.f.",
"g.g.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.t.j.f.g.",
"f.f.j.y.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K P K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.t.g.f.f.",
"f.f.g.y.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.y.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.r.j.f.f.",
"g.g.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! X.t.j.f.f.",
"f.f.j.u.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K P K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.r.j.f.f.",
"f.f.g.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.y.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.t.j.f.g.",
"g.g.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! X.t.j.f.g.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K ,.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.t.g.f.f.",
"f.f.g.y.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K K K K K K K K K K K K K K K K K K K K K K K P K ^ ;.r.j.f.f.",
"f.f.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K P K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! X.r.j.f.f.",
"f.f.j.y.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K K K K K K K K K K K K K K K K K K K K K K K P K ! ;.t.j.f.f.",
"g.g.j.i.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.j.f.f.",
"f.f.j.u.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K P K ^ ;.r.j.f.f.",
"f.f.j.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K P K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.r.h.f.f.",
"f.f.g.i.Y K K K K K K K K K K K K K K K K K K K K K K K K K K K @.$.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K K K K K K K K K K K K K K K K K K K K K K K P K ^ ;.r.g.f.f.",
"f.f.j.y.Y K P K K K K K K K K K K K K K K K K K K K K K K K K K @.%.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.t.j.f.f.",
"f.f.j.i.Y K U U U U U U U U U U U U U U U U U U U U U U U U U U <.$.K L P L P P P P P P P P P P P P P P P P P P P P P L K E :.I P P P L P P P P P L P P P P P P P P P P P P P P L K / X.r.j.f.f.",
"g.f.j.w.n  .` ` ` ` ` [ ` ` ` ` ` ` ` [ ` ` ` ` ` ` ` [ ` ` ` ` T +.>.:.>.:.:.:.>.>.>.>.>.>.>.>.>.>.:.>.:.>.>.>.>.>.>.>.>.+.&.:.:.:.:.:.:.:.>.>.>.:.:.:.>.>.>.>.>.:.>.>.>.>.:.>.>.>.#.} r.j.f.f.",
"f.f.l.<..                                                       X =.W E W W W W W W W W W W W W W W W W W W W W W W W E W &.+.E E W E E W W W W W W W W W W W W W W W W W W W W E W $.o.r.j.f.f.",
"g.d.l.#.  X                                                     O *.K K K K K K K K K K K K K K K K K K K K K K K K K K K E :.L K K K K K K K K K K K K K K K K K K K K K K K K K K ^ ;.r.j.f.g.",
"f.d.l.#.  X                                                     o *.K P K P K K K P K K P K P K K P K P K K K P P K K P K W :.L K P K K K P K J K P P J J J L P J K P K K P K K P K ! ;.r.j.f.f.",
"f.f.l.#.                                                        o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K K K K K K K K K K K J K K K K K K K K ! ;.r.g.f.f.",
"f.f.l.#.  X                                                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K K K K K K K K H V 9 6 4 8 m S K K K K K K K P K ^ ;.r.j.f.f.",
"f.f.l.#.                                                        o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K K K K K J 0 % k ..1.3.1.v w 4 Z K K K K K K K ! ;.t.j.f.f.",
"f.f.l.#.  X                                                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K K K K K A % z u.k.x.x.x.x.l.d.5., 0 J K K K K K ! X.r.j.f.f.",
"f.s.l.#.                                                        o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K J K C & 5.x.x.x.x.x.x.x.x.x.x.j.h 5 K K K P K ! ;.r.j.f.f.",
"f.f.z.#.  X                   X z r.j.f.7.a                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K K K A = 7.x.x.x.x.x.x.x.x.x.x.x.x.x.h 0 K K K K ! ;.r.j.f.f.",
"f.f.z.#.                    + 6.x.l.x.x.x.x.v                   o *.K P K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K J 6  .x.l.x.x.x.x.x.x.x.x.x.x.x.x.z.> C K P K ! ;.r.j.f.f.",
"f.f.l.#.  X                 v x.x.s.v { z.x.k.2                 o *.K P K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K V g l.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.8.$ K K K ^ ;.t.j.f.f.",
"f.f.l.#.                  @ p.x.x.d     =.x.x.5.                o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K J 9 ..x.l.x.x.x.x.x.x.x.x.x.x.x.x.x.x.z.e A K K ^ ;.r.k.f.f.",
"f.d.z.#.  X               2 x.x.s.:     j l.x.p.                o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K D y p.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.{ 0 K K / ;.r.j.f.f.",
"f.f.l.#.                  d x.x.r.;     a x.x.s.@               o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K A s x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.8.4 K K / ;.r.j.f.f.",
"f.d.l.#.  X               h x.x.q.@     2 x.x.f.;               o *.K P K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K C p x.z.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.u.# K K ! ;.r.j.f.f.",
"f.f.z.#.                  d x.x.r.;     a l.x.s.@               o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K C s x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.y.$ K K ! ;.r.g.f.f.",
"f.f.l.#.  X               < x.x.s.<     l l.x.p.                o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K A s l.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.8.4 P K ! ;.r.j.f.f.",
"f.f.l.#.                  @ r.x.x.h     6.x.x.4.                o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K D r r.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.n m K K ! ;.r.j.f.g.",
"f.d.l.#.  X             .   z x.x.f.' <.l.x.j.<                 o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K 0 ` x.l.x.x.x.x.x.x.x.x.x.x.x.x.x.x.k., D P K / ;.r.j.f.f.",
"f.f.l.#.  .                 X #.x.l.x.x.x.z.z                   o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W >.P K K K C a g.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.<.3 K K K / ;.t.j.f.g.",
"f.d.l.#.  X                     j 9.s.p.4.2                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W >.P K K K K 9 c x.x.x.x.x.x.x.x.x.x.x.x.x.x.d.& D K K K ^ ;.r.j.f.f.",
"f.f.z.#.                                                        o *.K P K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K F 3 o.x.x.x.x.x.x.x.x.x.x.x.x.g.1 M K K P K ^ ;.t.g.f.f.",
"f.f.l.#.  X                                                     o *.K P K K K K K K K K K K K K K K K K K K K K K K K K K W >.L K K K K K A % _ k.x.x.x.x.l.x.x.x.x.e.1 q K K K P K ^ ;.r.j.f.f.",
"f.d.x.#.                                                        o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K F 5 h 2.a.x.x.x.x.k.0._ = N K K K K K K ! X.r.j.f.f.",
"f.f.l.#.                                                        o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.L K K K K K K J K B 6 u l c ) c k 7 9 F K J K K K P K ! ;.r.j.f.f.",
"f.d.l.#.  X                                                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K K K W :.P K K K K K K K K K P S N m q M V G K K K K K K K K K ! ;.t.j.f.f.",
"f.f.z.@.                                                        o *.K P K K K P K K P K K K K K K K K P K K K P K K K P K W >.L K P K K K K K P K K K K K K P K K P J K K K K K P K ! ;.r.g.f.f.",
"f.f.l.#.  X                                                     o *.K K K K K K K K K K K K K K K K K K K K K K K K K P K W :.P K K K K K K K K K K K K K K K K K K K K K K K K K K ! ;.t.g.f.f.",
"f.f.l.#.                                                        X =.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.| =.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.-.O.r.j.f.f.",
"f.f.j.r.' O.{ { { { { { { { { { { { { { { { { { { { { { { { { { O.#.,.,.,.,.,.@.,.,.,.,.,.,.,.,.,.,.,.@.,.,.,.,.,.,.,.,.@.4.; . o o o o o o o o o o o o o o o o o o o o o o o o o O   h s.j.f.f.",
"f.f.j.r.7.k.g.g.g.g.g.h.g.g.g.h.g.g.g.g.h.g.g.g.h.g.g.g.g.h.g.g.#.4.j.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.k.f.g.f.f.f.f.f.g.f.f.g.f.f.g.f.f.g.f.f.g.f.f.f.f.f.g.O.4.j.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.j.7.+                                                         h s.g.f.f.",
"f.f.g.q.7.k.d.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.O.4.h.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.9.+                                                     X   h s.g.f.f.",
"f.f.j.q.7.k.f.f.g.f.f.f.f.g.f.f.f.f.f.f.f.g.f.f.f.f.f.g.f.f.f.f.O.4.g.f.f.f.f.f.g.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.d.j.7.+                                                         h s.f.f.f.",
"f.f.k.q.7.k.f.f.g.f.f.g.g.f.g.f.g.f.f.h.f.f.g.f.g.f.f.f.f.f.f.f.O.4.j.f.g.f.g.f.f.f.f.g.f.f.f.g.g.f.f.g.f.f.f.g.f.f.f.f.g.9.+                                                         h s.g.f.f.",
"f.f.j.q.6.k.f.f.f.g.g.f.f.f.f.f.f.f.f.g.f.g.f.f.f.f.g.f.f.f.f.f.O.4.j.f.f.f.f.f.g.f.f.f.g.f.f.g.f.g.f.f.f.f.f.f.g.f.g.f.j.7.+                                                         h s.g.f.g.",
"f.f.j.q.7.j.d.f.f.f.f.g.f.f.g.f.g.f.g.f.f.f.f.f.f.f.f.g.f.f.f.f.O.4.h.f.f.f.g.f.f.g.f.g.f.f.g.f.f.g.f.g.f.f.f.g.g.f.g.f.j.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.k.f.f.g.f.g.f.f.g.f.f.f.f.f.f.f.g.f.g.f.h.f.f.g.f.f.f.O.4.j.f.f.g.f.f.f.f.f.f.g.f.f.g.g.f.f.g.f.g.f.f.f.g.f.f.j.7.+                                                     X   g s.g.f.f.",
"f.f.j.q.7.k.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.g.f.f.f.O.4.j.f.f.f.g.f.f.g.f.g.f.f.f.f.f.f.g.f.f.f.g.f.g.f.g.f.j.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.j.f.f.f.f.f.f.f.f.f.g.g.j.j.j.j.j.f.f.f.f.f.g.f.f.f.f.O.4.j.f.g.f.f.f.f.f.f.f.h.f.g.f.g.f.f.f.h.f.f.f.f.f.f.f.g.9.+                                                         h s.g.f.f.",
"f.f.j.q.7.k.f.f.f.g.f.g.f.z.@.  + X X X X + j.f.f.f.f.f.f.f.f.f.O.4.j.f.f.f.f.f.f.g.f.f.f.g.f.g.f.f.g.f.g.f.g.f.f.f.f.f.j.7.+                                                         h s.g.f.f.",
"f.f.k.q.7.j.d.f.f.f.g.f.f.l.O.  X         X g.f.g.f.g.f.f.f.f.f.O.4.j.f.f.g.f.g.f.f.g.f.f.f.f.f.f.g.f.f.f.f.f.f.f.g.g.d.g.7.+                                                     X   h s.g.f.f.",
"f.f.j.q.7.k.f.f.g.f.f.f.d.x.O.            X j.f.f.g.f.g.g.f.f.f.O.4.j.f.f.f.f.f.f.f.f.h.f.g.f.g.g.f.f.f.h.f.g.f.g.f.f.f.h.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.k.f.f.f.g.g.f.f.z.O.  X         X j.f.f.f.f.f.f.f.f.f.O.4.j.f.g.f.g.f.g.f.g.f.f.g.f.f.f.f.f.g.f.g.f.f.g.f.f.f.j.7.+                                                     .   h s.g.f.g.",
"f.f.j.q.7.k.d.f.f.g.f.f.f.l.O.  X         X j.f.f.g.g.f.f.f.f.f.O.4.h.f.f.f.f.g.f.f.f.f.f.f.f.g.g.f.g.f.f.f.f.f.f.g.f.f.j.9.O                                                         h a.g.f.f.",
"f.f.j.q.7.k.f.f.g.f.f.g.s.z.O.  X   X   . O j.f.f.f.f.f.h.f.f.f.O.4.g.f.f.h.f.f.g.f.g.f.f.h.f.f.f.f.f.f.f.g.f.g.f.f.f.f.j.7.+                                                     X   h s.g.f.f.",
"f.f.j.q.7.k.f.f.g.f.f.f.f.z.O.            X j.f.f.f.f.g.f.f.f.f.O.4.j.f.f.g.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.h.f.f.f.f.g.9.+                                                         h s.g.f.f.",
"f.f.k.q.7.j.f.f.f.f.g.f.f.j.r.' @.+.O.O.O.@.g.f.f.f.f.g.g.f.f.f.O.4.j.g.g.f.f.f.f.g.f.g.g.f.g.f.g.f.g.g.f.g.f.f.f.f.f.f.j.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.j.f.f.f.f.f.f.f.f.j.x.z.l.l.l.z.z.f.f.f.f.f.f.f.f.f.f.O.4.h.f.f.f.f.f.g.f.f.f.g.f.g.f.f.f.f.f.g.f.g.f.g.f.g.f.j.7.+                                                     X   h s.g.f.f.",
"f.f.j.q.7.k.f.f.f.g.f.f.f.f.f.d.f.d.f.f.f.d.f.f.g.f.g.f.g.f.f.f.O.4.g.f.f.g.f.g.f.f.f.g.f.f.f.f.h.f.f.g.f.f.f.f.g.f.g.f.j.7.+                                                         h s.f.f.f.",
"f.f.j.q.7.j.f.f.f.f.f.f.g.f.g.g.f.f.g.f.f.g.f.g.f.f.f.f.f.f.f.f.O.4.j.f.f.f.g.f.f.h.f.f.g.f.g.f.f.f.f.f.g.f.f.f.f.g.f.f.j.7.+                                                         h s.g.f.f.",
"f.f.j.q.7.k.d.f.f.g.f.g.f.f.f.f.f.f.f.g.g.f.f.f.f.g.f.g.g.f.f.f.O.4.j.f.g.g.f.f.f.f.f.g.f.f.f.f.f.g.f.g.f.f.f.g.f.f.f.f.g.9.+                                                         h s.g.f.g.",
"f.f.j.q.7.k.f.f.h.f.f.f.f.g.f.f.f.g.f.f.f.g.f.g.g.f.g.f.f.f.f.f.O.4.g.f.f.g.f.g.g.f.g.f.g.g.f.h.f.g.f.g.g.f.g.f.f.f.f.f.j.7.+                                                         h s.g.f.f.",
"g.f.j.q.7.k.d.g.f.f.f.g.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.g.f.f.f.O.4.j.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.7.+                                                     X   g s.g.f.f.",
"f.f.j.q.7.k.d.f.g.g.f.f.f.g.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.O.4.j.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.g.g.f.f.g.f.f.f.f.f.g.7.+                                                         h s.g.f.f.",
"f.f.k.q.7.j.f.f.d.f.f.d.f.f.f.f.f.f.f.f.f.d.f.f.d.f.f.f.f.d.f.f.O.4.j.f.f.f.d.f.f.f.f.f.d.f.f.f.d.f.d.f.f.d.f.f.f.d.f.d.g.7.+                                                         h s.f.f.f.",
"f.f.j.q.7.x.g.k.j.k.k.k.j.k.k.j.j.k.j.k.j.k.k.k.k.k.k.j.k.k.j.k.O.4.z.j.j.k.j.k.j.k.j.k.j.k.k.k.k.k.k.j.j.k.j.k.k.k.k.j.z.9.@     X   X X     X   X . X   X   X   X   X   X X   X X   j s.g.f.f.",
"f.f.j.q.O.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.6.7.7.O.O.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.4.+                                                         d s.g.f.f.",
"f.f.g.d.r.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.u.r.q.r.q.q.q.q.q.r.q.q.q.q.q.q.q.e.q.q.q.q.q.q.q.q.r.q.q.p.4.@.#.#.#.@.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.@.#.#.#.#.#.@.7.f.f.f.f.",
"f.f.f.g.j.j.j.k.j.j.j.j.k.j.j.j.j.j.j.j.j.j.j.j.k.j.j.j.j.j.k.j.g.h.j.j.j.j.j.j.g.j.j.j.j.g.k.j.j.j.j.j.j.j.j.k.j.g.j.j.j.j.l.z.l.l.l.z.l.l.l.z.z.l.l.l.l.l.z.l.l.z.l.l.z.z.l.l.l.l.l.j.f.f.f.f.",
"g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.d.f.f.f.f.d.f.f.f.f.d.f.d.f.f.f.d.f.d.f.f.f.f.d.f.f.f.f.f.f.f.f.f.",
"f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.f.f.f.f.f."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 150 2 ",
"   c #000000",
".  c #0A0A0A",
"X  c #0D0D13",
"o  c #09091A",
"O  c gray7",
"+  c #1E1E1E",
"@  c #3E3E11",
"#  c #3E3E1C",
"$  c #171727",
"%  c #1F1F36",
"&  c #242424",
"*  c #2C2C2C",
"=  c #353521",
"-  c #393926",
";  c #20203A",
":  c #333333",
">  c #3C3C3C",
",  c #444400",
"<  c #404009",
"1  c #48480C",
"2  c #545400",
"3  c #5A5A00",
"4  c #49491C",
"5  c #545410",
"6  c #5A5A11",
"7  c #57571D",
"8  c #696900",
"9  c #727200",
"0  c #7B7B00",
"q  c #7A7A08",
"w  c #676716",
"e  c #6A6A10",
"r  c #454523",
"t  c #4A4A21",
"y  c #5F5F24",
"u  c #404034",
"i  c #47473B",
"p  c #4F4F3F",
"a  c #50503A",
"s  c #454545",
"d  c #4A4A44",
"f  c #414148",
"g  c #4B4B4B",
"h  c #5C5C4A",
"j  c #515155",
"k  c #5B5B5B",
"l  c #616155",
"z  c #5E5E61",
"x  c #636364",
"c  c #6A6A60",
"v  c #65656B",
"b  c #6D6D6D",
"n  c #7A7A6B",
"m  c #6C6C76",
"M  c #6C6C78",
"N  c #747474",
"B  c #787876",
"V  c #797979",
"C  c #848400",
"Z  c #888800",
"A  c #939300",
"S  c #9D9D00",
"D  c #A7A700",
"F  c #AAAA00",
"G  c #B5B500",
"H  c #BCBC00",
"J  c #C5C500",
"K  c #CDCD00",
"L  c #D2D200",
"P  c #DADA00",
"I  c #E3E301",
"U  c #EBEB00",
"Y  c #EBEB0F",
"T  c #F4F401",
"R  c #FFFF00",
"E  c #F6F60C",
"W  c #EBEB11",
"Q  c #F4F410",
"!  c #FFFF16",
"~  c #FDFD1A",
"^  c #DCDC34",
"/  c #D6D63C",
"(  c #E6E624",
")  c #ECEC27",
"_  c #E0E02E",
"`  c #BDBD62",
"'  c #B7B768",
"]  c #B8B869",
"[  c #AFAF75",
"{  c #A7A77B",
"}  c #A8A87C",
"|  c #B1B173",
" . c #B9B976",
".. c #CACA4E",
"X. c #C7C754",
"o. c #CACA50",
"O. c #D7D75E",
"+. c #D4D462",
"@. c #CBCB72",
"#. c #747484",
"$. c #76768B",
"%. c #7F7F89",
"&. c #868686",
"*. c #81818D",
"=. c #919187",
"-. c #97978E",
";. c #98988C",
":. c #949494",
">. c #9B9B93",
",. c #95959B",
"<. c #9A9A9B",
"1. c #A2A286",
"2. c #ADAD87",
"3. c #ADAD88",
"4. c #AEAE92",
"5. c #A0A09E",
"6. c #8C8CA4",
"7. c #8B8BAC",
"8. c #9191A3",
"9. c #9E9EA5",
"0. c #9F9FAA",
"q. c #8585B6",
"w. c #A5A5A5",
"e. c #A1A1AD",
"r. c #ABABAB",
"t. c #B0B0A6",
"y. c #AFAFB2",
"u. c #AAAAB8",
"i. c #B2B2B2",
"p. c #B4B4BD",
"a. c gray73",
"s. c #B7B7C0",
"d. c #B9B9C7",
"f. c #BDBDCB",
"g. c #C3C3C3",
"h. c #C1C1C8",
"j. c #CBCBCC",
"k. c #CBCBD3",
"l. c #C8C8D8",
"z. c #D5D5D5",
"x. c #D1D1D9",
"c. c #DADAD9",
"v. c #E0E0DA",
"b. c #DADAE0",
"n. c #E5E5E5",
"m. c #E7E7EB",
"M. c #EBEBEB",
"N. c #F2F2F2",
"B. c #F7F7FA",
"V. c #FEFEFE",
/* pixels */
"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.m.n.m.n.n.n.n.n.n.n.n.n.n.n.n.m.n.n.n.n.n.n.n.n.m.n.m.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.m.n.m.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.",
"n.n.n.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.n.n.n.n.",
"n.n.M.g.y.i.i.y.y.y.y.y.p.y.i.y.y.y.i.y.y.y.i.i.y.y.y.y.y.i.i.y.y.y.i.i.i.y.y.y.y.y.i.y.y.y.i.i.y.y.y.y.y.y.i.y.i.y.i.y.p.y.y.y.y.y.i.y.y.y.i.i.y.y.y.y.y.y.y.y.y.i.y.a.M.n.n.n.",
"n.n.M.t.=.;.:.;.-.:.-.-.-.:.-.-.-.-.:.-.;.:.-.-.>.-.:.-.-.;.;.;.-.:.-.-.:.:.;.>.-.-.:.-.;.:.-.-.>.-.:.-.-.-.;.;.;.-.-.:.-.:.-.-.-.-.:.-.;.:.-.-.>.-.:.-.-.-.:.-.-.-.;.<.M.n.n.n.",
"n.n.M.u.W R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.W R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R 1.0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.y.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.m.m.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R E R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.n.n.n.n.",
"n.n.N.y.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.y.W R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { w.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { e.n.n.M.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.n.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.n.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R E R { 0.M.n.M.n.",
"n.n.M.y.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.n.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.m.n.n.",
"n.n.N.y.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.W R R R R R R R R R R R R R R R R R R R R R R R R <.| R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.n.M.u.Y R R R R R R R R R R R R R R R R R R R R R R R R ,.| R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.n.n.n.n.",
"n.n.M.p.) ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ! 5.[ R Q E E E E E E E E E E E E E E E E E E E E E R / q.^ R E E E E E E E E E E E E E E E E E E E E E W R { w.M.n.n.n.",
"n.n.N.-.v M m m m m m m m m m m m m m m m m m m m m m m m n >.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.8.1.6.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.;.w.M.n.n.n.",
"n.c.V.s                                                   X 3...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X...] ,.` ..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.;.w.M.n.n.n.",
"n.c.B.d           .               .                       o  .R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.m.n.n.n.",
"n.n.V.s   .                                               o  .R E R E R R R R R R R R R E R R R R R R E R R R / q.( R R R E R R R R E R R R ! R R R E R R T R R E R { 0.M.n.n.n.",
"n.n.V.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R R R R T P L L P U R R R R R R R R R { 0.M.n.n.n.",
"n.b.V.s   .                                               o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R T R I A w g s f d y C K R R R R R R R { 0.M.n.n.n.",
"n.v.V.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R T R R R R F 4 m p.B.V.V.B.k.%.i C T R R R R R { 0.M.n.n.n.",
"n.n.B.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R C i k.V.V.V.B.V.V.V.V.n.x 3 U R R R R { 0.M.n.n.n.",
"n.c.V.s                     & :.j.j.w.>                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R S i n.V.V.B.V.V.V.V.V.B.V.V.N 8 R R R R { 0.M.n.n.n.",
"n.n.V.s                   > M.V.V.V.V.V.b                 o  .R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R P # b.V.V.V.V.V.V.V.V.V.V.V.V.V.g D R R R { 0.M.n.n.n.",
"M.b.B.s                 . j.V.M.B x c.V.n.:               o  .R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R E R 8 8.V.V.V.V.V.V.V.V.V.V.V.V.V.V.x.@ R R R { 0.n.n.n.n.",
"n.n.V.s                 k B.V.w.    N V.V.&.              o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R I 7 x.V.V.V.V.V.V.V.V.V.V.V.V.V.V.B.h G R R { 0.M.n.n.n.",
"n.n.B.s                 &.V.V.N     > N.V.r.              o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R F b V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.0.9 R R { 0.M.n.n.n.",
"n.v.V.s             .   :.V.B.x     : M.V.a..             o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R A #.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.f.2 R R { 0.M.n.n.M.",
"n.c.V.s   .             :.V.B.x     : M.V.a..             o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R Z $.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.l., E R { 0.M.n.n.n.",
"M.n.V.s             .   &.V.V.N     s N.V.r.              o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R ! A #.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.d.3 R R { e.M.n.n.n.",
"n.b.B.s                 k B.V.w.    V V.V.&.              o  .R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R G l B.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.,.0 R R { 0.M.n.n.n.",
"n.n.V.d                 . j.V.M.N x c.V.n.:               o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R U 5 k.V.V.V.V.V.V.V.V.V.V.V.V.V.V.B.p J R R { 0.n.n.n.n.",
"n.n.B.s   .               > M.V.V.V.V.B.c                 o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R T R 0 %.V.V.V.V.V.V.V.V.V.V.V.V.V.V.s.1 R R R { 0.M.n.n.n.",
"n.v.V.s                     & :.j.z.w.>                   o  .R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R U < h.V.B.V.V.V.V.V.V.V.V.B.V.N.u J R R R { 0.M.n.n.n.",
"n.c.V.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R H - k.V.V.B.V.V.V.V.B.B.V.N.j C R R R R { 0.M.n.n.n.",
"n.n.B.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R F # e.V.V.V.V.V.V.V.V.j.d 0 T R R R R { e.n.n.M.n.",
"n.n.V.s                                                   o  .R E R R R R R R R R R R R R R R R R R R R R R R ^ q.( R R R R R R K 6 g <.b.B.B.M.i.z t F R R R R R R { 0.n.n.n.n.",
"n.v.V.s                                                   o  .R R R R R R R R R R R R R R R R R R R R R R R R / q.( R R R R R R R T H q t = = r e D U R E R R R R R { 0.M.n.n.n.",
"n.b.V.s                                                   o  .R E R R R R R E R R R R R R R R R R R R R E R R / q.( R E R R T R R E R R R T T T R R R E R R E R E R 1.0.M.n.n.n.",
"n.n.V.s   .           .           .                       o  .R R R R R R R R R R R R R R R R R R R R R R R R ^ $.( R R R R R R R R R R R R R R R R R R R R R R R R { 0.M.n.n.n.",
"n.c.V.s                                                   X 2...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X...' e.@.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.O.4.w.M.n.n.n.",
"n.n.N.:.b b b b N b b b b b b b b b b b b b b b b b b b b B <.6.6.7.6.6.6.6.6.7.6.6.6.6.7.6.6.6.7.6.6.8.6.6.6.e.z % % % ; % % % % % % % % ; % ; % % % ; % % % % % % & 5.M.n.n.n.",
"n.n.M.p.c.M.n.M.n.n.M.n.M.n.M.n.n.M.M.n.n.M.n.M.M.n.n.n.M.w.r.v.c.v.v.v.v.c.v.v.v.v.v.v.v.v.v.v.v.v.v.v.c.c.c.z.>                                                     5.M.n.n.n.",
"n.n.M.w.z.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.:.r.N.n.n.M.n.n.M.n.M.M.n.n.M.n.M.n.M.M.n.n.n.M.n.M.c.>   .                                                 <.M.n.M.n.",
"n.n.M.r.z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.c.s                                                     <.M.n.n.n.",
"n.n.N.r.z.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.c.>                                                     5.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.M.n.n.M.n.n.n.n.<.r.M.n.n.n.M.n.n.n.n.n.M.n.n.n.n.n.n.M.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.N.r.z.M.n.n.M.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.M.n.n.n.n.n.M.n.n.n.n.n.n.n.n.M.c.>                                                     9.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.M.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.N.r.z.M.n.n.n.n.n.n.n.n.n.n.b.n.n.v.n.n.n.M.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.m.c.>                                                     5.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.n.N.B.B.B.B.B.B.n.n.n.n.n.M.n.n.n.<.r.M.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.M.M.n.n.n.n.n.M.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.B.l * : : : * i M.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.c.s                                                     w.M.n.n.n.",
"n.n.N.r.z.M.n.n.n.n.n.b.B.>           O M.n.n.n.n.n.n.M.M.,.r.M.n.n.n.n.M.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.c.>                                                     w.M.n.n.n.",
"M.n.M.r.z.M.n.n.n.n.n.n.V.s           O M.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.M.n.v.B.>           O M.n.n.n.n.n.n.n.n.:.r.M.n.n.n.n.n.n.n.n.M.n.n.n.n.M.n.n.n.M.n.n.n.n.n.c.>                                                     5.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.v.V.>           O M.n.n.n.n.n.n.n.n.<.r.N.n.M.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.V.>           O M.n.n.n.n.n.n.n.M.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.n.n.n.n.n.n.b.B.g . + O + O * M.n.n.n.n.M.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.M.n.n.n.n.c.>                                                     w.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.M.n.n.n.M.M.N.N.M.M.M.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.M.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.c.s                                                     <.M.n.n.n.",
"n.n.M.y.z.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.m.n.M.c.>                                                     9.M.n.n.n.",
"n.n.N.r.z.M.n.n.n.n.n.M.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.:.r.M.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.m.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.M.<.r.M.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.M.n.M.n.n.n.c.>                                                     5.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.:.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.N.r.z.M.n.n.n.M.n.n.n.n.n.n.M.n.n.n.n.n.n.n.M.n.n.n.M.<.r.N.n.M.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.c.>                                                     w.M.n.M.n.",
"n.n.M.r.z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.<.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.c.>                                                     <.M.n.n.n.",
"n.n.M.r.z.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.,.r.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.z.>   .                                                 5.M.n.n.n.",
"n.n.M.r.z.n.n.n.c.n.n.n.n.n.n.c.n.c.n.n.n.b.n.n.n.n.v.n.n.:.r.M.c.n.b.n.n.n.v.n.n.n.n.b.n.n.c.n.n.c.n.n.n.v.n.z.>                                                     <.M.n.M.n.",
"n.n.M.a.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.r.w.w.w.w.w.w.w.w.w.w.w.w.r.w.w.w.w.w.w.w.5.p.k O & & + + + $ + + + & + + + $ + + + & + + + & + + + r.M.n.n.n.",
"n.n.n.M.M.n.M.n.M.n.M.M.M.M.n.M.M.M.M.n.M.M.M.n.M.n.M.M.n.M.M.n.M.M.n.M.M.M.n.M.n.M.M.M.n.M.M.M.M.M.M.n.M.n.M.n.M.N.N.N.N.N.N.M.N.N.N.N.N.N.M.N.N.N.N.N.M.N.N.M.N.N.N.n.n.n.n.n.",
"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.",
"n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.M.n.",
"n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.M.M.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 116 2 ",
"   c #010101",
".  c #0C0C0C",
"X  c #040417",
"o  c #07071A",
"O  c gray8",
"+  c #1D1D1D",
"@  c #20201F",
"#  c #242424",
"$  c gray16",
"%  c #33332A",
"&  c #323232",
"*  c #3D3D33",
"=  c #3D3D3D",
"-  c #43433E",
";  c #6D6D37",
":  c #74743E",
">  c #424245",
",  c #5F5F5F",
"<  c #767641",
"1  c #7B7B42",
"2  c #74745E",
"3  c #606060",
"4  c gray46",
"5  c #9E9E11",
"6  c #A5A50D",
"7  c #B5B506",
"8  c #BABA02",
"9  c #B2B209",
"0  c #A2A214",
"q  c #9D9D27",
"w  c #9A9A28",
"e  c #999930",
"r  c #C3C300",
"t  c #CDCD00",
"y  c #D7D700",
"u  c #E3E300",
"i  c #EBEB00",
"p  c #F5F502",
"a  c #FEFE01",
"s  c #F7F70B",
"d  c #FBFB09",
"f  c #EAEA13",
"g  c #F1F113",
"h  c #FFFF16",
"j  c #FEFE19",
"k  c #D2D233",
"l  c #D8D839",
"z  c #E1E12B",
"x  c #EDED29",
"c  c #8A8A4D",
"v  c #929245",
"b  c #8A8A57",
"n  c #969651",
"m  c #999952",
"M  c #9A9A5E",
"N  c #BDBD4F",
"B  c #B6B655",
"V  c #8A8A65",
"C  c #AEAE6D",
"Z  c #B5B562",
"A  c #BABA65",
"S  c #B6B66D",
"D  c #BBBB68",
"F  c #ADAD71",
"G  c #A6A67A",
"H  c #ACAC7B",
"J  c #B2B272",
"K  c #B1B17B",
"L  c #CFCF47",
"P  c #C5C54B",
"I  c #C9C94F",
"U  c #D0D045",
"Y  c #C2C250",
"T  c #CACA50",
"R  c #CFCF5E",
"E  c #C0C06B",
"W  c #838383",
"Q  c #8D8D87",
"!  c #8E8E8E",
"~  c #9E9E85",
"^  c #9D9D9C",
"/  c #A5A584",
"(  c #AEAE85",
")  c #ACAC97",
"_  c #A6A69A",
"`  c #ADAD99",
"'  c #B1B19D",
"]  c #A6A6A6",
"[  c #A5A5A9",
"{  c gray66",
"}  c #ACACB4",
"|  c #B5B5B5",
" . c #BDBDBD",
".. c #BDBDC4",
"X. c #C5C5C5",
"o. c #C3C3CF",
"O. c #CDCDCD",
"+. c #C7C7D4",
"@. c #CFCFD3",
"#. c #C8C8DC",
"$. c #D5D5D5",
"%. c #D2D2DC",
"&. c #DBDBDB",
"*. c #E0E0DF",
"=. c #D2D2E6",
"-. c #DADAE7",
";. c #DCDCE9",
":. c #E5E5E5",
">. c #EBEBE7",
",. c #E4E4EA",
"<. c #EAEAEA",
"1. c #E2E2F3",
"2. c #E9E9FA",
"3. c #F2F2F2",
"4. c #F3F3FF",
"5. c #FDFDFD",
/* pixels */
":.:.:.:.:.:.:.:.:.:.:.:.:.:.:.>.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.<.:.:.:.:.:.<.:.<.:.:.",
":.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.",
":.:.:.:.3.>.>.>.>.>.>.>.<.>.>.>.<.:.3.>.>.>.>.<.3.>.>.>.>.:.>.>.>.>.<.<.>.>.>.>.>.>.>.<.:.:.<.:.",
":.:.:.:.#.#.#.#.#.#.#.#.#.#.#.#.%.@.#.#.#.#.#.#.#.#.#.#.#.@.%.#.#.#.#.#.#.#.#.#.#.#.#.$.:.:.:.:.",
":.:.:.@.B P Y Y Y Y Y Y Y Y Y P F C P N Y Y Y Y Y Y Y N T Z G P N Y Y Y Y Y Y Y Y T N _ :.:.:.:.",
":.:.<.@.f a a a a a a a a a a a T L a a a a a a a a a a a z D a a a a a a a a a a a p ` ,.:.:.:.",
":.:.<.@.f a a a a a a a a a d a T L a a a a a a a a a a a z D a a a a a a a a a a a s ) ,.:.:.:.",
":.:.<.@.f a a a a a a a a a a a I U a a a a a a a a a a a z D a a a a a a a a a a a p ) ,.:.:.:.",
":.:.>.$.f a a a a a a a a a a a I U a a a a a a a a a a a z D a a a a a a a a a a a a ` <.:.:.:.",
":.:.:.@.f a a a a a a a a a a a I L a a a a a a a a a a a z D a a a a a a a a a a a p ` 1.:.:.:.",
":.:.<.$.f a a a a a a a a a a a T U a a a a a a a a a a a z A a a a a a a a a a a a p ` :.:.:.:.",
":.:.:.@.f a a a a a a a a a a a I U a a a a a a a a a a a z A a a a a a a a a a a a a ` <.:.:.:.",
":.:.<.@.f a a a a a a a a a a a I U a a a a a a a a a a a z A a a a a a a a a a a a p ` ,.:.:.:.",
":.:.:.@.f a a a a a a a a a a a I U a a a a a a a a a a a z A a a a a a a a a a a a a ` ,.:.:.:.",
":.:.<.$.f a a a a a a a a a a a T L a a a a a a a a a a a z A a a a a a a a a a a a p ` ,.:.:.:.",
":.:.<.$.f a a a a a a a a a a a P L a a a a a a a a a a a z A a a a a a a a a a a a a ` ,.:.:.:.",
":.:.:.$.x d j j h h h h j j j d E T d g g g g g g g g f d l S d f g g g g g g g g g f ` ,.:.:.:.",
":.:.3.| % - * * * * * - * * * * - F S J J J J J J J J J J H / S J J J J K J J J J J F ` <.:.:.:.",
":.:.3.{                         X k a a a a a a a a a a a z D a a a a a a a a a a a a ` ,.:.:.:.",
":.:.3.{                         o k a a a a a a a a a a a z A a a a i 7 q q 9 i a a p ) <.:.:.:.",
":.:.3.]                         X k a a a a a a a a a a a z A a a y c +.2.2.+.b t a p ` ,.:.:.:.",
":.:.3.]         . ^ :.| @       X k a a a a a a a a a a a z D a i b 4.5.5.5.5.5.V u d ) ,.:.:.:.",
":.:.3.]         W 5.= &.|       X k a a a a a a a a a a a z D a 6 #.5.5.5.5.5.5.=.0 a ` ,.:.:.:.",
":.:.3.]         X.X.  ! <.      X k a a a a a a a a a a a z D a v 4.5.5.5.5.5.5.5.m p ` ,.:.:.:.",
":.:.3.]         X.X.  ! <.      X k a a a a a a a a a a a z D a n 5.5.5.5.5.5.5.5.M p { <.:.:.:.",
":.:.3.]         W 5.= &.|       X k a a a a a a a a a a a z D a w 1.5.5.5.5.5.5.2.w a ` ,.:.:.:.",
":.:.<.]         . ^ :.| #       X k a a a a a a a a a a a z D a t ^ 5.5.5.5.5.5.[ r a ` ,.:.:.:.",
":.:.3.]                         X k a a a a a a a a a a a z D a a 6 [ 5.5.5.5.} 5 a d ` ,.:.:.:.",
":.:.3.{           .             X k a a a a a a a a a a a z D a a a 8 v ~ ~ v 7 a a p ) ,.:.:.:.",
":.:.3.{                         X k a a a a a a a a a a a z E a d a d a p p a a d a d ' ,.:.:.:.",
":.:.3.| & = > = = = = = = = = = > / K H ( K K K K K K K J ( 2 : : : : < 1 1 < : < < ; Q <.:.:.:.",
":.:.:.$.&.3.<.:.<.<.<.<.<.<.:.3.X...,.-.-.-.-.-.-.-.-.-.;.%.+                         , 3.:.:.:.",
":.:.:.$.$.:.:.:.:.:.:.:.:.:.*.>. .X.<.:.>.:.:.>.:.>.:.:.<.*.#                     .   3 3.:.:.:.",
":.:.:.O.&.:.:.:.:.:.:.;.:.:.:.<.| X.<.:.:.:.:.:.:.:.:.:.:.&.+                         3 3.:.:.:.",
":.:.<.$.$.<.:.:.:.5.3.3.:.:.:.<. .X.<.:.:.:.:.:.:.:.:.:.:.&.+                         3 3.:.:.:.",
":.:.<.O.$.:.:.<.X.W Q ! :.:.:.<. .X.<.:.:.:.:.>.>.:.:.:.:.&.+                         3 3.:.:.:.",
":.:.<.$.$.:.:.3.^     . &.:.:.<. .X.<.:.:.:.<.:.:.:.:.:.<.&.+                         3 3.:.:.:.",
":.:.:.O.$.>.:.3.^     . &.:.:.3.| X.<.:.:.:.:.:.<.:.:.:.<.&.+                         , <.:.:.:.",
":.:.<.@.$.:.:.3.{ O @ $ &.:.:.<. .X.<.:.<.:.:.:.:.:.<.:.:.&.@                         , 3.:.:.:.",
":.:.<.$.$.<.:.:.:.:.:.:.:.:.:.<...X.<.:.:.:.<.:.:.:.:.:.<.&.@                         , 3.:.:.:.",
":.:.:.@.&.:.:.:.:.:.:.:.:.:.:.<. .X.:.:.:.:.:.:.:.:.:.:.:.&.+                         , 3.:.:.:.",
":.:.>.O.$.>.:.:.:.,.:.:.:.:.:.3. .X.<.:.:.:.:.:.:.:.:.:.:.&.@                     .   , 3.:.:.:.",
":.:.:.$.&.<.:.>.:.<.<.<.<.<.:.3. .X.<.:.<.<.<.<.:.<.:.>.<.-.@                         , <.:.:.:.",
":.:.:.$.X.X.X.X.X.X.X.X.X.X.X.X.| | O.X.X.X.X.X.O.X.O.X.X.X.= @ # # # # # # # # # # + 4 3.:.:.:.",
":.<.:.:.:.:.-.:.&.:.:.:.:.:.:.-.:.:.:.:.:.:.:.:.:.:.:.&.:.:.:.:.:.<.<.<.<.<.<.:.<.:.<.:.:.:.:.:.",
":.:.:.:.>.:.:.:.:.:.:.>.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.",
":.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.",
":.<.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.<.:.:.:.:.:.:.:.:.<.:.:.:.:.<.:.:.:.:.:."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 117 2 ",
"   c #010101",
".  c #00000C",
"X  c #090909",
"o  c #030314",
"O  c #070719",
"+  c #080818",
"@  c #131313",
"#  c #1D1D1D",
"$  c #232323",
"%  c #37372D",
"&  c #38382E",
"*  c #313131",
"=  c #3D3D36",
"-  c #3D3D39",
";  c #494949",
":  c #525252",
">  c #5F5F5F",
",  c #646464",
"<  c #67676C",
"1  c #6C6C6C",
"2  c #767676",
"3  c #B8B807",
"4  c #B0B00B",
"5  c #B9B90F",
"6  c #A3A319",
"7  c #B4B419",
"8  c #9A9A28",
"9  c #A9A922",
"0  c #A8A82C",
"q  c #C6C604",
"w  c #CBCB00",
"e  c #D3D300",
"r  c #DBDB00",
"t  c #E2E200",
"y  c #EEEE00",
"u  c #EDED0F",
"i  c #F3F300",
"p  c #FEFE00",
"a  c #F5F50E",
"s  c #FFFF0D",
"d  c #EDED12",
"f  c #EFEF18",
"g  c #F1F114",
"h  c #FEFE15",
"j  c #FFFF19",
"k  c #C7C72C",
"l  c #CACA2F",
"z  c #D6D62D",
"x  c #D9D92A",
"c  c #C7C732",
"v  c #CBCB34",
"b  c #C3C338",
"n  c #D3D333",
"m  c #D3D33D",
"M  c #9A9A43",
"N  c #97974C",
"B  c #92925C",
"V  c #BFBF49",
"C  c #939362",
"Z  c #9D9D68",
"A  c #BABA66",
"S  c #B6B66A",
"D  c #B8B86A",
"F  c #A7A774",
"G  c #ACAC71",
"H  c #A7A779",
"J  c #ACAC7B",
"K  c #CBCB44",
"L  c #C4C44D",
"P  c #CDCD49",
"I  c #D0D046",
"U  c #D6D64B",
"Y  c #D9D94A",
"T  c #D4D457",
"R  c #818181",
"E  c gray56",
"W  c #9A9A86",
"Q  c #909090",
"!  c #9C9C9C",
"~  c #A3A384",
"^  c #A7A78B",
"/  c #B4B489",
"(  c #BCBC8C",
")  c #ACAC93",
"_  c #A6A6A6",
"`  c #A8A8A5",
"'  c #AAAAAA",
"]  c #B3B3A6",
"[  c #B1B1A9",
"{  c #B2B2B2",
"}  c #B5B5B9",
"|  c #BCBCBC",
" . c #BDBDCC",
".. c #C5C5C5",
"X. c #CBCBCB",
"o. c #D0D0CE",
"O. c #C4C4D7",
"+. c #CECED4",
"@. c #C5C5D9",
"#. c #C9C9DC",
"$. c #D3D3D3",
"%. c #DEDEDE",
"&. c #E0E0DC",
"*. c #CFCFE2",
"=. c #D1D1E4",
"-. c #DDDDF1",
";. c #E5E5E5",
":. c #ECECE7",
">. c #E1E1EB",
",. c #EAEAEA",
"<. c #E4E4F7",
"1. c #E5E5FB",
"2. c #EEEEFF",
"3. c #F2F2F2",
"4. c #FBFBF6",
"5. c #F3F3FF",
"6. c #FDFDFD",
/* pixels */
";.;.;.;.;.;.;.;.;.;.;.;.;.:.;.;.;.;.;.;.;.;.;.;.;.,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.,.",
";.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.",
";.;.;.;.:.:.,.:.:.,.:.:.:.:.:.,.:.,.,.:.:.:.:.:.:.:.:.,.:.,.:.:.:.:.:.:.:.:.:.,.;.;.;.;.",
";.;.,.;.#.#.#.#.#.#.#.#.#.#.#.+.#.#.#.#.#.#.#.#.#.#.#.+.#.#.#.#.#.#.#.#.#.#.#.$.;.;.>.,.",
";.;.,.X.V K K K L K K K K K K H L K K K K K K L K K K H L K K K L K K K K K K ^ >.;.;.;.",
";.;.,.$.u p p p p p p p p p p A g p p p p p p p p p p S a p p p p p p p p p p / >.:.;.;.",
";.;.,.$.d p p p p p p p p p p A f p p p p p p p p p p A g p p p p p p p p p p / >.;.;.;.",
";.;.,.o.d p p p p p p p p p p A g p p p p p p p p p p A a p p p p p p p p p p / >.;.;.;.",
";.;.,.$.u p p p p p p p p p p A g p p p p p p p p p p A a p p p p p p p p p p / >.;.;.;.",
";.;.,.o.u p p p p p p p p p p A g p p p p p p p p p p S a p p p p p p p p p p / >.;.;.;.",
";.;.,.$.u p p p p p p p p p p A g p p p p p p p p p p S a p p p p p p p p p p / >.;.;.;.",
";.;.,.o.d p p p p p p p p p p A g p p p p p p p p p p S a p p p p p p p p p p / >.;.;.;.",
";.;.,.$.u p p p p p p p p p p A g p p p p p p p p p p D a p p p p p p p p p p / >.;.;.;.",
";.;.,.o.d p p p p p p p p p p D f p p p p p p p p p p A a p p p p p p p p p p / >.;.;.;.",
";.;.,.$.u p p p p p p p p p p D g p p p p p p p p p p A a p p p p p p p p p p / ;.:.;.;.",
";.;.,.o.c x n x z z z z z n x G P m m I I m m I m I m J I m m I m I m m m I m ) >.;.;.;.",
";.;.3.' . O o O o O O O O + . - T K P I P P P P K I P J P I P P U Y U P P P K ) >.;.;.;.",
";.;.3._                       % j p p p p p p p p p p D g p p p y r t p p p p / >.:.;.;.",
";.;.3._                       % j p p p p p p p p p p D g p i 6 ~ | [ N w p p / -.:.;.;.",
";.;.3._         $ ! Q @       % j p p p p p p p p p p S a p 8 =.6.6.6.6.W e p / ;.;.;.;.",
";.;.3._       X %._  .|       % h p p p p p p p p p p S s w } 6.4.6.6.6.5.M p / -.&.;.;.",
";.;.3._       * 6.# ; 4.@     % h p p p p p p p p p p S p 9 1.6.6.6.6.6.6.) r ( >.:.;.:.",
";.;.3._   X   * 6.$ ; 4.@     % h p p p p p p p p p p S p 0 2.6.6.6.6.6.6.] r ( >.;.;.;.",
";.;.3._       X %.` | |       % h p p p p p p p p p p S s 3 #.6.6.6.6.4.6.Z i / >.;.;.;.",
";.;.3._   X     $ ! Q @   X   % j p p p p p p p p p p S s y C 5.6.6.6.6. .4 p / >.;.;.;.",
"&.-.3.`                       % j p p p p p p p p p p S d p e B O.<.-.` 6 p p / >.;.;.,.",
";.;.3.`                       % h p p p p p p p p p p S s p p i q 7 5 r p p p / >.:.;.;.",
";.&.3.'   X X X X X X X X X   = U v v m v m v m v m m F b l c v z z x n c c k ^ >.;.;.;.",
";.;.,.X.| X..................._  .O.O.O.O.O.O.O.O.O.=.<   o o o o o o o o o   : 3.&.;.;.",
";.;.,.$.%.,.,.,.:.:.,.,.,.,.3.} &.3.:.:.:.:.:.:.:.:.4.1                       : 3.;.;.;.",
";.;.,.o.$.;.;.;.-.%.%.;.;.;.;.{ %.;.;.;.;.;.;.;.;.-.3.1                       : ,.;.;.;.",
";.;.,.+.%.,.;.;.3.4.4.,.;.;.;.{ %.;.;.;.;.;.;.:.&.&.3.1                       : 3.;.;.;.",
",.;.,.$.%.,.;.,.R > , X.,.;.;.{ %.;.;.;.;.;.,.;.;.;.3.<                       : 3.;.;.;.",
";.;.,.$.$.;.;.,.*     } 3.;.,.{ %.;.;.;.;.;.;.;.;.;.3.1                       : ,.;.;.;.",
";.;.,.+.%.,.;.,.*     | 3.;.;.{ %.;.;.;.;.,.;.;.;.;.3.1                       : 3.;.;.;.",
";.;.,.$.$.;.;.,.! 2 R $.;.;.,.{ %.;.;.;.;.;.;.;.;.;.3.1                       : 3.;.;.;.",
";.;.,.o.$.,.;.;.3.3.4.,.;.;.;.{ %.;.;.;.;.;.;.;.;.;.3.1   X                   : ,.;.;.;.",
";.;.,.$.$.,.;.;.;.%.-.;.;.;.;.{ %.;.;.;.;.;.;.;.&.-.3.1                   X   : 3.;.;.;.",
";.;.,.+.%.,.,.,.:.,.;.,.,.;.3.{ %.,.;.,.,.,.;.,.:.;.4.1                       : 3.;.;.;.",
";.;.,.$...X.X.X.X.X.X.X.X.X.X.{ ..+.X.X.X.X.X.X.X...$.2 @ # # # # # # # # # @ , ,.;.;.;.",
",.;.;.;.&.&.%.-.%.%.;.%.-.&.%.;.;.-.%.&.&.&.;.%.%.&.-.;.;.;.;.;.>.;.;.;.;.;.;.;.;.;.,.;.",
";.;.;.;.:.;.;.;.:.;.;.;.&.:.;.;.;.;.;.;.:.;.;.;.:.:.&.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.",
";.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.",
";.;.;.;.;.;.;.:.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.,.;.;.;.;.;.;.;.;.;.;.;.;.;."
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 105 2 ",
"   c #010101",
".  c #00000F",
"X  c gray3",
"o  c #000011",
"O  c gray8",
"+  c #1E1E1D",
"@  c #35351D",
"#  c #3F3F25",
"$  c #353535",
"%  c #3D3D30",
"&  c #3A3A3A",
"*  c #404027",
"=  c #3D3D41",
"-  c #414141",
";  c #4C4C4C",
":  c #5B5B5B",
">  c gray40",
",  c #6D6D6D",
"<  c #7E7E7E",
"1  c #BEBE1E",
"2  c #868625",
"3  c #88882F",
"4  c #929222",
"5  c #91912D",
"6  c #898931",
"7  c #BCBC2A",
"8  c #ACAC32",
"9  c #C5C50A",
"0  c #D2D200",
"q  c #DBDB02",
"w  c #C3C310",
"e  c #E0E000",
"r  c #EDED00",
"t  c #F1F100",
"y  c #FEFE01",
"u  c #F4F40D",
"i  c #FEFE0D",
"p  c #ECEC1B",
"a  c #F4F412",
"s  c #FDFD10",
"d  c #CCCC25",
"f  c #DDDD25",
"g  c #DBDB2D",
"h  c #C9C933",
"j  c #D2D234",
"k  c #DEDE30",
"l  c #D7D73B",
"z  c #E2E23B",
"x  c #8A8A5D",
"c  c #AEAE5F",
"v  c #BFBF54",
"b  c #8A8A65",
"n  c #AAAA61",
"m  c #ACAC6F",
"M  c #B5B564",
"N  c #B3B374",
"B  c #C5C54C",
"V  c #CACA4D",
"C  c #D2D245",
"Z  c #C6C653",
"A  c #CACA53",
"S  c #C3C359",
"D  c #CFCF5A",
"F  c #D1D152",
"G  c #C6C665",
"H  c #CCCC67",
"J  c #C4C469",
"K  c #CACA68",
"L  c #D0D063",
"P  c #C6C671",
"I  c #8B8B8B",
"U  c #979797",
"Y  c #B2B282",
"T  c #B0B088",
"R  c #B1B191",
"E  c gray64",
"W  c gray67",
"Q  c #B1B1A5",
"!  c #B6B6AD",
"~  c #B9B9B7",
"^  c #BCBCBC",
"/  c #C5C5C5",
"(  c #C9C9C6",
")  c #C3C3CE",
"_  c #CCCCCC",
"`  c #D6D6CC",
"'  c #D8D8CE",
"]  c #C7C7D3",
"[  c #CFCFD5",
"{  c #CCCCDB",
"}  c #D4D4D4",
"|  c #D5D5DD",
" . c #DDDDDD",
".. c #DFDFE7",
"X. c #DBDBED",
"o. c #E5E5E5",
"O. c #E8E8E4",
"+. c #E3E3E9",
"@. c #EAEAEA",
"#. c #F0F0ED",
"$. c #E3E3F4",
"%. c #EBEBFE",
"&. c #F3F3F3",
"*. c #F6F6FF",
"=. c #FEFEFD",
/* pixels */
"o.o.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.o.o.",
"o.o.{ { [ { { } { { } [ { { { { { { { [ [ { [ { { [ { { { } o.o.",
"@.` h g g g g g j f B v f g g g g g g j M g j g g g g g f N X.O.",
"@.` u y y y y y y y k l y y y y y y y u A y y y y y y y y G X.O.",
"@.` u y y y y y y y k l y y y y y y y u Z y y y y y y y y G X.O.",
"$.` t y y y y y y y k l y y y y y y y u Z y y y y y y y y G X.O.",
"@.` t y y y y y y y k l y y y y y y y u Z y y y y y y y y G X.O.",
"@.` u y y y y y y y k l y y y y y y y u Z y y y y y y y y G X.O.",
"@.` u y y y y y y y g l y y y y y y y u Z y y y y y y y y G X.@.",
"@.} t y y y y y y y g l y y y y y y y u A y y y y y y y y G X.O.",
"+.` a s i i i i i i z C y a u u u a u p S u a u a a u a t J X.O.",
"&.~ # * # # * # * * * n A Z Z Z A A A S N V Z Z F F Z Z V Y o.o.",
"&.W                 . d y y y y y y y u Z y y y 0 0 r y y G X.@.",
"&.W   X     + X     o d y y y y y y y u Z y q n [ X.R w y G X.O.",
"&.W       I _ E     . d y y y y y y y u Z y c *.=.=.=.! q H X.O.",
"&.W     +  .O } -   o d y y y y y y y u F 0 / =.=.=.=.%.w D X.O.",
"&.W     +  .O _ -   o d y y y y y y y u F 0 [ =.=.=.=.%.7 D X.@.",
"&.W       I } E     o d y y y y y y y u D t T =.=.=.=.] 0 L X.O.",
"&.W   X     + X     o d y y y y y y y a Z y 9 Q %.%.] 8 y G X.@.",
"&.W                 . d y y y y y y y u Z y y r d h q y y G X.O.",
"&.~ $ & & & = & & & = m K J J G J J J P x 2 6 5 4 4 5 6 2 b +.o.",
"o. .o.@.@.@.@.&.@.&.} ] $.X.X.X.X.X.X.$.-                 $ @.o.",
"@.}  .o.o.o.o.o.o.@._ ( @.O.O.@.@.O.O.@.-                 & @.o.",
"@.}  .+.O.@.+.o.o.@._ ( @.o.O.o.O.o.o.@.-                 & @.o.",
"@.}  .o.@.: O < &.@._ ( @.+.o.o.o.o.o.&.=                 & @.o.",
"@.}  .o.@.&   > &.+.` ( @.o.+.o.o.o.o.@.*                 & @.o.",
"@.}  .@.@.U , W @.@.[ ( @.o.+.o.o.o.o.@.- .               & @.o.",
"o.}  .o.o.&.&.&.o.@._ ( @.o.o.o.o.o...&.-   X             & @.o.",
"@.} ..@.@.o.o.o.o.@.} ( @.+.@.@.@.+.@.#.-                 & @.o.",
"@.} _ } } } } } } } / ^  .` } } } } [  .; X O O O O O O X - @.o.",
"O.O. . . . . . . . . .o. . . . . . . . . . . . . . . . . . .o.o.",
"o.o.@.o.@.@.@.+.@.@.o.o.@.+.@.o.@.@.o.@.+.@.o.@.o.o.o.@.@.@.o.+."
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 177 2 ",
"   c gray89",
".  c #D8D8DB",
"X  c #D7D7DB",
"o  c #D8D8DA",
"O  c #D9D9DB",
"+  c gray90",
"@  c #DEDED1",
"#  c #E5E52C",
"$  c #EDED1C",
"%  c #EBEB20",
"&  c #ECEC1F",
"*  c #D4D442",
"=  c #EEEE1C",
"-  c #E3E32C",
";  c #D8D83C",
":  c #EFEF1A",
">  c #EAEA22",
",  c #EFEF15",
"<  c #D8D84E",
"1  c #DCDCE8",
"2  c #DFDFCF",
"3  c #F6F60F",
"4  c yellow",
"5  c #FEFE01",
"6  c #E1E12C",
"7  c #FEFE00",
"8  c #F4F410",
"9  c #E6E624",
"0  c #FDFD03",
"q  c #E5E538",
"w  c #DBDBEA",
"e  c #DEDECF",
"r  c #F2F211",
"t  c #FCFC00",
"y  c #F9F903",
"u  c #FAFA01",
"i  c #DFDF2D",
"p  c #FCFC03",
"a  c #FDFD02",
"s  c #F2F212",
"d  c #E5E526",
"f  c #FBFB06",
"g  c #E4E43A",
"h  c #E0E0D1",
"j  c #F7F710",
"k  c #E2E22D",
"l  c #D4D4CB",
"z  c #99991F",
"x  c #9C9C12",
"c  c #999912",
"v  c #989814",
"b  c #ABAB3A",
"n  c #E7E72C",
"m  c #E1E129",
"M  c #E4E427",
"N  c #DBDB35",
"B  c #D1D145",
"V  c #EAEA20",
"C  c #E2E218",
"Z  c #EAEA18",
"A  c #D2D256",
"S  c #DCDCE7",
"D  c #BFBFC0",
"F  c #030304",
"G  c #010106",
"H  c #0E0E17",
"J  c black",
"K  c #686819",
"L  c #FFFF0A",
"P  c #F5F507",
"I  c #FCFC04",
"U  c #EFEF18",
"Y  c #E4E424",
"T  c #E1E11C",
"R  c #CECE7F",
"E  c #DCDC27",
"W  c #E0E036",
"Q  c #DBDBEB",
"!  c #C3C3C3",
"~  c #595955",
"^  c #A1A19A",
"/  c #0D0D19",
"(  c #64640F",
")  c #FFFF03",
"_  c #FAFA00",
"`  c #F8F810",
"'  c #D5D521",
"]  c #E1E1BC",
"[  c white",
"{  c #E9E9D5",
"}  c #CCCC48",
"|  c #E0E0E6",
" . c gray35",
".. c #A1A19E",
"X. c #0C0C1C",
"o. c #646411",
"O. c #FFFF05",
"+. c #FAFA02",
"@. c #F8F811",
"#. c #D0D025",
"$. c #E2E2CB",
"%. c #EBEBE1",
"&. c #C6C64E",
"*. c #E1E1E4",
"=. c gray75",
"-. c gray1",
";. c #010101",
":. c #0F0F0B",
">. c #696916",
",. c #FFFF02",
"<. c #F7F700",
"1. c #FDFD00",
"2. c #F1F111",
"3. c #E7E721",
"4. c #EAEA2D",
"5. c #E2E2A6",
"6. c #E7E73E",
"7. c #E4E435",
"8. c #DCDCEC",
"9. c LightGray",
"0. c #8D8D8D",
"q. c gray56",
"w. c #8D8D8C",
"e. c #8B8B8E",
"r. c #A2A291",
"t. c #DADAA4",
"y. c #D4D4A2",
"u. c #D6D6A2",
"i. c #D4D4A6",
"p. c #5A5A34",
"a. c #454505",
"s. c #434303",
"d. c #434300",
"f. c #5C5C3A",
"g. c #DFDFDF",
"h. c #EEEEEE",
"j. c gray96",
"k. c gray95",
"l. c #F6F6F6",
"z. c #E5E5F1",
"x. c #E7E7F2",
"c. c #E6E6F1",
"v. c #252526",
"b. c #252525",
"n. c gray85",
"m. c gray93",
"M. c gray53",
"N. c #2F2F2F",
"B. c #ECECEC",
"V. c #CCCCCB",
"C. c #E4E4E2",
"Z. c #E5E5E2",
"A. c #E5E5E3",
"S. c #282826",
"D. c #070705",
"F. c #282827",
"G. c gainsboro",
"H. c #E6E6E6",
"J. c #CDCDCD",
"K. c #B2B2B2",
"L. c gray92",
"P. c gray81",
"I. c #E7E7E7",
"U. c gray91",
"Y. c gray87",
"T. c #D8D8D8",
"R. c #E4E4E4",
"E. c #DDDDDD",
"W. c gray80",
"Q. c gray21",
"!. c #0E0E0E",
"~. c #181818",
"^. c gray5",
"/. c #373737",
"(. c gray88",
"). c #D7D7D7",
"_. c #DADADA",
/* pixels */
"  . X X X o X X X X o X X X O + ",
"@ # $ % & * % & = - ; : > , < 1 ",
"2 3 4 5 4 6 5 7 4 8 9 4 0 4 q w ",
"e r t y u i p a 4 s d 4 f 4 g w ",
"h j 4 5 4 k 5 7 4 8 9 4 0 4 q w ",
"l z x c v b n m M N B V C Z A S ",
"D F G H J K L P I U Y T R E W Q ",
"! J ~ ^ / ( ) _ 4 ` ' ] [ { } | ",
"! J  ...X.o.O.+.4 @.#.$.[ %.&.*.",
"=.-.;.:.J >.,.<.1.2.3.4.5.6.7.8.",
"9.0.q.w.e.r.t.y.u.i.p.a.s.d.f.*.",
"g.h.j.k.l.X z.x.x.c.v.J F J b.  ",
"n.m.M.N.B.V.C.Z.A.Z.S.J D.J F.  ",
"G.H.J.K.L.P.H.I.U.I.b.J -.J b.  ",
"Y.T.R.U.E.W.E.E.Y.Y.Q.!.~.^./.  ",
"+ (.Y.E.(.(.(.(.(.(.n.).T.)._.+ "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
