#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXkXlXhXfXfXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXgXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXhXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXjXfXjXlXkXlX",
"lXkXlXjXnXJXGXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXCXKXAXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXFXJXMXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXsXcXKXmXjXlXlX",
"lXlXjXmX=Xz.V.aXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXnX^.j.R.vXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXzXhXS.l.@XPXLXLXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXLXUX9Xd.&XMXjXlX",
"lXhXnX;Xz     @.lXvXxXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXkXVXL.;   # N.VXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXxXcXbX2.    y 1.<.<.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.<.4.F   x.JXfXlX",
"lXfXJXx.  & O   :XtX0XqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqX5XcXD   %   j lX6XqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXwX9X$   +                                                     @   c.HXfXlX",
"lXfXFXC.  O   ; 8XgXpXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXrXVX^   X   F MXtXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXaXsXpX8                                                         @   l.JXfXlX",
"lXjXzXaX%.  : F.vXxXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXvX<XN   h &XbXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXnXU.    S ;X$X%X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X;Xr.  l.KXfXlX",
"lXlXkXxXlX:X8XvXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXcXsX*XiXvXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXbXeX    | UXcXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXcX,XqXcXkXlX",
"lXkXlXjXvXtXgXxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXcXwXxXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { PXaXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXcXpXiXxXkXlX",
"lXlXlXkXxX0XpXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX6XjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXkXlXkXgXdXsXdXjXlXkXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXkXhXfXdXsXdXfXkXlXkXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXkXlXkXhXCXKXLXGXcXhXlXlXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXkXlXbXSXJXLXJXZXjXkXlXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXkXkXlXxXM. .` <.-XnXjXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXjX.Xp.#.] o.z.fXxXkXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXkXkXzX) #     X 7 /.mXjXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXvXtXC   .     @ B eXxXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXjXmXk.  X 2.!.c   m 7XnXjXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXnX8Xx ..^.'.Z     t.vXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXkXgXCXz   u cXJXl.    ~.NXjXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXgX0XzXcXCX/.2   ` vXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXkXkXuX6   G BXBXU.>   s.xXlXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXkXlXxXzXdXAXL.:   i.vXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXjXzX<X2   E MXNXW.3   7.kXzXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXkXlXkXgXnX7Xm   f wXxXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXjXzX6X3   I nXMXT.1   q.lXzXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXkXgXmX=Xv   s +XcXkXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXkXhXcXw   v ZXAXG.O   A.nXkXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXkXlXNX'.g   M =XnXkXkXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXhXCX_   > .XvX .  & #XNXjXkXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXlXK.w   H =XfXeXpXlXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXkXkXzX;X,   w M -   1.lXzXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXvXrXb   O s Z c c &.cXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXkXnX{.D o   2 e.pXxXjXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXnX8X8   .         x bXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXkXlXkXnXiX8X7XqXzXcXkXlXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXjX8X3X4X5X6X6X6XwXlXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXkXkXcXnXmXbXlXkXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXkXlXnXmXmXmXmXmXmXbXkXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXkXkXkXkXkXkXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXlXkXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXkXkXkXkX5XrXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgX1XdXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbX8X    [ PXsXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXlX8XrXcXkXlX",
"lXlXlXhXVXcXVXvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXSXlXSXhXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXdXzX8X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMXNXgXlXkXlX",
"lXkXhXnXK.A ! <XvXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXlX8.M :.cXGXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXPX2X    ) FXdXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXnX{.c P.DXgXlX",
"lXgXCX/.>     M sXcXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXSX9.    o u d s d d d d d d d d d d d d d d d d d d d d d d q     & J.AXgXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXBX*Xu   x.JXfXlX",
"lXfXJXl.  % X   *XqX6X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X1XkXV   O                                                         @   -.lX2X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X7X4XsXF.    z.JXfXlX",
"lXgXZXE.%     h iXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXAX,.    X 2 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 ,     + C.AXfXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXNX@X8   z.JXfXlX",
"lXkXjXvXN.j D &XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXcXu   2 jXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXZX3XP f h.cXjXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXZXl.  n.JXfXlX",
"lXlXlXjXVXlXMXvXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXfXGXd   5 BXdXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXxXBXjXCXjXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXfXHXA.  n.JXfXlX",
"lXkXkXkXlX6XtXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXfXFXs   5 BXhXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXiX4XkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXlXkXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXkXzXvXbXnXnXbXvXxXkXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXjXcX7Xe.M 4 ; h 6.eXxXkXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXgXAXY.# @ 2 - .   B fXjXkXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXhXCX).| !.fX>Xv   = A.BXgXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXkXkXMXmXhXvXv.  % z.ZXfXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXkXlXkXhXgXhXmX^   q =XcXhXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXkXlXlXjXjXbXe.  o d.NXgXkXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXkXlXjXzXkX-.    p.xXjXkXkXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXjXvXiX'   # Z.mXcXzXkXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXjXcX7XY   + y.*XOXoX8XxXkXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXgXSXL.+   .         7.DXfXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXgXCX/.f r y w e w w h.AXfXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXkXvXSXSXSXDXDXDXDXmXjXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXkXlXjXgXfXgXfXfXfXfXjXlXkXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXcXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXlXlXkXxXqXaXzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXd   5 BXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX9XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXHXZ.  n.JXfXlX",
"lXkXlXkXcXwXsXzXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXFXd   5 BXhXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXfX0XcXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXfXHXZ.  n.JXfXlX",
"lXlXkXzXbX9XpXnXbXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXbXzXPXd   6 ZXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXvXsX8XvXbXbXbXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXzXUXD.  n.JXfXlX",
"lXkXlXhX3.@ 5 U.eX9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X8X8X2Xq   , 3XxXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXvX].w o +.8X8X8X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X8XuX9.  b.JXfXlX",
"lXgXFXD.  X                                                             P BXiXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXfXsXr                                                         @   l.JXfXlX",
"lXfXJXz.  @                                                         +   f jX4X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X0X8X@                                                         @   x.JXfXlX",
"lXhXMX#Xa     S | { { { { { { { { { { { { { { { { { { { { { [ { ) *   O g.CXkXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXcXvX#.    9 { [ [ { { { { { { { { { { { { { { { { { { { { [ | b   x.JXfXlX",
"lXkXdXLX<.    ;XUXPXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXPXIXFXJ.=.C.cXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXbX8X    { UXHXPXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXPXPXUX4X=.[.VXhXlX",
"lXkXdXLX<.    $XcXaXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXdXAXlXAXjXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbX8X    [ HXrXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXaXmXNXgXlXkXlX",
"lXkXdXLX<.    %XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgX2XfXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbX8X    [ PXsXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXlX8XrXcXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXlXkXjXjXjXjXjXkXkXlXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXkXzXmXBXVXVXNXxXjXkXlXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXlXdX4X&X@X+X*XsXvXkXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXjXvX!.9   .   = _ ,XvXjXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXjXbXV.j ! | x     @.fXxXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXzX5X>XgXZX.Xs   C 7XnXjXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXkXvXnXFXGX'.t   2.lXzXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXkXzXuXA n 0   o.pXcXjXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXkXcXyX+   . . 1 G.cXkXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXkXvXzXiXaXW.a   g 3XmXjXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXlXtXjXBXAXcX{   - %XBXjXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXhXVXT $.A.W.1.,   N 8XbXjXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXhXCXS         # a !.bXkXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXcXXXx.9.1.7.c.5XnXkXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXkXmXFXKXPXKXDXxXhXlXlXkXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXkXlXhXfXdXdXdXfXjXkXlXkXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXlXdXPX1.    &XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX7XkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { IXsXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXyXxXkXlX",
"lXkXdXPX1.    &XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjX4XhXkXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnX9X    { PXsXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXzXqXtXxXkXlX",
"lXkXdXPX<.    %XnXdXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXBXsXNXhXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXzX8X    [ PXsXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXnXzXsXzXkXlX",
"lXlXsXUX3.    ,XUXGXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXSX&XD.+XZXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXUXuX    | UXaXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXvXpXH.;XmXjXlX",
"lXjXcX9XJ   . ,.F.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.b.t   6 l.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.9.O   n 3XmXlXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXzXnXaX#.  x.JXfXlX",
"lXfXJXl.  @                                                                                                                   +   ,.MX9XrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXwXlXP.    l.JXfXlX",
"lXjXmX&Xa.x.k.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.x.l.z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.l.x.s.[.gXrXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXtXsX;Xh.s.%XMXjXlX",
"lXlXjXMXPXHXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXJXLXVXlXcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXzXmXLXLXMXjXlXlX",
"lXkXlXjXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXfXfXjXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXgXfXhXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXhXlXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXgXfXlXlXlXlX",
"lXlXkXzXSXHXNXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXAXJXBXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXZXJXVXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXCXGXkXlXlXlX",
"lXkXzXyXX.n N.bXkXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXzXsX&.v k.vXkXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXlXhX2.v y.cXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXxX6.K cXkXkXlX",
"lXgXSXo.    # ).mXsXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXCX,.    X P.NXaXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXCXr.    + 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4   > vXkXkXlX",
"lXfXHXN   -   m.jX7X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X5XcXK   ;   i.lX6X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X0X5XcX_   @                                                   5 vXkXkXlX",
"lXhXNXB.%   c 5XmXlXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXkXVXP.;   d ;XMXlXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXkXVX/.>   0 <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.,.3 = bXkXkXlX",
"lXlXkXbX_.n.5XbXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXnX{.v.,XnXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXHXn   W UXFXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXKX#XV.zXlXkXlX",
"lXkXlXkXmXjXmXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXmXhXMXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXDXv   R FXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXNXfXkXlXlXlX",
"lXkXkXlXsX7XlXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXfX6XkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXFXv   R KXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXhX6XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXkXkXkXkXkXkXkXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXkXlXkXkXlXzXlXkXkXlXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXkXlXkXkXlXlXlXlXkXkXlXkXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXkXlXjXxXvXzXxXzXbXlXkXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXkXlXvXcXcXxXzXbXzXkXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXjXcXaXq.q o g B.zXlXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXkXxXyXw.h & = M m.jXzXkXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXkXjXcX+.  < b *   v.bXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXhXNX#X* 0 D i     k.nXkXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXhXCX[.%   F.DX>.  w sXxXkXlXlXlXkXlXhX9XzXkXlXlXlXlXkXbX6Xn.1XZX>Xk   G sXxXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXhXCXn.  > 9XJXY.. X XXbXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXkXzXCXvXjXkX)   Q gXzXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXjXnXe.  r 6XAXQ.=   P.nXjXlXlXlXkXlXhX9XzXkXlXlXlXlXkXlXkXgXfXVXW.#   L.MXjXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXjXmXr.  e 6XSXW.*   I.nXjXlXlXlXkXlXhX9XzXkXlXlXlXlXkXlXjXjXNXI.;   e.xXkXkXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXhXZXB.  = 8XIXL.  O $XvXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXjXzXmXv.@ O z.MXzXkXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXhXBXoX<   k.zX|   g gXzXkXlXlXlXkXlXhX9XzXkXlXlXlXlXkXlXhXw.+ % k.iX6XqXkXlXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXkXkXhXmX8.  O <   o P.bXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXjXMX%X<   X 5 : * m iXcXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXkXlXxXN.C u U (.vXkXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXjXmX:XN a s w r 0 J pXxXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXkXlXkXlXmXAXDXZXbXkXkXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXkXxXAXSXAXDXDXDXZXlXkXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXkXkXkXjXhXgXhXjXkXkXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXkXlXkXhXgXgXgXgXgXhXkXlXkXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXlXpX5XkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXsX4XjXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXDXv   R KXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXgX4XkXlXlXlX",
"lXlXkXzXCXcXCXjXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXZXxXCXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXsXFXb   E PXdXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXAXlXkXlXlXlX",
"lXkXlXsX>.G L.nXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjX7.D C.ZXBXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXBXAXl   P SXgXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXs.Q cXlXkXlX",
"lXgXAX*.    - {.MXfXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXsXZX7.    * i i i i i i i i i i i i i i i i i i i i i i y @   O D.VXsXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXsXCXN.  , vXkXkXlX",
"lXfXHXN   ;   n.hX6X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X4XxXK   @                                                   %   <.zX4X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X4XxX&.  7 cXkXkXlX",
"lXhXBXk.O   s <XMXkXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXjXCXZ.#   q .. . . . . . . . . . . . . . . . . . . . . .[ >   4 {.BXjXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXjXVX_.= - bXkXkXlX",
"lXlXkXvXI.u.;XnXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXZXi   ..UXGXLXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXLXPXHX).r..XmXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXLXZ X mXkXkXlX",
"lXkXlXkXNXlXMXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXBXi    .GXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXfXBXkXNXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXdXKXC X mXkXkXlX",
"lXkXkXlXaX6XlXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXVXi    .LXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXgX5XjXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXlXkXkXjXjXjXjXkXkXlXkXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXkXlXbXNXBXNXmXnXlXkXlXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXzXsXc.D 9 7 D C.kXlXkXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXjXnX2X2 - h 8 .   s.nXjXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXvXqXp.OXMX<Xz   N tXcXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXkXlXVXmXjXvX#.  S yXcXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXlXkXgXfXNX+X2   k.MXjXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXlXkXhXNX Xr   +.hXlXkXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXkXlXNXR.,   2.xXxXjXlXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXkXlXm.: . 9.dXtXyXkXlXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXjXnX5Xe   . p r 9 V 0XvXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXjXnX5Xx 5 6 - : * h 9XbXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXkXzXmXMXMXNXBXBXMXlXkXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXkXlXkXjXjXjXjXjXjXjXkXlXkXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXKXC X mXkXkXlX",
"lXlXkXzXgX0XxXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXi    .PXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX9XlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXKXC X mXkXkXlX",
"lXkXkXlXpX5XkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXVXi    .LXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXfX3XhXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXdXKXC X mXkXkXlX",
"lXlXkXlXCXvXVXdXgXgXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXsXBXi    .PXdXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXkXZXcXZXfXgXgXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXiXHXZ X mXkXkXlX",
"lXkXlXhXe./ ^.JXDXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXDXFXAXy   [ HXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXx.~ S.FXDXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXDXAXUXN o mXkXkXlX",
"lXgXZX2.    < b v v v v v v v v v v v v v v v v v v v v b l @   ; (.BXfXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXfXZXc.X   = v v v v v v v v v v v v v v v v v v v v v v v + : vXkXkXlX",
"lXfXHXN   @                                                 . %   u.kX5X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X3XxX)   #                                                   3 vXkXkXlX",
"lXhXVXu.    0 W R R E E E E E E E E E E E E E E E E E R E P %   5 .XBXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXZXD.$   1 R R R E E E E E E E E E E E E E E E E E R E R & ; vXkXkXlX",
"lXkXkXcX5   <.UXFXKXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXKXPXSXD.:.{.mXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXfXDXv   R UXGXKXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXLXKXLXJXR.8.xXlXkXlX",
"lXkXkXcX5   <.FXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXgXVXxXBXhXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXFXv   R GXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXCXkXkXlXlXlX",
"lXkXkXcX5   <.LXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXsX4XjXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXFXv   R KXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXgX4XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXlXkXjXhXgXgXhXjXkXlXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXkXlXMXAXSXSXCXnXlXkXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXlXdXh.V a d I H.lXlXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXjXvX9XC $ 9 *     C.nXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXxXuX_.>XcX|.t   _ lXlXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXkXzXnXSXLX>Xs   h.bXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXlXfXCX:.s q   $.jXzXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXlXdXAX| # %   < U.vXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXjXvXMXbXBX8XD   B jXzXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXkXbX4X'.gXBXuXR   h gXzXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXgXSXL.X n D p     y.vXkXkXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXjXmX=XH 3   = B m.hXzXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXkXzXvXcXxXxXzXbXzXkXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXlXkXlXlXzXlXlXkXkXlXkXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXlXkXkXkXkXkXkXkXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX9XzXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXv   E LXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlX9XkXlXlXlX",
"lXkXkXcX5   <.LXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXsX4XjXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXDXv   R KXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXgX4XkXlXlXlX",
"lXkXkXcX5   <.GXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXgXCXcXVXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXiXAXv   R LXdXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXZXlXkXlXlXlX",
"lXkXlXxX5   <.UXFXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXLXAXM.@.).PXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXHXUXv   R JXdXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXmXL.,.xXlXkXlX",
"lXgXCX7.    3 Z C C C C C C C C C C C C C C C C C C C C Z m @   , C C C C C C C C C C C C C C C C C C C C C Z N %   * R.CXgXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXZXL.X > bXkXkXlX",
"lXfXGXP + 3 = X X X X X X X X X X X X X X X X X X X X X X o , 5 - X X X X X X X X X X X X X X X X X X X X X X o : 5   8.kX4X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X4XlX1.  g cXkXkXlX",
"lXlXkXcXvXcXbXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXnXvXcXbXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXvXcXvXxXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXxXbXcXkXlXlXlX",
"lXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXlXlXlX",
"lXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXgXjXlXkXlXlXlXlXlXlXkXlXkXgXjXlXkXlXlXlXlXlXlXkXlXkXhXjXkXkXkXkXkXkXkXkXkXkXkXhXkXlXkXlX",
"lXlXkXlXZXbXjXkXkXkXkXkXkXkXkXkXlXZXbXjXkXkXkXkXkXkXkXkXkXlXZXnXlXzXzXzXzXzXzXzXzXzXxXVXlXkXlXlX",
"lXkXlXhXT.4XbXlXzXzXzXzXzXzXlXzXjXT.3XbXlXzXzXzXzXzXzXlXzXkXU.,XcXhXjXjXjXjXjXjXjXkXdX`.fXzXkXlX",
"lXhXZXT.  ( bXyXpXpXpXpXpXpXyXcXU.  ! vXyXpXpXpXpXpXpXyXcXU.  @ & & & & & & & & & * X 6 fXzXkXlX",
"lXjXbX5XE H.mXgXjXjXjXjXjXjXhXxX5XW D.mXgXjXjXjXjXjXjXhXcX6X# #.W.F.H.H.H.H.H.H.H.K.A.*.sXzXkXlX",
"lXlXjXbXnXmXkXlXlXlXhXgXkXlXlXkXbXnXmXlXlXlXkXgXgXkXlXlXlXmX: J.UXVXSXSXSXSXSXSXSXAXDXvXhXlXkXlX",
"lXkXkXlXtXgXlXkXkXkXAXJXcXjXlXkXlXtXgXlXlXjXnXJXGXvXkXkXlXzX; N.ZXsXgXgXgXgXgXgXgXgXjXyXhXlXkXlX",
"lXlXkXzXpXjXlXkXkXvXZ.4.7XbXjXkXzXpXjXlXjXbX%X6.r.7XvXjXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXlXkXzXpXjXlXgXSXa.y ! j kXlXkXzXpXjXlXhXBXc.;.M x cXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXlXkXzXpXjXlXhXAXn 2.lX# +XMXhXzXpXjXlXlXkXzXUX1.h bXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXlXkXzXpXjXlXhXAXn 1.jX@ @XMXhXzXpXjXlXkXjXCXg.v yXmXhXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXlXkXzXpXjXlXgXAXg.r U c lXlXkXzXpXjXlXgXZXg.  ^ i.aXzXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXlXkXzXpXjXlXkXkXbXH.w.qXbXjXkXzXpXjXlXjXmX/.i.0.i.fXlXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXkXlXyXhXlXkXlXjXZXJXcXjXlXkXlXyXgXlXkXjXNXGXHXGXlXjXlXxX; B.DXgXlXlXlXlXlXlXkXkXlXuXhXlXkXlX",
"lXlXkXzXcXcXkXkXkXkXgXfXjXkXkXkXzXcXcXlXzXzXkXgXhXhXlXlXzXvX; V.DXgXkXkXkXkXkXkXkXkXzXzXjXlXkXlX",
"lXkXlXjXI.5XbXlXzXzXzXzXzXzXlXzXkXL.2XbXkXlXlXlXlXlXlXlXzXlX: N.FXhXzXzXzXzXzXzXlXzXjX^.dXzXkXlX",
"lXhXZXR.  ) bXyXpXpXpXpXpXpXyXcXL.  # - = = = = = = = = = -   T cXyXpXpXpXpXpXpXyXcXP., gXzXkXlX",
"lXjXbX3XU D.mXgXjXjXjXjXjXjXgXcX2X+ #.U.Z.S.S.S.S.S.S.S.D.A.T B.mXgXjXjXjXjXjXjXgXvX,Xg pXxXkXlX",
"lXlXjXbXnXmXlXlXlXlXlXlXlXlXlXlXbX- U.UXCXSXSXSXSXSXSXSXSXDXbXmXlXlXlXkXgXgXkXlXlXzXkXZ rXcXkXlX",
"lXkXkXlXtXgXlXkXkXkXkXkXkXkXkXzXkX* Z.CXsXgXgXgXgXgXgXgXgXhXyXfXlXlXkXnXJXGXvXkXkXzXdXN tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXjXvX=X0.y.8XvXjXzXdXB tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXhXVXv.&.M z zXkXzXdXB tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXlXkXlXUX7.a vXkXzXdXB tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXkXjXZXx.z wXMXhXzXdXB tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXgXZXx.  ~ s.pXzXzXdXB tXcXkXlX",
"lXlXkXzXpXjXlXkXlXlXlXlXlXlXkXzXlX= S.SXgXlXlXlXlXlXlXlXkXzXpXhXlXjXmX^.e.7.e.dXzXzXdXB tXcXkXlX",
"lXkXkXlXyXhXlXkXkXkXkXkXkXkXkXlXlX= S.SXgXlXlXlXlXlXlXkXkXlXyXgXlXkXjXNXGXHXGXlXjXzXdXB tXcXkXlX",
"lXlXkXzXcXcXlXlXlXlXlXlXlXlXlXzXzX= D.SXgXkXkXkXkXkXkXkXkXzXcXcXlXlXlXjXgXgXhXlXlXxXgXB tXcXkXlX",
"lXkXlXkXU.6XmXzXxXxXxXxXxXxXxXvXlX- A.DXhXzXzXzXzXzXzXlXzXzXY.3XmXzXxXxXxXxXxXxXxXvXdXB tXcXkXlX",
"lXhXZXU.  % : ; ; ; ; ; ; ; ; ; :   ! vXyXpXpXpXpXpXpXyXcXY.  $ : ; ; ; ; ; ; ; ; > @ 6 fXzXkXlX",
"lXjXnX,XX #.J.N.V.V.V.V.V.V.B.V.N.P B.mXfXhXhXhXhXhXhXgXcX3X@ ..K.M.V.V.V.V.V.V.B.C.b.o.aXxXkXlX",
"lXkXlXxX* W.UXZXDXSXCXCXSXDXDXDXFXvXmXlXlXlXlXlXlXlXlXlXlXmX> K.UXCXDXDXDXDXDXDXDXDXGXcXhXlXkXlX",
"lXkXzXhX% F.VXsXfXxXFXSXzXfXgXgXhXyXgXlXkXkXkXkXkXkXkXkXlXzX; M.CXsXgXgXgXgXgXgXgXgXhXyXhXlXkXlX",
"lXkXzXjX& H.SXfXvX;X7.u.5XvXjXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.SXfXMXE.u.m x bXkXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.SXhXjXbX~.c %.VXhXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.SXhXjXBXE.G Z zXlXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.SXdXNXl.f.R y kXlXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.SXfXnX`.-.w.6XvXjXkXzXpXjXlXkXlXlXlXlXlXlXkXlXxX; V.DXgXlXlXlXlXlXlXlXkXzXpXhXlXkXlX",
"lXkXzXjX& H.AXgXjXNXKXGXvXjXkXkXlXyXgXlXkXkXkXkXkXkXkXkXlXxX; B.DXgXlXlXlXlXlXlXkXkXlXuXhXlXkXlX",
"lXkXzXkX* K.DXjXzXkXhXhXlXzXzXzXcXvXvXzXzXzXzXzXzXzXzXzXxXvX> C.DXgXkXkXkXkXkXkXkXkXxXxXjXlXkXlX",
"lXkXxXdX$ C.NXpXdXdXdXdXdXdXdXfXsXL.>XkXdXdXdXdXdXdXdXdXgXdX* m.FXhXzXzXzXzXzXzXlXxXhX^.dXzXkXlX",
"lXhXVX).: k C N B B B B B B B B M , d Z N B B B B B B B B B : o.cXyXpXpXpXpXpXpXuXzX^.i fXxXkXlX",
"lXkXlXfXdXiXrXtXtXtXtXtXtXtXtXtXtXgXpXrXtXtXtXtXtXtXtXtXtXtXdXsXhXhXhXhXhXhXhXhXhXjXdXfXlXkXkXlX",
"lXlXkXzXzXxXcXcXcXcXcXcXcXcXcXcXcXzXxXcXcXcXcXcXcXcXcXcXcXcXzXxXlXlXlXlXlXlXlXlXlXlXzXzXkXlXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXkXlXkXkXlXkXlXlXlXlXlXkXlXkXkXkXlXkXlXlXlXlXlXkXlXkXkXlXkXlXlXlXlXlXlXkXlXkXkXlXkXlX",
"lXkXlXkXzXlXkXkXkXkXkXkXkXkXkXkXxXkXkXkXkXkXkXkXkXkXkXlXzXgXgXgXgXgXgXgXgXgXgXzXlXkXlXlX",
"lXlXkXxXjXlXxXlXzXzXzXzXzXzXlXvXfXcXlXzXzXzXzXzXzXzXxXlXfXKXJXJXJXJXJXJXJXJXKXjXhXlXkXlX",
"lXkXzXjXt P vXaXsXsXsXsXsXpXbXQ.  Z.mXiXsXsXsXsXsXpXnXO.1 P H H H H H H H J F i qXvXkXlX",
"lXkXlXlXI $.bXdXfXfXfXfXfXsXvX Xp Q.nXsXfXfXfXfXfXaXVX@.- 7.>.,.,.,.,.,.,.<.,.Y wXvXkXlX",
"lXlXkXxXvXbXxXlXzXkXhXhXlXzXkXnXcXnXlXzXlXhXhXjXzXhXJXz.n UXGXKXKXKXKXKXKXJXLXvXgXlXkXlX",
"lXkXkXlXaXdXlXkXjXnXFXAXlXkXlXkXuXjXlXkXcXDXFXNXjXgXGXd.k CXsXgXgXgXgXgXgXfXhXpXhXlXkXlX",
"lXlXkXzXsXfXlXjXmX#X! t.zXlXkXlXpXkXjXvX7X@./ _.nXdXGXf.l DXhXkXlXlXlXlXlXkXzXaXgXlXkXlX",
"lXlXkXzXsXfXlXkXcXh e.k m.AXgXlXpXkXjXbX:XT.6.p zXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXkXzXsXfXkXcXwX5 kX+.$.GXgXlXpXkXlXjXnXUX| <.VXdXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXkXzXsXfXlXlXzXi c.v k.SXgXlXpXkXkXzXdXV M 1XkXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXkXzXsXfXlXhXMX'.F >.hXzXkXlXpXkXjXmX&Xm W  .dXhXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXkXkXzXpXsXzXlXjXMXZXCXzXkXlXkXyXjXkXjXzXZXmXmXkXfXFXd.l SXhXkXlXlXlXlXkXkXzXiXgXlXkXlX",
"lXlXkXlXbXvXkXkXlXhXhXhXkXlXkXxXbXbXcXvXcXzXxXxXvXlXPXj.z FXgXkXkXkXkXkXkXkXzXcXjXlXkXlX",
"lXkXkXvXQ. XnXkXlXlXlXlXlXkXxXuXZ.2XtXwXwXwXwXwXeX9XxXe.k CXjXlXlXlXlXlXlXlXlXQ.uXxXkXlX",
"lXkXxXsX- v lXiXpXpXpXpXpXyXbXA.  ; , > > > > > > > < O & ,XgXiXpXpXpXpXiXhX-X7 qXvXkXlX",
"lXkXkXvXZ.Q.nXjXkXkXkXkXkXjXbX2X- W.3X=X;X;X;X;X;X-X1XE.b.lXkXkXkXjXjXkXkXkXxXP 3XnXkXlX",
"lXlXkXlXmXnXlXlXlXlXlXlXlXkXcXtX, 3XSXnXmXmXmXmXmXmXmXMXnXzXkXlXlXbXxXjXlXhXBX~ <XnXkXlX",
"lXkXkXzXpXsXzXkXkXkXkXkXkXkXvXwX> =XnXgXjXjXjXjXjXjXkXdXuXzXkXlXkX5XaXMXjXjXMXW <XnXkXlX",
"lXlXkXzXsXfXlXkXlXlXlXlXlXkXvXeX> ;XmXjXlXlXlXlXlXkXlXgXsXzXhXVXx.Z l ^.NXgXMXQ <XnXkXlX",
"lXlXkXzXsXfXlXkXlXlXlXlXlXkXvXeX> ;XmXjXlXlXlXlXlXkXlXgXsXzXkXzX7XDXC <.FXdXMXQ <XnXkXlX",
"lXlXkXzXsXfXlXkXlXlXlXlXlXkXvXeX> ;XmXjXlXlXlXlXlXkXlXgXsXzXkXhXGXx.Q kXzXhXMXQ <XnXkXlX",
"lXlXkXzXsXfXlXkXlXlXlXlXlXkXvXeX> ;XmXjXlXlXlXlXlXkXlXgXsXzXgXZXf.  X./.nXgXMXQ <XnXkXlX",
"lXlXkXzXsXfXlXkXlXlXlXlXlXkXvXwX> ;XmXjXlXlXlXlXlXkXlXgXsXzXjXnX'.v.i./.mXgXMXQ <XnXkXlX",
"lXkXkXzXpXaXhXgXgXgXgXgXgXfXlX9X: -XmXjXkXkXkXkXkXkXlXdXuXhXgXfXnXZXSXmXfXdXbXW <XnXkXlX",
"lXlXkXxXnXVXJXGXGXGXGXGXGXFXPXxX1 1XmXkXlXlXlXlXlXlXlXmXmXJXGXHXDXSXSXDXHXDXUX( ,XnXkXlX",
"lXkXlXlXO.o.z.d.f.f.f.f.f.d.j.e.. E.MXdXgXgXgXgXgXdXmXh.E k.d.f.f.f.f.f.f.f.h.z 6XbXkXlX",
"lXkXzXfXq : b l l l l l l l z k   n.nXuXsXsXsXsXsXiXnX/   b l l l l l l l z j w wXvXkXlX",
"lXlXgXKXP 7.UXCXDXAXCXZXDXDXFXCX<XlXzXzXzXzXzXzXzXhXJXk.b UXZXDXDXDXDXDXDXSXGX9XsXzXkXlX",
"lXkXgXJXH >.GXsXgXmXFXmXgXhXgXjXgXkXkXkXkXkXkXkXkXgXGXd.l ZXdXhXhXhXhXhXhXhXjXgXhXlXkXlX",
"lXlXgXJXH ,.KXfXvX_.e.'.cXkXkXlXiXkXlXkXlXlXlXlXlXgXGXf.l DXhXkXkXkXkXkXkXkXzXaXgXlXkXlX",
"lXlXgXJXH ,.JXfXxXZ.8.; XXNXhXlXpXkXlXkXlXlXlXlXlXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXgXJXH ,.KXdXvXfXO.k wXcXjXlXpXkXlXkXlXlXlXlXlXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXgXJXH ,.KXfXlX7XI.< T.CXhXlXpXkXlXkXlXlXlXlXlXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXgXJXH ,.JXgXjX+.R Z ,XbXjXlXpXkXlXkXlXlXlXlXlXgXGXf.l DXhXkXlXlXlXlXlXkXzXsXgXlXkXlX",
"lXlXgXJXH ,.KXfXzXyX,XlXnXjXlXlXiXkXlXkXkXkXkXkXkXgXGXf.l DXhXkXlXlXlXlXlXkXzXaXgXlXkXlX",
"lXkXgXJXJ ,.HXdXhXzXvXjXgXjXhXkXhXkXhXjXjXjXjXjXjXdXDXf.z SXhXkXkXkXkXkXkXkXlXhXhXlXkXlX",
"lXlXgXJXH 2.UXvXMXMXmXMXMXMXNXbX=XxXBXMXMXMXMXMXMXbXUXj.z GXjXzXzXzXzXzXzXlXvX4XsXzXkXlX",
"lXkXzXhXj a ) W Q Q Q Q Q W ! U 7 K ~ W Q Q Q Q Q W ( l w 9XgXaXsXsXsXsXaXhX4XM 0XvXkXlX",
"lXkXlXhXwX7X,X<X<X<X<X<X<X<X<X1XqX2X<X<X<X<X<X<X<X<X,X6XwXsXhXgXgXgXgXgXgXhXsX0XkXlXkXlX",
"lXlXkXlXvXbXnXnXnXnXnXnXnXnXnXnXvXnXnXnXnXnXnXnXnXnXnXbXvXzXlXlXlXlXlXlXlXlXzXvXlXkXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXkXxXlXkXkXkXkXkXkXkXxXlXkXkXkXkXkXkXkXxXkXhXhXhXhXhXhXhXzXlXkX",
"kXzXdXkXzXlXlXlXlXlXxXdXkXzXlXlXlXlXlXxXaXxXCXBXBXBXBXBXCXjXhXlX",
"xXdX2 B.MXiXsXsXsXdXfX0 g.NXiXsXsXsXsXhXV s J S S S S S D a 7XbX",
"lXkXB.,XvXhXgXfXhXjXzXA.*XbXhXgXfXhXgXZXP w.-X}. X X X|.XXL.yXcX",
"kXzXMXvXkXlXVXSXvXkXzXMXvXkXzXVXSXnXfXHX( T.UXmXBXBXBXBXVXmXjXlX",
"kXlXiXhXkXnXN.+.7XvXkXpXgXzXhXu.*.,XzXDX~ F.ZXfXjXjXjXjXkXaXgXlX",
"kXlXsXhXmX&XI 0.#.FXhXdXjXzXpXrX) e.AXSX~ H.SXhXlXlXlXkXlXdXhXlX",
"kXlXsXhXNXoXR m.{ FXhXdXjXjXNXP.! rXkXFX~ H.SXhXlXlXlXkXlXdXhXlX",
"kXlXsXjXkXvXe.E %XmXkXsXhXzXjXY Y ~.vXDX~ H.SXhXlXlXlXkXlXdXhXlX",
"kXlXdXjXkXlXMXnXnXjXlXfXgXhXgXbXjXfXsXSX! G.SXhXkXkXkXkXlXfXhXlX",
"kXxXfXzXzXlXjXkXkXlXcXaXMXDXSXAXSXSXVXUX] L.DXjXlXlXlXlXxXfXfXzX",
"xXdX0 Z.MXpXdXdXsXdXaXB n T P I I I P Q & t.BXiXdXdXdXsXjX] 2XnX",
"lXkXg.*XvXgXjXjXjXgXmXV e.{.Q.~.~.~.!.).j..XbXgXfXdXgXgXMX#.;XMX",
"kXzXNXvXkXlXlXlXlXhXDXT {.UXBXZXZXZXZXZXBXbXkXlXCXDXnXgXSX9.=XMX",
"kXlXiXhXlXkXkXkXkXhXSXP Q.BXfXhXhXhXhXjXpXfXlXzXz.,.<XzXCX4.=XMX",
"kXlXsXjXlXkXlXlXkXhXSXI ~.ZXhXlXlXlXkXlXdXhXzXsX5X| ,.SXBX5.=XMX",
"kXlXsXjXlXkXlXlXkXhXSXI ~.ZXhXlXlXlXkXlXdXhXjXmX.X~ 4XzXCX5.=XMX",
"kXlXsXjXlXkXlXlXkXhXSXI ~.ZXhXlXlXlXkXlXdXhXlXvXT Z R.vXCX5.=XMX",
"kXlXsXfXgXgXgXgXgXsXVXP !.ZXhXkXkXkXkXlXdXfXgXfXkXaXiXdXBX3.=XMX",
"kXxXhXZXHXGXGXGXGXSXUX! ).ZXjXlXlXlXlXcXhXBXJXGXGXHXHXAXUXr.*XNX",
"xXaXV J ( ~ ~ ~ ~ ! ' * x.NXpXdXdXdXdXjXR C ) ! ~ ~ ~ ~ / j 5XnX",
"kXxXk w.T.F.D.S.G.G.L.0..XbXgXhXhXhXfXBXG *.W.F.H.H.H.H.J.j.tXcX",
"hXCXJ -XUXAXIXUXGXAXDXVXbXkXlXlXlXlXgXJX) Q.UXCXSXSXSXSXDXBXjXlX",
"hXBXS {.MXdXn.r.4XzXhXiXgXlXkXkXkXkXgXGX! F.CXdXhXhXhXhXjXpXgXlX",
"hXBXS  XBXhX!.g K.ZXjXdXjXlXkXlXlXlXgXGX~ H.SXhXlXlXlXkXlXdXhXlX",
"hXBXS  XNXxX>Xb B.AXhXdXjXlXkXlXlXlXgXGX~ H.SXhXlXlXlXkXlXdXhXlX",
"hXBXS |.ZXwX7.W W.BXjXdXjXlXkXlXlXlXgXGX~ H.SXhXlXlXlXkXlXdXhXlX",
"hXBXD {.mXgX0XiXbXfXhXsXgXhXgXgXgXgXsXSX! H.SXhXkXkXkXkXlXdXhXlX",
"hXCXG *XUXVXFXSXCXZXSXkXMXSXZXZXZXZXBXUX_ K.DXjXlXlXlXlXxXkXgXlX",
"zXhXk } q.4.4.4.5.4.8.R #.8.4.5.5.5.3.r.i j.BXpXdXdXdXdXkX4.5XbX",
"lXhX8X:X*X=X=X=X=X=X*X,X;X*X=X=X=X=X=X*X3XtXjXgXhXhXhXhXhX5XhXlX",
"kXlXbXMXNXMXMXMXMXMXNXmXMXNXMXMXMXMXMXNXnXcXlXlXlXlXlXlXlXbXlXkX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"gXwXlXgXzXrXpXkXhXkXwX0X0X0X8XgX",
"wXF.xXcXMXE.@XMXbXyX#.x.z.x.h.eX",
"lXxXkX.XuXcXvX6X&XsXz.ZXnXMXbXjX",
"hXkX6XW ).vXzX).3.gXf.xXgXjXdXhX",
"zXmXhX(.eXnXHX<X%XNXx.bXkXlXcXlX",
"rXE.xXbXmX{.v.R.E.n.<.vXfXxX*XqX",
"pX#XzXaXVXV.B.&X X X#XkXdXVX/.:X",
"zXvXkXhXZXK.=XJXMXBXcXcXb.:X@X:X",
"kXhXxXkXSXJ.XXMXhXhXhXvX5.2X@X;X",
"jXuXiXeXxXV.XXNXjXkXuXyX2XgX(.>X",
"wX#.k.v.v.;.#XvXhXuX#.h.z.l.t.0X",
"0Xv.CX*XhXbXlXkXxXiXl.BXcXbXcXkX",
"0Xl.VX+._.bXdXjXlXyXh.cXhXkXfXhX",
"0Xm.SX/.pXVXmXNXVXkXz.bXkXlXzXkX",
"wX0..XOXXXQ.(.{.}.~.t.cXfXzX2XtX",
"jX5X;X-X:X;X:X>X>X:X0XkXhXkXtXfX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
