#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 86 1 ",
"  c #000000",
". c #0C0C00",
"X c #0C0C0C",
"o c #131302",
"O c #1C1C01",
"+ c #141414",
"@ c #1C1C1C",
"# c #2C2C01",
"$ c #3C3C03",
"% c #252525",
"& c #2B2B2B",
"* c #343434",
"= c #383838",
"- c #555531",
"; c #434343",
": c #4C4C4C",
"> c #515151",
", c #5B5B5B",
"< c #656565",
"1 c #6B6B6B",
"2 c #747474",
"3 c #7C7C7C",
"4 c #8F8F01",
"5 c #919100",
"6 c #97970D",
"7 c #ACAC00",
"8 c #B1B100",
"9 c #B5B50E",
"0 c #A3A328",
"q c #BDBD2D",
"w c #C7C700",
"e c #CDCD00",
"r c #D4D400",
"t c #DADA00",
"y c #D0D00A",
"u c #CDCD11",
"i c #D0D011",
"p c #DBDB13",
"a c #D2D22E",
"s c #CFCF33",
"d c #D4D435",
"f c #DBDB36",
"g c #D5D53D",
"h c #DFDF38",
"j c #D7D758",
"k c #848484",
"l c #8B8B8B",
"z c #9F9F89",
"x c #939393",
"c c #9E9E9E",
"v c #A1A1A1",
"b c #A2A2A8",
"n c #ACACAC",
"m c #B0B0AF",
"M c #B3B3B3",
"N c #BBBBB5",
"B c #BBBBBB",
"V c #D4D48B",
"C c #C8C89D",
"Z c #DDDD9D",
"A c #DFDFA1",
"S c #DBDBA9",
"D c #DFDFBF",
"F c #E2E2A4",
"G c #E1E1AC",
"H c #E1E1BF",
"J c #C2C2C2",
"K c #CDCDCD",
"L c #DDDDC1",
"P c #D2D2D2",
"I c #DDDDDD",
"U c #E2E2C5",
"Y c #E4E4CC",
"T c #F1F1CF",
"R c #E5E5D4",
"E c #E5E5DE",
"W c #E5E5E5",
"Q c #E6E6EB",
"! c #ECECEC",
"~ c #E7E7F2",
"^ c #E8E8F2",
"/ c #E7E7FB",
"( c #E8E8FF",
") c #F3F3F3",
"_ c #F5F5FE",
"` c #FDFDFD",
/* pixels */
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWEWWWIWWWWWIEEWWWEWWWWWWIWWWWWIWWWIWWWWWWIWWWWIWWWWWWIWWWWIWWWWWWIWWWWIWWWWWWIWWWWWWIIWWWWWQW",
"WWW!_)))))))))_)))_)))))_)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))_))))`))WWWW",
"WW!KxcvcccvcccccccccccccccccccvcccvcvcccccvcccvcvcccccvcccvcvcccccvcccvcvcccccvcccccccccvvxnWWWW",
"WW_c                                                                                       &)WWW",
"WW)c +=================*===*=**================*======**=========*=====*=======X &========*,!WWW",
"WI)c =`!)^!))^)))^)!)))))!))!II))))!^)))!)!))))))!)!)!IP!))!^)))))^!)))))!)!)!`= n`!^!))!))!WWWW",
"WW)c =)WWWWEWEWWIWWWEWWWWWWWIKKIIWEWWWIWWWWWIWWWWWWWWWKKIWEWWIWWWWWWEWWWWWWWWI!= c)EWWEWWEWWWWWW",
"WW)c =!WWW!WWWWWWWWWWQWQWWWWWKPWWWWWWWW!WWWWWWWWWWWWWWPKWWWWWWQWWQWWWWWWWWWWWW!* v)WWWW!WWWWWWW!",
"WW)c =)WWWWWWWWWWWWWWWWWWWWWIKPWWWWWWWWWWWWWWWW!QWWWWWPKWWWWWWWWWW!WWWWWQWWWWW)* v)WWWWWWWWWWWWW",
"WW)v =!WWWWWWWWWWWWWWWWWWWWWWKPWWWQWWWWWWWWWWWWWWWWWWWPKWWWWWWWWWW!WWW!WWWWWWI)= v)WWWWWWWW!WWWW",
"WW)c =)WWWWWWWW))))WWWWWWWWWWKKWWWWW!WQWWWW!W!WWWWWWWWPKIWWWWWWQWWWWWWWWWWWWWW!* v)IW!WWWWWWW!WW",
"WI)c =)IWWWWWWImxlvWQWWWWWWWWKKWWWW!WWWWWWW!WWWWQWWWWWPKWWWWWWWWWWWWWWWWWQWWWW!* v)WWWQWWWW!WWWW",
"WW)c =)WWWWWW!*    &K!WWWWWWWKPWWWWWWWWWWWWWWWWWWWWWWWPKWWWW!WWWWWWWWWWWWWWWWE)* v)IWWWWWQWWWWWW",
"WW)v =)WWWWWWW*,b3X <)WWQWWWIKPWWWWWWWWW!WWWWWWWWQWWWWPKWWWWWWWWW!WWW!!WWW!WWW!* v)WWQWW!WWWWWWW",
"WW)c =)WWWWWWWI)!`: :!WWWWWQWKPWQWWWWW!WWWWWWW!W!WWWWWKKEWWWW!WWWWWWWWWWWWWWWW^= v)WWWWWWWWWWWW!",
"WW)v =)WWWWWWWWEQI& k)WWWWWWWKKWWWWWWWWWWWWWWWWWWWWWWWPKEWWWWQQW!WWWWWW!WWWWWI)* c)WWW!WQWWWWW!W",
"WI)c =!WW!WWWWW!I; :WWWWQWWWWKPWWWWWW!WWQWWWWW!WWWWWWWPKWWWWWWWWWWWWWWWWWWWWWW!= v)EWWWWWWWWWWWW",
"WW)c =)WWWWWWW)K& >WQWWWQWWWEKKWWW!WWWWWW!!WWWWWWWWWWWPKEWWWWWWWWWWWWWWWWWWWWW!= v_EWWWW!WWWWWWW",
"WW)c =!WWQWWW!N@ 1)QWWWWWWWWWKPWWWWWWWWWWWWWWWWW!WWWWWPKIWWWWWQWWWW!!WWWWWW!WW!* v)WWWWWWWW!WWWW",
"WE_c =)WWWWWWW& X;-&<WWWWWWWWKPWWWWQWWWWWWWWWWWWWW!WWWPKWWWWWWWWWWWW!WWWWWW!WW)* v)WW!WWWWWWW!WW",
"WW)c =!WWQWWWW%     =WWWWWWWWKPWWW!WWW!WWWWWWW!WWWWWWWPKWWWW!WWWWWQWWWWWWWWWWW!* v)WWWWWWWW!WWWW",
"WW)c =^WWWWWWWIPPIIPIWWWWWWWIKKWWWWWWW!WWW!WWQWWWWWWWWPKWWWWWWWWWWWWWWQW!WWWWW!= v)WWWW!WWWWWWW!",
"WW)c *)WWWWWWWQQ!QQ!WWWWWWWWWKPWWWWWWWWWWWWWWWWWWWWWWWPKEWWWWW!WW!WWWWWWWWWWWE!= v)IWWWWWWWWWWWW",
"WW)c =)WWWWWWWWWWWWWWQWWWQWWWKKWWWWWWWWWWWWWQWWWWWWWWWPKWWWWWWWWWWWWWWWWWWWWWW!* v)WWWWWWWWWWQWW",
"WE)c =!WWWWWWWWWWWWWWWWWWWWWIKPWWWWWWW!WWWWWWWWWWWWWWWPKWWWWWWWWWWQWWWWWWWWWWW)* v)IWWWQWWWWWQWQ",
"WW)c =)WWWWWWWWWWWWWWWWWWWWWWKKWWWWWWEWWWWWWWWWWWWWWWWKKIWEWWWWWWWWWWWWWWWWWWI!= v)WWWWWWWWWWWWW",
"WW)c =)WWQWWWWWWWWWWWWWWWQWQWPI!)!!!!)!!!)!^)!!!!)^!!!IPQ)!!!!)^!!!!)!!!!!!)!Q`= b_WQ~Q!QQQ~WWWW",
"WW_c =)IWWEIWWWWWIWWIWWIWEWWInMJJJJJJJJJJJJJJJJJCJJJJJMnJJJJCJJJJJJJJJJJJJJJJJK& zTLULUUUUUUWWWW",
"WW)c *PKKKKKKKKKKKKKKKKKKKKPn                                                    4teeeeeeeea!WWW",
"WW)c *IKKPPPKPKPPPPKKPPPPKKIn  +++++++++++++++++++@+++.o++++++@++++++++++++++++o 6puiiiiiiyg!WWW",
"WI)c =!WWWWWWWWWWWWWWWWWWWW!J +IIWWIWIIWIIWIWWIIQIIQIEuwLQIIQIIQWIWIIWIWIEIWIIQseZ!EWWEWEEWWWWWW",
"WW)c =!WQWWWWWWWWWWWWWWWWWW^J +WQW!WWWW!WWWWWWQQWWQWQEieU^WWWQWWWW!WWWWW!WWWWW^deA~WWWWWWQWWWWWW",
"WW)c =)WWWWWWWWWWWWWWWWWWWW!J +IWWWWWWWWWWWWWWWWWWWWWEirUQWWWWWWWWWWWWWWWWWWWE!deA~WWWWWWWWWW!W!",
"WW)v =)WWWWWWWWWWWWWW!WWWWW!J +WWWWWWWWWWWWWWWWWW!WWWWurUQWWWWWWWWWQWW!WW!WWWW~deA~WWWWWWWWWWWWW",
"WW)c =!W!WWWWWWWWWWWWWWWWWW!J +IQWWWWWWWWWWWWWWWWWWWWEieU~WWWWW!WW!WWWWWWWWWWW~deA~WWWQWWWWWWWWW",
"WI)c =)IWWWWWWW!))!WWWWWWWW)J +WWWWWWWWW!)^)WWWWWWWWQEieU!WWWWW!WWWWWWWWWWWWWW^deA^WWQQWWWW!!WWW",
"WW)c =)WWWWWWWWPNMJQWWWWWQW!J +W!WWWWWWWKNNBE!WWWWWW!EieUQWWWWWWW!WWWWWWWWWWWWQdeA^WWWWWWWWWWWQW",
"WW)v =)E!WWWWQ>   .>IWWWWWW!J +IWWWWWW)l    &M!WWWWWWEieUQWWWWWWWWWWW!W!WW!WWW!deF^WWWWWWWWWWWWW",
"WW)c =)WWWWWWW%*k>  2)WWWWW!J +IWWWWWW)k;31+ ;QWWWWWWEirUQWW!WWWWWWWWWWWWWWWWW!deZ^WWWWQW!WWWWWW",
"WW)v =)WWW!WWWJ!^); :!WWWWW)C +QWWWWWWWW_``, =!WWWWWQEieU~WWWWWWWWWWWWWWWWWWWW^deA~WWWQ!WWWWWWWW",
"WI)c =!WWWWWWWQWWQ= 2)WWWWW!J +IQWWWWWWQN,:X+n)WWWWWWEieUQWWWWQWWWW!WWWWWQWWWW~deA~WWWWWWWWWWWW!",
"WW)c =)WWWWWWWEW!< &IWWWWWW!J @IWW!WWWW)c   &J!WQWWWQEieUQWWWWWWWWWWWW!WWWWWWWQdeA~WWWWQWWWWWWWW",
"WW)c =!WWWWWWW!W: *PWWWWWWW!J +QWWWWWWWWIIK: *WQWWWWWEueU~WWWWQWWW!WWWWWW!WWWE^deZ~WWQWWWWW!W!WW",
"WE_c =)WWWWWWQP= >Q)QWWWQWW)J +W!WWWWWWI))`x XJ!WWWWWWirUQWWWQWWWWWWWWWWWWWWWWQdeA~WWWWWWWW!WWWW",
"WW)c =!WWW!WWQ= X,1,kWWWWWW!J +IWW!WWWE=:3<+ =WWWWWWWEieUQWWWWW!!WWWWWWWWWWWWWQdeA~WWWWWWWWWWWWW",
"WW)c =^WWWWWWW%     *WWWWWW!J +WWWWWWWW:   X=J!WW!WWWWieU!WWWWWWWQWWW!W!WW!WWW~deA~WWWWW!WWWWWWW",
"WW)c *)WWWWWWWBMMNNMJWWWWWW!J +IWWWWWWWWKNNJ!!WWWWWWWEieUQW!WWWWWWWWWWWWWWWWWWQdeA~WWWWWWWWWWW!W",
"WW)c =)WWWWWWW)))^))!WWWWWW!J +IWWWWWWWW!!)!WWWWWWWWWWyeU!WWWWWWWQW!WWWW!WWWWE!deA^WWWWWWWWWQWWW",
"WE)c =^WWWWWWWEWWWWWWWWWWWW!J +W!WWWWWWWWWWWWWWWWWWWWEieU~WWWWWWWWWWWWWWWWWWWW~deA^WWWQWWWW!WWWQ",
"WW)c =)IWWWWWWWWWWWWWWWWWWW!J +EWWWWWQWWWWWWWWWWWWWWWWueUQWWWWWWWWWWWWWWWWWWWW^deF^WWWWWWWWWWWWQ",
"WW)c =)EWWWWWWWWWWWWWWWWWWW)J +IWWWWWWWWWWWWWWWWWWWWWEieUQWWWWWWWWWWWWWWWWWWWW^deZ^WWWWWWWWWWWWW",
"WW_c =)WWWWWWWWWWWWWWWWWWWW!J +WQWQWWWWWWWWQWWQWQWWWQWurU^WW!WWWQWQWWWWW!WWWQW~deA~WWWQWQW!WWWWW",
"WW)c =)WWWWWWWWWWWWWWWWWWWW!J +IEEEEWEWEEEEWEEWEEEEEWRuwUWEEWEEWEEEEWEEWEEEEEEWdwZQEEEWEEEEEWWWW",
"WW)c *IKPPPKKPPKKPKPPKKPKPKIm ouiuiiuiiiiuyiuiiuiuiiiuO.9puiiuuiiiiuiiiiiiiiiui$ 6puuiiiiuygQWWW",
"WI)c *PKKKPKKKPKPKKPKKKKKKKPn oererrreeeeerereeerreerw. 8reeereeeeeereeereeeret# 5teereeerea~WWW",
"WW)c =!IWWWIWWWIWWEWIWWWWIW!J XLUUUUUUUUUUUUUUUUUUUUUH98SYUUUUUUUUUUUUUUUUUUUUYq7VRLUUUUUUUYWWWW",
"WW)c =)WWWWWWWWWWWWWWWWWWWW!J +W^QQQQ~~Q!QQQQ~~QQQ!Q^WirY~QQ~QQ~QQ!Q~QQQQQ~WQQ/frG(WQ~QQQQ!WWWW!",
"WW)v =)WWWWWWWWWWWWWWWWWWWW!J +WWWWWWWWWWWWWWWWWWWWWWEieUQWWWWWWWWWWWWWWWWWWWWQdeA~EWWWWWWWWWWWW",
"WW)c =!WWWWWWWWWWWWWWWWWWWW!J +IQWWWWWWWWWWWWWWWWWWWQEueUQWWWWWWW!WWWWWWWWWWWW^deA~WWWWW!WWWWWWW",
"WI)c =)WWWWWWWWWWWWWWWWWWWW!J +IWWWWWWWWWWWWWWWWWQWWQEirU!WWWWWWWWWWWQWWWQWWWWQdeA^WWWWQWWWWQWWW",
"WW)c =!WQWWWWWWQWQWWWWWWWWW^J +WQWWQWWWWWQ!WWWWWWWWWWEieU!WWWWWQWWWW!WWWWWQWWWQdeF^WWWWWW!WWWWWW",
"WW)v =)EWWWWWWQWIPI)QWWWWWW)J +EWWWWWWWQWIPI!!WWWWWWWWueUQWWWQWW!WWWWWWWWWWWWW~deA^WWWQWWWWWW!WW",
"WW)c =)WW!WWW!3+  @<I!WWWWW!J +E!WWWWE)c@  +>K!WWWWWWEieU~WWWWWWWWWWWWW!WWWWWWQdeA^WWWWWWWWWWWQW",
"WW)v =)WWWWWW)>%>=  2)WWWWW!C @QWWWWWW)3@:-  >)WWWWWQEirUQWWWWWQWWWWWWWW!WWWWW~deA~WWWQWWWWWWWWW",
"WI)c =!W!WWWWWI!`)= ,)WWWWW!J +IWWWWWWWIW``, =WWWWWWWEueUQWWWWWW!W!WWWWWWWWWWW!deA~WWWWWW!!WWW!W",
"WW)c =)WWWQWWW!Nl1XXn!WWWWW)J +I!WWWWWW!Kl3@ l!EWWWWQEieU~WWWQWWWWWWWW!WWWWWWE!deA~WWWWWWWWWWWWW",
"WW)c =!WWWWWWW)2   ,WWWWWWW^J +QWWWWWWW)c   =IQWWWWWWEieUQWWQWWWWWWWWWWWWWW!WW^deZ~WQQWWWWWWWWWW",
"WE_c =)WWWWWWWWKMx@ 1!WWWWW!J +WWWWWWWWWPBb* ;WWWWWWQEirUQWWWWWWWWWWWWWWQWWWWW~deA~WWWWWWWWWW!WW",
"WW)c =!WWWWWWW!```1 &WWWWWW)J +IQWW!WWWQ)_`x +K!WWWWWEieU!WWWWW!WW!WW!WWWWWWWW~deA~WWWWWW!WWQWWW",
"WW)c =^WWWWW!K:kbk@ ;!WWWWW!J +IWWWQWWI,2bx& &IWWWWWWEieUQWWWWQWWWWWW!WWWWWWWEQdeA~WWWWWWWWWW!WW",
"WW)c *)WWWWWQK+    &J!WWWWW^J +WWWWWWWE*    @b!WWWWWQEieUQWWW!WWWWWWWWWWWWWWWW~deA~WWWWWWWWWWWWW",
"WW)c =)EWWWWWWKvxxnW^WWWWWW!C @QWWWWWWWPnxxvI!WWWQWWWWyrUQWWWWWWQ!WWWW!WWWWWWE!deZ^WWQWWWWWWWWWW",
"WE)c =)WWWWWWWW))))WWWWWWWW!J +IWWWWQWW!)_))WIWWWWWWWEieU~WWW!WWWWWWWWWWWW!QWW~deF^WWWWWW!!WWW!W",
"WW)c =)WWWWWWWWWWWWWWWWWWWW!J +IWWWWWWWWEEWWWWWWWWWWWWurU~WWWWWWW!WWWWWWWWWWWWQdeA^WWWWWWWWWWWWW",
"WW)c =^IWWWWWWWWWWWWWWWWQWW)J +QWWWWWWWWWWQWWWWWWWWWWEieUQWWWWWWWWWWWWWWWWWWWW^deA^WWWWWWWWWWWWW",
"WW)v =)WWWWWWWWWWWWWWWWWWWW!J +IWWWWWWWWWWWWWWWWWWWWWEueUQWWWWWWWWWWWWWWWWWWWE^deA~WWWWWWWWWW!WW",
"WW)c =)IWWEWWIWEWWIEEWIWIWW!J +IWWWWIWWEWWWIWWWWWWEWWEueUQWWWWWWWWWWWWWWWWWWWWQdwA~EWWWEWWWWWWWW",
"WW)c =`!^)!)^))))))^!))!!)^`K +^)!)!)!)!))!^!!)!)))!^!prU~WWQQWWWWW!W!WW!!W!WW^hrG(Q!~~~QQ^!WWWW",
"WI)c +=*==**=*&=***==****=*=& .=**=**=*****=*=*=****=*##NIPPPPIPPIPPPPPIPPPPPPI-O0hdddddddaj!WWW",
"WW)c                                                    mPKKKKKKKKKKKKKKKKKKKKP& 4reeeeeeeesQWWW",
"WW)c &nvvvvvvvvvcvvvvcvvvvvvclxvvvvvvvvvvvvvvcvvvvvcvcX JWIIIEIEIIIWIEIEIIIWIEWclCFAFFAAAAZSWWWW",
"WW)v =`))))))))))))))))))))))II)))))))))))))))))))))_!+ J^WWWWWWWQWWWWWQWQWWWW!EIQ~~^^^^~~~~WWWW",
"WW)c =!IWWIEWWEWIEWWWEWWWWWIIKKWEWWWWWWIWIWWWEWWWWWEWI+ J)WWWWWWWWWWWWWWWWWWWWWPKIWWEWWWWWWWQWWW",
"WW)c =)WWWWWW!WWWWWWWWWWQWWWWKKWWWWWW!WWWWQWWWW!WWWWQE+ J)WWWWQWWWWQWWWWWWWWWWWPKIWWWWWWWWWWWWWW",
"WI)c =!WWWWWWWWWWWWQW!!WWWWWWKKWWWWWWWWWWWWWWWWWWWWWWIX J)WWWWW!WWWWWWWWWWWWWW!PKIWWQWWWW!WWWQWW",
"WW)c =)WWQWWWWW!QWWWWWWWWWWWWKPWWWWWWWWWWQWW!WWWWWWWQE+ J!WWWWWWWWWWWEWWWWWQWW!PKIQWWW!WWWWWW!WW",
"WW)v =)WWQWWWWWWQWWWWWWWWWWWIKPW!WWWWWWWWWWWWWWWWWWWQEX J!WWWWWWQ)!!!)!WWWWWWWWPKIWWWWWWWWWWWWQW",
"WW)c =)WWW!WWWWWWWWWWW!QWQWWWKPWWWWWWWW!WWWWWWQWWWWW!I+ J)WWWWWQB,&@*2IQWWWWWW!PKEWWWWWWWWWWWWWW",
"WI)c =^WQWWWWWWWWWWWWWWWWWWWEKPWWWWWWWWWWWWWW!WWWQWWWE+ J!WWWWE)2 @@  >!WWWWWWWPKEWWW!WWW!!WWW!W",
"WW)c =)WWWWWWWWW!WWWWWWWWWW!WKKWWWQW!WWWW!!WWWWWWWWWWI+ J)WWWWW)vcWW< +K!W!WWWWPKIWWWWWWWWWWWWWW",
"WW)n+,!WWWW!W!WWWW!WWWWWWWWWWPPW!WWWWWWWWWWWWWWWWWQWQW=%K!WWWWWW!)W)m@-PWWWQWWWIPI!WWWWWWWWWWWWW",
"WWWQ)!WWWWWWWWWWWWWWW!WWQWWWWWWWWWWWWWWWWWWWWW!WWWWWWW)!!WWWWWWWWWWWQ^!WWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWW!WWWWWW!WWWWWWWWWWWWWWWWWWWWWW!WWWWWQWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW!WW!WWW!WW",
"WWWWWWWW!WWWWWWWWWWWWWWWWWQWWWWWW!WW!W!WWWWWWW!WWWWWWWWWWWWWWW!WWWQWWWWWWWWWQWWWWWWWWWWWWWWWW!WW",
"WWWWWWWWWWWWWW!WWWWWWWW!WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW!WQWWWWWWWWWW!WWWWQQWWWWW!WWWWWWQWW"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 94 2 ",
"   c #000000",
".  c #0B0B0B",
"X  c #131313",
"o  c #1B1B1B",
"O  c #353500",
"+  c #3F3F01",
"@  c #242424",
"#  c #2C2C2C",
"$  c #353535",
"%  c #3D3D3D",
"&  c #4C4C00",
"*  c #525202",
"=  c #42421A",
"-  c #7A7A1C",
";  c #464635",
":  c #464646",
">  c #484847",
",  c #47474C",
"<  c #4B4B4C",
"1  c #5B5B49",
"2  c #525252",
"3  c #5C5C5C",
"4  c #5D5D61",
"5  c #636363",
"6  c #6D6D6D",
"7  c #747474",
"8  c #7C7C7C",
"9  c #8A8A00",
"0  c #929200",
"q  c #9A9A00",
"w  c #828221",
"e  c #AEAE3A",
"r  c #B4B43D",
"t  c #C7C700",
"y  c #CBCB00",
"u  c #D7D700",
"i  c #DADA00",
"p  c #888857",
"a  c #ABAB4E",
"s  c #B4B445",
"d  c #A0A07D",
"f  c #D5D546",
"g  c #D6D64A",
"h  c #D7D751",
"j  c #DFDF56",
"k  c #D6D65B",
"l  c #D8D85C",
"z  c #E1E14D",
"x  c #E3E356",
"c  c #E2E259",
"v  c #DFDF61",
"b  c #CCCC7C",
"n  c #E1E162",
"m  c #848484",
"M  c #8B8B8B",
"N  c #91918E",
"B  c #949494",
"V  c #9B9B9B",
"C  c #A1A19F",
"Z  c #A4A4A4",
"A  c #A5A5AD",
"S  c #ACACAC",
"D  c #B2B2AF",
"F  c #B6B6B6",
"G  c #B7B7B8",
"H  c #BEBEBE",
"J  c #CFCF83",
"K  c #C9C99F",
"L  c #DFDFA4",
"P  c #DEDEAB",
"I  c #DDDDB3",
"U  c #E4E4A5",
"Y  c #E0E0AD",
"T  c #EEEEAF",
"R  c #E2E2B5",
"E  c #E3E3BA",
"W  c #EFEFB9",
"Q  c #C4C4C4",
"!  c #CBCBCB",
"~  c #D6D6D6",
"^  c #DCDCDC",
"/  c #E3E3CA",
"(  c #F2F2C4",
")  c #E4E4DE",
"_  c #E5E5E5",
"`  c #E6E6EC",
"'  c #EEEEEE",
"]  c #E7E7F5",
"[  c #E8E8F6",
"{  c #E7E7F8",
"}  c #E8E8FE",
"|  c #F3F3F3",
" . c #F6F6FF",
".. c #FBFBFB",
/* pixels */
"_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` _ _ _ ",
"_ _ _ _ _ _ _ _ _ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ _ _ _ _ _ _ ^ _ _ _ _ _ _ _ ",
"_ _ _ _ } [ | [ ' ' ' ' [ { [ ' ' ' | ' [ { [ ' ' ' ' | ' ' | ' [ { [ ' [ { ' [ ' ' | ' [ { [ ' ' ' ' | ' ' | ' [ { [ ' [ { ' [ ' ' | ' [ { [ ' ' | _ | | ' ' ' ' [ ' { _ _ _ _ ",
"_ _ _ _ H H K H H H H H Q H Q K H H H H K Q Q H H H H H H H H H K Q Q H Q H Q K H H H H K Q Q H H H H H H H H H K Q Q H Q H Q K H H H H K Q Q H H G H H H H H H H H K Q _ _ _ ` ",
"_ _ [ H                                                                                                                                                                 H ' _ _ ",
"_ _ ' H   X % % % % % % % % % % % % % % % % % % % % % $ % % % % % % % % % % % % % % % % % % % % % % $ $ % % % % % % % % % % % % % % % % % % % : #   o : % % % % % % % $ Q ' _ _ ",
"_ _ ' H   ; ..| | | | | | ' | | | | | ' | | | | | | ' ~ ^ | | | | | | | | ' | | | | | ' | | | [ | ' ~ _ | | | | | | | | | ' | | | | | ' | | | ..S   5 ..' | | | | | | | _ _ _ _ ",
"_ _ ' H   % | ^ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ _ _ _ _ ^ ! ~ _ _ ^ _ _ ^ _ _ _ _ _ ) _ _ _ _ _ _ _ _ ^ ! ~ _ _ _ ^ _ _ ^ _ _ _ _ _ ^ _ _ _ _ _ ^ | Z   3 | ^ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ ^ ! ~ ' _ _ _ _ _ _ _ ` _ _ _ _ _ _ _ _ _ _ _ _ ! ^ _ _ _ _ _ _ _ _ _ ' _ _ _ _ ' _ _ _ ^ | Z   3 | _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ ' _ _ _ _ ^ ! ~ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | Z   3 ..^ _ ' _ _ _ _ _ _ _ ' _ ",
"_ _ | H   % | _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ ' _ ' _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ ' _ _ _ | Z   3 | _ _ _ _ _ ' _ _ _ _ _ _ ",
"_ _ ' H   % ' _ _ _ _ _ _ [ _ ^ ~ _ | _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` ^ ! ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` _ | Z   3 | _ _ _ ` _ _ _ _ _ _ ' _ ",
"_ ^ [ K   % | _ _ _ _ _ ' M o     @ B ' _ _ _ _ _ ' ^ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' ` _ _ _ ! ~ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | Z   3 ..^ _ _ _ _ _ _ _ _ ` _ _ ",
"_ _ { Q   % | _ _ _ _ _ ..2 o 7 :     G [ _ _ _ _ _ _ ! ^ _ _ _ ' _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ ` _ _ _ _ _ ' _ _ _ _ _ _ _ ) | Z   3 | _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ [ Q   % | _ _ _ _ _ _ ! _ .._ #   B | _ _ _ _ ' _ ! ~ _ _ _ _ _ _ _ _ ' _ _ _ ' _ _ _ _ _ _ _ ^ ! ~ _ _ ' _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ | Z   3 | _ _ _ _ _ ' _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ ) ' ~ X   Q ' _ _ _ _ _ ^ ! ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ | Z   3  .^ ' _ _ _ _ _ _ _ _ ' _ ",
"_ _ [ Q   % | _ _ _ _ _ _ _ | ! $   m | _ _ _ _ _ _ _ ! ~ ' _ ` _ ' _ _ _ _ _ ' _ _ _ ' _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ | Z   3 | _ _ _ _ _ _ ' _ _ _ _ _ ",
"_ _ { H   % | _ _ _ _ _ _ | Q o   B .._ _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ ' ^ ! ~ ' _ _ _ ' _ ' _ _ _ _ _ _ _ _ _ _ _ _ | Z   3 ..^ _ _ _ _ _ _ _ _ _ _ _ ",
"_ ^ [ Q   % | _ _ _ _ _ ' S X   M ^ Q ^ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ^ _ _ ` _ _ _ _ _ _ _ ' _ _ _ ' _ _ _ _ | Z   3 | _ _ _ _ _ _ _ _ ' _ ' _ ",
"_ _ ' K   % | ^ _ _ _ _ | <           8 | _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ ' _ _ _ ' _ _ _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' ^ | Z   3 .._ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ ' B 3 5 3 5 3 S [ _ _ _ _ _ _ ! ~ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | Z   3 .._ _ ' _ ` _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ |  .| ..| ..' _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ ` _ _ _ _ _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ ` _ _ _ ' _ _ _ _ _ | Z   3 | ^ _ _ _ _ _ _ _ _ ' _ _ ",
"_ _ | H   % | _ _ _ _ _ _ _ _ _ ) ^ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ ` _ _ _ _ _ _ _ _ _ ' _ _ _ _ ' _ ! ~ _ _ _ _ _ ' _ ' _ _ _ ' _ _ _ _ _ _ ^ | Z   3 .._ _ _ _ _ _ ' _ _ _ _ _ ",
"_ _ ' H   % | ^ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ ^ ! ~ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | Z   3 | ^ _ _ _ _ _ _ _ _ _ _ _ ",
"_ ^ [ K   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' ^ ! ~ _ _ _ _ _ _ _ ) _ _ _ _ ^ _ ) _ _ _ _ _ ^ Q ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ^ ) _ _ _ ' Z   3 ..) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ { Q   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ~ ^ | ' | [ | | ' | ' ' ' | | | [ ' ' ' | | ' ~ ) | [ ' | ' [ ' | ' ' ' ' | | | [ | ' ' ..S   3  ._ ] ` ] [ [ ' [ _ _ _ _ ",
"_ _ [ Q   % | ^ _ ^ _ _ _ _ ^ _ _ _ _ _ _ _ ^ _ ^ _ ~ V S F F F F G G G F F F F G F G G G G F F F F C S F F G G G G F F F F G F F F G G F F F Q m   1 ( I I R R R R R R _ _ _ _ ",
"_ _ ' H   $ ~ Q ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ~ C                                                                                               & i t y y y y y y t E ` _ _ ",
"_ _ [ Q   $ ^ ~ ~ ~ ^ ~ ~ ~ ~ ~ ~ ~ ~ ^ ~ ~ ^ ~ ~ ^ S   o > : : > , : : : > > > : : : > > : : : : ; + = : : : > > > : : > > > > : : : , : : : : ; O - z f f f f f f f f / ` _ _ ",
"_ _ { H   % | _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ | F   < ..| | | | | | | | | | | | | | | | | |  .W i x  .| | | | | | | | | | | | | | | | | |  .T i n } ' [ ] ] [ [ [ [ _ _ _ _ ",
"_ ^ ' Q   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | F   > | ^ _ _ _ ^ _ _ _ _ _ _ _ ^ _ _ _ ) ) ] P t h ] ^ _ _ _ _ ^ _ _ _ _ _ _ _ ^ _ _ _ ) ` L t k ] ) ) _ ) _ _ _ _ _ _ _ _ ",
"_ _ [ K   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ F   > | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] Y t h ] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] U t l ] _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ | F   > | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ Y y h [ ) _ _ _ _ ' _ _ _ _ _ _ _ ' _ _ _ _ [ L y l [ ) _ _ ' _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | ) _ _ _ _ _ _ ` { _ _ _ _ _ _ _ _ _ | F   : | ^ _ _ _ _ _ _ _ ' ' _ _ _ _ _ _ _ _ [ Y y h [ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ ) ] L t l [ _ _ _ _ _ _ _ _ _ _ ' _ ",
"_ _ | H   % | _ _ _ _ _ _ [ ` ! ! _ | _ _ _ _ _ ^ | G   : | _ _ _ _ _ _ _ ^ ~ ! ^ ' _ _ _ _ _ _ ] P y h { _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ ] U t l [ ) _ ' _ _ _ _ ' _ _ _ _ ",
"_ _ ' H   % [ _ _ _ _ _ | m X .   o M ' _ _ _ _ _ | G   , | _ _ _ _ _ | B .     o m _ _ _ _ _ _ ] P u h [ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ ' _ [ L y l { _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ ^ [ K   % | _ _ _ _ _ ..2 @ p >     G ' ) _ _ ^ ' F   > | _ _ _ _ _ ' m > 8 2     F ' _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ L t l ] _ _ _ _ _ _ _ _ _ ' _ _ ",
"_ _ { Q   % | _ _ _ _ _ _ ! _ | ' #   B [ _ _ _ _ | F   > | _ _ _ _ _ _ _ ....^ o   F ' _ _ _ ) ] Y y h [ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ ) ` U y l { _ _ _ _ ' _ _ _ _ _ _ _ ",
"_ _ [ Q   % | _ _ _ _ _ _ ' ) ' ! X . Q ' _ _ _ _ | F   : | _ _ _ _ _ _ ' V @ o   7 ' _ _ _ _ _ ] Y y h [ _ _ _ _ ' ' _ _ _ _ _ _ _ _ _ _ _ _ [ L y l [ ) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ ) [ ! @   M | _ _ _ _ ^ | F   : | ^ _ _ _ _ _ ' V # o   < ^ _ _ _ _ _ ] Y y h ] ) _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ ` L t l [ _ _ _ _ _ _ _ ' _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ | G o   Z .._ _ _ _ _ _ ' G   > | _ _ _ _ _ _ | | ..' $   M | _ _ _ _ [ Y y h [ ) _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ [ U y l { _ _ _ _ _ _ _ ' _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ ' S X   M ~ G ~ _ _ _ _ ) | F   > | _ _ _ _ _ _ B F ~ G @   M | ) _ _ _ [ Y y h [ _ _ ' _ _ _ _ ' _ _ _ _ _ _ _ _ _ ) [ L y l { ) _ _ _ _ _ _ _ _ _ _ ' ",
"_ ^ ' H   % | _ _ _ _ _ | 2           8 | _ _ _ ) [ G   > | _ _ _ _ _ _ #         $ ~ _ _ _ _ _ [ Y y h [ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ ' _ [ L t l { _ _ ' _ _ _ _ _ _ _ _ _ ",
"_ _ | H   % | ^ _ _ _ _ ' B 5 6 6 6 5 F ' _ ' _ _ | F   > | _ _ _ _ _ _ H m 7 7 V _ _ _ _ _ _ _ ' Y y h [ ) _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ ) [ U y j [ ) _ _ _ ' _ _ _ _ ' _ _ ",
"_ _ | H   % | _ _ _ _ _ _ [ ..| | ....[ _ _ _ _ _ ' G   : | _ _ _ _ _ _ ' | | | | _ _ _ _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ _ _ ' _ _ _ ' _ _ ) ] L t l { _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ _ ) _ _ ) _ _ _ _ _ ) [ G   : | ) _ _ _ _ _ _ _ _ ) _ _ _ _ _ _ _ _ ] P y h [ ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] L t l [ ) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' F   : | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ Y y h [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] U y l { _ _ _ _ _ _ _ _ _ ' _ _ ",
"_ _ ' H   % | ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | G   > | ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ) ) ` Y t h [ ) _ _ _ _ _ _ _ _ _ _ _ _ _ ) _ _ _ ` L t k [ ) ) _ _ _ _ _ _ _ _ _ _ ",
"_ ^ [ K   % | _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ ` _ | F   ,  .] ] ' [ [ [ ` ] [ [ ' [ [ [ ] ] ] ' } E i x } ' ] ] ] ] [ [ [ ' ] ] [ [ [ ' ] ] ` } Y i n } ' ] ] ] ' [ [ [ _ _ _ _ ",
"_ _ { Q   % ' ^ ^ _ _ ^ _ ^ _ _ ^ _ ^ _ ^ _ ^ _ ^ ' F   ; W P P P Y Y Y Y Y Y Y P Y Y Y Y Y P Y E J 0 r E Y P P Y Y Y Y Y Y P P Y Y Y Y P P P E b 0 s E Y Y P Y P Y Y Y ) ' _ _ ",
"_ _ [ Q   $ ~ ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! Q ~ V   + i t t t y y y y y y y t y y y y y y t u q   & i t y y y y y y y y t y y y y y t y y i 0   * i t y y y t y y t I ] _ _ ",
"_ _ ' H   $ _ ~ ^ ~ ~ ^ ~ ~ ~ ~ ~ ^ ~ ~ ~ ~ ^ ~ ~ _ S   = x h h h h h h h h h h h h h h h h h h j r O - c g h h h h h h h h h h h h h h h h h x r O w x h h h h h h h g / ] _ _ ",
"_ _ [ Q   % | _ _ ' _ _ _ _ _ ' _ ' _ _ _ ' _ _ _ | G   ,  .` ] [ [ [ ] ] ] ] [ [ [ ] ] [ [ [ [ } E i c } [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ] ] ] } R i n } [ [ [ [ [ ] ] [ _ _ _ _ ",
"_ _ { H   % | ^ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' F   > | ) _ _ _ _ ) _ _ _ ) _ _ ) _ _ _ ) ) ` Y t g [ ) _ _ _ _ _ _ _ _ _ ) _ _ _ _ _ ) ) ' L t k [ ) _ _ _ _ _ ) _ _ ' _ _ ",
"_ ^ ' Q   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' F   : | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ Y y h [ ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ L y l [ ) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ [ K   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' F   > | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ Y y h ] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ) [ L t l [ ) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | ^ _ _ _ _ _ _ _ [ ' _ _ _ _ _ _ _ _ | F   : | ^ _ _ _ _ _ _ _ ' ' _ _ _ _ _ _ _ _ [ Y u h [ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ ' ) [ U y l [ _ _ _ _ _ _ _ _ ' _ _ _ ",
"_ _ ' H   % | _ ` _ _ _ _ ' ^ ! ! ~ | _ _ _ _ _ _ | F   > | _ _ _ _ _ _ _ ^ ! Q ~ ' _ _ _ _ _ _ ] Y t h [ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ L t l { _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ | H   % | _ _ _ _ _ | N       . 6 _ _ _ _ _ ^ | G   : | _ _ _ ' _ | M       o 7 _ _ _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ L t l { ) _ _ ' _ _ _ _ _ _ _ _ ",
"_ _ ' H   % ' _ _ _ _ _ ' B 2 M 5 .   S | _ _ _ _ ' G   , | _ _ _ _ _ ' M 2 M 5     F ' _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ _ ' _ ' _ _ _ _ _ _ [ U y j [ _ _ _ _ _ ' _ _ _ _ _ ' ",
"_ ^ [ K   % | _ _ _ _ _ _ ' | ..^ o   S | _ _ _ _ ' F   > | _ _ _ _ _ _ _ | ..^ X   F ' _ _ _ _ ` Y y h [ ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` L y l [ ) _ _ _ _ ' _ _ _ _ ' _ ",
"_ _ { Q   % | _ _ _ _ _ _ ' V o X   7 ' _ _ _ _ _ ' F   , | _ _ _ _ _ _ | B X X   8 ' _ _ _ _ ) [ Y y h [ _ _ _ _ _ _ _ _ _ ' _ ' _ _ _ _ _ _ ] L t l { _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ [ Q   % | _ _ _ _ _ _ ' Z % #   % ~ _ _ _ _ _ | F   > | _ _ _ _ _ _ _ C % @   : ^ _ _ _ _ _ [ Y y h [ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ ] U y l [ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ ' ....| %   m | _ _ _ ^ | F   : | _ _ _ _ _ _ | ....| $   M | _ _ _ _ [ Y y h [ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] L t l { _ _ ` _ _ _ _ _ ' _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ B S ! F @   m | _ _ _ _ [ F   > | _ _ _ _ _ _ M S ! D o   M | _ _ _ _ ] P y h [ _ _ _ _ _ ' _ _ _ ' _ _ _ _ _ _ _ _ ] L t l { _ _ _ _ ' _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ _ _ _ _ _ $         $ ~ ' _ _ _ _ ' F   : | _ _ _ _ _ _ #         % ^ _ _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ ] U y l [ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ ^ ' H   % | _ ' _ _ _ _ Q N 7 8 Z ) _ _ _ ` _ _ ' G   : | _ _ ' _ _ _ Q M 7 8 Z _ _ _ _ _ _ ) ] Y y h [ _ _ _ _ _ ' _ _ _ _ _ _ _ ' _ _ _ _ ] L t l { ) _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ | H   % | ^ _ _ _ _ _ [ ....| | _ _ _ _ _ _ ) | F   : | _ _ _ _ _ _ [ ......| _ _ _ _ _ _ _ ] Y y h [ _ _ _ _ _ _ _ _ ` _ _ _ _ _ _ _ _ ) ] U t l ] ) _ _ _ _ ' _ _ ' _ _ _ ",
"_ _ { H   % | _ _ _ _ _ _ _ _ ^ _ _ _ _ _ _ _ _ _ ' F   : | _ _ _ _ _ _ _ _ ^ _ _ _ _ _ _ _ _ _ [ Y y h [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [ L t l { _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ [ Q   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | F   : | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ] Y y h [ ) _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ [ U t l [ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ [ K   % ' ^ _ ^ _ _ _ ^ _ _ _ _ ^ _ _ _ ^ _ ^ ' F   > | ^ _ _ ^ _ _ _ ^ _ _ _ _ _ ^ _ _ _ ) ` P t h [ ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ) [ L t k ] ) ) _ ) _ _ _ ) _ _ _ _ ",
"_ _ ' H   : ..| | | | | | | | | | | | | | | | | | ..Q   < ..[ | | | | | | | | | | | | | | | | |  .W i x [ ' _ _ ' _ _ _ _ ' _ _ _ _ _ _ _ _ _ [ U i v } ' [ ] ] [ [ [ [ _ _ ' _ ",
"_ _ ' H   # S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z S m   $ S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z A d 9 a ] ^ ^ ) ^ ^ _ ^ ) ^ _ ^ _ ) ^ ^ ^ ^ ^ ` K 9 s R U L L U L U L U ) _ _ _ ",
"_ _ ' G                                                                                               : ^ Q ! ! ! ! ! ! ! Q ! ! ! ! ! ! ! ! ! ^ M   * i t t t y t y t t E [ _ _ ",
"_ _ | H   o 5 3 3 3 3 3 3 3 3 4 3 3 3 3 3 3 4 3 3 3 3 < 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 3 5 >   < _ ~ ~ ^ ~ ^ ~ ^ ^ ^ ^ ^ ^ ^ ^ ~ ^ ^ ~ _ S : p c k l l l l l l l / _ _ _ ",
"_ _ ' H   : ..| ..| ..| ..| ..| ..| ..| | ..| | | ..| ^ _ ....|  .| | | ..| ..| ..| ..| ..| | | ..G   2 .._ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ^ _ } ] [ [ [ [ [ { } _ _ _ _ ",
"_ _ ' H   % ' ^ _ ^ _ _ _ ^ _ ^ _ ^ _ _ _ ^ _ _ ^ _ ^ Q ~ _ ^ _ _ ^ _ _ _ ^ _ _ _ ^ _ ^ _ ^ _ ^ | S   2 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ^ Q ~ _ _ _ _ _ _ _ ) _ _ _ _ ' ",
"_ _ ' H   % ' _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | S   < | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ ^ ' H   % | _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | S   2 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' ^ ! ^ ' _ _ _ _ _ _ _ _ _ _ _ ' ",
"_ _ | H   % | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ! ~ _ _ _ ' _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ | S   2 | _ _ _ _ _ _ _ ' [ ' _ _ _ _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ ! ~ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ | S   2 | _ _ _ _ _ _ _ ~ Q H ~ ' _ _ _ _ _ _ ' ^ ! ~ ' _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ ' H   % | _ ` _ _ _ _ _ ' _ _ _ _ _ _ ' _ _ _ _ _ ! ~ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | S   2 | _ _ _ _ _ | 5       X m ' _ _ _ _ _ _ _ ! ~ _ _ _ _ _ _ ' _ _ _ _ ' _ ",
"_ _ ' H   % | _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ ! ~ ` _ _ _ _ _ _ ' _ _ _ _ _ ' _ _ ' _ _ | S   2 | _ _ _ _ _ | : : B 2   . H [ _ _ _ _ _ ^ ! ~ _ _ _ _ ' ' _ _ _ _ _ ' _ ",
"_ _ | H   % | _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ^ ! ~ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ | S   2 | _ ' _ _ _ _ ~ | | _ o   Z | _ _ _ _ _ ^ ! ~ ' _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ _ ^ H Q _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ ' ' _ _ _ _ _ _ _ _ _ _ _ _ ^ F ! ' _ _ _ _ _ _ _ _ _ _ H H ) _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ _ _ ' [ _ _ _ ' _ _ _ _ ' _ _ ' _ ` _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` _ _ ' _ _ _ _ ' [ ' _ _ _ _ _ _ _ _ _ _ _ ' ' _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ ",
"_ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ) _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",
"_ _ _ _ _ _ _ _ _ _ _ _ ` _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ ' _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ ` _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ ' _ _ "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 79 1 ",
"  c #040404",
". c #0A0A0A",
"X c #1B1B1B",
"o c #242415",
"O c #232323",
"+ c #2E2E2E",
"@ c #303030",
"# c #35353A",
"$ c #393939",
"% c #55550B",
"& c #5D5D0F",
"* c #4C4C2D",
"= c #5F5F3D",
"- c #434343",
"; c #4B4B4B",
": c #535353",
"> c #5B5B5B",
", c #646464",
"< c #696969",
"1 c #757575",
"2 c #7A7A7A",
"3 c #93931F",
"4 c #9D9D1F",
"5 c #ACAC1C",
"6 c #9B9B20",
"7 c #939328",
"8 c #A1A127",
"9 c #ADAD2C",
"0 c #D3D32E",
"q c #D9D92F",
"w c #D4D435",
"e c #DEDE32",
"r c #D4D43A",
"t c #DDDD3D",
"y c #9A9A6A",
"u c #D5D541",
"i c #D6D64B",
"p c #E2E240",
"a c #C4C46A",
"s c #CBCB78",
"d c #D2D27A",
"f c #838383",
"g c #8B8B8B",
"h c #959595",
"j c #9F9F9E",
"k c #A3A3A4",
"l c #A0A0AB",
"z c #ADADAD",
"x c #B0B0AE",
"c c #ACACB5",
"v c #B2B2B2",
"b c #B1B1BB",
"n c #BBBBBB",
"m c #DEDE9C",
"M c #DFDFA6",
"N c #D1D1AC",
"B c #DFDFAE",
"V c #E4E4A4",
"C c #EDEDA7",
"Z c #E0E0AC",
"A c #E0E0B1",
"S c #E4E4BC",
"D c #C5C5C5",
"F c #CBCBCB",
"G c #D3D3D3",
"H c #DDDDDD",
"J c #E0E0DE",
"K c #DDDDE0",
"L c #E5E5E5",
"P c #E8E8E6",
"I c #E6E6ED",
"U c #EDEDED",
"Y c #F1F1EF",
"T c #E7E7F3",
"R c #E7E7FC",
"E c #E9E9FF",
"W c #F3F3F3",
"Q c #F5F5FF",
"! c #FCFCFC",
/* pixels */
"LLPLLLLLLPLLLLLLLLLLPPLLLLLPLLLLLLLLLLLLLLLLPLLP",
"LLLLLLKLLLLKLPKLLLLLKLLLKLLLLKLPLLLLLLLLLLLLLLLL",
"PPLPYWWWWWWWYWWWYWWWWWWWWWWWWWYYWWWWUWYWWWYYLLLP",
"PLPKvzzczzzzzzzzzzzzzzzcczzzzzzzzzzzzzvvzzzcLILL",
"LLWv @@@@@@@@@@++@@@@@++@@++@@@++@@+@#.O@@+-HLLL",
"LLWz#!UUUUUUUUYHPYUYYUYYYYLKYYUYUUUWUW@n!UUULLPL",
"LLWz@ULLPUILLLLGHLLLLKLLLLKGPKLLLLPJPI+zWKLLLPLL",
"LLWz@ULLJnFULLPGKPLLLLLLLPKGPLLLLLLPPU+vWLLLLPPP",
"LLUz@ULWj$OgWLLGKLLPLPLLLLKGPPLLPLLLLU+xWLLPPLLI",
"LLWz+WLLH!;,WLIGKPLLLPPLLPKGPLLPPPPLLU+vWLLLLLPL",
"LKWz@ULLW1:ULLPGKPLIPLLLLPKGILLLLPLLLU+cUKLLLPLP",
"LLWz+ULWh -gUPPGKPLLPLLLLIHGPLLLLLLLLU+cWLPLILLP",
"LLWz+YKIFnznIPIGKLLLLLLLLLHGPLLLLLLLPU+xWLPLLPLL",
"LLWz@YLLIUWUPPLGHLLLLLLLLLHGLLLKLPLJJU+xYKLLLLPL",
"LLWz@ULPPLLPLLLHUWWWWWWWWWULWWWWWWWWW!@bEITTLLLP",
"LLWz+HGGGGGGGGH,@$##$$$$$###$$$#$$$#$$.9trriLILL",
"PLWz@PHHKHHHHHU$<zjkjjjjjly7ljjjkjjkjl6sZmmMLLLL",
"LKWz@YLLLLLLPLW$z!WWWYWWWQCpQWWWWWWWWQeSETTTPLLP",
"PLWz@ULLUWWULLW$jWHPWWULLTmrTJLLLKKLLI0BIPLLLLLL",
"PKYz@YLUv;>FLLW$jWLL2;gLJTmrTPLPPIPLPP0BTLPLLIPP",
"PKWc@ULUvv->WLW$jWLJz<XHITmrTLLLPLLLLI0BIPLPPPLL",
"LLWz@YLK!H$vULW#jWLWG$;LPTmrTLLLLPPLLI0AILLLLPLP",
"LLWz@ULUn.,GLLW$jWIGzh.FUTmrTLLLPPLLLI0ATLLLLLPL",
"LLWz@YHWj-:gULW$jWLH,;hULUmrTLLPPLLLLI0BIPLLPLLI",
"LLWz@ULLUWWYLLW$jWJLYWWLJTmrTJPPPPJPPL0BIJLLLPLP",
"LLWz@WLLLLLPPLW$lQTTTTTTTEVtETTTRTTTTReSETTTLLLL",
"LKWz@PHHKKKKKHI#yCmmmmmmmVa8VmmmmmmmmM4sVmmMLLLI",
"LLWz+HGGGGGGGGJ#3prrrrrrrt8&trrrrrrrrt%9trriLPLL",
"LLYz@YLPPLLLLLW$lQTTUTTTTEVtEUTRTTTTTReSRITTLLPP",
"LLYz@ULLUWYLLPW$jYJPYYLLPTmrTJLPLLLLLP0BTPLPLLLL",
"LLYc@YKUHknILLW$jWLLnkHIJTmrTJLLLLLLLI0ZILLLPLPL",
"PKWz@YKYv,o2WHW$jWLL2;OHPTmrTLLPPLLLLI0BTLLLILLL",
"PLYc@UPLIhXhEKW$jWLUF-$PPTmrTLLPLLLLLI0ATLLLLLPP",
"LLYz@YLLJD#>QLW#kWLLHgXGPUmrTLLILPPLLI0AILLLLLPP",
"PKYz@ULWh:+yWHW$jWPG:;$HPTmrTLLLPPLLLI0BILPLLPLL",
"PLWz@ILLHnDULPW$jWKLDbLIPRmrTLLLLLLLLI0ATPLLLLLP",
"LLWz@ULLLYILLPY$kWLLUULPLTmwTPLLLLLLLI0AILLLLPLL",
"LLWz@!UUUUUUUI!$k!UUUUIUUEVtTPLLPPLLLIqARIIIILLP",
"LKWv @++++++++@.o++++++++@o=HGGGGGGGGH*5e00rLILL",
"LLWcOnzvvxzvxvxzzvvxxxcczn1$YHKKKKKLKLcNAAAALLLP",
"LLYz@!WWWWUWYYYKPWWWWYYYW!k$WKLLLLLPLLHITTUTLLLP",
"LLYc@YKKLLLLLLLGKLLKKLLLLWj$WLLYYWULLLGHPPLLLPLL",
"LLWz+WLLLLLLLLLGKPLPPLPLLWj$WLYk-;DULLGKLLLLILPL",
"LLWv-YLLLPLLLPPGKPLLPLILLWl;WLYbn#1WLLHKLLLLPLPL",
"LLLLKPLLPLLLLLLLLILLLLILLLLHLLLUWILLLLLLLLLLLLLP",
"LLLLPLLLLLPLPLLPLLLPPPLPLLLLLLLLPPLLILLPLLPPLPIL",
"LLPLLPLPILIPLLILLLPLLLLLLPLLLLPLLLLLLLLLIPLLLLLP",
"LPLLILLLLPLLPPLLPLLILPPLLPPPPLLIPPPLPLLPLLPILPLL"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 89 1 ",
"  c #141414",
". c #1A1A1A",
"X c #1E1E25",
"o c #232323",
"O c #2D2D2D",
"+ c #34342E",
"@ c #363636",
"# c #3E3E3E",
"$ c #535312",
"% c #424242",
"& c #4C4C4C",
"* c #525252",
"= c #5C5C5C",
"- c #757547",
"; c #656564",
": c #6C6C6C",
"> c #727272",
", c gray47",
"< c #80801F",
"1 c #8A8A26",
"2 c #9B9B2D",
"3 c #9A9A3D",
"4 c #A3A337",
"5 c #A9A932",
"6 c #D2D234",
"7 c #E2E23A",
"8 c #AFAF40",
"9 c #BDBD4D",
"0 c #B5B552",
"q c #BDBD52",
"w c #BFBF5F",
"e c #CBCB43",
"r c #D5D54B",
"t c #D9D94E",
"y c #D6D65C",
"u c #D8D85D",
"i c #E1E14D",
"p c #E2E253",
"a c #DEDE61",
"s c #D9D96D",
"d c #C1C175",
"f c #C1C178",
"g c #E3E364",
"h c #848484",
"j c #8A8A8A",
"k c #939393",
"l c #9F9F9E",
"z c #A0A09F",
"x c #A4A4A4",
"c c #A0A0AE",
"v c #AAAAAA",
"b c #A9A9B5",
"n c #B3B3B3",
"m c #BBBBBB",
"M c #C4C48B",
"N c #C9C989",
"B c #DBDB87",
"V c #DCDC89",
"C c #C6C69E",
"Z c #DDDD94",
"A c #DEDE9E",
"S c #E2E28C",
"D c #E4E494",
"F c #DFDFA7",
"G c #E5E5A2",
"H c #E5E5AC",
"J c #C4C4C4",
"K c #C9C9C6",
"L c #CACACA",
"P c #CACAD7",
"I c #CBCBDB",
"U c #D4D4D4",
"Y c #D9D9D6",
"T c #DBDBDB",
"R c #E2E2C7",
"E c #E3E3CB",
"W c #E4E4DD",
"Q c #E5E5E5",
"! c #E9E9E6",
"~ c #E5E5EC",
"^ c #EBEBEB",
"/ c #F1F1ED",
"( c #E7E7F5",
") c #E8E8F6",
"_ c #E7E7F8",
"` c #E9E9FD",
"' c #F2F2F2",
"] c #F7F7FC",
"[ c #FCFCFC",
/* pixels */
"QQQQQQQQQ!QQQQQQQQQQQQ!QQQ!QQQQQQQQQQQQQQQQQ",
"QQ~!QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ!",
"!!Q!/')/')/'//''/')//')'/'')''/////))/'/QQ!!",
"!Q~TmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmmnnnmQQQ~",
"QQ^m %###%#%##@%%######%@########%O.%#@*W~QQ",
"QQ'n%[^'^^^'/)Q^''''''^'QQ''')'//[v&[/'^QQQ~",
"QQ'n#'QQ']!Q!QUTQQQTQQQQYTQQWQQQT'l&]WQQQQQ!",
"QQ'n#^QQk:m!QQUQQQQQQQQQYTQQQQQQQ'l&]QQQQQQ!",
"QQ)n#'QTl>O^QQUWQQQ~QQQ~YT!~QQQ!Q'l&]WQQQQ!Q",
"!Q/n#'QQ[>j'QQUQQQQ!Q~Q!TT!QQQQ~W]l&]QQQQ~!Q",
"QQ'n#'Q^%.xQQQUQQQQ!QQQ!YT~QQQQQQ'z&'QQQQQQQ",
"QQ'n#^QQkhkQQQPQQQQQQQ~!TTQQQQQQQ'z&'QQQQQQ~",
"QQ'n#'QQ]]'QQQUQ!~QQQQQ!TT!QQ~QQQ'z&]QQQ!Q!~",
"QQ'n#'QQWQQQQQUQ!!!QQQQ!TT!Q!!QQQ]z&]QQQ!QQQ",
"QQ'n@QUUUPUUUU%O@@@@@@@@O@@@@@@@@@X$666rQ!QQ",
"QQ^n%^TQWWQQQQ@nPJLLLLKIqdIKLLLLLIM6WREEQQQQ",
"QQ'n#'Q!)'!!!!@P'^'['!^`gS`^^^^^!`Gt`!!~!Q~Q",
"QQ'n#)Q!JvQ!Q!@L!!UxP!W_uV(WQQQQQ(Ar(QQQQ!QQ",
"QQ'n#'QT>%%^QQ@L^^v=oU!_uV)Q~!!QQ(Dr(QQQQ~QQ",
"QQ/n#'QQ[k&'QQ@L^Q):OT!)uV_QQ!!QQ(Fr(QQQQ!!Q",
"QQ^n#'Q/,.KQQQ@L^!Jl.m^)uV(QQQ!!Q(Ar(QQQQQ!!",
"QQ'n#)QQ=&>QQQ@L^^k*,WQ_uV(QQQQ~W(Ar)QQQ!QQQ",
"QQ'n#'QQ''^QQQ@K^Q!/)QW)yV(WQQQQQ(Zr(WQQQQQQ",
"QQ'n#'Q!QQQ!!Q@I]___(_)`gD`((__(_`Hp`(__~QQQ",
"QQ/n#QUYYYTYTU+9ayuuuuyg14gyyyuuyg5<pytsQ!QQ",
"QQ'n#QYTTTTTTT@dSVVVVVVD40DBVVVVBDd2DVBZQ!QQ",
"QQ)n%'!!Q!Q!(!@I`))`__(`gD`(_()_(`Hp`(((QQQQ",
"QQ/n#)Q!QT'QQQ@L^QQY!!W(yV(WQQQQQ~Ar(QQQQQQQ",
"QQ'n#'QQh%:)Q!@L^^v*&Y!_uV(WQQ!QW(Ar(QQ!Q~QQ",
"QQ'n#'Q!L%&'Q!@L^!Y>oU!_uV_QQQQQQ(Ar(QQ!Q!QQ",
"QQ/n#)QQY:#!QQ@L^QQloJ^_uV_QQQ!!Q(Ar_QQQQQQQ",
"QQ'n#'QT:&=~QQ@L!^j*#U!_uV_QQQ~!Q(Ar(QQQQ~!!",
"QQ'n#^QQUL!QQQ@KQQYKQQW(yV_QQQQ~Q(Ar(WQQQQQ!",
"QQ/n%[/'[[''']#U['][]''[gV)Q~!!!Q(Gt`()(QQ!Q",
"QQ^mOvllllllllojxllllllc3N~TWTWTY~C5HZFGQ!QQ",
"!Q^m &&&&&&&&&&&&&&&&&&* jQUYUUUYWb-trruWQQQ",
"!Q/n%[']]]]]]'Q']'][]''[;j]QQQQQ!!~Q__)(!QQQ",
"QQ)n%/QTWTWQQWPWQQWTWQW'=j]Q^']!Q~TUQQQQQ!QQ",
"~Q^n#'QQQQQQQQUQQQQQ~QQ]=j[QL;:U!QTUQQQQ~QQQ",
"QQ'm*'QQQQQQQQUQQQ~QQQW]:k]!Kv%h'~WYQQQQQQ~!",
"QQQQWQQ!QQQ!~QQQ!Q!QQQQ!WQQQ^'!QQQQQQQ~!QQQQ",
"QQQ~~Q~!QQQQQQQQQQ~QQQQQ~!QQQQQQQQQQQQQ!!Q~!",
"QQ!QQQQQ!!!QQQQQQQ!Q!QQQQQQQQQQQ!QQQQQQQ!QQ!",
"!QQQQQQQQ!~QQ~!!QQ~Q!~QQQQQQQ~~!~!QQ~!QQ~QQQ"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 217 2 ",
"   c gray90",
".  c #E6E6E6",
"X  c gray92",
"o  c #EEEEEE",
"O  c gray93",
"+  c LightGray",
"@  c gray78",
"#  c #C8C8C8",
"$  c gray79",
"%  c #CACACA",
"&  c gray82",
"*  c #E4E4E4",
"=  c #353535",
"-  c gray36",
";  c #5B5B5B",
":  c #5A5A5A",
">  c gray35",
",  c gray34",
"<  c gray37",
"1  c #515151",
"2  c #2D2D2D",
"3  c #5F5F5F",
"4  c #585858",
"5  c #646464",
"6  c gainsboro",
"7  c gray91",
"8  c gray98",
"9  c gray97",
"0  c #FBFBFB",
"q  c #EFEFEF",
"w  c gray94",
"e  c #ECECEC",
"r  c #E1E1E1",
"t  c #F1F1F1",
"y  c #D0D0D0",
"u  c #606060",
"i  c gray76",
"p  c gray70",
"a  c gray88",
"s  c gray84",
"d  c gray89",
"f  c #E2E2E2",
"g  c #C6C6C6",
"h  c #AFAFAF",
"j  c gray27",
"k  c gray56",
"l  c #F6F6F6",
"z  c #DFDFDF",
"x  c #D8D8D8",
"c  c #E7E7E7",
"v  c #D7D7D7",
"b  c #C1C1C1",
"n  c #6A6A6A",
"m  c #393939",
"M  c #BCBCBC",
"N  c #5C5C5B",
"B  c #F0F0EF",
"V  c #E3E3E2",
"C  c #EAEAE9",
"Z  c #DFDFDD",
"A  c #F4F4F4",
"S  c #CFCFCE",
"D  c #5E5E5F",
"F  c #F0F0F7",
"G  c #E4E4EB",
"H  c #E6E6EC",
"J  c #C5C5C5",
"K  c #C5C5C7",
"L  c #BCBCC3",
"P  c #CECECE",
"I  c #ACACAD",
"U  c #595950",
"Y  c #EDEDD0",
"T  c #E0E0C5",
"R  c #E3E3C9",
"E  c #E5E5E4",
"W  c #D5D5D5",
"Q  c #5D5D5D",
"!  c #5C5C5E",
"~  c #5B5B52",
"^  c #56562D",
"/  c #5C5C5F",
"(  c #515150",
")  c #787825",
"_  c #E0E061",
"`  c #D6D659",
"'  c #D9D964",
"]  c #E5E5DC",
"[  c #E6E6E8",
"{  c #E1E160",
"}  c #F1F1FA",
"|  c #EFEFED",
" . c #EEEED0",
".. c #E0E060",
"X. c #E7E7FA",
"o. c #E6E6EE",
"O. c #E6E6EF",
"+. c gray77",
"@. c gray71",
"#. c #B7B7B7",
"$. c #E0E0DF",
"%. c #E5E5EB",
"&. c #E0E0C6",
"*. c #D6D65C",
"=. c #E4E4ED",
"-. c #E3E3E1",
";. c #D6D65B",
":. c #E6E6ED",
">. c #E5E5E1",
",. c #8E8E8E",
"<. c #FDFDFD",
"1. c #EAEAEA",
"2. c gray68",
"3. c #2C2C2C",
"4. c #A1A1A0",
"5. c #F4F4FA",
"6. c #D8D85C",
"7. c #E6E6F0",
"8. c #E5E5E3",
"9. c #E2E2C7",
"0. c #E7E7F0",
"q. c #E6E6E5",
"w. c #C0C0C0",
"e. c gray87",
"r. c #464646",
"t. c #8E8E8D",
"y. c #F6F6FD",
"u. c #DFDFC4",
"i. c #BBBBBB",
"p. c #F3F3F3",
"a. c #EFEFEE",
"s. c #E7E7E6",
"d. c #959595",
"f. c #545453",
"g. c #A9A9A8",
"h. c #F1F1F6",
"j. c #E0E0C4",
"k. c #D7D75B",
"l. c #E5E5E2",
"z. c #E5E5EC",
"x. c #E1E1E8",
"c. c #E3E3EA",
"v. c #EFEFF4",
"b. c #E5E5F3",
"n. c #E4E4CE",
"m. c #DCDC5F",
"M. c #E7E7F7",
"N. c #E6E6EB",
"B. c #E7E7F4",
"V. c #E9E9E9",
"C. c #E4E4C9",
"Z. c #E3E3C8",
"A. c #E1E1C5",
"S. c #DCDCAD",
"D. c #C6C650",
"F. c #E5E5D0",
"G. c #E2E2C6",
"H. c #E2E2C5",
"J. c #BBBBC3",
"K. c #E1E15E",
"L. c #D5D55A",
"P. c #888825",
"I. c #DEDE60",
"U. c #DEDE61",
"Y. c #EDEDF6",
"T. c #E7E7EF",
"R. c #B9B9B9",
"E. c #E7E7E5",
"W. c #C9C9C7",
"Q. c #B9B9B7",
"!. c #E2E2DF",
"~. c #E7E7EC",
"^. c #A0A0A0",
"/. c #8D8D8D",
"(. c #535353",
"). c gray66",
"_. c #F0F0F6",
"`. c #D7D75C",
"'. c gray38",
"]. c #F5F5F4",
"[. c #ECECF3",
"{. c #EAEACE",
"}. c #DBDB5D",
"|. c #E6E6E4",
" X c #E7E7EE",
".X c #E4E4C8",
"XX c #DCDC60",
"oX c #505050",
"OX c #C6C6C5",
"+X c #C8C8CE",
"@X c #C5C5AC",
"#X c #CCCC59",
"$X c #E2E2E0",
"%X c #E2E2E1",
"&X c #E4E4E9",
"*X c #DCDCC7",
"=X c #C6C652",
"-X c #4E4E4E",
";X c #606061",
":X c #4A4A48",
">X c #56564E",
",X c #DCDCDB",
"<X c #C6C6CC",
"1X c #888856",
"2X c #DEDE5B",
"3X c #D6D65A",
"4X c #5D5D5E",
"5X c gray95",
"6X c #DEDEE3",
"7X c #E7E7F1",
"8X c #D6D6D5",
"9X c gray85",
"0X c gray65",
"qX c #484848",
"wX c #9A9A9A",
"eX c #DADADA",
"rX c white",
/* pixels */
"  . X o O O O O O O O O O O O O O O O O O O O O O O X O O O .   ",
".   + @ # # # # # # $ # # # # # # # $ # # # # # # % & @ # % * . ",
"X + = - ; : > ; - : , - ; ; ; ; - : , - ; ; ; ; < 1 2 3 4 5 6 7 ",
"O @ 3 8 O 9 0 q w e r t q w w q w e r t q w w q 9 y u 8 o q .   ",
"O # ; O   i p   * a s * d d d d * a s * d d d f X g - O r *   . ",
"O # ; q   h j k l z x .         . f x .       * O @ - w d     . ",
"O # ; q c v 3 b o r x c     .   . f x c     . * O @ - w d   . . ",
"O # ; O w n m M O r v   * * * *   r v   * * * d e @ N B V     . ",
"O # - w d 7 d a 7 d 6 o e O O O o C Z o O O O e A S D F G H .   ",
"O # : e r d * d d a J @ # @ @ @ # K L # @ @ @ @ P I U Y T R E . ",
"O $ , r s s W v 6 J = Q - ; : N ! ~ ^ / N - - N D ( ) _ ` ' ] [ ",
"O # - t * o t   o # 3 8 O l 8 B F Y { } | w w B F  ...X.o.O..   ",
"O # ; q c +.@.. e @ - O   @ #.$.%.&.*.=.-.d d V G &.;.:.>.E   . ",
"O # ; q . h j ,.<.+.- o 1.2.3.4.5.T 6.7.8.    E :.9.6.0.8.  q.. ",
"O # ; q c v 3 w.A g - q   e.r.t.y.u.6.0.8.  . E :.9.6.0.8.  . . ",
"O # ; O w n m i.p.g N a.s.d.f.g.h.j.k.O.l.E E 8.H 9.k.O.l.    . ",
"O # - w d 7 d z q # ! F z.x.c.v.b.n.m.M.N.:.:.H B.n.m.M.N.H .   ",
"O # : e r d * d V.K ~ Y &.C.Z.A.n.S.D.F.G.9.9.9.n.S.D.F.H.R E . ",
"O $ , r s s W s Z J.^ K.*.;.L.k.m.D.P.I.k.6.6.k.m.D.P.U.` ' ] [ ",
"O # - t * O t . o # / } =.Y.} T.M.F.I.X.:.0.0.O.M.F.I.X.o.O..   ",
"O # ; q c $ R.r O @ N | E.W.Q.!.~.H.k.:.>.8.8.l.N.G.k.:.>.E   . ",
"O # ; o 1.2.3.^.8 J - o 1.2.3.4.5.T 6.0.8.    E :.9.6.0.8.  q.. ",
"O # ; q   e.r./.<.+.- q   e.r.t.y.u.6.0.8.  . E :.9.6.0.8.  . . ",
"O # ; o . d.(.).l +.; o . d.(.g._.u.`.7.8.    E :.9.`.O.l.    . ",
"O # < 9 e 7 1.A p.P '.9 e 7 1.].[.{.}.0.|.. . q. X.XXXM.N.H .   ",
"O % 1 y g $ # J P 2.oXy J $ # OX+X@X#X=.$Xf f %X&X*X=XF.H.R E . ",
"X & 2 < - - - - Q > -XQ - - - N ;X:X>Xd W v s v ,X<X1X2X3X' ] [ ",
"O @ 3 8 O w w w w O d w q w w q 9 & 4Xt * o 5Xc c   6X7X7.O..   ",
"O # ; O r d d d * a W * d d d f X g - q c J p * c f 8X|.8.E   . ",
"O % 5 q *       . d 9X.         e $ 5 o c 0XqXwXA a 9X.     q.. ",
". * 6 .     .   .     .   . .   . * 6 . * t V.eXc     .   . . . ",
"  . 7   . . . .   . .   . . . .   . 7   . d   V.  . .   . . . . "
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 174 2 ",
"   c gray90",
".  c #CDCDCD",
"X  c gray77",
"o  c #C6C6C6",
"O  c #C5C5C5",
"+  c #C8C8C8",
"@  c gray79",
"#  c gray89",
"$  c #868686",
"%  c gray69",
"&  c #AFAFAF",
"*  c #A7A7A7",
"=  c #A5A5A5",
"-  c #AAAAAA",
";  c #A9A9A9",
":  c gray68",
">  c gray59",
",  c gray50",
"<  c gray71",
"1  c gray88",
"2  c gray95",
"3  c gray91",
"4  c gray94",
"5  c #ECECEC",
"6  c #E9E9E9",
"7  c #EFEFEF",
"8  c #F6F6F6",
"9  c #D0D0D0",
"0  c #B0B0AF",
"q  c #FAFAF9",
"w  c #E4E4E4",
"e  c #B1B1B1",
"r  c #C1C1C1",
"t  c #808080",
"y  c #EAEAEA",
"u  c #E1E1E1",
"i  c #ECECEB",
"p  c gray92",
"a  c #E7E7E7",
"s  c #E4E4E3",
"d  c #EAEAEB",
"f  c #F1F1F1",
"g  c #CDCDCC",
"h  c #A8A8AC",
"j  c #EEEEF5",
"k  c gray66",
"l  c #E6E6E6",
"z  c #D8D8D8",
"x  c gray78",
"c  c #C6C6C7",
"v  c #C3C3C6",
"b  c #CECECE",
"n  c #ADADAF",
"m  c #A4A491",
"M  c #EEEED4",
"N  c #E3E3E1",
"B  c #A4A4A4",
"V  c gray51",
"C  c #B0B0B4",
"Z  c #A5A594",
"A  c #A4A47F",
"S  c #A9A9AE",
"D  c #A9A9AC",
"F  c #A1A193",
"G  c #C4C479",
"H  c #E5E5B5",
"J  c #E4E4DF",
"K  c #AEAEAE",
"L  c #D7D7D7",
"P  c gray80",
"I  c gray70",
"U  c #E1E1DF",
"Y  c #A7A7AD",
"T  c #F3F3D6",
"R  c #E8E8AE",
"E  c #F1F1F9",
"W  c #F0F0F4",
"Q  c #EEEED0",
"!  c #E4E4AF",
"~  c #E7E7F9",
"^  c #E5E5E4",
"/  c #B2B2B2",
"(  c gray76",
")  c #888888",
"_  c #ADADB1",
"`  c #CACAD0",
"'  c #777784",
"]  c #E8E8D3",
"[  c #DEDEAB",
"{  c #E5E5F4",
"}  c #E4E4EF",
"|  c #E2E2CC",
" . c #E0E0AB",
".. c #E7E7F5",
"X. c #E5E5E3",
"o. c #DEDEDD",
"O. c #C6C6C8",
"+. c #A7A795",
"@. c #E7E7CA",
"#. c #DEDEC8",
"$. c #DEDEAF",
"%. c #D6D692",
"&. c #E4E4D0",
"*. c #E4E4CC",
"=. c #DDDDAF",
"-. c #D6D691",
";. c #E5E5D4",
":. c #E5E5E1",
">. c #EFEFEE",
",. c #C2C2C5",
"<. c #A3A37E",
"1. c #EDEDB1",
"2. c #E9E9B5",
"3. c #D5D592",
"4. c #CCCC7B",
"5. c #E2E2AF",
"6. c #E1E1AB",
"7. c #D6D693",
"8. c #CCCC79",
"9. c #E3E3B5",
"0. c #D5D5D5",
"q. c #A2A2A3",
"w. c #ACACB3",
"e. c #D6D6DF",
"r. c #9C9CAC",
"t. c #E9E9D6",
"y. c #E1E1AE",
"u. c #E7E7FA",
"i. c #E4E4D1",
"p. c #D2D2D2",
"a. c #868685",
"s. c gray83",
"d. c #B4B4B2",
"f. c #D3D3D0",
"g. c #7F7F84",
"h. c #F0F0D3",
"j. c #DFDFA6",
"k. c #E7E7ED",
"l. c #E6E6E9",
"z. c #E4E4C7",
"x. c #E1E1AC",
"c. c #979797",
"v. c #CBCBCB",
"b. c #CACACA",
"n. c #939393",
"m. c #CCCCCB",
"M. c #C4C4CA",
"N. c #C6C6AE",
"B. c #D8D8A4",
"V. c #E4E4EC",
"C. c #E2E2E6",
"Z. c #DDDDC7",
"A. c #E5E5D3",
"S. c gray64",
"D. c #9F9F9F",
"F. c #90908F",
"G. c #A2A29F",
"H. c #EBEBEC",
"J. c #D6D6D8",
"K. c #CCCCA2",
"L. c #E3E3AD",
"P. c #E4E4E1",
"I. c gray98",
"U. c #EEEEEE",
"Y. c LightGray",
"T. c #B3B3B4",
"R. c gray84",
"E. c #EAEAE9",
"W. c #E2E2EA",
"Q. c #E7E7F0",
"!. c #E5E5E6",
"~. c #E2E2E2",
"^. c #E2E2E1",
"/. c white",
/* pixels */
"  . X X o o o o o o o O + @ + # ",
". $ % & * = - ; * = ; : > , < 1 ",
"X < # : 2 3 4 4 5 6 7 8 9 0 q w ",
"X e r t y u i p a s d f g h j # ",
"o k l z u + x x c v + b n m M N ",
"o B 5 5 x V 0 C Z A S D F G H J ",
"O K L - P I U Y T R E W Q ! ~ ^ ",
"X / ( ) 9 _ ` ' ] [ { } |  ...X.",
"o k   o.O.+.@.#.$.%.&.*.=.-.;.:.",
"o B 5 >.,.<.1.2.3.4.5.6.7.8.9.J ",
"O K 0.q.g w.e.r.t.y.u...i.5.~ ^ ",
"X < p.a.s.d.f.g.h.j.k.l.z.x...X.",
"+ c.v.b.& n.m.M.N.B.V.C.Z.7.A.:.",
"b.t & k S.D.- K F.G.H.  J.K.L.P.",
"+ < I.U.U.p 4 8 Y.T.R.- E.W.Q.!.",
"# 1 w # # ~.# w u ^.# R.  s X.  "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
