#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXgXfXfXgXkXlXkXlXlXlXkXkXlXjXgXfXfXhXkXlXkXlXlXlXlXlXlXkXlXkXfXfXhXlXkXlXlXlXkXkXlXjXgXfXfXhXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnXDXJXHXAXxXkXlXkXlXlXlXlXkXbXSXHXHXCXlXkXlXkXlXlXlXlXkXlXjXxXGXKXBXjXlXlXlXlXlXlXkXnXSXJXHXVXkXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXvX&Xf.2.5.N.yXvXjXlXlXlXkXkXzX:Xn.5.7.H.jXcXkXlXlXlXlXkXlXjXvXqX9.*.W.NXhXlXlXlXkXkXlX*Xc.4.8.I.zXxXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXFX]   $ .   n tXxXjXlXlXkXzXsXl   % .   Q jXlXkXlXlXlXkXkXhXVX..    #.HXfXlXlXlXjXcXeXy   $ .   } xXkXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXvX*X3XCX`.#   [.VXhXlXlXkXxXiXd.].yXD.+   .XBXhXlXlXkXlXgXCXH.% k   <.GXfXlXlXlXkXcXwXa. XyXv.    :XmXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXDXL.E G   K uXxXjXlXlXlXkXlXNXnXDXeX& + =XmXjXlXlXlXjXnX0X> *.4.  ,.SXgXkXlXlXlXkXlXBXvXHX<X. : 6XbXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXhXmXp.6 & o k.mXjXkXlXlXkXlXlXdXnXiXL   8.mXjXkXlXlXkXkXnXE p KX4.  8.UXdXlXlXlXkXlXkXdXmXqXB   d.MXjXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXMXvXmX4Xe   (.NXhXlXlXlXkXjXCX=Xg   a.VXzXkXlXlXlXhXVX^.  4.OXR   ! ;XlXkXlXlXlXkXkXZXoXr   b.ZXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXtX_.tXxX<Xt   N.VXhXlXlXkXjXbXW.2 + B.xXrXgXlXkXlXkXhXCXJ.  o     #   S SXgXlXlXkXjXbXH.- = L.xXrXhXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXbX4X1 * r #   u 6XvXjXlXlXjXxXuXf   # 3 * . E.BXhXlXlXkXcX6XS.J.!.K   K %XzXjXlXlXjXvX8Xw   % 2 % @ {.MXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXD.o.W [ f.qXbXjXlXlXlXkXzXsX<.! / R ! I XXmXjXlXlXlXkXcXZXBXKXF.D L.LXgXlXlXlXkXxXtX*.~ ^ R Q T *XnXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXVXGXJXGXZXcXjXlXkXlXlXlXkXlXSXHXGXJXHXJXbXkXlXlXlXkXlXkXgXhXfXMXKXMXgXlXkXlXlXlXkXzXDXHXHXJXHXJXvXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXfXfXgXkXlXkXkXlXlXkXlXkXgXfXfXfXfXfXjXlXkXlXlXlXlXlXlXkXlXhXfXhXlXkXlXlXlXkXlXkXgXfXfXfXfXfXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXfXfXhXlXkXlXlXlXkXkXlXjXgXfXfXhXkXlXkXlXlXlXlXkXlXjXgXfXfXhXlXkXkXlXlXlXlXkXlXjXgXfXfXgXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXzXGXKXVXjXlXlXlXlXlXlXkXnXSXJXHXZXlXkXlXkXlXlXlXlXkXvXSXHXKXBXjXlXlXlXlXlXlXlXkXMXGXJXHXZXzXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXcXtX5...D.NXhXlXlXlXkXkXzX&Xj.;.>.V.fXcXkXlXlXlXlXkXcX,Xk.;.o.T.nXjXkXlXlXlXkXjXvX{.0.&.:.M.pXcXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXCX=.    ( GXfXlXlXlXkXzXaXk   ; o   U gXlXkXlXlXlXgXSX%.  *   ,.VXhXkXlXlXlXkXgXZXF   - X   G gXzXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXVXR.* x   ..FXgXlXlXlXkXxXiXz.XXsXL.@   .XBXhXlXlXlXkXcX:X4X<.  6.VXhXkXlXlXlXkXkXxX-XrXFXP.    ,XmXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXbXyX4 X.u.  | AXgXkXlXlXlXkXlXBXvXDX0X% # ;XmXjXlXlXlXlXkXvXHX4.  4.VXhXkXlXlXlXlXkXhXSXk.G c   | jXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXMX` 0 GXd.  %.UXdXlXlXlXkXlXkXdXmXrXS   e.mXjXkXlXlXlXkXlXgXmX1.  4.BXgXkXkXlXlXkXkXhXbX5.r % % Z.mXjXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXNX.X  #.{.^   D XXlXkXlXlXlXkXjXCX@Xi   z.AXzXkXlXlXlXlXlXkXkXZX4.  6.SXjXkXlXlXlXlXkXxXNXnXCX=X, X @XmXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBX(.  X     @   k BXhXlXlXkXjXbXI.> # C.jX9XfXlXkXlXlXlXkXlXdXcX1.  3.vXdXlXkXlXlXkXvX7X~.eXlX{.>   Q.NXhXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXeXI.T.]./   Z &XkXkXlXlXjXxXyXd   @ ; +   R.BXhXlXlXlXhXCXp.: &   * : d.VXhXlXlXhXMX+X# * 6 o   V aXxXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXCXBXKXQ.T S.KXgXlXlXlXkXzXsX7.] { _ ] ^ OXnXjXlXlXlXhXMXJ.E [ | [ W L.mXjXlXlXkXzXaXA.%.` $.B.sXcXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXhXfXmXKXBXgXlXkXlXlXlXkXlXSXJXHXJXJXKXbXkXlXlXlXlXlXjXBXLXJXHXJXLXBXjXlXlXlXlXkXzXVXGXKXGXCXzXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXfXhXlXkXlXlXlXkXlXkXgXfXfXfXfXfXjXlXkXlXlXlXkXlXhXfXfXfXfXfXhXlXkXlXlXkXlXkXhXgXfXfXhXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXcXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXfX9XqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqX0X9X9X9X9X9X9X9X9X9X9X9X9X9X0X9X9X9X9X9X9X9X9X9X9X9X9X8XrXzXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX#XJ E U Y Y Y Y Y Y Y Y Y Y U R Y U Y Y Y Y Y Y Y Y Y Y U E / ^ / / / / / / / / / / / Q / / / / / / / / / / / ( Y 2.MXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXfXfXfXfXgXkXlXkXlXlXjXMX#XG ' X.....................X.)  ..................... .o.E x v v v v v v v v v v v c H v v v v v v v v v v v n d ;.BXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXVXJXJXJXKXDXlXkXlXlXlXjXMX$XS ;.k.s.d.d.d.d.d.d.d.d.s.g.#.p.d.d.d.d.d.d.d.d.d.d.a.l.Q   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXV.( ' _ ! 3.dXzXkXlXlXjXMX$XD =.s.y.u.u.u.u.u.u.u.u.y.i.+.r.u.u.u.u.u.u.u.u.u.u.t.f.W   X . . . . . . . . . . . j . . . . . . . . . . . o   @.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFX{   < 5 @ z iXxXjXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDX&.  d.U.].fXlXkXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFX}   +   % 3.xXlXkXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXNXC.p._.e.#   R.BXhXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXDXLXSXKXP   w.VXhXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXrXk.oXiX].8   A.VXhXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXcXtXa   , o   L dXzXkXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXzX-Xh.=.>.F.jXcXjXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbXSXJXHXCXlXkXlXkXlXlXjXMX$XD =.s.t.y.y.y.y.y.y.y.y.y.i.+.r.u.y.y.y.y.y.y.y.y.y.t.f.W   X . . . . . . . . . . . j . . . . . . . . . . . o   @.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXjXgXfXfXhXkXlXkXlXlXlXjXMX$XS :.k.d.f.f.f.f.f.f.f.f.d.h.$.a.f.f.f.f.f.f.f.f.f.f.s.z.Q   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX#XG { #.+.+.+.+.+.+.+.+.+.+.@.` O.+.+.+.+.+.+.+.+.+.+.O.$.E p d s s s s s s s s s s s A s s s s s s s s s s s f q -.BXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXfXfXfXfXgXkXlXkXlXlXjXMX@XY d   X . . . . . . . . .   j O   . . . . . . . . . .   l - * * * * * * * * * * * * c = * * * * * * * * * * ;   $.VXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXBXHXHXHXJXDXlXkXlXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXBXn.T Q R L -.sXzXkXlXlXjXMX@XY s   .                     h o                         j X                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFX{   6 e - m iXxXjXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDX&.  p.K.'.jXzXkXlXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFX}   +   @ -.zXlXkXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXNXF.k.}.s.&   U.BXhXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXDXLXSXKXI   w.VXhXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXrXa.[.eX^.5   D.VXhXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXxXyXd   * .   R gXzXkXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXzX<Xb.3.7.I.zXxXkXlXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXbXSXJXHXVXkXkXlXkXlXlXjXMX@XY d   X . . . . . . . . .   j + . X X X X X X X X X X   j X   . . . . . . . . . .   k X . X X X X X X X X X O   @.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXjXgXfXfXhXkXlXkXlXlXlXjXMX@XY s   .                     h o                         j .                         j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX@XP A p f d d d d d d d d f s D N n m m m m m m m m m m m G d d d d d d d d d d d f d F m m m m m m m m m m m N j :.NXhXlXlXlX",
"lXkXkXlXjXgXgXfXjXlXkXlXlXlXlXlXlXlXkXlXjXgXgXfXhXlXkXkXlXlXlXjXMX@XY j O & % % % % % % % % =   / UXJXLXLXLXLXLXLXLXLXLXHXUX>.  = % % % % % % % % % =   O.UXHXLXLXLXLXLXLXLXLXLXLXKXn.lXkXlXlXlX",
"lXlXlXkXNXFXGXGXvXkXlXlXlXlXlXlXlXlXlXkXbXSXGXGXNXkXlXlXlXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXkXxXY...Y P .XmXjXlXlXlXlXlXlXlXjXbX@X>.W D n.mXjXkXlXlXlXjXMX@XY s   .                 X   ~ UXLXIXIXIXIXIXIXIXIXIXKXUX:.  o                   X   o.UXKXIXIXIXIXIXIXIXIXIXIXPXn.lXkXlXlXlX",
"lXkXkXxXn ; -   U.BXhXlXlXlXlXlXlXlXgXSX<.O 6   &.BXhXkXlXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXlXjX0XpXF   W.BXhXlXlXlXlXlXlXlXkXzXqXhXw.  >.VXhXkXlXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXlXkXkXbXxXZ   E.BXhXlXlXlXlXlXlXlXlXkXzXSXq.  ;.VXhXkXlXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXkXkXjXgXC   R.MXhXlXkXlXlXlXlXlXkXlXgXmX9.  -.NXgXkXkXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXlXlXkXvXbXA   ^.DXkXkXlXlXlXlXlXlXlXkXlXFXe.  ,.FXlXkXlXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXkXkXeX4XV   S.tXaXlXkXlXlXlXlXlXkXzXyXtX1.  #.tXtXlXkXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXkXvXP   X     + ^.BXhXlXlXlXlXlXgXZXu.  X   X   5.VXhXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXkXkXxXV.1.q.w.7.7.,XbXjXlXlXlXlXlXjXnX'.1.0.w.0.1./.bXjXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXlXlXkXAXKXHXGXJXJXbXkXlXlXlXlXlXlXlXjXNXKXHXGXHXKXBXjXlXlXlXjXMX@XY d   o . . . . . . . . O   ~ UXJXKXKXKXKXKXKXKXKXKXGXUX:.  o . . . . . . . . . o   X.UXGXKXKXKXKXKXKXKXKXKXKXJXn.lXkXlXlXlX",
"lXkXkXlXgXfXfXfXfXfXjXlXkXlXlXlXlXlXkXlXjXfXfXfXfXfXhXlXkXlXlXjXMX@XY s   .                 X   ~ UXPXIXUXUXUXUXUXUXUXUXKXUX:.  X                   X   o.UXLXUXUXUXUXUXUXUXUXIXUXPXn.lXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX#XL H c b b b b b b b b b n l ! V.M.M.N.N.N.N.N.N.N.N.m.A.] i h f f f f f f f f f h p ^ v.j.k.k.k.k.k.k.k.k.k.z.s.e.nXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXgXgXhXlXkXlXlXlXjXMX$XS ;.k.s.d.d.d.d.d.d.d.d.s.g.+.<.3.3.3.3.3.3.3.3.3.3.2.8.T o $ # # # # # # # # # # # l                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXcXDXFXNXjXlXlXlXlXjXMX$XD =.s.y.u.u.u.u.u.u.u.u.y.i.@.p.d.s.s.s.s.s.s.s.s.s.a.l.Q   .                       j X X X X X X X X X X X O   @.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXnX,XT n k.ZXhXlXlXlXjXMX$XS =.d.y.u.u.u.u.u.u.u.u.u.p.+.t.i.u.u.u.u.u.u.u.u.u.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXjXnXW      .HXfXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXAXg.: H   &.FXfXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXNX-X. u.r.  $.AXgXkXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXm Z UXe.  2.UXdXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVX!.  ` f.B   z D.vXjXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVX!.. +     #   m ZXhXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXiX$X&X8X}   ! aXhXkXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXMXnXAX|.7.'.AXhXlXlXlXjXMX$XS =.d.u.i.i.i.i.i.i.i.i.u.p.@.t.i.u.i.i.i.i.i.i.i.i.y.g.W   .                       j                       X   +.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXjXgXMXJXNXgXlXkXlXlXjXMX$XD -.d.y.u.u.u.u.u.u.u.u.u.p.@.t.i.u.u.u.u.u.u.u.u.u.y.g.Q   o X X X X X X X X X X . k X X X X X X X X X X X O   @.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXfXhXlXkXlXlXlXhXNX#XV &.d.u.i.i.i.i.i.i.i.i.u.a.o.t.i.i.i.i.i.i.i.i.i.i.y.g.T   .                       g                       X   o.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXmX*X^ %.<.>.>.>.>.>.>.>.>.>.>.,.@.:.>.>.>.>.>.>.>.>.>.>.>.<.| F H H H H H H H H H H H H ^ H H H H H H H H H H H K B 8.NXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXhXdXfXfXfXfXfXfXfXfXfXfXfXhXfXfXfXfXfXfXfXfXfXfXfXfXdXjXvXvXvXvXvXvXvXvXvXvXvXvXvXzXvXvXvXvXvXvXvXvXvXvXvXvXvXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXlXzXzXzXzXzXzXzXzXzXzXzXzXlXzXzXzXzXzXzXzXzXzXzXzXzXzXlXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXhXgXhXjXlXkXkXlXlXkXlXkXjXhXgXhXkXlXkXlXlXlXlXlXkXlXkXgXgXkXlXkXlXlXkXkXlXjXhXgXhXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXZXSXZXvXjXlXkXlXlXlXkXlXnXZXSXBXkXkXlXkXlXlXlXkXlXkXlXZXDXvXkXlXlXlXlXlXkXcXCXSXCXzXjXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXxX6XQ.H.E.8XmXjXlXlXlXkXkXkX<XE.L.}.xXcXkXlXlXlXlXkXkXzXgXT.D.6XvXkXlXlXkXkXzXwX).K.~.iXmXjXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXZXU   O   4 _.MXhXlXlXhXNX(.X O X   _ hXlXkXlXlXkXlXgXSXq.    S.SXgXlXlXjXxXtXa   +   d :XbXjXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXcXXX2XxX..  %.GXfXlXlXjXmX Xd.,X.Xe   '.VXhXlXkXlXhXNX X< a   L.AXgXlXlXkXcXqXi.|.5X!   1.GXfXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXSX8.N 3 7 .XmXjXkXlXlXkXcXVXVXSXj   *XMXhXlXlXkXxXlXu $.<.  J.CXhXkXlXlXkXlXVXbXUX1.  l.SXgXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXw.F - f :XbXjXlXlXkXlXgXcXjX^   y.mXjXkXlXkXjXVX*.a UX2.  '.IXdXlXlXkXlXjXjXVXf.  U fXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXVXJXUXU.  ~ BXhXkXlXlXjXMX6Xn @ I.UXcXjXlXlXkXxXiX; k *.p   n [.NXhXlXlXjXxXzX%.  ,.FXVXjXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnX1X .n.J.J   [ BXhXkXlXjXbX;Xq   { G.f.,XvXjXlXkXxXuXD w 9 *   X A.AXgXlXkXlXhXW   n S.h.).bXjXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXvX9Xz o   & ! 4XbXjXlXlXhXVXL.  @ o X   H.VXhXlXkXlXlXhXgXZX&.  U.AXgXlXlXjXvX6X7   @ o    .CXhXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXkXqX7XrXmXbXjXlXkXlXkXlXdX7X5X6X8X6XsXzXkXlXlXkXlXzXlXxXyX3XdXzXkXlXlXkXlXjX0X5X5X8X6XyXzXkXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXzXbXnXvXjXjXlXkXlXlXlXkXzXbXbXnXbXnXzXkXlXlXlXlXkXkXkXkXcXnXzXkXlXkXlXlXkXlXbXbXbXbXnXcXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXjXjXjXkXlXkXlXlXlXkXlXkXjXjXjXjXjXkXlXkXlXlXlXlXlXkXlXkXjXkXlXkXlXlXkXlXkXjXjXjXjXjXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXhXfXgXkXlXkXlXlXkXlXkXhXgXgXgXjXlXkXkXlXlXkXlXkXgXgXfXjXlXkXlXlXlXlXkXlXhXgXgXgXhXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXMXGXSXzXkXlXlXlXlXkXxXAXGXGXSXbXjXlXkXlXlXlXkXcXDXFXFXnXkXlXlXlXlXlXlXkXVXGXHXFXBXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXVXY.H ' uXxXkXlXlXkXxXeXa.^ I -.:XnXjXlXlXlXjXvX4X1.Q J W.MXjXkXlXlXkXjXbXB.! J _ J.xXkXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXbX7X9   # 9XbXjXlXlXhXVXU.o N i   q 7XvXjXlXlXhXCXY.q u   j.CXhXkXlXlXkXjXMXY z J ;   B.ZXgXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXjXBXP b h $ wXvXjXkXlXkXcX5X2XNXNXM   `.VXhXlXlXkXlXfXDXg.  v.CXhXkXlXlXlXlXkXzXdXgX)   u.FXgXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXSXk.@ :Xk o rXvXjXlXlXlXkXvXzXVX4X: 0 eXcXjXlXlXlXkXhXCXt.  x.CXhXkXlXlXkXkXjXvXZ     J dXzXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnX1X- b.BXy + rXvXjXlXlXlXkXjXZX}.3 1 oXmXhXlXlXlXkXlXgXNXt.  z.BXgXlXkXlXlXkXzXcX{.L.G # I.NXhXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVXR.  > * O X & 1XnXjXlXkXjXnXC.@ B uXJXlXkXlXlXlXlXkXlXUXg.  V.UXkXkXlXlXkXzXpXuXFXUXV.  ] NXhXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXbX>X<.2.-.;   %.tXcXkXlXhXBXQ.    z D d (.NXhXlXlXjXmX+XW p   g ^ =XnXjXlXhXMX+X5 D G %   k.CXhXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXAXDXVXX.P vXbXjXlXlXjXMX].D K B M k (.NXhXlXlXhXMX Xb C K B B %XmXjXlXkXxXtX5.G N ( P.cXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXgXhXCXAXhXkXlXkXlXlXkXbXSXAXDXFXGXbXkXlXlXlXlXkXvXGXDXAXDXFXcXkXlXlXlXkXzXAXFXFXSXBXkXkXlXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXkXlXkXlXlXkXlXjXgXgXgXgXgXjXlXkXlXlXkXlXkXgXgXgXgXgXkXlXkXlXkXlXkXhXgXgXgXhXkXlXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXxXcXvXvXvXvXvXvXvXvXvXvXvXcXvXvXvXvXvXvXvXvXvXvXvXvXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX4.o.+.O.O.O.O.O.O.O.O.O.O.@.O.O.O.O.O.O.O.O.O.O.O.O.&.=.=.=.=.=.=.=.=.=.=.=.&.*.=.=.=.=.=.=.=.=.=.;.+.h.mXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXgXgXgXgXkXlXkXlXkXlXkX] I ' _ _ _ _ _ _ _ _ _ _ W _ _ _ _ _ _ _ _ _ _ _ _ C z c c c c c c c c c z C m x c c c c c c c c b s >.BXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXAXFXGXGXDXzXkXlXlXkXlXlX} } k.s.d.d.d.d.d.d.d.d.f.*.s.d.d.d.d.d.d.d.d.d.d.d.t   .               .   t ;                   X   &.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXpX_ A N v ! rXxXkXlXkXlXlX{ [ s.y.u.u.u.u.u.u.u.u.u.$.y.u.u.u.u.u.u.u.u.y.u.u.t   X . . . . . . . X   t :   . . . . . . . . o   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXtX& 5 W S Q wXcXjXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXuX- p ;.t.0XmXjXlXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXeXr j 9   6 <XbXjXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXwXkXMX}   a.CXhXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX6XwXVXGX$.  u.CXhXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXCXH.O A x   1 ;XnXjXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXrXp.E G =.:XmXjXlXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXAXGXGXSXbXjXlXkXlXkXlXlX} ] s.t.y.y.y.y.y.y.y.y.u.#.t.y.y.y.y.y.y.y.y.y.y.u.t   .               .   t :   .               o   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXgXgXjXlXkXkXlXkXlXlX{ } x.f.g.g.g.g.g.g.g.g.h.*.g.g.g.g.g.g.g.g.g.g.g.g.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXjXjXjXkXkXlXkXlXkXlXkX..Y ^ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ Q ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( N i d s s s s s s s d i N l p s s s s s s s s g q ,.VXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXvXbXbXbXvXlXkXlXlXkXlXjX@.l   .                   d                       ; y   O X X X X X X X O   y >   o X X X X X X X +   %.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX0X9X0X0XwXjXlXkXlXkXlXjX@.z   X . . . . . . . .   d X   . . . . . . . .   : r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXyX8   X   9 9XvXjXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXiX* v M.h.K.aXzXkXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXtX- = w n J.nXjXkXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXtX[ 9.-.%   ~.BXhXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXKXHXUX9.  8.CXhXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXmX}.k.<X;XZ   n.CXhXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXNX!.X @ o   W dXzXkXlXkXlXjX@.l   .                   d                       ; r   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXzX<XI.D.{.cXcXkXlXlXkXlXjX@.l   .                   d .                     : t   .               .   t ;                   o   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnXAXDXBXkXkXlXkXlXkXlXjX@.l   .                   d X . . . . . . . . X   > r   .               .   t >   X . . . . . . . O   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXgXgXhXkXlXkXlXlXkXlXjX+.v $ - = = = = = = = = * h                       - s # - = = = = = = = - # s -                   X   %.ZXhXlXlXlX",
"lXlXkXlXjXgXgXgXkXlXkXlXlXlXlXlXkXlXkXjXgXfXhXlXkXkXlXlXkXlXkXO.C r u y y y y y y y i 0 _ ~.U.Y.Y.Y.Y.Y.Y.Y.Y.R.J.n e u y y y y y y y u e m J.R.Y.Y.Y.Y.Y.Y.Y.Y.R.K.h.bXjXlXlXlX",
"lXlXlXkXvXAXGXDXzXkXlXlXlXlXlXlXlXlXkXmXDXGXZXkXlXlXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXkXxX3XF.h.m.pXzXkXlXlXlXlXlXkXkXlX%XN.d.I.zXkXkXlXlXkXlXjX@.z   X . . . . . . . O   ..UXGXKXKXKXKXKXKXKXJXUXmXy   X . . . . . . . X   u MXIXJXKXKXKXKXKXKXKXKXJXS.zXkXlXlXlX",
"lXkXhXVX(     : 4XvXjXlXlXlXlXlXkXxXaXa O   B xXkXkXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXkXzX:X,Xj * 8XvXjXlXlXlXlXlXkXlXfX:X{.o C vXkXkXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXlXjXMXcXf # 8XvXjXlXlXlXlXlXlXkXjXSX<X  N vXkXkXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXkXkXhXpXd # 5XxXjXlXkXlXlXlXkXlXjXxX%X  M zXhXkXkXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXlXjXNXVXj $ dXSXjXkXlXlXlXlXlXkXjXGX8X  Z HXnXjXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXjXvX).a.7 + q.Y.kXlXkXlXlXlXkXlXhXL.4.  y h.{.vXjXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXkXhXVXo.  > ,   G zXlXkXlXlXlXkXzXfXc   , :   2.VXhXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXkXlXfXaXpXpXaXdXlXlXkXlXlXlXkXlXkXdXaXpXpXaXgXlXkXlXkXlXjX@.z   X . . . . . . . O   ..UXHXLXLXLXLXLXLXLXJXUXMXy   X . . . . . . . X   u NXUXJXKXKXKXKXKXKXKXLXJXS.zXkXlXlXlX",
"lXlXlXkXzXcXxXxXxXxXkXkXlXlXlXlXlXkXlXxXxXxXxXcXzXkXlXlXkXlXjX@.l   .               o   X.UXLXIXUXUXUXUXUXUXPXUXVXt   .               .   y VXUXPXUXUXUXUXUXUXIXUXPXS.lXkXlXlXlX",
"lXlXkXlXkXkXkXkXkXkXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXlXkXlXkXlXjXO.B 7 q 0 0 0 0 0 0 0 w 2 ' $X|..X.X.X.X.X.X.X XoX_.v 8 e w w w w w w w e 8 b ].+XXXoXoXoXoXoXoXoXOX|.x.vXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXgXjXlXkXlXlXkXlXlX} ] a.t.y.y.y.y.y.y.y.t.u.o.=.;.-.-.-.-.-.-.-.-.-.:.g = < , , , , , , , < - g -                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXVXZXMXkXlXlXlXkXlXlX{ [ f.u.i.i.i.i.i.i.i.i.i.%.d.f.f.f.f.f.f.f.f.d.f.f.t   .               .   t :                   o   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXcX#.a 3.VXhXlXlXkXlXlX{ [ d.y.u.u.u.u.u.u.u.u.i.$.y.u.u.u.u.u.u.u.u.u.u.u.t   X               .   t :   .               o   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXAXz.    L AXgXlXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXMX*X> } . T AXgXkXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXbXz ' %X  E GXgXlXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXAXi.- qX^.  P bXhXkXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXAX}   @   @   m CXhXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX(.t.x.+.  r Y.cXjXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXMXZXLX6XW k.LXgXlXlXkXlXlX{ [ d.u.i.i.i.i.i.i.i.u.i.$.u.i.u.i.i.i.i.i.i.u.i.i.t   .               .   t ;                   X   %.ZXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXgXfXzXHXVXgXlXkXlXkXlXlX| { f.i.p.p.p.p.p.p.p.i.p.%.i.p.p.p.p.p.p.p.p.i.p.p.u   O X X X X X X X o   u ,   o X X X X X X X +   &.CXhXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXfXhXlXkXlXlXkXlXlX( / i.w.e.e.e.e.e.e.e.e.e.X.w.e.e.e.e.e.e.e.e.e.e.w.q   .               .   q -                   X   +.ZXgXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXw.<.r.w.w.w.w.w.w.w.w.w.w.5.w.w.w.w.w.w.w.w.w.w.w.w.@.[ } { { { { { { { } [ @...{ } { { { { { { { | ( k.MXjXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXnXnXvXvXvXvXvXvXvXvXvXvXvXbXvXvXvXvXvXvXvXvXvXvXvXvXNXVXVXVXVXVXVXVXVXVXVXVXNXBXVXVXVXVXVXVXVXVXVXVXCXnXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXjXjXkXkXkXkXkXkXkXkXkXkXkXjXkXkXkXkXkXkXkXkXkXkXkXkXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXkXkXlXkXlXkXjXkXlXkXkXlXkXjXlXkXlXkXjXkXlXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXmXvXjXlXlXkXbXmXjXkXlXlXkXzXvXkXlXkXlXmXvXjXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgX*X0XnXjXkXzX6X:XnXlXkXkXxXgX8XzXkXlXhX-XqXMXjXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXmX=XO.a I.VXlXrX&.Z #.VXhXkXVXK x mXgXNX).] k Y.CXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXCXF.9 !.VXhXfXUXw.) SXfXBXM.} L MXjXjXxXFXN G.AXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX,X{.n q.FXfXnX$.h :XxXkXlXH F & |.mXzX0Xj o.dXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX[. .*.,XvXzXyX( ' r.xXkXkXeXR.*.iXkXNX(.P  .T.NXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnXVXCXbXkXlXlXAXBXnXlXkXlXcXmXZXxXkXkXbXSXMXvXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXgXcXVXlXkXkXzXmXmXMXkXlXkXvXBXzXjXlXkXxXxXNXbXjXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXVX.XC 1XbXlXpX:.E L.mXgXMX!.A /.BXgXnX;X*.} #XmXjXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX=.8 &XNXlXtXqX9.B AXgXkXfXG j.FXgXlXdXa.> I.ZXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXFX0.T s h.CXfXMX.XU =XnXjXfXUX' k.HXgXkXkX*Xn v.SXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX Xg.u z.BXlXpXt j u.zXhXMXW.t C <XcXMXR...C P.VXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMXFXfXnXlXlXhXuX7X6XzXkXzXtX9X8XaXzXlXhX1XpXNXjXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXlXjXgXzXjXkXkXlXcXvXvXkXkXkXcXvXvXzXkXkXlXbXzXjXlXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXjXkXkXkXkXjXjXjXkXkXjXjXhXhXjXjXjXjXhXjXjXjXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXhXhXkXlXkXzXvXcXcXcXcXcXcXcXcXcXcXcXvXnXbXbXbXnXbXbXnXbXbXbXnXxXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXvXZXZXxXhXmX+X&.4.2.2.2.1.1.2.2.2.1.2.,.&.*.&.*.&.*.*.&.*.&.-...T.NXhXlXlX",
"lXlXlXlXlXlXlXlXlXkXcX0X(.Q.yXlXBX/.` e.7.7.8.6.-.8.7.7.6.e.'           % =       o   i.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXgXDXk.# [ uXlXNX).O.j.p.a.a.p.6.s.a.a.i.k.O.  .       * ;       o   s.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXjXMX|.r.D _.MXMX).X.f.y.u.i.y.4.i.u.u.y.g.X.  .       & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXjXbX].~.p B.ZXmX)...f.y.u.u.t.3.i.y.u.t.f...  .       * ;   .   o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXjXnX.X;.V.xXhXBX(.O.k.a.s.s.p.6.d.a.s.p.l.O.          & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXlXjXMXKXDXlXhXBX_.' 9.3.4.4.3.=.4.3.4.2.9.[ & ; ; ; = 4 7 * ; ; ,   g.AXgXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXiXqXhXjXMX X0 X # + + # 6 O @ + @ o 5 ; % & & # 1 3 # & & -   f.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXgXAXA.p o.0XzXmX X7   .     . 1           < O         & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXgXAXA.k ^ 3XxXmX X7   .     X 2       .   < +         * -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXkXxX,X0Xl x.AXbX X7   .     X 1           < O         & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXhXNXP.W { 0XzXmX X7   .     . 2 . o X o   1 O         & :   o X @   s.SXgXlXlX",
"lXlXkXlXhXgXkXlXkXlXkXvXgXMXvXgXMX X0 X @ + O # 3           1 & O + + o : -       o   a.SXgXlXlX",
"lXlXlXkXVXFXxXkXlXlXkXvXGXnXhXjXMX|.u : < , 2 # :..X^.).^. Xt.& 1 < < > 4 S.]./.(._.W._.nXjXlXlX",
"lXkXjXbXZ.+.8XvXjXjXnX-X..Y.NXfXMX X7   .   o   x.UXJXUXKXUXQ.  X       O tXUXPXIXUXKX=XzXkXlXlX",
"lXkXkXxX Xt |.NXjXkXzXiXE $.FXdXMX X7   .   O   l.UXFXKXGXUXE.  o   .   O wXUXHXKXLXGX*XxXkXlXlX",
"lXlXkXjXKXA &XCXhXlXdXUXs.;.UXsXMX X7   .   o   x.UXJXUXKXUXQ.  X       O tXUXPXIXUXKX=XzXkXlXlX",
"lXkXjXnXn.= X.fXzXhXbX;Xl a @XvXnX X8   o . +   z.UXGXLXHXUXW.  o       O wXUXHXJXKXFX*XxXkXlXlX",
"lXkXkXxX&XXXXXfXzXkXcX0X|.}.6XzXmX X7   .   o   x.UXJXUXKXUXQ.  X       O tXUXPXIXUXKX=XzXkXlXlX",
"lXlXlXkXMXBXBXzXkXlXkXxXZXLXbXgXNX[.B V V B C x 5.].Q.~.Q.[.e.= 3 1 2 < 6 q.k.f.g.j.t.T.MXjXlXlX",
"lXlXkXlXjXhXjXkXlXlXjXcXrX/.hXjXBX(.@.b.h.j.j.j.1.7.7.7.6.e.[   X . .   = -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXkXjXZX' : pXlXNX)...s.t.y.y.r.5.s.a.a.i.k.o.          & > . O o #   s.SXgXlXlX",
"lXlXlXlXlXlXlXlXkXhXZXz.&.Z 7XxXNX).X.g.u.u.i.y.4.p.u.u.y.g.X.          & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXkXhXBX%.G o B.BXmX).X.f.u.u.i.y.4.i.u.u.y.g.X.  X . .   * ;   . . O   s.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXcXqXx.uXlXBX(...h.u.i.p.u.4.p.i.i.u.h.X.          & -       o   a.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXcXAXxXhXBX'.X.u.q.w.w.q.1.w.q.w.0.u.O.1 6 5 5 3 e t 3 5 5 8 % l.AXgXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXkXkXgXkXkXlXfXqXqXqXqXqXqXwXqXqXqXqXqXeXyXyXyXyXyXyXyXyXyXyXyXtXsXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXvXcXcXcXcXcXcXcXcXcXcXvXcXcXcXcXcXcXcXcXcXcXcXxXcXzXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXjXhXkXlXlXkXhXjXlXkXkXlXjXjXlXkXlXjXhXkXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXBXBXlXkXkXxXZXmXkXlXlXjXbXmXkXlXkXNXCXlXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkX|. XgXlXzXuXR.:XbXkXjXnX2X*XcXkXzX.X/.lXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXu.8 V.ZXvXXXe.i $XmXlXzXx ` GXhXaXm.G =.GXgXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXmX9XB m.SXdXAX@X} pXlXNX3.E ^ nXhXxXMX%.T.VXhXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX6Xi.D d.ZXnX[.# +.9XcXzXg.P p iXxXcXV a /.bXjXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhX}.XXcXkXcX0X.X_.rXxXjXZXaX7XbXkXhX#X].%XvXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXBXIXcXkXjXMXUXIXcXkXkXcXGXMXjXlXlXHXUXZXjXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXxXaX7.1XvXvX<X2.N.jXjXnXOX1.2XbXjXxXG.r.$XbXjXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXNXB.1 }.VXxX1X).i OXMXlX0Xn E.ZXgXbXR.w q.DXgXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXNXXXF x y.ZXgXnXr.3.cXkXfXJX( L.AXhXkXeX_ -.DXgXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX0XI.P b.MXMX/.w X.,XcXmX_.x ..sXcXiX8.^ m.BXhXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXSXMXmXkXlXkXcXpXhXlXlXfXjXfXjXkXzXfXgXVXjXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXjXhXdXgXgXhXhXhXhXkXjXhXhXjXjXjXjXhXhXjXjXfXhXjXlXkXlXlX",
"lXlXlXlXlXlXlXlXkXlXkXkXkXkXlXkXMXVXBXBXBXBXBXBXBXBXBXBXNXMXMXMXNXNXNXMXMXMXNXvXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXkXlXxXcXlXkXzX.X!.^.^.^.^./.^.^.^.^./.[.{.[.[.{.].[.[.[.{.`.3XcXkXlXlX",
"lXlXlXlXlXlXlXlXkXkXlXaXqXhXlXxX%.| $.@.#.O. .$.@.@.$.| 4 > , , > 0 1 , , 2 o l.AXgXlXlX",
"lXlXlXlXlXlXlXlXhXZXR.8 <.hXlXlX5.u.h.f.g.p.w.h.f.d.j.0.#         , X     o   k.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXNX.X..! 5XvXlX2.0.i.u.i.e.6.i.y.y.a.5.$   . .   < o   . O   k.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXbX#XI.a |.BXkX2.9.i.y.u.e.5.i.y.t.p.4.#   .     , o     o   k.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXbX>Xw.Q.bXjXzX3.i.j.g.h.a.w.j.g.g.l.q.@         , X     o   j.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXjXMXUXJXlXkXxX:.' X. ...| { .. . .X.] 4 : , > : w < > > 1 X c.AXgXlXlX",
"lXlXlXlXlXlXlXlXkXxXeX^.).fXlXbXX.  .     + :         = - . O O X 2 @ o O #   k.SXgXlXlX",
"lXlXlXlXlXlXlXlXgXAXL.@ %.lXjXbXX.  X .   @ >   . .   - %         , X     o   j.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXbX,XH.N +XmXcXX.  .     + >         = %         , X     o   j.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXmX[.8.N :XbXvXX.  .     O < . O O . : %         < @ o O #   k.SXgXlXlX",
"lXkXlXlXgXgXlXkXkXxXuX(.0XnXhXbXX.  X .   @ >         = &   . .   < X     o   j.SXgXlXlX",
"lXlXkXlXAXZXkXlXlXjXnXUXBXhXkXbXO.* 1 < < ; -.x.f.g.k.w.4 > < 1 & C c.f.g.k.t.!.MXjXlXlX",
"lXkXlXlXh.l.vXkXjXvX6X>.].MXhXbXX.  .   X   ].UXKXPXUXyXO     o   Q UXLXIXUXKX>XxXkXlXlX",
"lXkXkXbXM.S mXjXkXlXkX( w.GXfXbXX.  .   X   `.UXFXHXUXeXO     o   W UXGXJXLXDX:XxXkXlXlX",
"lXlXjXBX&XD cXkXkXfXLXq.4.FXfXbXX.  .   X   ].UXKXLXUXyXO     o   Q UXKXIXUXJX>XxXkXlXlX",
"lXkXlXlX,.k K.MXgXbX1XK P 2XvXvXX.  .   X   ].UXKXPXUXyXO     o   Q UXLXIXUXKX>XxXkXlXlX",
"lXkXlXkXhXzXgXlXkXlXhXhXjXhXkXbXX.  o X O   ^.UXNXBXHX6X* @ $ &   ^ UXSXFXGXZX:XxXkXlXlX",
"lXlXkXlXlXlXlXkXlXlXkXMXnXlXkXzX<.&.<.,.<.-.4.p.u.y.a.6.1 = ; ; * r u e r u < n.ZXgXlXlX",
"lXlXlXkXkXkXkXlXlXgXFXg.Y vXkXlX3.t.f.s.f.i.7.i.u.y.a.5.#         , X     o   j.SXgXlXlX",
"lXlXlXlXlXlXlXlXjXmX#X) G xXkXzX2.0.i.y.u.e.7.p.u.u.s.6.#   .     < O . . +   k.SXgXlXlX",
"lXlXlXlXlXlXlXkXgXSX7.S 4 XXMXkX3.q.p.u.p.r.7.p.u.u.s.6.$   X X   < O . . +   k.SXgXlXlX",
"lXlXlXlXlXlXlXlXkXlXdX@Xp.pXzXlX<.0.p.u.i.e.5.p.u.y.a.4.@         > X     o   j.SXgXlXlX",
"lXlXlXlXlXlXlXlXlXkXzXmXSXzXkXzXw.q.i.u.i.r.9.i.u.y.p.8.f y i i y x p u i a 5 V.ZXgXlXlX",
"lXlXlXlXlXlXlXlXkXlXkXjXgXkXlXlXdXiXpXpXpXpXpXpXpXpXiXpXhXhXhXhXhXgXhXhXhXhXhXjXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXxXxXxXxXxXxXxXxXxXxXxXlXlXlXlXlXzXlXlXlXlXlXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXkXzXBXvXkXkXmXNXkXlXjXvXbXkXkXNXMXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXzXfX+X8XzXcX=X@XzXjXbX9X4XcXzX@X=XxXkXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXzX$.) NXjX@XU '.VXxX/ 0.GXfX'.K :XmXjXlX",
"lXlXlXlXlXlXlXlXlXlXkXlXhXl.Y xXMXR.Q 7XDXR.l } mXnXM.] sXzXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXcXwXc./.xXnXC.y.6XbXdX'.R.bXxXl.g.tXcXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXkXzXKXFXjXkXAXLXmXjXxXFXZXjXkXFXPXvXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXhXDXZ.y.CXzXI.o.;XNXrXo.$XnXvXN.o.yXcXkXlX",
"lXlXlXlXlXlXlXlXlXlXjXnX<XS ] MXlX9X' $XbXZX1.(.VXcX$Xz ;XmXjXlX",
"lXlXlXlXlXlXlXlXlXlXjXbX1X3.} hXCX5.T 0XbXaX~ i.MXhXN.} 2XbXjXlX",
"lXlXlXlXlXlXlXlXlXkXlXjXvXBXxXlXhXdXyXaXlXdXuXiXjXkXrXgXcXjXlXkX",
"lXlXlXlXlXkXlXjXjXlXkXcXnXvXnXnXmXMXNXMXbXbXmXmXbXvXmXbXvXcXkXlX",
"lXlXlXlXlXlXkXvXnXkXxXwX=X;X;X;X;X-X;X-X,X5X4X5X4X4X5X5X3XeXzXkX",
"lXlXlXlXkXkXzX9X2XfXVXB.| >.-.*.$.;.=.<.Q 4 0 8 r t 8 e - 7.AXgX",
"lXlXlXlXkXjXmXY ) gXVXC.6.h.d.i.e.f.p.x.)   X   # %   O   ;.SXgX",
"lXlXlXlXkXlXhXW.F XXJXV.<.i.t.w.7.y.e.f.^   o   $ *   +   :.SXgX",
"lXlXlXlXkXlXlXF.k.pXCXC.0.x.k.d.u.l.g.m.'   X   # %   O   ;.SXgX",
"lXlXlXlXlXkXkXHXKXjXVXB.D E T T T T Y W B * ; = 2 3 = ,   2.AXgX",
"lXlXlXlXkXkXbX2.e.jXCXb.  .   + *       - X     # &   O   ;.SXgX",
"lXlXlXlXkXkXxXe.K <XGXb.  o . # ; . o . : .     # &   O   ;.SXgX",
"lXlXjXkXkXlXhXK.^ ;XHXv.  .   + *       - .     # %   O   ;.SXgX",
"kXlXNXcXkXlXzXeXgXxXVXn.X & # = 4 * - = 5 % $ # : 3 * ,   2.SXgX",
"lXkX.X9XcXjXxX=X2XkXVXn.X % & . ].CXfXFXz.  = # = >XMXlXzX<XkXlX",
"jXBX:.x.GXdXVXz.;.SXMXn.  . .   &XUXGXUXV.  O   O uXUXLXUX9XjXlX",
"hXZXd.<.CXgXBXE._ xXVXb.  o O   $XUXSXUXN.  O   O eXUXFXKX7XjXlX",
"lXkXB.n.fXlXvXU.a.0XSXb.  . .   &XUXGXUXV.  +   O uXUXLXUX9XjXlX",
"kXlXZXAXlXlXjXZXIXkXBXB.F Q E I k.R.J.~.*.O > = < ..*.&. .B.MXhX",
"lXlXhXgXkXhXBX&X..kXBXZ.0.x.k.f.5.0.8.u.Q   .   # %   O   ;.SXgX",
"lXlXlXlXkXzXgXX.b 9XAXC.<.p.y.w.q.s.u.l.)   o   % ; o %   >.SXgX",
"lXlXlXlXkXxXpXv.Q :XFXN.1.a.u.e.8.i.t.h.^   .   # %   O   -.SXgX",
"lXlXlXlXlXkXzXZXnXlXNXH.5.d.p.y.w.a.u.h...6 e 0 u p 0 t > q.ZXgX",
"lXlXlXlXkXlXkXhXjXkXlXgXiXpXpXpXpXpXpXiXaXfXfXfXfXfXfXfXfXgXlXkX",
"lXlXlXlXlXlXlXkXkXlXkXzXxXxXxXxXxXxXxXxXxXzXzXzXzXzXzXzXzXzXkXlX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXkXxXrXaXdXeXcXuXkXqXgXlX",
"lXlXlXlXhXCXF.I.:Xc.tX&.lXu.6XbX",
"lXlXlXlXkXxX9XyX9X,XgX;XgX#XgXlX",
"lXlXlXkXjXVXF.!.4XA.dXZ.NXg.3XnX",
"lXkXlXjXhXmXoX:X7X|.xX^.cX_.iXcX",
"lXlXjXbXMXaXyXrXqXrX0XaX0XpXuXkX",
"lXjXMX].{.>X;.8.4.e.b & 0 + Y MX",
"lXjXMX}.R.>Xw.h.p.n.h   *   C MX",
"kXjXbX;X8X@Xe s h h 5 O <   K MX",
"lXzXBXE.V.*X  o +   @   %   Z MX",
"hXrXvXqXhXXX@ - :.f.l   G e.x.xX",
"dXd.mX`.!.=X  X eXUX!   7.UXlXdX",
"jX*XjXrXqX+Xt d `.iXL   ]  X_.kX",
"lXbXVX~.D.<X9.d.4.r.a   &   C MX",
"kXhXbX&XOX>Xw.f.s.b.S < p < ^ mX",
"lXlXjXmXNXgXiXpXiXpXiXuXiXuXaXlX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
