#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"                                                                                                                                                                                                ",
"      . O o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o O .       ",
"                                                                                                                                                                                                ",
"  .   d 9.-.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.:.>.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.:.>.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.,.9.p   .   ",
"  X   f V.d.9.e.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.e.9.k.g.9.e.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.e.9.k.g.9.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.e.5.Z.N   X   ",
"  .   c M k 4.$.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.#.5.f v 4.$.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.#.5.s m 3.$.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.#.2.z   X     ",
"  O   w.z.6.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX;.p.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX%.h.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUXw.  +     ",
"  o   ,.9.$.LXiXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXPX| 1.KXiXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXIX' 6.JXiXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXGX-.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXkXlXjXgXgXgXgXgXgXgXgXhXkXlXkXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXjXnXDXFXFXFXFXFXDXFXSXvXkXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXjXvX3XY.I.U.U.U.I.P.L.R.0XcXkXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXfXGXf.            .   O J.SXgXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXgXAXD.0 4 7 5 7 5 @ o q _.VXgXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXjXcX8X_.(.).).(.@.    E dXlXjXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXkXlXfXdXdXfXlXkXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXkXvXCXCXCXDXvXc   @ M.DXfXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXjXDXHXHXSXjXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXkXlXjXhXgXhXlXG.    Z pXlXjXkXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXgXZXL y t E SXfXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXkXkXlXzXN   . u.DXfXlXkXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXfXDXt     f GXdXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXkXcX).X   d 0XzXjXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXfXDXt     f GXdXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXkXlXjXmXI     :.FXdXlXkXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXgXZXS 8 6 L DXfXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXkXkXxX$X=   7 <XzXjXkXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXjXZXDXDXZXjXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXkXlXgXZX]     ] AXgXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXjXzX6Xw   - $XzXkXkXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXkXfXSX(     K MXjXlXkXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXkXjXbX~.N.A.;XlXkXkXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXjXAXJXGXmXkXlXkXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXkXkXlXhXgXgXjXlXkXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   >.9.#.KXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXuXPX| 1.JXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXPX' 6.HXiXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXFX=.  +     ",
"  O   e.h.3.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX*.y.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX+.d.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX9.  +     ",
"  .   k c f =.| ..............................................| -.p l =.| ..............................................} -.u x *.| ..............................................} &.h   X     ",
"  .   N A v u.1.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.1.i.l B u.1.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.1.i.h Z y.1.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.1.t.m   X     ",
"  O   e.h.3.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX*.y.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX+.d.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX9.  +     ",
"  o   ,.0.$.LXiXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXIX| 1.KXiXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXIX' 6.JXpXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXGX-.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXjXAXGXGXSXjXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXjXSXGXGXAXjXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXfXSXY 0 w H ZXgXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXgXZXH w 0 Y SXfXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXdXGXf     t DXfXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXfXDXt     f GXdXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXdXGXf     t DXfXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXfXDXt     f GXdXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXfXSXY 0 w H ZXgXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXgXZXH w 0 Y SXfXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXjXAXGXGXSXjXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXjXSXGXGXAXjXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   1.w.&.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX..4.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   >.9.#.JXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXLX} 1.JXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXPX' 6.HXiXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXFX=.  +     ",
"  O   e.j.2.UXGXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXFXUX&.y.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX+.d.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX9.  +     ",
"  .   h j m t.<.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.,.y.x f #.' [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ' #.t k @.' [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ` +.f   X     ",
"  X   M W   o                                                   o   U a.6.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.6.g.k S d.7.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.6.s.N   X     ",
"  O   6.I.  = + + + + + + + + + + + + + + + + + + + + + + + + + -   Z.UXHXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX+.d.UXJXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX9.  +     ",
"  o   *.b.  +                                                   @   g.DXpXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXiXIX' 7.JXpXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXuXGX-.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXkXlXhXfXgXgXgXgXgXgXjXlXkXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXjXCXJXGXGXGXGXGXHXMXjXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXhXmX].M.S.S.S.D.D.C.=XnXjXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXPXQ   o       +   2.PXdXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXLX_   * 3 3 4 7 > x.FXfXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXkXlXgXfXfXgXlXkXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXPX^   3 @X4X>X&X[.4XvXjXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXjXZXDXDXZXjXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXPX^   ; ( Y ) h.sXZXgXlXkXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXgXSXH 7 7 H SXgXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXPX!   o         f {.BXgXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXfXFXp     p FXfXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXsXIX^ @ E %.P X o   P tXxXjXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXfXFXp     p FXfXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXkXjXvX=XrXvXxXbXN.  . ; Q.ZXgXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXgXAXY t t Y AXgXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXkXcXmXjXhXgXnX4Xq     S.FXgXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXjXSXHXHXSXjXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXkXxXrX9XCXZXmXHX-X- X X H.DXgXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXkXlXfXdXdXfXlXkXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXhXBX(._ j.|.&X`.(     a #XMXhXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXgXVXT.1   7 k 7     . y.bXjXkXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXjXcX3X<.s X     X l z.aXxXjXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXjXvXgX=X'.Q.T./.1XmXxXjXlXkXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXkXlXkXzXMXZXSXDXAXmXjXjXlXkXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXkXkXkXkXjXhXhXgXhXjXkXlXkXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   -.M.  +                                                   @   k.JXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUX[ 9.UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXPX:.  +     ",
"  o   &.v.  +                                                   @   f.AXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXPX` 6.HXuXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXFX=.  +     ",
"  O   6.P.  @                                                   #   Z.UXGXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXFXUX+.s.UXGXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXFXUX8.  +     ",
"  .   c L   X                                                   X   G 7.-.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.=.q.f N 9.-.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.=.8.v   X     ",
"                                                                                                                                                                                                ",
"      X o                                                           o + + + + + + + + + + + + + + + + + + + + + + + + + + @ X X + + + + + + + + + + + + + + + + + + + + + + + + + + + X         ",
"                                                                                                                                                                                                ",
"                                                                                                                                                                                                "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"                                                                                                                                                                                ",
"      o + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + O         ",
"                                                                                                                                                                                ",
"  o   r.XXW.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.!.(.^.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.!.^.(.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.!._.G.  .     ",
"  .   d l M N N N N N N N N N N N N N N N N N N N N N N N V k v B N N N N N N N N N N N N N N N N N N N N N N B v k V N N N N N N N N N N N N N N N N N N N N N N N V p         ",
"  +   T.M rXdXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXtXJXE Z.BXiXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXiXBXZ.E JXtXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXgX:         ",
"  +   ~.B dXzXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXUX! G.HXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXHXG.! UXfXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXvX>         ",
"  +   ~.N sXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXUXQ F.GXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXGXF.Q UXdXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXkXlXjXdXdXdXdXdXdXdXdXjXlXkXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXjXmXKXKXKXKXKXKXKXKXmXjXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXhXmX+X0.9.9.9.9.9.8.0.$XnXjXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXfXFXf.  .             z.DXfXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXhXBX~.I P I L I 1   5 '.MXhXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXkXlXgXfXfXhXlXkXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXkXlXlXlXhXVX/.,   I NXhXkXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXjXZXHXHXBXjXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXkXlXlXlXhXVX .  * U.NXhXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXjXmXE.b.x.|.MXhXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXkXkXgXBXoX6   b cXjXkXkXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXHXB     %.LXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXkXjXMX6.    V.nXkXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXHXB     %.LXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXjXmX1Xw   i iXxXkXkXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXGXI * X 2.KXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXkXkXbXz.    g.bXkXkXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXkXvXbXbXcXkXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXkXkXcXpXa   8 <XmXjXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXkXlXkXkXkXkXlXkXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXkXnXS.    3.mXjXkXkXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXkXkXvXm   5  XBXhXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXkXkXkXuXuXsXkXkXlXkXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXkXcXcXxXlXkXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXkXkXkXkXlXkXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   R.M tXfXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXyXKXE Z.VXpXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXpXVXZ.E KXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXhX:         ",
"  +   +XS FXUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXGXUX' ^.UXLXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXLXUX^.' UXGXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXUX,         ",
"  .   V < E Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q E ' 8 n ) W Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q W ) n 8 ' E Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! +         ",
"  o   5.p Z.G.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.(.n -.W.D.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.D.W.-.n (.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.H.&         ",
"  +    XA BXHXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXVXUX) W.UXSXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXSXUXW.) UXVXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXKX,         ",
"  +   Q.N iXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXpXIXW D.SXfXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXfXSXD.W IXpXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXlX:         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXkXlXkXkXkXkXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXkXlXkXkXkXkXlXkXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXkXzXbXvXvXkXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXkXcXvXvXxXkXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXkXzXdXwXeXrXlXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXkXzXyXwXwXpXzXkXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXfXGXN.    1 bXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXHXB     %.LXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXfXGXB.  O 5 bXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXHXZ     =.LXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXfXGXN.    1 bXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXfXHXB     %.LXdXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXkXcX0X).[. XzXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXjXvX$X'._.<XvXjXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXkXvXZXCXVXkXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXjXNXCXZXnXjXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXkXlXkXhXhXhXlXkXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXkXlXjXhXhXjXlXkXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ~.N sXlXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXdXUXQ F.GXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   Q.N iXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXpXIXW D.SXfXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXfXSXD.W IXpXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXlX:         ",
"  +    XZ bXAXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXmXUX/ W.UXSXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXSXUXW.) UXVXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXKX,         ",
"  o   5.s ~._._._._._._._._._._._._._._._._._._._._._._.~.=XS *.W.D.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.D.W.-.n (.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.H.&         ",
"  .   Z -                                                 .   Z ( W Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q W ) n 8 ' E Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! +         ",
"  +   *Xj   + O O O O O O O O O O O O O O O O O O O O O O &   &XUXLXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXLXUX^.' UXGXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXUX,         ",
"  +   ~.a                                                 O   ~.mXpXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXpXVXZ.E KXyXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXhX:         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXkXlXkXhXhXhXhXhXhXhXkXlXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXkXvXZXVXCXCXCXCXVXlXkXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXgXSXH.- i e e e 0 v dXxXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXfXGXn.  +         > aXxXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXlXkXfXfXdXjXlXkXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXfXGXN.  1 n.K.S.c.c.hXzXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXkXzXJXHXKXvXjXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXfXGXM.  1 q.q.f.%XKXzXkXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXcXyXM Z g $XNXjXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXfXGXn.  +       % <.cXlXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXvXeX  o   [.CXhXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXgXGXB.$ ) <.I +     L.nXjXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXvXeX  o   [.CXhXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXkXkXxX0XrXBXvXVX2.    ^ BXhXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXxXpX$.=.| <XnXjXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXkXzXBXzXfXsXZXE.@   C VXhXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXkXzXPXLXIXvXjXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXkXxXuX~.aXSXnXGXe.    ! BXhXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXkXlXkXdXdXsXjXlXkXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXjXvXqXV q &.s.{ *     K.nXjXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXkXcXyXT   X       # 2.zXlXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXkXkXzXqXV.=.( ^ ;.'.nXlXkXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXkXzXVXFXKXKXFXnXjXkXlXkXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXkXkXlXkXgXfXdXdXfXhXkXlXkXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXcX>         ",
"  +   ).s                                                 O   _.ZXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXhXGXF.Q UXdXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXcX>         ",
"  +   _.s                                                 O   _.ZXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXGXF.Q UXdXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXcX>         ",
"  +   '.d                                                 O   '.DXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXKXH.! UXhXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXnX>         ",
"      = X                                                     = , : > > > > > > > > > > > > > > > > > > > > : , & + < : > > > > > > > > > > > > > > > > > > > > > > > .         ",
"                                                                                                                                                                                ",
"                                                                                                                                                                                ",
"                                                                                                                                                                                ",
"                                                                                                                                                                                "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"                                                                                                ",
"        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X         ",
"                                                                                                ",
"      , D v b b b b b b b b b b n Z b b b b b b b b b b b b Z n b b b b b b b b b b n n .       ",
"  .   a e.K.F.G.G.G.G.G.G.G.G.G.S.<.J.F.G.G.G.G.G.G.G.G.F.J.<.S.G.G.G.G.G.G.G.G.G.S.R...  .     ",
"  X   m P.SXbXmXmXmXmXmXmXmXmXNXxXx.CXnXmXmXbXbXbXbXmXmXnXCXx.xXNXmXmXmXmXmXmXmXmXcXUX5.  O     ",
"  X   b F.vXdXhXhXhXhXhXhXhXhXjXaXh.zXgXgXkXBXBXNXMXkXgXgXzXh.aXjXhXhXhXhXhXhXhXhXsXSX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXxXuX(./._.}.iXxXjXvXj.dXzXkXlXlXjXjXlXkXlXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXgXMX#X6 8 : O %XMXgXvXj.dXzXkXkXkXMXmXkXlXlXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXlXkXaXmXH n mXkXjXvXj.dXzXkXlXlX-X1XxXkXkXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXkXjXBX*X  K.AXgXjXvXj.dXzXkXlXxX> n ZXhXkXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXlXgXGX| e xXlXkXjXvXj.dXzXkXlXzXy.b.nXjXkXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXjXmX-X  l.SXgXlXjXvXj.dXzXkXkXkXDXAXjXlXlXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXjXNX].=.iXxXkXkXjXvXj.dXzXkXlXlXgXgXlXkXlXfXGX1.  O     ",
"  X   b G.mXhXkXkXkXkXkXkXkXkXzXdXj.vXjXlXjXmXGXzXkXlXkXjXvXj.dXzXkXkXkXkXkXkXkXkXfXGX1.  O     ",
"  X   n H.NXjXzXzXzXzXzXzXzXzXxXfXj.bXlXzXzXkXhXlXzXzXzXlXbXj.fXxXzXzXzXzXzXzXzXzXhXHX2.  O     ",
"  X   v A.xXaXdXdXdXdXdXdXdXdXfXuXd.jXsXdXdXdXdXdXdXdXdXsXjXd.uXfXdXdXdXdXdXdXdXdXiXCX,.  O     ",
"  .   w  .x.g.j.j.j.j.j.j.j.j.j.d.^ l.h.j.j.j.j.j.j.j.j.h.l.^ d.j.j.j.j.j.j.j.j.j.f.M.J   X     ",
"  X   n K.CXzXvXvXvXvXvXvXvXvXbXjXl.NXcXvXvXvXvXvXvXvXvXcXNXl.jXbXvXvXvXvXvXvXvXvXlXPX4.  O     ",
"  X   b F.nXgXjXjXjXjXjXjXjXjXlXsXh.cXhXjXjXjXjXjXjXjXjXhXcXh.sXlXjXjXjXjXjXjXjXjXdXFX1.  O     ",
"  X   b G.mXhXkXlXkXjXkXlXkXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXlXjXkXlXkXlXfXGX1.  O     ",
"  X   b G.mXhXlXkXlXbXxXkXlXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXkXkXvXcXkXlXlXfXGX1.  O     ",
"  X   b G.mXhXkXlXhXeXsXzXkXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXlXtXuXlXkXlXfXGX1.  O     ",
"  X   b G.mXhXjXNX*X  8.GXfXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXxX> n ZXhXkXfXGX1.  O     ",
"  X   b G.mXhXjXbX6XI K.VXhXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXzXo.7.MXjXkXfXGX1.  O     ",
"  X   b G.mXhXlXkXxXHXMXjXlXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXkXkXDXZXjXlXlXfXGX1.  O     ",
"  X   b G.mXhXkXlXkXfXjXlXkXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXlXgXgXlXkXlXfXGX1.  O     ",
"  X   b G.mXhXlXlXlXlXlXlXlXkXzXdXj.vXjXlXlXlXlXlXlXlXlXjXvXj.dXzXkXlXlXlXlXlXlXlXfXGX1.  O     ",
"  X   b D.cXsXgXgXgXgXgXgXgXgXhXiXg.cXhXjXjXjXjXjXjXjXjXhXcXh.sXlXjXjXjXjXjXjXjXjXdXFX1.  O     ",
"  X   b T.UXZXDXDXDXDXDXDXDXDXFXVXc.MXcXvXvXvXvXvXvXvXvXcXNXl.jXbXvXvXvXvXvXvXvXvXlXPX4.  O     ",
"  .   y J ( / ( ( ( ( ( ( ( ( ) W K c.g.j.j.j.j.j.j.j.j.h.l.^ d.j.j.j.j.j.j.j.j.j.f.M.J   X     ",
"  X   L h   .                 o   ^ BXiXdXdXdXdXdXdXdXdXsXjXd.uXfXdXdXdXsXsXsXdXdXiXCX,.  O     ",
"  X   P l   + o o o o o o o o #   ) FXhXzXzXzXzXzXzXzXzXlXbXj.fXxXzXzXxXcXvXcXzXzXhXHX2.  O     ",
"  X   P j   .                 o   ( DXgXkXkXkXkXkXkXkXkXjXvXj.dXzXkXlXfXpXuXaXkXkXfXGX1.  O     ",
"  X   P j   .                 o   ( DXgXlXkXlXlXlXkXlXlXjXvXj.dXzXhXCX/ 2 u z aXxXfXGX1.  O     ",
"  X   P j   .                 o   ( DXgXlXkXlXxXzXkXlXlXjXvXj.dXzXhXSXV i 8.!.vXkXfXGX1.  O     ",
"  X   P j   .                 o   ( DXgXjXvXtX& o.DXgXlXjXvXj.dXzXhXVX/ l 2 k wXcXdXGX1.  O     ",
"  X   P j   .                 o   ( DXgXkXcXuXl 7.ZXgXlXjXvXj.dXzXkXlXcXUX+X  S.SXaXGX1.  O     ",
"  X   P j   .                 o   ( DXgXlXkXlXAXMXjXlXlXjXvXj.dXlXcXeX>.G. .  {.NXsXGX1.  O     ",
"  X   P j   .                 o   ( DXgXkXlXkXhXjXlXkXlXjXvXj.dXlXlXhX-.k k M.nXjXfXGX1.  O     ",
"  X   P j   .                 o   ( DXgXlXlXlXkXkXlXlXlXjXvXj.dXzXkXzXAXVXCXVXkXlXfXGX1.  O     ",
"  X   L h   .                 o   ^ CXaXfXfXfXfXfXfXfXfXdXlXf.iXhXfXfXsXdXsXsXfXfXpXZX,.  O     ",
"  X   E z   .                 o   [ UXAXGXGXGXGXGXGXGXGXFXPXM.CXHXGXGXGXGXGXGXGXGXZXUX0.  O     ",
"  .   y 3                     .   s 9.<.1.1.1.1.1.1.1.1.1.4.J ,.2.1.1.1.1.1.1.1.1.,.0.M   X     ",
"                                                                                                ",
"      .                           . O O O O O O O O O O O O X O O O O O O O O O O O O X         ",
"                                                                                                ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"                                                                                        ",
"        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X         ",
"                                                                                        ",
"      : N k l l l l l l l l k v b k l l l l l l l l k b v k l l l l l l l l z z X       ",
"  .   p h.^.R.W.W.W.W.W.W.E./.n.f.).R.W.W.W.W.W.W.R.).f.n./.E.W.W.W.W.W.W.T.'.:.  .     ",
"  X   x /.DXbXMXMXMXMXMXMXnXGX&X(.KXbXmXvXvXvXvXMXbXKX(.&XGXnXMXMXMXMXMXMXvXUXg.  O     ",
"  X   l R.bXdXhXhXhXhXhXhXfXmXXXE.NXdXjXSXFXSXZXjXdXNXE.XXmXfXhXhXhXhXhXhXsXAXi.  o     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.VXkXsXo.Y ) ;.sXkXVXW.oXNXjXlXkXhXkXlXkXgXFXp.  O     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.CXjXfXd.i.i j vXhXCXW.oXNXjXkXzXAXbXjXlXgXFXp.  O     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.CXhXkXHXMX7 A.SXdXCXW.oXNXhXbX8Xe H.ZXgXgXFXp.  O     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.CXhXgXSXy.0 zXlXgXCXW.oXNXhXbX9Xd L.ZXhXgXFXp.  O     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.CXgXxXpX< p.DXgXhXCXW.oXNXjXkXzXDXnXjXlXgXFXp.  O     ",
"  X   l W.MXhXlXlXlXlXlXlXjXNXoXW.CXgXmX*X@.tXcXkXhXCXW.oXNXjXlXkXgXjXlXkXgXFXp.  O     ",
"  X   l R.nXfXjXjXjXjXjXjXgXMXXXE.BXgXhXxXDXlXhXjXfXBXE.XXMXgXjXjXjXjXjXjXdXSXi.  O     ",
"  X   x ).GXmXNXNXNXNXNXNXMXJX*X_.LXmXBXNXnXNXBXNXmXLX_.*XJXMXNXNXNXNXNXNXbXUXh.  O     ",
"  X   a k.&X.XoXoXoXoXoXoXXX*XS.l.;X.XoXoXoXoXoXoX.X;Xl.S.*XXXoXoXoXoXoXoX X<X;.  o     ",
"  .   y e.(.E.W.W.W.W.W.W.E._.l.r.'.E.W.W.W.W.W.W.E.'.r.l._.E.W.W.W.W.W.W.R.{.o.  X     ",
"  X   c `.KXNXCXCXCXCXCXCXBXLX;X'.UXNXCXCXCXCXCXCXNXUX'.;XLXBXCXCXCXCXCXCXMXUXj.  O     ",
"  X   l R.bXfXhXhXhXhXhXhXfXmX.XE.NXfXhXhXhXhXhXhXfXNXE..XmXfXhXhXgXhXhXhXsXAXi.  o     ",
"  X   l W.MXhXlXkXzXzXkXlXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXjXkXlXzXlXkXlXgXFXp.  O     ",
"  X   l W.MXhXlXlXkXkXlXkXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXjXlXkXkXkXlXkXgXFXp.  O     ",
"  X   l W.MXhXhXZXv V SXhXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXgXnX4X  b.DXgXgXFXp.  O     ",
"  X   l W.MXhXjXMXq.y.NXjXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXhXvXeX] `.NXhXgXFXp.  O     ",
"  X   l W.MXhXlXjXSXAXjXlXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXjXkXxXJXmXjXlXgXFXp.  O     ",
"  X   l W.MXhXkXlXgXgXlXkXjXNXoXW.CXhXlXlXlXlXlXlXhXCXW.oXNXjXlXkXfXjXlXkXgXFXp.  O     ",
"  X   l T.bXdXhXhXhXhXhXhXfXnX.XE.NXfXhXhXhXhXhXhXfXNXE..XmXfXhXhXhXhXhXhXsXAXi.  o     ",
"  X   c `.KXBXZXZXZXZXZXZXVXPX;X'.UXNXCXCXCXCXCXCXNXUX'.;XLXBXCXCXCXCXCXCXMXUXj.  O     ",
"  .   y w./.T.E.E.E.E.E.E.R.(.j.r.'.E.W.W.W.W.W.W.E.'.r.l._.E.W.W.W.W.W.W.R.{.o.  X     ",
"  X   n e   .               X   j.;X.XoXoXoXoXoXoX.X;Xl.S.*XXXoXoXoXoXoXoX X<X;.  o     ",
"  X   K f   O X X X X X X X +   (.PXnXNXNXNXNXNXNXmXLX_.*XJXMXNXVXCXCXVXNXbXUXh.  O     ",
"  X   G p   .               X   R.VXfXjXjXgXhXjXjXfXBXE.XXMXgXjXsXtXeXsXkXdXSXi.  O     ",
"  X   G a   .               X   E.ZXhXkXlXnXvXkXlXhXCXW.oXNXhXvXF f s x.ZXaXFXp.  O     ",
"  X   G a   .               X   E.ZXhXlXkX4XeXxXkXhXCXW.oXNXhXbXa l <.7XvXdXFXp.  O     ",
"  X   G a   .               X   E.ZXgXzXkX$ o.HXfXhXCXW.oXNXhXxX5.=.> X.VXsXFXp.  O     ",
"  X   G a   .               X   E.ZXgXlXkXb.`.mXjXhXCXW.oXNXlXpXdXUX..w mXfXFXp.  O     ",
"  X   G a   .               X   E.ZXhXkXlXDXNXjXlXhXCXW.oXMXcX6Xm n @ s.BXsXFXp.  O     ",
"  X   G a   .               X   E.ZXhXlXkXgXhXlXkXhXCXW.oXNXjXzX:XI.$XmXkXfXFXp.  O     ",
"  X   F p   .               X   Y.NXsXgXgXgXgXgXgXsXMXR. XbXdXfXcXBXvXdXgXaXZXu.  o     ",
"  X   P f   .               X   [.UXAXFXFXFXFXFXFXAXUX{.<XUXSXFXSXAXSXFXFXZXUXz.  O     ",
"  .   i 3                   .   X.k.i.p.p.p.p.p.p.i.j.o.;.h.i.p.p.p.p.p.p.u.z.T   X     ",
"                                                                                        ",
"      .                         X O o O O O O O O o O X o O O O O O O O O o O X         ",
"                                                                                        ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"                                                                ",
"    ; & & & & & & & % ; & & & & & & & % ; * % & & & & & % - X   ",
"  # 3.D.V.C.C.C.C.C.A.w.B.Z.V.B.B.V.C.D.r.n.A.C.C.C.C.V.H.9.    ",
"  & F.AXbXmXmXmXmXnXBXQ.cXmXVXJXFXZXvXSX(.aXVXnXmXmXmXvXKXQ.  o ",
"  & C.bXgXjXjXjXjXhXzXU.sXxX7X~.}.1XjXbXW.qXzXjXgXfXjXfXVXU.  X ",
"  & C.mXjXlXlXlXlXkXcXY.sXBX).` 9 X.AXvXQ.eXvXjXMXCXjXhXZXY.  X ",
"  & C.mXjXlXlXlXlXkXcXY.fXkXbXGXN `.NXbXQ.eXlXSXv.] CXdXZXY.  X ",
"  & C.mXjXlXlXlXlXkXcXY.fXjXAXz.S ZXfXmXQ.eXzXNX).v.MXfXZXY.  X ",
"  & C.mXjXlXlXlXlXkXcXY.fXkXNX` U.ZXfXMXQ.eXvXhXNXSXjXhXZXY.  X ",
"  & C.nXhXkXkXkXkXjXxXY.dXlXhXkXcXjXhXmXW.wXxXkXhXgXkXgXCXU.  X ",
"  & S.BXzXcXcXcXcXxXmXE.kXvXcXvXxXcXzXVX^.yXmXcXcXcXcXlXFXR.  X ",
"  # :.Q.U.Y.Y.Y.Y.Y.E.7.P.T.Y.Y.Y.Y.U.!.q.D.E.Y.Y.Y.Y.I.(.7.  X ",
"  % N.xXsXfXfXfXfXdXkXP.pXgXfXfXfXfXsXcXR.9XkXfXfXfXfXaXNXP.  X ",
"  & Z.MXkXzXjXkXzXlXvXT.gXxXzXzXzXzXkXNX!.rXvXzXkXjXzXjXAXT.  X ",
"  & C.mXjXjXDXBXjXkXcXY.fXzXkXkXkXkXjXMXQ.eXvXhXBXDXjXhXZXY.  X ",
"  & C.mXgXBX3.H.CXgXcXY.fXzXkXlXlXlXjXMXQ.eXzXCXH.3.BXfXZXY.  X ",
"  & C.mXgXBX3.H.CXgXcXY.fXzXkXlXlXlXjXMXQ.eXzXCXH.3.BXfXZXY.  X ",
"  & C.mXjXjXDXBXjXkXcXY.fXzXkXlXlXlXjXMXQ.eXvXhXBXDXjXhXZXY.  X ",
"  & B.cXdXgXsXdXgXfXkXI.dXkXjXjXjXjXgXnXW.qXzXjXgXfXjXfXVXU.  X ",
"  % K.UXAXDXDXDXDXSXKX(.cXNXMXMXMXMXnXDX).aXVXmXMXMXMXvXLX!.  o ",
"  & X.g.a.s.s.s.s.s.s.-.Q.Q.Q.Q.Q.Q.W.).r.J.^.Q.Q.Q.Q.E.].q.  X ",
"  7 x   .         X   D gX0XeXeXeXeXqXaXJ.,XyXwXeXrXeX0XhXS.  X ",
"  8 M   + o o o o @   P DXlXvXzXzXvXzXVX^.yXmXcXvXgXkXzXFXE.  X ",
"  8 b   X         o   J CXhXhXCXCXhXjXmXQ.wXnXeXZ J Z.mXBXY.  X ",
"  8 b   X         o   J CXfXBXH.H.BXgXMXQ.wXMX0Xw b U.nXVXY.  X ",
"  8 b   X         o   J CXdXDX3.3.DXfXMXQ.wXbXuXpXg.f bXCXY.  X ",
"  8 b   X         o   J CXhXjXBXBXjXjXMXQ.qXBX-X@.C *.mXVXY.  X ",
"  8 b   X         X   H NXdXhXfXfXhXfXvXE.0XlXfXXX}.zXfXBXI.  X ",
"  0 M   X         o   I UXBXZXZXZXZXVXLX].hXFXZXLXPXCXBXUX(.  o ",
"  1 p   .         X   z /.I.Y.Y.Y.Y.U.!.q.S.E.Y.I.I.Y.I.(.7.  X ",
"                                                                ",
"                        o X X X X X X o X X X X X X X X o X     "
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
". @ + + + @ @ o X + # + + + @ . ",
"+ B.@X[.XXU.).+X&X].P..X}.@XA.  ",
"+ @XHXnXAX7XvX Xn.mX4XCXlXHX=X  ",
"+ [.nXsXzX-XhX_.9.vX%XzXG.lXoX  ",
"+ XXAXzXNX2XlX,XrXbX,XmXcXAX#X  ",
"O L.8X-X3X`.#X7X4X=X(.2X-X8XT.  ",
"+ (.kXfXsX$X7XiXuXeX+XaXfXkX].  ",
"+ XXMXXXMX1XpXbXcXhX>XnXoXMX#X  ",
"+ }.xX{.xX:XiXcXzXgX;XbX.XnX+X  ",
"O @XPXSXFX7XwXhXgXiX&XhXjXbX X  ",
"* J J H F ^ =X;X;X&X!.<X7X6XP.  ",
"< 4   X   s vXvXvXhX1XhXv.hX&X  ",
", 6   +   a mX X.XlX-XpXL U.:X  ",
"< 5   o   d CXbXnXbX6XMXJ.8X1X  ",
"; <   X   e +X+X+X XI.@X%X<XA.  ",
"                                "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
