#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXjXfXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXfXjXlXkXlX",
"lXlXjXmXKXGXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXGXKXmXjXlXlX",
"lXjXmX>Xl.V.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.V.l.>XmXjXlX",
"lXgXHXN.  @                                                                                                                                                                         @   N.HXgXlX",
"lXgXHXN.  @                                                                                 + @ +                                                                                 X -   V.GXgXlX",
"lXhXAXE.#.Q.D.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.D.E.+.s.U.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.S.W.7   & w.6.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.9.,._ q.6.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.5.y.~     N.HXgXlX",
"lXjXVX].!.UXAXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXAXUXD.6XUXDXFXFXFXFXFXFXFXFXFXFXFXFXFXFXFXCXUXd   > $X|..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XOX^.g.$X|..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X}.:Xy.    N.HXgXlX",
"lXhXCX_.S.VXsXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXsXVXc.@XbXfXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXZXp   ; _.W.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.^.H.w.).E.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.R.}.5.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.^.~.~.!.!.!.~.~.^.~.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.~.^.`.[.{.[.(.~.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~.^.~.H.b.l.b.U.).~.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~./.R.6     o V A._.!.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~./.U.l @.>.h   | [.!.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~.^.!.W.|.@X>.  ] _.~.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.~.^.Q.(.S.t $ p.[.Q.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.~.~._.C.e % 3.(.~.~.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~.~.(.k.< < d.}._.~.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~./.U.%   7 A k +.W./.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.~./.L.# * * *   I R./.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.~.^.`.`.`.`.`.).^.~.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.^.~.~.~.~.~.~.~.~.^.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.(.L.r.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   ; /.T.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.R.!.F.q./.T.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.Y.[.3.    N.HXgXlX",
"lXjXCX`.F.VXdXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXsXVXv.#XbXfXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXaXAXp   > -XOX+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X%X_.k.=XOX+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XoX2Xp.    N.HXgXlX",
"lXjXCX_.I.UXNXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXNXUXM.<XLXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXmXUXs   @ A V C C C C C C C C C C C C C C C C Z M g A V C C C C C C C C C C C C C C C V D s     N.HXgXlX",
"lXjXBXXX1.z.f.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.f.j.9.i.h.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.s.n.3                                                                                       @   N.HXgXlX",
"lXjXVX].m.yX1X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X1XtXk.`.qX3X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X,XpXt   .                                       X X .                                       @   N.HXgXlX",
"lXjXCX_.K.KXxXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXxXKXn.-XSXvXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXzXIXa   ; E.K.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.Y.C.    M `.G.L.L.L.L.L.L.L.L.L.L.L.L.L.L.J./.,.    N.HXgXlX",
"lXjXCX`.G.AXgXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXgXAXb.$XMXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXDXp   : }.(.).).).).).).).).).).).).).).).].Y.    Z &X!.).).).).).).).).).).).).).)./.+X9.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.).L.    C +XR.~.~.~.~.~.~.~.~.~.~.~.~.~.~.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXkXlXjXfXdXdXfXjXlXkXlXlXlXfXFXp   : '.!.^.^.~.^.!.W.W.W.Q.~.^.~.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXkXbXGXIXLXDXzXkXlXkXlXlXfXFXp   : '.!.^.^.^.~.'.XX+XOX[.!.^.^.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXjXvX4Xm.7.e.N.rXzXkXlXlXlXfXFXp   : '.!.^.~.~.(.c.;.{ O.i.(.!.~.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXfXGXx.+ : X   E zXkXkXlXlXfXFXp   : '.!.^.~.W.|.s   &   * %.{.Q.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXjXbX<X{.7XXX= o 8XzXkXlXlXfXFXp   : '.!.^.~.!.'.#.w.Z.$.  f !.!.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXgXCX6XA.:.O G jXlXkXlXlXfXFXp   : '.!.^.~.^.~./.{..Xv.  k (.Q.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXkXfXZXl.+   % v.nXkXlXlXlXfXFXp   : '.!.^.^.^.~.^.(.H.q # 7.'.Q.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXkXbXxXpX|.< & &XxXkXlXlXfXFXp   : '.!.^.^.^.~.).B.8 % 9.{.!.~.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXkXlXgX,X4XsXaXq   !.vXjXlXlXfXFXp   : '.!.^.~.!.(.h.1 + 7.R.I.!.^.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXkXkXzX`   c =   n iXlXkXlXlXfXFXp   : '.!.^.~.W.{.u   o < @ f S.(.!.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXkXkXxX^. .Y ) e.9XxXkXlXlXlXfXFXp   : '.!.^.~.Q.'.~ x m n z T H./.!.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXkXMXKXIXLXSXlXkXlXkXlXlXfXFXp   : '.!.^.^.^.~.XX@X@X@X#XoX(.~.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXkXkXlXhXdXsXsXfXjXlXkXlXlXlXfXFXp   : '.!.^.~.~.^.W.R.E.E.R.W.~.^.~.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXgXAXb.%XNXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXfXFXp   : '.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.).L.    C +XE.~.~.~.~.~.~.~.~.~.~.~.~.~.~.Q..X7.    N.HXgXlX",
"lXjXCX`.H.DXjXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXhXDXb.&XBXkXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXgXGXa   : ].~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^._.P.    C @XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.D.BXaXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXaXBXv.@XvXdXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXpXCXp   ; _.W.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q./.J.    V oXT.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.E.|.5.    N.HXgXlX",
"lXjXNXoX:.p.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.y.7.w.y.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.e.h.2   & t.9.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.w.2.    d d.6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.p./     N.HXgXlX",
"lXjXCX_.J.HXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXHXn.*XZXxXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXkXKXa   : [.^./././././././././././././././.`.I.    C $XW././././././././././././././.~.oX8.    N.HXgXlX",
"lXjXCX`.G.AXgXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXfXZXv.$XMXhXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXdXDXp   : '.!.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.).L.    C +XR.~.~.~.~.~.~.~.~.~.~.~.~.~.~.W. X6.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXAXb.%XNXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXfXFXp   : '.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXgXAXv.$XmXhXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXdXDXp   : '.Q.~.~.~.~.~.~.~.~.~.~.~.~.~.~.!.(.K.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.ZXfXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXdXJXC.,XHXMXNXNXNXNXNXNXNXNXNXNXNXNXNXNXNXvXUXs   : XX`.].].].].].].].].].].].].].].'.|.E.    C +XR.~.~.~.~.~.~.~.~.~.~.~.~.~.~.W. X6.    N.HXgXlX",
"lXjXCX_.L.UXbXNXNXNXNXNXNXNXNXNXNXNXNXNXNXNXmXBXjX8.R.2X*X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X$X9Xr   = A.m.N.N.N.N.N.N.N.N.N.N.N.N.N.N.M.C.k.    Z &X~._._._._._._._._._._._._._._./.@X0.    N.HXgXlX",
"lXjXVX[.z.2X#X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%XOXqX'   O                                       o X o                                       X   n Q.V.S.S.S.S.S.S.S.S.S.S.S.S.S.S.Z.T.=.    N.HXgXlX",
"lXjXBX.X6.V.v.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.z.H.J   @                                                                                   X   h v.t.i.i.i.i.i.i.i.i.i.i.i.i.i.i.u.z.]     N.HXgXlX",
"lXjXCX).U.UXVXAXAXAXAXAXAXAXAXAXAXAXAXAXAXAXMXUX,.    H ~ W W W W W W W W W W W W W W W W W Q m E W W W W W W W W W W W W W W W W W ! U     A ;X(.].].].].].].].].].].].].].]._.%Xw.    N.HXgXlX",
"lXjXCX`.F.VXsXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXiXJX%.    I.-XOX+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X$Xd.oX@X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X&X`.    V OXT.!.!.!.!.!.!.!.!.!.!.!.!.!.!.E.|.6.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    b.(.R.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.R.Q.7.T.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.~.G.    C +XE.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.^.^.~.~.~.~.~.~.^.^.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.^.~.~.~.~.~.~.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.^.~.^././././.^.~.^.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~.^././././.^.~.^.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.^.~.^.!.E.W.!.(.~.^.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~.^.~.E.E.W.^./.~.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.Q.{.6.5 & o a a.).~.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~./.!.Z - X & T H.).!.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.W.XX{ 3 ) v   ; Y.^.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~./.Q.F / ` t   o.}.Q.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.~.(.J.Q.}.).,   N./.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~.^.{.!.W.(   @.].!.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.~.~.^.R.'.e.O t !.^.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~.~.(.P.M ;   d A.'.Q.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.^.~.Q.'.r.& 6 l.(.~.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~./.U.X.P q < e.).!.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.~.!.(.,.+ v G.+X(.~.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~.~.XX=X4X4.  L R./.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.Q.}.<.o # I X.{ Z./.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~./.v.V X.#.l   / ).~.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.W..X(   O     o r.).~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~.(.m.1 .   # L S.).!.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.~.~./.I.Z.A.Z.Z.A.R.^.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.~.^.~.P.A.A.H.W.(.~.^.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.^.~.).'.`.'.'.'./.~.^.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.~.^._.`.'._./.~.^.^.~.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    N.].~.^.~.^.~.~.~.~.~.~.~.^.~.^.^.^.~./.0.Q.^.~.^.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).L.    C +XE.^.^.^.~.~.~.~.~.~.~.^.~.^.^.Q..X7.    N.HXgXlX",
"lXjXCX`.G.SXhXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXsXPX&.    b.).E.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.E.!.7.R.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.H.    V .XU.W.W.W.W.W.W.W.W.W.W.W.W.W.W.T.{.4.    N.HXgXlX",
"lXjXCX`.F.VXdXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXpXJX%.    L.=XoXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXoX@Xs..XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXoX$X).    F 5X}.OXOXOXOXOXOXOXOXOXOXOXOXOXOX.X<Xi.    N.HXgXlX",
"lXjXCX`.T.UXVXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXMXUX2.  O | ,.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.;.E =.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.:.#.O   d 5.&.-.-.-.-.-.-.-.-.-.-.-.-.-.-.=.3.R X   V.GXgXlX",
"lXhXCX'.4.T.F.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.A./.P   o                                                                                                                               @   N.HXgXlX",
"lXkXcXrX'.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`._.[.L.n.N.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.N.M.B.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.C.V.l.>XmXjXlX",
"lXlXkXcXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXVXDXJXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXHXGXKXmXjXlXlX",
"lXkXlXkXhXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXhXjXgXfXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXfXjXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXgXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXfXlXkXlXlX",
"lXlXjXSXLXJXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXKXGXkXlXlXlX",
"lXgXSX>.m K G G G G G G G G G G G G G G G G G F G G G G G G G G G G G G G G G G G G D D F G G G G G G G G G G G G G G G G G F G G G G G G G G G G G G G G G G G G F V ^ nXjXlXlX",
"lXdXKXD   o                                                                                                                                                           6 MXjXlXlX",
"lXfXGX( a C M M M M M M M M M M M M M M M N m t N M M M M M M M M M M M M M M M N b o   8 k d f f f f f f f f f f f f f f h y i g f f f f f f f f f f f f f f d k 1   0 MXjXlXlX",
"lXhXBXB.jXIXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXJXZXN.PXFXGXGXGXGXGXGXGXGXGXGXGXGXGXGXPXcXX   1.<X}.XXXXXXXXXXXXXXXXXXXXXXXXXX X%XV.P.$X.XXXXXXXXXXXXXXXXXXXXXXXXXXX{.2XQ   0 MXjXlXlX",
"lXhXVXx.3XlXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXgXiXf.kXdXfXfXfXfXfXfXfXfXfXfXfXfXfXfXlX9XX   $.|.T.W.W.W.W.W.W.W.W.W.W.W.W.W.E.).h.m./.E.W.W.W.W.W.W.W.W.W.W.W.W.W.Y..XI   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.^.~.!.Q.Q.!.~.^.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.^.~.^.'.|. X].~.~.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.^.!.N.y.e.z./.^.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~._.D.O o . # | '.!.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.(.J.{ v.s.* ; I.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.^.~.^._. X(.< < Q.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.^.^.!./.W.n   2.`.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.~.(.L.z ; i.+X/.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.(.I.d   G 2.,.L./.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~._.V.  . .   - c._.!.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.~.^.!.H.F.D.F.H.Q.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.^.!.'.l.B.`.~.^.^.~.^._._.`.`._.^.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   &.XXW.~.~.~.~.~.~.~.~.~.~.~.~.~.!.'.l.B.`.~.~.~.~.~.~.~.~.~.~.~.~.~.~.E.+XU   0 MXjXlXlX",
"lXhXVXv.7XvXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXdXh.cXjXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcXwXX   *.oXQ./././././././././././././.~.].z.V.'.^./././././././././././././.W.@XY   0 MXjXlXlX",
"lXhXVXc.eXVXbXnXnXnXnXnXnXnXnXnXnXnXnXnXnXmXlXk.BXvXnXnXnXnXnXnXnXnXnXnXnXnXnXbXBXpXX   &..XE.!.!.!.!.!.!.!.!.!.!.!.!.!.Q.`.k.N._.Q.!.!.!.!.!.!.!.!.!.!.!.!.!.R.oXU   0 MXjXlXlX",
"lXhXVXv.OX8X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X4X,Xs.7X2X3X3X3X3X3X3X3X3X3X3X3X3X3X3X7X$X    @ = * * * * * * * * * * * * * * * & + @ * * * * * * * * * * * * * * * * = +   6 MXjXlXlX",
"lXhXBXm.g.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.0.m.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.h.                                                                                  6 MXjXlXlX",
"lXhXVXc.pXFXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXZXnXl.FXVXCXCXCXCXCXCXCXCXCXCXCXCXCXVXFXhX    n X.` ] ] ] ] ] ] ] ] ] ] ] ] ` ..A     E } ' ] ] ] ] ] ] ] ] ] ] ] ] _ o.i   8 MXjXlXlX",
"lXhXVXv.5XxXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXaXh.zXgXhXhXhXhXhXhXhXhXhXhXhXhXhXgXzX0XX   2.2X XOXOXOXOXOXOXOXOXOXOXOXOX.X,Xs.    I.*XoXOXOXOXOXOXOXOXOXOXOXOXOX|.5X!   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   $.}.Y.E.E.E.E.E.E.E.E.E.E.E.E.T.].7.    n.(.R.E.E.E.E.E.E.E.E.E.E.E.E.U. XI   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXkXlXjXdXdXdXgXkXlXkXlXkXvXeXX   *.XXW.^.~.^.Q.W.E.W.!.^.~.~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXjXnXJXPXKXBXkXlXlXlXkXvXeXX   *.XXW.^.^.~.].oX+XXX).~.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXjXnX#X5.X.-.W.lXkXkXlXkXvXeXX   *.XXW.~.~.(.t.) Y [ C.(.~.~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXfXFXu.9 l #   P.VXhXkXkXvXeXX   *.XXW.~.!.'.9 = 4   q J.).~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXkXzXpXiXvXl.  f.VXhXkXkXvXeXX   *.XXW.~.~.^.a.K.).H   d._.~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXkXlXgXCXv.m % d <XmXhXlXkXvXeXX   *.XXW.^.^.~.(.`./.l . A.).~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXkXjXnXD.[ g 8 ).bXjXkXkXvXeXX   *.XXW.~.^.~.).W.B   3.(.~.~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXkXlXhXxXJXUX'.  $.kXlXkXkXvXeXX   *.XXW.^.~.(.J.k ; s.oX).~.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXkXkXkX+.D $.l   d.mXjXkXkXvXeXX   *.XXW.~.!.`.s   9 J M s.).~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXkXjXcXs.g p v f.sXzXkXlXkXvXeXX   *.XXW.~.!.).h 4 9 3 , 8.).~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXkXMXZXZXZXMXzXkXlXlXkXvXeXX   *.XXW.^.^.~.{.}.{.}.|.).~.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXkXkXlXjXhXhXhXjXkXlXkXlXkXvXeXX   *.XXW.~.~.^.!.Q.Q.Q.Q.~.^.~.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.6XxXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXaXh.zXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXxXqXX   &..XE.!.!.!.!.!.!.!.!.!.!.!.!.W.}.9.    N.`.Q.!.!.!.!.!.!.!.!.!.!.!.!.R.OXU   0 MXjXlXlX",
"lXhXVXc.pXGXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXAXmXl.FXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXFXhXX   ;.%X(.'.'.'.'.'.'.'.'.'.'.'.'.).@Xr.    S..X`.'.'.'.'.'.'.'.'.'.'.'.'./.=XR   0 MXjXlXlX",
"lXhXBXn.J.).^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q.t.(.~.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).P.X   ` F.x.b.b.b.b.b.b.b.b.b.b.b.b.c.S.$.    e.B.v.b.b.b.b.b.b.b.b.b.b.b.b.z.H.Z   9 MXjXlXlX",
"lXhXBXn.J.).^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.Q.t.(.~.^.^.^.^.^.^.^.^.^.^.^.^.^.~.).P.X   ` F.x.b.b.b.b.b.b.b.b.b.b.b.b.c.S.$.    e.B.v.b.b.b.b.b.b.b.b.b.b.b.b.z.H.Z   9 MXjXlXlX",
"lXhXVXc.pXGXCXCXCXCXCXCXCXCXCXCXCXCXCXCXCXAXmXl.FXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXFXhXX   ;.%X(.'.'.'.'.'.'.'.'.'.'.'.'.).@Xr.    S..X`.'.'.'.'.'.'.'.'.'.'.'.'./.=XR   0 MXjXlXlX",
"lXhXVXv.6XxXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXaXh.zXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXxXqXX   &..XE.!.!.!.!.!.!.!.!.!.!.!.!.W.}.9.    N.`.Q.!.!.!.!.!.!.!.!.!.!.!.!.R.OXU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXh.vXjXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXeXX   *.XXW.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXiXd.jXsXdXdXdXdXdXdXdXdXdXdXdXdXdXdXkX8XX   $.}.Y.E.E.E.E.E.E.E.E.E.E.E.E.T.].7.    B.'.~.^.^.^.^.^.^.^.^.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.5XxXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXgXVXC.UXJXLXLXLXLXLXLXLXLXLXLXLXLXLXKXUXnXX   2.2X XOXOXOXOXOXOXOXOXOXOXOXOX.X,Xs.    M.`.Q.!.!.!.!.!.!.!.!.!.!.!.!.R.oXU   0 MXjXlXlX",
"lXhXVXc.pXFXVXCXCXCXCXCXCXCXCXCXCXCXCXCXBXLXk.D 9.5.6.6.6.6.6.6.6.6.6.6.6.6.6.6.8.,..   n X.` ] ] ] ] ] ] ] ] ] ] ] ] ` ..A     S. X`.'.'.'.'.'.'.'.'.'.'.'.'./.=XR   0 MXjXlXlX",
"lXhXBXm.g.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.F.9   .                                                                           .   1.g.i.p.p.p.p.p.p.p.p.p.p.p.p.y.v.M   9 MXjXlXlX",
"lXhXVXv.OX8X3X3X3X3X3X3X3X3X3X3X3X3X3X3X<XiXh   % - = - - - - - - - - - - - - = - = @ + & * * * * * * * * * * * * * * * = $     k.R.K.L.L.L.L.L.L.L.L.L.L.L.L.F._.J   9 MXjXlXlX",
"lXhXVXc.eXVXbXnXnXnXnXnXnXnXnXnXnXnXnXnXxXPXz   N oXR.!.!.!.!.!.!.!.!.!.!.!.!.!.!.(.S.d.`.Q.!.!.!.!.!.!.!.!.!.!.!.!.!.W.}.9.    C.{.(.).).).).).).).).).).).).!.$XY   0 MXjXlXlX",
"lXhXVXv.7XvXjXkXkXkXkXkXkXkXkXkXkXkXkXkXfXSXl   N +XW./././././././././././././.^.`.F.g.].~./././././././././././././.!..X0.    N.'.!.~.~.~.~.~.~.~.~.~.~.~.~.E.OXU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.~.~.~.~.~.~.~.~.~.~.~.~.~._.D.f.'.!.~.~.~.~.~.~.~.~.~.~.~.~.~.Q. X0.    B.'.~.^.^.~.~.~.~.~.~.^.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.^.^.~./.)._._.^.~.^.~.^.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.~.^.(._._.).~.~.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.^.~.^.~.U.G.K.!.(.~.^.^.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.^.^.T.G.H.I.(.^.^.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.W.|.X.+ @ o G J.).!.^.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.(.I.a +   2 ;.`.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.Q.|.X.Y 8.V   @.[.!.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.(.Y.+.q.2.# , Q.~.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.^.^.Q.[.%Xr.  +.].!.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.~.).`.k.,.% c /.~.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.^.~.^.~.).C.2 5 N.`.!.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.!.`.c.4   @ ,.].!.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.^.^.!.`.v.4 r Z.}.!.~.^.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.~.(.{.!.D.5 , D.(.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.!.`.f.: ; 0.n.A.^.^.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~./.Z.0.V.B.4 % N.).!.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.W..XL   o X   U ~.^.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~._.a.  # . $ _ (.~.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.~.).b.8.0.0.7.v.~.^.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.^.E.l.0.r.c.^.^.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.^.^.~.]. X|. X.X].^.~.^.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.^.~./.[. X X].~.~.^.~.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXlXlXlXlXlXlXlXlXlXlXlXlXlXgXDXl   N OXE.~.~.^.!.Q.Q.Q.Q.!.^.^.~.^.~._.D.f.'.!.^.^.^.^.^.^.^.^.^.^.^.^.^.Q. X0.    B.'.~.~.^.~.!.Q.Q.!.~.^.~.^.^.E.+XU   0 MXjXlXlX",
"lXhXVXv.8XvXkXkXkXkXkXkXkXkXkXkXkXkXkXkXgXDXl   M  XY.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.Z.a.).E.W.W.W.W.W.W.W.W.W.W.W.W.W.R.[.7.    m.(.E.W.W.W.W.W.W.W.W.W.W.W.W.Y..XI   0 MXjXlXlX",
"lXhXVXv.8XbXlXlXlXlXlXlXlXlXlXlXlXlXlXlXgXFXz   A 3X}.oXoXoXoXoXoXoXoXoXoXoXoXoXXX#XW.m.&X.XoXoXoXoXoXoXoXoXoXoXoXoXoX X>Xs.    P.&XXXoXoXoXoXoXoXoXoXoXoXoXoX}.3X!   q MXjXlXlX",
"lXhXVXz.5XcXhXjXjXjXjXjXjXjXjXjXjXjXjXjXdXAXh   * y w e e e e e e e e e e e e e e r 9 5 t e e e e e e e e e e e e e e e t 4     9 r e e e e e e e e e e e e e w y -   7 MXjXlXlX",
"lXhXNXD.u.j.h.h.h.h.h.h.h.h.h.h.h.h.h.h.f.b.k 1 4 ; : ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; : , ; : ; ; ; ; ; ; ; ; ; ; ; ; ; : ; , 7 6 > ; : ; ; ; ; ; ; ; ; ; ; ; ; : - 3 1 l mXjXlXlX",
"lXlXkXcXxXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXmXMXNXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXNXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXNXMXMXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXNXMXmXkXlXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXhXkXlXkXlX",
"lXlXkXvXDXSXSXSXSXSXSXSXDXSXSXDXSXSXSXSXSXDXSXAXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXSXCXlXkXlXlX",
"lXjXvX5XB.D.S.S.S.S.S.S.A.D.S.S.S.S.S.S.S.S.S.K.F.D.D.D.D.D.D.D.D.F.D.D.D.D.D.D.D.D.D.W.kXlXkXlX",
"lXgXAXK.  ; & & & & & & * @ % & & & & & & & %   o O O O O O O O O X O O O O O O O @   q kXlXkXlX",
"lXjXnX*X5XvXjXkXkXkXkXjXbXOXtXxXkXkXkXkXjXvXwX@ f.{.!.^.^.^.^.^.~.V./.^.^.!.!.~.!..X,.2 zXlXkXlX",
"lXjXnX*X7XnXlXzXzXzXzXkXmXOXyXvXlXzXzXzXlXbXeXo f.}.~.^.^.^.^./.~.V.(.^.(. X X_.Q.XX>., xXlXkXlX",
"lXjXnX&X5XvXjXkXkXkXkXjXbXoXtXxXkXkXkXkXjXvXqXo d.[.Q.~.~.~.~.~.!.B.^./.I.Q Q S.^.|.:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.~.^.!.B.^.(.K.b.m ] |.}.:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.~.^.!.B./.!.].z.J K.^. X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.~.^.!.B.^.).J.* d t.(.|.:., zXlXkXlX",
"lXjXnX*X5XvXjXkXkXkXkXhXbXoXtXxXkXkXkXkXjXcXqXo a.`.E.W.W.W.W.Q.E.M.Q.Q.Y.V.c.A.W.{.-.< zXlXkXlX",
"lXjXnX*X9XBXcXvXvXvXvXcXVX@XpXmXvXvXvXvXcXNXyXo n.-X.XoXoXoXoXoX.XL.OXXXOX$X&X#X X,X7.> xXlXkXlX",
"lXjXmX*X#XeX8X9X9X9X9X7XrX).>XqX8X9X9X9X8XeX*X+ F [ ) ) ) ) ) ) _ ^ ` ) ) ( ( ) ( | x 5 lXlXkXlX",
"lXjXmX&X).=X#X$X$X$X$X#X=XU.|.&X$X$X$X$X#X=X'.# < 0 8 8 8 8 8 0 3   6 9 8 8 8 8 8 w & 9 kXlXkXlX",
"lXjXnX*XqXCXnXnXnXnXnXbXZX$XsXBXnXnXbXvXbXVXiXo c.$X[.}.{.{.{.#XN.X E.oX{.}.}.}.[.=X5., xXlXkXlX",
"lXjXnX*X4XcXhXjXjXjXjXhXvXXXrXzXjXzXcXNXgXcX0Xo s.].Q.)._._.E.'.j.  F.(.Q.!.!.!.E.|.;.< zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXzXbXb.^ k.mXxXwXo d.{.E.! M y._.'.k.  H._.~.~.~.~.Q. X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXzXvX-XG ` CXzXwXo d.{.Y.T./ F  X`.k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXxXlXtX>.P bXcXqXo d.]._.p.M F./.].k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXhX9.Q 4.bXcXqXo d.{.W.y u -.(.].k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X4XvXjXjXjXjXjXhXbXXXrXzXkXiXeXmXjXcXqXo d.[.W.Q.U.U.!.].k.  G.).!.~.~.~.W. X:.< zXlXkXlX",
"lXjXnX*XqXVXbXnXnXnXnXvXCX#XsXNXbXMXNXvXbXVXiXo h. X/._.`.`./.|.x.  K.].(.).).).^.OX,., xXlXkXlX",
"lXjXmX&X}.3X>X,X,X,X,X>X3XQ.#X1X>X>X>X,X>X3XoXX q.R.G.H.H.H.G.T.y.  n.P.G.H.H.H.F.Q.@.< zXlXkXlX",
"lXjXmX&X}.3X>X,X,X,X,X>X3XQ.#X1X>X,X,X,X>X3XoXX q.R.G.H.H.H.G.T.y.  n.P.G.H.H.H.F.Q.@.< zXlXkXlX",
"lXjXnX*XqXVXbXnXnXnXnXvXCX#XsXNXnXnXnXnXbXVXiXo h. X/.).).)./.|.x.  K.].(.).).).^.OX,., xXlXkXlX",
"lXjXnX*X4XvXjXjXjXjXjXhXbXXXrXzXjXjXjXjXhXcXqXo d.[.Q.~.~.~.Q.].k.  G.).!.~.~.~.W. X:.< zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.!.[.k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.!.[.k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXlXlXlXjXvXwXo d.{.!.^.^.^.!.[.k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXlXjXnXoXtXcXkXkXkXkXjXvXwXo d.{.!.~.~.~.!.[.k.  H._.~.^.^.^.Q..X:., zXlXkXlX",
"lXjXnX*X4XcXhXjXjXjXjXhXvX.XeXlXhXhXhXhXgXxX0Xo s.].W.!.!.!.W.'.j.  G.).!.~.~.~.W. X:.< zXlXkXlX",
"lXjXnX*XqXCXnXnXnXnXnXbXZX*XkXFXZXZXZXZXCXGXgX@ c.$X{.}.}.}.{.#XM.  L.].(.).).).^.OX<., xXlXkXlX",
"lXjXmX&X).=X#X$X$X$X$X#X&XH p f d d d d d f p   2 0 8 8 8 8 8 0 2 o z.G.A.S.S.S.Z.T.o.1 zXlXkXlX",
"lXjXmX*X#XeX8X9X9X9X8X9XwX7 j [ ~ ^ ~ ^ ^ ^ ( ^ _ ) ) ) ) ) ) [ J X B.R.P.P.P.I.L.).%.< zXlXkXlX",
"lXjXnX*X9XBXcXvXvXvXvXvXNX5 3.<X X#X&XoXoXoX+XL. XoXoXoXoXoX.X=XC.  K.'./.[.]./.~.oX,., xXlXkXlX",
"lXjXnX*X5XvXjXkXkXkXkXkXvX3 $.}.E.S.c.!.Q.W.!.M.E.Q.W.W.W.W.E._.h.  G._.!.M.Z.(.W. X:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXkXkXvX3 &. X^.} l U ].!./.B.!.^.~.^.^.^.!.[.k.  G.'.P.' t 4.].}.:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXkXkXvX3 &..XR.#X>.F {.Q./.B.!.^.~.^.^.^.!.[.k.  H.(.'.z.q 7.].}.:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXkXkXvX3 &. X`.O.5 z.(.~./.B.!.^.~.^.^.^.!.[.k.  G.'.K.d.l ` }.}.:., zXlXkXlX",
"lXjXnX*X5XbXkXlXlXlXkXkXvX3 &. X/.( F o.~.~.^.B.Q.^.~.~.~.~.Q.].k.  F.].D.~ / V.^.|.:., zXlXkXlX",
"lXjXnX*X4XcXhXjXjXjXjXjXcX4 =.OX~.XXoX}.(.(._.Z.^.).(.(.(.(.^.}.x.. K.'._..X.X'.~.oX<.1 xXlXkXlX",
"lXjXmX%X9XVXvXbXbXbXbXbXBX5 o.).K.K.K.L.I.P.U.z.L.I.I.I.I.I.L.Q.p.  B.R.L.K.K.P.K.(.%.< zXlXkXlX",
"lXjXnX:X^.+X.X.X.X.X.X.XoXb i b x x x x x x x l x x x x x x x c j q l c x x x x x b u M kXlXkXlX",
"lXkXlXkXpXiXiXiXiXiXiXiXiXjXgXdXdXdXdXdXdXdXdXfXdXdXdXdXdXdXdXdXfXkXfXdXdXdXdXdXdXdXgXkXkXlXlXlX",
"lXlXkXlXxXxXxXxXxXxXxXxXxXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXzXzXzXzXzXzXzXzXzXlXlXlXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXhXkXlXkXlX",
"lXlXkXvXFXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXAXSXDXDXDXDXDXDXDXSXDXDXDXDXDXDXDXDXCXlXkXlXlX",
"lXjXvX5Xm.C.V.V.V.V.V.V.Z.C.V.V.V.V.V.V.V.K.D.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.E.jXlXkXlX",
"lXhXZXU.> i r r r r r t 7 w t r r r r r r o : 4 2 2 2 2 2 2 > 2 2 2 2 2 2 5 & 5 dXzXkXlX",
"lXjXbX:XpXSXNXBXBXBXNXDX,XjXZXBXBXBXNXCXmX6 z.@X'.[.[.[.[.[.J.[.[.{. X[.'.+Xc.4 fXzXkXlX",
"lXjXnX-X7XcXhXjXjXjXhXvX#XrXzXjXjXjXjXlXfX2 s.[.Q.!.!.!.!.~.V.!.~.W.S.^.~.].d.1 fXzXkXlX",
"lXjXnX-X8XvXkXkXkXkXjXbX$XtXxXkXkXkXkXzXgX2 s.{.!.~.~.~.~.~.C.!.].g.S D W.{.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXxXkXlXlXkXzXgX2 s.{.!.^.^.^.~.^.C.^.!.{.c.A ~.{.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXxXkXlXlXkXzXgX2 s.{.!.^.^.^.~.^.C.!.'.k.- $.!.[.f.1 fXzXkXlX",
"lXjXnX-X8XcXjXkXkXkXjXbX#XtXxXkXkXkXjXlXgX2 p.'.E.Q.Q.Q.Q.Q.B.E.(.v.$.2.P.].a.1 fXzXkXlX",
"lXjXnX-XwXNXcXvXvXvXcXBX*XaXmXvXvXvXcXnXzX2 n.-X.XoXoXoXoXoXI.oXXX$X>X;XXX=Xm.1 fXzXkXlX",
"lXjXnX-X&XeX8X9X9X9X8XrX].,XqX9X9X9X8X0X6X2 G  .' ] ] ] ] [ ` [ ] ' _ ` '  .G 3 fXzXkXlX",
"lXjXnX-X{.,X=X-X-X-X=X,X!.OX:X-X*X=X=X;X&X2 0 j f d d f g p X p g f f f f j 9 5 fXzXkXlX",
"lXjXnX-XrXVXbXnXnXnXvXCX=XsXNXnXSXVXbXMXcX2 b.*X.X%XOX X#XE.- R.#X.XXXXX X*Xn.1 fXzXkXlX",
"lXjXnX-X7XcXjXjXjXjXhXvX#XrXxXgX#X4XlXkXfX2 p.].Y.j.J.^./.A.% Z.(.W.Q.Q.E.'.s.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XtXbXtX<.l :XMXfX2 a.XXn.Q f G.].S.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXlXBX|.l *XNXfX2 d.].].C.J R.`.D.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XtXmX2Xp.b [.VXdX2 a.XXm.* ~ T.`.S.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X7XcXjXjXjXjXhXvX#XrXcXuXY.+XzXkXfX2 a.|.G.y.t.P.`.S.% A._.!.~.~.Q.[.d.1 fXzXkXlX",
"lXjXnX-XrXBXbXbXbXbXvXVX=XsXMXmXJXAXvXmXxX3 g.|._..X X).].H.& F.]./.(.(./.|.h.1 fXzXkXlX",
"lXjXnX-XoX5X1X2X2X2X1X6X(.&X4X1X,X<X1X3X,X< w.E.H.H.H.H.U.v.% c.U.J.K.K.H.E.w.1 fXzXkXlX",
"lXjXnX-XoX5X1X2X2X2X1X6X(.&X4X1X2X2X1X3X,X< w.E.H.K.K.J.U.v.% c.U.J.K.K.H.E.w.1 fXzXkXlX",
"lXjXnX-XrXBXbXbXbXbXvXVX=XsXMXbXbXbXbXmXxX3 g. X/.(.(./.].H.& F.]./.(.(./.|.h.1 fXzXkXlX",
"lXjXnX-X7XcXjXjXjXjXhXvX#XtXzXjXjXjXjXlXfX2 s.[.Q.~.~.!._.D.% A._.!.~.~.Q.[.d.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXxXkXlXlXkXzXgX2 s.{.!.^.^.~._.D.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXxXkXlXlXkXzXgX2 s.{.!.^.^.~._.D.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXlXjXbX$XyXxXkXlXlXkXzXgX2 s.{.!.^.^.~._.D.% S._.~.^.^.!.[.f.1 fXzXkXlX",
"lXjXnX-X7XcXjXjXjXjXhXvX+XwXkXgXgXgXgXjXsX2 p.'.E.Q.Q.W.(.A.% A._.!.~.~.Q.[.d.1 fXzXkXlX",
"lXjXnX-XrXVXbXnXnXnXvXCX<XvXKXFXFXFXFXHXAX6 b.*X XXXXX.X@XE.& G.[.(.).)./. Xh.1 fXzXkXlX",
"lXjXnX-X{.,X=X-X-X-X=X1X[ M S A A A Z A Z + e h f f f f h i + x.K.D.F.F.D.U.0.2 fXzXkXlX",
"lXjXnX-X&XeX8X9X9X9X7XuXs z | ( / / ) ) ` ` [ ] ] ] ] ] } ! # m.E.P.L.P.P.~.t.1 fXzXkXlX",
"lXjXnX-XwXNXcXvXvXvXxXSXs 9.,XXX>X-XOXoX@XU.|.OXoXoXoXXX$XW.& F.'._.XX{.^.|.h.1 fXzXkXlX",
"lXjXnX-X8XcXjXkXkXkXhXNXp -.|.P.-.e.!.W.!.B.R.Q.Q.Q.Q.W./.Z.% A.].D.<.k.^.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXkXjXBXp :.OXF.5.u h.].^.Z.Q.^.~.^.^.~._.D.% A.[.D.H g ~.[.f.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXkXjXBXp :.|.`.f.W W.^./.Z.Q.^.~.^.^.~._.D.% S.)._.1.h R.}.d.1 fXzXkXlX",
"lXjXnX-X8XvXkXlXlXkXjXBXp ;.+XS.1 A A.).^.Z.Q.^.~.~.~.!._.D.% Z.|.p.I G T.{.d.1 fXzXkXlX",
"lXjXnX-X7XcXjXjXjXjXhXNXa >.XXE.U.F.R.^./.Z.Q./.^.^.^.~._.D.* S.`.R.A././.[.g.2 fXzXkXlX",
"lXjXnX-XeXBXvXbXbXbXvXDXa :. XQ.(.).^.!./.C.W.^.~.~.~.!._.D.% A._.~.).~.Q.[.d.1 fXzXkXlX",
"lXjXbX>X'.*X#X#X#X#X@X;XV d F C C C C Z Z M C Z Z Z Z C A N 8 N A C C C C S z j fXzXkXlX",
"lXkXlXkXuXyXyXyXyXyXyXyXdXuXrXtXrXrXrXrXrXtXtXrXrXrXrXtXrXtXdXtXrXtXrXrXtXrXyXfXkXlXkXlX",
"lXlXkXlXxXxXxXxXxXxXxXxXzXxXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXzXcXcXcXcXcXcXcXcXzXlXkXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"kXlXbXnXnXnXnXnXnXnXnXnXnXnXnXvXbXbXbXbXbXbXbXbXbXbXbXbXbXvXlXkX",
"lXkX7X4X5X4X5X4X5X5X4X5X4X5X4X0X9X6X7X7X7X7X7X7X7X7X7X7X6XeXkXlX",
"cXrXC c n b b n x x n b b b M 0 e j f g g g s f g d d h a e eXvX",
"cXrX<XcXhXjXhXxX6X6XxXhXjXdXFX[ =.|.E.Q.Q.~.D.R.!.'.'.!.E.f 7XbX",
"cXrX2XbXkXlXlXbX8X8XbXlXlXhXHX{ ;.XX!.^.^.(.H.Q.(.7.w.).!.g 7XbX",
"cXrX1XvXjXkXjXvX7X7XvXjXkXfXGX[ -..XQ.~.~./.G.E.(.h.D !.!.f 7XbX",
"cXrX1XvXjXkXkXvX7X7XvXkXkXfXGX[ =. XW.!.!.^.F.T.`.P ~ (.E.f 7XbX",
"cXrX3XnXlXzXzXnX9X9XnXzXzXjXKX{ 1.*X'.[.[.|.U._.{.V.C.].].h 6XbX",
"cXtX;XgXpXaXpXgX1X1XgXpXaXyXBX] ! m.s.f.f.g.i.d.f.x.x.g.a.u 8XbX",
"cXyX}.<X:X:X:X1X X X1X;X=X*XeX( 1 M k k z v - p v l l x j 3 qXvX",
"cXrX4XNXxXvXcXMXqXqXMXmXFXcXLX} 2.*X X#X{.#Xv x.@X].{.}.].h 6XbX",
"cXrX1XcXjXkXjXcX7X5XBX].q.9XKX] *.oX5.X.U.{.z d.'.W.Q.~.E.f 7XbX",
"cXrX2XvXjXlXkXvX7X6XMX6XC {.UX] =.OXV.F G. Xz f.[.!.~.^.Q.g 7XbX",
"cXrX1XvXjXkXjXcX7X6XMX/.^ .XUX] *.*X~ H E.}.z f.[.!.~.^.Q.g 7XbX",
"cXrX4XMXxXcXxXmX0X0XNXeXrXcXLX} ;.OXJ.F.W. Xx g.}.^./.(.~.g 7XbX",
"cXtX&XiXeXrXeXiX;X;XuXuXiX9XvX) %.'.R.Q.Y.(.l i./.U.Y.R.I.f 7XbX",
"cXyX.X5X1X2X1X5XOXOX5X<X1X>XpX! @.^.G.J.H.W.j e.E.H.J.L.G.d 7XbX",
"cXrX5XNXcXvXvXNXqXqXNXvXvXlXIX} ;.OX^.(.^. Xx h.|.^.(.).^.g 7XbX",
"cXrX1XcXhXjXjXcX7X7XcXjXjXfXGX[ -..XQ.~.Q.[.z f.[.!.~.^.Q.g 7XbX",
"cXrX2XvXjXlXkXvX7X7XvXkXlXgXHX[ -..XQ.~.!.{.z f.[.!.~.^.Q.g 7XbX",
"cXrX1XcXjXkXjXcX6X4XlXfXgXaXAX] *.}.R.Q.E.'.z f.[.!.~.^.Q.g 7XbX",
"cXrX5XNXcXvXcXMXyXhXIXGXHXSXUX@.6.<X.XoX.X-Xn g.|.^./.).^.g 7XbX",
"cXtX+XqX7X7X6XyXT.:.q.8.8.6.i.l n  ._ ` _ } 5 a.Q.L.P.I.K.d 7XbX",
"cXtX+XqX7X7X4XgX4.e } / / ^ / _ ' ` ` ` _ } 5 a.Q.I.P.I.K.d 7XbX",
"cXrX5XNXcXvXlXIXq.| 4X[.XX#X@X^.].+XoXoX.X-Xn g.|.E.).).~.g 7XbX",
"cXrX1XcXjXkXfXGX8.! +Xu.F b.`.F.I.!.W.Q.E.'.z d. X#.R (.Q.f 7XbX",
"cXrX2XvXjXlXgXHX8.^ #XZ.K Z.].J.T./.~.~.!.{.z d..Xi.z W.~.f 7XbX",
"cXrX1XcXhXjXfXGX8.! *X@.F H.).G.U.~.Q.!.W.].z d._.$.| Q.W.g 7XbX",
"cXrX5XBXcXvXlXUX0.' -X}..X].|.E./.}.[.[.].@Xv x.@X[.oX|.'.h 6XbX",
"xXyXoX5X1X2X>XuX7.f O.` ' ] [ ( _ [ ] ] ' | y U | ' ` [ _ a qXvX",
"lXkXyXrXrXrXrXrXtX6X<X1X1X1X1X2X1X1X1X1X1X<X0X3X<X1X1X1X<XwXkXlX",
"kXlXxXcXcXcXcXcXcXbXmXmXmXmXmXnXmXmXmXmXmXmXvXnXmXmXmXmXmXvXlXkX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"jX:X&X*X-X*X&X,X1X:X>X>X>X;X5XkX",
"uXB.N.B.z.M.F.<. .q.4.1.6.q.} 5X",
"pXjXSXVXdXNXUX!.j.OX(._.n.n.y.;X",
"iXtXzXjX0XfXBXP.g. X^._.x.N.r.;X",
"pX3XeXqX:XwXxXC.R 4.$.' ;.>.W 3X",
"iXrXkXgXwX8X7XY.q.N.b.O.U.T.,.,X",
"iXiXbXlXsX%XZ./.f.3.V.,.].}.7.:X",
"pX9XsXiX5XqXhXH.y.W.D.$.~.(.3.>X",
"pX7XiXyX1XtXcXS.u.[.D.@.!.^.2.>X",
"iXiXvXzXwXkXAXY.d. XL.*.`.[.6.>X",
"iXyXzXkXtXjXZXU.p.}.H.&.).`.5.>X",
"pX3XwXtX8.1.u.X.' -.[ ' /.(.<.,X",
"pXyXzXlX7.N.j.E.R.^.H.;.S.B.0.:X",
"iXiXvXxXt.n.9.].~.}.T.3.v.p.u.-X",
"pX8XuXpX2.s.z.h.h.c.s.} x.b.*.3X",
"kXpXiXpX0X1X2X2X2X1X2X5X2X1X7XkX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
