#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXXXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXXXoXXXXXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXXXXXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXXXXXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXXXoXoX",
"oXoXXXoXoXoXOXOXOXOXOXOXOXOXoXXX|.}.}.{.}.}. XXXOXOXOXOXOXOXOXOXoXOX X{.}.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.}.{. XOXoXOXOXOXOXOXOXOXOXoXXX|.}.}.{.}.}. XXXOXOXOXOXOXOXOXOXoXXXXXoXXXoX",
"oXoXXXoXOX X{.}.}.}.}.}.}.].`. X=X1X3X4X3X1X=X X`.].}.}.}.}.}.{.XX}.&X7X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X7X&X}.XX{.}.}.}.}.}.}.].`..X-X1X3X4X3X1X*X|.`.].}.}.}.}.}.{. XOXoXXXoXoX",
"oXXXoXoX X,XqX9X9X9X9X8X5XpXkX#Xd.@.[ _ [ #.h.&XkXiX5X8X9X9X9XqX>X$X0.I / ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ / I 0.$X>XqX9X9X9X9X7X5XaXjX+Xa.+.] _ [ $.k.=XlXuX5X8X9X9X9XqX,X.XOXXXoXoX",
"oXoXXXOX{.qXMXcXvXvXzXMXDXT.` N *           - V ] ^.FXmXxXvXcXMX8X<XQ   o                                             o   Q <X8XMXcXvXvXzXMXSXP.) m %           : Z { `.GXnXxXvXcXMXqX{.OXoXXXoX",
"oXoXoXOX}.9XcXjXjXjXnX$XU 3   ; } m.T.].Y.b._ =   5 E >XnXjXjXxX6X,X!   # o o o o o o o o o o o o o o o o o o o o o o #   ! ,X6XxXjXjXjXnXOXP 2   > ..M.R.].U.v.^ &   6 ! 2XbXjXjXcX9X}.OXXXoXoX",
"oXoXoXOX}.9XvXjXlXnXU.1   y I.0XsXcXMXCXMXcXpX0XD.9   6 ^.nXkXcX6X<XW   o                                             o   W <X6XcXjXlXnXH.,   s R.qXsXcXMXCXmXcXpX9XC.5   0 '.nXjXcX9X}.OXoXoXoX",
"oXoXoXOX}.9XvXjXnXl.+ + 4.hXxXmXxXlXkXjXkXlXcXmXzXdX-.o % N.nXxX6X<XW   o                                             o   W <X6XcXkXbXd.X # 0.jXxXnXxXlXkXjXkXlXcXmXzXaX#.X = A.mXxX9X}.OXoXoXoX",
"oXoXoXOX}.9XzXnXU.+ : S.BXlXkXhXhXgXgXgXhXjXkXkXlXzXNXb.% * ^.VX3X<XW   o                                             o   W <X6XzXnXH.. 1 J.BXlXkXhXhXgXgXgXhXkXkXkXlXxXMXl.@ > `.VX6X}.OXoXoXoX",
"oXoXoXOX}.8XMX$X1 # S.VXjXkXxXNXZXSXDXSXCXbXjXkXlXkXjXBXb.  0 3X0X>XW   o                                             o   W <X4XMXoX- * J.VXhXkXzXnXVXSXFXFXAXzXkXlXkXkXkXNXk.  y 7XeX[.OXoXoXoX",
"oXoXoXOX}.5XDXI   5.BXjXkXzXuX&X].!.T.E.'.7XMXlXkXlXlXkXMX=.  { aX-XW   o                                             o   W <X2XAXD   q.VXhXlXlXfX4XoXW.P.K.!.sXlXkXlXkXkXlXbX@.  @.gX`.OXXXoXoX",
"oXoXoXOX].pXR.3 r gXlXkXgXZXn.5 @       $ N Z.kXjXkXkXkXcXuX5 r V.9XT   o                                             o   W :XtXL.< a lXkXlXgXNX/.F >   .   9 1XzXjXlXlXlXkXvXwX< i J.#X.XoXoXoX",
"oXoXoXoX`.kX_   I.xXlXkXfXHX:.  w h a   .   2 R.VXgXlXkXlXzXC.  E pXU   o                                             o   W -XfXE   W.xXlXkXdXHXe.  : u %   y 6XzXjXlXlXkXkXlXzXb.  [ ,X|.XXoXoX",
"oXoXoXXX X#XM + 0XmXkXkXjXmX|.S.{.XXoXZ.* #   ,.LXdXlXlXjXNX<X  k %XQ   o                                             o   R 2X Xz & yXbXkXlXjXmX$XV.`.b.#   q 5XzXjXlXlXlXlXjXVX*X  B _.OX.XoXoX",
"oXoXoX|.-Xs.*  .aXxXkXlXlXjXNXFXLXUXHXoX@ X   w.JXdXlXkXkXcXyX( o Z.'   o                                             o   Y rXq.& @.fXxXkXlXlXjXbXSXGX).$   q 5XzXjXlXlXlXkXkXvXeXQ & k.-X XoXoX",
"oXoXoX}.1X@.  m.cXlXkXkXkXkXgXsX^ 9 p , .   n 3XcXjXlXlXkXlXxXd.  u. .  o                                             o   I sX`   Z.cXlXkXlXkXlXjXdXzXW.$   q 5XzXjXlXlXlXlXkXlXzXy.  4.1X|.oXoX",
"oXoXoX}.4X]   R.MXkXkXlXlXjXjXfXc   X     J 6XbXhXlXlXlXkXjXNXD.  9...  o                                             o   I fXR   /.mXkXkXlXkXlXkXjXvXQ.$   q 5XzXjXlXlXlXlXkXjXNXM.  :.2X}.oXoX",
"oXoXoX{.4X`   ].CXjXkXkXlXkXjXjXT.x.t.b     N ;XbXhXlXlXkXhXAXE.  8.X.  o                                             o   I gXU   oXBXjXkXlXlXlXlXjXvXQ.$   q 5XzXjXlXlXlXlXkXhXSXJ.  ;.3X}.oXoX",
"oXoXoX}.3X]   Y.MXkXkXlXkXzXzXhXlXxXbXsXB     X.VXgXkXlXkXjXMXA.  9...  o                                             o   I fXR   ~.mXkXkXlXkXlXkXgXxXW.#   0 3XkXgXkXlXkXlXkXjXNXn.  :.2X}.oXoX",
"oXoXoX}.1X#.  b.cXlXkXkXzXdXgXZXBXnXVXMX'     J rXxXjXlXkXlXzXa.  u.|   o                                             o   I sX]   V.cXlXkXlXlXkXxXnXCX).$   w wXNXbXzXkXlXlXkXlXzXe.  5.<X|.oXoX",
"oXoXoX X=Xh.; ] pXxXkXhXNX+X1.H.#X;X%XM.: #   ! lXkXkXkXkXvXrXW @ D.`   o                                             o   Y eXt.= ..dXxXkXlXkXzXuX;X>Xm.@   6 '.-X,XdXzXkXkXkXvXqXU - x.-X XoXoX",
"oXoXoXXX X*XV   0XmXkXgXZXQ.-   r n d       - G.ZXfXlXlXjXNX,X  x =XW   o                                             o   R 1XOXv + yXbXkXlXgXBX~.A c s $ O = x k ~ ;XnXjXlXhXVX&X  A ].OX.XoXoX",
"oXoXoXOX`.lX]   F.zXlXhXmX*X! >         1 J L.zXjXkXkXkXlXzXb.  Q pXU   o                                             o   W =XfX!   P.zXlXkXfXDXx.X           X   9 {.BXhXkXlXlXj.  } ,X|.XXoXoX",
"oXoXoXOX].uX(.5 7 sXzXkXlXhX5X].R.J.G.I.].rXCXjXlXlXkXkXcXeX: u F.8XT   o                                             o   W :XrXW.1 w jXlXlXjXvX3XJ.S.D.A.Z.A.F.A.E.rXxXkXkXbX7X& d Y.@X.XoXoXoX",
"oXoXoXOX}.4XGXW   =.NXjXlXlXbXCXSXFXGXDXCXcXgXkXlXkXkXlXbX .  o.sX-XW   o                                             o   W <X2XDXL   <.VXjXlXjXnXFXGXGXGXGXGXGXHXSXcXkXlXzXcX'   =.hX`.OXXXoXoX",
"oXoXoXOX}.8XnX>X6 X b.BXkXkXjXhXgXgXgXgXhXjXkXlXkXkXlXNXd.  y 0X8X>XW   o                                             o   W <X5XmX=X< @ V.VXjXkXjXgXgXgXgXgXgXgXgXgXkXkXzXMXy.  f rXqX[.OXoXoXoX",
"oXoXoXOX}.9XxXnX^.% % v.MXcXlXjXkXkXkXkXkXkXkXjXlXcXbXd.o , {.BX4X<XW   o                                             o   W <X6XxXnXE.+ - B.MXxXkXjXkXkXkXkXkXkXkXjXlXvXvXy.  4 XXBX7X}.OXoXoXoX",
"oXoXoXOX}.9XvXjXnXN.= . &.yXxXNXcXlXjXhXjXlXcXNXzXeX .  , G.nXxX6X<XW   o                                             o   W <X6XcXkXbXc.% o >.uXxXNXcXlXjXhXjXlXvXBXzXqX]   2 I.nXxX9X}.OXoXoXoX",
"oXoXoXOX}.9XcXjXkXnX^.9   w B.<XyXxXNXAXMXxXtX,Xv.6   t {.nXjXxX6X,X!   # o o o o o o o o o o o o o o o o o o o o o o #   ! ,X6XxXjXkXnXR.6   y A.1XuXxXNXAXMXzXrX>Xl.2   p XXnXhXcX9X}.OXXXoXoX",
"oXoXXXOX{.qXMXxXcXxXVX3X} w   * ~ f.D.E.A.s.R %   r X.9XBXxXxXmX8X<XQ   o                                             o   Q <X8XmXxXcXxXVX,X] 9   = ) g.D.E.Z.a.U $   y @.eXNXxXxXMXqX{.OXoXXXoX",
"oXoXoXoX X1XtXwXwXwX0XyXjXG./ b #           % M _ U.lXtX0XwXwXtX<X$X6.D R Y Y Y Y Y Y Y I L J J J J J L I Y Y Y Y Y Y R D 6.$X<XtXwXwXwX9XyXjXA.^ b #           = V ` E.lXrX0XwXwXtX1X XoXXXoXoX",
"oXoXoXXX+X|._.'.`.`.'._.^.|.#X^.v.r.8.7.8.r.b.).$X}.^._.'.`.'._.|. X$X2X,X<X<X<X<X<X;X-X2XrXsXfXgXfXsXeX1X=X:X<X<X<X<X,X2X$X X|._.'.`.`.'.)./.OX=XW.y.&.o. .o.=.s.(.-X.X^._.'.`.'._.}.@XoXXXoXoX",
"oXoXoXoX X<XrXqXqXqXwX0X7XiXfX$Xx.1.&.#.&.2.b.*XgXuX7X0XwXqXqXrX2X|.,X7X5X5X5X5X3X1XtXdX Xe.{ ! E ~ | p.+XfXeX<X4X5X5X5X7X,X|.2XrXqXqXqXqXqXqX8X6XwXdXkXzXzXzXkXaXqX6X9XqXqXqXqXqXrX<X.XoXXXoXoX",
"oXoXXXOX{.qXMXxXcXcXzXMXSXI.^ v #           % m ( Q.DXmXxXcXcXMXtX_.rXMXxXcXcXzXMXAXL.~ b %           - M ) ^.FXnXxXcXxXMXrX_.tXMXcXcXcXcXcXcXcXcXxXlXkXkXkXkXkXlXxXcXcXcXcXcXcXxXMXqX{.OXoXXXoX",
"oXoXoXOX}.9XcXjXjXjXnX@XK 2   > ..B.Q.|.E.M.] -   2 U ;XnXjXjXxXwX'.qXxXjXjXjXnXOXJ 1   , X.B.Q.|.E.m.` =   3 Y >XbXjXjXxXqX'.wXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcX9X}.OXXXoXoX",
"oXoXoXOX}.9XvXjXlXbXL.,   i R.eXdXcXMXVXmXcXsXeXJ.0   3 !.nXkXcXwX`.qXcXjXlXbXH.:   a W.eXdXcXMXVXmXcXaXeXG.8   5 ^.nXkXcXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.9XvXjXnXh.o # 7.kXxXnXxXlXkXjXkXlXxXnXzXgX>.+ # n.nXxXwX`.qXcXjXbXd.X $ 0.kXxXnXxXlXkXjXkXlXxXnXzXfX-.O $ N.mXxXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.9XzXnXL.O , F.VXlXlXkXkXkXjXgXgXgXhXkXlXlXBXM.* & Q.VX9X'.wXzXnXH.X 1 J.VXlXkXhXhXgXgXgXgXkXkXkXlXzXBXn.% = ^.VX8X'.wXcXkXlXlXlXkXkXkXkXjXhXgXgXgXhXjXkXkXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.7XMX+X, $ F.VXhXlXkXkXlXjXMXGXFXGXBXjXlXkXjXBXM.  9 1XyX_.0XMXoX: & J.VXhXkXzXnXVXDXFXGXSXzXkXlXkXkXjXBXb.  w 3XtX).wXcXkXlXlXlXkXlXkXzXmXCXSXFXDXCXcXhXlXlXkXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.5XDXP   8.BXhXlXkXkXlXjXvX-XG.H.A..XnXjXkXlXkXMX:.  ] jX/.7XSXH   q.VXhXlXlXfX2X XY.H.D.T.aXlXkXlXkXlXkXmX=.   .hX/.wXcXkXlXlXlXlXkXzXdX>X'.Q.P.I.'.tXBXhXlXkXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX].pXY.2 y gXlXkXkXlXkXkXhXgXm   o   Q PXsXlXkXkXxXiX7 e S. XiXP.1 p kXkXlXgXNX(.D :   .   6 ,XzXjXlXlXlXkXcXtX5 t F.oX9XcXkXlXlXlXjXzXyXw.z *       = U _.nXhXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXoX`.kX_   Y.xXlXkXlXkXlXdXCX4.    %   X.KXdXlXlXkXlXxXA.  ^ #XgX~   E.xXlXkXdXHXi.  > p &   e 4XzXjXlXlXkXkXkXxXB.  _ =X7XcXkXlXlXlXhXbX<Xb   : f u   X   p @XmXhXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXXX.X@Xm @ qXmXkXlXkXlXgXBX^.>   t .   } KXsXlXlXlXjXNX<XX c ~.#Xx % rXnXkXlXjXnX*XS.[.N.%   8 3XzXjXlXlXlXlXjXBX:X  M !.eXxXkXlXlXlXjXbX2X..1._.%XOX4.  $   7.JXdXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX|.-Xa.* ..sXxXkXkXlXjXlXrXM   *.^     } KXsXlXlXkXkXcXyX_ O c.z.# O.dXxXkXlXlXjXbXAXGX'.&   8 3XzXjXlXlXlXkXkXcXtX/ % p.dXlXkXlXlXlXkXzXsX7XvXSXMXSXiXw o   >.JXfXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX}.1X@.  m.cXlXkXlXkXgXCX;.  g eX`     } KXsXlXlXlXkXlXxXf.  e.1.  V.cXlXkXlXkXlXjXfXzX~.%   8 3XzXjXlXlXlXlXkXlXxXa.  ;.lXkXkXlXlXlXlXkXzXbXkXgXgXvXqX,     l.FXfXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX}.4X]   R.MXkXkXlXfXAXL.:   (.NX~     } JXsXlXkXlXkXjXNXD.  8.%.  !.MXkXkXlXkXlXkXjXvX^.%   8 3XzXjXlXlXlXlXkXjXNXC.  #.zXkXkXlXlXlXkXlXkXjXkXkXbXjX]     G uXzXjXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X`   ].CXjXkXjXbX<XB   s.AXZX)     X.UXjXjXlXlXkXhXAXE.  8.#.  |.VXjXkXlXlXlXlXjXvX^.%   8 3XzXjXlXlXlXlXkXhXSXI.  +.xXkXkXlXlXlXlXkXlXkXkXnXqXU     m 3XvXhXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX}.3X[   U.mXkXkXgXAXd.  k /.,X%XK     Q 6X6XcXkXlXkXjXMXZ.  8.&.  E.mXkXkXlXkXlXkXgXxX!.%   7 1XkXgXkXlXkXlXkXjXMXN.  #.zXkXkXlXlXlXkXlXjXlXbX+Xs     I 0XlXgXlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX}.1X$.  v.cXlXkXhXVXq.  +             @   u.LXdXlXkXlXzXa.  r.2.  m.cXlXkXlXlXkXxXnXZX'.&   9 qXNXbXzXkXlXlXkXlXzXy.  :.kXkXkXlXlXlXlXjXxXzXH.2   , 5.AXZXCXmXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX X*Xj.: ` pXcXkXhXVXi.  < : > > +     *   g.JXfXkXkXvXrXE % n.n.* [ aXxXkXlXkXzXuX*X;XM.$   4 (.&X:XsXzXkXkXkXvXwXY ; f.sXlXkXlXlXlXkXkXjXs.*     / oX)._.^.-XlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXXX|.=XC   9XmXjXkXvX*XB.H.F.F.G.C +   J P.$XmXjXlXjXBX>X  M (.=Xm X wXnXkXlXgXBX/.Z l a $ O * l h W =XmXhXlXjXBX-X  C (.wXxXkXlXlXlXhXbX>Xz   * $ y 2 4 9 @ *.cXjXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX`.lX[   S.zXlXlXkXnXSXZXZXAXSXU     ( UXkXjXlXkXlXzXc.  _ #XgX)   G.zXlXkXfXDXn.o   .       X   7 '.VXgXkXlXlXk.  [ -X7XcXkXlXlXlXhXnX*Xj   X         O   ' lXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX].uX_.6 4 aXzXkXlXjXfXgXfXgXgX{.G.A. XxXgXlXkXkXvXwX- i Y.}.yX/.4 7 fXzXkXjXvX5XU.J.K.G.G.H.K.H.!.rXxXkXkXvX9X& s T..X9XcXkXlXlXlXkXzXiX^.S.H.G.J.J.J.K.A.XXzXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.4XGXQ   %.NXkXlXlXkXlXlXkXkXVXGXGXBXjXlXkXkXlXbX{   +.lX^.7XFXT   =.BXjXlXjXbXDXGXFXFXFXFXFXGXSXcXkXlXzXvX'   %.kX^.wXcXkXlXlXlXlXkXxXAXGXFXFXFXFXFXFXHXVXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.8XnX<X8 . c.BXkXkXkXlXkXlXlXhXgXgXhXlXkXkXlXMXp.  i wXrX_.0XnX>X5 o n.BXkXkXjXgXgXgXgXgXgXgXgXhXkXkXzXMXy.  s rXeX_.wXcXkXlXlXlXkXlXkXhXgXgXgXgXgXgXgXgXhXlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.9XxXbX).* # z.mXcXlXjXkXkXkXkXkXkXkXjXlXvXvXp.X <  XNX0X'.wXxXbX^.$ % v.mXcXkXjXkXkXkXkXkXkXkXjXlXvXvXy.  3 XXNX9X'.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.9XvXjXnXV.;   #.eXxXBXcXlXjXhXjXlXvXBXzX0X{   1 K.nXxXwX`.qXcXjXnXN.- . &.rXxXBXcXlXjXhXjXlXvXBXzX9X'   3 I.nXxXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoXOX}.9XcXjXkXmX(.w   q m.:XtXxXNXSXNXzXeX;Xl.5   i  XnXhXxXwX'.qXxXjXkXmX^.q   e M.:XtXxXNXSXNXzXwX-Xj.3   a XXnXhXcXqX'.wXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcX9X}.OXXXoXoX",
"oXoXXXOX{.qXMXxXcXxXVX5Xo.r   % W a.C.U.B.i.U $   y #.qXBXxXcXMXtX_.rXMXxXcXxXVX3X..e   & ! a.C.U.B.u.I #   i %.eXNXxXcXMXrX_.tXMXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXxXMXqX{.OXoXXXoX",
"oXoXoXoXXX>X7X5X5X5X2X8XaXZ.~ c @           $ n / J.sX7X3X5X5X6X,X X1XrXqXqXqX8XtXjXG._ m @           & V [ R.lXeX9XqXqXrX2X}.2XrXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXrX<X.XoXXXoXoX",
"oXoXXXOX{.$X2X,X<X<X<X>X-X9XpX*XD.a.e.q.e.s.H.;XaX8X-X>X<X<X,X2X$X|. X_.'.`.`.'._.^. X$X/.n.u.w.q.e.i.N._.$X}.^._.'.`.'._.}.#X{._.'.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.'._.}.@XoXXXoXoX",
"oXoXXX X*X7.D R Y Y Y Y Y P K Y ( ] { } { ] / Y K P Y Y Y Y R F 3.$X,XtXwXwXwXwXqX8XpXfX@Xk.;.@.X.@.>.v.*XgXiX8XqXwXwXwXtX2X{.3XtXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXtX1X XoXXXoXoX",
"oXoXoX{.5X^   o                                             o   T <X7XMXxXcXcXzXMXZXH.R l @           % v ! Q.DXmXxXcXxXMXrX_.tXmXxXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXxXMXqX{.OXoXXXoX",
"oXoXXX}.4X/   # o o o o o o o o o o o o o o o o o o o o o o @   R ,X5XcXjXjXkXnX.XD ,   1 @.A./.oX~.V.{ -   1 L ;XnXkXjXcXqX'.wXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcX9X}.OXXXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X5XcXjXlXbXD.-   f ~.yXfXcXmXBXmXcXsXtXK.q   2 !.bXkXcXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X5XcXjXbXp.  & r.zXxXbXxXlXkXjXkXlXxXbXzXjX>.@ @ n.nXxXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X5XzXnXD.. 4 P.VXkXjXfXgXgXgXgXgXgXgXjXlXlXVXM.* * Q.VX8X'.wXcXkXlXlXlXkXkXkXkXhXhXgXgXgXhXjXkXkXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X3XMX.X- * P.VXhXjXMXHXGXGXGXGXGXHXSXcXkXlXjXBXM.  0 1XyX).wXcXkXlXlXlXkXlXkXzXmXZXDXGXFXZXcXhXlXlXkXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X1XAXF   r.VXhXjXnX&XB.A.S.S.S.D.Z.Y.eXxXkXlXkXmX:.  } hX/.wXcXkXlXlXlXlXkXzXdX;X).Y.G.J.).rXBXhXlXkXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y ;XtXK.< s kXkXlXdXLX1.  O       .   9 `.NXgXlXkXcXyX7 r S.OX9XcXkXlXlXlXjXzXyX9.k %       * K /.nXhXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y -XdX!   Q.xXkXkXdXHXi.  # < 4 3 6 , B @XnXhXkXkXkXxXC.  _ =X7XcXkXlXlXlXhXbX<Xb   > h p   X   i +XmXhXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   I 3X}.c & rXnXkXlXdXJXt.    m.6X,X;XXXXXiXzXkXlXlXjXBX:X. m Q.eXxXkXlXlXlXjXbX2Xo.6.[.*X#X8.  $   7.JXdXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   L tXq.% @.dXxXkXlXdXJXt.    I W T &.`.SXxXkXlXlXkXkXcXyX( % p.dXlXkXlXlXlXkXzXdX8XvXAXmXSXiXw o   >.JXfXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   J sX[   V.vXlXkXlXdXJXr.  X       . .  .dXlXjXlXlXkXlXxXa.  -.lXkXkXlXlXlXlXkXzXbXkXgXgXvX0X,     z.FXfXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   J fX!   ~.MXkXkXlXdXJXt.. A +.} 7   .   r.SXfXkXlXkXjXBXC.  #.zXkXkXlXlXlXkXlXkXjXkXkXbXgX_     K iXlXjXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   J gXE   |.VXjXkXkXjXbX,X6XvXzXbX0Xh .   G wXxXjXlXkXhXSXI.  @.xXkXkXlXlXlXlXkXlXkXkXnX8XL     B 4XvXhXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   J fX!   E.mXkXkXlXkXzXmXlXgXhXjXlXh.    h &XmXhXlXkXjXMXN.  #.zXkXkXlXlXlXkXlXjXlXbXXXp     T wXkXgXlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   J sX|   m.cXlXkXkXxXpX5XnXSXmXCXBX&.    v >XnXhXlXkXlXzXy.  :.kXkXkXlXlXlXlXjXcXlXD.1   1 9.SXZXZXMXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   L eXa.; ] aXxXkXjXmX-X} 6.(.$X+Xl.; #   _ xXjXkXkXkXvXwXI : g.sXlXkXlXlXlXkXkXhXi.&     /  X~./.W.*XzXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   I 1X#XN   wXnXkXhXmX%Xg   : g a   .   q {.BXgXlXlXjXBX=X  Z ).wXxXkXlXlXlXhXbX>Xz   * $ t < 2 7 + &.cXjXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y =XfX_   D.zXlXjXxXtXp.m &       1 ^ }.nXgXlXkXkXlXlXh.  { -X7XcXkXlXlXlXhXnX*Xj   X         O   ' lXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y :XwX_.5 5 dXzXlXkXxXlX2X{.^.T.W. XpXBXhXlXkXkXkXbX8X$ d E..X9XcXkXlXlXlXkXzXpX_.J.I.P.U.U.U.Y.H.OXlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X<XGXE   %.NXkXlXkXlXnXCXSXDXSXVXxXhXlXlXkXkXzXcX)   *.kX^.wXcXkXlXlXlXlXkXxXZXFXDXFXFXFXFXDXGXBXkXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X4XnX<X7 X c.BXkXkXkXjXhXhXgXhXhXjXlXlXkXkXzXmXe.  f yXeX_.wXcXkXlXlXlXkXlXkXhXgXgXgXgXgXgXgXgXjXlXkXkXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X5XxXbX).& # z.nXvXkXjXkXkXkXkXkXkXkXhXlXbXxXe.  5 +XNX9X'.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXoX{.4X~   o                                             o   Y <X5XcXjXnXV.:   #.qXxXVXvXlXjXhXjXlXvXVXlX6X)   6 Y.nXxXqX`.wXcXkXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvX9X}.OXoXoXoX",
"oXoXXX}.4X/   # o o o o o o o o o o o o o o o o o o o o o o #   R ,X5XxXjXjXmX(.r   w b.=XrXxXBXSXNXzXqX&Xd.2   f +XnXhXxXqX'.wXxXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcX9X}.OXXXoXoX",
"oXoXoX{.5X^   o                                             o   T <X7XMXcXcXxXVX6X@.t   % E u.M.J.n.r.K @   a -.tXNXxXcXMXrX_.tXMXcXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXcXMXwX{.OXoXXXoX",
"oXoXXX X&Xq.I / ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ / I 7.$X>XqX9X9X9X6XeXgXG.] V $           = S | E.jXqX7X9X9XqX<X}.1XqX9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9XwX,XXXOXXXoXoX",
"oXoXXXOX{.*X7X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X4X7X=X|.XX{.}.}.}.}.[.`.$X,X_.k.4.:.-.>.5.x.[.<X+X`.[.}.}.}.{..X@X X{.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.{.XX X|.oXXXoX",
"oXoXoXXXOX.X{.}.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.}.{. X+XoXOXOXOXOXOXOXOX X|.OX-X1X2X3X2X<X-XoX}..XOXOXOXOXOXOXoXoXoXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX|. XoXXXoX",
"oXoXXXoXXXXXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXXXXXXXoXXXoXoXoXoXXXoXXX.X X|.}.}.}.|. X.XXXoXXXoXoXoXXXoXXXXXXXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXXXoXoXXXoXoX",
"oXoXoXXXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXXXXXoXXXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXXXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXXXoXXXXXoXoXoXoXoXoXoXoXoXXXXXXXXXXXXXXXXXoXoXoXoXoXoXoXoXoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXoXoXoXoXoXoXoXoXXXXXXXXXXXXXXXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXXXOXoX.XXXXXXXXXXX.X X XoX+X@X#X@X@XOX.X X.XXXXXXXXX.XXXXX@X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X@XoXXX.XXXXXXXXXXX.X X.XOX@X@X#X@X+XoX X X.XXXXXXXXX.XXXoXXXoXoXoX",
"oXoXXXoXOX@X@X@X@X@XOXXX-X>X@X{.'.'.'.].XX-X>X+XXX@X@X+X+X@X}./././././././././././././././././././././././././.].@X+X+X@X@X@XXX+X>X-XXX].'.'.'.{.@X>X-XXXOX@X@X+X@X+XOXXXoXoXoX",
"oXoXoX.X@XzXlXlXlXhXcXCX3XE...1       # D M.#XxXBXgXlXkXvX8X;Xj   X                                           : XX3XvXkXlXlXhXBXxX#XM.S @       1 X.E.3XZXcXhXlXkXvX=X XoXoXoXoX",
"oXoXoXXX@XlXkXlXhXnXtXk.e   = J `  .[ Q w   o $.@XVXhXjXcX7X;Xj   X                                           : XX2XvXkXkXhXBX@X%.X   e Q [  .` J =   e h.tXnXhXkXcX=X XoXoXoXoX",
"oXoXoXXX@XlXlXjXNX=XM   k j.{.uXnXGXVXhX*XF./   : B.MXkXxX7X;Xj   X                                           : XX2XvXhXkXmXN.:   ( F.=XhXVXGXnXuX[.h.h   M -XNXhXcX=X XoXoXoXoX",
"oXoXoXXX@XlXhXNX_.e X 5.qXCXVXzXhXfXgXkXnXFXgXY.w X q.zXcX7X;Xj   X                                           : XX2XcXkXxXq.X w T.gXFXnXkXgXfXhXzXVXCX0X5.X e _.MXzX=X XoXoXoXoX",
"oXoXoXXX@XhXnX=Xq $ G.BXbXdXaXsXdXdXfXgXhXfXzXCX<XM   x.VX6X;Xj   X                                           : XX3XxXmXx.  N <XCXlXsXdXdXdXdXfXjXgXgXbXBXG.# w =XBX%X XoXoXoXoX",
"oXoXoXXXOXcXrXN   H.CXkXjXnXAXHXKXJXFXmXhXkXkXgXNX4Xg . ].tX=Xj   X                                           : XX1XCX^.. j 5XNXgXkXnXZXHXKXPXAXlXlXlXjXkXCXG.  B pX:X}.oXoXoXoX",
"oXoXoX.XXXZXj.  7.BXjXkXzX#XD.f.e.r.c.OXmXzXkXlXfXCX{.o B wX=Xj   X                                           : XX<XBXv o {.CXfXlXhX*XL.p.0.1.D.kXkXkXkXkXkXBX6.  z.7X{.oXoXoXoX",
"oXoXoX X-X3Xr i 0XbXjXjXmXv   .     . < 7.hXkXkXlXfXAXo.# w.qXd   X                                           : }.uXN.o +.ZXgXkXbX5Xz .   O   U hXlXjXlXkXjXbXqXy i ~.#X.XoXoXoX",
"oXoXoX X>XW.  l.CXgXkXjXnXg x ' X.b O   + Q.ZXgXkXkXxX6X  A 0Xf   X                                           ; |.tX(   8XxXkXjXmX,Xq x W ;   ! kXkXkXlXkXkXgXVXj.  j.*X.XXXoXoX",
"oXoXXXoX@X .* [.VXgXlXkXlXgXnXKXGXcXa o   M.GXfXkXkXzXkXB 6 _.c   X                                           - %X~.a B kXzXkXkXlXhXaXmX'.=   R kXkXkXlXlXlXgXVX].* E oXoXXXoXoX",
"oXoXXX+X{.2 K iXzXjXkXlXkXvX4Xm.N.=.&   9 +XMXhXlXkXkXvXh.  v.B   X                                           * <Xp.  j.vXkXkXlXkXlXlXmX_.=   R kXkXkXlXlXkXjXzXyXJ : [.@XXXoXoX",
"oXoXXX@X'.  ` nXhXkXlXkXkXmXD.  o     h }.bXhXkXlXkXjXmXT.  a.Z   X                                           & 4X5.  R.mXjXkXlXlXkXjXnX_.=   R kXkXkXlXlXlXkXjXbX`   '.@XXXoXoX",
"oXoXXX#X'.  ..HXfXkXkXlXjXcX$X&.*.j   < 6.aXzXjXlXkXjXBX|.  i.A   X                                           & 4X2.  |.BXjXkXlXlXlXjXnX_.=   R kXkXkXlXlXlXkXfXHX .  '.#XXXoXoX",
"oXoXXX@X'.  [ VXgXkXlXkXxXjXgXhXfXyXP     v.CXhXkXkXjXMX^.  p.Z   X                                           & 4X3.  /.MXjXkXkXlXkXgXcX(.=   T gXgXhXlXkXlXkXgXBX[   '.@XXXoXoX",
"oXoXXX@X].# W hXkXkXkXzXpXbXSXNXNXIX,.    @.lXlXkXkXkXbXB.  j.C   X                                           * 2Xw.  C.bXkXkXlXkXlXbXSX}.=   Q MXMXcXkXlXkXjXlXfXE O ].@XXXoXoX",
"oXoXXXOXXXD y =XnXhXhXBXD.&.L. X XN.8 O   7.MXjXkXkXzXkX[ % I.n   X                                           = -XD.2 { lXzXkXkXzXfX$X@Xv.&   A .X.X6XzXkXkXhXmX&Xt v  XOXXXoXoX",
"oXoXXX.X-XN.  G.FXfXfXSXq.  X 4 4 o .   i ;XmXhXlXkXxXfX@ c <Xh   X                                           ; XX2XP o gXxXkXjXbX8XC 2 2 .   # 6 3 a.mXjXlXfXFXD.  0.$XXXXXoXoX",
"oXoXoX X>X#X  ^ fXzXhXnX.X{ u %   , x 4.4XcXjXlXlXhXNXb.  } tXd   X                                           : {.sX4.  M.NXhXkXnX4Xi   . . .       7.MXjXkXzXfXQ   H.&X.XXXoXoX",
"oXoXoX.X+XcX=.  Y.CXgXlXzXkXdXsXaXaXdXcXbXjXlXlXhXcXuX7 t OX,Xh   X                                           : .X5XeX0 8 iXcXhXlXkXsXpXpXiXuXiXpXpXgXlXlXgXCXU.  :.;X XXXoXoXoX",
"oXoXoXXXXXBX+X2 9 <XNXfXlXzXxXcXcXcXxXlXjXkXlXhXlXbX'   s.sX*Xk   X                                           : XX,XGXr.  [ nXlXhXlXxXcXcXcXcXcXcXcXzXlXfXNX>X7 3 &X4X{.oXoXoXoX",
"oXoXoXXX@XgXVXN.X N 4XCXfXkXkXkXkXkXkXkXkXkXhXcXbX<.  / bX7X;Xj   X                                           : XX2XvXlX/   1.nXcXhXkXkXkXkXkXkXkXkXkXgXCX3Xm X B.AX$X XoXoXoXoX",
"oXoXoXXX@XlXhXMXw.  g ].ZXxXzXkXjXjXjXkXzXxXNXuX'   A rXnX7X;Xj   X                                           : XX2XcXzXrXZ   ] iXNXxXzXkXjXjXjXkXzXxXZX'.f   e.mXzX=X XoXoXoXoX",
"oXoXoXXX+XkXjXkXzXx.X O X.7XkXvXmXBXMXbXkXfXn.7   ^ tXlXzX7X;Xz   + o o o o o o o o o o o o o o o o o o o O   < XX2XcXgXzXrX!   8 m.dXkXbXMXBXmXvXkX6X..o o v.xXjXxX=X XoXoXoXoX",
"oXoXoX.X@XvXcXxXcXVX].V #   B h.T. X/.V.[ &   r a.bXnXzXmX9X;Xk   X                                           : oX4XMXxXzXnXbXa.t   & [ V./.|.T.g.N   # B ].VXcXzXmX-X XoXoXoXoX",
"oXoXoXXX+XwXwXwXwX0XaXuXu.H 8           * m o.&XjXwXqXwXrX<X@X+.H T Y Y Y Y Y U I L K K K K L I U Y Y Y Y Y P ^ }.:XtXqXwXqXwXjX&XX.M =           0 J i.uXaX0XwXwXrX%XXXoXoXoXoX",
"oXoXXXoXOX'.].].].].`._.%X&XR.z.a.i.p.h.F.oX-X[.).].].].`. X X=X1X,X<X<X<X,X,X<X6XrXiXaXaXiXrX6X<X,X,X<X<X<X<X>X X.X`.].].].]._.{.-X}.v.7.<.>.1.e.J.%X%X`.`.].].].'.oX+XXXoXoXoX",
"oXoXoXXX+XpXpXpXpXuXpXfXdX5Xn._ F N Z T 9.+XpXfXsXuXpXiXsX6X}.8XrXwXeXwXqXuXpXrXI.) z u u z ) I.rXpXuXqXwXeXeXqX.X,XdXiXpXpXpXpXuXrXuXjXvXbXnXbXxXfXtXtXiXpXiXpXiXsX&X.XoXoXoXoX",
"oXoXoXXX@XcXxXxXlXcXmX<X_ # $ ; ; & = : & O g E.lXMXkXzXnXrX'.aXbXxXzXzXNXuXu.< # > 1 ; ; 1 > # < u.uXNXzXzXcXkX{.4XmXzXxXxXxXxXxXxXzXlXkXjXjXjXkXlXxXxXxXxXxXxXzXnX-X XoXoXoXoX",
"oXoXoXXX@XlXkXhXvXfX5.+ - N 8.oXwXcXaX>XM.T 9   G :XmXgXxXwX].iXxXhXlXnXP.0 X d X.Q.5XkXkX5XQ...d X 9 I.mXlXkXhX}.3XcXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXcX=X XoXoXoXoX",
"oXoXoXXX@XlXjXvX9X`   m L.NXAXvXzXkXlXcXNXJX&X..  u ).vXxXwX].pXzXlXkXd.+ 3 i.pXHXnXxXlXlXxXnXHXiXu.4 + d.jXzXgX}.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXX@XkXzXfXY   #.pXAXfXgXjXjXjXjXhXgXdXmXVXV.4 < .XBXqX].iXzXmXs.  V @XGXlXdXhXhXjXjXjXjXfXlXGX+XC   s.MXgX{.3XvXjXlXlXlXkXlXkXkXjXjXjXjXjXkXlXkXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXX+XjXvX#.  :.cXvXdXkXlXkXzXMXNXBXvXkXgXhXZXY.; r wXtX'.uXNXP.  B 4XVXdXkXcXnXNXNXBXcXkXlXjXdXVX4XN   Y.vX{.3XvXjXlXlXlXlXkXkXxXnXMXNXMXbXjXjXlXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXXXXAXP.  U jXcXhXlXlXkXzXdX;X&X$X9XcXkXjXgXSXh.  [ hX).fXuX6 5 @XVXfXkXkXiX6X-X&X$XrXzXkXkXkXfXVX@X4 0 wXXX2XvXjXlXlXlXkXlXxXsX6X<X-X;X8XnXxXkXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoX X%XuXI . *XNXhXlXkXkXgXVXa.  +   &.LXdXlXkXjXVXV < P.oXdXi.  i.GXdXhXMX{.I 3   o   k.nXkXkXlXkXdXGXi.  e.OX2XvXjXlXlXkXkXxX/.E q .   X i q.pXxXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoX|.,X{.  4.bXjXkXkXlXhXNXoX4   $   2.JXdXkXlXkXvX}.  W -XtX, g pXlXjXfXGXp.  4 0 o   c.nXkXkXlXlXjXlXiXh ;  X3XvXjXlXlXkXlXxX<.  & p e   X   -.xXlXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXXXX%Xq.  E.SXgXlXkXkXxXsXK   p %   <.KXdXlXkXkXxXjX0 f _.W.+ ..HXfXlXjXbX<X~.=X>.    z.nXkXkXlXkXlXfXHX..O x.8XcXjXlXlXkXlXzXl.:. X,X>X;.  o $ yXcXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX+X|.a m 6XcXjXkXlXjXmXp.  ` 3.O   <.KXdXlXlXkXlXzX5.  M.@.- Q.nXjXkXlXkXvXZXCXw.    z.nXkXkXlXlXkXjXnXW.; W tXzXjXlXlXkXlXkXaXxXCXcXDX>X*   O rXcXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX@X'.  ( xXjXkXlXjXMXXXo 2 <Xs.    <.KXdXlXlXkXkXnXJ.  d.K : 6XxXkXkXkXlXjXhXzX9.    z.nXkXkXlXlXkXkXxX4X1 l iXlXjXlXlXlXkXlXxXlXgXsXSXF.    K jXzXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X'.  | DXfXkXkXlXdXv   p.PX5.X   >.SXsXlXkXkXjXBX[.  p.B * kXlXkXlXlXlXkXkXcX0.    z.nXkXkXlXlXlXkXlXkX: i pXlXjXlXlXlXlXkXkXkXhXZXE.9   q +XbXkXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X'.  | DXfXkXgXCX1.  ..HXUXs.X   9.UXhXkXlXkXjXNX].  p.B * kXlXkXlXkXlXkXkXxX9.    z.bXjXkXlXkXlXkXlXkX> i pXlXjXlXlXlXlXlXjXlXMXl.-   u .XbXjXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX@X'.  ( xXjXjXgXBXG   u b b 8     8 d &XMXjXkXkXnXH.  d.K : 6XxXkXkXlXkXlXxXnXq.    c.NXzXlXkXlXkXkXxX4X1 l iXlXjXlXlXlXkXjXvXgX=.X   J 8XVXzXlXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX+X|.a m 6XcXhXgXNXG   o           o   XXVXjXkXlXzX4.  M.#.- Q.nXjXkXkXlXhXaXfX6.    h.jXaXjXlXkXkXjXnXE.; Q tXzXjXlXlXkXkXxX7XP     ! 7XpX0XeXhXlXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXXXX%Xe.  E.SXfXjXvXA.4.r.w.a.L @   G u.5XbXkXkXxXjX8 f `.Q.@ ..HXfXlXhXMX{.^ E g o X c R ' #XnXhXlXfXHX| o c.8XcXjXlXlXkXlXxX3.  # $ x x h h k -XcXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoX X,X{.  3.bXjXkXkXNXAXZXBXUX7..   -.UXgXkXlXkXbX{.  W -XtX< g iXlXjXfXSXn.          .   & I.CXgXjXlXuXh : |.3XvXjXlXlXkXlXzX$.  X              XbXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoX.X%XiXI   &XNXhXlXhXgXgXfXlX$XD.V.OXxXhXlXkXjXNXM < P.oXdXp.  u.GXdXjXvX4XJ.F.F.S.S.F.F.P.9XcXjXdXGXy.  e.OX2XvXjXlXlXkXlXlX@XC.D.D.F.F.F.F.F.rXzXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXXXXAXI.  P jXcXhXlXkXkXlXkXMXFXGXMXjXlXjXgXSXd.  { hX).fXuX7 4 +XVXfXjXbXDXFXFXFXFXFXFXSXvXkXfXVXOX2 q wXXX2XvXjXlXlXlXkXkXNXGXFXFXFXFXFXFXFXcXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXX+XjXbX%.  ;.xXbXdXkXlXkXlXjXgXfXjXlXgXhXZXI.- y eXtX'.uXNXU.  N 4XVXfXhXgXgXgXgXgXgXgXgXhXfXVX2Xm   T.bX{.3XvXjXlXlXkXlXlXjXgXgXgXgXgXgXgXgXkXlXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXX@XkXzXfXT   @.iXAXfXgXjXkXkXkXjXhXdXmXVXN.3 1 XXBXqX].iXzXmXd.  V +XGXlXfXjXkXkXkXkXjXfXlXGXoXB   f.NXgX{.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXoXXX@XlXjXvX9X`   b J.NXSXbXxXkXzXcXNXJX%X .  i _.cXxXwX].pXzXlXjXd.+ 2 y.iXHXnXxXlXlXxXnXHXiXy.2 @ g.kXzXgX}.3XvXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXcX=X XoXoXoXoX",
"oXoXoXXX+XzXzXkXbXhX9.# - N 7.XXqXcXaX;Xm.T 0   K ,XNXjXvXeX'.pXcXkXzXMXY.e X f ..W.4XkXkX4XE...f X e Y.MXzXlXjX}.3XbXkXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXvX=X XoXoXoXoX",
"oXoXoXXX@XsXaXaXiXdXhX$XW   X = - & = ; @   y K.pXjXuXpXfX8X[.yXkXhXgXgXvXwXr.; X * : * * : * X ; r.eXvXgXgXjXfX}.2XzXgXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXgXlX=X XoXoXoXoX",
"oXoXoXXXXX<X<X<X<X,X<X6X7X=Xz.) D M Z Y 5.{.6X6X3X,X<X<X2X*XXX X{.}.}.{.{.XX.X].b.} H B B H } n.[..XXX{.{.}.}.}.+XXX{.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.{.oX+XXXoXoXoX",
"oXoXXXOX(.;.>.>.>.>.:.:.:.,.5.q.e.r.r.w.8.1.:.:.:.>.>.,.&.g.+X>X3X3X3X3X2X,XqXsX&XA.f.p.p.f.A.&XsXqX,X2X3X3X3X2XXX*X4X2X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X2X4X$XoXoXoXoXoX",
"oXoXXX#X).                                            o   Y <XyXmXcXvXcXmXFX[.X.M +         + M o.[.GXmXcXvXbXzX{.4XNXcXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXcXMX-X XoXoXoXoX",
"oXoXXX@X/.X O O O O O O O O O O O O O O O O O O O O O $   R ,XwXzXjXjXnX6X( :   q 5.K.[.[.K.5.0   ; ( 7XbXhXkXgX}.2XcXhXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXxX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y <XeXxXhXvXoXr   C .XkXzXnXNXNXnXzXkX|.B   t oXvXkXhX}.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y <XeXkXmX_.< - h.VXvXxXlXkXjXjXkXlXxXbXBXh.; < _.NXdX}.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y <XqXMX-Xw , Y.SXjXjXhXhXhXhXhXhXhXkXkXjXSXU.> w >XcX[.3XvXjXlXlXlXkXlXkXjXjXhXhXhXjXkXkXlXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XtXlXH   Z.ZXgXjXbXCXCXCXCXCXCXCXvXkXkXgXZXC.  P fX X2XvXjXlXlXlXlXkXxXmXBXCXCXVXNXbXkXkXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XiXQ.  o.VXgXdXDXx.4 y e e e q p E.mXhXjXgXVXo.  U.OX2XvXjXlXlXkXkXzX1Xg./ c i x [ }.vXkXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XiXf 9 *XnXgXfXJXq.  o         @ D.NXhXlXgXmX&X9 a oX2XvXjXlXlXkXlXcX6.  X         . V.bXkXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   U 3X.XO R JXdXlXfXHXu.  * x.J.D.m.h.;XcXjXkXlXdXJXR . J.6XcXjXlXlXkXlXxX0.f 6.D.n.N     9 aXxXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   P wX=.= N.NXhXkXfXHXy.  * q.9.i./.SXMXjXlXkXkXhXNXM.* X.eXzXjXlXlXkXlXkX-XwXJXNXLXOX+   o rXcXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   K iXM 1 >XcXjXkXdXHXr.  o       o J 9XcXjXlXkXjXcX;X1 n uXlXjXlXlXlXkXlXnXxXdXaXBX XO   u sXxXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   K pXa > sXlXkXlXfXGXa.> ^ <.~ =     ` VXgXkXlXkXzXaX, s pXlXjXlXlXkXlXkXjXjXgXNXqXG     C.bXkXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   K aXy ; cXkXkXkXkXcX6XiXNXxXFXv.@   y >XvXhXlXkXkXcX: u pXlXjXlXlXlXkXlXkXgXBX%Xb   # g.vXkXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   K pXg < wXzXkXlXkXzXVXlXfXfXkX5Xt   6 [.MXhXlXkXxX0X1 g iXlXjXlXlXlXlXkXkXNXY.4   : D.bXgXjXlXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   L yXJ < oXvXjXkXcXeX!.dXSXbXLXF.%   t ;XvXhXkXjXbX.X, D yXzXjXlXlXlXkXzXzXu.=   m =XPXNXVXxXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   P 9Xh.% 7.SXgXjXbX2Xc q $.s.#.2     ( BXgXkXlXgXSX5.@ 9.0XxXjXlXlXkXkXcXh.  O @ Y :...O.+.4XxXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   U 1X3X$ B NXfXjXcX9XF   X       o H 0XcXjXlXkXfXMXV O ).4XcXjXlXlXkXlXzX#.  X             .XvXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XaX' + J.AXdXkXzX8XV.-._ Q #.F.zXcXkXlXlXdXSXH.@ / +X2XvXjXlXlXkXlXzXB.K E T T R R T R <XcXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XiX1X  m iXvXhXkXxXVXFXJXKXGXBXkXkXlXlXhXbXuXn   -XoX2XvXjXlXlXlXkXkXVXPXLXLXLXLXLXLXLXvXkXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y ,XeXmX8.  #.cXcXhXjXgXfXdXdXfXhXkXlXkXhXcXxX+.  q.xX}.2XvXjXlXlXkXlXlXhXdXdXdXdXdXdXdXdXjXlXkXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y <XqXcXgX(   -.jXNXjXfXjXkXkXkXkXjXfXjXNXhX=.  _ jXjX{.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX#X/.                                            o   Y <XeXlXvX0XY   L &XbXSXcXjXfXfXkXcXSXbX%XK   T qXbXfX}.3XvXjXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcX=X XoXoXoXoX",
"oXoXXX@X/.. o o o o o o o o o o o o o o o o o o o o o #   R ,XwXzXgXcXfX#.  : ,.R.5XzXDXDXzX5XR.,.:   $.gXcXjXgX}.2XcXjXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXxX=X XoXoXoXoX",
"oXoXXX#X(.                                            o   Y <XtXnXcXxXbXMXE.I   X v / | | / c X   I E.MXvXxXvXlX{.4XMXxXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXxXmX-X XoXoXoXoX",
"oXoXXXOX_.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.m.v.G.XX&X=X=X=X*X&X8X.XB.$.w         w %.B.XX8X&X*X=X=X=XoX$X-X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X-X@XoXoXoXoXoX",
"oXoXoXXXoX-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X;X%XoXXX X X X X X[.oX*X@X}.'.'.'.'.}.@X*XoX[. X X X X X+XoX X X X X X X X X X X X X X X X X X X X X X X X XoX].oXXXoXoX",
"oXoXXXoXoX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.XoXoXoXoXoXoXoXoXXX.XoX+X@X#X#X@X+XoX.XXXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXXXoXoXoXoXoXoXoXoXXXXXXXXXXXXXXXXXXXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXXXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXXXoXoXoXoXXX X|.|..XoXoXoXoX.X|.|.|.|.|.|.|.|.|.|.|.|.oXoXoXoXoX.X|.|. XXXoXoXoXoXXXoXoXoX",
"oXoXXXoX.X|.|.[.+X>X2X2X;XXX[.|.|.#X<X,X,X,X,X,X,X,X,X,X<X>XXX|.|.[.XX;X2X2X>X+X[.|.|.XXoXXXoXoX",
"oXoXoX.X-X6X6XdX}.5.( ' a.:XaX3X8XA.{ +.o.o.o.o.o.o.o.O.X.&.OX7X3XsX:Xa.' ( 5.}.dX6X4X@XXXoXoXoX",
"oXoXoX|.6XNXbX,.n &.f.a.[ v M.SXbX8.  o               .   ; $XbXSXM.b ] p.f.*.n >.nXbX@X.XoXoXoX",
"oXoXoX|.6XbXU { gXUXIXLXAX>XM 6.GX7.  @ o o o o o o o O   < +XDX6.M ,XLXUXLXDXsX{ Y zX$X.XoXoXoX",
"oXoXoX[.dX>.{ UXsX].W.-XxXBXcXc R.d.  o               .   = 3XY.c vXBX-X/.OXgXxXPX} -.5X}.oXoXoX",
"oXoXXX+X}.N iXDXV.r k X u.nXBX`.L y.  X               .   ; :XJ _.GX3Xn X h zXhXzXdXb R.#XXXoXoX",
"oXoX X>X4.=.SXhXsX%XY.O ^ AXgXkXW `   .               .   6 C.I zXkXsXjX^ r vXlXfXDX%.>.,X XoXoX",
"oXoX|.2X( j.FXdXCX6.= & `.NXdXZX+.S                   .   w w.' SXgXjXSX! w lXkXgXFXh.) 2X|.oXoX",
"oXoX|.2X' d.DXgXzXGXDXg l mXgXBXo.F   .               .   q t._ ZXgXjXUX[ i LXvXfXDXs.' 2X|.oXoX",
"oXoX.X;Xs.{ ZXvX;.W {   W MXjXaXP O.  X               .   3 Y.G sXcXyX2.0 = o.:XzXAX' w.:X XoXoX",
"oXoXoXXX:Xm :XSXE.@. .z.aXgXJXm.( d.  o               .   = 3X/ m.IX0X*.@.=.} %XDX:Xc }.OXXXoXoX",
"oXoXoX[.aXM.M xXPXHXFXCXxXJX=Xi :Xi.  O . . . . . . . X   ; >X-Xp =XLXJXDXSXJXGXxXM b.4X}.oXoXoX",
"oXoXoX|.4XHX9.n _.gXNXmXdXN.d W.JX6.  o               .   : +XHXE.d B.sXBXCXkX'.n q.SX+X.XoXoXoX",
"oXoXoX X<XuXxXN.b R %.+.F F [.zXiXa.3 u q t j b b j t w q j +XyXzX|.G n ~ / A c C.cXrX@XXXoXoXoX",
"oXoXoX.X&X,X=XlX1X%.j b u.pXpX*X-X%X7X3XaX6XB.1.1.V.6XaX4X2X@X<X-X7XeX'.m.v.E.7XwX;X>X+XXXoXoXoX",
"oXoXoX|.6XmXCXg.n | q.6.W C !.JXyX,XcXAXS.M E =.-.W M S.FXsX:XvXcXzXlXmXAXSXBXxXlXcXxX#X.XoXoXoX",
"oXoXoX|.4XCX .J 1XNXGXLXMX(.g b.cX*XDX5.n @XZXIXKXNX+Xn 8.nX*XlXkXkXjXzXvXzXgXkXkXkXjX#X.XoXoXoX",
"oXoXoX[.dXy.I DXnXlXuX-XiXFXtXj Y.gXA.n vXZXwX;X7XjXVXvXM m.0XjXkXkXcXiX,XwXMXlXkXlXkX#X.XoXoXoX",
"oXoXXXOX#XM qXbXhXkXz   E.mXAXR.Z 9XC OXHX@Xf   U NXsXVX$Xv ;XxXhXNX(.9 7 # q.nXjXlXkX#X.XoXoXoX",
"oXoX X:Xw.+.DXsXDX=.u   K.CXgXjXP 3._ MXkXtX<Xj Z VXjXgXVXU N.CXgXnX&XE.gXU o pXcXkXkX#X.XoXoXoX",
"oXoX|.2X_ g.AXMXT.S +X  `.FXsXCX$.z 0.SXfXlXAXc V NXhXgXGX-.5.GXgXkXxXKXfX0 U mXjXkXkX#X.XoXoXoX",
"oXoX|.2X_ g.SXvXh ! 6.  ..aXjXVX#.z 0.SXfXzXIXM H UXlXfXGX=.6.GXgXhXNX*Xy } SXcXjXlXkX#X.XoXoXoX",
"oXoX X:Xw.O.SXhX@.N p   y 4XbXgXL 4._ MXlX0Xd.6 w j.eXlXBXU N.CXfXMX Xo 2 6.9.rXxXkXkX#X.XoXoXoX",
"oXoXXXOX#XM qXnXxXGX6XK *XnXAXT.Z 0XC OXFX;XL T U U 1XDX@Xv ;XxXhXNX_.K ~ Z P qXcXkXkX#X.XoXoXoX",
"oXoXoX[.dXu.I DXnXdXjXZXlXSXrXh Y.gXA.n cXAXSXCXZXAXAXcXm M.0XjXkXjXbXFXSXGXFXzXkXlXkX#X.XoXoXoX",
"oXoXoX|.4XVX .H ,XBXSXVXbX/.f n.xX=XGX8.M @XnXCXCXnX@Xm q.MX=XcXzXzXlXhXjXjXjXzXzXzXlX#X.XoXoXoX",
"oXoXoX|.8XNXSXz.N { 8.4.W F ).LXpX;XdXmXb.j ~ 0.0.~ j b.NXrX=XfXsXsXsXsXsXsXsXsXsXdXsX#X.XoXoXoX",
"oXXXXX@XY.x.b.L.l.] A F #.V.G.z.C.#X:X$XsX8X2.z z 3.8XsX%X=X#X;X;X;X;X;X;X;X;X;X;X;X;X+XXXoXoXoX",
"oXoX|.,Xo.  o     X $ # .   .   r 6XzXSX_.L R #.#.R L _.FXaX;XcXzXzXzXzXlXzXzXzXzXzXlX#X.XoXoXoX",
"oXoX|.,XO.  + . .         . o   y 2XDXx.f U.kXAXAXjXP.f b.MX*XzXkXkXjXkXxXlXhXkXkXkXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   w iX~.g yXDXaXtXrXfXGXtXj Y.8XkXkXkXbXbXaXlXBXkXkXlXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   r qXD /.UX`.< d 3 $.vXZX`.m 1XzXhXMX}.f 0 7 m.nXjXlXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   h G.Y bXNX(.  ..e.>XvXgXNXJ S.VXgXmX Xz.;XB # pXxXkXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   b 3.-.AXmX'.t B . #.nXfXFX*.7.FXgXkXxXKXSXj n vXkXkXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   n ,.:.GXgXlXVXUX@.. 7XzXFX;.4.GXgXjXMXqXb D xXbXjXlXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   l c.( NXnXD.5.K.t r dXjXVXQ c.ZXfXnX=X< 1 x.A.uXxXkXkX#X.XoXoXoX",
"oXoX|.,Xo.  o               .   y ,XN >XSX^.A g J +XcXnX2Xz $XcXgXBXE.u B p l 8XvXkXkX#X.XoXoXoX",
"oXoX|.,XO.  o               X   q sXh.J SXAXBXnXBXcXvXDXK i.wXjXkXkXcXBXmXBXBXlXkXlXkX#X.XoXoXoX",
"oXoX|.,XO.  o               .   r 4XCX..U 0XAXSXAXAXwXI O.vX-XzXkXlXkXjXjXjXjXlXlXlXkX#X.XoXoXoX",
"oXXX|.,XO.  @ X X X X X X X O   y 4XzXMXe.l ..f.f...l e.BXsX-XlXkXkXkXkXkXkXkXkXkXkXjX#X.XoXoXoX",
"oXXXXXOX).Y.R.R.R.R.R.R.R.R.R.T.Q.+X#X@X6X).5._ _ 5.).5X@X@X+X#X#X#X#X#X#X#X#X#X#X#X#XXXXXoXXXoX",
"oXoXoXXX+X$X$X$X$X$X$X$X$X$X$X$X#XXX.X.X}.@X>X2X2X>X@X}..XXXXX.X.X.X.X.X.X.X.X.X.X.X.XXXXXoXoXoX",
"oXoXXXoXXX.X.X.X.X.X.X.X.X.X.X.X.XoXoXoXoXXX X|.|. XXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXXXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXXXoXoXoXoX.X X X XXXoXoXoX X|.|.|.|.|.|.|.|.|.|..XoXoXoXXX X X X.XoXoXoXoXXXoXoXoX",
"oXoXXXoX.X|.{.XX:X,X,X,X#X[.|. X-X<X,X,X,X,X,X,X,X,X<X#X|.|.[.#X,X,X,X:XXX[.|.XXoXXXoXoX",
"oXoXoX.X,X8XsX<Xy.( Q ;.`.gX9X2X:.W ( / / / / / / ) T B.wX7XgX_.;.Q ( y.<XdX7X$X.XoXoXoX",
"oXoXoX|.8XJXW.A >.J.T.s.J 6.CXpXl   X             o   9.BXNX6.J a.T.L.<.A Q.GX%X.XoXoXoX",
"oXoXoX{.sXW.M 1XUXIXIXPXbX..&.xXz   + o o o o o o @   8.HX$...mXUXIXGXHX1XM R.6X}.oXoXoX",
"oXoXoXXX<XA 1XDX9.T O.+XbXDXE A.S   X             o   f.!.U KXrX=.E U.cXCX2XZ XXoXXXoXoX",
"oXoX.X:Xt.<.JXaXd.b.9 z bXBX).~ A   X             X   d. .^.FX3X0.% 6.DXiXJX>.5.>X XoXoX",
"oXoX X,X( I.VXvX7XU & y.VXkXtXE g   X             X   2.~ tXlXxXGXt 2.AXdXZXI./ ,X XoXoX",
"oXoX X,XQ Q.VXzXxX<XE Z cXzXpXW d   X             X   ,.! aXlXzXDXr t.UXsXCXW.Q ,X XoXoX",
"oXoX X>X:.d.PX*X+.n.a y jXmX&XE M   X             X   r.' %XNXeXa.- N W.jXDXs.#.,X XoXoX",
"oXoXXX#X`.K MXyX<./ :.1XjXPX1.8.G   X             o   k.j.>.UX2X} O._ y.mXvXH P.$XXXoXoX",
"oXoXoX[.gX6. .HXUXLXHXCXPXH.F tXb   + o o o o o o @   w.vXA H.UXPXHXKXIXDX .5.9X}.oXoXoX",
"oXoXoX|.0XSX-.E ~.wXuX%X<.H wXkXk   X             o   8.FX9XJ 2.&XpXeX).W ;.ZX*X XoXoXoX",
"oXoXoX.X;X7XtXB._ T U Q 9.1XwX>X1.~ _ O.%.X.X.%.O._ Q C.7XqX3X-.D F F K x.iX6X#XXXoXoXoX",
"oXoXoX X1XwXhX%X<.A M [ T.gXyX;XtXbXDX{.;./ / ;.{.DXbX<X6XwXrXxXpX5X8XjXjX0XeX%X.XoXoXoX",
"oXoXoX|.8XJXh.Z c.&X>XY.^ ' vX0X0XBX-.J C.$X%XA.J -.NX<XsXbXxXjXkXcXzXkXlXxXvX=X XoXoXoX",
"oXoXoX[.gXv.I lXDXAXGXDXHXt.( 0XjX,.X.ZXIXFXCXSXZXX.,.rXyXzXjXnXAXNXZXcXjXkXlX*X.XoXoXoX",
"oXoXXX+X@XA aXcXNXP.9 A.MXJX .d.[.K AXfX..a 8.nXjXZXI Z.xXjXmX XJ z | eXxXjXzX*X.XoXoXoX",
"oXoX X>X6.e.DXxX5Xp   w.AXbXXX/ #.D.DXyXW.s R SXsXSXF.) MXhXMX_.h.T.  6.FXfXzX*X.XoXoXoX",
"oXoX X,X~ R.VXbX^ J.f s.IXgXpXY V >XbXhXUXK U ZXgXnX-XJ zXlXjXvXUXOXX I.VXhXzX*X.XoXoXoX",
"oXoX X,X~ U.UXT.; 9.- V qXbXuXY V >XnXgXUXP ^ UXgXnX-XJ zXlXjXNXG.9 W.JXgXkXzX*X.XoXoXoX",
"oXoX X>X6.q.UX+XO.` O s 2XAX X/ #.D.DXpX3.1 4 9.sXDXD.) MXgXVXP.  d Q c.BXhXzX*X.XoXoXoX",
"oXoXXX+X@XS pXVXCXDXM.&XNXJX .f.[.K AXhXf.a.i.j.kXZXP Z.xXjXbX#Xf.h.2.!.mXjXzX*X.XoXoXoX",
"oXoXoX[.fXv.P jXAXcXKXGXFXe.( 9XjX,.X.CXUXPXPXUXCX..<.tXyXzXhXnXFXDXJXBXjXkXlX*X.XoXoXoX",
"oXoXoX|.9XJXj.S b.&X-XY.) ] vX0XeXAX,.K C.=X=XC.J ,.AX1XsXbXxXzXjXkXjXlXcXxXvX=X XoXoXoX",
"oXXXoX.X&X>XrXR.] J G W g.9X3X#X-X<XrXE.| B B | W.rX<X%X:X1X<X<X<X<X<X<X<X<X1X#XXXoXoXoX",
"oXXX X:X .$ 3 q a e w i u 4 # +.sXsXfXN.[ Y Y [ N.fXgX;XwXsXpXpXpXiXpXpXpXpXaX&X.XoXoXoX",
"oXoX|.,X/   o             o   _ mXjX^ | oXdXdXXX} ^ zX4XaXvXzXzXxXvXlXlXxXzXcX=X XoXoXoX",
"oXoX|.,X(   O . . . . . . O   _ CX( t.PXcXuXyXvXIXt.] qXuXzXjXbXlXiXnXnXjXkXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   #.R.^ PX0Xs x a j.MXFX` j.bXhXNX~.h e M :XbXjXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   $.$.I.FX7X; D ,.7XzXCXR.! nXhXnX+X(.1X  <.GXfXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   X.^ =XNXtX*.-.*  .NXvX>XH lXlXjXnXUXZ.*  XMXhXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   o.) @XNXrXlXUX) r xXmX$XK zXkXkXcX8.8 @XDXgXlXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   &.5.k.UX'.g M O a.bXDXv.{ NXfXCXA.  p j r.CXhXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   ..;XV lXmXXXK.$XcXmXkXA E.kXkXcX5X(.!.G.%XvXjXzX*X.XoXoXoX",
"oXoX|.,X(   O . . . . . . O   ) FXd.P sXUXIXJXFXaXP k.tXyXxXjXvXCXCXSXmXjXkXzX*X.XoXoXoX",
"oXoX|.,X/   o             o   ` zXZXx.C 8.U.Y.0.C c.FX,XaXcXzXlXjXjXjXkXzXzXxX=X.XoXoXoX",
"oXXXXX+XY.M.V.B.B.B.B.B.B.V.M.T.=X%X8X(.;.~ ~ ;.(.8X&X@X&X=X*X*X*X*X*X*X*X*X=XOXXXoXXXoX",
"oXoXoXXX$X=X*X*X*X*X*X*X*X*X=X#X X.X}.@X,X,X,X,X@X}. XXX.X X.X.X.X.X.X.X.X.X.XXXXXoXXXoX",
"oXoXXXoX.X X.X.X.X.X.X.X.X.X X.XoXoXoXXX X X X XXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXXXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"oXXXoXoXoX.X X X.XoXoXXX|.|.|.|.|.|.|.|.XXoXoXXX X X.XoXoXoXXXoX",
"XXoX.X}.}.*X>X>X*X|.}.@X,X>X>X>X>X>X>X,X@X}.{.#X>X>X;X.X{.XXoXXX",
"oX.X%X8XqXV.-.;.V.0XwXY.%.:.;.;.;.;.:.%.T.7XtX!.2.*.d.:XrX$XXXoX",
"oX}.8XkX*.y..X'.0.&.mXn.  X         X   z.IXd.*.(. Xc.{ ;XtX{.oX",
"oX}.0X*.R.zX.XuXUXL.2.B.  + o o o o +   F.A.6.BX>X9XJX5X] .XOXXX",
".X*XV.9.UXb.) 4 `.UXu.'             X   i.=.mX1Xv n lXFXW.*.:X X",
" X>X:.^.ZXhX&.q ;XSX}.m o               { k.NXCX^.c NXzXrX| +XXX",
" X>X:./.VX>X+X0 C.PX[.m o               { k.BXnXC.j kXzXeX| +XXX",
".X*XV.0.UX<.P U &XUXu.'   .         X   i.=.MX>XA i 4.IXE.*.:X X",
"oX}.qX-.Y.UXcXFXUXP.3.B.  o         o   F.D.6.DXBXVXSX7X[ XXOXXX",
"oX|.6XsXO.e.oX|.q.X.xXb.  X X & * O X   l.HXu.O.P.).l._ $XwX{.oX",
"oX.X%X0XgXq.j h q.hX0X{.R.|.m.O.} i.].!.}.5XuX~.e.6.k.>XtX%XXXoX",
"oX|.5XnX8.4.I.R.4.0.lX7XHXm.;.H.P.9.5.vXqXgXjXMXKXHXCXxXzX4X|.oX",
"oX{.rX8.z.SXCXhXAXc.<.zXd.7.nXdXcXFXP.O.8XhXlXjX3XqXnXhXcX3X|.oX",
"XX%XK.1.GXVX| , wXIX<.l.=.HX|.w { MXLXi.j.NXMXU.P k V.VXlX3X|.oX",
" X>X<.E.IXY.{ j uXZX[.v K.NXVXy.I AXbX#X=.VXjXyXLXJ $.GXkX3X|.oX",
" X>X-._.VXv } = F.HXXXf T.mXGXp.Y HXcX-X&.BXhXcX*.' xXkXxX3X|.oX",
".X=Xx.d.HXH.9.4 L.UXf.=.q.IX'.h 7 x.UXC.0.BXVXV.  G h.MXzX3X|.oX",
"oX X4X...XUXHXfXUX.X' yX:.Y.AXqXwXxX9X` %XzXlXpXeX<X0XlXxX3X|.oX",
"oX{.rXaX+.M.>X4XN.#.eXyXsXo.s.5XwXP.( $XrXgXzXxXbXmXvXkXvX3X|.oX",
"XXOX_.(.T.} H G } T.(..X8XsXs.M z %.6XtX$X4X4X4X3X3X3X4X5X*X.XoX",
"|.>X;.  O & $ $ & .   T.GXF.=.h.x.2.u.lX5XfXjXgXjXhXfXhXlX2X XoX",
"|.>X:.  o         .   }.T.#.gXVXvXvXl.3.rXgXlXbXkXvXNXjXvX3X|.oX",
"|.>X;.  o             D.+.SXG.g ! .XUX3.N.MXMXQ.J Z !.MXzX3X|.oX",
"|.>X;.  o           % %.n.UXi., E -XSX.X;.VXlX3XcXK ..GXkX3X|.oX",
"|.>X;.  o           * | L.AX4XfXJ X.IX*X*.BXfXZXv.( fXzXxX3X|.oX",
"|.>X;.  o           @ 0.t.UXl.| g N.UXL.4.BXBXS.  K M.nXzX3X|.oX",
"|.>X>.  @ o o o o o   ).=. XBX].1XPXgX] }.xXzX7X@X).&XxXzX3X|.oX",
"|.>X;.  o             ).aX] H.fXdX'.} ).iXjXcXmXCXSXBXzXnX4X|.oX",
".X$XZ.$.>.;.;.;.;.:.=._.tX=X<.{ } +./.yX%X2X3X2X1X1X2X3X4X&X.XoX",
"oXXX$X,X>X>X>X>X>X>X>XOX{.XX:X#XOX;X#X{.XX X|.|.|.|.|.|.|..XoXXX",
"XXoX.X|.|.|.|.|.|.|.|.XXOXoX XXXXX XXXoXoXoXoXoXoXoXoXoXoXoXXXoX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"XXoX#X`.@X+X=X-X-X-XOX$X'.+X+XXX",
"oX<XG.L.U._.N B V M }.E.H.Z.*X+X",
"@XK.{.v.=Xq..     o a.XXF.9XV.XX",
"].F.jXA 5Xa.  @ O + 5.AXo.aXW.Q.",
"#XH.].`.,X8.X     o p.OXS.|.S.XX",
"XX7Xb.t.B.+X[ Z n _ @XW.^.H.*X+X",
"#X.XE.).J.$X|.^.+X!.uXkX;XvXyX|.",
" XZ.6X' eXq.|.H.!.;X/.cX>.{.hX}.",
"{.D.[.F <X0.@XP.f.3X).pX( >XdX|.",
"#X X.XyX_.|.T.^.].D.7XaX=XaXrX X",
"#Xe.n f v V.,Xr.7.].iXpXnXhX6X.X",
"-XB   +   W _.N..XU.:XgXF.0XaX|.",
"=XA   $   x qXr.+.0X!.cX[ [.hX}.",
"-XB   +   H {.[.~./.#XtX7.eXaX|.",
"&Xo.x A j e.|.A.Y.I.qXuXjXuX5X.X",
"XX&X-X=X;X#X#X_.~.$X.X|.{. X.XoX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
