#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 76 1 ",
"  c #010101",
". c #0D0D0D",
"X c #141414",
"o c #1E1E1E",
"O c #232323",
"+ c #2C2C2C",
"@ c #343434",
"# c #393939",
"$ c #007D00",
"% c #434343",
"& c #4C4C4C",
"* c #565656",
"= c #5C5C5C",
"- c #646464",
"; c #6A6A6A",
": c #737373",
"> c #7B7B7B",
", c #008300",
"< c #038A03",
"1 c #0B8E0B",
"2 c #0E900E",
"3 c #128C12",
"4 c #188F18",
"5 c #149114",
"6 c #1B941B",
"7 c #229722",
"8 c #259925",
"9 c #2B9A2B",
"0 c #329E32",
"q c #3BA23B",
"w c #44A544",
"e c #4BA74B",
"r c #4DA94D",
"t c #53AA53",
"y c #5CAE5C",
"u c #65B265",
"i c #6BB56B",
"p c #71B771",
"a c #73B873",
"s c #7CBB7C",
"d c #828282",
"f c #8C8C8C",
"g c #969696",
"h c #999999",
"j c #82BE82",
"k c #A4A4A4",
"l c #ABABAB",
"z c #B2B2B2",
"x c #BDBDBD",
"c c #87C087",
"v c #8CC28C",
"b c #92C492",
"n c #9AC79A",
"m c #9CC89C",
"M c #A5CBA5",
"N c #ABCEAB",
"B c #B3D1B3",
"V c #BCD5BC",
"C c #C4C4C4",
"Z c #CBCBCB",
"A c #C1D7C1",
"S c #C6D9C6",
"D c #CCDCCC",
"F c #D4D4D4",
"G c #D3DED3",
"H c #DDDDDD",
"J c #D6E0D6",
"K c #DBE1DB",
"L c #E5E5E5",
"P c #E9E7E9",
"I c #ECEBEC",
"U c #F2EBF2",
"Y c #FAEDFA",
"T c #F5F5F5",
"R c #FFF2FF",
"E c #FAFAFA",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"   .@@@@@@@@@@@#@@@@@@@@@@@@@@@#oO#@@@@@@@@@@@@@@@@@@@@@@@@@@#Oo@@@@@@@@@@@#@@@@@@@@@@@@@@@#.   ",
"   #ETTTTTTTTITTTTITTTTTTTTITTIEfkEITTUTTTITTTTTTTTITTTTTTTTTEkfETTTTTTTTTITTTUTUTTTTTTITTIE#   ",
"   @THHLHKLKLLHLLKLLKLKLLLLLHLHEphTLLLLKLKLLKLKLLLLLHLKLHLHLHTgdEHHLHKLKHLLLLKLLKLKLLLLLHLHT@   ",
"   @TLLLLLLPLPLLLPLPLLLLLLLLLLLE>gTLLLLLLPLLPPLLLLLLLLLPLLLLLThdEHLPPLLPLLLLLLLPLPLPLLLLLLLT@   ",
"   @THLLPLPLPLLLLLPLPLLLLLLLLLKEdhTLPLLLLLPLLPLLLLLLLLPLLLLLLThdELLLLLPLLLILLLLLLLLLLLLLLLLT@   ",
"   @TKPLLLLLLLLLLPLPLLPLLLLLLLLEdhYLLLPLPLLLLLLLPLPLPLPLLLLLLEhdELLLLLLPLPLLLLLLLPLPLLLLLPLT@   ",
"   @TLLPPLLPPLLPLLPLLPLLLLPLLLHEdhYHLPLPLPLPPLLLLLLLLLLLPLLPKThdEKLLLLLLPLPLLPLLPLPLPLPLPLLI@   ",
"   @TLLLLLPLLLLLLLLLLLLLPLLPPLLTdhYPLLLLLPLLLLLLLLLLLLPLLLPLLEhdELLPPLILLLLLLILLPPLLLLLLLPLI@   ",
"   @TKLLLPLPLLLLLLLLLLLLLLLPLPHEdhYLLPLLLLLLLLLLKLLLLLLLLPLPLThdEKLLLLLLPLLLLLLLLKLLLLPLLLLT@   ",
"   #TLLLLLLLLLILLLPUIILLLPLLLPKEdhTLLLLPLLLLLTTITITILLLPLLLLLEhdELLLLLLLLLPLLIUIIIILLLPLLLLT@   ",
"   @TKLLLPLPLLLLLUn78qJLLLLLPLLEdhTLLLLLLPLLLz;%+@*zILLLPLLLKThdEKPLLPLPLLLLIBy00wjLLLLPLPKT@   ",
"   @TLLPPLPLLLLLID5,<1GLLLLLLPLEdhTLLPLPLLLLLO      gILPLLLLLEhdELLLLPLLPLLIc<,,<,3GILLLLLKT@   ",
"   @TKLLLLLLLLLLIe,5<2JILLLLLLHEdhTLLLPLLLLLL@*kz*  +LLLLLLLLThdTLLLLLLPLLIN1,qBDNsGLLLPLPLT@   ",
"   @TKLLLLLLLPLUb,yy,2GILLPLLLKEdhTLLLPLLLLLLZITILO oCILLLLPKEhdELLLLLLLLKUt,6GLHIYLLLLLLLLI@   ",
"   @TLLPLLLLLLID35Ky,3GLLLLPPLLEdhTLPPLPLLILLILKIHo @LLLLLLLLThdEKLLLPPLLPK9,7w,<0NULPLLLLLT@   ",
"   @TLLLLLLLLLLr,nYt,2GPLPLLLPKEdhELLLLLLLLLLLLPI=  hTLLLPLLPThdELLLLLLPLID6<,<71,1VILLLLLLT@   ",
"   @ILLPLLPLLTb,yIUt,2GPLLPLLLLTdhTKPLLLLPLLLKIL*  fTKLLPLLPLThdEKLLLPPLLIS6,<bYv<,uILLILLLT@   ",
"   @TKLLPLLPKYu,5551,<2iILLLLLLEdhTLLLLLPLLPLIF# .gILPLLLPLLLEhdELLPLLPLLLK9,5DIJ1,eLLLLLPLT@   ",
"   @TLLLLLLLLYp,<<<,<<,yILLLLLHEdhTLLPLLLPLLPC+ XlTPPPLPPLLLKThdEKPLPLLLLLUt,3VRV1,uILLLLLKT@   ",
"   @TLPLLLLLLISMNNBw,5mSLLPLLLHEdhTLLLLLLLLLI@  @=&&*ZILLPLLLEhdELLLLLPLLLIN1,qbq,<NILLLLLLT@   ",
"   @ULLLPLPLLLIUIIYt$3KILPLLPLLEdhTLLPLLPLLLLO      .zTKLLLLLThdTLLLLLLLLLLIc2,$,1jILLPLLLLU@   ",
"   @THLLLLLLLPLKLLPMijKLLLLLPLLEdhTLLLLLLPLLLf:>>>>>dFILPLLLLThdEHLLILLLPLLLUSvsbDILLLPLLLLI@   ",
"   @THLLILLLLPLLLLLIYYLLLLLILLHEdhTLLLLIPLLPLTETEEEETPLLLLLLLThdEHLLLLPLLLLLLPYYYPLLLLLLLLLT@   ",
"   @TLLLPLPLPLLPLLLLLLLLLLLLLLHEdhTLLPLLLPLLLKLLLHLKLLPLLLLLLThdELLLLLPLPLPLLLLLKLLLPLPLLLLI@   ",
"   @TLLPLPLPLPLLLLLLLPLLPPLLLLLEdhTLPLLLLPLLLLLLLLLLLLLLPLPLLThdELLLLPLPLLLLLLLLLLPLLPLLLLLT@   ",
"   @TLLLLLLLLLLLLPLLLPPLLPLLLLHEdhTLLPLLLLLLLPLLLLLLLLLLLLLLLThdELLLLLLLPLLPLLLLLPLLPPLLLLLT@   ",
"   @TLLPPLLLLLLLLLLLLLLLLLLLLPLEdhTLPLPLLLLPLLLLLPLPLLPLLPLPLThdTLLLLLLLLLLLLLLPLLLLLLPLLLHT@   ",
"   @IKLHKLKLLHLHLHLHLKLHKLKLLHHEpfTLKLKLHLHLLHHLLHLKHLLHLHHLHYgaEHHLLLHLLKKLKLHLLLLHKLKLLLHT@   ",
"   #ETEEEEEEEEEEEEEEEEEEEEEEEETEfkETEEETEEEEEEEEEEEEEEEEEEERTYkfETEEETEEEEEEEEEEETEEEEETEETE#   ",
"   ofddddddddddddddddddddddddddf&*fddddddddddddddddddddddddddf*&fddddddddddddddddddddddddddfo   ",
"   Okghghhhhhhhhhhhhhhhhhhhhhhgl*;khhhhhhhhhhhhghhhhhhhhhhhggk;*khhhhhhhhhhhhhhhhhhghhhhhhgkO   ",
"   @ETTTTEETTETTTETETETETTTEETTEfkYYTETRTTTTETTTTTTETETTTTTTTEkfETTTETTTTTTTTETTTTTTTTTETTTE@   ",
"   @TKLLLLKLLLLLLLKLLLKLLLHLLLHTdgYHLHLLLKLLLLLLLLLLKLLLPLLLLTgdTKLLLLLLLLLLKLLLPLLLLLLLLLLI@   ",
"   @TKLPLLLLLLLLLLLLLLLLLLLLPLLEdhTLLLPLLLLLLLLILPPLPLLLLLPLLTgdEKPPLLLLLLPLPLLLLPLLLLLLLLLT#   ",
"   @TLLLPLLPLLLPLLPLLPPLLLLPLPKEdgTLLLLLILLLLLLLLLLLLPPLLLLLLThdELPLLLLLLLLPPLPLPLPLLPPLILLI@   ",
"   @TKLLLLLLLLLPLLLPLLLLLPLPLLLEdhELLPLPLLLLILLLLLLLPLPLLLLLPThdEKLLLLPLLLLLLLPLLLLLLLLLLLKT@   ",
"   @TLLLPLLPLLLLLPLLLPLLPLPLLLHEdhTLLLLLLLILLLLLLLLLLLLLLLPLLThdELLLILLLLILLLLLLLPLLLLPLLLLT@   ",
"   @TLLLLLILLLLLPLLLLLLLPLPLLLKEdhTLLLLLLLLLLLLILLLLLLPLLLPLLThdELLLLPLLLLILLILLLLLLLLLLILLT@   ",
"   @TLLLLLLLLLPKLKLLLKLLLLLPLPLEdhTLLPPLLLLLLILLLLLLPLLLILLPKEhdEKLLPLPLLLLLLLLLLPPLILLLLLKT@   ",
"   @TLLLLLLLLLLTTTTETEILLLLLLPKEdhTLLLLLLLLLLLLILILLLLPLLLLLLEhdELLPLLLLLILLLLILLLLLLLILLPKT@   ",
"   @ULLLLLLLLLIf#%%%%#hTLLPLLLLTdhTLLPLLLLLILLLLLLLLPLLPLLLPLThdEKLLPLPLLLLLILLLLLPLLLLLPPKT#   ",
"   @TLLLPLLPLLI=      :TLLLLLLHEdhTLLLLPLPLLLPLLLLILLLPLLLPLLEhdELPLLLLLLLILLILLLLILLLLLLLLT@   ",
"   @ILPLLLLLLPI- @gff>zILLLLPPHEdhTLLLPLPLLPLLLLLLLLLLLPPLLLKThdEKLLILLLLLLLLLLLLLLLLLLIPLKT@   ",
"   @TKLLPLLLLLI- #d:gLTLLLLLLLLEdhTLLLLPLLPLLLLLLLLLLLLLLLPLLEhdTLLLLLILLLLLLLLLLLILLLLLLLLT@   ",
"   @TLLLLLLLLLI=     oxILLLILLKEdhELLLPLPLLLPLLLLLLILLLLPLLLLThdTKILLLLLLLLIILLLLLLLILLLLLKT@   ",
"   @UKLLLPLLLLI-+>>@  #LLLLLILLEdhTLILLLLILLLLLILLLLLLLLILLLLThdEHPLLLLLLLLLLLLLLLLPLLLLLLLI@   ",
"   @TLPLPLLLLPLGIITHO  xILLLLLHEdhTLLLLLLLLLLLLLILLLLLLLLLLLKThdEKLPPLLPPLLPLLLIPLPLLLLPLLLT@   ",
"   @TKLLLPLPPLPILKLI=  zILLPLLLEdhTKLLILLLLIILLLLLILLILLLLILLThdELLPLLPLLLLLLILLLLLPLLLLLLLT@   ",
"   @TLPLPLLLLIFlPTIH+  CILPLPLKEdhTLLLLLLLLLLLLLILLLLLLILLLLLThdEKPLLPLPLLLPLLLLLLPLLLLPLLLT@   ",
"   @TLLLPLLLLLD.@>d#  #LPLLLLLKEdhTLLILLILLLLLLILLLLLLLLLLLILThdELLLLPLLLLLLLPLLPLPLLPLLLLLT@   ",
"   @TLLLLLLILPFo     +CILPLLLLLEdhTLLLLLLLILLLLLLLLIILLLLLLLLThdEKLLLLLPLLLPLLLLLLLLLLLLLLLT@   ",
"   @TLLLPLLLLLLFg:-;gLILLLLLLLLEdhTLLLLLILLLLLPLLLLLLLLLPLLLLThdELPLLPPLLPLLLLLLLLLLPLPLLLHT@   ",
"   @ILLLLPLLLLLPTTTTTPLLLLLPLLLTdhTLLILLLLLLLLLLILLLLLILLPLLLThdEKLLLLLPLLPPLPLPLLLLLPLPLLHT@   ",
"   @TLLLLPLLLLLLLKLKLLPLLLPLLPHEdhTLLLLPLLLLPLPLLLLLLLPLPLLLLThdELLLLLPLLPLPLLLLLLLILLLLLLLT@   ",
"   @TKPLLLLLLLLLLLLLLLLPPPLPLPHEdhTLLLPLLLLPLPLLLPLPPPLLPLLPKEhdEHLLLPLLLLLLLLLLLILLLLLILLLT@   ",
"   @ILPLLLLLLLLLPLLPLLPLLLLLLPLEdhTLLLLPLLPLPLLLLLLLLLLLLPLLLEhdELPLLLLPLLLPLLPLLLILLLLLLLHT@   ",
"   @TLLPPLLPLLLILLLPPLLPPLPLLLHEdhTLLPLLLLLLLLPLLLLLPLLLLLLLLThdEHLPLPLLLPPLPLLLLLLLLILLLLLT@   ",
"   @TKLLLLLPLLLLLLLLLLLLKLLLHLHEdhYHLLLLLLLLLLLLLLLLLLLLLLLLKThdRHLHLLLPLLLKLLLLLLLLLLLKLLHT@   ",
"   #ETTTTTTTTETTTTTTTTTTTETTETTEfkRYTTTTETTTTTTTTTTTETTTTTTTTEkfYYTETTTTTTETETTTTTTTTTETTETE#   ",
"   Okghhghhhhhghhhhhhhhhhhhhhhgl*-kghhhhhhhhhhhhhhhhhhhhhhhhgk;*kghhghhhhhhhhhhhhhhhhhhhhhgkO   ",
"   ofddddddddddddddddddddddddddf&*fadddddddddddddddddddddddddf*&fadddddddddddddddddddddddd>fo   ",
"   #ETEEEEEEEEEEEEEEEEEEEEEEEETEfkYYRETEEEEEEEEEEETEEEEETEEETEkfYYEEEEEETEEEEEEEEEEEEEEEEETE#   ",
"   @THHLKLLKKLKLHLLHKLHLLHHLHLHEagYHHLLLLHLHKLLKKLLLLHLHLKLKLTfpYHHLHLLHLKLKKLHLLHHLLKKLLKKI@   ",
"   @TLLLLLLLLLLLLLLLLPLLLLLLLLLEdhTKLLPLLLLLLLLLPLLLLLLLLPLLLThdRLLLLLLLLPPLLLLLLLLLLLLLLLLT@   ",
"   @TLLLLLLPPLLPLPLLLLPLLLLPLLHEdhELLLLLLLLLLLLLLLPLLLLLLLPPLThdELLLLLLLLLLLLPLPPLLLLPLPLLLU@   ",
"   @TLLLLPLLLLLLLPLILLLLPLLPLLLEdhTLLLLLILPLLLLPLPLLLLLLLLPLLThdTLLLPLLILPLLLLLLLLLLPLLLLLHT@   ",
"   @ILLLLLLLPPLLLLLLLLLLLLPLPLHEdhELLPLLLLLPPLLPLLLPILLLLLLPLThdEKPLLLLLPLLPLLILLPLLLPLLLLLT@   ",
"   @ILLLLPLPLPLLLLPLLPLLLLLPLLLEdhEKPLLPLPLLLLLPLPPPLPPLLLLLLThdELPLPLLLLLLLLPLLPLILPLLPLLLT@   ",
"   @TLLLLLPLLLLHLHLHLKLLPLLPLLHEdhTLLLPLLLPLLLLKLKKLLLLPILLLLThdEKLPLPLLLLLLLLLKKLLLLPLLLLLT@   ",
"   @UKLLLPLPLLIEEEEETEELLLLPLPKEdhTLLLLPLLLLLPUYTYUILLLLLLLPLTgdEHLLLLLLLILLITEEELLLPLPLLLKT@   ",
"   @TLPLPLPLLPA-==-===-FLLLLLLLEdhTLLLPLLPLLLDbauujSILLLPLLLLThdELLLLLLLLLLKld-=;KLLLLLLLILT@   ",
"   @TKLLLLLLLIk        xTLPLLLKEdhTLLLLLILLLUy$$$,,2mULLLLPLLThdEHLILLLLPLTk    XGILLLLLLLLI@   ",
"   @TLPLLLPLLIZ;----. +FPKLPLLLEdhTLLILLLLLLIiesjq<,9LLLPPLPPThdELLLLPLPLLIl+:@ XHLLLLPLLLLT@   ",
"   @TLLLPLLLLLLTIIEk  >TLLLPLPKEdhTLLPLPLPLPLLIYRL6,9KLLLLLLLThdELLLLPLLLLLLLT* XHLLLPLLPLLT@   ",
"   @TLLLLLLLLLLLLLL% XFILLPLPLLEdhTLLLLLLLLLLLHBBu1,uILLPLLLLThdEHLLPLLLLPLLLI& XHILPLPLLLKI@   ",
"   @TLLLPLLLILLLLIz  -TKLLLLLLHEdhTLLLLLLLPLLIN,$,<yILLLLLPLLThdELLLLPLPLLLLLI& XHLLLPLLLLLT@   ",
"   @ILLLLLLLLLLLKT* .xILLLLLLLLEdhTLLLLPLLLPLIVew6<1sULLLLLLLThdEHLLPLLLLLLLLI& XHPLLLPLPLLT@   ",
"   @TKLLLLPLLLLLICX &TLLLLLLPLKEdhTLLLLPLLPLPLPYID9,5SIPPLPLLThdEKLLPLLPLLLLHI& XFLLLLLPLPLT@   ",
"   @TLLPPLLLLLLLT;  lILLLLLLLLLEdhELLLLLLLLLKLUPIYw<1NUKLPLLLThdELLLLLLLPPLLIT* XLTILLLLPLLI@   ",
"   @TKLLLLLPLLLIFo #LPLLPLLPLLKEdhTKPLLPLLLISqimmy1,5GPLLLLLLThdELLLLLLLLLIFhk@ XhgVILLPLPKT@   ",
"   @TLLLPLPLLLKT>  gTKLLLPLLLLLEdhELLPLLLLLIA3,,$$,<bULLPLLLLThdEKLLLPPLLLIz       :TLLLLLLT@   ",
"   @TLLPLLLLLLLL;@*HLLPLPLPLLPKEdhTLLPLPLPLLLMirwtaSILLLLLPLLYhdEKPLPLPLLLLC%%%%%%@hTLLLLLLT@   ",
"   @TKLLLLLLPLPLTTTLLLLLLLLLPLLEdhTPPLPLLLLLLIUTYYUILPLLLLLLPYhdELLLLLLPLPPLTTTTETEILLLLPLKI@   ",
"   @TLLLLILLPLLLLLHLLLLPPLLLLLLTdhTLLLPLLLLLLLLLKLLLLLLLPLPLHYhdEHLILLLLPLPLLLKLHLHLLLLPLLLT@   ",
"   @TLLLLLLLLPLLLLLLPLPLLPLLLLLEdgTLLLLLLPLLLLLLLLLLLLPPLPLLLYhdELLLLLLLLLLLLLLLPLLLLLLLLLLT@   ",
"   @TLLLLLLPLLLLPLLLLLLLPLLLLLKEdhYLLLLLPLLLLLLLLPLLLLLLLLLLLThdELLLLPLPLLLLLLLLLLLLLLLLPLHT@   ",
"   @TLLLLLLLPLLLLLLLLLLLLLLLPPLEdhYLLPLLLLLLLLLLPLPLLPLPLLLLLTg>EHLLPLLLLLLLLPLLPLLLPPLLLLLT@   ",
"   @THLHHLKLLHLLLLLHLLLLLLKLLKHTpfTLHHLHLLLHLLLLLLLLLKKLLLLLLThpTHLLLKLKLLLLLKLLLLKLLLLHLLHT@   ",
"   #EITTTTTTTTTIITTTITTTTITTTTTEfkEIYYYTITTTITTTTIITTTTTITTTIEkfETTITTTTITTTTTTUITTTTITTTTIE#   ",
"   .#@@@#@@@@@@@@@@@@@@@@@@@@@@#OO#@@@@@@@@@@@@@@@@@@@@@@@@@@@Oo#@@@@@@@@@@@@@@@@@@@@@@@@@@#.   ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 77 1 ",
"  c #000000",
". c #0F0F0F",
"X c #141414",
"o c #1B1B1B",
"O c #242424",
"+ c #2C2C2C",
"@ c #343434",
"# c #3B3B3B",
"$ c #007E00",
"% c #424242",
"& c #4C4C4C",
"* c #545454",
"= c #5D5D5D",
"- c #666666",
"; c #6A6A6A",
": c #747474",
"> c #7C7C7C",
", c #008400",
"< c #028902",
"1 c #0A8B0A",
"2 c #0F900F",
"3 c #158F15",
"4 c #1C8E1C",
"5 c #139113",
"6 c #1B951B",
"7 c #229522",
"8 c #249824",
"9 c #2B9B2B",
"0 c #369F36",
"q c #389F38",
"w c #36A036",
"e c #3DA23D",
"r c #43A343",
"t c #48A648",
"y c #53AB53",
"u c #59AE59",
"i c #63AF63",
"p c #63B263",
"a c #6BB46B",
"s c #71B671",
"d c #76B976",
"f c #7BBB7B",
"g c #858585",
"h c gray55",
"j c #939393",
"k c #9C9C9C",
"l c #83BE83",
"z c #A5A5A5",
"x c #ACACAC",
"c c #B5B5B5",
"v c #BCBCBC",
"b c #8DC28D",
"n c #92C492",
"m c #99C799",
"M c #9DC99D",
"N c #A3CBA3",
"B c #ABCEAB",
"V c #B6D2B6",
"C c #BCD5BC",
"Z c #C5C5C5",
"A c #CDCDCD",
"S c #C1D7C1",
"D c #C5D8C5",
"F c #CCDBCC",
"G c #D6D6D6",
"H c #D2DED2",
"J c #DDDDDD",
"K c #D6E0D6",
"L c #DCE2DC",
"P c #E5E5E5",
"I c #E9E7E9",
"U c #EAE9EA",
"Y c #F3EBF3",
"T c #F9EEF9",
"R c #F1F1F1",
"E c #FFF2FF",
"W c #FAFAFA",
/* pixels */
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"    .........................X .......................... X.........................    ",
"   .GPJJJJJJJJJJLJJJJJJJJJJJPA-PJJJJJJJJLJJLJJJJJJJJLJJJU-APJJJJLJJLJLJLJJJJLJJJJJJG.   ",
"   .JPPUUUUUUUPUIIUIIUUUUUUPUG;RPUUUUUPUIIIIIIUUUUIIPUPPR-GUUPUUIIIIIIIIUUIIPUUUUPUP.   ",
"   .JPPPPPPPPPPPPPPPPPPPPPPPUG-RPPPPPPPPPPPPPPPPPPPPPPPPR-GUPPPPPPPPPPPPPPPPPPPPPPPJ.   ",
"   .JUPPPPPPPPPPPPPPPPPPPPPPUG-RLPPPPPPPPPPIPPPPPPPPPPPPR-GUPPPPIPPPPPPPPPPPPPPPPPUJ.   ",
"   .LIPPPPIPPPIPPPPPIPIPPIPPUG-RPPIPPPPPPIPPPPPPPPPPPPPPR-GUPPIPIPIPPIPPIPPPPIPPPPPJ.   ",
"   .JIPPPPPIPPPPPPPPPPPPPPPPUG-RJPPPPPPPIPPIPPPPPIPPPPPLR-GUPPPIPIPPPPIIPPPPPPPPPPUJ.   ",
"   .JIPPPIPPPPPPIPLPPIPPPPIPUG-RPPPPPPPPPPPLJPPPPPIPPPPPR-GUPIIPPPPPPPPPPLPPPPPPPPUJ.   ",
"   .LIPPPPPIIPPPPUTTUPPPPIIPUG-RPPPIPPPPPIRRWWRPPPPPPPPPR-GUPPPPPPPPPPPUTTYUPPIPPPIJ.   ",
"   .JIPPPPIPPPPPYBaaBUPPPPIPUG-RPPPPPIPPILcg:>zUUPPPPPPPR-GUPPPPPPPPPIPNdfnFIPPPPPIJ.   ",
"   .LIPPPPPPPPPUF3$$dRLPPPPPUG-RPPPPPPPPR;     &PPPPPPPPR-GUPPPPPPPPIF0,$,$yUPPPPPUJ.   ",
"   .LIPPIPPPPPPUt,5,dYPPPPPPUG-RJPPPPPPPW=Ohk#  jRPPPPPPR-GUPPPPPPPPPr,8MCllIPPPPPIJ.   ",
"   .LUPPPPPPPPYb,d9$dTLPPPPPUG-RPPPPIPPPIAPRWZ  ;UPPPPPPR-HUPPPIPPPYB,<VPGYYPPPPPPIL.   ",
"   .JUPPPIPPPUF10J8$dYPPPIPPUH-RPIPIPPPPPUPJRc  kRPPPIPPU;GUPIPIPPLYd,50,,wCYPPPPPUJ.   ",
"   .JUPPPPPPPIt1HY7,fEPPPPPPUG-RLPIPPPPPPPPRG+ &PPPPPPPPR-GUPPIPPPPUp,<3y6,8LIPPPPPJ.   ",
"   .JIPPPPPPYN,uCN6,uSLPPPPPUG-RPPPPPPPPPPRvo %JPPPPPPPLR-GUPPPPPPPYa1,mEM1,BUPPPPUJ.   ",
"   .JIPPPPPPYn,,$$,<,4HIPPPPUG-RPPIPPPPPPUzX -RRUPPPPPPPR-GUPPPIPPPYl,<CTC,<NUPPPPUJ.   ",
"   .LPPPPUPPUVryyy1,8sLIPPPPUG-RPPPPPPPPUz  #xxzZPPPPPPPR-GUPPPPPIPUD3,sUs,1FUPPPPUJ.   ",
"   .JUPPPPPPPUUIUP7$fTPPPPPPUG-RLPPPPPPPR=      *YLPIPPPR-GUPPIPPPPPYl<,<,,lYIPPPPUJ.   ",
"   .JUPPPPPPPPPPIJu0nIPPPPIPUG-RPPPIPPPPRg#%%%%#gUPPPPILR-GUPIPPPPPPPUBueuBUPPPPPPUJ.   ",
"   .JUPPIPPPPPPPPPYTUPPPIPIPUG-RPPPPPPPPPRRWWRRRRPPIIPPPR-HUPPPPPPPPPPYRYTUPPPPPPPUJ.   ",
"   .JUPPPIPIPIPPIPPPPIPPPPPPUG-RPPPPPPPPPPPLPJPPPPPPPPPLR-GUIPPPIPPPPPPLPLPPPPPPPPIJ.   ",
"   .JIPPPPPPPIIPPPPPPPPPPIPPUG-RPPPPPPPPPPPPPPPIPIPPPPPPR-GUPPPIPIIPPPPPIPPPIPIIPPUJ.   ",
"   .JUPPPPIPPPPPPPPPPPIIPPPPUG-RJPPPPPIPPPPPPPPPPPPPPPPPR-GIPPPPPPPIPPPPPPPPPPPPPPPJ.   ",
"   .JPPPPPPPPPPPPPPPPPPPPPPPUG-RPPPPPPPPPPPPPPPPPPPPPPPPR-GIPPPPPPPPPPPPPPPPPPPPPPUJ.   ",
"   .PUUUIUUUUUUUPUUUUUUUUUUUUJ;RPUUUUUUUUUUUUUUUUUUUUUUPR-JUIUUUUUUUUUUUUUUUUUUUUUUP.   ",
"   XAGGGGHGGGGGGGGGGGGGGGHGGJZ=PGGGGGGGGGGJGJGGGGGGGGGGGP=ZJHGGGGGGGGGGGHGGGGGGGGGGA.   ",
"    -----------------------;-=+;-------;----------------;+=-------------------------    ",
"   .URRRRRRRRRRRRRRRRRRRRRRURP;WURRRRRRRRRRRURRRRRRRRRRRW;PRRRRRRRRRRRRRRRRRRRRRRRRUX   ",
"   .JPPPPPPPLPPPJPPPPPPPPPPPPG;UPPPPPPJPPLPPLPPLPLPPPLPLU-GPPPPPPLPPLPLPPPLPPLPPLPPJ.   ",
"   .JPPPPPPPPPPPPPPPPPPPPPPPUG-RPPPPPPPPPPIPPIPIPIPPPPPPR-GUPPPPPPIPPIIPPPPPPPIPPPIJ.   ",
"   .JPPPPPPIPPPPPPPPPPIPPPPPUG-RJPPPPPPPPPPPPPPPPIPPPIIPR-GUPPPPPPPPPIPPPPPPPPPPPPIJ.   ",
"   .JIPPPPPPPPPPPPPPPPPPPPPPUG-RPPPPPPPPPPUPPIPPPPPPPPPLR-GUPPPPPUPPPPPPIIPIUPPPPPIL.   ",
"   .JIPPPPPPPIPPPPPPPPPPPPPPUG-RPPPPPPPUPPUPPPUPIPPIPPPPR-GUPPPPPPPPPPPPPPPPPIUPPPUJ.   ",
"   .JUPPPPPPPPPPPPPPPPPPPPPPUG-RPPPPPPPPPPPPPPPPIPPPPPIPR;GUPPPPPPUPPUPPPPPPPPPPPPPJ.   ",
"   .JUPPIPPPPPURRRURRPPPPPPPUG-RPPPUPPPPPPPPPUPPPPPPPPPLR-GUPPPPUPPPPPPPPPPIPUPPPPUJ.   ",
"   .JUPPPPPPPUAzxxcxcPPPPPPPUG-RPPPPPUPPPUPPPPPPPPIPIPPPR-GUPPPPPPPPUPPUIPPPPPPPPPUJ.   ",
"   .JUPPPPPPPR:     oJPPPPPPUH-RPPPPIPPPIPPPPPPUUPPPPPPPR-GUPPPIPUPPPPPPPPPPPPUPPPUJ.   ",
"   .JUPPIPPPLR: +-=&-PPPIPPPUG-RJPPPPPPPPPPUPUPPPPPPPPPJR-GUPPPPPPPPPUPPUPPUPPPPPPUJ.   ",
"   .JIPPPPPPPR: *kjARPPPPIPPUG-RPPPPPPPPPUPPPPPUPPPUPPPPR-GUPPIPPPPPPPPPPPPPPUPPPPUJ.   ",
"   .JIPPPPPPPR:     >UPPPPPPUG-RPUPPPIPPPPPPPPPPPPPPPPPPR-GUPPPIPUPPPPUPPPPPPPPPPPIJ.   ",
"   .LPPPPPPPPUg#g>O  xRPPPPPUG-RPPPPPPPIPPPPPPPPIIPIPPPPR-GUPPPIPPPPPPPPPPPPPPPUPPIJ.   ",
"   .JUPPPIPIIPJURWc  ;WJPPIPUG-RPPPPPPPIPPPUUPPPPPIPPPPPR-GUPPPPPPUPPUPPPUPPPUPPPPUJ.   ",
"   .JUPPPPPIPPRRPUGo -WJPPPPUG-RJPPPIIPPPPPPPPPPPPPPPPPPR-GUPPPPUPPPPPPPPPPUPPIPPPIJ.   ",
"   .JUPPPIPPIJ;xJP:  gRPPPPPUJ-RPPPPPPPIUPPPPPPUPIPPPPPPR-HUPPIPPPPPUPUPPPPPPPPPPPIL.   ",
"   .JIPIPPIPPLO oo  +JPPPPPPUG-RPPPIPIPPPPPIPIPPPPPPPPPPU;GUPPPUPPIPPPUPPPPUPPIPPPUJ.   ",
"   .JIPPPPPPPPj%X.+-GUPPPPPPUG-RLPPPPPPPUPPPPPPPPIPPPPPPR-GUPPPPPPPPPIPPPPPPPPPPPPPJ.   ",
"   .JIPPIPPPPPRUPLPUPPPPPPPPUG-RPIPPPPPIPPPPPPPIIPIPPPPPR-GUPPPPPIIPPPIPPUPPIPPPPPUJ.   ",
"   .JPPPPPPPPPPIIIIPPPPPPPPPUG-RPPPPIPPIPPPPIPPPPPPPPPPPR-GUPUPPPIPPPPPPPPPPPPPIPPUJ.   ",
"   .JUPPPPPPPPPPPPPPPPIPPPPPPG-RLPPPPPPPPPPPPPPIPPPPPPPLR-GUPPPPPPIIPIPPPPPPPPPPPPUJ.   ",
"   .JIPPIPPPPPPPPPPPIPPPIPPPUG-RPIIPPPIPPUPPPPIPPPIPIPPPR-GUPPPPPPPPPPPIPPPIPIPIPPUJ.   ",
"   .JPPPPIPPPPPIPPPPPPPPPPPPUG-RPPPPPPIIPPPUPPIIUIPIPIPPR-GPPPPPPPPPPPPPUIPIPIPIPPUJ.   ",
"   .JPPPPPPLPPPLLPPPLPPPPPPPPG-ULPLPPPLLPPPLPPLPLPPLPLPLU-GPPPPPLPPPLPPPLPPLPLPLLPPJ.   ",
"   XURRURURRRRRRRRRRRRRRRRRRRP;WURRRRRRRRRRRRRRRRRRRRRRUW;JRRRRRRRRRRRRRRRRRRRRRYRRI.   ",
"    -;-----------------------=+;------------------------;+=-------------------------    ",
"   .AGHGGGGGJGGGGGGHGGGGGGGGJZ=PGGGGGGGGGGGHGGGGGGGGGGGGP-ZJGJGGGGGHGGGGGGGGGGGGGGGA.   ",
"   .PUUIUUUUUUUUUUUUUUUUUUUUUJ;RPUUUUUUUUUUUUUUUUUUUUUUPR;JUPUUUUUUUUUUUUUUUUUUUUIUPX   ",
"   .JIPPPPPPPPPPPPPPPPPPPPPPUH-RPPPPIPPPPPPPPPPPPPPPPPPPR-GUPPPPPPPPPPPPIPPPPPPPPPUJ.   ",
"   .LIPPPPPPPIPPPIPPPPPPIPPPUG-YLPPPIPPPPPPPPPPPPIPPPPPPR-GUPPPPPPPPPPPPPIPPPIPPPPIJ.   ",
"   .JIPPPPIPPPPPPPIPIPPPPPPPUG-RPPIPPPPIIPPPPPPIPIPPPPPPR-GUPPPPPUPPPPPIPIPPIPPPPPIJ.   ",
"   .LUPPIPPPPIPPPPPPPPPIPPPPIG-RPPPPPIPPPPPIPPPPPPPIPPPPR-GUPPPPPPPUPPPPPPPPPPPPPPUL.   ",
"   .JUPPIPPPPPPPPPPPPPPPPPPPUJ-UPPPPPPPPPPPPPPPPPPPPPPPPR-GUIPPPPPPPPPPPPPPPPPIPIPIL.   ",
"   .JUPPPPIPPPIIIIUUUPPPPPPPUG;RPPPPPPPPIPPPIUPPPPPPPIPPR-GUPIIPIPPPPPPUUPPPPPPPPPIJ.   ",
"   .JIPPPPPPIPJJJJHJJJPPPPPPUG-RPPPIPIPPPUILLLPYPPPPPPPPR-GUPPPPPPPPIUPHJJPPPPPPIPIJ.   ",
"   .JIPPPPPPUAX    . >RPPPPPUG-RLPIPIPPPUVw5<50mIPPPPPPPR-GUPPPPPPPUP:O. +UPPPPPPPIJ.   ",
"   .LPPPPPPPPA+XooX  gRPPIPPUG-RLPPPPIPPYb,881,<BUPPPPPPR-GUPIPPIPPIGo.o +UPPPPPPPIJ.   ",
"   .JUPPPIIPPPGGGL; XGUPIPPPUG-RPIPIPPPPUFDPYN<,lUPPPPPPR-GUPPPIPPPPPvJ- +UPPPUPPPIL.   ",
"   .JUPPPPPPPPIUUJO -RPPPPPPUG-RLIPPIPIPPUUJHf<<BYPPPPPPR-HUPPPPPPPPPUR- +UPPPPPPPIJ.   ",
"   .JUPPPPPPPPPLRh .vUPPPIIPUG-RPPPIPPPPPIS1,,<bYPPPPPPJR-GUPPPPPPPPPPR- +UPPPPPPPIL.   ",
"   .JUPPPPPPPPPPP# &RLPPPPPPUG-RJPPPPPPPPIFyr5<9DIPPPIPPR-GUPPPPIPPPPPU- +UPPPPPPPUJ.   ",
"   .JUPPPPIPPPPRz  zRPPPPPPPUG-RPPPPPPPPPUIYYD5$iYPPPPPPR-GUPPPIPPPIPPR- +PPPPPPPPPJ.   ",
"   .JUPPIPPPPPPU& #IPPPPIPPPUG-RPPPPIPPPPFPIUH6,tUPPPPPJR-GUPPPIPPPPPUW; +RUPPPPPPUJ.   ",
"   .JUPPPIPIPPYv  jRPPPPPPPPUG-RPPPPPPPPP07uu6,,bYLPPPPPR-GUPPPPIPPPP:=+ X==GUPPPPUJ.   ",
"   .JUPPPPPPPPY* +JPPPPPIPPPUG-RPPPPPPPPPp<,,,6fIPPPPPPPR-GUPIPPPPPPP+      ZUPPPPUJ.   ",
"   .JUPPPPPPPPIVcAIPPPPIPPPPUH-RPPPPPPPPPPFSCSLYPPPIPPPPR-GUPPPPPPPPJCccccvcPUPPPPUJ.   ",
"   .JPPPIPPPPPPURUPPPPPPPIIPUG-RPPPPPIPPPPUYUUPPPPPPIPPPR-GUPPPIPPPPIYRRRURRPPPPPPUJ.   ",
"   .JUPPPPPIPPPPPPPPPPIPPPIPUG-RPPIPPPPPPPPPPPPPPPPPPPPPR-GUPPIPUPPPPJPPPPPPPPPPPPUJ.   ",
"   .JUPPPPPPPPPPIPPPPPPPPPPPUG-RPPPPPPPIPPPPPPPPPPPPPPPPR-GUPPPPPPPPPPPPPPPPPPPPPPPJ.   ",
"   .JPPPPPPPPPPPPPPPPPPPPPPPIG-RPPPPPPPPPPPPPPPPPPPPPPPPR-GUPPPPPPPPPPPPPPPPPPPPPPPJ.   ",
"   .JUPUUUUPIIUUIIIIUPUUUUUIUG-RPPIUPIIIIPIIUIUUUPUUPPPPR;GUPUUUUUUPIIUUUUUPIIUUUPUP.   ",
"   .GPJJJJJLJJJJLJJLJJJJJJJJPA-UJJJJJJJJJLJLJJJJJJJJJJJJP-APJJJJJJJLJJJJJJJLJJJJJJJG.   ",
"    .......................... X................X........ X.........................    ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 225 2 ",
"   c black",
".  c #010101",
"X  c #111111",
"o  c gray7",
"O  c #101010",
"+  c gray5",
"@  c gray81",
"#  c #DDDDDD",
"$  c gray85",
"%  c #DADADA",
"&  c gray88",
"*  c gray77",
"=  c #A7A7A7",
"-  c gray89",
";  c #D8D8D8",
":  c #ECECEC",
">  c gray91",
",  c #E9E9E9",
"<  c #EEEEEE",
"1  c gray82",
"2  c #B2B2B2",
"3  c gray95",
"4  c #E7E7E7",
"5  c #E4E4E4",
"6  c gray90",
"7  c #E3E4E3",
"8  c #E2E4E2",
"9  c #EAEAEA",
"0  c #CDCDCD",
"q  c #AFAFAF",
"w  c #E2E2E2",
"e  c #E2E3E2",
"r  c #E6E6E6",
"t  c #E4E5E4",
"y  c #EEE9EE",
"u  c #F1EAF1",
"i  c #E8E6E8",
"p  c gray92",
"a  c #CECECE",
"s  c #EFEFEF",
"d  c gray96",
"f  c gray94",
"g  c #F3F3F3",
"h  c #E7E6E7",
"j  c #F4EBF4",
"k  c #EFE9EF",
"l  c #F0EAF0",
"z  c #F5ECF5",
"x  c #97C697",
"c  c #249824",
"v  c #BCD5BC",
"b  c gray93",
"n  c gray75",
"m  c gray25",
"M  c gray18",
"N  c gray46",
"B  c #6BB46B",
"V  c #369F36",
"C  c #69B469",
"Z  c #E8E9E8",
"A  c #E3E5E3",
"S  c #C7D9C7",
"D  c #269826",
"F  c #028602",
"G  c #A7CBA7",
"H  c #F2EBF2",
"J  c #B7B7B7",
"K  c gray55",
"L  c #989898",
"P  c #AEAEAE",
"I  c #F1F1F1",
"U  c #E1E1E1",
"Y  c #F6ECF6",
"T  c #6DB46D",
"R  c #1E941E",
"E  c #99C799",
"W  c #AFCFAF",
"Q  c #E9E7E9",
"!  c #50AA50",
"~  c #AACEAA",
"^  c #1F961F",
"/  c #AFD0AF",
"(  c white",
")  c #9F9F9F",
"_  c #EDE9ED",
"`  c #359D35",
"'  c #1A941A",
"]  c #319D31",
"[  c #54AB54",
"{  c #B6D2B6",
"}  c #108B10",
"|  c #4CA94C",
" . c #018A01",
".. c #45A545",
"X. c #E6E5E6",
"o. c gray57",
"O. c gray12",
"+. c #C8C8C8",
"@. c #2F9B2F",
"#. c #52AA52",
"$. c #DCE2DC",
"%. c #008200",
"&. c #C0D5C0",
"*. c #EDE8ED",
"=. c #E7E8E7",
"-. c #D6DFD6",
";. c #96C696",
":. c #82BD82",
">. c #048604",
",. c #AAAAAA",
"<. c gray19",
"1. c #4B4B4B",
"2. c #B1B1B1",
"3. c #F3EBF3",
"4. c #8CC28C",
"5. c #1B941B",
"6. c #47A647",
"7. c #2A9A2A",
"8. c #DEE3DE",
"9. c #E7E5E7",
"0. c #9BC89B",
"q. c #DAE1DA",
"w. c #ECE8EC",
"e. c gray79",
"r. c #929292",
"t. c gray56",
"y. c gray50",
"u. c #ADCFAD",
"i. c #87C087",
"p. c #D7E0D7",
"a. c #EBE8EB",
"s. c #E1E3E1",
"d. c #F3EAF3",
"f. c #F8F8F8",
"g. c #F0E9F0",
"h. c #F7ECF7",
"j. c #E8EAE8",
"k. c #EAEBEA",
"l. c LightGray",
"z. c #B4B4B4",
"x. c #E9EAE9",
"c. c #B9B9B9",
"v. c #9D9D9D",
"b. c #D7D7D7",
"n. c gray80",
"m. c #868686",
"M. c #B6B6B6",
"N. c #F9F9F9",
"B. c gray70",
"V. c #3A3A3A",
"C. c #1E1E1E",
"Z. c #313131",
"A. c #373737",
"S. c #202020",
"D. c gray33",
"F. c #CBCBCB",
"G. c #ACACAC",
"H. c #282828",
"J. c gray26",
"K. c gainsboro",
"L. c #2F2F2F",
"P. c #DFDFDF",
"I. c gray13",
"U. c gray83",
"Y. c #FBFBFB",
"T. c #F9EDF9",
"R. c #FAEEFA",
"E. c gray98",
"W. c #6C6C6C",
"Q. c #626262",
"!. c #6A6A6A",
"~. c #74B874",
"^. c #61B161",
"/. c #A6CCA6",
"(. c #C0C0C0",
"). c #808080",
"_. c gray42",
"`. c #0C0C0C",
"'. c #505050",
"]. c #F4F4F4",
"[. c #C2D7C2",
"{. c #6AB36A",
"}. c #008300",
"|. c #B7D3B7",
" X c gray67",
".X c gray22",
"XX c #181818",
"oX c #FEFEFE",
"OX c #B4D1B4",
"+X c #42A442",
"@X c #289A28",
"#X c #D9E1D9",
"$X c gray97",
"%X c #646464",
"&X c #353535",
"*X c #F2EAF2",
"=X c #C6D9C6",
"-X c #71B771",
";X c #BAD4BA",
":X c gray66",
">X c gray8",
",X c #D2D2D2",
"<X c gray4",
"1X c #A0A0A0",
"2X c #87BF87",
"3X c #8DC28D",
"4X c #A1CAA1",
"5X c #E1E2E1",
"6X c #CACACA",
"7X c #5A5A5A",
"8X c #090909",
"9X c #8D8D8D",
"0X c gray38",
"qX c #BBD5BB",
"wX c #51AA51",
"eX c #49A749",
"rX c #94C594",
"tX c #A5A5A5",
"yX c #464646",
"uX c #585858",
"iX c #515151",
"pX c #D5D5D5",
"aX c #F8ECF8",
"sX c #E5E7E5",
"dX c #E6E7E6",
/* pixels */
"                                                                                                ",
"        . . . . . . . . . . . .     . . . . . . . . . . . .     . . . . . . . . . . . .         ",
"                                                                                                ",
"      . X o o o o o o o o o o o O + o X o o o o o o o o X o + O o o o o o o o o o o o X .       ",
"  .   X @ # $ % % % % % % % $ & * = - ; % % % % % % % % ; - = * & $ % % % % % % % $ # @ X   .   ",
"  .   o # : > , , , , , , , > < 1 2 3 4 , , , , , , , , 4 3 2 1 < > , , , , , , , > : # o   .   ",
"  .   o $ > 5 6 6 6 7 8 5 6 5 9 0 q < - 6 6 - w - w 5 6 - < q 0 9 5 6 6 5 e 7 7 6 5 > $ o   .   ",
"  .   o % , 6 6 r t y u i 6 6 p a q s - r 5 : d f g 4 6 5 s q a p 6 r 6 h j k l r 6 , % o   .   ",
"  .   o % , 6 r 8 z x c v y 7 p a q s - 5 b n m M N r r - s q a p 6 6 h 7 B V C h t Z % o   .   ",
"  .   o % , 6 A k S D F G H 8 p a q s - 5 < J K L   P I U s q a p 6 8 Y T R E W r t , % o   .   ",
"  .   o % , t 6 Q ! ~ ^ / z 8 p a q s - r 5 , ( ) O 0 p w s q a p t t _ ` ' ] [ 6 6 > % o   .   ",
"  .   o % , 8 l { } |  ...8 X.p a q s - 6 5 s o.O.+.d w 5 s q a p 6 t H @.#.$.%.&.*.=.% o   .   ",
"  .   o % , 5 Q -.;.:.>.T Q t p a q s - - I ,.  <.1.2.s U s q a p 6 7 3.4.5.6.7.8.9.> % o   .   ",
"  .   o % , 6 6 i Y H 0.q.w.7 p a q s - 5 p e.r.t.y.+.p w s q a p 6 6 6 _ u.i.p.a.7 , % o   .   ",
"  .   o $ > 5 6 t s.8 d.h 5 5 p 0 q < - 6 5 9 d d f.p 5 - < q 0 p 5 6 6 7 g.h.i 5 5 > $ o   .   ",
"  .   o & < 9 p p p p j.k.p 9 I l.z.d , p p 9 > > > 9 p , d z.l.I p p p p x.j.k.p 9 < & o   .   ",
"      O * 1 0 a a a a a a a 0 l.c.v.b.n.a a a a a a a a n.b.v.c.l.0 a a a a a a a 0 1 * O       ",
"      + = 2 q q q q q q q q q z.v.m.M.P q q q q q q q q P M.m.v.z.q q q q q q q q q 2 = +       ",
"  .   o - 3 < s s s s s s s < d b.M.N.b s s s s s s s s b N.M.b.d < s s s s s s s < 3 - o   .   ",
"  .   X ; 4 - - 5 w w U - 5 - , n.P b U - - - - - - - - U b P n., - - - - - - - - - 4 ; X   .   ",
"  .   o % , 6 r 6 : f I 9 6 6 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 r n.c.B.1 , 5 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 5 b V.C.Z.L 3 w p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 5 : A.S.D.F.p - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 4 q G.H.J.g w p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 > K.c.3 1.L.3 - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 4 P.J.I.S.q < - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 > , U.r < 5 6 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   X ; 4 - 5 - - > 5 U 5 - , n.P b U - - - - - - - - U b P n., - - - - - - - - - 4 ; X   .   ",
"  .   o - 3 < s s s < < s s < d b.M.N.b s s s s s s s s b N.M.b.d < s s s s s s s < 3 - o   .   ",
"      + = 2 q q q q q q q q q z.v.m.M.P q q q q q q q q P M.m.v.z.q q q q q q q q q 2 = +       ",
"      O * 1 0 a a a a a a a 0 l.c.v.b.n.a a a a a a a a n.b.v.c.l.0 a a a a a a a 0 1 * O       ",
"  .   o & < 9 p p p p p p p p I l.z.d , p p p p p p p p , d z.l.I p p p p p p p p 9 < & o   .   ",
"  .   o $ > 5 6 5 U U U w 6 5 p 0 q < - 6 6 t s.s.8 6 6 - < q 0 p 5 6 6 - U U 6 6 5 > $ o   .   ",
"  .   o % , 6 6 4 N.Y.f.g 6 6 p a q s - r 6 Q T.R.u 6 r - s q a p 6 r 5 b E.d r 6 6 , % o   .   ",
"  .   o % , 5 > % W.Q.!.o.9 5 p a q s - 6 Q -.~.^./.Q 6 - s q a p 6 5 : (.W.).- r 5 , % o   .   ",
"  .   o % , 5 > % _.!.`.'.].w p a q s - t *.[.~.{.}.|.k s.s q a p 6 - <  X.XXX& 4 5 , % o   .   ",
"  .   o % , 6 6 r oXK.O c.f - p a q s - r 7 k OX+X@X#XQ e s q a p 6 r U Y.,.X P.4 5 , % o   .   ",
"  .   o % , 6 r U $X%X&Xg - 6 p a q s - r 7 *X=X-X' ;Xy s.s q a p 6 r w E.:X>X3 , 5 , % o   .   ",
"  .   o % , 6 5 9 ,X<X1Xg - 6 p a q s - t k ~ 2X3X}.4X3.5Xs q a p 6 5 9 6X7X8X9X# r > % o   .   ",
"  .   o % , 6 5 s 2.0X6 r 6 6 p a q s - t *.qXwXeXrXQ 6 - s q a p 6 - f tXyXuXiXpX, > % o   .   ",
"  .   o $ > 5 6 5 9 d 6 5 6 5 9 0 q < - 6 7 w.T.aX*X6 6 - < q 0 9 5 6 - b f.d $X4 - > $ o   .   ",
"  .   o # : > , , > 6 > , , > < 1 2 3 4 , , =.sXsXdXZ , 4 3 2 1 < > , , 4 6 6 6 > > : # o   .   ",
"  .   X @ # $ % % % % % % % $ & * = - ; % % % % % % % % ; - = * & $ % % % % % % % $ # @ X   .   ",
"      . X o o o o o o o o o o o O + o X o o o o o o o o X o + O o o o o o o o o o o o X .       ",
"                                                                                                ",
"        . . . . . . . . . . . .     . . . . . . . . . . . .     . . . . . . . . . . . .         ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 228 2 ",
"   c black",
".  c #020202",
"X  c #010101",
"o  c #070707",
"O  c #2A2A2A",
"+  c gray16",
"@  c gray17",
"#  c #202020",
"$  c #272727",
"%  c #232323",
"&  c gray14",
"*  c gray93",
"=  c #E9E9E9",
"-  c gray91",
";  c #F1F1F1",
":  c gray70",
">  c #DADADA",
",  c #C6C6C6",
"<  c gray77",
"1  c gray95",
"2  c gray94",
"3  c gray80",
"4  c gray1",
"5  c #E4E4E4",
"6  c gray90",
"7  c #E4E5E4",
"8  c #E1E4E1",
"9  c gray89",
"0  c gray69",
"q  c gray84",
"w  c #E2E2E2",
"e  c gray76",
"r  c #C0C0C0",
"t  c #E2E4E2",
"y  c #ECECEC",
"u  c #C8C8C8",
"i  c #E7E6E7",
"p  c #F5ECF5",
"a  c #E9E7E9",
"s  c #D7D7D7",
"d  c gray96",
"f  c #F6F6F6",
"g  c #E6E5E6",
"h  c #F5EBF5",
"j  c #F6ECF6",
"k  c #E8E7E8",
"l  c #DFE3DF",
"z  c #95C595",
"x  c #D0DDD0",
"c  c #EAE7EA",
"v  c gray86",
"b  c #989898",
"n  c gray57",
"m  c #EAEAEA",
"M  c #C3C3C3",
"N  c #C1C1C1",
"B  c #EEEEEE",
"V  c #98C698",
"C  c #92C492",
"Z  c #DDE2DD",
"A  c #E3E4E3",
"S  c #65B265",
"D  c #007D00",
"F  c #A2C9A2",
"G  c #F3EBF3",
"H  c #E1E3E1",
"J  c #ACACAC",
"K  c #4E4E4E",
"L  c gray21",
"P  c gray20",
"I  c #EDE9ED",
"U  c #4FA94F",
"Y  c #42A442",
"T  c #76B976",
"R  c #CEDCCE",
"E  c #E9E6E9",
"W  c #EBECEB",
"Q  c #F2EBF2",
"!  c #9FC99F",
"~  c #73B773",
"^  c #36A036",
"/  c #A3CBA3",
"(  c #F7ECF7",
")  c #E0E2E0",
"_  c white",
"`  c #898989",
"'  c gray92",
"]  c #E2E3E2",
"[  c #ECE8EC",
"{  c #C7D9C7",
"}  c #0B8C0B",
"|  c #44A544",
" . c #63B163",
".. c #D8E0D8",
"X. c #E7E5E7",
"o. c #389C38",
"O. c #51A951",
"+. c #159315",
"@. c #52AA52",
"#. c #E8E6E8",
"$. c gray58",
"%. c #323232",
"&. c gray85",
"*. c #C6D8C6",
"=. c #018801",
"-. c #B5D3B5",
";. c #329832",
":. c #7EB97E",
">. c #E9EBE9",
",. c #84BF84",
"<. c #118D11",
"1. c #62B062",
"2. c #EBE8EB",
"3. c gray68",
"4. c #393939",
"5. c #6A6A6A",
"6. c gainsboro",
"7. c #E6E6E6",
"8. c #4BA84B",
"9. c #279927",
"0. c #AECFAE",
"q. c #EEE8EE",
"w. c #EAECEA",
"e. c #F1EAF1",
"r. c #FAEEFA",
"t. c #B2D1B2",
"y. c #DAE1DA",
"u. c #CECECE",
"i. c #A2A2A2",
"p. c gray60",
"a. c #9B9B9B",
"s. c #E0E3E0",
"d. c #97C697",
"f. c #BFD6BF",
"g. c #EEE9EE",
"h. c #AFAFAF",
"j. c #D5D5D5",
"k. c #E7E7E7",
"l. c #F3F3F3",
"z. c gray75",
"x. c #E5E4E5",
"c. c #F4EAF4",
"v. c #ECE7EC",
"b. c gray78",
"n. c #ECEDEC",
"m. c #B6B6B6",
"M. c gray87",
"N. c gray79",
"B. c #F4F4F4",
"V. c gray81",
"C. c gray53",
"Z. c #A5A5A5",
"A. c #959595",
"S. c #9A9A9A",
"D. c #B4B4B4",
"F. c #DDDDDD",
"G. c #BBBBBB",
"H. c #CBCBCB",
"J. c #CACACA",
"K. c gray52",
"L. c #151515",
"P. c gray23",
"I. c #E1E1E1",
"U. c #7E7E7E",
"Y. c #101010",
"T. c gray26",
"R. c #B9B9B9",
"E. c gray34",
"W. c #343434",
"Q. c #979797",
"!. c #3A3A3A",
"~. c #484848",
"^. c gray67",
"/. c #565656",
"(. c gray43",
"). c #D8D8D8",
"_. c #EFEFEF",
"`. c #F9F9F9",
"'. c gray64",
"]. c #AAAAAA",
"[. c gray66",
"{. c #EDEEED",
"}. c #EFE9EF",
"|. c #F2EAF2",
" X c gray46",
".X c #353535",
"XX c #676767",
"oX c #4CA84C",
"OX c #3DA23D",
"+X c #8BC18B",
"@X c #727272",
"#X c #AEAEAE",
"$X c #282828",
"%X c #6C6C6C",
"&X c #D4DED4",
"*X c #AFD0AF",
"=X c #57AB57",
"-X c #279727",
";X c gray",
":X c #1D1D1D",
">X c #929292",
",X c #CDCDCD",
"<X c #1B1B1B",
"1X c #F8EDF8",
"2X c #9DC89D",
"3X c #199419",
"4X c #67B367",
"5X c #F0EAF0",
"6X c #313131",
"7X c gray59",
"8X c gray88",
"9X c #505050",
"0X c gray35",
"qX c #F8F8F8",
"wX c #C8DAC8",
"eX c #CBDBCB",
"rX c #87BF87",
"tX c #0F8A0F",
"yX c gray50",
"uX c #AACEAA",
"iX c #38A038",
"pX c #349F34",
"aX c #85BF85",
"sX c #626262",
"dX c #EAE6EA",
"fX c #E8E5E8",
"gX c #F0E9F0",
"hX c #EAEBEA",
/* pixels */
"                                                                                        ",
"        . . . . . . . . . . . X X . . . . . . . . . . X X . . . . . . . . . . X         ",
"                                                                                        ",
"      o O + + + + + + + + + @ # $ O + + + + + + + + @ % % @ + + + + + + + + O &         ",
"  .   O * = = = = = = = = - ; : > * = = = = = = = - ; , < 1 - = = = = = = - 2 3 4       ",
"  .   + = 5 6 6 6 7 8 7 6 9 * 0 q = 6 6 6 w w 5 6 5 * e r * 9 6 6 7 t t 6 9 y u 4       ",
"  .   + = 6 6 6 7 i p a 7 5 * 0 s = 6 6 - d f - 5 5 * e r * 5 6 6 g h j i 9 y u 4       ",
"  .   + = 6 6 6 k l z x c 9 * 0 s = 6 - v b n > m 9 * M N B 5 6 k 6 V C Z g y u 4       ",
"  .   + = 6 6 A p S D F G H * 0 s = 9 ; J K L P m 5 * M N B 5 7 I U Y T R E W u 4       ",
"  .   + = 6 A Q ! ~ ^ / ( ) * 0 s = 6 6 w _ ` & ' 5 * M N B ] [ { } |  ...X.y u 4       ",
"  .   + = 6 7 I o.O.+.@.#.5 * 0 s = 6 9 ; $.%.&.* w * M N B ] I *.=.-.;.:.j >.u 4       ",
"  .   + = 6 6 i / ,.<.1.2.9 * 0 s = 9 ; 3.  4.5.6.7.* M N B 5 6 c Y 8.9.0.q.w.u 4       ",
"  .   + = 6 6 6 e.r.t.y.[ 9 * 0 s = 5 m u.i.p.a.w 6 * M N B 5 6 a s.d.f.g.] * u 4       ",
"  .   + - 9 9 5 H ) q.g 9 w ' h.j.k.5 9 = 1 l.l.5 w y N z.y w 5 9 x.c.v.] w ' b.4       ",
"  .   @ ; * * * * * W n.* ' d m.M.; * * y m m m * y d N.b.d y * * n.w.W * ' B.V.4       ",
"  X   # : 0 0 0 0 0 0 0 0 h.m.C.Z.: 0 0 0 0 0 0 0 h.m.A.$.m.h.0 0 0 0 0 0 h.m.S..       ",
"  X   $ > q s s s s s s s j.M.Z.N.> s s s s s s s q M.m.D.M.j.s s s s s s j.F.G..       ",
"  .   O * = = = = - - = = k.; : > * = = = = = = = - ; , < ; - = = = = = = - 2 H.4       ",
"  .   + = 6 6 6 k.y * = 6 5 * 0 s = 6 6 6 6 6 6 6 5 * e r * 5 6 6 6 6 6 6 5 y u 4       ",
"  .   + = 6 6 k.F.J.N q - 9 * 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + = 6 w d K.L.P.a.; I.* 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + = 6 w f U.Y.T.R.* w * 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + = 6 6 - j.F.E.W.l.w * 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + = 6 5 * A.Q.!.~.B.I.* 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + = 6 9 * ^./.(.).= 9 * 0 s = 6 7.7.7.7.7.7.5 * M N B 5 7.7.7.7.7.7.5 * u 4       ",
"  .   + - 5 5 9 _.`.f k.9 9 y h.q - 5 5 5 5 5 5 5 9 y N r y 9 5 5 5 5 5 5 9 ' b.4       ",
"  .   @ ; * * B ' = m y B y d m.M.; * * * * * * * y d N.b.f y * * * * * * y d V.4       ",
"  X   % , e e M M M M M M N N.A.m., e M M M M M M N N.Z.'.N.N M M M M M M N u ]..       ",
"  X   % < r r N N N N N N z.b.$.D.< r N N N N N N r b.'.i.u z.N N N N N N z.b.[..       ",
"  .   @ 1 * * B B * * * B y d m.M.; * B B {.{.B B y f N.u f y B B B * B B y d V.4       ",
"  .   + - 9 5 5 9 9 w 9 5 w y h.j.- 5 5 A ] ] H 5 9 y N z.y 9 5 5 w w 9 5 w ' b.4       ",
"  .   + = 6 6 6 ' B B * 6 5 * 0 s = 6 6 a }.g.|.6 5 * M N B 5 6 7.2 _.- 6 5 * u 4       ",
"  .   + = 6 9 _. X%..XXXB w * 0 s = 7 [ { oXOX+X[ A * M N B 5 6 - @X+ #X2 I.* u 4       ",
"  .   + = 6 6 - < z.$X%Xf I.* 0 s = 7 a &X*X=X-X2.5 * M N B 5 7.5 ;X:X>Xd I.* u 4       ",
"  .   + = 6 6 9 f ,X<Xj.' 9 * 0 s = 6 t 1X2X3X4X5X] * M N B 5 6 5 _ 6X7X`.8X* u 4       ",
"  .   + = 6 6 9 d 9X0XqXw 5 * 0 s = 7 c wXeXrXtXZ X.n.M N B 5 6 6 &.% yXy 9 y u 4       ",
"  .   + = 6 5 = > 4.r B 5 5 * 0 s = A 5XuXiXpXaX2.A * M N B 5 6 m sX$ @ 3._.m u 4       ",
"  .   + - 9 5 5 w k.k.9 5 w ' h.j.- 5 A dXX.fXgX5 w y N z.y w 5 5 9 k.6 9 w ' b.4       ",
"  .   O 2 y y y * y y * y ' B.m.F.2 y * W y y hX* ' d u b.d ' * y * y * * ' B.u.4       ",
"  X   & 3 u u u u u u u u b.V.S.G.H.u u u u u u u b.V.].[.V.b.u u u u u u b.u.h..       ",
"        4 4 4 4 4 4 4 4 4 4 4 . . 4 4 4 4 4 4 4 4 4 4 . . 4 4 4 4 4 4 4 4 4 4 .         ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 187 2 ",
"   c black",
".  c #010101",
"X  c gray6",
"o  c #101010",
"O  c gray5",
"+  c #111111",
"@  c #CDCDCD",
"#  c gainsboro",
"$  c #D8D8D8",
"%  c gray85",
"&  c #D8D9D8",
"*  c gray80",
"=  c gray70",
"-  c #DFDFDF",
";  c gray93",
":  c gray91",
">  c #E8E9E8",
",  c #EAE9EA",
"<  c #EDEBED",
"1  c gray86",
"2  c #C0C0C0",
"3  c #EFEFEF",
"4  c #E9E9E9",
"5  c #EEEEEE",
"6  c #ECECEC",
"7  c #E7E8E7",
"8  c #EBEAEB",
"9  c #F0ECF0",
"0  c gray89",
"q  c #E6E5E6",
"w  c #E3E4E3",
"e  c #D3DED3",
"r  c gray90",
"t  c #D7D7D7",
"y  c gray74",
"u  c gray92",
"i  c #E7E7E7",
"p  c #D0D0D0",
"a  c #CACACA",
"s  c #ECE7EC",
"d  c #DCE1DC",
"f  c #C4D8C4",
"g  c #E1E3E1",
"h  c #E9E8E9",
"j  c #E2E4E2",
"k  c #F7ECF7",
"l  c #5DAF5D",
"z  c #37A037",
"x  c #EFE9EF",
"c  c gray",
"v  c gray88",
"b  c #717171",
"n  c gray22",
"m  c gray51",
"M  c gray95",
"N  c #ECE8EC",
"B  c #C8DAC8",
"V  c #43A443",
"C  c #6FB66F",
"Z  c #D9E0D9",
"A  c #ECEAEC",
"S  c #F1E9F1",
"D  c #9EC99E",
"F  c #54AB54",
"G  c #48A748",
"H  c #E7E6E7",
"J  c #E4E4E4",
"K  c #E2E2E2",
"L  c white",
"P  c gray42",
"I  c gray48",
"U  c gray96",
"Y  c #E5E7E5",
"T  c #F7EDF7",
"R  c #7BB97B",
"E  c #2A992A",
"W  c #68B468",
"Q  c #C7D9C7",
"!  c #EFEBEF",
"~  c #E6E8E6",
"^  c #74B874",
"/  c #3CA13C",
"(  c #148D14",
")  c #BFD6BF",
"_  c #F1ECF1",
"`  c #D6D7D6",
"'  c gray37",
"]  c gray19",
"[  c gray81",
"{  c #F6ECF6",
"}  c #86BF86",
"|  c #4EA84E",
" . c #4AA24A",
".. c #97C497",
"X. c #F8F0F8",
"o. c #D6D8D6",
"O. c #CADACA",
"+. c #6F6F6F",
"@. c #656565",
"#. c #9A9A9A",
"$. c #EAEAEA",
"%. c #80BD80",
"&. c #85BF85",
"*. c #F6EEF6",
"=. c gray98",
"-. c #F9F9F9",
";. c gray94",
":. c #F8EFF8",
">. c #D7D8D7",
",. c #D5D7D5",
"<. c #CBCBCB",
"1. c #B2B2B2",
"2. c gray87",
"3. c #D5D5D5",
"4. c gray83",
"5. c gray84",
"6. c gray61",
"7. c #C3C3C3",
"8. c #BCBCBC",
"9. c #C1C1C1",
"0. c #747474",
"q. c gray56",
"w. c #E6E6E6",
"e. c #F4F4F4",
"r. c gray59",
"t. c #060606",
"y. c #686868",
"u. c #D2D2D2",
"i. c gray75",
"p. c gray16",
"a. c #A7A7A7",
"s. c #606060",
"d. c gray25",
"f. c #B6B6B6",
"g. c #F6F6F6",
"h. c #E8E7E8",
"j. c #DADADA",
"k. c #CECECE",
"l. c #D7DFD7",
"z. c #D6DFD6",
"x. c #EDE8ED",
"c. c #ECEBEC",
"v. c #E1E1E1",
"b. c #9B9B9B",
"n. c gray29",
"m. c #272727",
"M. c #84BE84",
"N. c #3AA13A",
"B. c #8CC28C",
"V. c #F2EAF2",
"C. c #E9EBE9",
"Z. c #BDBEBD",
"A. c gray18",
"S. c #848484",
"D. c #434343",
"F. c #E2E3E2",
"G. c #CCDCCC",
"H. c #309D30",
"J. c #F4EAF4",
"K. c gray49",
"L. c #FBFBFB",
"P. c #F1F1F1",
"I. c #484848",
"U. c gray62",
"Y. c #E5E4E5",
"T. c #E0E3E0",
"R. c #BAD4BA",
"E. c #5AAD5A",
"W. c #F5EBF5",
"Q. c #E8EAE8",
"!. c #5D5D5D",
"~. c #EAEBEA",
"^. c #DEE2DE",
"/. c #79B979",
"(. c #63B063",
"). c #B7D2B7",
"_. c #EAE6EA",
"`. c #E9EAE9",
"'. c #5A5A5A",
"]. c #565656",
"[. c #C5C5C5",
"{. c #F0EFF0",
"}. c #F5EEF5",
"|. c #F7EFF7",
" X c #E6E7E6",
".X c gray97",
"XX c #DDDDDD",
/* pixels */
"                                                                ",
"  . X o o o o o o o X O + o o o o o o + O X o o o o o o o X .   ",
"  X @ # $ % % & % # * = - $ % $ $ % $ - = * # % % & & $ # @ X   ",
"  o # ; : > , < > ; 1 2 3 : 4 5 3 : : 3 2 1 6 4 7 8 9 : ; # o   ",
"  o $ : 0 q w e r : t y u 0 i p a 6 0 u y t : w s d f g h $ o   ",
"  o % 4 j k l z x 7 $ c u r v b n m M 4 y $ 7 N B V C Z A & o   ",
"  o % 7 S D F G H > $ c 6 J K L P I U 4 y $ Y T R E W Q ! $ o   ",
"  o % ~ S ^ / ( ) _ ` c 6 0 3 ' ] [ i u y $ ~ { } |  ...X.o.o   ",
"  o % 4 w N O.} q : t y u r K +.@.#.u $.y $ : q w %.&.w 4 $ o   ",
"  o # ; : > < *.4 6 1 2 3 i 4 =.-.M i ;.2 1 6 : , :.:.h 6 # o   ",
"  X * 1 t $ >.,.$ 1 <.1.2.t $ 3.4.5.t 2.1.<.1 $ >.,.,.t 1 * X   ",
"  O = 2 y c c c y 2 1.6.7.8.c c c c 8.7.6.1.2 y c c c y 2 = O   ",
"  + - 3 u u : 4 u 3 2.7.M $.6 6 6 6 $.M 7.2.3 u 6 6 6 u 3 - +   ",
"  o $ : K $.U ;.J i t 8.$.0 J J J J 0 $.8.t i J J J J 0 : $ o   ",
"  o % : 6 9.0.q.K $.$ c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % w.e.r.t.y.4 : $ c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % : : u.i.p.y M 5.c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % i 5 a.s.d.4.; t c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o $ i r 1 f.1 4 w.t 8.$.0 J J J J 0 $.8.t i J J J J 0 : $ o   ",
"  + - ;.$.5 g.5 $.;.2.7.M $.6 6 6 6 $.M 7.2.3 u 6 6 6 u 3 - +   ",
"  O = 2 y y 8.y y 2 1.6.7.8.c c c c 8.7.6.1.2 y c c c y 2 = O   ",
"  X * 1 t $ t t t 1 <.1.2.t $ >.>.$ t 2.1.<.1 $ $ t $ t 1 * X   ",
"  o # ; : 6 5 6 4 6 1 2 3 h.4 A A 7 : 3 2 1 6 : 4 6 $.: ; # o   ",
"  o % : w.j.k.1 0 4 t y u w H l.z.x.0 c.y $ : r J $ v.r 4 % o   ",
"  o % i 3 b.n.m.<.3 t c 6 J r M.N.B.V.C.Z.$ i u k.A.S.e.w.% o   ",
"  o % 4 K U = D.5 : $ c 6 F.N G.H.M.J.C.Z.$ 4 v.=.K.0.L.r % o   ",
"  o % 4 0 P.I.U.U w.$ c 6 Y.T.R.| E.W.Q.y $ 4 J 3 @.!.; : % o   ",
"  o $ i i 5.0.K r : t y ~.Y.^./.(.)._.`.y t i $.a '.].[.3 t o   ",
"  o # ; : $.g.$.: ; 1 2 {.7 8 }.|._  X;.2 1 ; : u .X.Xu 6 XXo   ",
"  X @ # $ % 5.% % # * = - $ % o.o.>.$ - = * # % % 5.5.$ # @ X   ",
"  . X o o o o o o o X O + o o o o o o + O X o o o o o o o X .   ",
"                                                                "
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 112 2 ",
"   c #010101",
".  c #101010",
"X  c #111111",
"o  c #0E100E",
"O  c gray6",
"+  c #0F100F",
"@  c #101110",
"#  c gray76",
"$  c #D8D8D8",
"%  c #DCD6DC",
"&  c #D5D5D5",
"*  c #BEBFBE",
"=  c #D0D0D0",
"-  c gray84",
";  c #DDDDDD",
":  c gray82",
">  c gray75",
",  c gray83",
"<  c #DBD5DB",
"1  c #DDDADD",
"2  c #C1C2C1",
"3  c #EEEFEE",
"4  c #A5CEA5",
"5  c #E7EAE7",
"6  c #D4D3D4",
"7  c gray93",
"8  c #CDCDCD",
"9  c gray66",
"0  c gray92",
"q  c #D2D3D2",
"w  c #F3EFF3",
"e  c #B0D2B0",
"r  c #C4DEC4",
"t  c #DEDADE",
"y  c #DAD5DA",
"u  c #C1D9C1",
"i  c #3D9C3D",
"p  c #D4DED4",
"a  c #D1CED1",
"s  c #EAEBEA",
"d  c #AFAFAF",
"f  c DimGray",
"g  c gray91",
"h  c #CBCCCB",
"j  c #EFEAEF",
"k  c #57A957",
"l  c #79BC79",
"z  c #DDD6DD",
"x  c #E9EBE9",
"c  c #C5D8C5",
"v  c #E2E6E2",
"b  c #D1D0D1",
"n  c #EAEAEA",
"m  c #C6C6C6",
"M  c #BBBBBB",
"N  c #EDEBED",
"B  c #CBDBCB",
"V  c #CEE0CE",
"C  c #D9D6D9",
"Z  c #D5D0D5",
"A  c #D2D1D2",
"S  c gray80",
"D  c #D7D7D7",
"F  c gray85",
"G  c #D4D0D4",
"H  c #DAD6DA",
"J  c gray",
"K  c #100F10",
"L  c #E9E9E9",
"P  c #E4E5E4",
"I  c gray90",
"U  c #E1E1E1",
"Y  c #E2E2E2",
"T  c #E0E1E0",
"R  c #E6E7E6",
"E  c gray86",
"W  c #CBCBCB",
"Q  c #6C6C6C",
"!  c gray89",
"~  c #E7E7E7",
"^  c #E4E4E4",
"/  c gray37",
"(  c #D2D2D2",
")  c #E6E6E6",
"_  c #E6E5E6",
"`  c #DFE4DF",
"'  c #E0E5E0",
"]  c #DADADA",
"[  c gray38",
"{  c #D1D2D1",
"}  c #E9E4E9",
"|  c #BBD4BB",
" . c #67B267",
".. c #E6E4E6",
"X. c #F3F3F3",
"o. c gray59",
"O. c gray87",
"+. c #A4A4A4",
"@. c gray95",
"#. c #EFEBEF",
"$. c #C0DAC0",
"%. c #80C080",
"&. c #EBE9EB",
"*. c #F8F8F8",
"=. c #A0A0A0",
"-. c #C3C3C3",
";. c #D0D2D0",
":. c #D6D5D6",
">. c #CECECE",
",. c gray7",
"<. c #131313",
"1. c white",
/* pixels */
"  . X o X O X . O X O X + @ .   ",
". # $ % & * = - ; : > , < 1 2 . ",
"X $ 3 4 5 6 7 8 9 0 q w e r t @ ",
"+ y u i p a s d f g h j k l z + ",
"X & x c v b n m M g = N B V C X ",
"O * , Z A M S D F S M = G H J K ",
"X : L P I 8 U Y Y U 8 I T R : X ",
". E W Q ! : ! ~ ~ ^ = g I 0 , X ",
". $ - / : & ! ~ ~ ^ = g I 0 , X ",
"X ( Y = ) 8 U ! ! U 8 I U g : X ",
". J D $ : M 8 A A 8 M = : & J O ",
"X - ^ : ~ : _ ` ' _ = n ] g - X ",
". & E [ & { } |  ...W X.o.d O.O ",
"X ] I +.@.{ #.$.%.&.: *.=.=.^ O ",
". -.- , & J : ;.:.A J & >., # . ",
"  . ,.. X O X ,.X X O X ,.<..   "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
