#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 206 2 ",
"   c #000000",
".  c gray4",
"X  c #161616",
"o  c #2A3C1E",
"O  c gray16",
"+  c #3A3B39",
"@  c #313D2A",
"#  c #354E24",
"$  c #36472A",
"%  c #394F29",
"&  c #415E2E",
"*  c #465A38",
"=  c #44662D",
"-  c #476632",
";  c #4E7137",
":  c #52753A",
">  c #55793C",
",  c #587E3F",
"<  c #4C4B4C",
"1  c #545454",
"2  c #5D5D5D",
"3  c #5A6F4D",
"4  c #556E44",
"5  c #577446",
"6  c #5A7547",
"7  c #5A7B40",
"8  c #5D7949",
"9  c #5D7150",
"0  c #627455",
"q  c #666F60",
"w  c #676767",
"e  c #747474",
"r  c #7E7D7E",
"t  c #6B7366",
"y  c #965D00",
"u  c #975700",
"i  c #925300",
"p  c #A35300",
"a  c #986705",
"s  c #99730A",
"d  c #A66605",
"f  c #00AE00",
"g  c #13A700",
"h  c #01B300",
"j  c #09B606",
"k  c #07B805",
"l  c #14B80D",
"z  c #18BD11",
"x  c #38BC1C",
"c  c #478900",
"v  c #508F04",
"b  c #5EA217",
"n  c #58863A",
"m  c #63AB20",
"M  c #1FC016",
"N  c #26C21B",
"B  c #2EC421",
"V  c #38C929",
"C  c #42CB2D",
"Z  c #4BD136",
"A  c #4FD438",
"S  c #55D63D",
"D  c #49CF34",
"F  c #5A8040",
"G  c #5F8943",
"H  c #628B46",
"J  c #668C49",
"K  c #698B4B",
"L  c #69964B",
"P  c #6C9A4D",
"I  c #639344",
"U  c #739A52",
"Y  c #6F9B50",
"T  c #74AB4E",
"R  c #70A34D",
"E  c #7AAB53",
"W  c #72A251",
"Q  c #79B154",
"!  c #5CD842",
"~  c #65DE48",
"^  c #64DC47",
"/  c #6CE24D",
"(  c #79E856",
")  c #9E871D",
"_  c #9E8D23",
"`  c #A1972B",
"'  c #AB922A",
"]  c #A3A333",
"[  c #CDAE00",
"{  c #CBB301",
"}  c #CAB70A",
"|  c #C8BD13",
" . c #C7C117",
".. c #C6C21A",
"X. c #C5C722",
"o. c #C3CD2D",
"O. c #C5C925",
"+. c #C1D338",
"@. c #83BB5D",
"#. c #A7BB49",
"$. c #86BC60",
"%. c #8BBC63",
"&. c #8ACE5D",
"*. c #86CE55",
"=. c #8BD05C",
"-. c #BDDE49",
";. c #BEDC44",
":. c #AAD35D",
">. c #A7C752",
",. c #87E95C",
"<. c #BBE656",
"1. c #BCE14E",
"2. c #8ECC64",
"3. c #92CD66",
"4. c #95CE6A",
"5. c #99CD6B",
"6. c #93D169",
"7. c #99D06D",
"8. c #9BDD6F",
"9. c #96DB68",
"0. c #9DDD71",
"q. c #A1DF73",
"w. c #ADD963",
"e. c #8BEB64",
"r. c #9AEC68",
"t. c #8AF363",
"y. c #96F76B",
"u. c #9EE171",
"i. c #9DFA71",
"p. c #A2EE6F",
"a. c #B8EE66",
"s. c #B7EF69",
"d. c #B6F36D",
"f. c #B7F067",
"g. c #A5EC76",
"h. c #ACEC7A",
"j. c #A8E576",
"k. c #B3EC7B",
"l. c #A3F575",
"z. c #A4FD75",
"x. c #AEFF77",
"c. c #ADF67B",
"v. c #AFFA7D",
"b. c #A4FD79",
"n. c #B2F67A",
"m. c #B1FC7E",
"M. c #B6F979",
"N. c #807F80",
"B. c gray55",
"V. c #858585",
"C. c #959595",
"Z. c #9C979F",
"A. c #9A9A9A",
"S. c #9C97A0",
"D. c #9D99A0",
"F. c #9A8EA2",
"G. c #A39EA6",
"H. c #A2A2A2",
"J. c #ADADAD",
"K. c #B2B2B2",
"L. c #BABABB",
"P. c #B4BBAF",
"I. c #AFFE83",
"U. c #B3FF80",
"Y. c #BAFF85",
"T. c #B4FF89",
"R. c #BEFF88",
"E. c #B3F280",
"W. c #BEFF90",
"Q. c #B3EC80",
"!. c #BACAAF",
"~. c #C2FF8A",
"^. c #C8FF8E",
"/. c #C1FF87",
"(. c #C2FF92",
"). c #CCFF92",
"_. c #D0FF95",
"`. c #C3DAB4",
"'. c #CDE8BB",
"]. c #BCB6C1",
"[. c #C2BEC6",
"{. c #CBCBCB",
"}. c #C3C2C3",
"|. c #D1DACB",
" X c #D8D3DC",
".X c #DCDBDC",
"XX c #D5D3D6",
"oX c #CFD5CA",
"OX c #D3EEC1",
"+X c #D6F3C3",
"@X c #DEEDD4",
"#X c #E5F7D9",
"$X c #E8F7DC",
"%X c #DFDCE1",
"&X c #E3DFE6",
"*X c #E6E6E6",
"=X c #E7E3E9",
"-X c #E9E4ED",
";X c #EAEBEA",
":X c #E7E9E6",
">X c #F0F1EF",
",X c #EDEAF0",
"<X c #F5F5F5",
"1X c #FAFAFA",
"2X c #F7F4F9",
"3X c #F0F0F0",
/* pixels */
"*X*X*X*X*X*X*X*X*X:X*X*X:X*X:X=X*X:X*X:X*X*X=X*X*X*X:X*X:X*X*X:X*X*X*X*X*X*X*X:X*X:X*X=X:X*X*X:X*X*X*X=X*X*X=X:X*X*X*X*X*X*X*X=X*X:X*X=X:X*X:X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X:X*X:X*X*X*X*X*X*X*X",
"*X*X:X*X*X*X:X*X*X*X*X*X*X*X*X*X*X=X*X*X=X*X*X*X:X*X*X*X*X*X*X=X*X*X:X*X:X*X*X=X*X*X*X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X*X:X*X*X:X*X*X*X*X*X*X*X*X:X*X*X=X*X*X*X:X*X*X:X*X*X*X*X*X*X*X:X=X*X*X*X*X",
"*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X*X*X*X*X:X*X=X*X*X*X*X*X:X*X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X:X*X*X:X=X*X:X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X:X=X:X*X:X*X:X-X*X*X",
":X*X:X*X*X*X*X*X:X*X:X=X*X*X:X*X*X:X*X=X*X:X*X:X*X*X:X*X*X*X*X*X*X*X:X*X:X:X*X*X=X*X*X*X:X*X*X=X*X*X*X*X:X*X*X*X*X*X*X=X*X*X:X*X:X=X*X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X",
"*X=X*X=X*X*X=X=X*X*X*X*X*X*X*X=X=X*X*X:X*X*X*X=X*X*X*X*X*X*X*X*X*X*X*X*X=X=X*X*X=X=X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X=X*X=X=X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X-X*X*X*X*X*X*X*X",
"*X*X*X*X:X*X:X:X;X:X:X;X;X;X:X:X:X;X:X:X:X:X*X=X:X:X:X:X;X:X;X:X:X:X;X;X;X;X:X*X:X:X*X:X:X:X:X:X;X;X;X:X:X:X:X;X:X*X:X;X;X;X:X:X;X:X:X:X:X:X:X:X;X;X:X=X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X:X*X:X",
"*X*X*X=X X&X X%X X X X X X X X X X X X X X X&X X X X X X X X X X X X X X X X X.X.X X X X X X X X X X X X X X X X X%X X X X X X X X X X X X X X X X X%X=X*X*X*X*X*X*X*X:X*X*X*X*X:X*X*X*X*X*X*X*X",
"*X*X;XoX- $ 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 8 $ 4 8 6 6 5 6 5 5 5 5 5 5 6 6 6 8 * * 8 6 6 8 6 6 6 6 6 6 6 6 6 6 6 8 $ 6 6 6 5 5 6 5 5 5 5 6 7 6 6 6 8 % J.<X*X*X=X*X:X*X*X:X*X:X*X*X*X*X=X:X*X*X*X",
"*X*X=X#X3.J ^.m.Y.Y.Y.Y.Y.Y.m.Y.Y.Y.Y.Y.M.~.> h.Y.Y./.~.~.~.~.~.~.~.~.~.R.U.^.@.U ^.E.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.: E.Y.Y.~.~.~.~.~.^.~.~.^.~.Y.Y.^.E Z.<X.X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X",
"*X*X=X#X2.H ~.c.m.m.U.m.m.U.U.M.m.m.m.m.m.Y.: g.m.Y.e.V V ^ C B Z ! B Z l.U.Y.@.L /.n.m.m.m.v.m.U.m.m.m.m.m.m.m.U.: v.v.U.,.V V ^ V B A S N S c.m.Y.T Z.<X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X:X*X",
"*X*X=X#X&.J ~.v.m.U.m.m.T.<.f.T.Y.m.U.U.m.Y.> g.Y.y.l f f f f f f f f f B m.R.$.L ~.m.U.U.m.m.U.<.d.U.U.m.m.U.m.Y.: v.Y.e.j f f h f f f f f f V m.~.T Z.<X*X*X:X*X*X*X-X*X*X*X*X%X*X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.v.m.m.m.U.U.| o.I.m.m.m.U.v.Y.> g./.( f k h h h h h h h h h i.~.Q P ~.m.U.U.U.U.m.} +.T.m.m.m.U.m.U.: c.~.^ f j h h h h h j h h j l.~.T Z.<X*X*X:X*X*X*X*X*X*X*X<X1X1X;X*X*X*X*X:X",
"*X*X*X#X2.H ~.v.U.U.m.I.<.[ { f.T.m.m.m.I.Y.: g.~.( f h h h h h h h h h j l.^.@.P ~.v.m.m.m.T.-.[ } d.T.m.U.U.m.U.: v.~./ f h h h h h h h h h z v.^.T S.<X*X*X*X*X*X*X*X*X*X=XD.e e K.;X*X*X*X*X",
"*X*X=X#X&.H ~.v.m.m.U.m...{ { o.U.m.m.m.m.Y.: h.l.N f h h h h h h h h h h C R.@.P ~.m.U.U.U.M.| [ [ +.I.m.U.m.U.U.; U.y.z h h h h h h h h h h h Z ^.T Z.<X*X*X*X*X:X*X*X=X;X X$ + X   J.;X*X*X*X",
"*X*X=X#X2.H ~.m.U.m.T.<.{ { { { a.T.m.m.v.Y.: E./ f h h h h h h h h h h h f z.$.P ~.v.U.m.T.-.[ { { } d.U.m.U.U.Y.; Y.! f h h h h h h h h h h h h v.T S.<X.X=X*X*X*X*X*X*X*X%X%X1XA.  C.<X=X*X*X",
"*X*X=X#X2.H ~.m.m.U.I...[ { { [ o.T.m.U.U.Y.: n./ f k h h h h h h h h h h f i.2.L ~.v.m.U.M.| { { { { +.T.m.U.U.U.; R.! f h h h h h h h h h h h h v.E S.<X*X:X*X*X:X:X=X*X=X;X{.O . + *X*X*X*X*X",
"*X*X=X#X2.H ~.v.m.T.<.[ { { { { { f.T.m.v.Y.> h.z.N f f f h h h h h f f f C R.@.P ~.m.m.T.-.{ { { { { { d.T.U.U.U.: U.y.z f f f h h f h h f f f A (.T Z.<X.X:X*X*X*X*X*X*X*X;X%XC.w   B.3X*X*X*X",
"*X*X=X#X2.H ~.v.U.v. .{ { { { { { o.I.m.v.Y.> g.Y.c.~ / S h k k h l / ~ ( v.~.@.P ~.v.m.m.| [ { { { { { +.I.m.m.U.: v.Y.l.^ / Z f f k h z / ~ ( U.~.T Z.1X*X:X:X*X*X*X*X*X;X{.H.*XA.  e <X=X*X=X",
"*X*X*X#X2.H ~.m.T.<.{ { { { { { { { f.I.m.Y.> g.U.U.R.~.Y.r.v c b b.Y.~.Y.m.R.@.P ~.v.T.;.[ { { { { { { } d.U.m.U.: v.m.Y.Y.~.Y.,.v c m x.R.~.R.m.~.T S.<X.X*X:X:X*X*X:X*X;XL.X . . + {.;X=X*X:X",
"*X*X:X#X&.H /.v.U...[ { { { { { { [ o.T.v.Y.> g.U.m.m.m.U.M.d p ' T.v.v.m.v.R.@.L ~.v.m.| { { { { { { { { +.T.m.Y.: v.U.m.m.v.T.k.d u ' T.m.v.v.v.~.T S.<X*X*X*X*X*X*X*X*X*X:XXX{.{.*X;X*X*X*X*X",
"*X*X=X#X2.H /.I.-.[ [ [ { [ [ [ [ [ [ a.I.Y.> g.Y.m.m.m.m.c.s u _ T.m.m.U.m.R.@.P /.I.;.[ [ [ [ { [ [ { [ { d.I.U.: m.m.m.m.m.U.d.a y ] T.m.I.U.m.R.T S.2X*X=X:X*X*X:X*X*X*X*X;X;X;X*X*X*X*X*X:X",
"*X*X=X#X2.H /.I.+.|  . . . . . . .| | ;.I.Y.> g.U.m.U.m.U.c.a i ) T.m.U.U.m.R.@.P ~.v.o.|  . . . . . .|  .| -.T.m.: v.m.m.m.m.T.j.u i ` T.m.m.U.m.~.T S.<X&X*X*X*X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X",
"*X*X=X#X2.H Y.c.v.I.I.I.I.I.I.I.I.I.I.v.c.Y.: g.m.m.v.v.m.c.>.>.:.v.m.m.v.c.R.@.L Y.c.I.I.I.I.I.T.U.I.I.I.I.v.v.U.: c.v.v.v.m.m.c.>.>.:.U.v.E.v.v.R.R S.<X*X:X*X*X:X*X:X*X*X*X*X*X*X*X*X:X*X*X*X",
"*X*X&X$X5.K ).R.~././.~./.~.~.R.~.R././.R.).7 Q.~.~.~.~.~.~.(.(.(./.~.~././.).%.U _.R./.R.~.~.~.Y.~.~.~.~.~.~.R.^.: R.~.~.~.~.~.R.(.(.~.~.~.R.~.R.).E S.<X.X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X",
"*X*X;X|.- # L H H H H H J J G J H J H H H I $ 7 H H H G G G G G G G G H H J L - % L H H H H J G H J H J H J H H J o G H H H H H H H H H H H J H H P % H.<X%X*X*X*X:X*X*X:X*X:X=X*X*X*X*X*X*X*X*X",
"*X*X=X@XR ; 8.2.3.2.3.2.2.2.2.2.2.2.2.2.2.7.% &.6.2.2.7.7.4.7.7.4.4.7.6.2.2.9.L > 8.2.2.2.2.2.2.2.2.2.2.2.2.2.3.4.& 2.3.2.2.2.3.2.4.2.2.3.2.2.2.2.u.n D.<X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X:X:X*X",
"*X*X=X#X3.K ).U.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.~.5 h.R.R.R.y.t.x.y.t.i.x.t.z.~.Y.(.%.U ).Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y./.: Y.Y.Y.Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.U.).E Z.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.H R.v.I.E.U.U.m.U.U.m.U.I.U.U.v.Y.: g.U.v.C h h l h f k j f h ^ U.Y.@.L ~.v.m.U.v.U.U.I.U.m.m.I.U.U.m.U.: c.m.E.U.I.U.m.U.U.m.m.U.U.v.m.R.T A.<X%X:X:X-X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.m.U.U.U.U.v.Y.> g.R.( f h h h h h h h h f j i.~.$.P ~.m.m.U.U.U.m.U.m.U.U.U.m.U.m.U.: v.U.v.U.U.U.U.U.U.m.U.U.U.U.m.R.T S.1X%X*X:X*X*X*X*X:X*X=X*X:X;X*X*X*X*X*X*X",
"*X*X*X#X2.H ~.v.U.U.m.U.m.U.U.U.U.U.m.U.U.Y.: g.^.( f h h h h h h h h h j g.~.@.P ~.m.m.m.U.U.U.U.U.U.U.U.U.U.m.U.: v.U.U.U.U.U.m.U.U.U.U.U.m.U.v.~.T S.<X%X*X*X:X*X*X*X*X*X*X;X.X X*X*X*X*X*X:X",
"*X*X*X#X2.H /.v.U.U.U.U.U.U.U.U.U.m.U.U.v.Y.> g.Y.S h h h h h h h h h f h ( ~.@.P ~.m.m.U.U.U.U.U.U.U.m.U.U.U.U.Y.: v.U.m.U.U.m.U.U.U.U.U.m.U.U.I.~.T S.<X*X*X*X*X*X*X*X*X*X*X1 . . K.<X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.m.U.U.U.U.m.U.U.U.U.U.m.Y.: c.,.h h h h h h h h h h h f l v.$.L ~.m.U.U.U.U.U.m.U.U.U.m.U.U.m.U.: v.U.m.U.U.U.U.U.m.U.U.U.m.U.v.~.T S.<X*X:X*X*X*X*X*X=X*X=XH.w   J.;X*X*X*X*X",
"*X*X*X#X2.H ~.v.U.U.U.U.U.U.U.m.U.U.U.U.m.Y.: E.~ f h h h h h h h h h h h f i.2.L ~.m.m.m.U.U.U.U.U.U.U.U.U.U.m.Y.: m.m.m.U.U.U.m.U.U.U.m.Y.U.U.m.~.T Z.1X.X:X*X*X*X:X*X*X*X=X1XA.  K.3X*X*X*X*X",
"*X*X=X#X&.H ~.v.U.U.m.U.m.U.U.U.U.U.U.U.v.R.: c.e.h h f h h h h h h f f f z m.@.L ~.m.m.U.U.U.m.U.m.U.U.m.U.U.m.Y.: m.m.m.U.m.U.U.U.U.U.m.m.U.U.m.~.T S.<X*X:X:X*X*X*X*X*X*X*X;XB.  J.;X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.U.U.U.U.U.U.Y.> g.Y./ z N z f h h h f M M N e.^.@.P ~.m.U.U.U.U.U.U.U.m.U.U.U.U.m.m.: v.m.m.m.U.U.U.U.U.U.U.U.U.m.m.~.T S.<X.X*X:X*X*X*X*X*X*X*X1XH.  }.1X%X*X*X*X",
"*X*X*X#X2.H ~.v.U.m.m.U.U.U.U.U.m.U.U.U.v.Y.> g.U.Y.U.U.l.Z g f l ^ m.m.Y.U.R.@.P ~.m.U.U.m.U.U.m.U.U.U.U.U.U.m.Y.: v.m.U.U.U.U.U.m.U.U.m.U.U.U.v.~.T S.<X*X*X*X*X:X*X*X*X*X;Xe O   O V.>X*X*X*X",
"*X:X=X#X2.H ~.v.U.U.m.U.U.U.U.m.U.U.U.m.m.Y.> g.U.m.U.m.T.M.s y _ ~.m.U.m.v.Y.@.P ~.m.m.U.U.U.U.Y.m.U.U.m.U.U.m.U.: v.U.m.U.U.U.U.U.U.U.m.U.U.U.m.R.T S.<X=X*X*X*X*X*X*X*X*X;Xe 1 t 1 B.3X=X*X*X",
"*X*X=X#X&.H ~.v.U.U.U.U.m.U.U.U.U.U.U.U.m.Y.: g.Y.m.U.m.U.n.s u ` T.m.m.m.m.~.@.P ~.v.m.U.m.U.m.m.m.U.U.U.U.U.m.U.: v.U.m.U.U.U.U.U.U.m.U.U.U.U.v.~.T S.<X*X:X*X:X*X*X*X*X*X*X1X1X1X1X2X*X*X*X*X",
"*X*X=X#X2.H ~.m.m.Y.U.U.U.U.U.m.U.U.U.U.v.Y.> g.U.m.U.m.U.n.a i ) T.m.m.U.m.R.@.P ~.m.U.U.U.m.m.U.U.U.U.U.Y.m.m.Y.: n.U.m.U.U.U.U.U.U.U.U.U.U.U.m.R.T S.<X%X*X*X*X*X*X*X*X=X*X*X%X%X%X=X*X*X*X*X",
"*X*X=X#X2.H /.m.m.m.m.m.U.m.m.m.m.m.m.m.m.Y.> g.Y.m.U.m.T.n._ s ] T.m.U.m.m.Y.@.P ~.m.m.m.m.m.m.m.U.m.m.m.m.m.m.U.: m.U.U.m.m.m.m.m.m.U.m.m.m.U.v.~.T S.<X*X*X*X*X*X*X*X*X*X*X*X*X:X:X*X*X*X*X*X",
"*X*X=X$X3.J (.U.Y.T.Y.Y.U.Y.Y.Y.Y.Y.Y.Y.U.R.> h.Y.U.Y.Y.T.Y.Y.Y.Y.Y.U.Y.Y.U.^.$.P ).U.Y.Y.T.Y.Y.Y.Y.T.Y.U.Y.Y.Y.Y.: E.Y.Y.T.Y.Y.Y.T.Y.Y.U.Y.Y.U.U.^.E Z.<X%X*X:X*X:X*X*X*X*X*X:X*X*X*X*X*X*X*X;X",
"*X*X:X@XQ > c.7.8.0.8.8.8.8.0.8.8.8.8.0.8.j.- 3.j.8.8.8.8.8.8.0.8.8.8.8.8.8.j.R G g.9.8.8.0.8.8.8.8.8.8.8.8.8.8.q.- 9.0.8.8.8.8.8.8.8.8.8.8.8.8.7.l.I D.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X",
"*X*X;XoX& $ G , n 7 F 7 n 7 F F F F F F > H o > F F F , n 7 F n 7 n n 7 , , H & $ H 7 7 7 F n 7 n 7 n 7 F F 7 7 F o , 7 F F n 7 n 7 F 7 n 7 F F 7 H # H.<X*X*X*X*X*X*X*X*X:X*X*X*X-X*X:X*X:X*X*X",
"*X:X=X#X5.K ).Y.~.~.Y./.~.R.~.Y.R.R.R.Y.R.(.7 k.~.Y.~./.~.Y.~./.R.~.R.~.R.R.).%.U ).Y.R.R.R.~./.Y.~.~.~.Y.~.Y.R.^.: Y./.R.~.R.R.~.R.R./.~.~.R.R.R._.E A.<X%X*X*X*X;X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X&.H Y.c.m.m.m.m.m.m.m.m.m.m.m.v.c.T.: j.m.m.m.m.v.v.v.I.m.m.m.m.m.c.Y.@.L R.c.v.m.c.m.m.m.m.m.v.m.m.v.m.m.: c.m.v.m.m.v.m.m.m.m.v.m.v.v.v.R.R D.<X*X*X*X*X*X:X*X-X*X:X*X*X*X*X*X*X*X*X:X",
"*X*X=X#X2.H ~.c.U.U.m.m.m.m.m.U.m.U.m.U.n.R.> g.U.m.m.U.m.U.M.-.U.m.m.m.m.m.~.@.P ~.m.U.U.m.m.U.U.U.U.m.U.U.m.m.U.: v.U.m.U.m.U.U.m.m.m.m.U.U.U.v.R.T D.1X.X*X*X*X*X*X*X*X*X*X%X%X=X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.m.m.U.U.U.U.U.U.U.m.U.U.U.m.Y.: g.Y.m.m.m.m.T.-.[ s.T.m.m.m.m.~.@.P ~.m.U.U.m.U.U.m.U.m.U.U.m.U.m.U.: v.m.m.m.U.U.U.U.U.m.U.U.U.U.U.R.T S.<X*X*X*X*X:X*X*X*X*X=X<X1X<X;X:X*X*X*X*X",
"*X*X=X#X2.H /.v.U.U.U.m.U.U.m.U.U.U.U.U.m.Y.> g.Y.m.U.m.m.m.| [ o.T.m.m.m.m.Y.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.m.Y.: m.U.U.U.U.U.U.U.U.U.U.U.U.U.v.~.T S.<X*X*X*X*X*X*X:X*X*X*XH.w w {.;X*X*X*X*X",
"*X*X*X#X2.H ~.v.m.U.m.U.U.U.m.U.U.U.m.U.m.Y.> g.U.U.m.m.T.;.[ { { f.T.m.U.m.R.@.P ~.m.U.m.U.U.U.U.U.m.U.m.U.U.m.Y.: m.m.m.U.U.U.U.m.U.U.U.m.m.Y.m.R.T S.<X.X:X*X*X*X*X*X*X*X*X1 X   J.3X=X*X*X*X",
"*X*X*X#X&.H ~.v.U.m.U.U.U.U.U.U.U.U.U.U.m.Y.> g.Y.m.U.U.m.| { { { o.U.m.U.m.R.@.P ~.m.U.U.U.U.m.U.U.U.U.U.m.U.m.U.: m.U.m.U.U.U.m.m.U.U.U.U.U.U.m./.T S.1X*X:X:X:X*X*X*X*X*X.X<XA.  K.>X*X:X*X*X",
"*X*X=X#X2.H ~.v.U.U.m.U.U.U.U.U.m.U.U.U.m.Y.> g.U.m.m.T.-.[ { { { { a.U.m.m.R.@.P ~.m.m.U.U.U.U.U.U.U.U.Y.m.U.U.Y.: m.m.m.U.m.U.m.Y.U.U.U.m.U.U.v.~.T S.<X.X:X*X*X*X*X:X*X*X*X;XC.  J.>X%X:X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.m.U.U.U.U.m.m.Y.> g.T.m.U.M.| { { { { [ o.T.m.m.~.@.P ~.m.m.U.U.U.U.U.U.U.m.m.U.U.m.U.: c.m.m.U.U.U.U.U.U.m.U.U.U.U.m.~.T S.<X*X*X*X*X:X*X*X*X*X*X<XC.  K.<X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.U.m.U.U.U.E.Y.> g.Y.m.T.-.[ { { { { { { f.T.v.Y.@.P ~.m.m.U.U.U.U.m.U.Y.m.m.m.U.m.U.: m.U.m.U.U.U.m.U.U.U.U.U.U.U.v.~.T S.2X*X*X*X*X*X*X*X*X*X*XXXe   B.XX*X*X*X*X",
"*X*X*X#X2.H ~.v.U.m.U.U.m.U.m.U.U.U.U.U.v.Y.> g.m.m.M.| [ { { { { { [ o.T.m.Y.@.P ~.m.m.U.U.m.U.U.U.m.U.U.U.U.U.T.: n.m.U.U.U.m.U.U.U.U.U.m.U.U.U.R.T S.<X*X:X*X*X:X=X:X*X*X:X+   X   1 <X=X=X*X",
"*X*X*X#X2.H ~.v.U.U.m.U.U.U.Y.m.U.U.U.U.I.Y.> g.m.T.-.{ { { { { { { { { s.I.Y.@.P ~.m.m.U.m.U.m.U.m.U.U.U.U.m.m.Y.; m.m.m.U.U.U.U.U.U.U.U.U.U.U.v.R.T S.<X%X*X*X*X:X*X*X*X*X:X.XXX.X.X%X*X*X*X*X",
"*X*X=X#X&.H ~.v.Y.m.U.U.U.m.U.m.U.U.m.U.m.Y.> g.Y.M.} [ { [ [ [ { [ [ [ O.U./.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.m.U.: m.U.U.m.U.U.U.m.U.U.U.m.m.U.v.~.T S.<X*X*X*X*X*X*X*X*X*X*X;X:X;X;X:X*X*X*X:X",
"*X*X=X#X2.H /.I.m.m.U.U.m.m.U.U.U.U.U.U.m.Y.: g.T.a...X.X.O.X.X.O.O.X.X.O.n.Y.@.P ~.m.U.U.U.U.U.m.m.U.U.U.U.U.m.Y.: n.U.U.U.U.U.m.U.U.m.U.m.m.U.m.R.T Z.1X%X:X*X*X:X-X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.G R.c.m.m.m.m.m.m.v.m.v.v.m.v.v.Y.: g.v.I.T.T.I.I.I.T.I.T.I.T.I.v.Y.@.L R.c.n.v.v.v.m.m.m.m.m.v.m.n.v.m.; c.m.v.n.m.v.v.m.m.m.m.m.v.m.v.Y.T Z.<X*X*X*X*X=X*X:X*X*X*X*X*X-X*X*X*X*X*X*X",
"*X*X=X#X3.K ).R./.R.~.Y.~.Y.Y.~.R.R.R.R.Y.).7 k.~.Y.R.Y.R.R./.Y.R.Y.~.Y.R.R.).%.U ).Y.~.R.R.~.R.~.Y.~.Y.R.R./.R.~.> R./.R.R.R.R.~.R.R.R.Y.~./.R.Y.).E A.<X%X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X*X*X:X",
"*X*X;XoX& $ G 7 n 7 , , , , , , 7 n , 7 > G o : F n F F F F 7 n 7 F F F F 7 G & # H 7 7 7 F F F F 7 F F F 7 , , F o , , F F F 7 F F 7 n 7 F F F 7 H # H.<X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X*X*X*X",
"*X*X*X;XG.5 h.9.9.j.j.q.j.j.j.0.j.j.0.8.7.g.- 3.q.8.8.8.8.8.8.8.8.0.8.8.8.9.g.W G g.8.8.8.0.8.8.8.8.8.8.8.8.8.8.j.& 8.8.0.0.8.8.8.8.8.8.8.8.8.8.8.h.I D.<X%X:X*X*X:X*X*X:X*X:X=X:X*X*X*X*X:X*X*X",
"*X*X*X>X].J ^.U.R.l.( t.y.( ( i.t.( v.R.U.~., h.R.T.Y.Y.T.Y.Y.Y.Y.U.Y.Y.T.Y.^.$.P ^.U.Y.Y.U.Y.Y.Y.Y.U.Y.T.Y.U.Y.Y.: U.Y.Y.U.T.Y.Y.Y.Y.Y.U.Y.Y.T.E.(.E Z.1X%X:X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X*X>X].G Y.Y.( l f j k f f j f f z y.U.Y.> g.Y.m.m.m.m.m.U.m.m.m.m.m.m.m.Y.@.P R.m.m.m.m.m.U.m.m.U.m.U.U.U.n.U.: n.U.U.m.m.m.m.m.U.m.m.m.m.U.v.~.T Z.<X=X*X:X*X:X:X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X*X>X].J R.U.B f h h h h h h f h f Z Y.Y.> g.U.m.m.m.U.U.U.U.U.U.U.U.U.m.R.@.P ~.v.U.U.U.U.U.U.U.U.U.U.U.U.U.U.: m.U.m.U.m.m.U.U.U.m.U.U.U.U.m.R.T Z.<X=X*X*X*X*X*X*X*X*X*X-X;X;X-X*X*X*X*X*X",
"*X*X*X;X].H R.Y.B h h h h h h h h h h Z ~.T.> g.U.m.U.U.U.m.U.U.U.m.U.U.U.m.R.@.P ~.m.U.U.U.U.m.U.U.m.U.m.U.U.m.Y.; m.U.m.U.U.U.m.U.U.U.U.m.U.U.m.R.T S.<X*X*X*X*X:X*X*X*X*X*X.X{.{..X;X*X*X*X*X",
"*X*X*X>X].G ^.e.l h h h h h h h h h h N l.R.: g.Y.m.m.U.U.U.U.U.U.U.U.U.m.m.R.@.P ~.m.m.m.U.U.U.U.U.m.Y.U.U.U.m.U.: n.U.m.U.U.U.U.U.m.U.U.U.U.U.I.~.T S.<X&X*X*X=X:X*X*X*X*X*X<     K.;X*X=X*X*X",
"*X*X*X>X].G ^.N f h h h h h h h h h h f D ~.> g.U.m.m.U.U.U.U.m.U.U.U.U.U.m.R.@.P ~.m.m.U.U.U.U.U.U.U.m.U.m.U.m.T.: v.U.m.U.U.U.U.m.U.U.U.U.U.m.m.R.T S.<X*X:X*X*X*X*X*X*X*X*XK.e   J.<X*X*X*X*X",
"*X*X*X>X].J ~.l f h h h h h h h h h h f B ^.: g.Y.m.U.U.U.U.U.U.m.U.U.U.U.m.R.@.P ~.m.U.U.U.m.U.m.U.U.U.U.m.Y.m.U.: v.U.U.U.U.m.U.U.U.U.m.U.U.U.v.~.T S.<X.X:X*X*X:X*X*X*X*X*X1XA.  K.;X*X*X*X*X",
"*X*X*X>X].G (.C f h f h h h f j h f f f ! ^.> g.Y.U.U.U.m.U.U.U.U.U.U.m.U.m.R.@.P ~.m.m.m.U.U.U.m.U.Y.m.U.U.U.m.U.: v.U.m.U.U.U.U.U.m.m.U.U.U.m.v.~.T S.<X*X*X*X=X:X*X:X*X*X*X;XB.  J.3X*X*X*X*X",
"*X*X*X>X].H ^.l.A N V j h h h f l V N ^ v.Y.: g.Y.m.m.U.U.U.Y.m.m.U.U.U.U.v.R.$.P ~.m.U.U.U.m.U.U.m.m.U.U.m.U.m.Y.: n.U.m.U.m.U.U.U.U.m.U.U.U.U.m.R.T S.<X*X*X:X*X*X*X*X*X*X=X1XH.  }.1X.X*X*X*X",
"*X*X*X;X].H ~.m.Y.Y.Y.e.x g g C y.Y.Y.Y.U.Y.> g.m.m.U.U.U.U.m.m.U.U.U.U.U.m.R.@.P ~.v.U.U.U.U.U.U.U.U.U.U.U.U.m.U.: v.U.U.U.U.U.U.m.m.Y.U.U.U.U.m.~.T Z.<X.X*X*X*X*X*X:X*X*X:Xw X   X r >X*X*X*X",
"*X*X*X>X].H ~.v.m.m.m.(.#.y u w.T.m.m.m.v.Y.> g.Y.m.m.U.U.U.U.m.U.U.m.U.U.m.R.@.P ~.v.m.U.m.U.U.U.U.U.U.m.U.U.U.U.: v.U.m.U.m.U.U.U.U.U.U.m.U.U.m.~.T Z.<X*X*X*X:X*X*X=X*X*X:XV.t V.w C.;X*X*X*X",
"=X*X*X>X].H ~.n.U.U.m.T.#.u y :.T.U.E.U.m.Y.> g.U.m.U.U.U.U.U.U.U.U.U.U.U.v.R.@.L /.m.U.U.U.U.U.m.U.U.U.U.U.m.U.U.: m.U.m.U.U.U.U.m.Y.m.U.U.U.U.v.~.T S.<X*X:X*X*X*X*X*X*X*X*X2X1X1X1X<X*X*X*X*X",
":X*X*X>X].J ~.v.U.U.m.T.#.i u :.T.v.U.U.v.R.> g.Y.m.U.U.m.U.m.U.U.U.U.U.U.m.R.@.Y /.m.m.U.U.U.U.U.U.Y.m.U.U.U.m.U.: v.U.U.U.U.U.U.U.m.m.U.U.U.U.m.R.T S.<X.X*X*X*X*X*X:X*X*X*X=X*X&X.X*X*X*X*X*X",
"*X*X*X>XL.H /.v.U.m.m.T.>.) ) j.I.m.U.U.v.Y.: g.m.m.U.U.U.U.m.U.U.U.I.U.v.v.R.@.L ~.v.I.m.m.U.v.m.m.m.m.U.U.I.E.U.; v.m.U.U.E.U.v.m.m.U.m.v.m.m.I.R.T S.<X*X*X*X;X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X",
"*X*X*X>X[.K ^.Y.R.Y.Y.Y.R.R.~.Y.Y.Y.Y.Y.Y.^.> h./.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.R.Y.Y.^.$.Y ).Y.Y.Y.Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.~.5 E.R.~.T.Y.W.R.R.R.R.R.R.R.~.Y.).E S.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X",
"*X*X*X*XF.; 9.&.&.&.5.2.2.2.&.&.&.&.2.=.&.9.= @.6.2.2.2.2.2.2.3.2.2.2.2.2.2.7.L > 8.2.2.2.3.2.2.3.2.2.2.2.2.2.2.6.& &.&.&.&.%.%.&.2.&.&.&.2.&.&.&.9.n A.1X.X*X*X*X*X*X*X:X*X*X=X*X=X*X:X*X*X*X*X",
"*X*X;X|.= < V.r r r N.U r r r r r r U r r V.+ n J H G J H H J J G J H H J J L - % P G J H H H H H J H J J J H H H @ r r r r e %.N.U r r U r r r r V.< G.<X*X*X*X*X*X:X*X*X*X*X:X*X:X*X*X*X;X*X*X",
"*X*X=X#X&.V.1X<X2X<X<X<X2X2X1X1X2X1X2X2X<X1Xt h.(.R.R.~././.R.R.R.~.~./.R.R.).%.U ).R.R.~.~.~.~.~.~.R.~.R.R.~././.0 2X1X2X<X1X1X2X2X2X2X2X2X2X1X<X1XJ.C.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X",
"*X*X=X#X*.r 2X%X*X*X*X%X%X%X=X%X&X&X&X&X%X,Xq p.U.v.v.v.E.v.I.v.v.E.v.v.v.v.Y.@.L R.c.v.c.m.m.m.v.v.v.v.v.v.I.v.m.4 &X.X%X*X*X%X&X&X&X=X&X&X&X=X.X<XC.A.<X*X*X*X:X*X:X*X*X=X:X*X:X*X:X*X*X*X*X*X",
"*X*X=X$X2.N.<X*X:X*X*X*X*X*X*X*X=X*X:X*X*X,Xq p.Y.m.U.m.U.U.U.U.U.U.U.U.U.m.R.@.P ~.m.m.U.U.m.U.U.U.m.U.m.U.U.U.U.3 =X*X*X*X*X*X*X*X*X*X:X*X*X*X%X<XA.C.1X%X*X*X*X*X*X*X*X*X*X*X.X%X*X*X*X*X*X*X",
"*X=X=X$X2.U <X*X*X*X:X*X:X*X:X*X:X:X*X*X*X3Xq p.Y.m.U.U.U.U.U.m.U.U.m.U.U.m.R.@.P ~.m.U.U.U.U.U.U.U.U.U.U.U.U.m.U.9 %X:X*X*X*X*X*X*X*X*X*X*X*X*X*X1XA.A.<X*X*X*X-X*X*X*X*X*X*X>X1X1X;X*X*X*X*X*X",
"*X*X-X$X2.r 1X.X*X*X*X*X*X*X*X:X:X*X*X*X%X<Xq p.U.m.U.U.U.U.U.U.U.m.U.U.m.m.~.@.P ~.v.U.m.U.U.U.m.U.U.U.U.U.U.U.m.3 &X*X*X*X:X*X*X:X;X*X*X*X:X*X%X1XA.A.1X%X*X*X*X*X*X*X*X*X;XB.< 1 }.;X*X*X*X*X",
"*X*X&X@X&.r <X*X*X:X*X*X*X-X*X*X*X*X:X=X*X3Xq p.Y.m.m.U.U.m.U.U.U.U.U.m.U.m./.@.P ~.m.m.U.U.U.m.U.U.U.m.U.U.U.U.m.3 &X:X*X*X*X*X*X*X*X*X*X*X*X*X*X<XC.A.<X*X*X*X:X*X:X*X*X*X=X2 O   J.>X*X*X:X*X",
"*X*X*X$X=.r 1X%X*X*X*X*X*X-X*X*X*X*X=X:X%X<Xq p.Y.m.U.U.U.U.U.U.m.U.U.U.U.m.~.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.U.m.3 =X*X*X*X*X*X*X:X*X*X*X*X*X*X%X<XA.A.<X*X=X*X*X*X:X*X*X*X*X<XA.  K.3X*X*X*X*X",
"*X*X=X#X&.r <X*X*X-X*X*X*X*X*X*X*X*X*X*X*X3Xq p.Y.m.U.m.U.m.U.U.U.U.U.U.m.m.R.@.P ~.m.m.U.m.U.U.U.m.U.U.U.m.m.U.m.9 *X*X*X*X*X*X-X*X*X*X*X*X*X*X*X<XA.A.<X*X*X*X*X:X*X*X*X*X*X<XC.  J.;X*X*X*X*X",
"*X*X=X$X=.r <X*X:X*X*X*X*X:X*X=X=X*X:X*X%X3Xq p.T.m.m.U.U.U.U.U.m.U.U.U.U.U./.@.Y ~.m.U.U.m.m.U.U.U.U.U.m.U.U.U.M.9 &X*X*X*X*X*X*X*X*X*X*X*X*X*X@X<XA.A.<X*X*X*X-X*X*X*X:X*X=X1XA.  L.1X*X:X*X=X",
"*X*X=X#X*.r 2X=X*X*X*X:X*X*X*X:X:X*X*X*X*X<Xq p.M.x.x.x.m.x.x.x.x.x.v.x.x.x.m.@.L m.n.x.x.m.x.x.m.x.x.x.v.x.x.x.x.3 &X*X*X*X*X:X*X:X*X*X*X*X*X=X*X<XA.A.2X*X*X*X*X*X*X*X=X*X*XK.2   e L.:X%X*X*X",
"*X*X*X:X`.}.;X*X*X*X*X-X*X*X*X*X:X*X*X*X*X;XL.'.+XOXOXOXOXOXOXOXOXOXOXOXOXOX+X`.!.+XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXP.*X*X*X*X*X-X*X:X*X*X;X*X*X*X=X;X{.{.;X*X*X*X*X*X*X*X*X*X:XA.B.C.V.H.>X*X*X*X",
"*X*X*X*X,X;X*X*X:X*X:X*X*X*X:X*X*X*X*X*X*X*X;X-X-X-X-X:X-X-X-X-X-X-X-X-X-X-X-X;X,X=X-X-X-X-X-X:X-X:X-X:X-X-X-X-X=X3X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X;X;X*X*X*X*X*X*X*X*X*X*X*X<X1X<X1X>X*X*X*X*X",
"*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X=X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X:X-X*X:X*X*X*X*X*X*X*X=X*X*X*X*X*X;X*X*X*X*X*X-X=X*X%X*X*X*X*X*X*X",
"*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X=X*X*X*X*X*X*X:X*X=X*X*X*X*X=X*X*X:X*X*X*X*X*X*X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X:X*X*X*X*X*X*X:X*X-X*X*X*X:X*X*X;X*X*X*X:X*X:X*X:X*X:X*X*X*X*X:X*X*X*X*X*X*X:X:X*X:X*X*X=X:X*X*X*X*X:X*X*X*X*X:X*X*X*X*X*X:X*X*X*X*X-X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X:X*X*X*X*X*X*X:X*X",
"-X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X:X*X=X*X*X*X*X*X*X*X*X*X*X*X:X*X:X=X*X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X:X*X*X*X*X",
"*X*X*X*X*X*X*X*X:X*X:X*X*X*X:X*X:X*X*X*X*X:X*X=X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X*X=X:X*X*X:X:X*X=X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X:X*X*X",
"*X:X:X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X:X=X*X*X*X:X=X*X*X*X*X*X*X:X*X*X*X=X*X*X*X*X*X*X:X:X*X*X*X*X:X-X*X*X*X;X*X*X:X*X*X:X*X-X*X*X*X:X-X*X:X*X:X*X*X*X*X*X-X*X*X*X*X*X*X*X"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 200 2 ",
"   c #020202",
".  c #0E0E0E",
"X  c #121212",
"o  c #2A2A2A",
"O  c #242424",
"+  c #3A3A3A",
"@  c #344A25",
"#  c #3C572B",
"$  c #3C4636",
"%  c #6C7600",
"&  c #676E00",
"*  c #415C2E",
"=  c #4A6A35",
"-  c #486733",
";  c #567B3D",
":  c #597E3F",
">  c #537C37",
",  c #5A5A59",
"<  c #4B4E49",
"1  c #597E41",
"2  c #5A6553",
"3  c #576B49",
"4  c #66785B",
"5  c #69795E",
"6  c #66755B",
"7  c #616F58",
"8  c #686868",
"9  c #6B7C61",
"0  c #747474",
"q  c #7E7E7E",
"w  c #965C00",
"e  c #985500",
"r  c #924C00",
"t  c #A15500",
"y  c #836A00",
"u  c #9A6601",
"i  c #9B7C14",
"p  c #A16200",
"a  c #279B00",
"s  c #00AD00",
"d  c #01B300",
"f  c #0AB507",
"g  c #0AB707",
"h  c #13BA0D",
"j  c #1DBC14",
"k  c #7B9418",
"l  c #27C21C",
"z  c #35C926",
"x  c #38C928",
"c  c #4BD335",
"v  c #4BD336",
"b  c #53D73B",
"n  c #55C62F",
"m  c #5C8442",
"M  c #638547",
"N  c #628C46",
"B  c #64824F",
"V  c #638B48",
"C  c #679349",
"Z  c #69954B",
"A  c #6B984D",
"S  c #659446",
"D  c #6F9A50",
"F  c #6E9750",
"G  c #719A51",
"H  c #668352",
"J  c #72A252",
"K  c #7AAE56",
"L  c #79AD56",
"P  c #79B154",
"I  c #7DB259",
"U  c #75AE4E",
"Y  c #718266",
"T  c #5AD940",
"R  c #66DB47",
"E  c #6CE34D",
"W  c #7AE657",
"Q  c #9C831C",
"!  c #A6861E",
"~  c #9F972C",
"^  c #81A225",
"/  c #A1A436",
"(  c #A8972C",
")  c #CDAE00",
"_  c #CBB301",
"`  c #CAB708",
"'  c #C9BB0E",
"]  c #C8BE16",
"[  c #C7C018",
"{  c #C7C017",
"}  c #C4C927",
"|  c #C4CA28",
" . c #C5C623",
".. c #C1D439",
"X. c #C2D135",
"o. c #C2CF32",
"O. c #83B35D",
"+. c #83BB5E",
"@. c #86B560",
"#. c #87BA61",
"$. c #88B861",
"%. c #93D258",
"&. c #AACC57",
"*. c #B3D354",
"=. c #83EB5E",
"-. c #81E65C",
";. c #B7E75C",
":. c #BAE456",
">. c #87C060",
",. c #8ECC65",
"<. c #89C362",
"1. c #91CF67",
"2. c #92CF69",
"3. c #9BCF6F",
"4. c #91D464",
"5. c #94D26A",
"6. c #9BDA6F",
"7. c #9ED273",
"8. c #ACDC64",
"9. c #89EA62",
"0. c #96EC6B",
"q. c #93FD69",
"w. c #99FE6D",
"e. c #98F36C",
"r. c #9EE171",
"t. c #9DF471",
"y. c #8EFB65",
"u. c #AEE56B",
"i. c #A6E86B",
"p. c #B9EC61",
"a. c #B3E96A",
"s. c #B5F36E",
"d. c #A5EB76",
"f. c #A7EF78",
"g. c #AAED7A",
"h. c #A8E972",
"j. c #B2EA7C",
"k. c #A1F473",
"l. c #A5FD76",
"z. c #ABFA76",
"x. c #ADF67B",
"c. c #AEFC7A",
"v. c #A9F877",
"b. c #B4F471",
"n. c #B1FC7E",
"m. c #B3F57E",
"M. c #A6F96E",
"N. c #858683",
"B. c #8B8B8A",
"V. c #868985",
"C. c #999999",
"Z. c #9BB28C",
"A. c #A3A3A4",
"S. c #A5A0A8",
"D. c #ADADAD",
"F. c #AAA3AF",
"G. c #B4B4B4",
"H. c #BBBBBB",
"J. c #AFD396",
"K. c #AFFF84",
"L. c #B4F481",
"P. c #B3FF80",
"I. c #BBFF85",
"U. c #B3FF88",
"Y. c #BFFF89",
"T. c #BDFF90",
"R. c #C3FF8C",
"E. c #C8FF8F",
"W. c #C0FF87",
"Q. c #CCFF91",
"!. c #C1FF92",
"~. c #C7F2A9",
"^. c #C8F4AA",
"/. c #CEFDAD",
"(. c #BDB7C2",
"). c #BEB8C3",
"_. c #BAAFC1",
"`. c #C2BCC6",
"'. c #C3BBC8",
"]. c #C4C3C4",
"[. c #CACACA",
"{. c #D8D2DC",
"}. c #D7D6D8",
"|. c #D0CFD1",
" X c #DFE3DD",
".X c #E1E7DD",
"XX c #DFD8E3",
"oX c #E6E6E6",
"OX c #E7E6E8",
"+X c #EAE6ED",
"@X c #ECEBEC",
"#X c #E7EBE4",
"$X c #E9F2E3",
"%X c #EFF1EE",
"&X c #EFECF1",
"*X c #ECE7F0",
"=X c #F0EEF2",
"-X c #F3F3F3",
";X c #FAFAFB",
":X c #F0F1EF",
/* pixels */
"oXoXoXoXoXOXoXoXOXoXoX#XoXoXoXOXoXoXoXoXoXoXoXoXoXoXOXOXOXOXOXoXoXoXoXoXoXoXoXOXoXoXoXOXOXOXOX#XoXoXoXoXoXoXoXoXOXoXoXOXoXOX#XoX#XoXoXoXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXOXoXOXoXoXOXoXOXoXoX#XOXoXoXoXoXoXoXoXOXoX#XoXoX#XoXoXoXoXoXoXoXoXoXoXoXOXoX#XOXOXoXoXoXoXoXoXoXOXoXOXoXoXoXOXoXoXoXOXOXoXoXoXoXoXoXoXoXoX#XoXoXoXoXoX@XoXoX@XoXoXoX",
"oXoXOXOXoXoXoXoXoXoXoXoX#XoX#XoXoXOXoXoXoXOX#XoXOXoXoXoXoXoXoXoXoXoXOX#XoXoXoXoXoXoXoXoXoXoXoXoX#XOXoXoXoXoXoXoXoX#XoXoXoXOXoXoXoXOXoXoXoXOX#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oX#XOXOXoXoXoXoXoX#XOXoXoXOXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoXoXOXOXoXoXoXoXoXOXOXoXoXoXoXoXOXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XoXoXoXoXoXoXoXoXoX.XoXoX.X#XoXoXoXoXoXOXoXOXoXOXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoX@X@X:X@X@X:X@X@X@X%X%X@X%X&X@X%X@X@X%X%X%X%X:X%X%X@X:X:X@X:X@X%X:X%X%X@X%X:X@X%X@X%X@X:X%X@X:X%X@X@X%X:X@X:X@X%X%X%X%X%X%X%X@X=XOXoXoXoXOXOXOXoXoX#XoXoXoXoXoXoX@XoXoXoX",
"oXoXoXoX`.].(.`.).).(.'.(.'.`.H.).).).(.`.].).).H.(.(.(.(.).).).).).).(.].`.H.`.).).).(.).).).).).).).(.].`.(.(.H.(.`.(.H.`.(.(.`.(.`.(.|.OXoXoX#XoXoXoXoXoXOXOXoXoXoXoXoXoXoXoX",
"oXoXOX.Xm # J Z A A A A A Z A Z A A A J = = G A A F G A A G A A D Z A J * ; G Z A A A A A A A A A A Z J # M A A A G F F F F A G A Z A N 2 @XoXoXoXoXoXoXoXoXoXoXoXoXoX@XoXoXoXoX",
"oXoXOX$X7.Z Q.I.Y.W.W.Y.W.W.W.Y.Y.Y.I.Q.O.O.Q.I.E.c.c.I.c.c.Y.c.n.Q.Y.Q.F 3.Q.I.W.W.W.W.W.W.W.W.W.W.Y.E.B g.R.E.W.l.P.P.l.n.I.z.Y.R.Y.I.5 +XoXoXoXoXoXoXoXoXoXOX@XoXoXoXoXoXoXoX",
"oXoXOX$X2.C Y.x.c.n.n.n.n.x.n.n.n.n.x.Y.K K Y.x.b d g j d d j d d R L.I.Z 1.U.n.n.x.c.L.x.n.n.n.n.n.x.P.m d.P.t.l s j h s h j d j 0.P.v.5 +XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoX$X3.Z Y.n.P.P.n.U.:.X.U.n.P.n.c.Y.O.I E.9.s d d d d d d d s f t.W.Z 4.I.P.n.n.P.U.} ;.U.n.L.P.n.I.m d.W.v s d d s d d d d s x W.z.5 +X.XoXoXoXoXoXoXoX#XoX:X=XoXoXoXoXoXoX",
"oXoXOX$X5.Z Y.K.n.n.P.n.' _ b.P.n.P.n.Y.I L Q.9.d d d d d d d d d d k.E.Z 1.I.n.P.n.K.p.) | P.n.P.n.n.I.m d.Q.v s d f d d d d d d z R.z.5 +X#XoXoXoXoXoXoXoXoX}.].`. X#XoXoXoXoX",
"oXoXoX$X5.Z W.L.n.n.U.:.) ) ..U.n.P.n.Y.I L W.c s d d d d d d d d d R E.A 1.I.n.n.n.P.} ) _ p.U.n.P.n.Y.m g.l.j d d d d d d d d d j e.n.5 @XoXoX@XoXoXoXoXoX@X0 X . o ].@XoXoXoX",
"oXoXoX$X5.Z R.c.n.n.n.] ) _ ` s.P.n.n.Y.I @.w.s d d d d d d d d d d d n.D 1.I.n.n.U.p._ _ ) | I.n.n.c.Y.m g.b s d d d d d d d d d s x n.4 @XOXoXoXoXoXoXoXOXOX[.-XA.  C.=XoXoXOX",
"oXoXoX$X5.Z W.n.n.U.:.) _ _ ) ..U.n.n.Y.I @.q.s d d d d d d d d d d s l.D 1.I.n.n.U.} _ _ _ _ p.U.n.n.I.m m.v s d d d d d d d d d s x n.4 OXoXoXoXoXoXoXoXoXoXoX, X +  XoXOXOXoX",
"oXoXoX$X5.Z W.n.n.n.] _ _ _ _ ` b.P.n.Y.I K Y.x d s d d d d d s d s c E.Z 1.I.n.U.;._ _ _ _ _ } P.n.n.I.m x.e.h d d s d d d s d s g =.n.5 +XoXoXoXoXoXoXoXoXoX@XG.0   C.-X.XoXoX",
"oXoXOX$X2.Z Y.n.U.:.) _ _ _ _ _ ..U.n.Y.I L W.n.-.=.T g d d g R 9.9.L.W.A 2.I.n.U.} _ _ _ _ _ _ p.P.c.I.N d.Y.k.W 9.z d d d l =.-.t.Y.z.4 @XoXoXoXoXoXoXoXoXoXq D.B.  B.-X XoXoX",
"oXoXoX$X5.Z Y.c.n.] ) _ _ _ _ _ ` s.K.I.I I Y.n.Y.I.Y.%.% % i.Y.I.Y.c.W.A 2.P.K.;._ _ _ _ _ _ _ | U.n.I.m d.P.P.Y.Y.I.^ & k P.Y.W.P.n.c.5 @XoXoXoXoXoXoXoXoXoX8 O o 0  XOXoXoX#X",
"oXoXoX$X5.Z W.K.:.) _ _ _ _ _ _ ) ..U.Y.I K Y.n.n.n.U.&.t p u.P.c.P.n.W.Z 2.Y.U.| _ _ _ _ _ _ _ _ p.K.I.m d.P.n.c.n.U.( t ! U.n.n.n.P.z.5 @XoXoXoXoXoXoXoXoXoX:X=X-X-X+XoXoXOXOX",
"oXoXoX#X5.C R.x.] ) _ ) ) ) ) ) ) _ s.Y.I K W.c.P.n.U.&.e u u.U.c.P.n.W.Z 1.U.;.) ) ) ) ) _ ) ) ) } P.I.m d.I.n.n.n.U.~ r Q P.n.P.n.P.z.4 +XoXoXoXoXoXoXoXoXoXoXoXoX XoXoXoXOXoX",
"oXoXOX$X2.C W.x.;.;.;.;.;.;.;.;.;.:.v.I.I L Y.x.c.c.U.8.i Q h.P.c.K.x.Y.Z 1.I.s.;.;.;.;.;.;.;.;.;.;.x.I.m d.P.n.K.L.U./ i / K.x.n.n.n.v.6 +XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXOX$X7.F Q.Y.T.Y.T.T.T.T.T.T.T.T.Y.Q.@.@.Q.Y.Y.Y.Y.Y.!.R.W.Y.R.Y.I.Q.G 3.E.I.Y.T.T.T.T.Y.T.T.T.T.I.E.B g.W.Y.Y.Y.Y.R.R.R.Y.W.W.Y.Y.I.5 +XoXOXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXOX.XC - @.L P K I I K K I K K K L +.; ; @.K I L I P L L P K L I L +.= N +.L K I K K P I L I L K K +.* J O.I P I I P L K K K P I O.U 2 =X XOXoXoXoXoXOX#XoXoXoXoXoXoXOX#XoXoX",
"oXoXOX.XA = #.I O.I I I I O.I I I I I #.1 1 >.K I $.@.O.$.$.O.$.$.I I +.= C +.I O.I I O.O.I I I I I I $.* J I I I I I I O.I O.I I I O.K 2 @X.XoXoX@XoXoXOXOXoXoXoXoXoXoXOXOXOXoX",
"oXoXOX$X7.F Q.Y.Y.Y.Y.Y.W.W.W.Y.Y.Y.I.Q.@.O.Q.Y.Y.q.e.l.y.q.l.w.w.W.Y.Q.F 3.E.I.W.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.E.B g.E.W.Y.Y.Y.Y.Y.Y.Y.Y.W.W.W.I.5 +XoXoXoXoXoXOXoXoX#XoXoXoX#XoXoXoXoXoX",
"oXoXoX$X2.C Y.x.c.K.n.c.n.n.n.n.L.c.K.I.I K Y.x.x s s f s s g s s b x.Y.Z 1.Y.x.n.n.n.n.n.c.n.n.c.n.x.Y.m d.n.n.P.c.P.c.c.c.n.K.n.n.P.z.5 +XoX#XoXoX#XOXoXoXoXoX XoXoXOXoXoXOXoX",
"oXoXOX$X5.Z Y.L.P.n.P.P.n.P.n.P.n.P.c.Y.I K Q.-.s d d d d d d d s d e.W.Z 1.Y.n.P.P.P.P.P.P.P.P.n.n.n.P.M d.P.P.P.P.P.P.P.P.n.P.I.n.n.z.5 +XoXOXoXoXoXoXoXoXoX+X-X-X+XOXoXoX#XoX",
"oXoXoX$X5.Z Y.c.P.P.P.P.P.P.P.P.P.P.n.Y.I L Q.9.d d d d d d d d d f k.E.Z 1.I.n.P.n.P.P.n.P.n.P.P.P.n.I.m d.P.n.P.P.n.P.n.P.n.P.n.n.n.c.5 +X.XOXoXoXoXoXoXoXOX|.A.C.|.@XoXoXoXoX",
"oXoXoX$X2.Z Y.n.P.P.P.n.P.P.P.P.P.P.n.Y.I I Y.z d d d d d d d d d d v E.A 4.Y.n.P.n.P.n.P.n.P.P.P.P.n.Y.m d.P.P.n.P.n.P.P.P.n.P.P.n.P.c.6 +XoXoXoXOXOX#XoX X:XB.X   A.=X XoXoXoX",
"oXoXoX$X5.Z Y.L.P.n.P.P.P.P.n.P.n.P.c.Y.I O.q.s d d d d d d d d d d s l.A 1.I.n.P.P.P.P.P.P.P.n.n.P.n.I.m d.I.n.P.P.P.P.P.P.P.P.P.n.P.n.5 +XoXoXoXOXoXoXoXoXoXoXH.  A.=XoXoXoXOX",
"oXoXoX$X2.Z Y.x.P.P.P.n.n.P.n.P.P.n.n.Y.I O.w.s d d d d d d d d d s d n.D 1.I.n.n.P.n.P.P.n.P.P.P.P.c.Y.m d.P.P.P.P.P.P.P.n.n.P.P.n.n.c.5 +XoXoXoXoXoXoXoXoXoX-XH.  S.%XoXoXoXoX",
"oXoXOX$X5.A Y.K.P.n.P.P.P.P.P.P.P.P.n.Y.I I W.b d f d d d d s f d f R E.Z 1.I.n.P.P.P.P.P.P.P.P.P.P.c.I.M h.I.n.n.P.n.P.P.P.P.P.n.n.n.c.5 @XoXoXoXoXoXoXoXoXoX-X[.  G.;X XOXoXoX",
"oXoXOX$X5.Z W.x.n.P.n.P.P.P.P.P.P.P.K.Y.I K W.I.t.k.W j s d l 9.t.k.L.W.A 1.I.n.P.P.n.P.P.n.n.P.P.n.n.Y.m f.U.n.P.P.P.P.P.P.P.P.P.n.P.c.5 @XoXoXoX#XoXoXoX X@XH.,   < D.&XoXoXoX",
"oXoXoX$X5.Z Y.n.P.P.P.P.P.n.P.P.P.P.c.Y.I K Y.n.P.U.Y.&.y y u.Y.I.P.c.Y.A 5.I.n.P.n.P.P.P.P.P.P.P.P.n.I.m g.P.n.P.P.n.P.P.n.P.n.P.P.P.n.5 +XoXoXoXOXoXoXoXoX=XC.+ , + B.-XoXoXoX",
"oXoXOX$X5.Z Y.K.P.P.P.P.n.P.P.n.n.P.c.Y.I I W.x.P.n.U.&.w u u.P.n.n.n.Y.A 1.I.P.P.P.P.P.P.P.P.P.P.P.c.I.m d.P.P.n.P.n.P.P.P.P.P.n.n.n.c.5 +X.XoXoXoXoXoXoXOX.X=X;X;X;X=XoXoXoXoX",
"oXoXOX$X5.Z Y.L.n.P.n.P.P.P.P.n.P.P.L.Y.I I I.K.n.n.U.&.e e u.U.n.P.n.Y.A 1.I.c.P.P.P.P.n.P.P.n.P.P.P.I.m d.P.P.P.P.P.P.n.P.n.P.P.n.n.c.5 +X#XoXoXoXoXoXoXoXoXoXoX X XoXoXoXoXoX",
"oXoXoX$X2.Z Y.x.n.L.n.n.n.n.x.n.n.n.x.I.I L I.x.n.n.P.8.~ / h.P.c.L.x.I.Z ,.U.x.n.n.c.L.n.n.n.n.c.c.c.I.m d.P.c.x.n.n.n.n.n.n.n.n.c.L.x.6 +XoXoXoXOXoXOXOXOXOXOXoXoXOXOXoXoXoXoX",
"oXoXOX$X7.F Q.I.W.W.Y.Y.Y.Y.W.Y.Y.Y.Y.Q.@.O.Q.Y.W.W.Y.Y.!.!.W.W.Y.Y.I.Q.G 3.Q.W.W.W.Y.Y.Y.Y.Y.W.Y.R.I.Q.M j.R.Y.W.Y.Y.Y.R.R.W.W.Y.Y.Y.P.5 +XoXoXOXOXoXoXoX#XOXoXoXoX#XOXoXoXoXoX",
"oXoXOX X1 # J C S Z Z Z Z Z Z Z Z Z C A - - D Z Z Z Z Z C C Z Z A Z C J # ; A Z Z C Z Z C Z Z Z Z Z C A @ V A Z Z Z Z Z Z Z C Z Z Z A N , %X XOX#XoXoXoXoXoXoXoXoXoXoXOXoXoXoXOX",
"oXoXoX#XK ; r.4.5.5.5.5.5.5.4.5.4.5.5.r.Z C r.1.5.5.5.5.4.5.5.5.5.5.5.r.; L 6.5.4.5.5.5.5.4.5.5.5.5.1.6.= <.5.5.5.4.4.5.5.5.5.5.5.5.2.%.7 @X.XoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoX",
"oXoXoX#X7.A E.L.W.Y.I.I.I.I.W.Y.I.I.P.E.O.O.E.L.Y.I.I.P.Y.Y.I.I.U.I.I.E.F 3.W.I.I.I.I.I.Y.I.I.I.I.I.I.W.M g.W.Y.I.I.Y.P.Y.Y.P.Y.W.W.Y.n.5 @XoXoX#XOXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoX$X5.C Y.c.n.n.n.n.n.n.n.n.n.P.x.Y.I I Y.c.n.n.n.P.s.b.P.n.n.n.x.Y.A 1.I.n.n.n.n.n.P.n.n.n.P.L.c.I.M d.n.n.n.n.n.n.n.n.n.n.n.n.n.c.5 +XoXoXoXOXOXoXoXoXoX.XoX XoXoXoXoXoXOX",
"oXoXoX$X5.Z Y.L.n.P.P.n.n.P.P.P.P.n.n.Y.I I Y.n.n.n.n.U.[ o.U.n.n.n.n.Y.A 1.I.n.n.P.P.n.P.n.n.P.P.P.n.I.m d.I.n.P.P.n.P.P.P.n.P.n.n.n.c.5 @X#XoXoXoXoXoXoXoXoX@X-X;X+XoXoXoXoXoX",
"oXoXoX$X5.Z Y.K.P.P.P.P.P.n.P.n.P.P.n.Y.I L Y.n.n.n.U.p._ ` b.P.n.n.n.Y.A 2.P.K.P.P.P.P.P.P.P.P.P.n.c.Y.m d.P.n.P.P.P.P.n.P.n.P.n.n.n.c.5 +XoXoXoXoXoXoXoXoX@X).0 0 ].@XoXoXoXOX",
"oXoXoX$X5.Z Y.c.P.P.P.P.P.P.n.P.P.n.K.Y.I I Y.n.n.n.P.} _ ) ..U.n.n.n.W.A 1.I.P.P.P.P.P.n.P.n.P.P.P.c.I.m f.P.P.n.P.n.P.P.P.n.P.n.n.I.c.6 +XoXoXoXoXoXOXoXoX%XC.o   A.-XoXoXoXoX",
"oXoXOX$X5.Z Y.L.P.n.n.P.n.P.P.P.P.n.n.Y.O.P Y.c.n.K.p._ _ _ ` s.P.n.n.W.A 1.I.P.n.P.P.n.P.P.P.P.P.n.P.I.m d.P.n.P.P.P.P.P.P.P.P.n.n.n.c.5 +XoXoXoXoX#XOXOXoX X=X].  A.-XoXoXoXoX",
"oXoXOX$X5.Z Y.K.P.P.P.P.P.P.n.P.P.n.c.Y.I I Y.L.P.U.} ) _ _ ) ..U.n.n.W.A 1.I.c.P.n.P.P.P.P.P.P.P.P.K.I.m f.I.P.P.P.P.P.P.n.n.P.I.n.n.c.5 +XoXoXoXoXoXoXOXoXoX@XG.  A.-X.XoXoXoX",
"oXoXOX$X5.C Y.c.P.n.P.P.n.P.P.P.P.P.n.Y.I P Y.n.U.;._ _ _ _ _ ` s.U.n.W.A 1.I.L.P.P.P.P.n.P.n.P.P.P.c.I.M h.P.n.n.P.n.P.P.P.P.P.n.n.n.z.5 @XoXoXOXoXoXoXoX+X X-X[.  G.;X XoXoXOX",
"oXoXoX$X5.Z R.x.P.P.P.n.P.P.n.P.n.P.n.Y.I I Y.c.U.} _ _ _ _ _ ) ..K.L.W.Z 1.I.n.P.P.P.P.P.n.P.n.P.P.n.I.m d.P.P.P.P.n.P.P.P.P.P.n.n.P.c.5 @XoXoXoXoXOXoXoX X=XA.o   O C.=XoXoXoX",
"oXoXoX$X5.C Y.K.P.n.P.P.P.P.P.P.P.P.n.W.I I Y.K.;._ _ _ _ _ _ _ ` s.K.W.A 1.I.n.n.P.n.P.P.P.P.P.P.n.n.I.m d.P.P.P.P.P.P.P.n.n.P.P.P.P.n.5 +X.XoXoXOX#XoXoXoX@XG.0 N.8 A.@X.XoX@X",
"oXoXoX$X5.A Y.n.P.P.P.n.P.n.n.P.n.P.n.Y.I L W.L. .) _ _ ) _ ) _ ) X.K.W.A 1.W.n.P.P.n.P.P.P.P.P.P.P.n.I.M d.P.n.P.P.P.P.P.P.P.P.n.n.P.c.5 @XoXoXoXoXoXoXoXoXoX=X;X;X;X=XoXoXoXoX",
"oXoXoX$X5.C Y.c.P.n.P.P.P.P.P.P.n.n.n.W.I I Y.s.' ' ' ' ' ' ' ' ' [ b.W.A 1.I.n.P.P.P.P.P.n.n.n.P.P.c.I.m g.P.n.n.P.n.P.P.P.n.P.P.n.P.c.5 +XoXoXoXoXoXoXoXoXoX X X X XoXoXoXoXoX",
"oXoXOX$X2.C Y.x.n.c.n.n.n.n.n.n.n.n.x.Y.I L W.x.n.n.n.n.n.c.P.c.n.n.x.Y.Z 1.P.n.n.n.n.n.n.n.n.n.P.n.L.U.m d.n.n.n.n.n.n.n.n.n.n.n.n.n.z.6 +XoXoXOXOXoXOXOXOXOX#X+XoXoXoXoXoXoXoX",
"oXoXoX$X3.Z E.I.I.I.I.I.Y.I.I.I.P.Y.I.E.O.O.E.U.I.I.I.I.I.I.I.I.I.I.L.E.Z 3.E.P.Y.I.Y.P.I.I.I.I.I.I.L.R.M g.Y.I.I.Y.P.I.W.I.I.I.I.I.I.n.5 OXoXoX#XOXoXoXoX#XOXoXoXoXoXoXoXoXoXoX",
"oXoXOX X3 @ V m m m m m m m m m : m m N * * N m m m m m m m m m m m m S # = N m m m m m m m m m m m m N @ ; m m m m m m m m m m m m N > 2 +XoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoX",
"oXoXoX@X_.V P.d.g.m.L.g.m.m.m.m.L.v.d.n.L J P.f.f.f.f.f.f.f.f.f.f.f.d.P.N +.n.f.f.f.f.f.f.f.g.x.f.f.d.c.; 6.x.d.f.f.f.f.f.f.f.f.f.f.g.i.6 +XoXoXoXoXoXoXoXoXoXoXoXOXoXoX@XoXoXoX",
"oXoXoX%X'.Z W.L.l.b v E v c E b c e.P.W.O.K W.L.P.P.P.P.P.P.P.P.P.U.L.R.A 1.Y.P.P.P.P.P.I.P.P.P.P.P.P.Y.M g.I.P.P.P.P.I.P.P.P.Y.I.n.I.n.5 @XoXoXoXoXoXoXoXoX#XOXoXOXoXoXoXoXoXoX",
"oXoXoX%X'.A R.x.l s s d s s s d s h e.W.I K Y.c.P.P.P.n.P.P.P.n.n.n.n.W.A 1.I.P.P.n.P.P.n.P.n.n.P.P.c.I.m h.P.n.n.n.P.n.n.n.n.n.n.n.n.c.4 +XoXoXoXoXoXoXoXoXoXoXoX XoXoXoXoXoXoX",
"oXoXoX@X'.A R.t.d d d d d d d d f s W Q.I K Y.K.P.P.n.P.P.P.P.P.n.P.n.W.A 1.I.n.P.n.P.P.P.n.P.P.P.P.n.I.m d.Y.n.P.P.P.n.P.P.n.P.I.n.n.z.5 +X#XoXoXOXoXoXoXoXoX@X;X;X+XoX#XOXoXoX",
"oXoXoX%X`.C E.0.f d d d d d d d d s W Q.I I W.L.P.P.P.P.P.P.n.P.P.P.n.W.A 1.I.n.P.P.n.P.P.P.P.P.P.P.n.Y.m d.P.n.P.n.P.P.P.n.P.P.n.n.n.c.5 @X.XoXOXOXoXoXoXoX@XD.< + H.@XoX+XoXoX",
"oXoXoX@X'.A I.l d d d d d d d d d d h l.O.K W.n.P.P.n.P.P.P.n.P.P.P.n.Y.A 1.I.K.n.P.P.P.P.P.P.P.P.P.n.I.m d.P.n.P.P.P.P.n.P.P.n.n.n.I.c.6 +XoXoX#XoXoXoXoXoX@XA.<   A.=XoXoXoXoX",
"oXoXoX%X'.F l.s d d d d d d d d d d s y.$.L W.n.P.P.P.P.P.n.P.P.P.P.c.Y.A 1.P.n.P.P.P.n.P.P.P.P.P.P.c.I.m d.P.P.P.P.n.P.P.P.P.P.n.I.n.c.5 +XoXoXoXoXoXoXoXoX X-X[.  A.=X XoXoXoX",
"oXoXoX%X`.Z I.j d d d d d d d d s s d l.O.I W.n.P.n.n.P.P.P.P.P.P.P.n.Y.A 1.Y.n.P.P.P.P.n.P.P.P.P.P.L.I.m h.I.n.n.I.n.P.n.P.P.n.n.n.n.z.5 +XoXoX#XOXoXoXoXoXoX@XG.  A.=XoXoXoXoX",
"#XoXoX@X`.A W.0.x z l d d d d j z z =.E.I L R.n.P.P.P.P.P.P.n.P.P.P.c.Y.A 1.Y.n.n.P.P.n.P.P.P.P.P.P.c.I.M g.P.n.n.n.P.P.P.P.P.P.n.n.n.c.5 +XoXoXoXOXoXOXoXoXoX-X].  D.;X XoXoXOX",
"oXoXoX@X).Z Y.L.W.W.c.R a a n v.W.Y.L.Y.O.I Y.n.P.P.P.P.n.P.P.n.P.P.n.Y.A 1.I.n.P.P.n.P.P.P.P.n.n.n.n.P.M d.P.n.P.P.P.P.P.P.P.P.n.n.n.c.9 +X#XoXoXoXoXoXoXoX-XB.X   . q -XoXoXoX",
"oXoXoX%X].Z Y.c.n.n.U.a.t t &.U.n.n.c.Y.I I Y.c.P.P.P.P.P.P.P.P.n.P.n.Y.A 1.I.n.P.P.P.P.n.P.n.I.P.P.n.Y.m d.P.n.n.P.P.n.P.n.P.P.P.P.n.z.5 @XoXoXoXoXoXoXoXoX#X].A.D.C.H.#XoXoXoX",
"oXoXoX%X'.Z Y.n.n.n.P.u.u w &.U.n.P.n.Y.I K Y.c.P.P.P.P.P.P.P.n.P.P.n.Y.A 1.I.P.P.P.n.P.P.P.n.n.P.I.n.I.M h.I.n.P.P.n.P.P.P.P.P.P.n.I.c.5 +X.XoXoXoXoXoXoXoXoX@X-X=X;X=XoXoXoXoX",
"oXoXoX@X'.Z Y.n.n.n.U.u.u e &.U.n.n.c.Y.I K W.n.n.n.n.n.n.n.P.n.n.n.n.Y.Z 1.I.n.n.P.n.n.P.n.n.n.n.n.n.I.m f.P.n.n.P.n.n.n.n.n.n.n.n.n.n.5 +XoXoXoXoXoX@XoXoXoXoXoXoX XoXoXoXoX@X",
"oXoXoX%X`.Z R.L.P.P.U.n.8.8.b.U.P.P.L.W.O.I Y.n.n.n.n.n.P.n.n.P.P.P.n.W.A 1.I.P.P.P.P.P.n.P.n.n.n.n.n.W.m f.U.n.P.P.U.P.P.P.U.P.P.P.P.n.5 +X#X#XoXoXoXoXoXoXoXoXoXoXoXoXoX@XoXoX",
"oXoXoX@X'.N n.v.z.z.z.z.K.c.x.z.z.z.v.P.P L Y.x.n.n.n.x.n.n.x.n.n.x.x.Y.Z ,.P.x.c.n.x.x.n.n.n.x.n.n.x.P.m i.n.z.z.z.z.z.z.z.z.b.z.z.z.M.6 +XoXoXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoX",
"oXoXOX.X3 $ Y 5 9 5 5 9 5 5 5 5 9 5 5 Y < # N m m : 1 M m m m : m m ; N @ = m m 1 m 1 M : m : M m ; 1 M + 6 5 5 5 9 9 9 5 9 5 9 9 5 9 7 , @X XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXOX$X4.B.;X+X*X+X*X*X@X@X+X@X+X*X+X;XF.P W.n.n.I.P.P.P.I.P.P.P.P.L.E.A 2.Y.L.P.P.P.P.P.I.P.P.P.P.n.P.M XX:X@X*X*X+X@X*X+X@X+X&X+X@X+X0 +XoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoX",
"oXoXoX$X4.N.-XoXoXoXoX XoXoX.XoXoXoXoX-XS.L Y.x.n.n.n.n.n.n.n.P.n.n.n.Y.A ,.I.P.n.n.P.n.n.n.n.n.P.n.n.I.B {.#XoX.XoXoXoXoXoX#XoXoXoXoX X0 oX#XoXoXoXoXOXoXoXOXoXoXoXoXoXOXoXoXoX",
"oXoXOX$X4.N.-XoXoXoXoXoXoXoXoXoXoXoX.X-XS.P W.n.P.n.P.P.P.P.n.I.P.n.n.Y.A 1.I.c.I.P.P.n.I.P.P.P.P.P.n.I.B {.oX#XoXoXoXoXoXoXoXoXoXoX+X X0 +XoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXOX",
"OXoXOX$X4.N.-XoXoXoXoXoXoXoXOXOXoXoX.X-XS.P W.n.P.I.n.P.P.P.n.n.P.P.L.W.A 1.I.P.n.n.P.P.n.n.n.n.n.I.n.I.B {.oX.XoXoXoXoXoXoXoXoXoXoXoXoX0 oXoXoXoXoX#XoXoXOX#X=X+XoXoXoXoXoXoXoX",
"oXoXoX$X4.V.-XoXoXoXoXoX#XOXOXoXoXoXoX-XS.P W.n.P.n.n.n.P.n.P.P.P.P.n.W.A 1.I.n.P.n.P.P.n.P.n.I.n.n.n.n.H {.+XoXoXoXoXoXoXoXoXoXoXoXoX X0 oXoXoXoXoXoXoXoX.X=XC.O O G.@XoXoXOXoX",
"oXoX+XoX4.N.;XXXOXoXoXoXoXoXoXoXoXoXoX-XS.P W.n.n.P.n.I.n.n.n.P.P.n.n.W.Z 4.W.n.P.P.P.P.n.P.P.n.n.P.n.W.M {.@X#XoXoXoXoXoXoXoXoXoXoXoXoX0 OXoXoXoXoXOXoXoXoXoXG.8   A.=XoXoXoXoX",
"oXoXoX$X4.N.-X XoXoXoXoXOXOXoXoXoXoXoX-XS.P W.n.I.n.n.n.I.n.P.P.P.n.n.R.A 1.W.n.n.P.I.n.P.n.P.P.n.P.c.W.1 {.oXoXoXoXoXoXoXoX@XoXoXoXoXoX0 +XoXoXOXOXoXoXoXoXoX-X[.  A.-X XoXoXoX",
"oXoXoX$X4.N.-X.XOXOX#XoX#XoXoXoXoXoX}.-XS.P R.n.n.P.n.n.n.n.P.P.n.n.n.W.A 2.W.n.n.n.n.P.n.n.I.I.P.n.n.W.H {.@XoXOXoXoXoXoXoXoXoXoXoXoX X0 +XoXoX#XoXoXOXoXoX X=X).  D.-XoXoXoXoX",
"oXoXoX$X4.N.;XoXOXOXoXoXoXoXoXoXoXoXOX-XA.U W.z.c.c.b.c.n.c.c.n.c.c.z.I.Z %.n.c.n.c.c.c.c.c.z.b.n.c.c.n.H {.@XoXoXOXoXoXoXoXoXoXoXoXoXoX0 oXoX#XoXoXoXoXoXoXOXoXA.  B..XoXoXoXoX",
"oXoXoXoXJ.D.=XoXoXoXOXOXoX#XOXoXoXoXOX:X].J.^.~.~.~.~.~.~.~.~.~.^.^.~./.Z.J.^.~.~.^.^.^.~.^.^.~.~.~.~./.Z.XX#XoXoXoXoXoXoXoXoXoXoXoXoXOXA.oXoXoXoXoXoXoXoXoX@XG.8 , 8 D.=XoXoXoX",
"oXoXoXoX=X@X#XoXoXoX#XOXoXOXOXoXoXoX#XoX@X*XOX+X+X+X+X+X+X+X*X*X+X*X+X+X=X=X+X+X+X+X+X+X+X+X+X+X+X+X+X+X=XoXoXoX@XoXoXoXoXoXoXoXoXoXoXoX=XoXoXoXoXoXoXoXoXoXoX@X-X;X-X#XoXoX#XoX",
"oXoXoXoX#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX#XoXoXoXoXoXoXoXoXoXoXoX.XOX.XOXoXoXoXoXoXoXoX.XOXOX.XOXoXoX.XoXoXoXoXoXoXoXoX@XoXoXoXoXoXoXoX.XoXoXoXoXoXoXoXoXoXoXoXoX XoXoXoXoXoX@X",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXOXoXoXoXoXoXoXOXoXOXOXOXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXOX#XoXoXOX#XoXoXoXoXoXoXoXOXoXoXOXOXoXoXoXoXoXoXoXoXoXoXOXoXoXOXoXoX.X+XOXoX.X+XoXoXoXoXoX@XoXoXoXoXoXoXoXoX@XoXoXoXoX@XoXoXoX@X@XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXOXoXoXOXOXoXoXoXoXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoX@XoXoXoXoXoXoXoXOXoXOXoXOX+XoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXOX#XoXoXoXoXoX#XoXOXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXOXOX.X.X+X.XoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoX",
"oX@XoXoXoXoXoXoXOXoXOXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXOXoXoXoXoXoXOXoX+XOXoXOXOXoXoXoXoXoXoXoXoXoX@XoXoXoXoXoXoXoXoXoXoXoXoX@XoXoXoXoXoXOXoXoXOXoXoXOXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 168 2 ",
"   c gray23",
".  c #5A7F00",
"X  c #484848",
"o  c #555555",
"O  c #5B5B5B",
"+  c #656565",
"@  c #6D6D6D",
"#  c #797979",
"$  c #A35901",
"%  c #A66307",
"&  c #369701",
"*  c #00AD00",
"=  c #03B402",
"-  c #0AB607",
";  c #0CB609",
":  c #1ABE12",
">  c #418E00",
",  c #25C21C",
"<  c #2FCC22",
"1  c #31CD23",
"2  c #42D42F",
"3  c #5EC734",
"4  c #46D332",
"5  c #4CD333",
"6  c #4FD93A",
"7  c #51D535",
"8  c #56D73B",
"9  c #59D93F",
"0  c #658F48",
"q  c #669249",
"w  c #69944C",
"e  c #77B151",
"r  c #7BB455",
"t  c #7DB259",
"y  c #768F65",
"u  c #7A916A",
"i  c #7C8F70",
"p  c #5CDA42",
"a  c #62DB44",
"s  c #65DC49",
"d  c #6CDA49",
"f  c #74DC4E",
"g  c #79D94D",
"h  c #6BE247",
"j  c #76E54F",
"k  c #78E653",
"l  c #CEAC00",
"z  c #CBB301",
"x  c #CABA0C",
"c  c #C8BE15",
"v  c #BFD73F",
"b  c #C6C31E",
"n  c #C9C41B",
"m  c #C6C926",
"M  c #C4CF32",
"N  c #C3D034",
"B  c #80B75C",
"V  c #84BD5D",
"C  c #86BF60",
"Z  c #89BF64",
"A  c #84C15B",
"S  c #89C85F",
"D  c #90DF5A",
"F  c #9CD85C",
"G  c #A3C54E",
"H  c #BED741",
"J  c #BFD943",
"K  c #BEDF4C",
"L  c #A5CC55",
"P  c #B3C256",
"I  c #80E559",
"U  c #BCE04F",
"Y  c #BBE557",
"T  c #86C161",
"R  c #8AC363",
"E  c #8DC965",
"W  c #88CA69",
"Q  c #91C567",
"!  c #92C569",
"~  c #95C86C",
"^  c #93DE60",
"/  c #94CF71",
"(  c #B7DF6D",
")  c #9BE868",
"_  c #8BF064",
"`  c #97F26B",
"'  c #9FE272",
"]  c #9CF572",
"[  c #9DF872",
"{  c #A1ED6E",
"}  c #ACE96D",
"|  c #BAED62",
" . c #B8E36F",
".. c #A4F66C",
"X. c #B6F26C",
"o. c #B8F56D",
"O. c #A4EE73",
"+. c #AAEF73",
"@. c #A7EF78",
"#. c #B9EC77",
"$. c #B9EC78",
"%. c #A5F372",
"&. c #ABF275",
"*. c #ACFC76",
"=. c #ABF37A",
"-. c #AEFA7C",
";. c #A4F877",
":. c #B5F674",
">. c #B2FD7E",
",. c #B3F87A",
"<. c #838383",
"1. c #888888",
"2. c #9C9C9C",
"3. c #8FA183",
"4. c #91A386",
"5. c #93AA85",
"6. c #97B782",
"7. c #99B685",
"8. c #9BB986",
"9. c #9DB48D",
"0. c #9FB98B",
"q. c #9CA795",
"w. c #A0B78F",
"e. c #A5AD9F",
"r. c #A1B692",
"t. c #A7B995",
"y. c #AABA96",
"u. c #A4B599",
"i. c #AAAAA9",
"p. c gray64",
"a. c #ABB6A3",
"s. c #ACB8A4",
"d. c #AEB9A9",
"f. c #B3BBAA",
"g. c #B4B4B4",
"h. c #BBBBBB",
"j. c #A9F781",
"k. c #ADFF85",
"l. c #B4FF81",
"z. c #B9FF85",
"x. c #B2FF89",
"c. c #B9FF89",
"v. c #BEC2BC",
"b. c #C8DABC",
"n. c #CECECE",
"m. c #CDD7C7",
"M. c #CED7C8",
"N. c #D1D6CE",
"B. c #D4D4D4",
"V. c #DBDBDB",
"C. c #D6EDC6",
"Z. c #DFE5DB",
"A. c #E0EDD7",
"S. c #E3EBDD",
"D. c #E0E2DE",
"F. c #DFDDE1",
"G. c #E2DEE5",
"H. c #E5E6E5",
"J. c #E6E8E4",
"K. c #E7E4E8",
"L. c #EAE6ED",
"P. c #EBEAEB",
"I. c #EFECF1",
"U. c #EEE7F4",
"Y. c #F0EEF2",
"T. c #F2EBF8",
"R. c #F2F2F3",
"E. c #F9F5FB",
/* pixels */
"H.H.H.H.H.H.P.H.J.H.H.H.H.H.H.H.H.J.H.P.H.H.J.H.H.H.H.H.H.H.H.H.H.H.J.H.H.H.H.H.H.H.P.H.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.P.H.J.H.H.H.H.H.H.H.H.H.H.H.P.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.J.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.H.P.",
"H.H.H.H.H.H.J.H.D.H.H.H.H.H.H.H.H.H.H.H.D.J.H.H.H.J.H.H.H.H.H.H.J.D.H.H.H.H.H.H.H.P.H.H.H.H.H.H.",
"H.H.H.H.Y.L.L.U.L.L.U.L.Y.P.L.L.H.L.L.L.U.L.L.U.P.U.L.L.U.P.L.L.H.L.L.U.P.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.K.D.4.9.9.9.9.w.w.9.3.9.y.y.y.y.t.9.4.9.9.0.9.9.9.9.4.w.y.y.y.y.y.5.b.H.H.H.H.H.K.H.H.H.H.H.",
"H.H.K.S.V &.*.*.*.*.*.*.V *.a 7 7 7 h *.V *.*.,.*.*.*.%.A *.7 7 7 7 k { p.U.H.H.H.H.R.H.H.H.H.H.",
"H.H.K.S.R >.l.l.M ,.l.l.R ] * * * * ; &.T l.l.:.N l.z.=.~ _ * * * * , =.s.P.D.H.P.V.v.G.H.H.H.H.",
"J.H.H.J.Z -.x.Y l K x.-.! p * = = = = s Q >.x.H l | x.=.Q 4 * = = = = f f.P.H.G.P.n.o @ R.K.H.H.",
"H.H.H.S.Z -.l.b l c >.>.! 9 = = = = * a Q k.,.x l m l.=.Q 2 * = = = = f f.Y.D.H.H.P.# o R.H.H.H.",
"H.H.K.S.C k.Y l z l K x.V >.] d & f ;.-.V c.H l z z | j.T l.] 3 & I *.%.a.Y.H.H.P.h.O # P.H.H.H.",
"H.H.K.S.Z -.n l z l c >.T ,.c.( $ $.z.-.R ,.x z z l m j.T l.c.P % c.c.{ a.Y.H.H.H.H.V.P.H.H.H.H.",
"H.H.H.S.R -.:.X.X.X.X.-.T >.-.&.G =.>.-.T ,.X.o.X.o.o.&.R l.>.} L >.l.{ a.P.H.H.H.H.J.H.H.H.H.H.",
"H.H.K.Z.w V T C T T T T 0 T Q ~ / ! Q V q R R T T T R B q R V R W V T e p.I.H.H.H.H.H.H.H.H.H.H.",
"H.H.P.S.Z -.l.>.k.>.>.l.V >.p 4 5 4 s >.T l.>.>.l.l.l.=.R l.l.>.>.l.l.O.s.R.H.H.H.H.P.H.H.H.H.H.",
"H.H.H.S.Z -.l.l.>.l.>.>.R ] * * * * = %.T l.>.>.>.k.l.=.T z.>.>.>.l.l.%.s.P.H.H.H.V.g.H.H.H.H.H.",
"H.H.K.S.Z -.l.>.>.l.l.>.Q p * = = = * a ! l.>.l.>.>.l.=.R l.l.l.>.>.z.O.a.P.H.H.H.B.  g.I.J.H.H.",
"H.H.K.S.Z -.l.>.l.>.l.>.Q a = = = = = d ! l.>.l.l.>.l.=.R l.-.>.l.>.l.%.a.Y.D.H.G.E.@ i.R.H.H.H.",
"H.H.K.S.Z -.l.>.>.>.>.>.C l.*.g > k k.>.A l.>.>.-.>.l.=.T l.l.-.>.>.l.O.a.Y.H.H.H.n.X # Y.H.H.H.",
"H.H.K.S.Z -.l.l.>.l.l.>.T j.z.( $ #.c.-.Z l.l.l.l.l.l.=.R l.l.l.l.l.l.O.a.Y.H.H.H.J.H.D.H.H.H.H.",
"H.H.H.S.C =.-.-.-.-.-.-.V -.j.&.L =.-.=.C l.-.-.-.-.>.@.C l.-.-.>.=.>.{ a.I.J.H.H.H.H.H.H.H.H.H.",
"H.H.K.Z.w V Z C T T C C q A Z T W Z C C 0 C V Z C C C B w R C C T T R e p.P.H.H.H.H.K.H.H.H.H.H.",
"H.H.K.S.Z l.z.l.l.l.l.l.Z l.l.l.,.l.l.,.Z l.l.l.l.l.l.,.R z.l.l.l.l.z.O.s.Y.F.H.H.H.E.J.H.H.H.H.",
"H.H.K.S.Z =.l.>.l.>.>.l.V >.l.:.b ,.l.>.C l.l.>.l.l.l.=.T l.>.>.>.>.l.%.s.P.H.H.H.V.i.V.J.H.H.H.",
"H.H.K.S.Z -.l.>.-.l.l.l.T >.x.H l U x.=.T l.>.>.l.>.l.=.T z.>.l.l.>.l.%.a.P.F.J.H.V.  g.R.K.H.H.",
"H.H.K.S.Z -.l.>.l.l.l.-.A l.,.x l c >.>.T l.>.l.l.>.l.=.T l.>.l.l.>.l.O.a.Y.H.J.D.E.@ i.R.H.H.H.",
"H.H.P.S.R -.l.>.>.>.>.>.V x.H l z l K l.V l.>.>.>.>.l.=.T l.>.>.l.>.l.O.a.I.H.H.P.n.o # H.H.H.H.",
"J.H.H.S.Z -.l.l.l.l.l.l.T ,.n x x x m ,.R l.l.l.l.l.l.=.R l.l.l.l.l.l.O.a.I.J.K.H.H.P.P.H.H.H.P.",
"H.H.H.D.B @.=.=.=.=.&.=.B =.+.+.&.&.+.@.V =.=.=.=.=.=.O.V >.=.=.=.=.,.) a.I.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.y V ~ R ! R Q R q R R T R R R Z q R T T T Z R V w R T T R T R r e.Y.D.H.H.H.H.H.H.H.H.H.",
"H.H.H.L.t.*.6 < 1 < 4 l.Z z.l.z.z.l.l.l.Z z.z.l.l.z.z.,.Q c.l.l.l.z.c.%.a.U.H.H.H.H.R.H.H.H.H.H.",
"H.H.H.L.r.` - * * * * ` Z >.-.l.>.>.l.,.C l.l.-.>.l.l.&.V l.>.l.l.,.>.{ s.I.H.H.H.B.2.V.P.H.H.H.",
"H.H.H.L.y.7 * = = - * 7 ! ,.l.l.l.>.>.-.C l.>.l.l.>.l.=.R l.l.>.l.>.l.%.s.Y.J.H.H.V.X g.P.J.H.H.",
"H.H.H.L.r.j : ; = - : k Z l.>.l.l.>.l.-.C l.>.l.>.>.l.=.T l.>.l.l.>.l.{ s.P.H.H.H.R.+ p.R.H.H.H.",
"H.H.H.P.9.>.z.) > F c.>.V l.>.>.l.l.l.=.C l.>.>.>.l.l.=.Z l.-.l.>.l.z.O.a.U.H.H.H.B.o 1.H.H.K.H.",
"H.H.H.L.r.-.l.#.% ( c.>.R l.l.l.l.l.z.l.Z z.l.l.l.l.l.-.R c.l.l.l.l.z.O.a.U.Z.K.H.H.R.P.J.H.H.H.",
"H.H.H.L.5.) O.{ F ) O.{ t O.@.O.@.O.@.O.t =.O.O.O.@.+.O.t %.O.{ O.{ %.^ a.P.J.J.H.H.H.H.H.H.H.H.",
"H.H.J.D.u a.s.a.f.s.s.f.y S R R R R R R w E R E R R E A i f.a.a.a.s.f.q.i.Y.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.A.0.L.Y.I.I.I.P.T.w.>.c.c.l.z.z.l.Z z.z.z.c.z.c.&.a.E.P.P.Y.P.Y.G.g.P.H.H.H.H.E.H.H.H.H.H.",
"H.H.H.S.6.G.H.H.J.H.H.H.6.,.,.>.>.>.l.-.C l.-.>.>.>.l.%.u.L.H.H.K.J.H.B.g.P.H.H.H.B.1.B.P.H.H.H.",
"H.H.H.A.8.K.H.H.H.H.H.K.8.-.l.l.>.l.l.>.T l.>.l.l.l.l.&.u.U.H.H.H.H.P.B.g.P.H.H.H.H.X h.R.H.H.H.",
"H.H.L.A.6.L.H.H.H.H.J.L.7.*.-.-.-.,.-.*.A ,.-.-.-.-.>...t.Y.H.P.H.H.P.B.g.Y.H.H.H.R.O 2.R.H.H.H.",
"H.H.H.H.M.K.H.H.H.K.H.K.M.C.C.C.C.C.C.C.b.C.C.C.C.C.C.C.N.H.H.H.H.H.H.H.B.H.H.H.H.V.p.h.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.H.L.L.H.L.L.L.L.P.L.L.L.L.H.L.L.H.K.H.H.H.H.H.H.P.H.H.H.H.H.R.Y.H.H.H.H.",
"H.H.H.H.H.H.H.H.P.H.H.H.H.J.H.H.J.J.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.J.H.H.J.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H.H.H.H.H.J.H.H.H.H.J.J.H.H.H.H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 174 2 ",
"   c #5D5D5D",
".  c gray33",
"X  c #646464",
"o  c #6D6D6D",
"O  c gray46",
"+  c #797979",
"@  c #8F6907",
"#  c #877D13",
"$  c #937915",
"%  c #00A700",
"&  c #01AC00",
"*  c #08AD00",
"=  c #02B301",
"-  c #0DB003",
";  c #10B80B",
":  c #16BD10",
">  c #1ABF12",
",  c #25BE17",
"<  c #70951A",
"1  c #7FB335",
"2  c #18C011",
"3  c #2AC919",
"4  c #29C71E",
"5  c #31CC1F",
"6  c #2FC721",
"7  c #38C927",
"8  c #43CD2F",
"9  c #43D32E",
"0  c #48D22F",
"q  c #52CE3B",
"w  c #4FD838",
"e  c #56D93D",
"r  c #6E9D4E",
"t  c #739D56",
"y  c #74A453",
"u  c #78AB56",
"i  c #79A75B",
"p  c #7DB25A",
"a  c #5FCF44",
"s  c #66CE49",
"d  c #66D947",
"f  c #77CD56",
"g  c #5FE340",
"h  c #69E54A",
"j  c #77EA55",
"k  c #ADAD3C",
"l  c #B0A032",
"z  c #A9B13F",
"x  c #CDA700",
"c  c #CDAC00",
"v  c #CCB201",
"b  c #C9BC14",
"n  c #C6C21D",
"m  c #C4CB2C",
"M  c #C0D036",
"N  c #C6DD3D",
"B  c #C4D737",
"V  c #82BA5D",
"C  c #B4BE4C",
"Z  c #A8B844",
"A  c #899E7A",
"S  c #86BF60",
"D  c #89BD66",
"F  c #84B662",
"G  c #8DA77B",
"H  c #8FAB7C",
"J  c #91AC7F",
"K  c #94B27F",
"L  c #9FC14D",
"P  c #BEDC49",
"I  c #A8C051",
"U  c #8AF55E",
"Y  c #BCE553",
"T  c #BCE857",
"R  c #BCE959",
"E  c #87C261",
"W  c #8BC664",
"Q  c #8DCA64",
"!  c #8EC46A",
"~  c #8ACC6B",
"^  c #90CC67",
"/  c #93CD6A",
"(  c #9ACE6E",
")  c #92C46C",
"_  c #8DD16C",
"`  c #95D46B",
"'  c #9AD36E",
"]  c #95DB6A",
"[  c #9ADB6F",
"{  c #94D966",
"}  c #9CCD70",
"|  c #8ED370",
" . c #96D271",
".. c #9BD372",
"X. c #9EDB71",
"o. c #92D871",
"O. c #ACDE63",
"+. c #B2D962",
"@. c #A2DF70",
"#. c #8BE962",
"$. c #96E86B",
"%. c #92F469",
"&. c #9FE372",
"*. c #9EED71",
"=. c #B9EC64",
"-. c #B2E46F",
";. c #B5F26F",
":. c #BAF56C",
">. c #A1E573",
",. c #A5EC75",
"<. c #A8ED76",
"1. c #AAED79",
"2. c #A7EC78",
"3. c #A9F575",
"4. c #AEFD77",
"5. c #A5F07C",
"6. c #ABF47A",
"7. c #AFFC7A",
"8. c #B2F374",
"9. c #B2FA74",
"0. c #B2F37C",
"q. c #B1FD7E",
"w. c #BCFA71",
"e. c #A4F76B",
"r. c #C7E040",
"t. c #C2E954",
"y. c #C3F767",
"u. c #888888",
"i. c #919191",
"p. c #9B9B9B",
"a. c #99AB8D",
"s. c #9BBD85",
"d. c #9BB985",
"f. c #A1BC8E",
"g. c #A9BB9D",
"h. c #A8BF96",
"j. c #ADADAD",
"k. c #ADBEA1",
"l. c #B2B2B3",
"z. c #9EC087",
"x. c #A4C28B",
"c. c #ADC098",
"v. c #AEFD82",
"b. c #B5FE82",
"n. c #BAFF84",
"m. c #B4FF8A",
"M. c #BCFF8A",
"N. c #C3FF8B",
"B. c #C4FF92",
"V. c #C0DBAD",
"C. c #C4D8B8",
"Z. c #CAEBB3",
"A. c #CFF1B8",
"S. c #D1F3BA",
"D. c #BCB7C0",
"F. c #C6C6C6",
"G. c #CDCBCB",
"H. c #CBD2C5",
"J. c #CFCCD1",
"K. c #D0CDD2",
"L. c #D3D2D3",
"P. c #D7D2DA",
"I. c #DBDBDC",
"U. c #DFE9D8",
"Y. c #E1E5DE",
"T. c #E1EBD9",
"R. c #E5E6E5",
"E. c #E4EAE0",
"W. c #E6E1E9",
"Q. c #E9E5ED",
"!. c #EBEBEB",
"~. c #F0F1EF",
"^. c #EEEAF0",
"/. c #F2F2F3",
/* pixels */
"R.R.R.R.R.R.R.!.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.!.R.R.R.R.R.R.R.R.R.!.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.!.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.E.E.!.R.R.R.R.E.R.R.R.R.R.R.R.E.R.R.R.R.R.!.R.R.R.R.R.R.R.",
"R.R.R.R.!.W.W.W.W.W.W.R.W.W.W.W.W.W.R.Q.W.W.W.W.W.R.W.W.W.W.W.W.R.R.R.R.R.R.R.R.R.R.R.R.",
"R.R.R.R.J d.s.s.z.s.z.G d.x.x.x.x.x.G K f.s.s.s.x.J K x.x.x.x.x.H L.!.R.R.R.R.R.R.R.R.R.",
"R.R.R.E.! 4.q.9.9.q.q.W 3.9 6 6 3 U / ,.q.q.9.4.q.{ ,.g 3 6 3 h @.F.!.R.R.R./.~.R.R.R.R.",
"R.R.R.Y.! q.m.P m m.b./ #.= & & % w ' <.n.=.n q.b.' &.2 & & & 4 @.F.!.R.R.I.i.l.^.R.R.R.",
"R.R.R.E.! 7.b.b v ;.b.( q % = = & 2 W 6.v.M x R m.@.s = & = & = f J.!.R.R.R.O   /.R.R.R.",
"R.R.R.E.! m.Y c v M m.Q #.g , - 9 j Q 5.:.v c n n./ { h 6 * 7 h ] F.!.R.R.I.o   !.R.R.R.",
"R.R.R.R.! 7.b x c c :.~ 6.B.C $ M.N.Q 5.m c c x t.o.>.B.-.@ 0.B.[ F.!.R.!.I.j.L.R.R.R.R.",
"R.R.R.E.! 8.Y T T Y w.~ 5.v.O.Z v.b./ 2.t.T Y Y y. .>.b.8.z 0.n.[ F.!.R.R.R./.!.R.R.R.R.",
"R.R.R.E.t W ~ ~ ~ ~ ~ r V ( (  .( ( r V / ~ ~ ~ ~ y p ^ Q _ W Q u F.!.R.R.R.R.R.R.R.R.R.",
"R.R.R.R.! 7.q.7.q.6.b.W 3.e 8 8 7 %./ ,.q.q.q.q.b.` &.b.q.6.q.b.[ F.!.R.R.R./.R.R.R.R.R.",
"R.R.R.E.! b.b.b.b.q.b./ $.= & = & e ..,.b.q.q.q.b.' >.b.q.b.b.b.[ F.R.R.R.R.p.P.!.R.R.R.",
"R.R.R.E.! 7.b.7.q.q.b.( q & = = & 2 W 2.b.b.q.q.b.` >.b.q.q.b.b.X.F.!.R.R.!.X j./.R.R.R.",
"R.R.W.E.! 7.b.b.b.q.b.) #.9 : = 6 h Q 2.b.q.b.b.n.` >.b.q.b.q.b.[ F.!.R.W.~.X u./.R.R.R.",
"R.R.R.E.! 7.v.7.q.q.b.Q 1.B.L # M.N.Q ,.b.v.q.7.b.` >.b.q.q.q.b.[ F.!.R.W.U.p.j.R.R.R.R.",
"R.R.R.E.) b.n.b.b.b.n.^ 6.m.+.k n.b./ 1.n.b.b.b.M.' ,.n.b.b.b.n.X.F.!.R.R.R./.!.R.R.R.R.",
"R.R.R.Y.t E Q Q Q Q ^ r E ^ Q _ W _ y V Q Q Q W ~ y p ^ Q Q Q / p F.!.R.R.W.R.R.R.R.R.R.",
"R.R.R.E.D 6.6.6.6.6.q.S ,.6.6.6.6.q.W >.4.6.6.6.q.^ [ q.6.6.6.q.` F.!.R.R.R./.R.R.R.R.R.",
"R.R.R.E.! q.b.b.b.b.n.Q 6.m.=.B m.b.^ 2.b.b.b.b.n.` >.n.b.b.b.b.X.F.!.R.R.R.j.I.R.R.R.R.",
"R.R.R.R.! q.b.q.q.b.b.Q 6.m.m c ;.M.Q 2.b.q.b.b.n.` >.b.q.q.q.n.[ F.!.R.R.R.  j./.R.R.R.",
"R.R.R.E.! 7.q.q.b.q.b.W v.:.v c M m.^ 2.b.b.q.7.n.` >.b.b.q.q.n.X.F.!.R.R./.o i./.R.R.R.",
"R.R.R.R.! 7.q.b.q.0.b.Q v.m x c c :.~ ,.b.7.b.7.b.` >.n.q.b.7.n.[ F.!.R.R.U.u.p.!.R.R.R.",
"R.R.R.T.) b.b.b.b.b.n.^ 1.N N N B y.` <.M.b.n.n.n.' >.n.n.b.b.n.@.F.!.W.W.W././.R.R.R.R.",
"R.R.R.R.i Q ' ..@.( ' y W  .| _ `  .y E ` Q Q Q ` u V / ^ ^ ~ ` p F.R.R.R.R.R.R.R.R.R.R.",
"R.R.R.^.a.*.s a q s *.V @.<.,.<.,.6.E [ 5.2.2.2.6.Q ` 6.,.,.,.6.~ G.!.R.R.R.R.R.R.R.R.!.",
"R.R.R.Q.h.#.= = = & j } 6.b.b.b.b.n.^ 1.n.b.b.b.M.` >.n.b.b.b.n.X.F.!.R.W.R.F.I.R.R.R.R.",
"R.R.R.Q.c.0 * = = & 6 ~ 6.b.b.q.q.b.^ 2.b.q.q.q.b.` >.b.b.q.b.b.X.F.!.R.R.R.. j./.W.R.R.",
"R.R.Y.Q.h.g : = = ; w Q 6.b.b.q.b.b./ 2.b.q.b.q.n.` &.b.q.q.q.b.[ F.R.R.Y./.O p./.R.R.R.",
"R.R.R.Q.f.9.9.V < b.n.Q 6.q.q.v.7.n.Q ,.b.q.q.q.b.` &.b.b.b.q.n.[ G.!.W.R.Y.O i.!.R.R.R.",
"R.R.R.^.h.9.M.C l M.n.) v.b.b.n.b.n.( 1.N.b.b.b.N.' >.n.b.b.b.M.@.F.Q.W.R.R./.!.R.R.R.R.",
"R.R.R.R.A ( .. . . ...i ^ ' ` ' ` [ u E ' ` ` ` [ p D ..' ' ( @.F F.!.R.R.R.R.R.R.R.R.R.",
"R.R.R.T.J K.K.K.J.L.P.a.] >.>.>.>.,.V ` >.>.>.>.<.D D.P.J.K.J.P.l.F.!.R.R.R.R.R.R.R.R.R.",
"R.R.R.T.f.!.!.Q.R.R./.k.3.n.b.b.b.n./ <.b.b.b.b.n...P.~.R.!.!.~.G.F.!.R.R.R.L.R.R.R.R.R.",
"R.R.R.T.f.R.R.R.R.R.!.g.3.b.b.b.q.n./ <.b.v.b.b.b...J.!.R.R.R.!.F.F.!.R.R.R.. l./.R.R.R.",
"R.R.Q.T.f.W.R.R.R.R.^.g.e.q.4.9.q.b.Q *.q.4.4.4.q.` J.!.R.R.R.!.F.F.!.R.R./.+ p./.R.R.R.",
"R.R.R.Y.C.R.R.R.R.R.Q.H.Z.S.A.A.A.S.V.Z.S.A.A.A.S.V.I.!.R.R.R.R.I.I.R.R.R.R.p.l.R.R.R.R.",
"R.Q.R.R.Q.R.R.R.R.R.R.!.Q.Q.Q.Q.Q.Q.Q.Q.Q.R.Q.Q.Q.Q.!.R.R.R.R.R.R.R.R.R.R.R.~.!.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.E.!.R.R.R.R.R.R.!.R.R.R.R.R.R.R.R.R.R.R.R.R.R.",
"!.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.!.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.!.R.",
"R.R.R.R.R.!.R.R.R.R.R.R.R.!.R.R.R.!.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.",
"R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.!.R.R.R.R.R.R.R.R.R."
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 171 2 ",
"   c gray37",
".  c #00AC00",
"X  c #03B302",
"o  c #0AB707",
"O  c #03BA03",
"+  c #0AB709",
"@  c #1ABE12",
"#  c #25BF19",
"$  c #29BF1D",
"%  c #479B0F",
"&  c #499E11",
"*  c #1DC111",
"=  c #22C115",
"-  c #29C81D",
";  c #2EC221",
":  c #38CF24",
">  c #3EC72C",
",  c #32C924",
"<  c #53C73B",
"1  c #53D938",
"2  c #7BAF57",
"3  c #7CAF58",
"4  c #7FB55B",
"5  c #7FAF60",
"6  c #5DC841",
"7  c #5AD640",
"8  c #5FDB43",
"9  c #63C749",
"0  c #63CB48",
"q  c #6ED145",
"w  c #72D84A",
"e  c #6FCF51",
"r  c #71D352",
"t  c #7FD05A",
"y  c #69E147",
"u  c #8D8F1C",
"i  c #8EA52F",
"p  c #AFA237",
"a  c #B0A53B",
"s  c #CEA600",
"d  c #CCAC00",
"f  c #C9B408",
"g  c #CAB810",
"h  c #C4CD2D",
"j  c #C5C925",
"k  c #C9D52F",
"l  c #C3D031",
"z  c #C4DA3E",
"x  c #80B75C",
"c  c #82B95D",
"v  c #87BE62",
"b  c #89BD64",
"n  c #9AC14A",
"m  c #8CD05F",
"M  c #83D85D",
"N  c #BDDE4C",
"B  c #A3C556",
"V  c #84E55E",
"C  c #BFE957",
"Z  c #BDEC5E",
"A  c #87C060",
"S  c #8AC363",
"D  c #8ECB64",
"F  c #8EC768",
"G  c #90CE67",
"H  c #93CD6B",
"J  c #8ADC61",
"K  c #8ED261",
"L  c #93D266",
"P  c #95D36B",
"I  c #99D46D",
"U  c #94D86C",
"Y  c #9ADB6E",
"T  c #96DD66",
"R  c #96C079",
"E  c #99CA7E",
"W  c #93D772",
"Q  c #9DD771",
"!  c #94DA72",
"~  c #9DDD70",
"^  c #A4D560",
"/  c #A2DD73",
"(  c #A3D773",
")  c #9CE36E",
"_  c #9FEC6B",
"`  c #87F061",
"'  c #8CF566",
"]  c #9CFB6D",
"[  c #9EE272",
"{  c #9CE678",
"}  c #AAE76E",
"|  c #A2E76D",
" . c #BAED63",
".. c #B1E86F",
"X. c #B9F064",
"o. c #A3E474",
"O. c #A5EB76",
"+. c #A8EC77",
"@. c #A6E179",
"#. c #A8E67B",
"$. c #A4EE7A",
"%. c #AAED7A",
"&. c #BBE875",
"*. c #ADFD77",
"=. c #ABF47A",
"-. c #AEFC7A",
";. c #A4F673",
":. c #B8F670",
">. c #B1FD7D",
",. c #B5F777",
"<. c #C3DE44",
"1. c #C3E148",
"2. c #C0E852",
"3. c gray54",
"4. c #858585",
"5. c #949494",
"6. c #9A9A9A",
"7. c #98AB8B",
"8. c #9EB78E",
"9. c #A2AF99",
"0. c #A3BD91",
"q. c #A8BF96",
"w. c #ACACAC",
"e. c #AFB4AA",
"r. c #B3B3B3",
"t. c #BCBCBC",
"y. c #9FCD82",
"u. c #A8CD88",
"i. c #ACD88E",
"p. c #AAC796",
"a. c #A9C595",
"s. c #B7CC9F",
"d. c #ADFF87",
"f. c #B5FE81",
"g. c #BAFF85",
"h. c #B4FF8A",
"j. c #BAFF8B",
"k. c #B6E595",
"l. c #BFF49C",
"z. c #B5C7A8",
"x. c #BEC7B8",
"c. c #BECDBC",
"v. c #BCC5B5",
"b. c #C1FF8D",
"n. c #C4FF95",
"m. c #C1F79D",
"M. c #C3FA9E",
"N. c #C2CBBC",
"B. c #C3C3C3",
"V. c #CECECE",
"C. c #C8CDC5",
"Z. c #D0CFCF",
"A. c #CCD1C9",
"S. c #CFCFD0",
"D. c #D4D4D4",
"F. c #D9D4D6",
"G. c #D7DED2",
"H. c #D8DFD4",
"J. c #D9DAD8",
"K. c #D8D5DA",
"L. c #D6E3CD",
"P. c #DAE2D5",
"I. c #E2DDE6",
"U. c #E5DEE8",
"Y. c #E5E5E5",
"T. c #E6E8E6",
"R. c #E7E5EA",
"E. c #E9E6EC",
"W. c #EBEAEB",
"Q. c #F4EEF8",
"!. c #F2F2F2",
/* pixels */
"Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.T.Y.Y.T.",
"Y.Y.W.W.W.W.W.W.W.R.T.R.W.W.W.W.W.W.W.W.W.W.Y.W.W.Y.Y.R.R.Y.R.T.",
"T.Y.V.S.V.Z.V.V.V.F.F.F.Z.V.V.V.V.S.Z.A.F.F.F.Z.F.T.Y.T.Y.Y.Y.Y.",
"E.H.v o./ { o.S P e 9 0 U S [ [ [ o.F H r 9 0 M a.E.Y.Y.!.W.Y.Y.",
"E.P.I j. .N j./ M O X X 0 ( h. .<.h...J O X . 1 s.R.Y.T.t.t.W.Y.",
"E.P.L h.j f f.@.< X O . - I d.l f f.#.< X O . # p.R.Y.!.5.  !.Y.",
"E.P.! Z d s 1.{ ) ` & w ;.U X.d s z { ) ' & q ] p.E.Y.W.6.3.W.Y.",
"T.P.W 2.h l <.~ %.j.p &.f.W C h l <./ o.n.a &.f.p.E.Y.Y.Y.W.E.Y.",
"E.G.3 U W W ! 4 S I U U H 3 I W W ~ c c P P P m 8.E.Y.Y.Y.Y.Y.Y.",
"W.P.L f.>.-.f.~ ) , # = V I >.>.>.>.) o.f.-.f.*.p.E.Y.Y.Y.T.Y.Y.",
"T.P.I f.f.>.f.@.0 . X . > Q >.f.f.f.[ o.f.d.f.*.p.E.Y.!.6.w.!.Y.",
"E.P.I f.>.>.f./ e - o @ 7 U f.>.f.f.) o.f.>.f.*.p.E.U.!.6.4.!.I.",
"E.P.U g.f.f.g.~ %.b.u ..b.H g.f.f.g.[ o.g.f.g.>.p.E.Y.W.t.r.T.Y.",
"E.H.S O.o.o.+.D P +.B | o.A +.O.o.+.P P +.O.O._ 0.E.Y.Y.T.!.Y.Y.",
"R.G.c [ Y ~ o.A G [ { [ Y c [ Y Y o.S D o.Y / T 0.E.Y.T.W.T.Y.T.",
"W.P.Q g.f.f.g./ %.j.<.,.f.L g.f.f.g.o.o.g.f.g.>.p.E.Y.W.t.Z.E.Y.",
"E.P.P f.f.>.f.Y $.:.d N d.L f.>.>.f.~ o.f.>.f.*.a.E.I.!.5.6.!.Y.",
"E.P.P f.-.>.f.Y $.h d g ,.P f.>.>.f.) o.f.f.f.*.p.E.Y.!.5.4.!.Y.",
"W.P.P f.f.f.f.~ } k h j  .W f.f.f.g./ O.g.f.f.>.p.E.T.R.P.I.Y.Y.",
"E.H.5 I Q Q ( c S ! W W G 2 U P P Y c v Y L L K 8.E.T.T.W.Y.Y.Y.",
"Y.I.u.y $ $ 1 Q o.>.=.>.=.G f.=.=.>.Y [ >.-.>.*.a.E.Y.Y.R.T.Y.Y.",
"T.U.y.* . . + M =.f.f.f.-.I f.f.f.f.[ o.f.f.>.>.a.T.Y.!.6.r.!.Y.",
"Y.U.E : + o - t %.f.>.f.-.G f.>.>.f.[ o.f.f.f.*.a.E.Y.!.6.4.!.Y.",
"T.I.u.b.n i n.( %.f.f.f.f.I f.f.f.g.o.o.g.f.f.>.p.E.Y.W.r.w.W.Y.",
"T.I.b -.^ B *.K Y =.+.+.O.S =.+.+.=.P T =._ O.| q.E.Y.Y.W.W.T.Y.",
"E.L.7.C.B.c.C.9.D ) Y Y U 4 Y Y Y ) v e.N.v.N.N.e.E.Y.Y.W.W.Y.T.",
"E.L.z.Q.W.E.!.C.+.g.g.g.f.I g.f.f.g.@.K.!.W.E.W.t.T.Y.E.B.K.W.Y.",
"E.L.z.E.Y.Y.W.x.| >.-.*.*.L >.*.-.>.Y D.T.Y.Y.Y.t.W.Y.!.5.5.!.Y.",
"R.P.N.E.Y.Y.E.A.k.M.M.m.m.i.M.m.m.M.k.K.E.T.T.Y.C.Y.Y.!.w.6.!.Y.",
"T.R.R.Y.Y.Y.Y.T.E.E.E.R.R.E.R.E.R.R.E.T.Y.Y.Y.Y.R.Y.Y.Y.Y.T.Y.Y.",
"T.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.R.Y.R.Y.Y.R.Y.Y.Y.Y.Y.Y.",
"T.Y.R.T.T.T.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.T.Y.Y.Y.Y.R.T.Y.Y.T.T."
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 224 2 ",
"   c #E6E6E7",
".  c #EAE5EE",
"X  c #EAE3ED",
"o  c #EEE6F1",
"O  c #F2E7F4",
"+  c #ECE6EF",
"@  c #EAE4ED",
"#  c #EBE6EF",
"$  c #F1E7F3",
"%  c #F0E7F2",
"&  c #E7E6E8",
"*  c gray90",
"=  c #DEE1DD",
"-  c #B8D6A6",
";  c #BBE2AA",
":  c #B9D7A5",
">  c #A9D198",
",  c #9BD08E",
"<  c #B1D29E",
"1  c #BBDDA8",
"2  c #BBDFA9",
"3  c #B5D3A0",
"4  c #9ED191",
"5  c #A2D091",
"6  c #D6DCD1",
"7  c #E8E7E9",
"8  c #EAEBEA",
"9  c #E6E6E6",
"0  c #D9DFD6",
"q  c #A6EA74",
"w  c #BFDD31",
"e  c #B0EF70",
"r  c #36C427",
"t  c #00AE00",
"y  c #6DDA53",
"u  c #BCE856",
"i  c #BEE346",
"p  c #85E364",
"a  c #00B200",
"s  c #1ABE0E",
"d  c #CBDBBF",
"f  c #EAE7ED",
"g  c #A3A4A3",
"h  c gray88",
"j  c #D9E2DB",
"k  c #AADB68",
"l  c #C9BD11",
"z  c #ACDA5C",
"x  c #97E36E",
"c  c #92CD4D",
"v  c #9CEB7B",
"b  c #BBCA35",
"n  c #C2C425",
"m  c #9EE979",
"M  c #86CD4C",
"N  c #89D854",
"B  c #CBDDC3",
"V  c #EAE6EB",
"C  c #BCBDBC",
"Z  c #E2E2E2",
"A  c #D9DED6",
"S  c #9CD872",
"D  c #A5F179",
"F  c #9FDD71",
"G  c #78CF55",
"H  c #5FCE42",
"J  c #8AD162",
"K  c #A4E876",
"L  c #A3EB77",
"P  c #97D66B",
"I  c #AEEC7B",
"U  c #A3E570",
"Y  c #C6D5BD",
"T  c #EBE7ED",
"R  c #E7E7E7",
"E  c #DADFD6",
"W  c #ACEB7F",
"Q  c #B8FF82",
"!  c #B5F382",
"~  c #40C62D",
"^  c #00B100",
"/  c #77D855",
"(  c #BDFD87",
")  c #B5FE81",
"_  c #A6E877",
"`  c #B7FF84",
"'  c #AEF979",
"]  c #CBDAC0",
"[  c #E8E5EB",
"{  c #A2A3A1",
"}  c #E4E4E4",
"|  c #A1E077",
" . c #ADF87A",
".. c #A0E474",
"X. c #9FDF6D",
"o. c #A0D35C",
"O. c #9DE272",
"+. c #A6ED76",
"@. c #AAF279",
"#. c #9BDD6F",
"$. c #ACF47B",
"%. c #A2EC71",
"&. c #C7D7BD",
"*. c #EBE8ED",
"=. c #D2D3D2",
"-. c #9FDD75",
";. c #ABF579",
":. c #9DE071",
">. c #A1E472",
",. c #B1F071",
"<. c #99DD71",
"1. c #A5EA75",
"2. c #A8F078",
"3. c #99DA6D",
"4. c #AAF17A",
"5. c #A0E96F",
"6. c #C7D6BD",
"7. c #EAE7EC",
"8. c #DBDCDB",
"9. c #ACEB7E",
"0. c #BBFF83",
"q. c #AAF282",
"w. c #B5DF56",
"e. c #D0C617",
"r. c #A8EA76",
"t. c #B4FA81",
"y. c #B7FF83",
"u. c #A7E877",
"i. c #B9FF85",
"p. c #B0F97A",
"a. c #E9E6EB",
"s. c #9FA09F",
"d. c gray89",
"f. c #D9DDD7",
"g. c #A2DC78",
"h. c #ACF278",
"j. c #9FE176",
"k. c #A2D258",
"l. c #B3D346",
"z. c #99D465",
"x. c #A2E976",
"c. c #A6EC76",
"v. c #97D76C",
"b. c #A7ED78",
"n. c #9EE66D",
"m. c #C6D5BC",
"M. c #EBE8EE",
"N. c #E4E4E3",
"B. c #EAE1E8",
"V. c #6FC85B",
"C. c #00B400",
"Z. c #57C63F",
"A. c #AFF282",
"S. c #ACFF86",
"D. c #9EE373",
"F. c #ADF77C",
"G. c #9EE071",
"H. c #B0F87F",
"J. c #A6F074",
"K. c #C9D8BE",
"L. c #C8C8C7",
"P. c #E6DFE6",
"I. c #8ADC6B",
"U. c #40C017",
"Y. c #78DC52",
"T. c #B2F57F",
"R. c #B8FF81",
"E. c #A6EA76",
"W. c #B2FA7F",
"Q. c #B6FF82",
"!. c #A3E872",
"~. c #B3FF7C",
"^. c #AAF972",
"/. c #C9DABE",
"(. c #EAE6EC",
"). c #A7A8A7",
"_. c #DADCD9",
"`. c #B3D29B",
"'. c #C7D99A",
"]. c #B1D493",
"[. c #9BDD70",
"{. c #97D56C",
"}. c #A1E474",
"|. c #A3E973",
" X c #9FD07E",
".X c #B9E09F",
"XX c #AFD992",
"oX c #CAD3C4",
"OX c #EAE9EC",
"+X c gray92",
"@X c #D7E0D1",
"#X c #CED5CB",
"$X c #EEE9F8",
"%X c #D3D6D2",
"&X c #A6F273",
"*X c #B1FF7A",
"=X c #A0E96E",
"-X c #ACFA77",
";X c #AAFF6F",
":X c #BBDAA5",
">X c #EEE2F6",
",X c #E1DDE4",
"<X c #D5D4D6",
"1X c #E6E7E6",
"2X c gray71",
"3X c #E1E4DF",
"4X c #DDE1DB",
"5X c #E8E7E7",
"6X c #DFE2DC",
"7X c #D1EAC0",
"8X c #D5F1C3",
"9X c #CFE7BE",
"0X c #D3EDC2",
"qX c #D3F0BF",
"wX c #D7E3CF",
"eX c #E7E6E7",
"rX c #E3E4E2",
"tX c #DFE0DF",
"yX c #C6C6C6",
"uX c #EAE5ED",
"iX c #E9E3ED",
"pX c #E9E4ED",
"aX c #E8E6EA",
"sX c white",
/* pixels */
"  . X . o O + @ X # $ % & * * * ",
"= - ; : > , < 1 2 3 4 5 6 7 8 9 ",
"0 q w e r t y u i p a s d f g h ",
"j k l z x c v b n m M N B V C Z ",
"A S D F G H J K L P I U Y T 8 R ",
"E W Q ! ~ ^ / ( ) _ ` ' ] [ { } ",
"A |  ...X.o.O.+.@.#.$.%.&.*.=.} ",
"A -.;.:.>.,.<.1.2.3.4.5.6.7.8.R ",
"E 9.0.q.w.e.r.t.y.u.i.p.] a.s.d.",
"f.g.h.j.k.l.z.x.c.v.b.n.m.M.N.* ",
"B.V.C.Z.A.S.D.@.F.G.H.J.K.a.L.9 ",
"P.I.U.Y.T.R.E.W.Q.!.~.^./.(.).d.",
"_.`.'.].[.b.{.}.|. X.XXXoXOX+X9 ",
"@X#X$X%X&X*X=X-X;X:X>X,X<X1X2X* ",
"3X4X5X6X7X8X9X0XqXwXeXrXtX9 yX} ",
"  eX* eXuXiXuXpXpXaX* 9 R * +X9 "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
