#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 193 2 ",
"   c #010101",
".  c #0B0B0B",
"X  c #080807",
"o  c #120F05",
"O  c #1C1604",
"+  c #0F1010",
"@  c #141413",
"#  c #1A1A1A",
"$  c #1C1A15",
"%  c #241B00",
"&  c #3F3310",
"*  c #362B07",
"=  c #222222",
"-  c #2C2C2C",
";  c #27282B",
":  c #3D3D3D",
">  c #353534",
",  c #2B2D32",
"<  c #423611",
"1  c #43350B",
"2  c #403D33",
"3  c #58450A",
"4  c #755601",
"5  c #765902",
"6  c #795B04",
"7  c #7B5E0A",
"8  c #665112",
"9  c #7D610D",
"0  c #7D6213",
"q  c #7E6519",
"w  c #504524",
"e  c #5E522E",
"r  c #4E493A",
"t  c #59533F",
"y  c #4E462C",
"u  c #6C5E34",
"i  c #7D6623",
"p  c #7E692A",
"a  c #7B6A34",
"s  c #7E6E3C",
"d  c #3D3F43",
"f  c #424242",
"g  c #4C4C4C",
"h  c #464748",
"j  c #51504F",
"k  c #535353",
"l  c #5B5B5B",
"z  c #796C49",
"x  c #7D714C",
"c  c #7E7046",
"v  c #7E7352",
"b  c #656258",
"n  c #646464",
"m  c #6C6C6C",
"M  c #706F6F",
"N  c #7D7762",
"B  c #7F7965",
"V  c #7A776D",
"C  c #747474",
"Z  c #7F7C74",
"A  c #7D7D7D",
"S  c #816513",
"D  c #80661B",
"F  c #83691C",
"G  c #856916",
"H  c #836B23",
"J  c #846E2A",
"K  c #87702C",
"L  c #89722C",
"P  c #897024",
"I  c #816E33",
"U  c #867133",
"Y  c #8A7434",
"T  c #8B773A",
"R  c #8D793D",
"E  c #917C3E",
"W  c #837343",
"Q  c #8E7B43",
"!  c #83764D",
"~  c #8A7B4D",
"^  c #917E44",
"/  c #917F4A",
"(  c #817553",
")  c #857955",
"_  c #837A5C",
"`  c #897D5A",
"'  c #847854",
"]  c #857D65",
"[  c #837D6C",
"{  c #827E72",
"}  c #807F7E",
"|  c #7F807F",
" . c #92814C",
".. c #988242",
"X. c #8D815B",
"o. c #958454",
"O. c #968759",
"+. c #97885A",
"@. c #998A5D",
"#. c #9D8B55",
"$. c #9B8C62",
"%. c #9C8F69",
"&. c #948969",
"*. c #9E9066",
"=. c #9E926C",
"-. c #8A8575",
";. c #81817E",
":. c #8E8A7D",
">. c #878378",
",. c #918971",
"<. c #96907F",
"1. c #9D9375",
"2. c #89826E",
"3. c #A1946E",
"4. c #A89768",
"5. c #A19573",
"6. c #A3997C",
"7. c #A99E7D",
"8. c #A79B76",
"9. c #7E7F80",
"0. c #7F8082",
"q. c #818182",
"w. c #8C8C8C",
"e. c #8A8881",
"r. c #918D83",
"t. c #9A9485",
"y. c #95938D",
"u. c #9B9587",
"i. c #8D8E90",
"p. c #8F9092",
"a. c #959594",
"s. c #989796",
"d. c #96979A",
"f. c #9A9B9B",
"g. c #999896",
"h. c #A59D83",
"j. c #A89F83",
"k. c #A59E89",
"l. c #A09F9A",
"z. c #ABA184",
"x. c #AAA28B",
"c. c #A7A088",
"v. c #ACA693",
"b. c #A2A19D",
"n. c #ADA799",
"m. c #AEA99A",
"M. c #AAA496",
"N. c #B2AC9B",
"B. c #B6AE95",
"V. c #9F9FA0",
"C. c #A3A3A3",
"Z. c #A9A7A3",
"A. c #ACAAA3",
"S. c #A6A7AA",
"D. c #A7A8AC",
"F. c #ACACAC",
"G. c #B2AEA3",
"H. c #B0AEA8",
"J. c #B5B1A7",
"K. c #B5B3AC",
"L. c #B9B6AE",
"P. c #BDB9AD",
"I. c #AFAFB0",
"U. c #AFB0B1",
"Y. c #B5B4B3",
"T. c #B8B7B3",
"R. c #BAB9B6",
"E. c #B4B5B9",
"W. c #BBBBBB",
"Q. c #C2BCAC",
"!. c #C2C1BE",
"~. c #CBC6BB",
"^. c #BDBEC1",
"/. c #BEC0C5",
"(. c #BFC1C8",
"). c #C3C4C4",
"_. c #C9C8C6",
"`. c #C4C6CB",
"'. c #C6C8CC",
"]. c #CCCCCC",
"[. c #C8C7C6",
"{. c #C7CAD1",
"}. c #CACCD1",
"|. c #D5D5D5",
" X c #DCDCDC",
".X c #D8D9DB",
"XX c #DFE0E1",
"oX c #E6E6E6",
"OX c #EAEAEA",
"+X c #EDEEF3",
"@X c #EEF1F7",
"#X c #F4F4F4",
"$X c #FBFBFB",
/* pixels */
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXOXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXOXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXOXOXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX+XOXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoX",
"oXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X|.|. XoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoX X.X|..XOXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoX.X|.]. XoXoXoXoXoXoXoXoXoXoXOXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXOXoXoXoXoXoXoXOXoXoXoXn       ; C.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXf.;     # q.oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXC       y.$XXXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX Xn j C >   @ |.OXoXoXoXoXoXoXoXoXoXoXoXoXoXoX$Xk # M j     a.#XXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXl : =   g.#XXXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoX XOX$XW.    ].OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX).|.+XOXf   n $XXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX XoXf   f.#XoXoXoXoXOXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX].W.m   m oXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXOXOXXX#X>   { $XoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoX:   f.#XXXoXoXoXoXoXoXoXoXOXoXoXOXoX",
"oXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXOXk     . C.OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX#Xq.  - |.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX:   g.#XoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXOXE.s.n   . _.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXA   # ).#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX:   s.#XoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX#X$X|.=   S.#XoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXA   , ].#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX#Xf   C.$XoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX].> e.s.l     ).OXoXoXoXoXoXoXoXoXoXoXoXoXoXoX+Xe.  X n a.A F.oXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXW.f.,   m S.].oXoXoXoXoXoXoXoXOXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXOX|..       # w.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX#Xg           l OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXg           a.#XoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX].W.Y.Y.].OXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoX).F.F.K.Y.F.).oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX).H.K.F.F.Y.|.oXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX#X#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX#X#X#X#X#XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX#X#X#X#XOXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXOXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX XoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXXXXXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X].].|.}.}.|.].|.].|.}.].|.|.].}.].|.].].].].|.|.}.].|.].|.}.}.|.|.|.].|.].|.].].].].|.].].].|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.XXoXoXoXoX",
"oXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.R.W.W.R.R.R.W.R.R.W.R.R.W.W.R.E.R.R.R.).).R.W.W.R.W.R.W.R.W.Y.W.R.W.W.E.R.W.W.W.R.W.W.}.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|. XOXoXoXOX",
"oXoXoXoXoXoXoXoXoXoXoXOXoXoXoXOXoXoXoXoX|.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.^.W.W.R.).`.R.W.W.^.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.].oXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoX.XW.R.W.W.W.W.W.W.W.W.W.W.W.W.W.^.K.h.M.W.W.W.).).R.^.K.h.m.W.R.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.}.OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.W.W.W.W.W.W.W.W.W.W.W.R.^.6.7 o.^.W.W.).).Y.^.x.0 T W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.R.}.OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoX.XW.W.W.W.W.W.W.W.W.W.W.W.W.W.R.^.m.F J W.^.W.`.].W.`.5.5 %.^.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.}.oXoXoXoXXX XoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXOX|.W.W.W.W.W.W.W.W.R.W.W.W.W.W.W.W.W.T I y.V.a.a.s.f.f.X.0 v.^.W.R.W.W.W.W.R.W.W.W.W.W.W.^.Q.W.].oXoXoXoXXXb.[.OXoXoXoXoXoXoXoXK.R.oXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX XW.W.W.W.W.W.W.W.^.W.W.W.W.W.W.I.C.>.A A 9.A A A 9.A A Z s.S.W.W.W.W.W.W.^.W.W.W.W.W.W.W.W.W.|.oXXXoXoXOX}.f.].OXoXoXoXoXOXY.C.XXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXOXoXoXoXoXOXoXoXoXoXoXOX.XW.W.W.^.Q.W.W.^.c.v.^.W.^.W.a.q.A } q.9.A A Z Z A 9.9.q.9.A e.F.W.W.^.T.6.T.W.W.W.W.W.W.W.W.].oXoXoXoXoXOX|.g.].OXoXoXOXY.C.oXoXoXoXoXoXoX X XOXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.W.W.W.^.m.0 J N.W.C.w.A 9.9.A A { y.V.S.S.d.>.A A 9.9.A e.d.Y.W.O.5 $.^.W.W.W.W.W.W.W.].oXoXoXoXoXoXOX|.s.].OXOXY.V.oXoXoXoXoXoXoXoX XXXoXoXoXoX",
"oXOXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.R.W.W.W.W.W.Y.O.7 J y.9.A 9.A e.C.~ q v.).[.].W.T J u.a.A A A A i.o.7 J v.W.W.W.W.W.W.W.R.|.oXoXoXoXoXoXoXOX|.f.}.W.b.oXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.W.W.W.Y.^.W.O.a A } A q.l.W.W.=.5 3.W.!.`.G.D L K.W.I.w.A ;.0.v U m./.W.W.W.W.W.W.W.R.|.oXoXoXoXoXoXoXoXOX Xq.f.OXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"OXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.W.W.W.W.W.W.W.f.9.q.9.w.F.^.W.^.v.7 / Y.).].6.7 o./.R.W.W.g.q.0.0.w.E.W.W.W.W.W.W.W.W.W.}.oXoXoXoXoXoXoXoXoXE.l.V.].oXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XR.R.W.W.W.W.W.W.F.A } q.N Y N.W.W.^.K.J D H.).{.~ 9 5.).R.W.W.+.c 0.| A a.W.W.W.W.W.W.W.W.R.|.oXoXoXoXoXoXoXOXY.V.oX|.f._.OXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoX.XW.W.W.W.W.W.W.W.a.A A w.&.6 J m.^.W.Y.o.p e.q.i.! J M.W.W.W.+.6 L y.A A q.F.W.W.W.W.W.W.W.R.}.oXoXoXoXoXoXOXY.C.oXoXoX|.f.].OXoXoXoXoXoXoX XXXOXoXoXoX",
"oXoXoXoXoXoXOXoXoXoXoXoXoXoXoXOXoXoXoXOX.XR.W.W.W.W.R.W.f.A q.} F.W.+.7 J N.Z.q.;.q.A A A 9.q.9.a.Y.O.6 J N.W.p.A 9.e.Y.W.W.W.W.W.W.R.|.oXoXoXoXoXOXY.C.oXoXoXoXOX|.f.].oXoXoXoXoXoX X XOXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.W./.^.^.Y.q.A A f.W.W.W.@.6 W q.A } 9.q.9.9.q.} 9.9.[ 9 J m.^.W.Y.0.9.A V.^.W./.W.R.W.W.}.oXoXoXoXoXI.C.oXoXoXoXoXoXoX|.d.[.OXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoX.XR.W.T.+.1.J.Z.q.A q.Y.W.R.W.E.&.N q.9.q.[ ( M.,.v q.q.q.A ( M.^.Y.W.W.d.A A a.L.x.O.v.^.W.R.|.oXoXoXoX XR.XXoXoXoXoXoXoXoXOX].W.oXoXoXoXoX X XoXoXoXoX",
"oXoXoXOXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoX|.W.^.n.F 7 q ] q.A s.T.^.).^.Z.9.q.q.Z b.O.9 3.E D m.-.9.q.9.a.W.^./.W.m.0.| | I 9 5 $.W.W.W.}.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoX XXXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoX XW.W.L.6.+.Q Z 9.9.! R =.k.H.w.A 9.;.i Y +.q D 0 Q O.0 N q.9.A Z.N.5.O.U Z q.9.( ..=.m.W.W.R.|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.^.`.C.A 9.;.U 7 6 0 J { q.9.Z.@.7 H Q *.+.Y 7 L m.w.A q.~ F 7 6 q ] 0.A w.W./.^.W.W.R.}.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXOXoXoXoXOXoXoXoXoXoXoXoXoX|.W.W.W.W.W.F.} A w.K.N.5.Q p Z 0.V Y o.U @.R.).].c.L  .R ( 9.q.c J $.x.K.b.A | d.W.Y.R.W.W.W.}.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX X XOXoXoXoX",
"oXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoX.XW.R.R.R.W.f.A A a.W.W.W.W.a.A 9.] H 5 J K.R.).).W.$.5 0 W 9.A q.Y.W.W.W.F.A | w.W.^.`.W.W.Y.|.OXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXOXoXoXoXOX.X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.)._._.`.].F.A 9.f.].).).].f.A A C.Q.z.v._.)._.]._.P.7.B.R.;.;.A ).[.)._.Y.A 0.e.L.c.=.R.].[.|. X X.X XXX X X X X X X X X X X XXX X X X X X|. XoXoXoXoX",
"oXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.).).).)._.F.A A f.].).)._.f.A A F.}.{.].).).[.].).`.{.}.^.q.9.;.W.`.).`.Y.A 0.A Q S 7 h.].Q.}.W.).W.^.W.!.W.)./.W.!.W.^.W.^.W.(.Q.^.W.^.W.[.XXoXoXoXoX",
"oXoXoXoXoXoXOXoXoXoXOXoXoXoXoXoXoXoXoXoX|.W.W.6.$.%.,.9.9.-.*.%.=.*.-.9.9.,.*.$.6.Y.E.!.).Y.R.Y.Y.R.p.} } Z.G.6. .H v q.A c ^ / Y v.W._.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.W.W.).XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.Y 4 5 a q.q.x 4 6 5 5 x q.0.a 5 4 Y W.W.).`.W.W.^.`.E.e.} 9._ 0 6 7 F _ 0.A a.x.F 0 T o._.R.5.@.W.W.W.R.@.5.Y.W.^.G.@.8.^.W.^.m.o.x.W.).XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoX.XW.W.M.6.j.<.A 9.e.7.h.6.7.:.9.A <.z.6.x.W.R.).[.E.W.x.$.Q _ 9.9.B Y $.h.N.f.A A q.x S @.Y 7 ~.K.J 7 T.W.W.Y.6 Y K.W.W.k.7 Y `.R.^.h.4 @.W.).XXoXoXoXoX",
"oXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.^.^.`.S.A 9.f.`.^.^.{.f.A A S.`./.^.W.W.).[.W.R. .5 0 W q.A e.F.W././.Y.i.0.q.A r.M.0 / ].T.Y S R.W.).T.9 R L.W.).v.0 Q `.W.^.h.4 $.^.).oXoXoXoXoX",
"oXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXOX.XQ.W.R.T.W.C.A 9.a.W.R.E.W.a.9.A C.W.Y.R.W.W.).).W.^.j.@.N.Y.w.A A f./.R.R.^.h.( A q.0.q.v ,.W.Z.W J F.I.U.Z.p ~ Z.F.Y.k.p ~ E.F.E.h.q &.I.T. XOXoXoXoX",
"oXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.(.`.`.S.A A f.{.^.(.'.f.A A S.`.(.^.W.W.).).R.W.W./.W.W.g.A A w.Y.W.^.x.D q >.A } 0.q.9.A q.;.9.0.;.0.;.q.;.0.0.0.9.9.q.9.9.9.9.} } q.C ).OXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.$.T ^ ` 9.9.] E ^ Q E ] q.9.` Q Q %.W.R./.).W.W.W.W.W.W.F.e.9.A a.^.x.D 0 =.Y.i.q.q.| A A A 0.q.;.A A A q.0.A 9.A 9.9.9.9.} } 9.9.9.9.C [.OXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoX|.W.W.Q 7 9 c 9.q.v 7 0 q 7 v q.0.s 9 7 Q W.R.).`.R.W.W.W.W.W.W.S.9.A 9.t.F 7 =.^.W.W.h.D _ w.a.w.[ B w.w.p.w.B [ w.w.y.e.] { i.w.p.e.N >.y.w.].OXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoX|.W.W.v.h.x.t.9.9.r.x.k.k.x.r.9.9.t.x.h.M.W.R.).[.W.W.W.W.W.W.W.W.w.A q.A s 3.W.W.R.^.@.7 =.`.].L.L 9 W././.L.9 T L.W./.x.0 E `.W.).j.5 *.W.).XXoXoXOXoX",
"oXOXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.W.^.).C.A A f.).^.^.).f.A A Z.`.^.W.W.R.).).W.W.W.W.W.W.R.W.U.q.q.0.q.V.W.W.W.W.T D M.W.].K.Y q R.W.W.L.0 R K.W.^.v.q Q ^.T./.j.5 $.W.).XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXOX.XW.W.W.W.^.C.A A g./.R.W.W.d.A A C.^.W.W.W.W.).).W.W.W.W.W.W.W.^.x.p N 0.} A a.F.^.N.F J Y.W.].J.U S Y.W.W.L.0 R K.W.^.x.q Q ^.E.`.h.5 $.W.!.XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.R.L.R.b.9.A s.R.Y.T.R.a.9.A b.R.Y.Y.W.R.).).R.W.W.W.W.W.W.h.D 9 &.w.A A 9.A d.<.i o.`.W.|.L.Y 9 W.^.).T.7 Y T.^./.v.7 R {.W.`.j.4 $.^.[.oXoXoXoXoX",
"OXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.R.$.T ^ ` 0.| ] R ^ ^ E ] 9.9.` E R $.W.W.^.[.R.W.W.W.W.W.W./ 7 =.^.I.d.e.A ;.A A { :.f.f.F.l.) s C.Z.C.l.s ` b.C.Z.u.I ` D.C.F.t.a ,.C.C..XOXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.R.E 6 6 s q.q.x 6 0 7 7 ! 9.q.I 9 5 R W.R.).`.W.W.W.W.W.W.W.K.h.W.W.W.W.S.q.A 9.0.q.9.A A A A 0.q.9.A A A q.q.A A A 9.q.9.9.A A A 9.9.9.C ).OXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXOX|.W.W.Y.K.T.l.A A a.T.J.J.L.a.A A f.T.K.Y.W.W.)._.Y.W.W.W.W.W.W.W.^.W.W.W.W.W.R.S.y.V ;.A q.A A A 9.q.A A 9.A q.9.A A A 9.q.0.A A A 9.q.} } C ).OXoXoXoX",
"oXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.W.W.).S.A A s.).W.W.).f.A A Z.).^.W.W.R.).`.W.W.W.W.W.W.W.R.W.W.W.W.W.W.W./.6.0 ,.V.V.a.V.a._ ( s.s.d.a.v ] a.f.f.r.( ] f.a.f.e.x -.f.s.|.OXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.XW.W.W.W.).C.A A f.^.W.W.^.f.A A C.^.W.W.W.W.)._.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.R. .6 x.).W.W.|.L.Y S R.^.).R.9 T R.^.).v.S R `.W.{.z.5 *.^._.oXoXoXoXoX",
"oXoXOXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoX|.W.W.R.Y.W.C.A A g.W.R.W.W.a.A A C.W.R.R.W.W.).).R.W.W.W.W.W.W.W.W.W.W.W.W.W.W.L.J H H.W.W.W.].J.Y 0 Y.W.W.L.7 Y K.W.^.x.9 T `.Y.^.7.5 $.^.Q.XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX|.W.W.^ 0 S W 0.0.v S D D S v 0.q.W S 9 ^ R.W.).[.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.v.c.T.W.W.W.].L.^ J R.W.W.R.H / Y.W.W.M.J  .`.R.).c.q =.W.).XXoXoXoXoX",
"oXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoX|.W.R.O.J L ! q.0._ P U L L _ 9.9.( L J O.W.Y.).[.E.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.R.].W.K.K.W.W.W.W.J.L.W.W.W.R.K.K.W.W.W.R.J.Y.W.).XXoXoXoXoX",
"oXoXoXOXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoX|.W.W.L.J.J.l.q.q.a.K.G.J.J.a.q.q.l.K.A.K.W.R.)._.W.W.W.W.W.W.W.W.W.W.W.W.W.W.R.W.W.W.W.W.W.W.].W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.).XXoXoXoXoX",
"oXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoX XW.W.T.Y.).C.m M y.`.W.W.`.a.m m C.).)./.^.W.).).W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.].W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.).XXoXoXoXoX",
"oXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X_.).R 0 4.r     d .X].). Xr     m  X)._._._.]..X X X|.|..X.X|.|..X|..X.X|..X.X|. X|. X|. X|.|.|. X|.|.|.|. X|.|. X|..X.X|. X|.|..X.X|.|.|.|.XXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X(.h.Y J 4 O     e 6.n.E.`.>     } ).Y.W.W.Y.W. XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX X XOXoXoXoX",
"oXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoXOXoXoX~.=.J q 7.-.    o 9 9 F E ~ #     q.].W.W.W.W.). XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX@X#.0 Q q H >     @ h.O.J G 3     X z N.H.R.W.W.W. XoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX+X8.9 8.5.%       g ^.^.Y.N.t     O 5 7 U n.^.^.Q. XoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXoXoX#XOX+XoXoXoXoXoXoXoXoXoX+XQ.8 w ,       2 Y.W.R.^.Y.;     b 6.Q L H.^.W.W. XoXoXoXoX|. XOXoXoXoXoXoXoXoXoX|.|.oXoXoXoXoX|.oXoXoXoX X|.oXoXoXoXoXoXoXoXoXoX|.XXoXoXoXoX X XoXoXoXoX",
"oXoXOXoXoXoX|.- # f .XoXoXoXoXoXoXoXoX#Xj           < P x.^.R.).;.    X a.`.Y.L.W.W.W.). XoXoXoXOX_.g. XoXoXoXoXoXoXOX|.f.|.oXoXoXoXoX|.oXoXoXoXoXC.W.OXoXoXoXoXoXoXoXZ.T.oXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXOXa.      R.OXoXoXoXoXoXoXXX#Xr         2 5.9 q k./.F.#     ; W.W.W.W.W.W.W.W. XOXoXoXoXOX).f. XOXoXoXoXoX|.g.|.oXoXoXoXoXoX|.oXoXoXoXoX Xf.).oXoXoXoXoXoXS.I.oXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoX#Xh   #   m OXoXoXoXoXoXoXXX$X:   * y n Y.).=.7 q x.h     # a.^.W.R.W.W.W.W.^. XoXoXoXoXoXOX!.f. XoXoXOX|.f.].OXoXoXoXoXoXoX|.oXoXoXoXoXoXXXf.Q.+XoXoXoXF.F.oXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoX_.@ # Z   = oXoXoXoXoXoXoXoXOXS.>.S ..!.W.W.W.5.G <       m _.E.W.W.W.W.W.W.W.oXoXoXoXoXoXoXOX).f. XOX|.s.].OXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoX XV.^.oXoXZ.I.OXOXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoX#Xi.  > .X=   I.OXoXoXoXoXoXoXoXXXW.U 0 m.^.Y.).W.r       , F.W.W.W.W.W.W.W.W./. XoXOXoXoXoXoXoXOX!.b.].f.].OXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoX XV.).Y.F.oXoXoXoXoXoXoXoXoX X XOXoXoXoX",
"oXoXoXoXOXk   C $Xl   n #XoXoXoXoXoXoXoX|.W.$.5 6./.].f.:       O ] ].Y.W.W.W.^.W.W.^.Q. XoXoXoXoXoXoXoXoX+XW.m ).OXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXOXXXA a.OXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXOX).#   - h =   -  XoXoXoXoXoXoXoX.X`.c.9 #.f.k @       @ 0 J h.W.W.W.W.W.W.W.W.). XoXoXoXoXoXoXoXoX|.V.Y.C. XoXOXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXF.I.m.Q.+XoXoXoXoXoXoXoXoX X XOXoXoXoX",
"oXoXoX#Xf.  X X   X   . S.#XXXoXoXoXoXOX].F.>.& % +         > b.=.7 D n.W.W.W.W.W.W.W.W. XoXoXoXoXoXoXOX|.f._.#X).f. XoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXS.F.OX XV.^.OXoXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXf   C OXoX#Xg   b +XoXoXoXoXXX$X:               # e.W.^.^.%.o.R.W.W.W.W.W.W.W.^. XoXoXoXoXoXoX|.f.].oXoXoX).f. XoXoXoXoXoXoXoX|.oXoXoXoXoXoXOXS.I.oXoXoXoXf.^.OXoXoXoXoXoXoX.X XoXoXoXoX",
"oXoXoX XA n _.OXoXoXR.n a. XoXoXoXoXXX$Xf         . - k f.).W.W.W.W.W.W.W.W.W.W.W.^.^.Q. XoXoXoXoXoX|.f.].oXoXoXoXOX).f. XoXoXoXoXoXoX|.oXoXoXoXoXoXA.I.OXoXoXoXoXXXf.^.oXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoX$X$XOXoXoXoXOX$X#XoXoXoXoXoXXX$X:   , $ * u Y.).).W.W.W.W.W.W.W.W.W.W.W.W.W.W.W. XoXoXoXoX|.a.].oXoXoXoXoXoXOX).f. XoXOXoXXXoX|.oXoXoXoXoXS.K.OXoXoXoXoXoXOXXXf.Q.+XoXoXoXoX XXXOXoXoXoX",
"oXoXoXoX XoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX_.F.Y.A.J L K.W.Y.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.oXoXoXoXoX|.|.OXoXoXoXoXoXoXoXoX_.|.oXoXoXoXoX|.oXoXoXoX X).oXoXoXoXoXoXoXoXoX|.`.oXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX XW.W.).R 7 6.^.E.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^. XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXOXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.W.W.^.6./ v.^.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^. XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX.X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXOXoXoXoXoXoXoXoXoXoX|.W.W.W.Y.R.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^. XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoX XW.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.`. XoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|.oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXoXoX|.W.W.E.W.W.W.W.W.W.W.W.W.W.W.R.W.R.W.W.R.W.R.Q. XOXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXOX|.oXOXoXoXOXoXoXoXoXOXoXOXoXoXoXoXoXoXoXoXoXOX X XoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX|._._.`._._.`._.[._._._._._.`.[._.].`._.[.`._._.|. X|.|.|.|.|..X X|.|.|.|.|.|.|.|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|.|.|.|.|. X|.|. XoXoXoXoX",
"oXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXoXoXoXoXoXoXXXoXoXoXoXoXoXoXoXXXXXXXoXXXoXXXXXoXoX XoX XoXXXoXoXoXoXoXXXoXXXXXXXoXXXoXXXXXoXXXoXXXoXXXoXoXXXXXXXXXXXoXXXoXoXoXOXoXoXoX",
"oXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXOXoXoXOXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX",
"oXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 187 2 ",
"   c #010101",
".  c #0B0904",
"X  c #0A0A09",
"o  c #060609",
"O  c #161103",
"+  c #181100",
"@  c #0F0F10",
"#  c #1B1B1B",
"$  c #151515",
"%  c #2F2506",
"&  c #372A04",
"*  c #20201F",
"=  c #222222",
"-  c #2B2B2B",
";  c #333333",
":  c #3A3A3A",
">  c #46380D",
",  c #53420D",
"<  c #544313",
"1  c #775903",
"2  c #795C05",
"3  c #755B0B",
"4  c #7A5E0A",
"5  c #7A5F10",
"6  c #67541C",
"7  c #7D610D",
"8  c #7D6313",
"9  c #7E6519",
"0  c #45402E",
"q  c #514620",
"w  c #45433E",
"e  c #6A5B2F",
"r  c #6A5E3A",
"t  c #7D692C",
"y  c #7D6722",
"u  c #7C6934",
"i  c #7D6C3B",
"p  c #414244",
"a  c #4A4A4A",
"s  c #4F504F",
"d  c #5B584E",
"f  c #545454",
"g  c #5B5B5B",
"h  c #535559",
"j  c #7E724E",
"k  c #6A675F",
"l  c #7E7455",
"z  c #7D755C",
"x  c #646465",
"c  c #6A6A6A",
"v  c #7E7865",
"b  c #7F7A6B",
"n  c #7C7664",
"m  c #6F6F70",
"M  c #737373",
"N  c #7E7C74",
"B  c #7D7D7D",
"V  c #80630D",
"C  c #806516",
"Z  c #80671B",
"A  c #82691D",
"S  c #846815",
"D  c #846C24",
"F  c #856E2A",
"G  c #87702C",
"H  c #89722E",
"J  c #8B7124",
"K  c #826F35",
"L  c #897433",
"P  c #81703C",
"I  c #8A763A",
"U  c #8D783C",
"Y  c #837033",
"T  c #917C3E",
"R  c #927B35",
"E  c #837242",
"W  c #8E7B43",
"Q  c #82744A",
"!  c #8E7E4C",
"~  c #907D44",
"^  c #917F4A",
"/  c #8A7C52",
"(  c #83795B",
")  c #817963",
"_  c #837D6C",
"`  c #817E74",
"'  c #807E79",
"]  c #93814C",
"[  c #99854B",
"{  c #958453",
"}  c #968759",
"|  c #97885B",
" . c #998A5C",
".. c #9F8C54",
"X. c #A3925F",
"o. c #8D8364",
"O. c #938762",
"+. c #9B8D64",
"@. c #9B8E69",
"#. c #978A63",
"$. c #9E916C",
"%. c #9E9066",
"&. c #858174",
"*. c #898475",
"=. c #84827B",
"-. c #89867B",
";. c #958E7B",
":. c #9E9371",
">. c #9B937D",
",. c #A19369",
"<. c #A19573",
"1. c #A49A7C",
"2. c #A89C77",
"3. c #AEA179",
"4. c #7E7F81",
"5. c #7F8083",
"6. c #838384",
"7. c #888782",
"8. c #8B8A85",
"9. c #838589",
"0. c #8B8B8B",
"q. c #928F85",
"w. c #92918D",
"e. c #99968B",
"r. c #9E9989",
"t. c #8D8E91",
"y. c #939393",
"u. c #9B9994",
"i. c #969799",
"p. c #9D9C9C",
"a. c #979899",
"s. c #A59C82",
"d. c #A79F88",
"f. c #A89F84",
"g. c #A19E96",
"h. c #ACA285",
"j. c #A9A28B",
"k. c #A7A089",
"l. c #A5A195",
"z. c #ACA593",
"x. c #AEA897",
"c. c #A3A29C",
"v. c #ABA699",
"b. c #AEA99A",
"n. c #B1AB9D",
"m. c #B3AB95",
"M. c #B9B29D",
"N. c #9FA0A3",
"B. c #A3A3A3",
"V. c #AFADA6",
"C. c #ACACAD",
"Z. c #A6A6A8",
"A. c #B2AEA3",
"S. c #B4B0A6",
"D. c #B4B2AC",
"F. c #BAB7AC",
"G. c #AFAFB2",
"H. c #AFB0B1",
"J. c #B5B5B4",
"K. c #B8B7B3",
"L. c #B9B8B6",
"P. c #B6B7B9",
"I. c #BBBBBB",
"U. c #B7B8BA",
"Y. c #C0B89F",
"T. c #C1BFBD",
"R. c #C0BDB5",
"E. c #C3C2BE",
"W. c #CAC4B5",
"Q. c #BDBEC1",
"!. c #BFC0C4",
"~. c #BFC1C8",
"^. c #C3C4C4",
"/. c #C2C4CA",
"(. c #C7C8C9",
"). c #CBCBCB",
"_. c #CDCED1",
"`. c #D5D5D5",
"'. c #DCDCDC",
"]. c #D1D2D8",
"[. c #E6E6E6",
"{. c #E7E7E8",
"}. c #EAEAEA",
"|. c #ECEDF1",
" X c #EFF1F8",
".X c #F2F2F2",
"XX c #FAFAFA",
/* pixels */
"[.[.[.[.[.[.[.{.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.{.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.}.[.[.[.[.[.[.[.'.'.{.[.[.[.[.[.[.{.[.[.[.[.{.[.[.[.[.[.'.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.'.[.[.[.{.[.[.[.[.[.[.[.}.[.[.[.",
"[.[.[.[.[.{.[.[.[.{.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[..XXXXX.X[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.|.XXXX|.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.{.XXXXXX{.[.[.[.[.{.[.[.[.[.[.[.[.[.[.",
"{.[.[.{.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.`.u.=.6.Z.[.[.[.[.[.{.[.[.[.[.[.[.[.{.[.[.'.C.8.6.c.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.(.y.B 6.'.{.[.[.[.[.[.[.[.{.[.[.[.[.[.",
"[.[.[.[.[.{.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.}.7.        m {.[.[.[.[.[.[.[.[.[.[.[.[.[..Xg.        f '.{.[.[.[.{.[.{.[.[.{.[.[.[.[.{.g       ).}.[.[.[.[.[.[.[.[.[.}.[.[.[.",
"{.[.[.{.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.}.I.C.'.i.  $ {.[.[.[.[.[.{.[.[.[.[.[.[.[..XZ.M `.J.$   J.}.[.{.[.[.[.[.[.[.[.[.[.[.[.[.V.B.- o `.{.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.{.[.[.[.[.[.}.[.[.[.[.}.[.[.[.[.}.[.[.{.[.[.[.[.}.|.XXZ.  s {.[.[.[.[.{.[.[.[.[.[.[.[.[.[.}..X}.XX;   J..X[.[.[.{.[.[.{.[.{.[.[.[.[.[..X{.-   _.}.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.{.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.w.    $ T.}.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.'..XB.  : '.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.-   `.}.[.[.{.[.{.[.[.[.}.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.}.J.x a   : [.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[..XB.X * ^.}.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.-   `.[.[.[.[.[.[.}.[.[.[.[.[.[.}.",
"}.[.[.[.}.[.[.[.[.[.[.}.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[..XXX'.$ X (.}.[.[.[.[.[.[.[.{.[.[.[.[.'.}.a.o - `.XX[.[.[.{.[.[.[.{.[.[.[.[.[.[.[.[..X|.-   '..X[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.{.[.[.[.[.[..Xg g 0.f   = '.[.[.[.[.[.{.[.[.[.[.[.[.[..XC.X   g 6.c E.}.[.[.[.[.[.[.[.{.[.[.[.[.[.[.D.5.#   B B.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.{.[.[.[.|.x       : F.}.[.[.[.[.[.[.[.[.[.[.{.[.[..Xw.          g.}.[.[.[.[.[.[.[.[.[.[.[.[.[.}.g         : '.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.'.`.`.[.}.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.`.`.`.`.`.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.{.'.`.`.`.`.'.[.[.[.[.[.}.[.[.}.[.[.[.}.",
"[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.}.}.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.}.}.}.}.}.[.[.[.[.{.[.[.[.[.[.[.[.{.[.[.[.{.}.{.}.}.{.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.}.[.[.[.[.[.[.[.[.[.}.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.{.[.{.{.{.[.[.[.[.{.{.[.[.}.[.[.[.[.[.}.[.[.[.[.{.{.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.",
"[.[.[.}.[.[.[.}.[.[.[.[.[.}.[.[.[.}.'._.`.`._.`._._.`.`._.`.`._.`._.`.`.).`.`.`.`._.`._._.`.).`.`._._.`._.`._._.`._.`._.`.`.`.`.`.`.`.`.`.`.`.'.`.`.`.`.'.`.`.`.`.`.`.[.[.[.[.[.",
"[.}.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.F.I.L.I.L.I.I.J.I.J.I.I.J.I.L.I.I.L.L.I.^.L.L.I.I.I.J.I.L.L.L.I.L.I.L.I.J.I.L.I.F.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.'.I.L.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.I.I.I.I.^.^.L.I.I.Q.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.L.'.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.'.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.1.+.J.I.J.E.(.J.^.k.#.A.I.I.I.I.I.I.I.I.I.I.I.I.I.I.L.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.[.'.I.L.I.I.I.I.I.I.I.I.I.I.J.I.I.I 7 A.Q.I.(.(.L./.] 4 j.Q.I.I.I.I.I.I.I.I.I.I.I.I.I.L.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.L.I.I.I.I.I.L.I.I.I.I.I.I.Q.1.2 1.I.J.J.I.J.D.G H L.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.`.[.[.[.[.(.`.}.[.[.[.[.[.{.[.^.'.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.[.'.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.l.j ' 6.6.B 5.9.6.z o.J.I.I.U.I.I.I.I.L.I.I.I.I.I.I.I.`.[.[.[.[.^.c.'.}.[.[.[.[.}.C.C.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.}.[.[.[.[.[.[.}.[.[.}.[.[.[.[.'.I.I.I.I.I.I.I.L.D.!.J.I.I.N.0.6.9.5.B B B B B 4.4.9.6.y.D.T.I.I.I.D.I.I.I.I.I.I.I.I.`.[.[.[.[.}.).p.'.}.[.[.{.D.H.}.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.I.I.I.I.I.I.{ F n.^.C.i.B B B B B 7.y.y.y.0.=.4.B B B 6.B.J.I.+.A b.Q.L.I.I.I.I.L.`.[.[.[.[.[.}.).g.`.}.}.C.C.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.I.I.I.L.U.I.$.7 G u.5.B 4.B t.;.t $./.^._.D.K ! i.5.B 4.B y.#.2 L A.I.I.I.I.I.I.I.`.[.[.[.[.[.[.}.).p.'.J.C.}.[.[.[.[.[.[.[.`.'.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.T.L.I.I.I.I.I.!.$.t N 5.B 6.Z.Q.n.8 ^ I.T.(.z.2  .I.J.u.5.B 5.j I D.Q.I.I.I.I.I.I.I.`.[.[.[.[.[.[.[.}._.4.C.}.[.[.[.[.[.[.[.[.'.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.}.[.[.[.}.[.[.[.'.I.I.I.I.I.I.I.I.Z.5.6.4.w.J.T.I.I.L F D.^.).@.7 k.!.I.I.B.6.5.4.t.I.I.L.I.I.I.I.I.I.`.[.[.[.[.[.[.{.}.K.B.Z.`.}.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.}.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.'.L.I.I.I.I.I.I.J.6.B 5.l H A.!.U.!. .2 d.Q.T.L A S.I.I.Q.%.t B B B p.I.I.I.I.I.I.I.L.`.[.[.[.[.[.[.}.C.C.|.).p.'.{.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.I.I.L.I.I.I.p.B B t.:.4 G b.!.J.;.j _ 5.5.Q ( B.I.Q.@.2 I g.4.' 9.H.T.I.I.U.I.I.I.`.[.[.[.[.[.{.D.H.{.[.}.).p.'.{.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.{.[.[.[.{.[.[.[.[.[.'.I.I.I.I.I.I.Z.B B 7.J.!.<.7 G l.7.B 5.5.B 4.9.5.B i.%.2 L A.^.i.4.4.0.I.L.T.I.U.I.I.`.[.[.[.[.[.C.H.{.[.[.[.}.).p.'.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.{.[.[.'.I.I.I.A.L.!.y.B B p.I.I.Q.:.y b 4.B B &.9.7.N B ' 4.P I D.Q.I.K.9.' 5.J.Q.A.D.I.I.U.`.[.[.[.[.I.C.{.[.[.[.[.[.|.(.B.[.[.[.[.[.`.'.[.[.[.[.",
"[.[.}.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.'.I.Q.j.C U %.9.B 0.U.!.I.I.C.=.4.4.t.;.y h.^ P p.6.5.' w.I.I.I.Q.N.' 4.q.{ D ^ I.I.U.`.[.[.[.[.'.[.{.[.[.[.[.[.[.{.`.[.[.[.[.[.'.[.[.[.[.[.",
"}.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.{.'.I.I.z.W A i 5.5._ ,.x.K.J.9.B 5.z I <.8 L Z ~ ,.u B 4.B N.T.A.s.O.' 5.n Z F @.L.I.I.`.[.[.[.[.{.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.'.I.I.I.Q.J.8.B 6.E 2 4 F ] =.B 0.>.8 D L ~ U Y 4 ~ p.B 4.*.~ C 2 C ` 5.' g.T.I.I.I.I.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.`.'.[.[.[.[.",
"[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.{.'.I.I.I.I.I.y.B 6.v.k. .G t 6.4.(  .W L x.^.E.+.F | ! ` 9.l C ~ :.z.w.B 5.G.T.L.U.I.I.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.'.I.I.J.I.U.0.B 6.U.Q.L.J.0.B 5.E 4 7 k.Q.T.(.U.U 1 D _ 4.' B.I.I.!.g.4.B Z./.Q.I.L.L.`.{.[.[.{.[.[.[.[.{.[.[.{.[.[.[.[.[.[.[.}.`.[.[.[.[.[.",
"}.[.[.[.}.[.[.[.{.[.[.{.[.[.[.[.[.[.'.(.(.(.(.(.0.B 0.(.(.^.).y.B 7.L.M.h.E.(.(.).(.M.h.R.u.B B P.).^.).Z.N B B.m.+.S.).^.`.'.`.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.'.E.I.T.T.^.0.B 0.I.E.T.^.y.B 6.I.(./.^.E.(.(.T.^.(.(.N.' B G.).E.T.u.B 5.( C 4  .(.^.).I.T.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.L.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.{.[.[.{.[.[.[.{.[.{.'.I.J. .W ^ ` 5.=.W W W ^ _ 5.=.! U ! A.I.Q.(.J.I.J.I.Z.B B e.s.} H 5 _ 5._ | } D <.K.(.U.K.L.I.I.I.K.J.L.I.I.J.J.L.I.I.L.J.K.L.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.K.L 4 C v 9.N 9 8 Z 8 ( 5.N A 8 D A.I.E.(.L.I.I.F.e.B 9.) 2 4 F { ' 4.5.e.D Z L H ).b.H $.~.L.I.W ] F.I.T.<.F A.I.T.n.F <.I.).[.[.[.[.[.",
"[.[.[.[.}.[.[.[.[.[.[.[.[.[.{.[.[.[.'.I.I.L.L.I.0.B 8.L.I.J.I.y.B 6.J.I.L.I.I.^.^.I.A.^ C 9 N 4.' @.n.U.Q.i.B 5.N P 1.D F ).z.4 } ^.J.!.D G J.I.I.+.1 x.I.!.x.1 +.I.(.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.{.{.[.[.[.[.[.[.{.'.I.I.L.L.I.0.B 0.J.I.L.I.y.B 6.J.I.I.I.L.Q.^.U.K.L I $.w.B 4.C.!.U.I.I.8.' 4.9.u.u +.].x.4  ./.I.!.F H K.I.!.+.2 b.!.!.b.2 $.I.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.I.!././.t.B 0.~.!.~./.i.B 9.Q./.Q.I.I.^.(.L.I.J.L.~.Z.B ' 0.I.I.Q.d.D Q 4.' B 4.6.t.8.) =.t.0.0._ _ 0.0.w.=.v 8.t.t.0.v =.w.w.[.[.[.[.[.",
"}.[.[.[.}.[.[.[.[.{.[.[.[.{.[.[.[.[.'.I.L.f.$.<.=.4.=.<.:.<.,.-.4.=.:.<.<.J.I.^.(.L.I.I.I.I.J.9.4.B c.Q.d.9 8 d.y.4.5.5.' B 4.5.5.B B B 5.4.B B B 5.5.B B B B 5.4.B B '.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.'.I.K.F 1 2 ) 9._ 3 2 3 1 ( 5.N 4 1 8 n.I.^.(.I.I.L.I.L.I.C.9.' 9.s.8 9 j.Q.I.c.P ( 9.0.7.` =.0.8.9.&.N 9.0.0.=.b 8.9.0.7.b =.8.w.'.[.[.[.[.",
"[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.{.'.I.L.k.1.f.7.B 6.s.s.f.1.8.4.6.s.f.f.J.I.I.^.L.I.I.I.I.I.I.t.' 4.N L k.Q.U.^.k.4  .Q.).z.8 | /.J.!.F L K.I.I.+.3 v.Q.Q.b.2 +.I.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.{.'.I.I.Q.Q.Q.0.B 7.Q.Q.Q.!.y.B 6.I.Q.Q.I.I.^.(.J.I.I.I.I.I.I.J.9.4.4.6.C.I.I.Q. .5 j.Q._.z.4 | ~.J.Q.F L D.I.Q.+.7 x.Q.Q.b.2 +.I.).[.[.[.[.[.",
"}.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.I.I.I.Q.t.B 0.I.Q.I.Q.y.B 6.U.Q.I.I.I.^.(.L.I.I.I.I.I.Q.d.D n 4.' 6.a.J.K.L A K.I.).z.8 | ~.L.Q.F G D.I.I.+.2 x.!.I.b.2 %.I.(.[.[.[.[.[.",
"[.[.[.}.[.[.}.[.[.[.[.[.[.[.[.[.[.[.'.I.I.A.n.A.8.B 6.n.n.n.n.q.4.6.b.n.A.L.I.I.(.J.I.I.I.L.I.f.8 Z r.0.B ' B 6.w.E / I.T.].x.7  ./.I.^.D H K.!.!.+.2 m.~.^.b.2 +.!.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.J.L 8 C _ 5.` Z C Z 8 ) 9.N D 8 D A.I.^.^.L.I.I.I.I.!.k.D d.^.J.Z.6.B B B B 6.0.0.a.8.( &.y.y.y.v v w.y.y.&.z 8.y.y.w.z -.y.i.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.}.[.[.[.}.[.[.[.[.'.I.L.+.^ ^ ` 4.' ^ ^ ! ] ` 4.=.! ] { D.I.^.(.L.I.I.I.I.I.I.J.I.I.I.I.C.y.0.9.4.B B B B B 9.5.B B B 5.5.B B 4.5.5.4.B B B 5.5.B B '.}.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.I.I.Q././.t.B 0././.~.).i.B 9.Q././.I.J.T.(.I.I.I.I.I.I.I.I.I.I.I.I.I.I.J.Q ) 0.0.' 6.6.N =.6.5.8.' =.7.6.6.=.N 7.7.9.6.N ' 7.0.'.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.I.L.L.I.0.B 7.K.L.L.I.w.B 9.J.U.L.I.I.^.(.J.I.I.I.I.I.I.I.L.I.I.I.L.I.b.7 { I.J.J._.l.8 | !.J.I.G P D.U.I.+.7 v.I.I.v.7 @.U.(.[.[.[.[.[.",
"}.[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.'.I.I.Q.Q.!.0.B 0.Q.Q.Q.^.y.B 9.Q.Q.Q.I.I.Q.(.J.I.I.I.I.I.I.I.I.I.I.I.I./.%.2 1.^.I.I._.z.7 } /.L.!.D H K.I.!.+.1 x.!.!.b.2 +.Q.(.[.[.[.[.[.",
"[.[.[.[.}.[.[.[.[.[.[.[.[.}.[.[.[.[.'.I.L.^ H L ` 5.' L L L F _ 4.' L H I D.I.^.^.U.I.I.I.I.I.I.I.I.I.I.I.I.Q.n.@.A.I.I.I._.z.Z +.~.J.!.H I D.I.I.%.8 b.Q.Q.b.8 %.I.(.{.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.K.U D D _ 4.N D F F D v 4.N F D H A.I.T.(.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.I.I.I.I.).J.A.D.I.I.I.S.S.I.I.I.D.V.J.I.I.J.A.D.I.(.{.[.[.[.[.",
"[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.[.[.'.I.L.K.D.D.w.9.0.D.A.V.D.y.9.0.A.A.A.J.U.^.(.J.I.U.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.).I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.L.(.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.'.^.^.A.A.Q.m g c Q.^.^.).B g x Q.(./.^.T.(.(.T.T.T.I.T.I.^.I.I.E.I.E.^.I.I.I.I.I.I.I.).T.I.T.!.I.T.I.T.T.!.!.I.!.I.T.!.I.T.I.I.).[.[.[.[.[.",
"[.[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.{.`.(.R.D C I @   X I._.(._.-     G.(.^.(.(.(.'.'.'.'.'.'.'.'.[.'.'.'.'.'.'.'.'.'.'.[.'.`.'.[.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.[.`.[.[.[.[.[.",
"[.[.}.[.[.[.[.[.[.[.[.[.[.}.[.[.[.{.'.I.} L [ <     > U @.z.V.*   - J.L.L.L.J.I.'.}.}.{.{.{.[.[.[.{.{.{.{.{.}.{.{.{.{.{.[.`.{.[.[.{.}.{.}.}.[.}.}.[.[.}.[.}.}.[.[.{.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.}.[.[.[.[.[.[.[.[.[.}.F.U F 7 2.p     e J 3 7 6 X   $ D./.I.I.I.I.'.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.'.'.[.[.[.{.[.[.{.[..X3.1 ,.T &       0.F.s.X.<     % H } z.I.U.T.'.{.[.[.[.[.[.[.[.[.[.[.[.'.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[..XXXXX[.[.[.[.{.[.[.[.}.W.C Q a       f I.I.Q.Q.:   X r H 3 $.!.U.T.'.{.[.[.[.'.[.[.[.[.[.[.[.[.{.'.[.[.[.[.[.`.[.[.[.[.'.{.[.[.[.[.[.[.[.{.'.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.|.y.d m '.[.[.[.[.[.[.[..Xw.+ X       , 2.!.L.^.i.    = D.L.k.D.I.I.I.'.[.[.[.[.C._.}.[.[.[.[.[.}.E.K.[.[.[.[.[.`.[.[.[.[.I.L.}.[.[.[.[.[.}.`.C.'.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.{.`.;     C..X[.[.[.[.[.'.XXx   o     d R 4 ,.Q.I.;     a ^.U.!.I.I.I.!.[.[.[.[.[._.p.`.}.[.[.[.}.^.c.'.[.[.[.[.[.`.[.[.[.[.'.B.I.}.[.[.[.}.'.p.(.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[..XZ.  #   x }.[.[.[.[.[.[.XXx   & 0 c Q.A.G 3 2.x     = B.T.J.I.I.I.I.I.'.[.[.[.[.}.`.p._.}.[.}.(.p.'.}.[.[.[.[.[.`.[.[.[.[.}.[.c.T.}.[.}.`.p.).}.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.}.c   M $ # [.[.[.[.[.[.[.{.U.&.A ..(.I.I.V.R , o     9.(.J.I.I.I.I.I.T.'.[.[.[.[.[.}.`.p._.|.^.B.'.}.[.[.[.[.[.[.`.[.[.[.[.[.[.[.Z.I.|.`.g._.}.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.{.}.'.# o `.f   Z.}.[.[.[.[.[.[.[.I.L 9 D.U.I.^.k   o   p L.I.L.I.I.I.I.I.I.[.[.[.[.[.[.[.}.`.B.U.Z.'.{.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.'.V.J.Z.).}.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.'.|.D.  : [.B   x .X[.[.[.[.[.{.`.I.| 4 m.(.Z.p       & O.^.I.I.I.I.I.I.I.I.'.[.[.[.[.[.[.[.}.I.M _.}.[.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.}.`.M H..X[.[.[.[.[.[.[.[.`.'.[.[.[.[.",
"[.[.[..Xg           - `.{.[.[.[.[.[.[.].k.3 ( h @       ; F 8 @.J.I.I.I.I.I.I.T.'.[.[.[.[.[.[.}.E.V._.c.`.}.[.[.[.[.[.[.[.`.}.[.[.[.[.[.}.'.g._.C.I.}.[.[.[.[.[.[.[.'.[.[.[.[.[.",
"[.[.{.'.*   k m M =   B..X[.[.[.[.}.Z.f w O         # x I.A.D F K.I.I.I.I.I.I.I.'.}.[.[.[.'.}.(.c.'.|.`.p._.}.[.[.[.[.[.[.`.[.[.[.[.[.[.`.p.).}.[.B.I.}.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[..XZ.X p XXXXXX0.  M {.[.[.[.[.XXx             ; c.(.I.Q.b.A.!.J.I.I.I.I.I.T.'.{.[.[.[.|.^.B.'.[.[.}.`.p.`.}.[.[.[.[.[.`.[.[.{.[.}.`.p._.}.[.[.[.B.I.}.[.[.[.[.{.`.[.[.[.[.[.",
"[.[.[.[.[.[.'.'.[.[.[.[.[.[.[.[.'.XXx   @   + d i.I.I.J.I.U.I.I.I.I.I.I.I.I.I.I.'.[.[.[.{.E.B.'.}.[.[.[.}.`.p._.[.[.[.[.[.`.[.[.[.{.`.p._.}.[.[.[.[.[.B.L.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.J.B y.` 7 ,./.I.I.I.I.I.I.I.I.I.I.I.I.I.I.T.[.[.[.[.'.J.'.{.[.[.[.[.[.}._.I.[.[.[.[.[.`.[.[.[.[.T.).}.[.[.[.[.[.}.'.J.'.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.(.^.T.A F D.I.I.I.I.I.I.I.I.I.I.I.I.I.I.T.'.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.{.[.[.[.[.[.[.[.[.}.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.`.I.P.I. .{ L.I.I.I.I.I.I.I.I.I.I.I.I.I.I.E.'.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.{.[.[.[.{.[.[.[.'.I.L.I.L.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.'.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.}.[.[.[.}.[.[.[.[.[.[.[.[.[.[.'.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.T.I.I.I.T.'.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.'.I.L.I.I.L.I.J.I.I.I.P.I.L.I.L.L.L.I.L.I.I.'.[.[.[.[.[.'.[.[.[.[.[.[.'.[.[.[.[.[.[.'.`.[.[.[.[.[.[.'.[.[.[.[.[.[.[.[.[.[.[.[.[.`.[.[.[.[.[.",
"[.[.[.[.[.[.[.[.[.{.[.[.[.{.{.[.[.[.'.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.'.`.`.`.`.'.'.`.`.`.'.`.`.'.`.`.`.`.`.'.`.`.`.`.`.`.'.`.`.'.`.`.`.`.`.`.`.`.`.`.`.`.[.[.[.[.{.",
"[.}.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.{.{.{.{.[.{.{.[.[.[.[.}.[.[.[.[.[.}.[.[.[.[.[.{.{.{.{.[.[.[.[.[.}.[.[.[.[.}.[.[.[.}.[.[.[.[.[.[.}.[.[.{.[.[.{.[.{.{.[.[.{.[.[.[.[.[.[.",
"[.[.[.[.[.[.{.[.[.[.[.{.[.{.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.",
"[.[.[.[.{.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.{.{.[.[.[.[.[.[.{.[.[.",
"[.[.[.[.[.[.[.[.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.}.[.[.[.[.[.{.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 168 2 ",
"   c #020201",
".  c #0E0A03",
"X  c #0B0B0D",
"o  c #1D1C1A",
"O  c #231F15",
"+  c #201F1A",
"@  c #27241B",
"#  c #38311A",
"$  c #252525",
"%  c #282722",
"&  c #2C2C2C",
"*  c #2D2E34",
"=  c #333334",
"-  c #3B3B3B",
";  c #514525",
":  c #484539",
">  c #625632",
",  c #6C5E37",
"<  c #736028",
"1  c #7C6C3C",
"2  c #434343",
"3  c #545453",
"4  c #5B5B5B",
"5  c #626262",
"6  c #6C6C6C",
"7  c #747166",
"8  c #7B776A",
"9  c #7F7A6A",
"0  c #7B7664",
"q  c #7B7A75",
"w  c #7D7D7D",
"e  c gray46",
"r  c #886F26",
"t  c #8B732E",
"y  c #8C7633",
"u  c #89763B",
"i  c #8E793A",
"p  c #86743D",
"a  c #937B30",
"s  c #917B3C",
"d  c #877541",
"f  c #897741",
"g  c #8A7947",
"h  c #857648",
"j  c #8C7C4C",
"k  c #847750",
"l  c #8B7D51",
"z  c #867A58",
"x  c #8B7F5B",
"c  c #837B64",
"v  c #857E6C",
"b  c #827E73",
"n  c #948046",
"m  c #9B8444",
"M  c #97844E",
"N  c #8E8056",
"B  c #8F825D",
"V  c #958556",
"C  c #998751",
"Z  c #998857",
"A  c #94865C",
"S  c #97885C",
"D  c #9A8A5A",
"F  c #A2905A",
"G  c #8C836A",
"H  c #928662",
"J  c #948866",
"K  c #9A8D64",
"L  c #998E6F",
"P  c #9F926C",
"I  c #858175",
"U  c #898474",
"Y  c #84827C",
"T  c #8A877D",
"R  c #938B72",
"E  c #998F71",
"W  c #928C79",
"Q  c #9A9074",
"!  c #98917C",
"~  c #A2956E",
"^  c #A6986F",
"/  c #A29672",
"(  c #A49976",
")  c #A29779",
"_  c #AC9D72",
"`  c #7D7E81",
"'  c #7F8082",
"]  c #828282",
"[  c #888783",
"{  c #8C8A86",
"}  c #84858B",
"|  c #87888D",
" . c #8B8B8B",
".. c #908F8C",
"X. c #9C9681",
"o. c #94938E",
"O. c #878992",
"+. c #8C8E92",
"@. c #8F9093",
"#. c #959595",
"$. c #989897",
"%. c #96979A",
"&. c #97989B",
"*. c #9B9B9B",
"=. c #A59D85",
"-. c #A89F82",
";. c #A29C8C",
":. c #A49F91",
">. c #AAA185",
",. c #AAA38C",
"<. c #A4A094",
"1. c #ABA594",
"2. c #A5A299",
"3. c #AAA79D",
"4. c #ADA99D",
"5. c #B2AB96",
"6. c #B9AF91",
"7. c #B2AC9B",
"8. c #B6B09D",
"9. c #A3A3A2",
"0. c #AAA7A0",
"q. c #ACAAA6",
"w. c #A7A9AD",
"e. c #ACACAC",
"r. c #B2AEA2",
"t. c #B0AFAA",
"y. c #B5B1A4",
"u. c #B5B2AC",
"i. c #BAB6AC",
"p. c #A7AAB2",
"a. c #A9ABB0",
"s. c #AFB1B7",
"d. c #B4B4B3",
"f. c #B9B7B2",
"g. c #BAB9B4",
"h. c #B4B6BA",
"j. c #B7B8BA",
"k. c #BBBBBB",
"l. c #C0BFBE",
"z. c #C0C0BE",
"x. c #B6B9C2",
"c. c #BCBDC2",
"v. c #BFC0C4",
"b. c #C2C2C2",
"n. c #C9C8C5",
"m. c #C3C5CB",
"M. c #C7C8CC",
"N. c #CBCBCC",
"B. c #D2CFC9",
"V. c #C6C9D3",
"C. c #CBCDD2",
"Z. c #C9CDD9",
"A. c #CDD0D6",
"S. c #CCD0DD",
"D. c #D3D3D4",
"F. c #D5D6D9",
"G. c #DCDCDC",
"H. c #D3D6E0",
"J. c #D6D9E1",
"K. c #D9DCE2",
"L. c #E5E5E5",
"P. c #E8E7E7",
"I. c #E8E8E7",
"U. c #EAEAEA",
"Y. c #EAEBF0",
"T. c #EEF0F4",
"R. c gray95",
"E. c #F9F9F9",
/* pixels */
"L.L.P.L.P.L.L.P.I.L.L.L.U.P.L.L.L.P.L.L.I.L.L.L.I.L.P.L.L.I.L.L.L.L.U.L.L.L.L.L.L.L.L.L.L.U.L.L.",
"L.L.L.L.L.P.L.L.L.L.I.L.P.L.L.L.P.L.L.L.L.L.L.L.L.L.L.I.L.L.L.I.L.L.P.L.L.L.L.I.L.L.L.L.L.L.L.L.",
"I.P.L.P.L.L.P.L.I.L.I.L.L.L.L.U.T.L.L.L.L.L.I.L.L.L.U.U.L.L.L.L.U.L.L.L.L.U.U.L.L.L.L.L.L.L.L.L.",
"L.L.P.L.L.L.L.L.L.L.L.L.P.L.L.F.k.G.U.L.I.L.L.L.L.I.A.b.I.I.L.L.L.L.L.L.L.M.D.L.L.L.I.L.U.L.L.L.",
"L.L.L.U.L.L.U.L.P.L.L.L.L.L.U.#.3 & D.I.L.L.L.L.L.G.4 = 5 R.L.L.L.P.L.U.D.* 2 R.P.P.L.I.L.L.L.U.",
"U.L.L.L.L.L.L.L.L.L.L.L.L.L.I.L.] & F.I.L.I.L.L.I.G.E.&.& R.L.L.P.L.L.G.R.9.= Y.L.L.L.I.L.L.L.I.",
"L.L.L.L.L.L.L.L.L.I.L.L.L.L.I.L.} + b.R.L.L.L.L.L.U.k.- N.I.L.L.P.L.L.L.E.q.: E.G.I.L.L.L.L.L.L.",
"L.L.L.U.L.L.L.U.L.L.I.L.L.L.U.' 5 % m.U.L.L.L.L.L.L.o $ w L.L.L.L.L.L.I.G.2 X $.Y.I.L.L.L.L.L.L.",
"L.L.L.L.L.L.L.L.L.L.U.L.L.L.U.N.9.D.U.L.L.L.L.L.L.L.k.d.d.L.L.L.L.L.L.P.G.s.u.c.L.L.L.P.L.L.L.L.",
"U.L.U.L.L.L.U.L.L.L.L.L.L.L.L.U.R.I.L.L.L.L.L.L.L.L.U.R.U.L.L.L.L.L.L.L.P.R.R.R.L.L.L.P.L.L.P.I.",
"L.U.L.L.L.U.L.U.L.L.L.L.L.L.L.L.P.P.I.I.P.P.P.P.L.L.L.L.L.L.I.I.L.L.I.I.L.L.L.L.L.L.I.L.L.L.L.L.",
"L.L.L.L.L.L.L.L.L.L.L.L.G.L.G.L.G.L.G.G.L.K.L.G.G.L.G.L.G.L.G.L.L.G.L.G.G.L.G.G.G.L.G.L.L.L.P.L.",
"L.L.L.U.L.L.L.L.L.L.L.F.k.k.k.k.k.k.k.b.c.k.b.k.b.k.k.k.k.k.k.k.z.L.G.L.G.L.L.L.L.L.L.G.L.L.L.L.",
"U.L.L.L.L.L.L.L.L.L.L.D.j.k.k.g.k.k.k.Q 7.b.N.y.P k.k.k.k.k.k.k.v.L.L.I.I.L.L.I.L.L.P.G.L.I.L.L.",
"L.L.L.L.L.L.L.U.L.L.U.D.j.k.k.v.k.k.m.S R w.w.! V b.g.k.c.k.k.k.b.L.I.N.G.I.L.G.N.I.L.G.L.L.L.L.",
"L.L.U.L.U.L.L.L.L.L.U.D.g.k.k.1.i.k.$.] ` ' ' ` ` #.j.f.,.k.k.k.b.L.L.G.k.L.L.k.G.I.L.K.L.L.L.L.",
"L.L.U.L.U.L.L.L.L.L.L.D.k.k.v.K j +.` #.j d.k.l o.] O.V Z v.k.g.b.L.L.I.L.k.k.G.I.L.L.G.L.L.L.I.",
"L.L.L.L.L.L.L.L.L.L.I.D.g.g.k.j.w 0 t.m.s 4.i.y b.d.8 q s.k.j.k.l.L.L.L.L.j.d.L.P.L.I.K.L.L.L.L.",
"U.L.L.L.L.L.L.L.L.L.P.D.j.v.v. .O.K s u.G b Y G d.n S O. .k.v.k.v.L.L.L.k.G.L.k.G.I.L.G.L.L.L.P.",
"L.L.L.U.L.L.P.L.L.L.L.D.j.-.2.w a.V.J 0 } I U } 8 A M.s.w 2.-.u.b.L.I.N.D.I.I.G.N.I.I.G.L.L.L.L.",
"L.L.L.L.P.L.L.L.L.L.I.D.d.Z z w V -.#.' j y t j Y O.,.Z q v M u.b.L.L.L.L.L.L.I.L.L.L.G.P.P.L.L.",
"L.U.L.L.L.L.P.L.L.L.I.D.j.m.@.{ ( j q z r 1.r.t k w j / {  .V.c.z.I.I.I.L.I.I.L.I.I.U.G.L.P.L.L.",
"U.L.U.L.L.P.P.L.P.L.I.D.z.M.| %.F.x.] 1.7.m.C.7.1.` s.J.*.Y P 5.C.D.D.D.F.D.D.F.D.F.D.F.L.L.L.L.",
"L.L.L.L.L.P.L.P.L.L.P.F.5.g I G f V ' l ~ b.l.b.k.' W n h ` g t y.u.4.k.4.u.d.1.k.r.3.C.I.L.L.L.",
"L.L.L.L.U.L.L.U.I.P.L.D.d.4.[ { 4.,.` <.y.k.m.,.u I I ( u.| Y f ~ _ D Z.i 5.u.y V.P V G.L.L.L.P.",
"L.L.L.L.L.L.L.P.L.L.U.D.f.f.{ #.g.q.` q.g.k.b.u.y.*.w x.y.f ] ' [ T Y @.b {  .v +.T b w.I.L.L.L.",
"U.L.L.L.U.L.L.L.L.L.L.F.1.y b c t g ' p Z v.b.k.v.j.}  .i >.d.k #.T I %.v { o.v %.T b e.U.L.L.P.",
"L.L.L.U.L.L.L.L.L.L.I.D.j.b. .#.M.d.w h.v.k.b.j.g.v.<.7 [ x.8.y A.^ D Z.i 7.i.y V.~ D K.I.L.L.L.",
"L.L.L.U.L.L.U.L.L.L.I.D.q./ T T ( Q ' Q ,.z.v.g.k.f.i ! | ` U G c.E J x.j <.0.g j.Q H V.I.L.L.I.",
"U.L.L.L.L.L.L.L.L.L.I.D.4.Z Y I D H ' A / v.z.k.k.g.y.v.j.$.Y ] w ' ' w ] ` ` ' w ] w $.I.L.L.L.",
"L.L.L.L.L.L.L.L.I.L.I.D.k.Z. .%.S.x.w x.m.k.b.k.k.k.v.k.k.g.u 3.c.L H x.g <.0.d h.E A m.I.L.L.L.",
"L.L.L.U.L.L.L.U.L.L.I.F.1.i Y G i l ] g K v.v.k.k.k.k.k.k.u.-.k.V.>./ m.K y.i.S m.-.) F.L.L.L.L.",
"L.L.L.L.I.L.L.L.L.L.I.F.u.,.[ { 7.;.w ;.7.b.b.k.k.g.k.j.j.k.c.k.k.k.k.k.k.k.j.k.j.k.j.N.I.L.L.L.",
"U.L.L.L.L.L.L.L.L.L.L.K.-.M o : B.*.  a.C.z.D.G.G.F.G.G.G.G.F.G.G.F.G.G.G.G.G.G.F.G.F.G.P.L.L.L.",
"L.L.L.L.L.U.I.L.L.L.U.6.a ,   > m ;   R g.k.G.I.I.I.L.L.P.L.I.I.G.L.L.I.I.I.I.I.I.P.I.L.L.P.L.L.",
"L.L.U.L.I.D.D.I.L.L.T./ ;   O h.b.% o n >.c.G.L.G.G.L.L.P.G.L.I.G.L.P.F.L.L.P.I.F.L.L.G.L.L.L.L.",
"L.U.L.L.L.$ = R.L.L.R.4   = d _ #.  6 N.j.k.G.I.G.k.G.U.D.b.L.I.L.L.I.D.l.I.U.b.N.I.L.L.L.L.L.L.",
"L.L.L.T.s.- = k.U.L.U.9.< i.n.1   * k.k.k.k.G.L.U.K.b.D.b.L.I.L.L.G.P.U.D.b.N.N.I.L.L.G.L.L.L.L.",
"L.L.L.E.6 - = e E.L.L.Y.F ! ` X . B c.j.k.k.G.P.L.R.B.*.G.U.I.I.G.L.L.L.U.j.e.U.L.L.L.G.L.L.L.L.",
"L.L.L.L.& 5 4 = L.L.R. .@ .   - 2.C r.k.k.k.G.P.U.D.b.G.k.G.I.L.L.G.L.I.b.D.D.l.I.P.I.G.L.L.L.P.",
"L.L.I.G.z.R.T.z.L.L.R.5 X #  .b.b.k.k.k.k.k.G.I.G.v.L.U.G.c.L.L.G.L.I.N.N.U.U.A.b.I.L.G.L.L.L.L.",
"L.L.L.I.R.G.L.Y.L.L.P.D.k.m i.c.j.k.k.k.k.k.G.L.G.L.L.L.I.G.L.I.G.L.I.G.I.L.L.L.L.I.P.G.L.P.L.I.",
"L.L.L.L.L.L.L.L.L.L.L.D.j.u.f.k.k.g.k.k.k.k.G.L.L.I.L.L.I.I.I.I.L.L.L.I.L.I.L.L.L.U.I.G.L.L.L.L.",
"L.I.I.L.L.L.L.P.L.L.L.D.k.b.b.z.b.z.b.k.b.k.G.L.G.L.G.L.G.L.G.K.G.G.L.G.L.G.L.G.K.G.L.G.P.L.L.L.",
"L.L.L.L.L.L.P.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.G.L.L.G.L.L.L.L.G.L.L.L.G.L.L.G.L.L.L.L.L.I.",
"L.I.L.I.P.L.L.P.L.L.L.P.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.L.L.L.L.",
"L.I.L.L.I.P.L.I.I.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.L.L.L.L.L.L.L.P.L.L.L.L.L.L.L.L.L.I.L.",
"L.L.L.I.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.U.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.I.L.L."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 155 2 ",
"   c #020201",
".  c #080705",
"X  c #0D0B07",
"o  c #110E05",
"O  c #19150A",
"+  c #0B0C12",
"@  c #181818",
"#  c #201800",
"$  c #272317",
"%  c #2A261A",
"&  c #252525",
"*  c #2B2B2B",
"=  c #373737",
"-  c #35373D",
";  c gray22",
":  c #423B23",
">  c #574C2E",
",  c #554F3B",
"<  c #625734",
"1  c #454545",
"2  c #4E4E4D",
"3  c gray33",
"4  c #5F5F5F",
"5  c #776E55",
"6  c #7D7459",
"7  c #5E6067",
"8  c #626262",
"9  c #6C6C6C",
"0  c #7B7666",
"q  c #757575",
"w  c #7C7B75",
"e  c #7C7C7B",
"r  c #897028",
"t  c #8C7737",
"y  c #8B773B",
"u  c #8D793E",
"i  c #927A32",
"p  c #917C3E",
"a  c #8D7A42",
"s  c #8D7D4C",
"d  c #907D44",
"f  c #907F4C",
"g  c #8B7D53",
"h  c #857B5B",
"j  c #8A7E5B",
"k  c #867E65",
"l  c #897F61",
"z  c #827C6B",
"x  c #827F77",
"c  c #807F7A",
"v  c #95824C",
"b  c #8F815A",
"n  c #938352",
"m  c #998751",
"M  c #9B8954",
"N  c #94865C",
"B  c #9B8B5C",
"V  c #A8955A",
"C  c #8C8163",
"Z  c #8A826B",
"A  c #948760",
"S  c #968A65",
"D  c #9C8E65",
"F  c #93896D",
"G  c #9E926C",
"H  c #848074",
"J  c #8C8574",
"K  c #8D8877",
"L  c #83827C",
"P  c #8B877C",
"I  c #958D77",
"U  c #938E7D",
"Y  c #9E9374",
"T  c #979078",
"R  c #9B927A",
"E  c #A3976F",
"W  c #A29673",
"Q  c #A49974",
"!  c #AE9F71",
"~  c #A29778",
"^  c #A69B7B",
"/  c #7E7F80",
"(  c #838383",
")  c #84868B",
"_  c #87888C",
"`  c #8B8B8B",
"'  c #959187",
"]  c #999486",
"[  c #92918C",
"{  c #9A968B",
"}  c #9E9A8C",
"|  c #848790",
" . c #8C8E95",
".. c #8F9092",
"X. c #949393",
"o. c #999894",
"O. c #94969C",
"+. c #9A9B9D",
"@. c #A79E83",
"#. c #A49E8B",
"$. c #A09F9D",
"%. c #ACA386",
"&. c #ABA38B",
"*. c #ADA693",
"=. c #AEA897",
"-. c #A5A29A",
";. c #AEAA9C",
":. c #B3AB94",
">. c #B3AD9B",
",. c #B8B19C",
"<. c #9C9DA0",
"1. c #9EA0A5",
"2. c #A4A4A3",
"3. c #AAA9A6",
"4. c #A4A5A9",
"5. c #ACACAD",
"6. c #B1AEA4",
"7. c #B5B0A1",
"8. c #B4B2AC",
"9. c #B9B6AD",
"0. c #ABADB2",
"q. c #B4B4B3",
"w. c #B8B7B4",
"e. c #B9B9B7",
"r. c #B7B7B9",
"t. c #B7B8BB",
"y. c #BBBBBB",
"u. c #C3B99C",
"i. c #C3BCA7",
"p. c #C2C1BD",
"a. c #CBC7BB",
"s. c #B6B9C1",
"d. c #BDBEC2",
"f. c #BFC0C3",
"g. c #C3C3C3",
"h. c #C3C5CA",
"j. c #CACACA",
"k. c #CACDD4",
"l. c #CFD0D6",
"z. c #D4D4D4",
"x. c #D8D7D7",
"c. c #D5D6D9",
"v. c #D7D8DA",
"b. c #DDDDDD",
"n. c #D6D9E1",
"m. c #DADCE2",
"M. c #DEE0E7",
"N. c #E5E5E5",
"B. c #E8E7E7",
"V. c #E8E8E7",
"C. c #E3E5E8",
"Z. c #EAEAEA",
"A. c #EBEDF2",
"S. c #F3F3F3",
"D. c #F8F8F8",
/* pixels */
"N.N.N.V.N.N.V.C.N.V.N.C.N.N.N.C.N.N.N.N.B.N.N.N.N.N.B.N.V.N.N.N.V.N.N.N.N.N.N.N.N.N.N.V.",
"N.N.V.N.N.V.N.N.N.V.V.C.N.N.N.N.N.N.N.N.N.N.B.N.N.N.N.N.N.N.N.N.V.B.N.N.N.N.V.N.V.N.N.N.",
"N.N.V.N.V.N.N.N.V.N.N.N.N.N.A.S.N.N.B.N.N.B.N.B.S.Z.N.B.N.N.V.N.N.Z.A.N.N.N.N.N.N.V.N.V.",
"V.N.N.V.N.N.V.N.N.N.V.N.N.B.y.8.N.N.N.N.N.N.B.b.3.j.Z.N.V.N.N.N.B.j.w.N.N.N.V.N.N.N.N.N.",
"C.V.N.N.V.N.N.N.B.N.N.N.N.C.X.= q D.N.N.N.N.A.8.8 * j.Z.N.N.N.N.Z.X.@ j.V.N.N.N.N.N.N.N.",
"N.N.V.B.C.N.B.N.N.N.V.N.N.Z.z.= _ S.b.N.N.N.N.S.B.; j.Z.C.N.N.N.N.S.1 h.Z.N.V.N.N.V.V.N.",
"N.B.N.N.V.N.N.V.N.N.N.N.N.b.w.2 3 D.N.N.N.N.B.j.& L Z.N.N.N.N.N.V.z.& 5.A.N.N.N.N.N.V.V.",
"N.N.N.N.C.N.V.N.N.N.N.N.N.N.q 4 w.Z.N.N.N.N.A.5.1 8 h.V.N.N.N.N.A.o.1 w V.B.N.N.N.V.N.N.",
"N.N.V.N.N.N.V.V.C.N.N.N.N.N.Z.S.Z.C.C.C.C.N.N.Z.D.S.V.C.C.N.N.N.N.Z.D.Z.N.N.N.N.N.N.V.N.",
"B.N.V.N.B.N.N.N.C.C.N.N.N.N.N.N.B.B.B.C.N.V.V.N.N.N.N.N.N.N.N.B.B.B.N.N.V.V.V.V.N.N.N.N.",
"B.N.N.V.N.N.N.V.C.B.N.N.N.N.N.N.N.b.C.C.N.b.N.b.b.C.C.C.N.N.b.N.N.b.N.b.b.N.b.V.N.N.N.N.",
"N.N.N.C.C.V.N.N.N.B.x.e.d.y.e.d.i.d.f.i.g.d.g.y.y.i.d.d.y.g.b.N.b.N.b.N.N.b.b.b.N.N.V.N.",
"N.N.N.B.N.V.N.V.N.B.v.e.y.y.e.e.d.&.^ h.j.*.~ d.e.e.y.y.w.g.B.N.B.B.N.B.V.N.N.N.V.N.N.N.",
"N.B.N.N.N.N.N.B.N.B.x.e.y.y.d.y.h.$.l +.+.Z R g.y.f.y.y.e.g.N.C.h.N.Z.b.j.N.N.b.N.N.N.V.",
"V.C.N.B.V.N.B.N.N.B.x.e.y.w.D 8.O./ c `  .x / ` q.G 6.d.w.h.N.V.x.g.N.g.x.V.N.b.N.N.V.N.",
"N.V.N.N.C.N.N.N.N.B.x.e.e.d.Y 0 _ 0.v >.a.d 5. .w N y.e.e.g.N.N.Z.z.1.b.V.N.N.m.N.N.V.N.",
"N.V.V.N.C.N.N.V.N.V.x.e.f.y.O.w n d.W I { N h.B z  .e.y.y.g.B.B.b.g.z.h.N.N.N.b.N.N.N.N.",
"C.N.N.V.N.V.N.N.N.V.v.r.8.3./ s.Q g ) c c ) l B d.) $.w.q.g.B.C.g.b.Z.v.g.V.N.N.V.N.N.N.",
"N.N.N.N.N.N.N.V.N.V.x.9.v H H %.3./ k y t l e $.*.Z c d 6.k.C.N.N.N.C.V.b.N.N.b.N.N.V.N.",
"V.N.V.N.V.N.N.N.N.V.x.y.y.( U m h x r ~ %.r z z v R / y.d.i.B.B.V.N.V.N.Z.V.B.b.N.N.N.N.",
"N.N.N.V.N.V.N.V.N.V.v.f.h.( 5.l. .' :.h.j.,.o._ k.r./ Y *.k.c.z.z.c.z.c.z.c.c.x.B.N.N.N.",
"N.V.V.N.N.N.N.N.N.N.b.=.a L b p x k B y.f.i.-.c N a c h r =.=.6.5.&.y.&.w.;.*.v.B.N.V.N.",
"N.N.N.N.N.V.N.N.N.V.v.e.e.( 2.p.` o.y.y.h.@.s / ] i.X.w h ~ D #.;.v d.a q.Y S n.B.N.N.N.",
"N.N.C.V.N.N.V.N.N.V.b.3.G L I Q P K ^ y.h.t.d.X. .6.p ' / c ( ( L / ( / ( ( w q.Z.V.V.N.",
"V.N.N.V.N.N.N.N.N.B.x.6.G ( T Q P K ^ y.d.e.y.t.| 6 *.f.p 0.S #.-.b q.b 3.R F l.V.N.N.N.",
"V.N.N.V.V.C.B.N.N.B.x.e.w.( -.y.` O.y.y.g.w.d.>.s )  .#.f l.M *.7.v h.a e.^ D M.N.N.V.N.",
"N.N.N.N.N.V.N.N.C.B.m.=.u L j u x l m y.g.w.d.=.#.s. .( c _ c ( ( H _ H ` L e w.Z.N.N.N.",
"V.C.N.N.V.N.N.V.C.V.x.y.h.( 5.k.` +.h.y.g.e.y.y.f.i.f.j { 0.l { o.b 4.j $.I Z j.V.N.N.N.",
"B.N.C.N.C.C.B.N.N.B.c.=.n ( A v L Z B y.g.y.y.y.y.y.y.^ w.k.~ 6.8.D h.B y.&.^ m.V.N.N.N.",
"N.N.N.N.C.B.N.B.N.B.b.8.@.w X.,.L P 6.i.g.y.y.y.y.y.y.f.y.i.f.t.y.p.y.y.y.y.e.z.V.N.V.N.",
"B.N.N.N.N.N.N.N.C.B.v.Q a . 5 a.& 7 n.d.c.b.b.b.b.b.b.b.b.x.b.b.b.b.b.b.b.b.b.b.N.N.N.N.",
"N.B.N.N.N.D.B.N.C.A.u.i : + S a   > :.t.b.Z.V.B.B.B.Z.B.Z.N.C.B.Z.B.B.Z.Z.B.N.M.N.N.N.V.",
"N.N.N.N.N.w g.A.N.S.] o . < z.w   T &.d.v.V.j.x.V.V.l.x.V.b.N.N.j.N.B.N.j.N.N.b.B.N.N.V.",
"N.N.N.A.e.  9 S.b.S.( O ` ! g + 2 j.d.t.b.V.N.d.N.z.g.N.N.N.N.V.l.g.V.p.x.B.N.b.N.N.V.N.",
"N.N.N.S.9 3 1 M.V.N.C.V i.1.X O 8.d.e.y.b.V.N.V.5.p.Z.V.N.b.N.N.Z.z.3.v.Z.N.N.N.V.N.N.N.",
"B.N.B.b.* 3 @ 2.S.V.d., %   - N ~ f.e.e.v.V.V.z.h.g.b.V.N.b.N.N.N.g.j.h.N.N.N.b.N.N.N.V.",
"N.N.B.x.3.D.g.e.V.S.w   $ e g.y.w.y.y.e.x.Z.z.h.Z.N.p.b.V.b.N.N.g.x.A.z.g.V.N.b.N.N.N.N.",
"B.N.N.B.S.b.Z.Z.C.V.v.8.m p.y.y.y.e.y.e.b.B.b.N.N.V.N.b.V.M.N.N.b.B.N.V.b.N.N.b.V.N.N.V.",
"N.N.B.N.N.N.N.N.N.B.x.e.5.q.e.e.w.e.r.w.x.B.V.B.N.B.B.V.V.b.V.V.Z.B.B.N.V.B.N.b.N.N.V.N.",
"B.N.N.N.N.N.N.N.N.V.b.h.j.j.j.j.j.h.j.j.x.N.b.b.b.b.b.N.b.b.b.b.b.b.b.N.b.b.b.N.N.N.N.N.",
"V.N.N.N.N.V.V.N.N.N.N.N.B.N.B.B.N.B.B.B.N.N.N.N.N.N.N.N.N.N.N.C.N.N.N.N.N.N.N.N.N.N.V.N.",
"N.N.N.C.V.N.N.B.N.N.N.C.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.C.B.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"V.C.N.V.N.N.N.N.N.N.N.C.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.V.N.N.V.N.N.N.V.N.V.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.V.N.V."
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 126 2 ",
"   c #040507",
".  c #181100",
"X  c #141417",
"o  c #1B1C1E",
"O  c #221C0F",
"+  c #191C26",
"@  c #3A3421",
"#  c #343331",
"$  c #3A3730",
"%  c gray24",
"&  c #413A25",
"*  c #433F38",
"=  c #4F4116",
"-  c #4D452D",
";  c #444444",
":  c #444548",
">  c #4C4C4C",
",  c #525354",
"<  c #5B5C5D",
"1  c #7E714C",
"2  c #76705D",
"3  c #7A735E",
"4  c #656565",
"5  c #6A6A6A",
"6  c #7A766B",
"7  c #7D796C",
"8  c #757575",
"9  c #7E7C74",
"0  c gray48",
"q  c #8F7B40",
"w  c #89794D",
"e  c #827651",
"r  c #847E6D",
"t  c #807D75",
"y  c #8D815E",
"u  c #9B8B5F",
"i  c #8B8265",
"p  c #86816F",
"a  c #8C836B",
"s  c #918563",
"d  c #958864",
"f  c #9E8F61",
"g  c #948B6F",
"h  c #998D6C",
"j  c #9F9064",
"k  c #9E916A",
"l  c #868274",
"z  c #8B8572",
"x  c #85827A",
"c  c #8A867A",
"v  c #8D897C",
"b  c #948C75",
"n  c #948D79",
"m  c #9E9372",
"M  c #9A927C",
"N  c #A09060",
"B  c #A2936C",
"V  c #A7986E",
"C  c #AF9F6F",
"Z  c #A09473",
"A  c #A39876",
"S  c #A89C76",
"D  c #A69C7C",
"F  c #AA9F7E",
"G  c #848482",
"H  c #888783",
"J  c #8C8A84",
"K  c #86878B",
"L  c #8C8C8A",
"P  c #918D82",
"I  c #9A9483",
"U  c #91908C",
"Y  c #9B978A",
"T  c #9C988F",
"R  c #8E9093",
"E  c #8D919B",
"W  c #959595",
"Q  c #9E9B91",
"!  c #93959C",
"~  c #9B9B9C",
"^  c #A89F83",
"/  c #A39D8D",
"(  c #A29E93",
")  c #A19F99",
"_  c #ABA187",
"`  c #ACA48A",
"'  c #B0A78D",
"]  c #ACA692",
"[  c #AEA997",
"{  c #A1A09E",
"}  c #A9A69B",
"|  c #ADA99C",
" . c #B0AA96",
".. c #B3AD9E",
"X. c #B8B29E",
"o. c #9A9DA6",
"O. c #A4A3A2",
"+. c #AEABA4",
"@. c #ABABAB",
"#. c #B1ADA2",
"$. c #B6B2A6",
"%. c #B9B4A6",
"&. c #B6B3AB",
"*. c #B8B5AC",
"=. c #BDBAAF",
"-. c #B6B6B6",
";. c #B9B7B2",
":. c #BBBAB5",
">. c #BABABB",
",. c #BEBEC1",
"<. c #BFC0C3",
"1. c #C3C3C4",
"2. c #C9C7C1",
"3. c #CAC9C6",
"4. c #C5C6CA",
"5. c #CBCBCB",
"6. c #CECFD3",
"7. c #D3D3D4",
"8. c #D4D5D9",
"9. c #DCDCDD",
"0. c #E5E5E5",
"q. c #E8E7E7",
"w. c #E8E8E7",
"e. c #E9E9EA",
"r. c #F4F4F4",
"t. c gray98",
/* pixels */
"0.0.0.q.0.0.0.0.0.0.e.w.0.w.0.0.0.e.e.0.0.0.0.0.0.e.0.0.0.w.0.0.",
"w.0.q.0.q.0.0.0.0.0.5.9.w.0.0.0.w.8.7.e.0.0.0.q.0.7.0.w.0.0.0.w.",
"0.q.0.q.0.e.0.0.w.0.8 , w.0.0.0.e.@.> O.r.0.0.0.0.> ~ r.0.0.0.w.",
"q.0.q.0.0.0.0.0.0.e.@.% 0.0.0.0.w.0.5 -.e.0.0.0.t.K ~ r.0.w.0.0.",
"0.0.0.0.0.0.0.0.w.9.8 < 9.0.0.0.t.0 # 5.w.0.0.0.w., 4 e.0.0.0.0.",
"0.e.0.0.w.0.e.0.0.0.5.0.w.0.0.0.0.9.7.9.0.0.0.0.0.7.7.0.0.0.0.0.",
"0.e.0.0.q.0.0.e.e.w.e.w.w.w.w.w.w.w.e.e.w.w.q.0.0.w.w.0.0.0.0.0.",
"0.0.0.0.0.0.0.9.7.7.7.6.7.9.7.7.8.7.7.7.7.7.9.0.9.0.9.0.9.0.0.0.",
"0.0.0.0.0.0.0.5.-.-.-.>.+.[ 5.*.] >.-.>.>.-.9.0.w.0.q.0.0.9.0.0.",
"e.0.0.e.0.0.e.5.-.>.>.4.` z o.J n 1.>.>.>.>.9.0.7.w.9.7.w.0.0.q.",
"0.0.0.0.0.0.0.5.-.&.k o.K p O.c G ! m ] ,.>.9.w.7.5.5.9.0.9.0.0.",
"e.0.e.0.0.0.0.5.>.<.v 3 ;.j +.j ;.z 6 -.,.>.9.w.0.>.5.w.0.0.0.q.",
"0.0.0.e.0.0.0.5.*.O.E ] d L 7 H b S o.W *.>.9.0.5.0.7.5.w.9.0.0.",
"w.0.0.0.0.0.0.6.A p a _ G e q w 9 ( h 9 m -.9.0.0.0.w.0.q.0.0.q.",
"0.0.0.0.0.0.0.5.4.R +.I x j :.V a v ..L $.,.9.0.0.0.0.0.0.0.0.0.",
"0.e.0.e.0.0.e.5.m x m I l _ 5.1.{ L S x w V :.>.*.>.*.>.&.5.0.0.",
"w.0.0.0.0.0.0.4.+.J } Q J &.<.$.s x ] T 6 y k / M / g } s >.w.0.",
"0.0.w.w.0.0.0.3.Z l g b l D 1.>.>.! W N Q x H G x H x L t O.e.0.",
"0.e.0.0.0.0.q.5.$.H } ( L *.<.>.>.] 2 ~ ` D ` ` D  .B $.u 2.e.0.",
"0.0.0.0.0.0.q.5.m l h g z D 1.>.,._ } ! x L J J J P v U l O.e.0.",
"0.0.0.0.0.0.w.5.$.H +.~ L ;.1.>.>.,.<.>.d @.M I n T b Q i &.e.0.",
"e.0.0.0.0.0.w.5.m v k g z m 1.-.-.-.-.>...<.$.$.| $.[ ;.] 3.0.0.",
"0.0.0.q.0.0.w.2.B $ ( G < 6.3.7.7.7.7.7.7.7.7.8.7.7.8.7.8.9.0.0.",
"q.q.e.r.0.0.w.C = X S & @ X.4.w.0.e.0.e.0.0.0.0.e.e.e.0.0.0.0.0.",
"0.e.5., 9.0.e.-   1 >.o x $.4.w.7.7.e.5.9.0.9.0.5.e.9.5.w.9.0.0.",
"0.r.W o -.r.e.v D %.. : 5.-.1.q.w.6.2.8.0.0.0.w.9.1.5.0.0.0.0.0.",
"0.e., ; < r.e.~ - + $ B >.-.2.q.w.7.,.9.0.0.0.0.9.,.5.w.0.9.0.w.",
"0.9.-.9.-.0.e., O 9 3.*.>.>.1.w.7.7.e.5.9.0.9.0.5.w.9.5.e.0.0.0.",
"0.0.r.0.r.0.0.6.` =.>.>.>.>.3.w.0.w.0.w.0.0.0.0.w.0.0.0.0.0.0.0.",
"0.0.0.0.0.0.q.5.<.1.,.,.1.>.5.9.9.0.0.9.9.9.9.0.0.9.0.0.0.9.0.0.",
"0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.",
"e.0.0.0.q.q.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0."
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 150 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c gray89",
"o  c #DADADA",
"O  c #E7E7E7",
"+  c #DFDFDF",
"@  c gray86",
"#  c gainsboro",
"$  c #E2E2E2",
"%  c #767676",
"&  c gray83",
"*  c gray94",
"=  c #C3C3C3",
"-  c #888888",
";  c gray92",
":  c gray64",
">  c gray71",
",  c #E4E4E4",
"<  c #A9A9A9",
"1  c #EFEFEF",
"2  c gray79",
"3  c #AFAFAF",
"4  c #ECECEC",
"5  c #BBBBBB",
"6  c gray",
"7  c gray93",
"8  c #DBDBDC",
"9  c gray88",
"0  c #E1E1E1",
"q  c #EAEAEA",
"w  c #E9E9E9",
"e  c gray91",
"r  c #D6D6D7",
"t  c #B6B5B4",
"y  c #B8B8B7",
"u  c #A5A299",
"i  c #A5A39D",
"p  c #ABA8A1",
"a  c #B9B9B8",
"s  c #BAB9B9",
"d  c #DDDDDD",
"f  c #D7D8D8",
"g  c #B7B6B4",
"h  c #989488",
"j  c #979387",
"k  c #9A9586",
"l  c #949085",
"z  c #A29F94",
"x  c #BFBFC0",
"c  c #CFCECE",
"v  c LightGray",
"b  c #D9D9D8",
"n  c #A19E96",
"m  c #979385",
"M  c #928A71",
"N  c #897F61",
"B  c #97907C",
"V  c #959288",
"C  c #B4B2AD",
"Z  c #E2E3E6",
"A  c #E2E2E3",
"S  c #E5E6E6",
"D  c #DADAD8",
"F  c #9E9A90",
"G  c #989281",
"H  c #99927D",
"J  c #B5AF9B",
"K  c #948F7E",
"L  c #969180",
"P  c #A09985",
"I  c #CFCEC8",
"U  c #D0CFCB",
"Y  c #CFCDC9",
"T  c #D3D2CE",
"R  c #E8E8E9",
"E  c #D8D7D5",
"W  c #9A9585",
"Q  c #95907F",
"!  c #A19D91",
"~  c #C2C1BF",
"^  c #9C9A93",
"/  c #979180",
"(  c #908870",
")  c #96907E",
"_  c #979283",
"`  c #928D7C",
"'  c #A5A195",
"]  c #E7E7E9",
"[  c #D8D7D4",
"{  c #9A9587",
"}  c #96907F",
"|  c #9F9A8B",
" . c #C1C1C2",
".. c #B2B0AA",
"X. c #969288",
"o. c #989486",
"O. c #989283",
"+. c #938D7B",
"@. c #A5A194",
"#. c #E7E7E8",
"$. c #DCDBDA",
"%. c #9E9989",
"&. c #969080",
"*. c #A29E91",
"=. c #BEBEBD",
"-. c #B9B9B9",
";. c #A8A59C",
":. c #A6A399",
">. c #A39F92",
",. c #A09C8F",
"<. c #B1ADA4",
"1. c #EDEEF1",
"2. c #C7C3B5",
"3. c #5B5238",
"4. c #726D5E",
"5. c #807D73",
"6. c #DADAD9",
"7. c #DCDCDD",
"8. c #DDDDDE",
"9. c #DDDDDC",
"0. c #DFDFE0",
"q. c gray87",
"w. c #757474",
"e. c #CCCDCF",
"r. c #B1AEA5",
"t. c #605943",
"y. c #514D42",
"u. c #9D9C97",
"i. c #D5D5D5",
"p. c #E5E4E4",
"a. c gray84",
"s. c gray85",
"d. c #838383",
"f. c #C4C5C6",
"g. c #BBB9B4",
"h. c #4B473C",
"j. c #8F8C84",
"k. c #BEBDBB",
"l. c #DCDCDB",
"z. c gray82",
"x. c #E4E4E3",
"c. c #D7D7D7",
"v. c #EEEEEE",
"b. c #D0D0CF",
"n. c #B7B4AD",
"m. c #CACBCC",
"M. c #BCBCBC",
"N. c #E5E5E7",
"B. c #E2E1E1",
"V. c white",
/* pixels */
"    .   X o   O + @     # $   . ",
"  . .   X % & * = - ; * : > * , ",
"    . O X < + 1 2 3 4 4 5 6 7 , ",
"  .   $ 8 . 9 + 0 X @ $ q w $ . ",
"  . e r t y u i p a s d 9 + $ . ",
"  . e f g h j k l z x + c v . , ",
"  . e b n m M N B V C Z A A S , ",
"  . e D F G H J K L P I U Y T   ",
"  . R E W Q ! ~ ^ / ( ) _ ` ' ] ",
"  . R [ { } |  ...X.o.O.L +.@.] ",
". , #.$.%.&.*.=.-.g ;.:.>.,.<.#.",
"  q 1.2.3.4.5.6.@ 7.8.9.0.q.q.. ",
"7 w.e.r.t.y.u.# d i.p.. a.s.. , ",
"0 d.f.g.h.j.k.i.l.z.X x.v c., , ",
". * v.b.n.m.M.a.  , $ 0 . , $ . ",
"  X , O N.B., , , , , , , , , . "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
