#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 56 1 ",
"  c #000000",
". c #0C0C0C",
"X c #131313",
"o c #1B1B1B",
"O c #232323",
"+ c #2B2B2B",
"@ c #333333",
"# c #3B3B3B",
"$ c #007E00",
"% c #424242",
"& c gray30",
"* c #535353",
"= c #5A5A5A",
"- c #676767",
"; c #6D6D6D",
": c #737373",
"> c #7C7C7C",
", c #018001",
"< c #0D850D",
"1 c #118611",
"2 c #158815",
"3 c #1E8C1E",
"4 c #248E24",
"5 c #3A973A",
"6 c #3F993F",
"7 c #449A44",
"8 c #4D9E4D",
"9 c #54A254",
"0 c #5BA45B",
"q c #62A762",
"w c #7CB17C",
"e c #848484",
"r c #8A8A8A",
"t c #959595",
"y c #9B9B9B",
"u c #85B585",
"i c #89B689",
"p c #8DB88D",
"a c #94BB94",
"s c #9BBD9B",
"d c #A3A3A3",
"f c #ACACAC",
"g c #B2B2B2",
"h c #BABABA",
"j c #A4C2A4",
"k c #AEC5AE",
"l c #B0C6B0",
"z c #B6C8B6",
"x c #BECCBE",
"c c #C3C3C3",
"v c #C4CEC4",
"b c #CCCCCC",
"n c #CCD1CC",
"m c #D5D5D5",
"M c #D9D7D9",
"N c #D8D8D8",
/* pixels */
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmmmmmmmmNmmmNmmmmmNmmmmmmmmmm",
"mmmfytyytyytytyyyyyytyytytyyytyyytyyyygmmmmmmmmmmmmmmmmmgyytyytyyytttyyttyytytytytyyytytytygmmmm",
"mmmytgfgfgfgfgfgggfgggfffgggfggggggggtymmmmmmmmmmmmmmmmmyyggfggffgfgfgfggfgfgffggfgffgfgggtdmmmm",
"mmmygNNNNNNmNNNNmmmmmMMmmmMmmmmNmmmmMfdmmmmmmmmmmmmmmmmmtgNNmmMmNNNNNNNmNNNNNNNNNNNmNNNNNMddmmmm",
"mmmtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmbmmmmmmmtgNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddNmmm",
"mmNygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddmmmm",
"mmmtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddNmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfyNmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdNmmmmmmmmmmmmmmmmtgmmmmmmmmmmbnbnbvvvvmmmmmmmmmmmmNfdmmmm",
"mmmtgNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmnnnmmmmmmmmmmtgmmmmmmmmmmkuq532221smmmmmmmmmmmNdymmmm",
"mmmygNmmmmmmmmmmmmmmbmmmmmmmmmmmmmmmmfymmc#OOrcmmmmmmmmmygmmmmmmmmml91<,,,$$$ammmmmmmmmmmNddNmmm",
"mmNtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddNmb:. OebmmmmmmmmtgNmmmmmmmmk5$$$$,,,,ammmmmmmmmmmNddNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmbc:X Oebmmmmmmmtgmmmmmmmmmk72587,,,$ammmmmmmmmmmNdymmmm",
"mmmtfmmmmmmmmmmmmmmmmmmmmmmmmmmbmmmmMfyNmmmc;o O>bmmmmmmtgmmmmmmmmmvsijkw,,,$ammmmmmmmmmmNfdNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNmmmmc;X OecmmmmmtgmmmmmmmmmmmNNni,,,,ammmmmmmmmmmNddmmmm",
"mmmtgNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNmmmmmc;o OebmmmmtgNmmmmmmmmmmmmbi,,,$ammmmmmmmmmmNddmmmm",
"mmmyfNmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmNfyNmmmmmmc;X oebmmmtgmmmmmmmmmmmmmnu$,,$ammmmmmmmmmmNfyNmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfyNmmmmmmmc;X oebmNtgmmmmmmmmmmmmmbi,,,$ammmmmmmmmmmmddNmmm",
"mmmyfNmmmmmmmmmnmmmmmmmnmmmmmmmmmmmmmfyNmmmmmmmmc:. orbNtgNmmmmmmmmmmmmnu,,,$ammmmmnmmmmmNfdNmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfyNmmmmmmmmmf&  +hNtgmmmmmmmmmmmmmni,,,,ammmmmmmmmmmNdymmmm",
"mmmtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfymmmmmmmmmc:. XebNtgmmmmmmmmmmmmmnu,,,$ammmmmmmmmmmNfyNmmm",
"mmmygmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfymmmmmmmNc:X oebmmtgmmmmmmmmmmmmmni,,,,ammmmmmmmmmmNddmmmm",
"mmmtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyNmmmmmmc;X oecmmmtgmmmmmmmmmmmmNbu,,,$ammmmmmmmmmmNfymmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfyNmmmmmc;o O>cmmmNtgNmmmmmmmmmmmNni,,,$ammmmmmmmmmmNddNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNmmmNc:o O>bmmmmmtgNmmmmmmmmmvxxzw,$,$uxvcvmmmmmmmNddmmmm",
"mmmtgmmmmmmmmmmmmmmmmmmmmmmmbmmmmmmmNfyNmmmc:X O>bNmmmmmtgmmmmmmmmmbu9095$,$$7009ummmmmmmmddNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNdyNmmh:X o>cNmmmmmmtgNmmmmmmmmx7$$$$,,,$$$$$7nmmmmmmNdymmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNmb>. oebNmmmmmmmtgmmmmmmmmmz7$$$$$$$$$$$$7mmmmmmmNfdmmmm",
"mmmtfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdmmc#oOecmmmmmmmmNtgmmmmmmmmmv03433433344430mmmmmmmNddNmmm",
"mmmygNmmmmmmmmmmmmmmmmmbmmmmmmmmmmmmNfyNmmbbbmmmmmmmmmmmtgmmmmmmmmmmmbnnnnnnnbbnnnmnmmmmmNddNmmm",
"mmmygmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmygmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmNfymmmm",
"mmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddNmmm",
"mmmyfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNnmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdymmmm",
"mmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfyNmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdNmmm",
"mmmygMNmmmmmmmmmmmmNNNNNmNNNNmNmNmNNNfymmmmmmmmmmmmmmmmmtgMmMmmMmmmmmmmmmmmmNNmmmmmmmmmmmMfdmmmm",
"mmmttffffffffffffffffffdfdffffffffffftyNmmmmmmmmmmmmmmmmytffffffffffffffffffffffffffffffffrdmmmm",
"mmmgdyydydyydyydyyyyyyydyyyyyyyyyyyydyhmmmmmmmmmmmmmmmmmgydyydyydyydyyydyydyydydyddyydyydyyhmmmm",
"mmmmmmmNmmMmmmmmNNNmNmNNNmNmNNNmNNmNmmmmmmmmmmmmmmmmmmmbmNNmmmNmMmmmMmmmmmmmmmmmmmMmmmMmMmMmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmnmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmb",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmbmmmmmmmmmmnmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmbmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmbmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmbmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmbmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmfyttyytyttttttttttttttttytttyttytttgmmmmmmmmmmmmmmmmmftytttttytttttyttttytttyttytttttttygmmmm",
"mmmyyggggggggggggggggggggggggggggfgggtdmmmmmmmmmmmmmmmmmyyggggggggggggggggggggggggggggggggydmmmm",
"mmmygmmmmmmmmmmmmNNmmNNmmmmmmmmmmmMmmfymnmmmmmmmmmmmmmmmtgMmNmmmmmmmmmmMmmmmmmmmmmmMmmmmmMddmmmm",
"mmmygmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdMmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddNmmm",
"mmmygmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmygNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfymmmm",
"mmmtgmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmMfdmmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddmmmm",
"mmmyfmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddNmmm",
"mmmygmmmmmmmmmmmnbbvvvvcnmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmbcccccbmmmmmmmmmNddNmmm",
"mmmtgmmmmmmmmmnku052111<ammmmmmmmmmmmfymmmmmmmnmmmmmmmmmtgmmmmmmmmmmmmmmbroXXX.:bmmmmmmmmmfymmmm",
"mmmyfmmmnmmmmml9<<,,,$$$pmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmg+     -bmmmmmmmmMdymmmm",
"mmmtgNmmmmmmmmh7$$$,$,,$pmmmmmmmmmmmmfyNmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmh=      -mmmmmmmmmNfdmmmm",
"mmmygMmmmmmmmmk72598,$,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmygmmmmmmmmmmmmbeX      -bmmmmmmmmNddNmmm",
"mmNtfmmmmmmmmmbsajkw,$,$pmmmmmmmmmmmmfdMmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmd@ .#    -bmmmmmmmmmddNmmm",
"mmNtgmmmmmmmmmmmNNmp,$,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmh=  @eX   -nmmmmmmmmmfymmmm",
"mmmtgMmmmmmmmmmmmmbp,$,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmn>o oedX   -nmmmmmmmmmddmmmm",
"mmmygmmmmmmmmmmmmmnp<$,$pmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmygmmmmmmnmmmd@ .=bfX   -nmmmmmmmmNfdNmmm",
"mmmtfNmmmmmmmmmmmmnp,$,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmc&  #gmdX   -bmmmmmmmmNfymmmm",
"mmNtgNmmmmmmmmmmmmnp,$,$pmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmmm;o +emmfX   -bmmmmmmmmNdymmmm",
"mmNtfNmmmmmmmmmmmmnp,,,$pmmmmmmmmmmmmfyMmmmmmmmmmmmmmmmmygmmmmmmmmd+ .-bmmfX   -bmmmmmmmmNfdmmmm",
"mmmygmmmmmmmmmmmmmna,,,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgMmmmmmmm&. %fmmbd.   -bmmmmmmmmNddNmmm",
"mmNtgNmmmmmmmmmmmmbp,,,$pmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmm#  .OOOOo    XO#emmmmmmmddNmmm",
"mmNtgNmmmmmmmmmmmmnp,,,$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmm#              o:Nmmmmmmfymmmm",
"mmmygNmmmmmmmnmmmNnp,$$$pmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmm#              o:Nmmmmmmddmmmm",
"mmmtfNmmmmmmmmmvxxzw,$$$ucxxvmmnmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmb;%%%%%%%@    O#*tNmmmmmNfdNmmm",
"mmmtgNmmmmmmmmbu9995$$$$6099wmmmmmmmmfymmmmmmmnmmmmmmmmNtgmmmmmmmmgfffdffdr.   *dgcmmmmmmmfdmmmm",
"mmmyfNmmmmmmmmx8$$$$$$$,$$$$7bmmmmmmmfdMmmmmmmmmmmmmmmmmtgNmmmmmmmNmmNNNNmfX   -mNmmmnmmmMdymmmm",
"mmmygmmmmmmmmmc8$$$$$$$$$$$$7nmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmf.   -bmmmmmmmmNfdmmmm",
"mmmtgNmmmmmmmmvq3444444444430mnmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmnf@O+O>nmmmmmmmmNddmmmm",
"mmmyfNmmmmmmmmmnnnmnnmnnnmnnnmmmmmmmmfdmmmmmmmmmmmmmmmmNtgNmmmmmmmmmmmmmmmmbnnmbmmmmmmmmmNddmmmm",
"mmmtgNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNdymmmm",
"mmNyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfymmmmmmmmmmmmmmmmmtgNmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmfdmmmm",
"mmmtfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfdmmmmmmmmmmmmmmmmmtgmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMddNmmm",
"mmmyfNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNfymmmmmmmmmmmmmmmmmtgmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNddmmmm",
"mmmygNNNNNNNNNNNNNNNNNNNMmNNmMNNmmmNNfdmmmmmmnmmmmmmmmmmtgMNNNNNNNNNmNNNNNNNNNNNNNNNNNNNMMfymmmm",
"mmmytddfddfdfddddfddfdddfdfdfdfddfdffrdmmmmmmmmmmmmmmmmmytfdddddfdfdfdfdddddddddddfddfddffrdmmmm",
"mmmgddydddydydddydddyddddydyyydddyddydhmmmmmmmmmmmmmmmmmgdyddddddyyddyddddddddddddyddydddydhmmmm",
"mmmmmNmNmNNmmNmmmmNNmNNmmNmmNmNNmNmNmmmmmmmmmmmmmmmmmmmnmmNmNmmmNmmmmmmmmmNmNNmmmNmNmmNmNNmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 59 1 ",
"  c #D5D5D5",
". c gray52",
"X c #808080",
"o c #CAD1CA",
"O c #94BB94",
"+ c #67A967",
"@ c #3A973A",
"# c #0D850D",
"$ c #008000",
"% c #C8D0C8",
"& c #161616",
"* c black",
"= c gray2",
"- c #A0A0A0",
"; c #96BC96",
": c gray64",
"> c gray4",
", c #090909",
"< c gray62",
"1 c #97BC97",
"2 c #1F8C1F",
"3 c #4C9E4C",
"4 c #79B079",
"5 c #81B481",
"6 c #AAC4AA",
"7 c gray45",
"8 c gray7",
"9 c #A2A2A2",
"0 c #CBD1CB",
"q c #A0C0A0",
"w c #7FB37F",
"e c #D2D4D2",
"r c #ADC5AD",
"t c #060606",
"y c #010101",
"u c gray",
"i c #CBCBCB",
"p c gray11",
"a c #565656",
"s c #9B9B9B",
"d c gray79",
"f c #181818",
"g c gray32",
"h c #505050",
"j c #B4B4B4",
"k c #979797",
"l c #C8C8C8",
"z c gray30",
"x c #585858",
"c c #939393",
"v c #1D1D1D",
"b c gray80",
"n c #020202",
"m c #101010",
"M c #868686",
"N c #7E7E7E",
"B c gray42",
"V c #717171",
"C c white",
/* pixels */
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.                .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X         oO+@#$$$$%           X    ",
"    X                              X   &*=-         X         ;$$$$$$$$%           X    ",
"    X                              X   :>*,<        X         ;$$$$$$$$%           X    ",
"    X                              X    :>*,<       X         12345$$$$%           X    ",
"    X                              X     :>*,<      X             6$$$$%           X    ",
"    X                              X      :>*,<     X             6$$$$%           X    ",
"    X                              X       :>*,<    X             6$$$$%           X    ",
"    X                              X        :>*,<   X             6$$$$%           X    ",
"    X                              X         :>*,<  X             6$$$$%           X    ",
"    X                              X          7=*8  X             6$$$$%           X    ",
"    X                              X         9,*,<  X             6$$$$%           X    ",
"    X                              X        9,*,<   X             6$$$$%           X    ",
"    X                              X       9,*,<    X             6$$$$%           X    ",
"    X                              X      9,*,<     X             6$$$$%           X    ",
"    X                              X     9,*,<      X         0qqqw$$$$;qqqe       X    ",
"    X                              X    9,*,<       X         r$$$$$$$$$$$$0       X    ",
"    X                              X   9,*,<        X         r$$$$$$$$$$$$0       X    ",
"    X                              X   &*t-         X         r$$$$$$$$$$$$0       X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.                .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.                .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X         oO+@#$$$$%           X                X              -y****u         X    ",
"    X         ;$$$$$$$$%           X                X             ip*****u         X    ",
"    X         ;$$$$$$$$%           X                X             a******u         X    ",
"    X         12345$$$$%           X                X            s**t****u         X    ",
"    X             6$$$$%           X                X           df**7****u         X    ",
"    X             6$$$$%           X                X           g**hj****u         X    ",
"    X             6$$$$%           X                X          k**flj****u         X    ",
"    X             6$$$$%           X                X         l&*ys j****u         X    ",
"    X             6$$$$%           X                X         z**x  j****u         X    ",
"    X             6$$$$%           X                X        c**vb  j****u         X    ",
"    X             6$$$$%           X                X        p*n:   j****u         X    ",
"    X             6$$$$%           X                X        m*************a       X    ",
"    X             6$$$$%           X                X        m*************a       X    ",
"    X             6$$$$%           X                X        m*************a       X    ",
"    X         0qqqw$$$$;qqqe       X                X        MNNNNNNB****VN9       X    ",
"    X         r$$$$$$$$$$$$0       X                X               j****u         X    ",
"    X         r$$$$$$$$$$$$0       X                X               j****u         X    ",
"    X         r$$$$$$$$$$$$0       X                X               j****u         X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    X                              X                X                              X    ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.                .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 159 2 ",
"   c #D5D5D5",
".  c gray83",
"X  c gray84",
"o  c #D8D8D8",
"O  c #D7D7D7",
"+  c #CDCDCD",
"@  c #C8C8C8",
"#  c gray79",
"$  c #9F9F9F",
"%  c #B1B1B1",
"&  c #AEAEAE",
"*  c #AFAFAF",
"=  c gray88",
"-  c gray85",
";  c #DADADA",
":  c LightGray",
">  c #D9DAD9",
",  c #D7D9D7",
"<  c #D6D9D6",
"1  c #D6D8D6",
"2  c #D8D9D8",
"3  c #D2D2D2",
"4  c #D8D5D8",
"5  c #E0D8E0",
"6  c #E4DAE4",
"7  c #E6DBE6",
"8  c #DCD7DC",
"9  c #D2D3D2",
"0  c #D4D3D4",
"q  c #CBCBCB",
"w  c gray80",
"e  c #DDDDDD",
"r  c #D6D5D6",
"t  c #BFCCBF",
"y  c #8CB88C",
"u  c #6EAB6E",
"i  c #61A761",
"p  c #9DBE9D",
"a  c #DCD8DC",
"s  c #D3D4D3",
"d  c #ACACAC",
"f  c #010101",
"g  c gray51",
"h  c #E4E4E4",
"j  c gray82",
"k  c #DDD8DD",
"l  c #4C9C4C",
"z  c #007600",
"x  c #067D06",
"c  c #007100",
"v  c #64A464",
"b  c #E4DBE4",
"n  c #D1D3D1",
"m  c gray78",
"M  c #E1E1E1",
"N  c #818181",
"B  c black",
"V  c #838383",
"C  c gray89",
"Z  c #D8D6D8",
"A  c #95BB95",
"S  c #9BBE9B",
"D  c #53A153",
"F  c #69AA69",
"G  c gray52",
"H  c #808080",
"J  c gray91",
"K  c #EDDEED",
"L  c #5DA55D",
"P  c #007300",
"I  c #68A968",
"U  c #E2E2E2",
"Y  c gray53",
"T  c #020202",
"R  c gray50",
"E  c #CECECE",
"W  c gray68",
"Q  c #D0D3D0",
"!  c #5AA45A",
"~  c gray9",
"^  c #323232",
"/  c #DED8DE",
"(  c #67A967",
")  c #E2DAE2",
"_  c gray81",
"`  c gray14",
"'  c #252525",
"]  c #E8DCE8",
"[  c #6BAA6B",
"{  c #ECDEEC",
"}  c #232323",
"|  c gray87",
" . c #C0CCC0",
".. c #BDCBBD",
"X. c #50A050",
"o. c #007700",
"O. c #5BA45B",
"+. c #C1CDC1",
"@. c #D7D5D7",
"#. c gray76",
"$. c gray11",
"%. c #E0DAE0",
"&. c #57A057",
"*. c #007400",
"=. c #037B03",
"-. c #007800",
";. c #65A565",
":. c #D0D2D0",
">. c gray65",
",. c gray37",
"<. c gray86",
"1. c #DBD7DB",
"2. c #61A661",
"3. c #6AAA6A",
"4. c #60A660",
"5. c #9CBE9C",
"6. c #D1D2D1",
"7. c #DFDFDF",
"8. c #DED7DE",
"9. c #E7DBE7",
"0. c #E5DAE5",
"q. c #DDD7DD",
"w. c #D0D0D0",
"e. c #E6E6E6",
"r. c #C6C6C6",
"t. c gray43",
"y. c gray38",
"u. c #9A9A9A",
"i. c gainsboro",
"p. c #535353",
"a. c #5F5F5F",
"s. c #909090",
"d. c #040404",
"f. c gray39",
"g. c gray5",
"h. c gray34",
"j. c DimGray",
"k. c #484848",
"l. c #111111",
"z. c #656565",
"x. c gray58",
"c. c gray55",
"v. c #585858",
"b. c #6A6A6A",
"n. c gray3",
"m. c #313131",
"M. c #929292",
"N. c #393939",
"B. c gray25",
"V. c #444444",
"C. c gray12",
"Z. c gray10",
"A. c #676767",
"S. c gray40",
"D. c gray60",
"F. c #5B5B5B",
"G. c #9B9B9B",
"H. c #E7E7E7",
"J. c white",
/* pixels */
"                                                                                                ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . o @ % = - ; ; ; ; ; ; ; ; ; ; - = % @ O : .   . o @ % = - ; ; > , < 1 2 ; ; ; - = % @ o .   ",
"  . O # & - 3 : : : : : : : : : : 3 - & # ; o : . . O # & - 3 : : 4 5 6 7 8 9 0 : 3 - & # O .   ",
"  . O # * ; :                     : ; & q w # e : . O # * ; : . r t y u i p a s . : ; * # O .   ",
"  . O # * ; :                     : ; d : $ f g h j O # * ; : s k l z x c v b n . : ; * # O .   ",
"  . O # * ; :                     : ; * m M N B V C . # * ; : . Z A S D z F b n . : ; * # O .   ",
"  . O # * ; :                     : ; * #   h G B H J @ & ; :   . a K L P I b n . : ; * # O .   ",
"  . O # * ; :                     : ; * # O j U Y T R E W ; : . . Q k ! P I b n . : ; * # O .   ",
"  . O # * ; :                     : ; * # o j - : ~ ^ w * ; : . . n / ! P ( ) Q   : ; * # O .   ",
"  . O # * ; :                     : ; * #   ; _ ` ' _ w W ; :   . r ] L P [ { . . : ; * # O .   ",
"  . O # * ; :                     : ; * m = j ` } w | m * ; : . r  ...X.o.O. .+.@.: ; * # O .   ",
"  . O # * ; :                     : ; W + #.$.' E ;   # * ; : 9 %.&.*.=.-.=.P ;.b :.; * # O .   ",
"  . O # * ; :                     : ; W j >.,.# <.j o # * ; : s 1.A 2.[ 3.[ 4.5.k 6.; * # O .   ",
"  . O # & - 3 : : : : : : : : : : 3 - & @ 7.J O : . O # & - 3 : 9 8.9.0.0.0.9.q.9 3 - & # O .   ",
"  . o @ % = - ; ; ; ; ; ; ; ; ; ; - = % # X w..   . o @ % = - ; ; 2 1 < < < 1 2 ; - = % @ o .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"                                                                                                ",
"                                                                                                ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . o @ % = - ; ; > , < 1 2 ; ; ; - = % @ o .     . o @ % = - ; ; ; ; - X X o ; ; - = % @ o .   ",
"  . O # & - 3 : : 4 5 6 7 8 9 0 : 3 - & # O .     . O # & - 3 : : : 3 X h e.e 3 : 3 - & # O .   ",
"  . O # * ; : . r t y u i p a s . : ; * # O .     . O # * ; : .   : o r.t.y.u.i.: : ; * # O .   ",
"  . O # * ; : s k l z x c v b n . : ; * # O .     . O # * ; : . . 3 7.p.B B a.C j : ; * # O .   ",
"  . O # * ; : . Z A S D z F b n . : ; * # O .     . O # * ; :   j M s.d.` B f.C j : ; * # O .   ",
"  . O # * ; :   . a K L P I b n . : ; * # O .     . O # * ; : : - r.g.h.j.B f.U j : ; * # O .   ",
"  . O # * ; : . . Q k ! P I b n . : ; * # O .     . O # * ; : : 7.k.l.- z.B z.e.j : ; * # O .   ",
"  . O # * ; : . . n / ! P ( ) Q   : ; * # O .     . O # * ; j = x.B c.h v.B a.i.j : ; * # O .   ",
"  . O # * ; :   . r ] L P [ { . . : ; * # O .     . O # * ; _ e.b.B n.B B T B m.  . ; * # O .   ",
"  . O # * ; : . r  ...X.o.O. .+.@.: ; * # O .     . O # * ; j 7.M.N.B.V.C.B Z.A.. : ; * # O .   ",
"  . O # * ; : 9 %.&.*.=.-.=.P ;.b :.; * # O .     . O # * ; : . O ; o J y.B S.J j : ; * # O .   ",
"  . O # * ; : s 1.A 2.[ 3.[ 4.5.k 6.; * # O .     . O # * ; :   . : 3 ; D.F.G.<.: : ; * # O .   ",
"  . O # & - 3 : 9 8.9.0.0.0.9.q.9 3 - & # O .     . O # & - 3 : : : : 3 e H.i.3 : 3 - & # O .   ",
"  . o @ % = - ; ; 2 1 < < < 1 2 ; - = % @ o .     . o @ % = - ; ; ; ; ; o X o ; ; - = % @ o .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 216 2 ",
"   c #D5D5D5",
".  c gray83",
"X  c LightGray",
"o  c #D7D7D7",
"O  c gray86",
"+  c #DADADA",
"@  c #D8D8D8",
"#  c #CACACA",
"$  c #B4B4B4",
"%  c #B7B7B7",
"&  c #B6B6B6",
"*  c #D0D0D0",
"=  c gray84",
"-  c #C3C3C3",
";  c gray71",
":  c gray73",
">  c #C8C8C8",
",  c gray77",
"<  c #C5C5C5",
"1  c #ACACAC",
"2  c #C1C1C1",
"3  c gray85",
"4  c #AAAAAA",
"5  c gray75",
"6  c #C6C6C6",
"7  c #C3C4C3",
"8  c #C2C4C2",
"9  c #C4C5C4",
"0  c #A7A7A7",
"q  c #CECECE",
"w  c gainsboro",
"e  c gray87",
"r  c #BCBCBC",
"t  c gray82",
"y  c gray69",
"u  c #DFDBDF",
"i  c #E3DCE3",
"p  c #E2DCE2",
"a  c #DDDDDD",
"s  c gray70",
"d  c #CDCDCD",
"f  c #B9B9B9",
"g  c #E2E2E2",
"h  c #D2D2D2",
"j  c #AFAFAF",
"k  c gray81",
"l  c #D5D4D5",
"z  c #D3D4D3",
"x  c #BACABA",
"c  c #A8C2A8",
"v  c #AAC3AA",
"b  c #D0D2D0",
"n  c #CBCBCB",
"m  c #A0A0A0",
"M  c gray18",
"N  c #DFDFDF",
"B  c #D5D6D5",
"V  c #DAD7DA",
"C  c #4A9E4A",
"Z  c #007C00",
"A  c #078007",
"S  c #C0CCC0",
"D  c #D9D6D9",
"F  c gray72",
"G  c #4E4E4E",
"H  c gray7",
"J  c #D6D5D6",
"K  c #7AB07A",
"L  c #1B8A1B",
"P  c #038103",
"I  c #C2CDC2",
"U  c #C0C0C0",
"Y  c gray89",
"T  c #555555",
"R  c #0C0C0C",
"E  c gray",
"W  c gray68",
"Q  c #E2DAE2",
"!  c #DFD9DF",
"~  c #208D20",
"^  c #007F00",
"/  c #E1E1E1",
"(  c #5D5D5D",
")  c gray8",
"_  c #CED2CE",
"`  c #1F8C1F",
"'  c #008000",
"]  c #E6E6E6",
"[  c gray53",
"{  c black",
"}  c #A4A4A4",
"|  c #D7D5D7",
" . c gray90",
".. c gray51",
"X. c gray1",
"o. c gray61",
"O. c #E0D9E0",
"+. c #228D22",
"@. c #D0D3D0",
"#. c #E5DBE5",
"$. c gray49",
"%. c #010101",
"&. c #8AB78A",
"*. c #5DA55D",
"=. c #108510",
"-. c #007E00",
";. c #59A359",
":. c #7AB17A",
">. c #A2A2A2",
",. c #9B9B9B",
"<. c #E4E4E4",
"1. c #D2D4D2",
"2. c #DED8DE",
"3. c #459B45",
"4. c #007B00",
"5. c #118611",
"6. c #128712",
"7. c #007D00",
"8. c #248E24",
"9. c #D4D3D4",
"0. c #CED1CE",
"q. c #CCD0CC",
"w. c #CBD0CB",
"e. c #CFD2CF",
"r. c gray88",
"t. c gray74",
"y. c #DCDBDC",
"u. c #DDDBDD",
"i. c gray80",
"p. c gray65",
"a. c gray67",
"s. c #B8B9B8",
"d. c #BBBBBB",
"f. c gray76",
"g. c #AEAEAE",
"h. c #CDCFCD",
"j. c #CCCECC",
"k. c #D9D7D9",
"l. c #E6DCE6",
"z. c #E7DDE7",
"x. c #DAD8DA",
"c. c #E7E7E7",
"v. c #B1B1B1",
"b. c #C8D0C8",
"n. c #99BC99",
"m. c #7CB17C",
"M. c #76AF76",
"N. c #BCCBBC",
"B. c gray45",
"V. c #848484",
"C. c #D1D3D1",
"Z. c #E1DAE1",
"A. c #67A867",
"S. c #007800",
"D. c #057D05",
"F. c #007400",
"G. c #99BB99",
"H. c #E0DAE0",
"J. c #D2D3D2",
"K. c #222222",
"L. c #131313",
"P. c #AAC4AA",
"I. c #4B9E4B",
"U. c #9DBF9D",
"Y. c #111111",
"T. c #EADDEA",
"R. c #4E9F4E",
"E. c #007500",
"W. c #9DBE9D",
"Q. c #959595",
"!. c #989898",
"~. c #1B1B1B",
"^. c #090909",
"/. c gray78",
"(. c #DCD8DC",
"). c #4D9E4D",
"_. c #007600",
"`. c #747474",
"'. c gray92",
"]. c gray6",
"[. c gray5",
"{. c #9CBE9C",
"}. c #727272",
"|. c #767676",
" X c #060606",
".X c #E9DDE9",
"XX c #52A052",
"oX c #A4C1A4",
"OX c gray44",
"+X c gray2",
"@X c #88B688",
"#X c #279027",
"$X c #138513",
"%X c #238C23",
"&X c #369636",
"*X c #C1CDC1",
"=X c #D8D5D8",
"-X c #D9DAD9",
";X c #0E0E0E",
":X c gray4",
">X c #86B586",
",X c #1E8C1E",
"<X c #359535",
"1X c #389638",
"2X c #2D922D",
"3X c #444444",
"4X c gray25",
"5X c #DAD6DA",
"6X c #E3DAE3",
"7X c #E0D8E0",
"8X c #DFD8DF",
"9X c #E1D9E1",
"0X c #E2D9E2",
"qX c #D6D8D6",
"wX c #A5A5A5",
"eX c white",
/* pixels */
"                                                                                        ",
"  .   . X X X X X X X X X X X X X X .   .     .   . X X X X X X X X X X X X X X .   .   ",
"    . o O + + + + + + + + + + + + +   .         . @ O + + + + + + + + + + + + +   .     ",
"  . o # $ % & & & & & & & & & & & & * = .     . o - $ % & & & & & & & & & & ; : .   .   ",
"  X O $ ; > , < < < < < < < < , # 1 2 3 .     . 3 4 5 6 < < , 7 8 7 9 < < , > 0 q = .   ",
"  X + % > w @ @ @ @ @ @ @ @ @ o e r 2 3 t X   . @ y . + @ @ 3 u i p 3 @ @ o a s d = .   ",
"  X + & , @ X . . . . . . . . X + f 2 O g 3 h . @ j k   . l z x c v b l . X @ y d = .   ",
"  X + & < @ .                 X + % n m M r N * @ j * B z V C Z Z A S D z X 3 y d = .   ",
"  X + & < @ .                 X + F 2 3 G H 5 a   j * B . J K K L P I D z X 3 y d = .   ",
"  X + & < @ .                 X + f U O Y T R E Y W * = . . Q ! ~ ^ I D z X 3 y d = .   ",
"  X + & < @ .                 X + f 2 @ X / ( ) F ; q = . . z _ ` ' I D z X 3 y d = .   ",
"  X + & < @ .                 X + f 2 3 k ] [ { } f d = . . . _ ` ' S | z X 3 y d = .   ",
"  X + & < @ .                 X + f 2 o  ...X.o. .1 * = l z ! O.+.' @.#.z X 3 y d = .   ",
"  X + & < @ .                 X + f 5 Y $.%.o.g   j * = z D &.*.=.-.;.:.  X 3 y d = .   ",
"  X + & < @ .                 X + % n >.R ,.<.* @ j * B 1.2.3.4.5.6.7.8.| X 3 y d = .   ",
"  X + & , o X X X X X X X X X h 3 F - k q a h . @ j k   X 9.b 0.q.w.0.e.X h @ y d = .   ",
"  X + & # e + + + + + + + + + 3 r.t.U w = X   . @ y   O + + y.u.y.y.u.y.+ 3 N s i.o .   ",
"  X + & 1 r f f f f f f f f f F t.p.- @ X .   X 3 a.$ : f f s.s.s.s.s.s.f F d.} k = .   ",
"  .   * 2 2 2 2 2 2 2 2 2 2 2 2 2 - X   .     . = i.U f.2 2 2 2 2 2 2 2 2 f.U 6   . .   ",
"    . = 3 3 3 3 3 3 3 3 3 3 3 3 3 3   .         . o 3 3 3 3 3 3 3 3 3 3 3 3 3 @ .       ",
"  .   . . . . . . . . . . . . . . . .   .     .   . . . . . . . . . . . . . . . .       ",
"                                                                                        ",
"                                                                                        ",
"  .   . . . . . . . . . . . . . . X .   .     .   . . . . . . . . . . . . . . X .   .   ",
"    . o 3 @ @ @ @ @ @ @ @ @ @ @ @ 3 = .         . @ @ @ @ @ @ @ @ @ @ @ @ @ @ 3   .     ",
"  . @ - 4 y j j j j j j j j j j y a.i.o .     . @ f 1 y j j j j j j j j j j j g.X   .   ",
"  X O $ 5 . k * k h.j.j.k * * k   $ U 3 .     . @ 1 # t * * * * q i.i.k * k . 1 d = .   ",
"  X + % 6 +   B k.Q l.z.x.  =   O : f.3 .     . @ y t o = = = . a c.<.o =   + v.d = .   ",
"  X + & < @ z J b.n.m.M.N.D z X + f 2 3 .     . @ j * = .   h w y B.V.* = X 3 y d = .   ",
"  X + & < @ C.Z.A.S.D.F.G.H.J.X + f 2 3 .     . @ j * = . X o n K.{ L.> o X 3 y d = .   ",
"  X + & < @ z D v P.I.S.U.O.J.X + f 2 3 .     . @ j * = . h g T ) L.Y.# o X 3 y d = .   ",
"  X + & < @ . z V T.R.E.W.O.J.X + f 2 3 .     . @ j * = t Y Q.%.!.~.^./.o X 3 y d = .   ",
"  X + & < @ .   @.(.)._.W.O.J.X + f 2 3 .     . @ j *   @ /.) `.'.].[.+ + h 3 y d = .   ",
"  X + & < @ . . J.2.)._.{.! J.X + f 2 3 .     . @ j * h <.}.{ |.`.^. X`./.= @ y d = .   ",
"  X + & < @ . . J .XXX_.oXT.z X + f 2 3 .     . @ j * h <.OX{ X.{ X.{ +Xy O o y d = .   ",
"  X + & < @ J.! @X#X$XS.%X&X*X=X-Xf 2 3 .     . @ j *   o , j F W ;X:XW h . 3 y d = .   ",
"  X + & < @ J.! >X,X<X1X2X2X*X=X-Xf 2 3 .     . @ j * = . @ O a . 3X4XX @ X 3 y d = .   ",
"  X + & , o X X 5X6X7X8X9X0Xl h 3 F f.3 .     . @ j k   . X h h h e e h X X @ y d = .   ",
"  X + ; > a @ 3 @ qXqXqXqXqX3 @ N d.U 3 .     . @ j . + 3 3 3 3 3 o o 3 3 @ e v.i.o .   ",
"  X + : 0 s y y y y y y y y y y s } 6 @ .     X 3 g.1 v.y y y y y y y y y y v.wXt = .   ",
"  .   . q d d d d d d d d d d d i.k   . .     .   X d d d d d d d d d d d d i.t   .     ",
"    .   = = = = = = = = = = = = o = .           .   = = = = = = = = = = = = o = .       ",
"  .   . . . . . . . . . . . . . . . .         .   . . . . . . . . . . . . . . .         ",
"                                                                                        "
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 189 2 ",
"   c gray83",
".  c gray84",
"X  c gray85",
"o  c #D5D5D5",
"O  c #D8D8D8",
"+  c #D0D0D0",
"@  c gray75",
"#  c #C0C0C0",
"$  c #C1C1C1",
"%  c LightGray",
"&  c #CDCDCD",
"*  c #C3C3C3",
"=  c #B7B7B7",
"-  c #C8C8C8",
";  c gray77",
":  c #C5C5C5",
">  c #B1B1B1",
",  c #CACACA",
"<  c gray73",
"1  c #BBBBBB",
"2  c gray78",
"3  c #C3C4C3",
"4  c #C4C5C4",
"5  c #AFAFAF",
"6  c gray81",
"7  c gainsboro",
"8  c #D7D7D7",
"9  c #DDDDDD",
"0  c #E6E6E6",
"q  c #DADADA",
"w  c gray82",
"e  c #BCBCBC",
"r  c gray86",
"t  c #E2DCE2",
"y  c #E6DDE6",
"u  c #E1DCE1",
"i  c #DBD9DB",
"p  c #CECECE",
"a  c #CBCBCB",
"s  c gray51",
"d  c #B9B9B9",
"f  c #DFDFDF",
"g  c gray79",
"h  c #D5D6D5",
"j  c #DCD7DC",
"k  c #88B688",
"l  c #2E922E",
"z  c #258E25",
"x  c #9CBE9C",
"c  c #DED8DE",
"v  c #D1D2D1",
"b  c #D2D2D2",
"n  c gray52",
"m  c #1E1E1E",
"M  c gray74",
"N  c #E4E4E4",
"B  c #DBD7DB",
"V  c #53A053",
"C  c #007700",
"Z  c #8BB68B",
"A  c #E2DAE2",
"S  c #ECECEC",
"D  c #898989",
"F  c #252525",
"G  c gray76",
"H  c #D1D3D1",
"J  c #E8DCE8",
"K  c #BFCCBF",
"L  c #007A00",
"P  c #8DB88D",
"I  c #F4F4F4",
"U  c #646464",
"Y  c #343434",
"T  c #D3D4D3",
"R  c #D9D6D9",
"E  c #ABC4AB",
"W  c #8AB78A",
"Q  c #E0D9E0",
"!  c #C6C6C6",
"~  c #EAEAEA",
"^  c #9F9F9F",
"/  c #232323",
"(  c #AEAEAE",
")  c #E7DCE7",
"_  c #C0CCC0",
"`  c #007B00",
"'  c #99BD99",
"]  c #F0DFF0",
"[  c #D0D2D0",
"{  c #989898",
"}  c #191919",
"|  c #A9A9A9",
" . c gray91",
".. c #DDD8DD",
"X. c #89B689",
"o. c #309230",
"O. c #007800",
"+. c #278D27",
"@. c #71AD71",
"#. c #D7D8D7",
"$. c gray80",
"%. c gray44",
"&. c gray66",
"*. c gray89",
"=. c #D4D5D4",
"-. c #8AB68A",
";. c #499C49",
":. c #63A763",
">. c #4E9E4E",
",. c #72AD72",
"<. c #D9D5D9",
"1. c #D6D7D6",
"2. c gray72",
"3. c gray87",
"4. c #E4DDE4",
"5. c #EDE1ED",
"6. c #E8DFE8",
"7. c #B4B4B4",
"8. c gray",
"9. c #BABBBA",
"0. c #B8BBB8",
"q. c #B9BBB9",
"w. c #BBBCBB",
"e. c #CAC9CA",
"r. c #C9CAC9",
"t. c #CBCACB",
"y. c #DEDADE",
"u. c #DDDADD",
"i. c #D5D7D5",
"p. c #1E8B1E",
"a. c #0D850D",
"s. c #7FB27F",
"d. c #DAD6DA",
"f. c #A1C0A1",
"g. c #74AE74",
"h. c #70AB70",
"j. c #E5DBE5",
"k. c gray88",
"l. c #4C4C4C",
"z. c #070707",
"x. c #090909",
"c. c #D2D3D2",
"v. c #007E00",
"b. c #70AD70",
"n. c #818181",
"m. c gray22",
"M. c #7B7B7B",
"N. c black",
"B. c #D7D5D7",
"V. c #6FAC6F",
"C. c #E3DAE3",
"Z. c #161616",
"A. c #A7A7A7",
"S. c #767676",
"D. c gray70",
"F. c #DFD9DF",
"G. c #D0D3D0",
"H. c #007F00",
"J. c #78B078",
"K. c #F0E0F0",
"L. c #E1E1E1",
"P. c #0E0E0E",
"I. c #060606",
"U. c gray13",
"Y. c #DFD8DF",
"T. c #1F8C1F",
"R. c #027A02",
"E. c #128412",
"W. c #4D9F4D",
"Q. c gray36",
"!. c gray62",
"~. c #A6C1A6",
"^. c #66A866",
"/. c #7BB07B",
"(. c #6EAB6E",
"). c #7CB17C",
"_. c #D4D3D4",
"`. c gray69",
"'. c gray46",
"]. c #E0DBE0",
"[. c #ECE0EC",
"{. c #E8DEE8",
"}. c #EADFEA",
"|. c #E9E9E9",
" X c #B7B8B7",
".X c #B5B7B5",
"XX c #B6B8B6",
"oX c gray71",
"OX c white",
/* pixels */
"  . X X X X X X X X X X X o   o o   . X X X X X X X X X X O o   ",
". + @ # # # # # # # # # $ % o     . & @ # # # # # # # # @ * o o ",
"X @ = - ; : : : : : ; - > ,   %   X < 1 2 : 3 3 3 4 : ; - 5 6 . ",
"X # - 7 O O O O O O 8 9 @ - 0 q w X e & r 8 t y u i O 8 7 1 p . ",
"X # ; O %           % O e a s d f o e g h j k l z x c v O d p . ",
"X # : O   o o o o o   X 1 b n m M N d , . B k V C Z A v O d p . ",
"X # : O   o o o o o   X e 2 S D F G # g 8 H J K L P A v O d p . ",
"X # : O   o o o o o   X e g + I U Y : g 8 T R E L W Q H O d p . ",
"X # : O   o o o o o   X e ! ~ ^ / ( $ g 8 H ) _ ` ' ] [ O d p . ",
"X # : O   o o o o o   X 1 w { } |  .d , h ..X.o.O.+.@.R #.d p . ",
"X # ; 8 %           % O e $.%.&.*.o e g =.j -.;.:.>.,.<.1.2.p . ",
"X # - 9 O X X X X X O 3.@ - 0 7 w X 1 p 7 #.4.5.6.5.6.#.9 1 & . ",
"X $ > @ e e e e e e e @ ( $.  b   X e 7.8.e 9.0.q.0.9.e 8.( + . ",
"o % , g g g g g g g g g a o       o b g g g g g g g g g - & o   ",
"  o 8 8 8 8 8 8 8 8 8 8 8     o o   o 8 8 8 8 8 8 8 8 8 8 .   o ",
"o                           o o   o                         o o ",
"o   %                       o     o   %                       o ",
"  . X X X X X X X X X X X o   o o   . X X X X X X X X X X X o   ",
". & < e e e 1 1 w.e e 1 e b o     . , d e e e e 1 1 e e 1 M   o ",
"X @ 1 & e.g r.t., , g p 7.g 8   % X d @ & , , g , a , g & > p . ",
"X # 2 r . y.u.h 8 8 . 7 8.g 8     X e & q 8 . q r o 8 . r 1 p . ",
"X # : i...P p.a.s.A [ X e g 8     X e , 8 b X ! / m $ O 8 d p . ",
"X # : #.d.f.g.` h.j.[ X e g 8     X e , 8 b k.l.z.x.M X 8 d p . ",
"X # : O H A c.v.b.j.[ X e g 8     X e ,   N n.m.M.N.: X 8 d p . ",
"X # : O T B.K v.V.C.[ X e g 8     X e g 7 * Z.A.S.N.D.O 8 d p . ",
"X # : O c.F.G.H.J.K.[ X e g 8     X e - L.&.N.P.I.N.U.a r 2.p . ",
"X # : 1.Y.P T.R.E.W.  X e g 8     X e , X & &.D.Q.N.!.. O d p . ",
"X # ; 1.d.~.^./.(.)._.O e g 8     X e g . o r N `.'.% . 8 d p . ",
"X @ - 7 1.].[.{.}.6.8 9 8.- 8     X 1 & r 8 . o 3.|.O 8 7 < & . ",
"O * 5 1 d  X.X.X.XXX2.1 ( & .     X M > 1 d d d = oXd d < ( w . ",
"o o 6 p p p p p p p p & + o   o   o   p p p p p p p p p & w o   ",
"  o . . . . . . . . . . .   o o o   o . . . . . . . . . . .   o "
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 106 2 ",
"   c LightGray",
".  c #CACACA",
"X  c gray79",
"o  c gray81",
"O  c gray83",
"+  c #CDCDCD",
"@  c #CCCBCC",
"#  c #CBCACB",
"$  c #CBCBCB",
"%  c #C5C5C5",
"&  c #CECECE",
"*  c gray80",
"=  c gray76",
"-  c gainsboro",
";  c #D7D7D7",
":  c #C1C1C1",
">  c #C7CAC7",
",  c #CACBCA",
"<  c #C3C3C3",
"1  c #D8D8D8",
"2  c gray84",
"3  c #C6C6C6",
"4  c gray52",
"5  c gray78",
"6  c #DEDADE",
"7  c #68AA68",
"8  c #57A357",
"9  c #E3DDE3",
"0  c #C8CAC8",
"q  c #D2D2D2",
"w  c #BBBBBB",
"e  c gray38",
"r  c #C6C7C6",
"t  c #DED9DE",
"y  c #B4C7B4",
"u  c #529F52",
"i  c #E7DDE7",
"p  c #C5C7C5",
"a  c #D5D5D5",
"s  c gray56",
"d  c #8D8D8D",
"f  c #DDD8DD",
"g  c #82B382",
"h  c #288D28",
"j  c #C3CFC3",
"k  c #CDCBCD",
"l  c #AFAFAF",
"z  c #DADADA",
"x  c #C4C5C4",
"c  c #D6D5D6",
"v  c #A0BFA0",
"b  c #8BB68B",
"n  c #BCCBBC",
"m  c #CCC9CC",
"M  c #CCCDCC",
"N  c gray77",
"B  c gray87",
"V  c #D0CAD0",
"C  c #D4CBD4",
"Z  c #CBC8CB",
"A  c #D4D5D4",
"S  c #D3D5D3",
"D  c #D2D3D2",
"F  c #D0D2D0",
"G  c #D0D0D0",
"H  c #C1C2C1",
"J  c #CAC8CA",
"K  c #D6CCD6",
"L  c #C3C4C3",
"P  c #C8C8C8",
"I  c gray82",
"U  c #C8C9C8",
"Y  c #D1CED1",
"T  c #C5D0C5",
"R  c #73AE73",
"E  c #BECCBE",
"W  c #D9D6D9",
"Q  c #7B7B7B",
"!  c #C9CAC9",
"~  c #CDCCCD",
"^  c #D5D6D5",
"/  c #439743",
"(  c #98BB98",
")  c #E1D9E1",
"_  c #C3C5C3",
"`  c #848484",
"'  c gray14",
"]  c #5EA35E",
"[  c #8AB68A",
"{  c #E0D8E0",
"}  c gray73",
"|  c #3E3E3E",
" . c #232323",
".. c gray58",
"X. c #D3D0D3",
"o. c #C1CFC1",
"O. c #479D47",
"+. c #66AA66",
"@. c #C7C6C7",
"#. c #5F5F5F",
"$. c #B6B6B6",
"%. c #D0CCD0",
"&. c #CECBCE",
"*. c #CDCECD",
"=. c #CECDCE",
"-. c white",
/* pixels */
"  . . . . X o O O + X @ # . $ O ",
". % & * + $ = - ; : + > , & < & ",
". & 1 2 ; 2 3 4 5 $ 6 7 8 9 0 & ",
". * 2 O O q + w e r t y u i p & ",
". + ; O a   $ s d , f g h j k + ",
"X $ a   O   : l z x c v b n m M ",
"o < 3 3 3 N X B   3 % V C Z < q ",
"a 2 2 2 2 2 2   O 2 2 A S a 2 a ",
"a O D F D   a a a O     G q O a ",
"+ H J K J L 3 2 O < % 5 a P : I ",
"U Y T R E W x 2   % z * Q & $ + ",
"! ~ ^ / ( ) _ 2   N - ` ' % & + ",
". ! i ] [ { _ 2 q * } |  ...O * ",
"U X.o.O.+.a @.^   5   } #.$.I * ",
"$ < . %.&.5 N 2 O = . G O o : o ",
"O & & M *.=.q a a I + * * + o a "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
