#include "gtk.h"
/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXkXlXkXlX",
"lXlXkXvXCXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXVXVXVXVXVXVXVXVXVXVXVXVXVXVXVXCXCXCXCXCXCXCXCXCXCXCXCXCXCXBXlXkXlXlX",
"lXjXvX2XI.W.E.E.E.E.E.E.E.E.E.E.E.E.E.R.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.T.T.T.T.T.T.T.T.T.T.T.R.U.U.U.U.U.U.U.U.U.U.U.U.U.U.E.E.E.E.E.E.E.E.E.E.E.E.E.E.R.U.U.U.U.U.U.U.U.U.U.U.U.U.U.^.hXlXkXlX",
"lXhXCXI.v G S S S S S S S S S S S S S K P P P P P P P P P P P P L J P P P P P P P P P P P P P K W Q Q Q Q Q Q Q Q Q Q Q Q W D S S S S S S S S S S S S A K ! Q Q Q Q Q Q Q Q Q Q Q ~ L W dXzXkXlX",
"lXhXVXW.G V M M M M M M M M M M M m N 5.d.p.p.p.p.p.p.p.p.p.p.a.i.:.s.p.p.p.p.p.p.p.p.p.p.p.s.4.,XrX0XqXqXqXqXqXqXqXqX0XrX;XF n M M M M M M M M M M B j 1.aX8XqXqXqXqXqXqXqXqXqX9XsXJ.^ hXzXkXlX",
"lXhXVXE.S M v v v v v v v v v v b v b 3.s.u.i.i.i.i.i.i.i.i.i.i.y.-.p.i.i.i.i.i.i.i.i.i.i.u.a.2.,XtXqXqXqXqXqXqXqXqXqX0XtX:XA x b v v v v v v v v v n f ,.sX0XqX0X0X0X0X0X0X0X9X8XdXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.a.u.u.u.u.u.u.u.u.u.u.i.y.=.p.u.u.u.u.u.u.u.u.u.u.u.p.2.>XeX0X0X0X0X0X0X0X0X0X9XrX;XA x b b b b b b b b b b m f >.sX4X#X=X*X*X*X*X=X&X>XeXaXH.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X:XrXqXwXwXwXwX0XpXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XeX0X0X0X0X0X8XiXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XeX0XqXqXqXqX9XiXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XeX0XqXqXqXqX9XiXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XeX0XqXqXqXqX9XiXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XeX0XqXqXqXqX9XiXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X;XwX9X0X0X0X0X8XuXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XrX;XA x b b b b b b b b b b m f >.dX2X>XtXwXeXeXeXeXqXaXfXiXJ.Q hXzXkXlX",
"lXhXVXE.S M b b b b b b b b b b b v n 3.a.y.u.u.u.u.u.u.u.u.u.u.t.=.i.u.u.u.u.u.u.u.u.u.u.u.p.2.:XwX9X9X9X9X9X9X9X9X9X8XeX-XA c b b b b b b b b b b m f >.aX5XiXzXkXlXlXlXlXkXxXyXiXH.! hXzXkXlX",
"lXhXVXE.S N b b b b b b b b b b n b n 4.d.p.p.p.p.p.p.p.p.p.p.a.u.;.f.s.s.s.s.s.s.s.s.s.s.s.g.5.3XpXtXyXyXyXyXyXyXyXyXtXaX1XZ z v c c c c c c c c c b s <.lXyXiXyXyXyXyXyXyXyXyXrXzXI.Q hXzXkXlX",
"lXhXVXE.A v l l l l l l l l l l z l c >.e.0.0.0.0.0.0.0.0.0.0.0.9.+.1.<.<.<.<.<.<.<.<.<.<.<.1.%.{.%X@X#X#X#X#X#X#X#X#X@X&X'.G N V B B B B B B B B B C c %.OX].{.{.{.{.{.{.{.{.{.].+Xk.^ gXzXkXlX",
"lXhXCXY.T (.(././././././././././.`.J.A B V V V V V V V V V V C c ;.[.!.^.^.^.^.^.^.^.^.^.!.[.i.x B M M M M M M M M M N M C G V C C C C C C C C C C A n @.`.W.!.!.!.!.!.!.!.!.!.W.`.s./ gXzXkXlX",
"lXhXCXU.! pXaXsXsXsXsXsXsXsXsXsXiXgX;Xm x v c c c c c c c c c n a q.cXyXpXpXpXpXpXpXpXpXpXyXcXF.s n n n n n n n n n n v x N C z b n b b b b b b n v b s 1.xXuXpXpXpXpXpXpXpXpXpXuXcXU.Q hXzXkXlX",
"lXhXCXU.Q 9X0X-X*X=X=X=X=X=X=X*X6XrX+XN v b b b b b b b b b b m f 8.aX6X9X9X9X9X9X9X9X9X9X6XaXV.f M p t y y y y y y t c b B Z b h r y y y y y y r g N f >.pX7X9X9X9X9X9X9X9X9X9X7XpXG.! hXzXkXlX",
"lXhXCXU.Q qX0X$X7X5X6X6X6X6X5X8XjXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n 0 k k k k k k k l K c N Z n y a z k k k k l g F Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X=XeXqXwXwXwXwXqXrXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n r n n n n n n n m I x B Z n u k M n n n n n c L Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X*XwX0X0X0X0X0X0XeXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n e b v v v v v v b P x B Z n u h n v v v v b x J Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n e b v b b b b v n P x B Z n u h n v b b b b x K Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n e b v b b b b v n P x B Z n u h n v b b b b x K Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n e b v b b b b v n P x B Z n u h n v b b b b x K Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X=XwXqXqXqXqXqX0XeXlXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n r n b b b b b b n P x B Z n u j m b b b b n x K Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX0X%X9X8X8X8X8X8X8X0XkXrX#XN c b b b b b b b b b b m d 9.dX8XqXqXqXqXqXqXqXqXqX8XdXC.f n q x x x x x x x c P c B Z n y f v x x x x c k J Z s ,.aX8XqXqXqXqXqXqXqXqXqX8XsXH.Q hXzXkXlX",
"lXhXCXU.Q qX9X8XxXkXlXlXlXlXkXxXzXrX#XN v b b b b b b b b b b m d 9.dX8X0X0X0X0X0X0X0X0X0X8XsXC.f b l P K L L L L K P Y x B Z v h F P K L L L L K E V d ,.aX8X0X0X0X0X0X0X0X0X0X8XsXH.Q hXzXkXlX",
"lXhXCXU.Q wXwXrXyXyXyXyXyXyXyXyXwXuX#XB n m m m m m m m m m m N h 9.aX7X9X9X9X9X9X9X9X9X9X7XaXV.f n m N N N N N N N N n c N S b N C V V V V V V C B N h ,.pX7X9X9X9X9X9X9X9X9X9X7XaXG.! hXzXkXlX",
"lXhXCXU.Q 6X7X5X5X5X5X5X5X5X5X5X4XqXoXz a f d d d d d d d d d h q 9.zXtXuXuXuXuXuXuXuXuXuXtXzXD.f M b v v v v v v v v b v V n a d s s s s s s s s s g q >.lXtXuXuXuXuXuXuXuXuXuXtXlXP.Q hXzXkXlX",
"lXhXCXT.U S.A.Z.A.A.A.A.A.A.A.A.Z.F.j.=.w.8.9.9.9.9.9.9.9.9.9.9.9.| X.o.X.X.X.X.X.X.X.X.X.X.O.` S D S S S S S S S S S D D A *.w.8.9.9.9.9.9.9.9.9.9.8.0. ...o.o.o.o.o.o.o.o.o.o.X.+._ ' fXzXkXlX",
"lXhXCXU.Q rXtXrXrXrXrXrXrXrXrXrXeXdX|.'.cXaXdXdXdXdXdXdXdXdXdXaXzXX.t j j j j j j j j j j h d B M c b n n n n n n n n b b g ~.vXpXdXdXdXdXdXdXdXdXdXpXvX-.r k g g g g g g g g g h f n } dXzXkXlX",
"lXhXCXU.Q 0XqX9X0X0X0X0X0X0X0X0X8XuX[.W.uX6X8X8X8X8X8X8X8X8X8X7XtXo.j m j h j h h h j h j n b S M v k f g g g g g g f x m j I.uX6X8X8X8X8X8X8X8X8X8X6XuX=.h M n n n n n n n n n m b C } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j j 8 a i i i i i y j A z S M v 9 i i i i i i i i A n h Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j h a B m m m m M b F H l S M c r M m m m m m m N U b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j j i m c v v v v x Z G l S M c e v v v v v v v b P b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j h i m v b b b b x A G l S M c e b v b b b b v n P b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j h i m v b b b b x A G l S M c e b v b b b b v n P b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j h i m v b b b b x A G l S M c e b v b b b b v n P b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j j i M v b b b b c A G l S M c r b b b b b b b n I b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j h y b x x x x c l C G l S M c w c x x x x x x c P b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q qXqX0XqXqXqXqXqXqXqXqX9XiX[.!.pX9XqXqXqXqXqXqXqXqX0X9XuXX.j j j F Z A A A A C L H l S M c p S A A A A A Z S T b j Y.aX8XqXqXqXqXqXqXqXqXqX9XaX=.f m b b b b b b b b b b c V } dXzXkXlX",
"lXhXCXU.Q 8X9X8X8X8X8X8X8X8X8X8X7XtX].W.uX7X8X8X8X8X8X8X8X8X8X7XtXX.h n A J G H H H H H H N c S N v B J H H H H H H J A n k U.iX6X8X8X8X8X8X8X8X8X8X6XuX=.g m b b b b b b b b b n v V } dXzXkXlX",
"lXhXCXU.! sXfXsXdXdXdXdXdXdXdXdXaXxX+X`.xXiXaXaXaXaXaXaXaXaXaXpXlXO.s v l k k k k k k k k z l C v l l h j j j j j j h k x s !.cXiXaXaXaXaXaXaXaXaXaXiXxX;.a v x x x x x x x x x x z N } dXzXkXlX",
"lXhXCXT.U Z.C.C.C.C.C.C.C.C.C.C.V.D.d.a.K.S.D.D.D.D.D.D.D.D.D.S.J.[ A J H H H H H H H H H H G P U P I I I I I I I I I I U G y.L.S.D.D.D.D.D.D.D.D.D.S.K...Z J H H H H H H H H H H H H { dXzXkXlX",
"lXhXVXE.A j f f f f f f f f f f f d k *.6.3.4.4.4.4.4.4.4.4.4.4.1.%.p.y.u.u.u.u.u.u.u.u.u.y.i.1.*X8X4X5X5X5X5X5X5X5X5X4X9XOX%.6.3.4.4.4.4.4.4.4.4.4.4.3.$.i.y.u.u.u.u.u.u.u.u.u.y.s.=._ fXzXkXlX",
"lXhXVXE.S B m m m m m m m m m m m n m 5.g.a.s.s.s.s.s.s.s.s.s.s.p.-.p.i.i.i.i.i.i.i.i.i.i.u.a.2.<XtXwXwXwXwXwXwXwXwXwXqXuX%X2.g.a.s.s.s.s.s.s.s.s.s.s.s.-.i.i.i.i.i.i.i.i.i.i.i.u.d.-._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.a.u.u.u.u.u.u.u.u.u.u.i.y.=.p.u.u.u.u.u.u.u.u.u.u.u.p.2.>XeX9X0X0X0X0X0X0X0X0X9XtX$X<.a.u.u.u.u.u.u.u.u.u.u.u.u.=.i.u.u.u.u.u.u.u.u.u.u.y.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b v n 3.s.u.i.i.i.i.i.i.i.i.u.i.y.=.p.u.i.i.i.i.i.i.i.i.i.u.p.2.,XrX0XqXqXqXqXqXqXqXqX0XtX$X<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M b b b b b b b b b b b v n 3.a.y.u.u.u.u.u.u.u.u.u.i.t.=.p.u.u.u.u.u.u.u.u.u.u.u.p.2.>XeX9X0X0X0X0X0X0X0X0X9XtX#X<.a.u.u.u.u.u.u.u.u.u.u.u.u.=.u.u.u.u.u.u.u.u.u.u.u.y.d.=._ fXzXkXlX",
"lXhXVXE.S m c c c c c c c c c c v c b 4.d.i.p.p.p.p.p.p.p.p.p.p.u.;.f.s.s.s.s.s.s.s.s.s.s.s.f.4.3XpXtXtXtXtXtXtXtXtXtXtXsX=X2.f.p.a.a.a.a.a.a.a.a.a.a.a.-.a.a.a.a.a.a.a.a.a.a.a.p.h.;._ fXzXkXlX",
"lXhXVXE.S Z N N N N N N N N N N B N B <.y.w.e.e.e.e.e.e.e.e.e.e.w.@.2.1.1.1.1.1.1.1.1.1.1.1.2.&.|.*X$X$X$X$X$X$X$X$X$X#X=X).*.0.7.7.7.7.7.7.7.7.7.7.8.7.#.8.7.7.7.7.7.7.7.7.7.7.7.q.@.` fXzXkXlX",
"lXhXVXE.D D Z Z Z Z Z Z Z Z Z Z Z C F H Z Z Z Z Z Z Z Z Z Z Z S m =.^.U.T.T.T.T.T.T.T.T.T.U.~.u.%.2.<.<.<.<.<.<.<.<.<.<.2.*.@.2.,.,.,.,.,.,.,.,.,.,.<.,.X.<.,.,.,.,.,.,.,.,.,.,.,.3...` fXzXkXlX",
"lXhXVXE.S n c c c c c c c c c c c z N V z v n b b b b b b n v b a w.vXuXaXaXaXaXaXaXaXaXaXuXxXL.6.g.a.s.s.s.s.s.s.s.s.a.f.0.2.h.a.s.s.s.s.s.s.s.s.s.s.s.;.s.s.s.s.s.s.s.s.s.s.s.a.j.:._ fXzXkXlX",
"lXhXVXE.S M b b b b b b b b b b b v V C b h y u u u u u u y h N d 8.aX6X8X8X8X8X8X8X8X8X8X6XiXS.3.a.u.u.u.u.u.u.u.u.u.u.p.7.,.a.y.u.u.u.u.u.u.u.u.u.u.u.=.u.u.u.u.u.u.u.u.u.u.u.y.s.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C n r a k h h h h j f F C s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y z M n n n n m v P V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y k n v v v v b x K V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y k n v b b b b x L V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y k n v b b b b x L V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y k n v b b b b x L V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C b y l n b b b b n c L V s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C n r g c x x x x x k K C s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S M v b b b b b b b b b b c B C v g F L J K K K K J E B s 9.dX8XqXqXqXqXqXqXqXqXqX8XaXD.4.s.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXVXE.S B n m m m m m m m m m m b C Z v M C C C C C C C C B M f 8.aX6X9X9X9X9X9X9X9X9X9X6XiXS.4.s.u.i.i.i.i.i.i.i.i.u.a.8.<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.i.i.i.i.i.i.i.i.i.i.u.d.-._ fXzXkXlX",
"lXhXVXE.A j f f f f f f f f f f f s c N j l j j j j j j j j k x u q.vXuXaXaXaXaXaXaXaXaXaXuXxXK.3.s.u.u.u.u.u.u.u.u.u.u.a.7.,.s.u.u.u.u.u.u.u.u.u.u.u.u.=.u.u.u.u.u.u.u.u.u.u.u.y.d.=._ fXzXkXlX",
"lXhXVXR.K 1.,.>.>.>.>.>.>.>.>.>.>.<.&./ ` _ _ _ _ _ _ _ _ _ _ _ ( ] ;.=.=.=.=.=.=.=.=.=.=.=.;...$.-.=.=.=.=.=.=.=.=.=.=.-.#.X.;.=.=.=.=.=.=.=.=.=.=.=.=.| =.=.=.=.=.=.=.=.=.=.=.=.:.} ' fXzXkXlX",
"lXhXCXU.! aXsXsXdXdXdXdXdXdXdXdXaXkX&X2.j.d.d.d.d.d.d.d.d.d.d.s.k.E i g h h h h h h h h h g a Z i.i.i.i.i.i.i.i.i.i.i.u.a.8.<.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.i.i.i.i.i.i.i.i.i.i.u.d.-._ fXzXkXlX",
"lXhXCXU.Q 8X0X4X2X2X2X2X2X2X2X2X5XtX X,.a.y.y.y.y.y.y.y.y.y.y.y.a.! c m z k l k k k k k l n v J y.i.u.u.u.u.u.u.u.u.u.u.a.7.,.s.u.u.u.u.u.u.u.u.u.u.i.u.=.i.u.u.u.u.u.u.u.u.u.u.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qXqX#X:X;X;X;X;X;X;X>XiXyXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x j 8 i y u u u u t h A l H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X=XrXeXeXeXeXeXwXtXlXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x g a B m m m m M b F J k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X*XqX0X0X0X0X0X9XwXkXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h i m c v v v v x Z G k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h i m v b b b b x A H k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h i m v b b b b x A H k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X*XwX0XqXqXqXqX0XeXlXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h i m v b b b b x A H k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X=XwX0XqXqXqXqX0XeXlXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h i M v b b b b c A H k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX0X&X0X8X9X9X9X9X8XqXkXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h y b x c c c c l C G k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q qX9X>XaXiXiXiXiXiXiXsXzXtXXX,.s.u.i.i.i.i.i.i.i.i.u.u.s.Q x h h S C C C C C B K J k H u.i.u.i.i.i.i.i.i.i.i.u.a.7.,.s.u.i.i.i.i.i.i.i.i.i.i.u.=.i.u.i.i.i.i.i.i.i.i.i.u.d.=._ fXzXkXlX",
"lXhXCXU.Q 9X8XeXgXfXfXfXfXfXfXgXyXeX X,.a.y.u.u.u.u.u.u.u.u.u.y.a.Q z b S K J J J J J J K B z H y.u.y.u.u.u.u.u.u.u.u.y.p.7.,.a.y.u.u.u.u.u.u.u.u.u.u.y.=.u.u.u.u.u.u.u.u.u.u.u.y.s.=._ fXzXkXlX",
"lXhXCXU.~ sXdXaXiXiXiXiXiXiXiXiXiXlX&X3.j.s.d.d.d.d.d.d.d.d.d.s.j.! k b x l z z z z z z l c z H s.d.d.d.d.d.d.d.d.d.d.d.h.q.3.j.s.d.d.d.d.d.d.d.d.d.d.d.:.d.d.d.d.d.d.d.d.d.d.d.s.k.>._ fXzXkXlX",
"lXhXCXU.L J.J.H.J.J.J.J.J.J.J.J.H.P.c...:.=.=.=.=.=.=.=.=.=.=.=.:.T M V V V V V V V V V V V N J =.-.=.=.=.=.=.=.=.=.=.=.;.@...:.=.=.=.=.=.=.=.=.=.=.-.=.} -.=.=.=.=.=.=.=.=.=.=.=.>.{ ( fXzXkXlX",
"lXhXBX^.W ^ Q Q Q Q Q Q Q Q Q Q ! Q ~ ` _ _ _ _ _ _ _ _ _ _ _ _ _ [ } } } } } } } } } } } } } { _ _ _ _ _ _ _ _ _ _ _ _ _ ` ` _ _ _ _ _ _ _ _ _ _ _ _ _ ' _ _ _ _ _ _ _ _ _ _ _ _ _ ( $.fXzXkXlX",
"lXkXlXhXdXhXhXhXhXhXhXhXhXhXhXhXhXhXgXfXfXfXfXfXfXfXfXfXfXfXfXfXfXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXfXkXlXkXlX",
"lXlXkXlXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXzXlXkXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"88 88 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXkXlXkXlX",
"lXlXkXcXBXNXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXVXVXVXVXVXVXVXVXVXVXVXVXBXBXBXBXBXBXBXBXBXBXBXBXBXBXVXVXVXVXVXVXVXVXVXVXVXVXVXNXlXkXlXlX",
"lXkXcXqX).[.].].].].].].].].].].].].`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.(.(.(.(.(.(.(.(.(.(.(.(._.[.].].].].].].].].].].].].(.(.(.(.(.(.(.(.(.(.(.(.(. XkXlXkXlX",
"lXhXBX).m G D D D D D D D D D D S G Y Y Y Y Y Y Y Y Y Y Y Y I U Y Y Y Y Y Y Y Y Y Y Y I ( _ _ _ _ _ _ _ _ _ ) ` Q S D D D D D D D D D D S F ( _ ) ) ) ) ) ) ) ) ) ' R ( hXzXkXlX",
"lXhXNX[.G N m m m m m m m m m M c I s.a.a.a.a.a.a.a.a.a.p.f.1.r.s.a.a.a.a.a.a.a.a.a.d.7.1XyXwXeXeXeXeXeXeXeXqXfXY.k N m m m m m m m m M v F <XyXeXtXtXtXtXtXtXtXwXdX!.' kXlXkXlX",
"lXhXBX].D m v b v v v v v v v b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.5.,XrX0XqXqXqXqXqXqXqX8XsXP.h n b v v v v v v v b x S >XrX5X4X4X4X4X4X4X4X6XsXW._ kXlXkXlX",
"lXhXBX].D m b b b b b b b b b b z L p.u.u.u.u.u.u.u.u.u.u.a.,.q.p.u.u.u.u.u.u.u.u.u.p.4.>XeX0X0X0X0X0X0X0X0X8XaXP.h n b b b b b b b b b x S >XwX#X,X>X>X>X>X>X>XuXaXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX;XtXwXeXeXeXeXeXjXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX-XwX0X0X0X0X0XqXhXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX-XwX0XqXqXqX0XqXjXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX-XwX0XqXqXqX0XqXjXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX-XwX0XqXqXqX0XqXjXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX=XqX9X9X9X9X9X0XhXpXW._ kXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXP.h n b b b b b b b b b x S >XqX:XuXrXtXtXtXrXtXkXpXW._ kXlXkXlX",
"lXhXBX].D M n n n n n n n n n m c P u.y.y.y.y.y.y.y.y.y.y.p.>.w.p.u.u.u.u.u.u.u.u.u.p.4.;XqX7X8X8X8X8X8X8X8X6XiXL.h n b b b b b b b b b x S ;XqXrXjXgXhXhXhXgXjXpXuXE._ kXlXkXlX",
"lXhXBX].S z k k k k k k k k k l f J g.d.d.d.d.d.d.d.d.d.d.h.1.q.p.i.i.i.i.i.i.i.i.i.p.5.9XhXsXdXdXdXdXdXdXdXpXbXW.f b c c c c c c c c v z A 4XsXyXtXtXtXtXtXtXtXrXkX/.) kXlXkXlX",
"lXhXBX'.H ^ Q Q Q Q Q Q Q Q Q Q Q ~ #.$.$.$.$.$.$.$.$.$.$.%. .4.8.7.7.7.7.7.7.7.7.7.9.=.k.M.b.n.n.n.n.n.n.n.b.V.8.B S A A A A A A A A A C J S.U.P.I.I.I.I.I.I.I.P.W.d.] jXlXkXlX",
"lXhXVX(._ eX0XqXwXwXwXwXwXwXwX8XdXb.i c z z z z z z z z x g I 2X5X4X4X4X4X4X4X4X4X2XrXZ.r g f g g g g g g g f a n V n M N N N N N N N M b F oX<X:X:X:X:X:X:X:X:X;X6XK.` kXlXkXlX",
"lXhXVX(._ eXqX6X5X5X5X5X5X5X5X6XfXn.f M b b b b b b b b n l T 9XeXwXwXwXwXwXwXwXwX0XfXH.j N x l l l l l l l b n A M c k h h h h h h h x x S <XuXeXrXrXrXrXrXrXrXwXfX!._ kXlXkXlX",
"lXhXVX(.) rX5X$X,X:X>X>X>X:X<XyXsXn.d m b b b b b b b b n l T 7XqX0X0X0X0X0X0X0X0X8XsXF.h c 0 a i i i i i p Z c Z N z 0 p i i i i i i Z x S :XrX9X0X0X0X0X0X0X0X8XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X<XtXwXeXeXeXwXuXgXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h z i B n m m m m N P z Z N k i N m m m m m M I z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X>XwX0X0X0X0X9XrXfXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h x u n c v v v v n K x Z N k y n c v v v v b L z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX9XtXgXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h x u m v b b b v n L x Z N k u m v b b b v n L z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX9XtXgXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h x u m v b b b v n L x Z N k u m v b b b v n L z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX0XtXgXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h x u m v b b b v n L x Z N k u m v b b b v n L z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X>XwX9X0X0X0X9XrXfXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h x u n c v v v c b K x Z N k y n c v v v c b L z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) tX4X<XyXeXrXrXrXeXiXgXaXn.d m b b b b b b b b n l T 7XwX0XqXqXqXqXqXqXqX8XsXF.h z p B m M M M m B I z Z N k i B m M M M m N I z S :XrX0XqXqXqXqXqXqXqX9XaXW._ kXlXkXlX",
"lXhXVX(.) wX7XiXjXhXhXhXhXgXkXyXpXn.f M n n n n n n n n m z T 5X9X8X8X8X8X8X8X8X8X6XiXD.g b C L K K K K K L F x Z B c C P K L L L K P H x D -XqX7X8X8X8X8X8X8X8X6XuXR._ kXlXkXlX",
"lXhXVX(.` aXpXuXyXyXyXyXyXyXyXrXxXN.u x l l l l l l l l z d U iXfXsXdXdXdXdXdXdXdXpXbXI.s n c z z z z z z z x x C v k k h j j j j j j k h C 8XhXsXdXdXdXdXdXdXdXaXvX_.) kXlXkXlX",
"lXhXBX_.Q R.U.U.Y.Y.Y.Y.Y.Y.Y.I.!.q.J R T T T T T T T T T U ^ N.Z.V.C.C.C.C.C.C.C.B.G.9.N A A A A A A A A A A C H R T T T T T T T T T R Y E v.A.V.C.C.C.C.C.C.C.V.F.r.[ jXlXkXlX",
"lXhXVX(./ :X-X-X-X-X-X-X-X-X-X*X1XS.;X0X7X7X7X7X7X7X7X7X5XiXN.e h g g g g g g g g g a M V n N N N N N N N N N v J >X0X7X7X7X7X7X7X7X7X5XyXY.u g f f f f f f f f f d z X.gXlXkXlX",
"lXhXVX(._ uXtXrXrXrXrXrXrXrXrXeXdXY.>XtXqXwXwXwXwXwXwXwX9XfXZ.h N x z z z z z z z b n A m c l j j j j j j j x z G 2XrXqXwXwXwXwXwXwXwX9XsXE.l M m m m m m m m m m n N X.hXlXkXlX",
"lXhXVX(._ eX0X0X0X0X0X0X0X0X0X8XuXP.:XeX0X0X0X0X0X0X0X0X8XsXV.g x 0 p u i i i u p C c Z N l 0 p u i i i i i C z H 1XeX9X0X0X0X0X0X0X0X8XpXR.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z p B n m m m n B P z Z N j i B n m m m n N I l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z u n c v v v c n K z Z N k u n c v v v v n L l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z i m v b b b v m K z Z N k u m v b b b v n L l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z i m v b b b v m K z Z N k u m v b b b v n L l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z i m v b b b v m K z Z N k u m v b b b v n L l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z u n c v v v c n K z Z N k u n c v v v c n L l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(._ eXqX0XqXqXqXqXqXqXqX9XiXP.:XrX0XqXqXqXqXqXqXqX8XdXC.g z p B n m m m n B P z Z N j i B n m m m m N I l H 1XeX0XqXqXqXqXqXqXqX8XaXE.j n b b b b b b b b b v M X.hXlXkXlX",
"lXhXVX(.) qX8X8X8X8X8X8X8X8X8X7XtXL.-XwX8X8X8X8X8X8X8X8X6XpXV.g b Z P K L L L K P F x A N c C I L L L L L P H z J ,XqX8X8X8X8X8X8X8X8X6XuXT.k m b b b b b b b b b b M X.hXlXkXlX",
"lXhXVX(.` gXsXsXsXsXsXsXsXsXsXpXzXW.6XfXpXaXaXaXaXaXaXaXuXvXF.p v z l l l l l l l z l V v l l k k k k k k k l h D 0XfXpXaXaXaXaXaXaXaXiXxX/.f c x x x x x x x x x z n X.hXlXkXlX",
"lXhXBX_.W J.G.F.G.G.G.G.G.G.G.F.K.y.A.I.L.L.L.L.L.L.L.L.J.E.w.C H G G G G G G G G G F L I L P P P P P P P P P K R D.I.L.L.L.L.L.L.L.L.K.R.d.Z H G G G G G G G G G G F ..hXlXkXlX",
"lXhXNX[.A j f g g g g g g g g g a D 6.4.4.4.4.4.4.4.4.4.4.6.%.q.i.y.y.y.y.y.y.y.y.y.i.3.*X7X4X4X4X4X4X4X4X4X2XeXL.%.7.4.4.4.4.4.4.4.4.4.6.&.8.i.y.y.y.y.y.y.y.y.y.a.:.{ jXlXkXlX",
"lXhXBX].D N n m n n n n n n n m c I d.s.s.s.s.s.s.s.s.s.a.g.1.w.p.i.i.i.i.i.i.i.i.i.a.5.<XtXwXwXwXwXwXwXwXwX0XsXT.6.g.a.s.s.s.s.s.s.s.a.g.3.8.a.i.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m b b b b b b b b b b z L i.u.u.u.u.u.u.u.u.u.u.a.,.q.p.u.u.u.u.u.u.u.u.u.p.4.>XeX9X0X0X0X0X0X0X0X8XpXY.3.s.u.u.u.u.u.u.u.u.u.a.1.8.p.u.u.u.u.u.u.u.u.u.s.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b z L p.u.u.i.i.i.i.i.i.i.u.a.,.w.p.u.i.i.i.i.i.i.i.u.p.4.>XrX0XqXqXqXqXqXqXqX8XaXY.3.s.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m b b b b b b b b b n z L i.y.y.u.u.u.u.u.u.u.y.p.>.q.p.u.u.u.u.u.u.u.u.u.p.4.:XwX8X8X8X8X8X8X8X8X7XuXU.3.a.u.u.u.u.u.u.u.u.y.a.1.8.p.u.u.u.u.u.u.u.u.y.s.:.{ jXlXkXlX",
"lXhXBX].S b c c c c c c c c c v k L f.s.s.s.s.s.s.s.s.s.s.h.1.e.s.p.a.a.a.a.a.a.a.p.s.6.7XfXpXaXaXaXaXaXaXaXuXzX!.5.g.a.s.s.s.s.s.s.s.a.g.3.q.f.a.s.s.s.s.s.s.s.a.h.<.{ jXlXkXlX",
"lXhXBX].F S Z Z Z Z Z Z Z Z Z Z V I >.:.:.:.:.:.:.:.:.:.:.,.O.<.4.3.3.3.3.3.3.3.3.3.5.*.G.R.Y.Y.Y.Y.Y.Y.Y.Y.U.!.f.%.2.<.<.<.<.<.<.<.<.<.2.#.=.2.<.<.<.<.<.<.<.<.<.3.O.} hXlXkXlX",
"lXhXBX].D V M M M M M M M M M N m D b x v v v v v v v v v j U *X;X-X-X-X-X-X-X-X-X*X4XC.&.6.3.3.3.3.3.3.3.3.3.5.%.3.q.9.9.9.9.9.9.9.9.9.w.;.2.q.9.9.9.9.9.9.9.9.9.e.&.{ hXlXkXlX",
"lXhXBX].D n v v v v v v v v v v x Z m v x l z z z z z l v l T qXtXrXrXrXrXrXrXrXrXwXgXU.7.g.s.s.s.s.s.s.s.s.a.g.2.q.d.p.p.p.p.p.p.p.p.p.f.3.0.d.p.p.p.p.p.p.p.p.p.g.,.{ jXlXkXlX",
"lXhXBX].D m b b b b b b b b b b c A M k 0 i y u u u y i C k T 7XqX9X0X0X0X0X0X0X0X8XpXL.4.a.u.u.u.u.u.u.u.u.u.a.<.9.p.u.u.u.u.u.u.u.u.u.a.1.8.p.u.u.u.u.u.u.u.u.u.s.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h p N n m m m n B P h T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i m c v v v c m K j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i m v b b b v M L j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i m v b b b v M L j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i m v b b b v M L j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i m v v v v c m K j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D m v b b b b b b b b b c A N h i M b n n n b N P j T 7XwX0XqXqXqXqXqXqXqX8XaXL.4.s.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXBX].D M b b b b b b b b b b v A M x Z I L L L L K I H j T 5X9X8X8X8X8X8X8X8X8X6XiXK.4.a.u.u.u.u.u.u.u.u.y.a.<.9.p.u.u.u.u.u.u.u.u.y.a.1.8.p.u.u.u.u.u.u.u.u.y.s.:.{ jXlXkXlX",
"lXhXBX].S v x x x x x x x x x x z C b x c z x x x x x z x h T yXsXpXaXaXaXaXaXaXaXuXxXR.6.g.a.s.s.s.s.s.s.s.a.g.2.w.f.a.s.s.s.s.s.s.s.a.g.3.q.f.a.s.s.s.s.s.s.s.a.h.<.{ jXlXkXlX",
"lXhXBX].F F S S S S S S S S S S A J S Z A A A A A A A A S B R T.E.R.E.E.E.E.E.E.E.T./.d.&.3.1.1.1.1.1.1.1.1.1.3.#.;.3.1.1.1.1.1.1.1.1.1.3.$.-.3.1.1.1.1.1.1.1.1.1.4.O.} hXlXkXlX",
"lXhXVX(.( <X>X>X>X>X>X>X>X>X>X;X6Xm.3.y.e.r.r.r.r.r.r.r.e.i.$.f j k k k k k k k k k f Z 8.8.8.8.8.8.8.8.8.8.8.q.=.2.0.8.8.8.8.8.8.8.8.8.q.-.1.0.8.8.8.8.8.8.8.8.8.w.%.} hXlXkXlX",
"lXhXVX(._ yXrXwXqXqXqXqXqXqXqX0XgXD.7.s.i.p.p.p.p.p.p.p.u.f.*.c m v x c c c c c x b v H i.a.p.a.a.a.a.a.a.a.p.f.2.q.d.p.a.a.a.a.a.a.a.p.f.3.0.d.p.a.a.a.a.a.a.a.p.g.,.{ jXlXkXlX",
"lXhXVX(.) eX5X#X;X-X-X-X-X-X:XeXiXA.6.a.u.u.u.u.u.u.u.u.y.d.&.x x 0 u y y y y y u V x G y.i.u.u.u.u.u.u.u.u.u.a.<.9.p.u.u.u.u.u.u.u.u.u.a.1.8.p.u.u.u.u.u.u.u.u.y.s.>.{ jXlXkXlX",
"lXhXVX(.) tX4X,XtXwXwXwXwXqXyXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i N n n n m n N P l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XwX0X0X0X0X9XrXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i n v v v v c n K l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX9XtXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i m v b b b v m L l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX9XtXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i m v b b b v m L l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XeX0XqXqXqX9XtXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i m v b b b v m L l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XeX0X0X0X0X9XrXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k i m v v v v v m K l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) tX4X>XeXqXqXqXqX0XtXgXiXS.6.a.u.i.i.i.i.i.i.i.y.d.&.c k u M v b b b v M P l G y.i.u.i.i.i.i.i.i.i.u.s.<.9.p.u.i.i.i.i.i.i.i.u.s.1.8.a.u.i.i.i.i.i.i.i.u.d.>.{ jXlXkXlX",
"lXhXVX(.) wX6XuXkXhXjXjXjXhXlXpXyXA.5.a.u.u.u.u.u.u.u.u.y.s.&.x c V I L L L L K I H l G y.u.u.u.u.u.u.u.u.u.y.a.<.9.p.u.u.u.u.u.u.u.u.y.a.1.8.p.y.u.u.u.u.u.u.u.y.s.:.{ jXlXkXlX",
"lXhXVX(.' dXsXaXpXpXpXpXpXpXpXyXxXJ.9.h.d.d.d.d.d.d.d.d.s.j.-.l b b c c c c c c c c z G a.d.s.d.d.d.d.d.d.d.s.h.3.e.g.s.d.d.d.d.d.d.d.s.h.4.w.g.s.d.d.d.d.d.d.d.s.j.1.} jXlXkXlX",
"lXhXVX(.R !.W.W.W.W.W.W.W.W.W.E.(.t.$.<.>.>.>.>.>.>.>.>.:.1.} b M M M M M M M M M M n F :.>.>.>.>.>.>.>.>.>.:.<.O.&.,.>.>.>.>.>.>.>.>.:.<.O.%.,.>.>.>.>.>.>.>.>.:.1...' hXlXkXlX",
"lXhXNX X( ' _ _ _ _ _ _ _ _ _ _ ) ] } { { { { { { { { { { { | X.X.X.X.X.X.X.X.X.X.X.X...{ { { { { { { { { { { { } { { { { { { { { { { { { } } { { { { { { { { { { } ' :.hXlXkXlX",
"lXkXlXkXhXkXkXkXkXkXkXkXkXkXkXkXkXjXhXjXjXjXjXjXjXjXjXjXjXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXjXjXjXjXjXjXjXjXjXjXjXhXhXjXjXjXjXjXjXjXjXjXjXjXhXhXjXjXjXjXjXjXjXjXjXjXjXhXhXkXlXkXlX",
"lXlXkXlXzXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlX",
"lXlXkXlXbXbXbXbXbXbXbXnXnXnXnXnXnXnXnXnXnXnXnXnXmXMXMXMXMXMXnXbXbXbXbXbXbXmXMXMXMXmXMXbXlXkXlXlX",
"lXkXlXfX4X5X5X5X5X5X4X,X,X,X,X,X,X<X,X,X,X,X,X,X*X&X*X*X*X&X1X5X4X5X5X5X4X*X&X*X&X*X%X2XkXlXkXlX",
"lXjXbX4XK S D D D S K %.&.&.&.&.&.+.*.&.&.&.&.%.c.B.N.N.M.A.| B F D D A L v.V.N.N.N.N.5.pXxXkXlX",
"lXjXbX5XS l c c c l Z p.d.s.s.d.a.0.d.s.s.s.s.p.9XfXaXsXiXcX:.a b c c k F 9XrXwXeXeXjXx.rXcXkXlX",
"lXjXbX5XD c n b n c S t.u.u.u.u.y.7.i.u.u.u.u.t.>XqX8X8X6XiX-.f m b n x H -X4X8X7X0XaXh.tXcXkXlX",
"lXjXbX5XD c b b b x A t.i.u.u.i.y.7.i.u.i.i.i.t.<XeX0X0X8XaX-.d m b b z G :X8XqX0XeXdXj.tXcXkXlX",
"lXjXbX5XD v n b n c S t.u.u.u.u.y.7.i.u.i.i.i.t.>XqX8X9X7XiX-.f m b b z G ;X5X9X8XqXsXh.tXcXkXlX",
"lXjXbX5XA j z l z j V p.s.a.s.s.a.8.i.u.u.i.u.y.7XaXuXiXtXlX:.s n v v l F 2XaXfXdXgXjXk.tXcXkXlX",
"lXjXbX3XI J L L L J Y 2.4.3.4.4.2.2.u.y.y.y.u.w.~.}.[.[.'.oX+.z V N B n H |.*X$X%X$X&Xa.yXxXkXlX",
"lXjXmX*Xn.wX>X<X>X8X(.z b v v m s f.wX,X1X<X8X(.k j h h h l B b x c c z H #X<X:X>X:X1Xf.tXcXkXlX",
"lXjXMX&XV.rX4X7X4XfX}.z b b b m s z.hX0XeXqXaX Xk d l j z B B d g j h c H 3XyXeXrXeXiXl.rXcXkXlX",
"lXjXMX*XN.eX9XwX9XjX[.z b b b m s l.dX7X0X8XuX}.j k M b N Z N g b n n V H <XeX9X0X9XrXk.tXcXkXlX",
"lXjXMX&XN.eX7X0X7XhX[.z b b b m s l.dX8X0X9XuX}.j h b x n C N g x v c N H <XeX0X0X0XtXk.tXcXkXlX",
"lXjXMX&XB.tXwXtXwXlX{.c M m m B g l.aX6X9X7XtX{.j z N m V C B l N V B A K >XqX8X8X8XwXj.tXcXkXlX",
"lXjXmX*Xm.pXeXrXeXsX_.i s s s g 8 z.vXuXpXiXkX+Xx B Z C C N c s l l z g M 9XdXpXaXpXgXx.rXcXkXlX",
"lXjXmX-Xf.%X}. X|.OXT.s.x.l.l.l.z.:.&.=.*.*.=.o.B B N N B c $.n.h.k.j.z.u.#.=.*.*.*.$.%.dXzXkXlX",
"lXjXMX&XB.fXqXeXwXuX&X9XhXdXdXaXvX&.5 y r e p x b d g f l s c.mXaXdXsXxX$Xd f f f g y / hXlXkXlX",
"lXjXMX*XN.aX8X0X9XrX#X;XqX7X8X6XuX=.y m n b A Z x g b c N z f.aX5X8X6XrX{.b m m m M z ` hXlXkXlX",
"lXjXMX*XN.sX8XqX0XtX#X>XeX0X0X9XpX*.r n b v C V c j n v V l g.dX8XqX9XuX|.c b b b n k _ hXlXkXlX",
"lXjXMX*XM.pX7X9X8XeX@X:XwX9X9X7XiX*.r b b c C V c h n c B z g.sX7X9X8XyX|.v b b b n k ` hXlXkXlX",
"lXjXMX&XC.lXtXuXyXdX-X3XpXyXyXrXjX*.u Z V V C M z c B M A f j.zXeXyXtXfXOXz c c x v h _ hXlXkXlX",
"lXjXmX-Xa.+X[.{.{. XT._.+XXXXX.X%X#.m F S S Z D J J K K L B u.*X XXX.X#XU.C Z A Z S M ] gXzXkXlX",
"lXjXbX5XA l c x c l C 8.0.0.0.0.9.4.y.r.r.r.t.e.&X4X1X2X1X6Xk.5.q.0.0.q.4.0.y.t.t.t.r.>.aXzXkXlX",
"lXjXbX5XD c n b b c S u.a.p.p.p.i.8.p.i.i.i.i.y.2XtXwXeXwXuXm.t.a.p.p.s.q.e.a.i.i.p.u.<.aXxXkXlX",
"lXjXbX5XD c b b b x A t.i.u.u.i.y.7.i.u.u.u.u.t.,XeX9X0X9XrXb.e.i.u.u.p.0.w.i.u.u.i.y.,.aXxXkXlX",
"lXjXbX5XD c b b b x A t.i.u.u.i.y.7.i.u.u.i.i.t.<XeX0X0X0XrXb.e.i.u.u.p.0.w.p.u.u.i.y.,.aXxXkXlX",
"lXjXbX5XD x b v b x A r.u.y.y.u.t.8.a.p.p.p.p.u.,XwX9X0X9XrXb.e.p.i.u.p.0.w.p.i.i.i.u.,.aXxXkXlX",
"lXjXbX5XD c n b b c S a.f.d.d.d.d.5.0.0.0.0.0.0.4XuXrXrXrXpXn.w.i.u.y.i.9.q.i.y.u.u.y.,.aXxXkXlX",
"lXjXbX4XG M B B B M A ^ ^ ^ ^ / T 9.T.H.K.J.I.m.j.m.b.b.b.n.7.6.7.7.7.8.1.3.8.7.7.7.5.;.sXzXkXlX",
"lXjXbX5XD x b v v c M l u p p f y x.xXtXiXyXgX$X6.t.e.e.e.w.6.p.i.i.i.a.q.e.p.i.i.i.u.<.aXxXkXlX",
"lXjXbX5XD c b b b v B c h n c V z j.sX6X9X8XrX.Xq.a.i.i.p.i.7.i.u.u.u.p.0.w.p.u.u.i.y.,.aXxXkXlX",
"lXjXbX5XD c b b b v N c j n v V l k.dX8XqX9XyXXX0.p.u.u.i.u.7.i.u.i.u.p.0.w.p.u.u.i.y.,.aXxXkXlX",
"lXjXbX5XD c n b b v B c h b c B z j.sX6X9X8XtX.X0.p.u.u.u.y.7.i.u.u.u.p.0.w.i.u.u.u.y.,.aXxXkXlX",
"lXjXbX5XA k x z z l n x v C B D h z.zXrXuXyXfX#Xq.s.p.p.p.i.8.a.p.p.p.s.q.r.a.p.p.p.i.<.aXxXkXlX",
"lXjXbX4XL F H G G F H A A A A D c t.%X}. X|.OXU.4.q.0.0.0.9.1.q.0.0.0.q.3.5.q.0.0.0.8.:.aXzXkXlX",
"lXjXmX*Xv.9X-X:X;X4X`.7.t.r.r.e.p.Q h l l l k C 0.e.w.w.w.q.3.e.w.w.w.r.5.8.e.w.w.e.q.>.aXzXkXlX",
"lXjXMX&XV.rX4X8X5XdXOX0.a.i.i.u.f.~ i j j h b S y.a.i.p.p.i.8.p.p.p.i.a.q.e.a.p.p.p.i.<.aXxXkXlX",
"lXjXMX*XN.wX8XqX9XhXXX9.p.u.u.y.d.~ a n m n C S r.i.u.u.i.y.7.i.u.u.u.p.0.w.p.u.u.i.y.,.aXxXkXlX",
"lXjXMX&XN.eX7X0X7XgXXX9.p.u.u.y.d.~ p v v c B S r.i.u.u.i.u.7.i.u.u.u.p.0.w.p.u.u.i.y.,.aXxXkXlX",
"lXjXmX*XN.eX0XeXqXhXXX0.a.i.i.u.d.~ s N N M A D t.p.i.i.i.u.7.i.i.i.u.p.0.e.p.i.i.i.u.<.aXxXkXlX",
"lXjXMX%XN.jXaXdXsXkXoX8.i.y.y.t.s.R f M n m c M r.u.y.y.u.y.5.u.y.y.y.i.8.q.i.y.y.u.y.:.aXxXkXlX",
"lXjXbX2X5.x.h.j.h.l.i.:.<.,.,.,.1...) _ ) ) ) ] >.<.,.,.,.,.;.<.,.,.,.<.:.>.<.,.,.<.:.3.fXzXkXlX",
"lXkXlXkXpXrXtXtXtXtXyXaXaXaXaXaXaXfXhXhXhXhXhXgXaXaXaXaXaXaXsXaXaXaXaXaXaXaXaXaXaXaXaXfXlXkXkXlX",
"lXlXkXlXxXcXcXcXcXcXxXzXxXxXxXxXxXzXlXlXlXlXlXzXzXxXxXxXxXxXzXxXxXxXxXxXzXzXxXxXxXxXxXzXkXlXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"44 44 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXkXlXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlX",
"lXlXkXzXbXbXbXbXbXbXnXnXnXnXnXnXnXnXnXnXnXnXMXMXMXMXMXmXbXbXbXbXbXnXMXMXMXMXMXnXlXkXlXlX",
"lXkXzXfX2X3X3X3X3X3X,X:X:X:X:X>X>X:X:X:X:X:X&X%X%X&X%X-X3X3X3X3X3X,X%X&X&X&X$X,XkXlXkXlX",
"lXjXbX2XF C Z Z Z C o.:.-.-.;.&.%.;.-.-.-.=.C.J.G.F.I.i.M A Z A m [ P.F.G.F.J.w.rXcXkXlX",
"lXjXbX3XC z v c c z 3.h.a.s.f.y.r.f.s.s.s.a.9XfXaXiXxX~.d b c b s &.gX0XrXwXzXC.0XvXkXlX",
"lXjXbX3XZ v n b b c <.a.y.u.i.w.q.i.u.u.u.y.>XqX8X6XiXY.h m b m g $.0X6X9X8XfXm.qXvXkXlX",
"lXjXbX3XZ c b b b c <.s.u.u.p.w.q.p.u.i.u.y.<XeX0X8XaXT.g n b m f $.wX6X9X8XgXm.qXvXkXlX",
"lXjXbX3XA v n n n v 1.s.u.u.p.w.e.s.p.p.p.i.1XrXqX9XsXT.g n v n d $.yXeXuXyXlXM.qXvXkXlX",
"lXjXbX3XN h l k k h <.s.u.u.p.w.5.q.0.0.0.0.,XwX9X7XpXY.j M m N j +.0X5X6X6X0Xv.qXvXkXlX",
"lXjXmX=Xd.'.Q.!.~.!.~ A G G F H Y.XX{.[.XXL.Y T Y Y T U M m n M k O.:X+X#X@X=Xl.wXcXkXlX",
"lXjXMX%XP.sX0XqXyXaXY g c x z v *XdXtXtXfX+Xd u s p j m l d h j g $.fXeXrXeXsXB.0XvXkXlX",
"lXjXMX&XD.wX9X8XrXeXT l n n v m +XrX8X8XtX Xk x N n Z C k x m M v #.iX8X0X8XyXM.qXvXkXlX",
"lXjXMX&XF.wX7X7XeXrXT l n b v m +XtX8X8XyX Xj j b x B V l l b b c #.iX8X0X8XyXM.qXvXkXlX",
"lXjXMX%XH.sXiXiXfXuXT j b v c n %XpXeXwXaXoXk v V N Z B l n B V v #.dXwXrXwXsXN.0XvXkXlX",
"lXjXMX&XB.7X,X<X1X;XR x M m n M ].3X:X:X4X/.n V C C B B M B V Z l O.5X-X:X;X3Xx.qXcXkXlX",
"lXjXmX*XM.2X%X*X-XOX/.%X+X+X%X].J N V B V S N c c v k ~ #X+X+XoX;Xg.v D A S N ( sXzXkXlX",
"lXjXMX%XJ.gXwXrXuX4X=XaXtXtXpX3XN u j f x N z d k j k ( uXyXyXeXlXM.i b x c h ! dXzXkXlX",
"lXjXMX%XG.pX8X0XwX1X#XeX9X8XwX:XV j N b C C z l m m m ( qX9X9X7XsXn.d M b n l ~ dXzXkXlX",
"lXjXMX%XF.pX7X9XqX<X#XeX9X9XeX:XV f n x B C x k b v n ( qX9X9X7XsXn.d m b n l ~ dXzXkXlX",
"lXjXMX%XL.kXtXuXpX7X=XpXtXtXpX2XB l V M C N l c N N v ~ iXtXtXeXlXM.p b c v h ! dXzXkXlX",
"lXjXmX*Xz.#X}.|..X_.~.$XOXOX#X`.J Z D D A S J K K P S ' @X+XOXoX;Xf.v S Z A M ( sXzXkXlX",
"lXjXbX3XC z v c c z -.r.0.q.w.6.8.t.r.r.r.e.&X4X1X<X8X!.4.e.q.q.w.4.r.t.t.t.t.,.uXxXkXlX",
"lXjXbX3XZ c b b b c 1.f.i.p.a.r.w.a.i.i.i.u.2XtXwXqXaX].q.s.p.p.a.9.u.p.i.i.p.1.uXxXkXlX",
"lXjXbX3XZ c b b b c <.s.u.u.p.w.q.p.u.u.u.y.<XwX9X8XyX`.0.p.u.u.i.8.y.i.u.u.i.1.uXxXkXlX",
"lXjXbX3XZ c b b b c <.a.y.y.i.q.q.p.i.i.i.y.,XwX8X8XyX_.9.p.u.u.i.8.y.i.u.u.i.<.uXxXkXlX",
"lXjXbX3XZ x b v v x 3.h.s.s.f.y.0.u.t.y.t.t.6XaXuXyXgX}.q.s.p.p.a.9.u.p.p.p.p.1.yXxXkXlX",
"lXjXbX2XS m N N N m O.<.>.>.>.=.t.h.d.f.g.i.Q.].`._.}.A.3.q.9.9.0.1.8.9.9.9.9.:.uXxXkXlX",
"lXjXbX3XA v m n b M n f f f g v oXeX7X7XeXXX4.q.0.9.q.3.w.t.t.r.t.6.e.t.t.t.t.,.uXxXkXlX",
"lXjXbX3XZ x b v v n m f c z m V @XuX0X0XyX+Xe.s.p.p.s.q.t.p.i.i.p.9.u.p.i.i.p.1.uXxXkXlX",
"lXjXbX3XZ c b b v m n h m b B V +XyX9X9XtXOXq.p.u.u.p.9.t.i.u.u.i.8.y.i.u.u.i.1.uXxXkXlX",
"lXjXbX3XA b m m n N m h m v B C oXeX7X7XeXoXq.p.u.u.p.9.r.i.u.u.i.8.y.i.u.u.i.1.uXxXkXlX",
"lXjXbX3Xm s g f d j x z N m N b :XlXaXaXkX;Xw.a.i.i.a.0.t.p.i.i.p.9.u.p.i.i.p.1.uXxXkXlX",
"lXjXnX,X[ &.$.$.$.@.~ W W W W E f.B.m.m.N.f.4.9.8.8.9.1.6.9.8.8.9.1.7.9.8.8.8.:.uXxXkXlX",
"lXjXMX%XP.gX0XwXtXrXg.s.d.s.f.u.l w t r t b e.u.y.y.u.8.e.u.y.y.u.7.t.y.y.y.y.<.uXxXkXlX",
"lXjXMX&XF.0X6X6XwX9Xi.y.u.y.i.w.N j m v B G r.p.i.i.p.9.t.p.i.i.p.9.u.i.i.i.i.1.uXxXkXlX",
"lXjXMX&XG.rX9X9XyXqXp.u.i.u.p.e.m h m v N D r.i.u.u.p.9.t.i.u.u.i.8.y.i.u.u.i.1.uXxXkXlX",
"lXjXMX&XF.wX9X8XtX0Xp.u.i.u.p.e.M j M b V F r.i.u.u.p.9.t.i.u.u.i.8.y.i.u.u.i.1.uXxXkXlX",
"lXjXMX$XJ.zXfXgXkXrXa.u.i.u.p.e.v x M m n N t.p.i.i.p.9.t.p.i.i.p.8.y.i.i.i.i.,.yXxXkXlX",
"lXjXnX,Xw.C.m.m.M.b.2.<.1.<.1.>./ ! ! ! Q ( ,.1.1.1.1.:.,.1.1.1.1.:.<.1.1.1.,.<.pXxXkXlX",
"lXkXlXkXrX0XqXqXqXqXyXuXuXuXuXuXdXdXdXdXdXdXuXuXuXuXuXuXuXuXuXuXuXuXuXuXuXuXyXpXkXlXkXlX",
"lXlXkXlXcXvXvXvXvXvXxXxXxXxXxXxXzXzXzXzXzXzXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXlXkXlXlX",
"lXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_4[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"kXlXxXxXxXxXxXcXcXcXcXcXcXcXcXcXbXbXbXbXvXxXxXxXxXvXbXbXbXvXlXkX",
"lXkXiXiXiXiXiXeXeXeXeXeXeXeXeXeX8X7X7X6XeXpXiXiXiX9X7X8X6XwXkXlX",
"xXiX_ J U L E 4.5.5.5.<.5.5.5.3.G.R.U.~.7.F U I P B.E.P.R.x.wXvX",
"xXiXJ g x j B y.p.p.i.q.p.p.p.y.3XsXrXxXf.y c l l XXiX0XjX!.6XbX",
"xXiXU x M v S t.u.u.y.0.i.i.i.t.=XqX4XpXs.d N n b ].wX5XsXR.7XbX",
"xXpXK g x j V i.s.a.a.q.u.u.u.t.2XaXeXzXh.a m v c |.aXrXlXW.6XbX",
"xXuX^ H P J Y 4.6.5.4.6.s.p.a.y.(.OX}.&X9.j B M n /.5X>X6XG.8XbX",
"bX7XP.6X;X7X[.v b M d i.rX,X7X@XM f j z N x z z b `.7X>X7XK.8XbX",
"bX7XY.rX8XaX+Xx b m a f.gX9XyX:Xn k c N N h c v M .XpX0XaXR.7XbX",
"bX7XI.eX7XaXOXb M B g s.pX4XqX*Xn l b B B z m N C {.rX5XtXU.7XbX",
"bX7XU.pXeXgX.Xp s g 7 f.mXiXjX4XB m C Z c a k l h #XzXiXxX~.6XbX",
"bX8XS.>X$X-X).u.f.d.f.6.4.4.5.<.C m N z ' l.s.f.i.3.6.5.6.>.rXcX",
"bX7XT.iX9XrX>XeXhXpXmX4.1 p y l z h z a q.nXpXgXyXZ u g y F pXxX",
"bX7XY.uX7XwX-X>X9X4XiX4.p B N S z x M l 6.iX4X9X1XP c N c U iXxX",
"bX7XE.dXwXuX<X4XyXqXjX5.y N m C l x M j 7.hXqXyX7XK k b k P iXxX",
"bX8XF.<X&X:X X@X>X=X6X2.z D Z C C S G n 3.6X=X>X%XP b V b Y iXxX",
"xXiXR m C N H e.y.t.t.6.0.0.0.9. X;X%X,XA.0.y.y.w.7.w.q.w.1.eXcX",
"xXiXP j v l C y.i.i.u.q.a.p.a.u.<XiXwXsXU.q.p.p.r.e.a.p.a.6.eXcX",
"xXiXI z m c A r.u.y.y.0.p.i.p.y.=XqX6XrXL.q.p.i.r.w.i.u.i.4.eXcX",
"xXiXI l n x A s.g.f.g.0.w.w.w.q.2XsXtXgXY.q.p.p.r.w.p.u.p.5.eXcX",
"xXiXY v N m Z | | | ' 8.H.Z.D.M.S.U.L.Y.f.7.q.q.7.5.q.0.q.<.eXcX",
"xXiXI l n v M g p g r f.lXwXpX1X0.q.q.q.7.u.u.i.r.w.i.u.i.5.eXcX",
"xXiXI l n v M x v N z d.aX5XwX-Xy.p.p.p.q.u.u.i.r.w.p.u.p.5.eXcX",
"xXiXI l n v M z v N k f.gX9XtX>Xy.p.i.p.q.i.i.p.t.e.p.i.a.5.eXcX",
"xXiXP l b c n n N Z j p.yX2X8X%Xw.r.r.r.7.r.r.t.q.9.t.r.t.3.eXcX",
"vX9XB.XX'..XE.2.5.4.8.] A G F P 7.e.w.w.5.w.w.e.9.7.e.w.e.2.eXcX",
"bX7XE.iXqXdX:Xr.d.p.k./ t k j N q.a.i.p.q.i.p.p.t.e.a.i.a.5.eXcX",
"bX8XP.0X5XtX%Xq.i.y.d.) f M M D 0.p.u.u.0.u.u.i.r.w.i.u.i.5.eXcX",
"bX6XR.jXaXxX>Xe.a.u.h.^ d m n N q.s.i.p.q.i.p.a.t.e.a.i.a.5.wXvX",
"vXwXx.!.T.Q.A.2.5.4.8.{ L T U Y 1.6.4.5.<.5.5.5.3.2.5.5.5.1.tXcX",
"lXkXwX6X7X6X8XeXeXeXeXyXiXiXiXiXeXeXeXeXeXeXeXeXeXeXeXeXwXtXkXlX",
"kXlXvXbXbXbXbXcXcXcXvXcXxXxXxXxXcXcXcXcXcXcXcXcXcXcXcXcXvXcXlXkX"
};

/* XPM */
static const char *const xpm_icon_5[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"kXuXuXtXrXrXrXrXwXqXtXuXtXqXeXkX",
"uX[ G &.s.r.i.a.}.-X&.M w.>X'.rX",
"uXC 4 [ c.r.8.r.eXNXo.7 8.xX=XqX",
"rXf.l.:.~ ;.!.K.6.9.R s 7.eX}.wX",
"qX=XAX0.= { VX9Xl s k q q.NX-XqX",
"wX}.wXk.( <.R.A.D M _  .q.Q.D.eX",
"qX&XrX3XvXR.8 l z s E.AXh.4 G uX",
"wX|.<X+X8XG.b G S B G.iXd.g W yX",
"yXQ v +.g.e.w.r.@X<Xv.u.e.0.r.rX",
"uXP a X.l.r.q.y.5XdXm.w.r.i.i.rX",
"yXT v K H #..X^.b.m.y.r.q.e.t.rX",
"uXA y h e ..VXtXu.w.r.p.r.u.i.rX",
"tX0.8.#.) #.j.s.r.r.q.r.q.e.t.rX",
"qX:XNXE.s.-.6 j q.u.e.u.e.y.u.rX",
"eX`.,XC.t.1.I ~ e.i.t.i.t.u.a.yX",
"kXrX0XeXrXtXuXyXrXrXrXrXrXrXyXkX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
    xpm_icon_4,
    xpm_icon_5,
};
const int n_xpm_icons = 6;
